import Foundation

/// 🔬 العلوم — بالعربية. مأخوذ عن البنك العبريّ (310 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let science: [BankQuestion] = [
        BankQuestion(prompt: "🕷️\nكم رِجلًا للعنكبوت؟", correctAnswer: "8", distractors: ["6", "10", "4"], grades: 0...2),
        BankQuestion(prompt: "🌱\nمن أين تحصل النباتات على الطاقة اللازمة لصنع غذائها؟", correctAnswer: "من الشمس", distractors: ["من التربة", "من الهواء", "من القمر"], grades: 2...4),
        BankQuestion(prompt: "🌍\nكم يومًا في الأسبوع؟", correctAnswer: "7", distractors: ["5", "6", "8"], grades: 0...2),
        BankQuestion(prompt: "🌈\nكم لونًا في قوس قزح؟", correctAnswer: "7", distractors: ["5", "6", "10"], grades: 0...2),
        BankQuestion(prompt: "👂\nبأيّ عضو نسمع؟", correctAnswer: "الأذنان", distractors: ["العينان", "الأنف", "الفم"], grades: 0...2),
        BankQuestion(prompt: "🐝\nأيّ حيوان يصنع العسل؟", correctAnswer: "النحلة", distractors: ["النملة", "الذبابة", "الفراشة"], grades: 0...2),
        BankQuestion(prompt: "❄️\nماذا يحدث للماء في البرد الشديد؟", correctAnswer: "يتجمّد", distractors: ["يتبخّر", "يختفي", "يسخن"], grades: 2...4),
        BankQuestion(prompt: "🌡️\nبأيّ أداة نقيس درجة الحرارة؟", correctAnswer: "بمقياس الحرارة (الترمومتر)", distractors: ["بميزان الوزن", "بالمسطرة", "بالساعة"], grades: 2...4),
        BankQuestion(prompt: "🦷\nكم سنًّا للإنسان البالغ عند اكتمال أسنانه كلّها بما فيها ضروس العقل؟", correctAnswer: "32", distractors: ["20", "28", "40"], grades: 2...4),
        BankQuestion(prompt: "🦴\nكم يومًا في السنة؟", correctAnswer: "365", distractors: ["360", "350", "400"], grades: 2...4),
        BankQuestion(prompt: "🌙\nكم يستغرق القمر ليُتمّ دورة كاملة حول الأرض؟", correctAnswer: "نحو شهر", distractors: ["يوم واحد", "سنة", "أسبوع"], grades: 4...6),
        BankQuestion(prompt: "☀️\nما أقرب نجم (جِرم يُصدر ضوءه بنفسه) إلى الأرض؟", correctAnswer: "الشمس", distractors: ["القمر", "المرّيخ", "المشتري"], grades: 4...6),
        BankQuestion(prompt: "🐠\nأين تتنفّس الأسماك؟", correctAnswer: "في الماء", distractors: ["في الهواء", "في التراب", "في الشجر"], grades: 0...2),
        BankQuestion(prompt: "🦋\nإلى ماذا تتحوّل اليرقة بعد خروجها من الشرنقة؟", correctAnswer: "إلى فراشة", distractors: ["إلى نحلة", "إلى عصفور", "إلى عنكبوت"], grades: 0...2),
        BankQuestion(prompt: "🌋\nما المادّة المنصهرة الحارّة التي تخرج من البركان؟", correctAnswer: "الحمم (اللابة)", distractors: ["ماء بارد", "ثلج", "رمل"], grades: 2...4),
        BankQuestion(prompt: "💨\nممّ يتكوّن الهواء في معظمه؟", correctAnswer: "من غازات", distractors: ["من ماء سائل", "من تراب", "من لا شيء"], grades: 2...4),
        BankQuestion(prompt: "🌊\nما الذي يصنع الأمواج في البحر عادةً؟", correctAnswer: "الريح", distractors: ["الأسماك", "الشمس", "الحجارة"], grades: 2...4),
        BankQuestion(prompt: "🦷\nما اسم المادّة الصلبة التي تغطّي السنّ من الخارج؟", correctAnswer: "المينا", distractors: ["السكّر", "الجير", "الحديد"], grades: 4...6),
        BankQuestion(prompt: "🚀\nما اسم الكوكب الأحمر؟", correctAnswer: "المرّيخ", distractors: ["المشتري", "زُحل", "الزهرة"], grades: 4...6),
        BankQuestion(prompt: "🧠\nأيّ عضو يساعدنا على التفكير؟", correctAnswer: "الدماغ", distractors: ["القلب", "المعدة", "الرئتان"], grades: 0...2),
        BankQuestion(prompt: "في أيّ درجة حرارة يغلي الماء؟", correctAnswer: "100 درجة مئوية", distractors: ["50 درجة مئوية", "80 درجة مئوية", "200 درجة مئوية"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما أكبر كوكب في المجموعة الشمسية؟", correctAnswer: "المشتري", distractors: ["المرّيخ", "زُحل", "الزهرة"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ماذا يفعل القلب في الجسم؟", correctAnswer: "يضخّ الدم إلى الجسم كلّه", distractors: ["يهضم الطعام", "يُرسل الأفكار", "ينقّي الهواء"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "كيف تصنع النباتات غذاءها بنفسها؟", correctAnswer: "بالبناء الضوئي — من ضوء الشمس", distractors: ["تمتصّ الغذاء من الحشرات", "تأكل التراب", "تشتريه من الدكّان"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كم عظمة في جسم الإنسان البالغ تقريبًا؟", correctAnswer: "206", distractors: ["100", "500", "50"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما الذي يجذبنا إلى الأسفل نحو الأرض؟", correctAnswer: "قوّة الجاذبية", distractors: ["الريح", "الكهرباء", "مغناطيس في السماء"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "أيّ غاز نستنشقه ويحتاج إليه جسمنا كي نحيا؟", correctAnswer: "الأكسجين", distractors: ["ثاني أكسيد الكربون", "الهيدروجين", "الهيليوم"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "أيّ هذه الحيوانات من الثدييات؟", correctAnswer: "الدلفين", distractors: ["القرش", "التمساح", "الضفدع"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كم يستغرق كوكب الأرض ليُتمّ دورة كاملة حول الشمس؟", correctAnswer: "سنة", distractors: ["يوم", "شهر", "أسبوع"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "ما حالة الماء في الجليد؟", correctAnswer: "صلبة", distractors: ["سائلة", "غازية", "بلازما"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "بأيّ عضو في الجسم نرى؟", correctAnswer: "العينان", distractors: ["الأذنان", "الأنف", "اليدان"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "أيّ حاسّة موضعها الأذنان؟", correctAnswer: "السمع", distractors: ["البصر", "التذوّق", "الشمّ"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "ماذا يحتاج النبات كي ينمو؟", correctAnswer: "ماء وضوء وهواء", distractors: ["الظلام فقط", "الرمل فقط", "سكّر وملح"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "ماذا نسمّي صغير الكلب؟", correctAnswer: "جَرْو", distractors: ["هِرّة صغيرة", "كتكوت", "عِجل"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "ماذا نسمّي صغير الدجاجة؟", correctAnswer: "كتكوت", distractors: ["عِجل", "جَدْي", "جَرْو"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "أين يعيش النحل؟", correctAnswer: "في الخليّة", distractors: ["في الجُحر", "في القنّ", "في الإسطبل"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "ماذا تأكل البقرة؟", correctAnswer: "العشب", distractors: ["اللحم", "السمك", "الحشرات"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "في أيّ فصل يهطل المطر أكثر ما يهطل في إسرائيل؟", correctAnswer: "الشتاء", distractors: ["الصيف", "الربيع", "الخريف"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "متى نرى النجوم في السماء؟", correctAnswer: "في الليل", distractors: ["عند الظهيرة", "في الصباح", "بعد الظهر"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "من أين يفقس الكتكوت؟", correctAnswer: "من البيضة", distractors: ["من بذرة", "من زهرة", "من ورقة"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "أيّ جزء من النبات يوجد داخل التربة؟", correctAnswer: "الجذر", distractors: ["الورقة", "الزهرة", "الساق"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "ما الذي يُضيء الأرض ويدفّئها في النهار؟", correctAnswer: "الشمس", distractors: ["القمر", "النجوم", "الغيوم"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "الجليد هو ماء في الحالة:", correctAnswer: "الصلبة", distractors: ["السائلة", "الغازية", "البلازما"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "الحليب مادّة في الحالة:", correctAnswer: "السائلة", distractors: ["الصلبة", "الغازية", "البلازما"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "عندما يغلي الماء يتحوّل إلى:", correctAnswer: "بخار (غاز)", distractors: ["جليد", "ثلج", "مادّة صلبة"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "ماذا يحدث لمياه البحر عندما تُسخّنها الشمس؟", correctAnswer: "تتبخّر", distractors: ["تتجمّد", "تختفي إلى الأبد", "تتحوّل كلّها إلى ملح"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "من أين يأتي المطر؟", correctAnswer: "من الغيوم", distractors: ["من الشمس", "من النجوم", "من الجبال"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "أيّ عضو يضخّ الدم في الجسم؟", correctAnswer: "القلب", distractors: ["الرئتان", "المعدة", "الدماغ"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "بأيّ عضو نتنفّس؟", correctAnswer: "بالرئتين", distractors: ["بالقلب", "بالكبد", "بالمعدة"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "ما وظيفة الهيكل العظمي في الجسم؟", correctAnswer: "يحمل الجسم ويحمي الأعضاء", distractors: ["يهضم الطعام", "يضخّ الدم", "يرى في الظلام"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "أيّ مادّة شفّافة؟", correctAnswer: "الزجاج", distractors: ["الخشب", "الحديد", "الحجر"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "أيّ مادّة ينجذب إليها المغناطيس؟", correctAnswer: "الحديد", distractors: ["الخشب", "البلاستيك", "الزجاج"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "ماذا يأكل الأرنب في السلسلة الغذائية؟", correctAnswer: "النباتات", distractors: ["الحشرات", "الأسماك", "اللحم"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "من يقع في بداية السلسلة الغذائية؟", correctAnswer: "النباتات", distractors: ["الأسود", "النسور", "بنو البشر"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "أيّ طاقة تتلقّاها الأرض من الشمس؟", correctAnswer: "طاقة الضوء والحرارة", distractors: ["طاقة الصوت", "طاقة الريح", "طاقة من البطّاريات"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "أيّ مادّة تُوصّل الكهرباء؟", correctAnswer: "النحاس", distractors: ["المطّاط", "البلاستيك", "الخشب"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "أيّ مادّة عازلة للكهرباء؟", correctAnswer: "المطّاط", distractors: ["الحديد", "النحاس", "الألمنيوم"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "كم كوكبًا يدور حول الشمس؟", correctAnswer: "ثمانية", distractors: ["سبعة", "تسعة", "عشرة"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "ما أقرب كوكب إلى الشمس؟", correctAnswer: "عُطارد", distractors: ["الزهرة", "المرّيخ", "المشتري"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "أيّ كوكب يُسمّى الكوكب الأحمر؟", correctAnswer: "المرّيخ", distractors: ["المشتري", "زُحل", "الزهرة"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "أيّ غاز يحتاجه جسمنا من الهواء كي نحيا؟", correctAnswer: "الأكسجين", distractors: ["ثاني أكسيد الكربون", "الهيدروجين", "النيتروجين"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "أيّ غاز تزداد نسبته في الهواء الذي نزفره؟", correctAnswer: "ثاني أكسيد الكربون", distractors: ["الأكسجين", "الهيدروجين", "الهيليوم"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "ما وظيفة الدم في الجسم؟", correctAnswer: "ينقل الأكسجين والغذاء إلى الجسم كلّه", distractors: ["يهضم الطعام", "يصنع الضوء", "ينقّي الهواء"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "ما النظام البيئي؟", correctAnswer: "كائنات حيّة ونباتات تعيش معًا في بيئتها", distractors: ["مجموعة حجارة في الصحراء", "آلة تُنتج الكهرباء", "نوع من الطقس"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "فيمَ تُستخدم طاقة الريح في التوربينات؟", correctAnswer: "في توليد الكهرباء", distractors: ["في تدفئة الشمس", "في صناعة المطر", "في تجميد الماء"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "لماذا يُضيء القمر في الليل؟", correctAnswer: "لأنّه يعكس ضوء الشمس", distractors: ["لأنّه يحترق مثل الشمس", "لأنّه يصنع ضوءًا خاصًّا به", "لأنّ النجوم تُضيئه"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "ماذا يُنتج النبات في عملية البناء الضوئي؟", correctAnswer: "سكّرًا وأكسجينًا", distractors: ["ملحًا وماءً", "ثاني أكسيد الكربون فقط", "تربة جديدة"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "ماذا يحتاج النبات كي يقوم بالبناء الضوئي؟", correctAnswer: "ضوءًا وماءً وثاني أكسيد الكربون", distractors: ["ظلامًا تامًّا", "أكسجينًا فقط", "ملحًا وسكّرًا"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "في أيّ جزء من النبات يحدث البناء الضوئي أساسًا؟", correctAnswer: "في الأوراق", distractors: ["في الجذور", "في الأزهار", "في البذور"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "بمَ تساعدنا الرافعة؟", correctAnswer: "على رفع حِمل ثقيل بسهولة", distractors: ["على تسخين الماء", "على الرؤية من بعيد", "على السمع بشكل أفضل"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "فيمَ تُستخدم البَكَرة؟", correctAnswer: "في رفع الأشياء بواسطة حبل", distractors: ["في قياس درجة الحرارة", "في صناعة الضوء", "في تبريد الطعام"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "ما الذي ينتقل أسرع من الصوت بكثير؟", correctAnswer: "الضوء", distractors: ["الريح", "الأمواج", "الغيوم"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "لماذا نرى البرق قبل أن نسمع الرعد؟", correctAnswer: "لأنّ الضوء أسرع من الصوت", distractors: ["لأنّ الرعد يحدث بعده بوقت طويل", "لأنّ الصوت أسرع من الضوء", "لأنّ البرق أقرب إلينا"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "عبر أيّ وسط ينتقل الصوت أسرع؟", correctAnswer: "عبر المواد الصلبة", distractors: ["عبر الهواء", "عبر الفراغ (الفضاء)", "عبر الماء"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "لماذا من المهمّ أن نعيد التدوير؟", correctAnswer: "كي نُقلّل التلوّث والنفايات", distractors: ["كي ننتج نفايات أكثر", "كي نلوّث البحر", "لا سبب، إنّها عادة فقط"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "أيّ حاوية مخصّصة لإعادة تدوير الورق في إسرائيل؟", correctAnswer: "الحاوية الزرقاء", distractors: ["الحاوية الخضراء", "الحاوية البرتقالية", "الحاوية الحمراء"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "أيّ جهاز نستخدمه كي نرى البكتيريا؟", correctAnswer: "المجهر", distractors: ["المنظار المقرّب", "التلسكوب", "العدسة المكبّرة"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "ما الذي يجعل عجين الخبز ينتفخ؟", correctAnswer: "الخميرة", distractors: ["الملح", "الماء البارد", "مزيد من الطحين"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🌱\nماذا تحتاج النباتات كي تنمو؟", correctAnswer: "شمس وماء وتربة", distractors: ["هواء وكعكة", "رمل فقط", "ثلج فقط"], grades: 0...2),
        BankQuestion(prompt: "💧\nكم نسبة سطح الأرض المغطّاة بالماء؟", correctAnswer: "نحو 71%", distractors: ["20%", "50%", "100%"], grades: 4...6),
        BankQuestion(prompt: "🧊\nماذا يحدث للماء عندما تصل حرارته إلى 0 درجة مئوية؟", correctAnswer: "يتجمّد", distractors: ["يختفي", "يغلي", "يُغيّر لونه"], grades: 2...4),
        BankQuestion(prompt: "🌡️\nفي أيّ درجة حرارة يغلي الماء؟", correctAnswer: "100°C", distractors: ["50°C", "200°C", "30°C"], grades: 4...6),
        BankQuestion(prompt: "🌍\nكم عدد الصفائح التكتونية الكبرى؟", correctAnswer: "7 صفائح كبرى", distractors: ["3", "2", "20"], grades: 4...6),
        BankQuestion(prompt: "🦴\nكم عظمة في جسم الإنسان البالغ؟", correctAnswer: "206", distractors: ["150", "100", "300"], grades: 2...4),
        BankQuestion(prompt: "👀\nكم لونًا في قوس قزح؟", correctAnswer: "7", distractors: ["5", "6", "10"], grades: 0...2),
        BankQuestion(prompt: "🐅\nأيّ عضو يضخّ الدم؟", correctAnswer: "القلب", distractors: ["الرئتان", "الكبد", "الدماغ"], grades: 2...4),
        BankQuestion(prompt: "🌬️\nأيّ غاز يحتاجه جسمنا من الهواء الذي نتنفّسه؟", correctAnswer: "الأكسجين", distractors: ["الهيدروجين", "ثاني أكسيد الكربون", "الأوزون"], grades: 2...4),
        BankQuestion(prompt: "🌙\nكم يستغرق القمر ليُتمّ دورة كاملة حول الأرض؟", correctAnswer: "نحو 27 يومًا", distractors: ["يوم واحد", "سنة", "100 يوم"], grades: 4...6),
        BankQuestion(prompt: "☀️\nكم يستغرق ضوء الشمس حتى يصل إلينا؟", correctAnswer: "8 دقائق", distractors: ["ثانية واحدة", "ساعة", "يوم"], grades: 4...6),
        BankQuestion(prompt: "🪐\nأيّ كوكب هو الأكبر؟", correctAnswer: "المشتري", distractors: ["الزهرة", "المرّيخ", "الأرض"], grades: 4...6),
        BankQuestion(prompt: "🌎\nكم كوكبًا في المجموعة الشمسية؟", correctAnswer: "8", distractors: ["7", "9", "10"], grades: 4...6),
        BankQuestion(prompt: "🔴\nأيّ كوكب لونه أحمر؟", correctAnswer: "المرّيخ", distractors: ["الزهرة", "المشتري", "زُحل"], grades: 4...6),
        BankQuestion(prompt: "🌟\nما أقرب جِرم إلى الأرض في المجموعة الشمسية؟", correctAnswer: "القمر", distractors: ["المرّيخ", "الزهرة", "الشمس"], grades: 4...6),
        BankQuestion(prompt: "🌳\nأيّ غاز تمتصّه النباتات كي تصنع غذاءها؟", correctAnswer: "ثاني أكسيد الكربون", distractors: ["الأكسجين", "بخار الماء", "النيتروجين"], grades: 4...6),
        BankQuestion(prompt: "🌳\nأيّ غاز تُطلقه النباتات في أثناء البناء الضوئي؟", correctAnswer: "الأكسجين", distractors: ["ثاني أكسيد الكربون", "النيتروجين", "الهيدروجين"], grades: 4...6),
        BankQuestion(prompt: "🐝\nكيف تنتقل حبوب اللقاح بين الأزهار؟", correctAnswer: "بواسطة النحل", distractors: ["بواسطة المطر", "بواسطة التراب", "بواسطة الشمس"], grades: 0...2),
        BankQuestion(prompt: "❄️\nما صفة الجليد؟", correctAnswer: "بارد وصلب", distractors: ["حارّ وطريّ", "سائل ودافئ", "أصفر وعطِر"], grades: 0...2),
        BankQuestion(prompt: "🔥\nماذا تحتاج النار كي تشتعل؟", correctAnswer: "أكسجين ووقود", distractors: ["ماء فقط", "رمل", "برد"], grades: 2...4),
        BankQuestion(prompt: "🌜\nما السبب الرئيسي لحدوث المدّ والجزر؟", correctAnswer: "القمر", distractors: ["الريح", "الشمس", "الأسماك"], grades: 4...6),
        BankQuestion(prompt: "🦟\nكم رِجلًا للحشرة؟", correctAnswer: "6", distractors: ["4", "8", "10"], grades: 0...2),
        BankQuestion(prompt: "🐍\nالأفاعي هي...؟", correctAnswer: "زواحف", distractors: ["ثدييات", "طيور", "أسماك"], grades: 2...4),
        BankQuestion(prompt: "🐬\nالدلافين هي...؟", correctAnswer: "ثدييات", distractors: ["أسماك", "زواحف", "طيور"], grades: 2...4),
        BankQuestion(prompt: "🦇\nالخفافيش هي...؟", correctAnswer: "ثدييات", distractors: ["طيور", "حشرات", "زواحف"], grades: 2...4),
        BankQuestion(prompt: "🐢\nالسلاحف هي...؟", correctAnswer: "زواحف", distractors: ["ثدييات", "أسماك", "طيور"], grades: 2...4),
        BankQuestion(prompt: "🌱\nأيّ جزء في النبات يمتصّ الماء؟", correctAnswer: "الجذر", distractors: ["الورقة", "الزهرة", "الجذع"], grades: 0...2),
        BankQuestion(prompt: "☀️\nأيّ جزء في النبات يصنع الغذاء من ضوء الشمس؟", correctAnswer: "الورقة", distractors: ["الجذر", "الزهرة", "التربة"], grades: 2...4),
        BankQuestion(prompt: "💪\nما الذي يمنح الجسم قدرته على الحركة ورفع الأشياء؟", correctAnswer: "العضلات", distractors: ["الجلد", "الشعر", "الأظافر"], grades: 2...4),
        BankQuestion(prompt: "🦷\nكم سنًّا للبالغ عند اكتمال أسنانه بما فيها ضروس العقل؟", correctAnswer: "32", distractors: ["20", "28", "40"], grades: 2...4),
        BankQuestion(prompt: "🧠\nأيّ عضو يفكّر؟", correctAnswer: "الدماغ", distractors: ["القلب", "الكبد", "الرئتان"], grades: 0...2),
        BankQuestion(prompt: "👀\nكم عينًا للنحلة، بما فيها العيون البسيطة الصغيرة؟", correctAnswer: "5", distractors: ["2", "3", "8"], grades: 2...4),
        BankQuestion(prompt: "🐌\nكم قلبًا للأخطبوط؟", correctAnswer: "3", distractors: ["1", "2", "5"], grades: 2...4),
        BankQuestion(prompt: "🦒\nأيّ حيوان هو الأطول على اليابسة؟", correctAnswer: "الزرافة", distractors: ["الفيل", "الحصان", "الإنسان"], grades: 0...2),
        BankQuestion(prompt: "🐋\nأيّ حيوان هو الأكبر في العالم؟", correctAnswer: "الحوت الأزرق", distractors: ["الفيل", "القرش", "الزرافة"], grades: 0...2),
        BankQuestion(prompt: "🐆\nأيّ حيوان هو الأسرع عَدْوًا على اليابسة؟", correctAnswer: "الفهد الصيّاد (شيتا)", distractors: ["الحصان", "الأسد", "الدبّ"], grades: 0...2),
        BankQuestion(prompt: "⚡\nماذا نسمّي العاصفة التي يصحبها رعد وبرق؟", correctAnswer: "عاصفة رعدية", distractors: ["عاصفة رملية", "إعصار قمعي", "عاصفة خضراء"], grades: 2...4),
        BankQuestion(prompt: "🌫\nما الضباب؟", correctAnswer: "سحابة قريبة من سطح الأرض", distractors: ["مطر خفيف", "غبار", "دخان"], grades: 2...4),
        BankQuestion(prompt: "🌋\nما المادّة المنصهرة التي تخرج من البركان؟", correctAnswer: "الحمم (اللابة)", distractors: ["ماء بارد", "رمل", "ثلج"], grades: 2...4),
        BankQuestion(prompt: "🌊\nماذا نسمّي الموجة العملاقة في البحر؟", correctAnswer: "تسونامي", distractors: ["إعصار قمعي", "عاصفة رملية", "ضباب"], grades: 2...4),
        BankQuestion(prompt: "💎\nأيّ مادّة هي الأقسى في الطبيعة؟", correctAnswer: "الماس", distractors: ["الحديد", "الحجر", "الزجاج"], grades: 2...4),
        BankQuestion(prompt: "🧲\nما الذي يجذب مسامير الحديد إليه؟", correctAnswer: "المغناطيس", distractors: ["الماء", "الحجر", "البلاستيك"], grades: 2...4),
        BankQuestion(prompt: "🔦\nكيف ينتقل الضوء؟", correctAnswer: "في خطّ مستقيم", distractors: ["في دوائر", "في منحنيات", "لا ينتقل أبدًا"], grades: 4...6),
        BankQuestion(prompt: "👂\nكيف نسمع؟", correctAnswer: "عبر الموجات الصوتية", distractors: ["عبر موجات الضوء", "عبر اللمس", "عبر الرائحة"], grades: 4...6),
        BankQuestion(prompt: "🌳\nما أطول شجرة في العالم؟", correctAnswer: "السكويا", distractors: ["البلّوط", "الكينا", "النخيل"], grades: 2...4),
        BankQuestion(prompt: "💨\nأيّ حالة من المادّة تنتشر بسرعة لتملأ الوعاء كلّه؟", correctAnswer: "الغازات", distractors: ["السوائل", "المواد الصلبة", "الجليد"], grades: 2...4),
        BankQuestion(prompt: "🌧\nما حالات المادّة الثلاث؟", correctAnswer: "صلبة، سائلة، غازية", distractors: ["حارّة، باردة، فاترة", "حجر، ماء، هواء", "واحد، اثنان، ثلاثة"], grades: 2...4),
        BankQuestion(prompt: "🐦\nما الذي يمكّن الطائر من الطيران؟", correctAnswer: "الجناحان", distractors: ["الأسنان", "الذيل", "الفراء"], grades: 0...2),
        BankQuestion(prompt: "🌳\nأيّ غاز تُطلقه الأشجار في أثناء البناء الضوئي؟", correctAnswer: "الأكسجين", distractors: ["ثاني أكسيد الكربون", "الهيدروجين", "النيتروجين"], grades: 2...4),
        BankQuestion(prompt: "🦠\nما البكتيريا؟", correctAnswer: "كائن حيّ صغير جدًّا", distractors: ["نوع من الخضار", "نوع من المعادن", "نوع من الحجارة"], grades: 4...6),
        BankQuestion(prompt: "🌍\nأيّ قوّة تجذبنا نحو الأرض؟", correctAnswer: "قوّة الجاذبية", distractors: ["المغناطيس", "الريح", "الضوء"], grades: 4...6),
        BankQuestion(prompt: "🐸\nماذا نسمّي صغير الضفدع؟", correctAnswer: "شُرْغُوف (أبو ذُنَيْبة)", distractors: ["جَرْو", "كتكوت", "مُهْر"], grades: 0...2),
        BankQuestion(prompt: "🐔\nمن أين تفقس الكتاكيت؟", correctAnswer: "من البيضة", distractors: ["من التراب", "من الغيمة", "من الماء"], grades: 0...2),
        BankQuestion(prompt: "🐪\nماذا يخزّن الجمل في سنامه؟", correctAnswer: "الدهون", distractors: ["الماء", "الرمل", "الهواء"], grades: 2...4),
        BankQuestion(prompt: "🦉\nمتى تنشط البومة غالبًا؟", correctAnswer: "في الليل", distractors: ["عند الظهيرة", "في الصباح", "لا تنشط أبدًا"], grades: 0...2),
        BankQuestion(prompt: "🐻\nماذا تفعل الدببة في الشتاء البارد؟", correctAnswer: "تنام نوم البيات", distractors: ["تسبح في البحر", "تطير جنوبًا", "تتشمّس"], grades: 0...2),
        BankQuestion(prompt: "🦷\nأيّ عضو يساعدنا على مضغ الطعام؟", correctAnswer: "الأسنان", distractors: ["الأذنان", "الركبتان", "الأظافر"], grades: 0...2),
        BankQuestion(prompt: "🩸\nما لون دمنا؟", correctAnswer: "أحمر", distractors: ["أزرق", "أخضر", "أصفر"], grades: 0...2),
        BankQuestion(prompt: "👃\nبأيّ عضو نشمّ؟", correctAnswer: "بالأنف", distractors: ["بالعينين", "بالأذنين", "باليدين"], grades: 0...2),
        BankQuestion(prompt: "👅\nبأيّ عضو نتذوّق؟", correctAnswer: "باللسان", distractors: ["بالأنف", "بالعينين", "بالأذنين"], grades: 0...2),
        BankQuestion(prompt: "💤\nمتى يرتاح جسمنا ويستعيد قوّته؟", correctAnswer: "عندما ننام", distractors: ["عندما نركض", "عندما نأكل", "عندما نضحك"], grades: 0...2),
        BankQuestion(prompt: "🌙\nما الذي يُضيء السماء في الليل؟", correctAnswer: "القمر", distractors: ["الشمس", "الأزهار", "غيوم المطر"], grades: 0...2),
        BankQuestion(prompt: "🌍\nما شكل كوكب الأرض؟", correctAnswer: "مستدير مثل الكرة", distractors: ["مسطّح", "مربّع", "مثلّث"], grades: 2...4),
        BankQuestion(prompt: "☀️\nمتى تُضيء الشمس سماءنا؟", correctAnswer: "في النهار", distractors: ["في الليل", "في الشتاء فقط", "لا تُضيئها أبدًا"], grades: 0...2),
        BankQuestion(prompt: "⭐\nمتى نرى النجوم؟", correctAnswer: "في الليل", distractors: ["عند الظهيرة", "في الصباح", "عندما تسطع الشمس"], grades: 0...2),
        BankQuestion(prompt: "🚀\nماذا نسمّي من يسافر إلى الفضاء؟", correctAnswer: "رائد فضاء", distractors: ["طيّار", "غوّاص", "سائق"], grades: 2...4),
        BankQuestion(prompt: "⛈️\nماذا يظهر في السماء قبل سماع الرعد بلحظة؟", correctAnswer: "البرق", distractors: ["قوس قزح", "الثلج", "القمر"], grades: 2...4),
        BankQuestion(prompt: "🌧️\nماذا يسقط من الغيمة عند هطول المطر؟", correctAnswer: "قطرات ماء", distractors: ["رمل", "أوراق", "حجارة"], grades: 0...2),
        BankQuestion(prompt: "⛄\nأيّ طقس نحتاج إليه في الخارج كي نبني رجل الثلج؟", correctAnswer: "جوّ بارد وتساقط ثلجيّ", distractors: ["حرّ شديد", "هطول مطر", "رياح دافئة"], grades: 0...2),
        BankQuestion(prompt: "🌬️\nما الذي يحرّك أذرع طاحونة الهواء؟", correctAnswer: "الريح", distractors: ["المطر", "الثلج", "الشمس"], grades: 2...4),
        BankQuestion(prompt: "🌡️\nفي أيّ فصل يكون الجوّ أشدّ حرارة في إسرائيل؟", correctAnswer: "في الصيف", distractors: ["في الشتاء", "في الخريف", "في الربيع"], grades: 0...2),
        BankQuestion(prompt: "🌼\nأيّ جزء في النبات هو الأكثر تلوّنًا وجمالًا؟", correctAnswer: "الزهرة", distractors: ["الجذر", "الساق", "التربة"], grades: 0...2),
        BankQuestion(prompt: "🍎\nمن أيّ جزء من الشجرة نقطف التفّاحة؟", correctAnswer: "من الغصن", distractors: ["من الجذر", "من التربة", "من الجذع"], grades: 0...2),
        BankQuestion(prompt: "🌻\nإلى أيّ جهة تتّجه زهرة عبّاد الشمس الفتيّة؟", correctAnswer: "نحو الشمس", distractors: ["نحو التراب", "نحو القمر", "نحو الماء"], grades: 2...4),
        BankQuestion(prompt: "🌳\nماذا ينمو من البذرة الصغيرة التي نزرعها؟", correctAnswer: "نبتة", distractors: ["حجر", "غيمة", "سمكة"], grades: 0...2),
        BankQuestion(prompt: "💧\nماذا نفعل بالماء كي ننظّف أجسامنا؟", correctAnswer: "نستحمّ", distractors: ["ننام", "نرسم", "نأكل"], grades: 0...2),
        BankQuestion(prompt: "🚰\nمن أين يخرج ماء الشرب في البيت؟", correctAnswer: "من الحنفية", distractors: ["من النافذة", "من المصباح", "من التلفاز"], grades: 0...2),
        BankQuestion(prompt: "🐟\nأيّ عضو يساعد السمكة على التنفّس في الماء؟", correctAnswer: "الخياشيم", distractors: ["الرئتان", "الأنف", "الأذنان"], grades: 2...4),
        BankQuestion(prompt: "🦆\nما الذي تتقنه البطّة أكثر من غيره؟", correctAnswer: "السباحة في الماء", distractors: ["تسلّق الأشجار", "حفر الأنفاق", "نسج الخيوط"], grades: 0...2),
        BankQuestion(prompt: "🌊\nما طعم ماء البحر؟", correctAnswer: "مالح", distractors: ["حلو", "حامض", "حارّ"], grades: 0...2),
        BankQuestion(prompt: "☁️\nممّ تتكوّن الغيوم؟", correctAnswer: "من قطرات ماء صغيرة جدًّا", distractors: ["من صوف ناعم", "من دخان", "من رمل"], grades: 2...4),
        BankQuestion(prompt: "🐜\nكيف يعيش النمل؟", correctAnswer: "في مجموعة كبيرة", distractors: ["وحيدًا دائمًا", "داخل البحر", "فوق الغيوم"], grades: 0...2),
        BankQuestion(prompt: "🦋\nكم جناحًا للفراشة؟", correctAnswer: "4", distractors: ["2", "6", "8"], grades: 2...4),
        BankQuestion(prompt: "🐢\nماذا تحمل السلحفاة على ظهرها دائمًا؟", correctAnswer: "درعًا", distractors: ["جناحين", "أشواكًا", "فراءً"], grades: 0...2),
        BankQuestion(prompt: "🌈\nمتى يظهر قوس قزح في السماء عادةً؟", correctAnswer: "بعد المطر", distractors: ["في المساء", "أثناء تساقط الثلج", "في الليالي المظلمة"], grades: 0...2),
        BankQuestion(prompt: "🌙\nماذا نرى في السماء في الليالي الصافية؟", correctAnswer: "القمر والنجوم", distractors: ["الشمس وقوس قزح", "غيوم المطر", "الأزهار"], grades: 0...2),
        BankQuestion(prompt: "🫀\nأيّ عضو ينبض داخل صدرنا؟", correctAnswer: "القلب", distractors: ["الكبد", "المعدة", "الطحال"], grades: 2...4),
        BankQuestion(prompt: "💪\nما الذي يساعدنا على تحريك أيدينا وأرجلنا؟", correctAnswer: "العضلات", distractors: ["الشعر", "الأظافر", "الدموع"], grades: 2...4),
        BankQuestion(prompt: "🦵\nما الذي يوجد داخل الجسم ويمنحه شكله؟", correctAnswer: "العظام", distractors: ["الغيوم", "الثلج", "الرمل"], grades: 2...4),
        BankQuestion(prompt: "🫁\nأيّ عضو يمتلئ بالهواء عندما نتنفّس؟", correctAnswer: "الرئتان", distractors: ["القلب", "المعدة", "الدماغ"], grades: 2...4),
        BankQuestion(prompt: "💇\nماذا ينمو على رؤوسنا؟", correctAnswer: "الشعر", distractors: ["الريش", "الحراشف", "الفراء"], grades: 0...2),
        BankQuestion(prompt: "🦘\nأيّ حيوان يحمل صغيره في جيب؟", correctAnswer: "الكنغر", distractors: ["الأسد", "الفيل", "الحمار الوحشي"], grades: 0...2),
        BankQuestion(prompt: "🐧\nأيّ طائر لا يستطيع الطيران لكنّه يسبح ببراعة؟", correctAnswer: "البطريق", distractors: ["الحمامة", "النسر", "العصفور الدوري"], grades: 0...2),
        BankQuestion(prompt: "🕸️\nماذا ينسج العنكبوت كي يصطاد؟", correctAnswer: "شبكة من الخيوط", distractors: ["عسلًا", "حليبًا", "عشًّا من القشّ"], grades: 0...2),
        BankQuestion(prompt: "🐘\nبمَ يستعين الفيل كي يشرب ويرفع الأشياء؟", correctAnswer: "بالخرطوم", distractors: ["بالذيل", "بالأذنين", "بالأرجل"], grades: 0...2),
        BankQuestion(prompt: "🐄\nأيّ مشروب نحصل عليه من البقرة؟", correctAnswer: "الحليب", distractors: ["العصير", "العسل", "الزيت"], grades: 0...2),
        BankQuestion(prompt: "🪐\nأيّ كوكب يشتهر بالحلقات التي تحيط به؟", correctAnswer: "زُحل", distractors: ["المرّيخ", "الزهرة", "الأرض"], grades: 4...6),
        BankQuestion(prompt: "🌕\nعندما يكون القمر مستديرًا وممتلئًا تمامًا ماذا نسمّيه؟", correctAnswer: "البدر", distractors: ["الهلال", "المحاق", "قمرًا أحمر"], grades: 2...4),
        BankQuestion(prompt: "🌌\nماذا نسمّي التجمّع العملاق من النجوم في السماء؟", correctAnswer: "المجرّة", distractors: ["السحابة", "قوس قزح", "العاصفة"], grades: 4...6),
        BankQuestion(prompt: "🌑\nكم شمسًا في مجموعتنا الشمسية؟", correctAnswer: "واحدة", distractors: ["اثنتان", "ثلاث", "ولا واحدة"], grades: 2...4),
        BankQuestion(prompt: "⚡\nأيّ ضوء ساطع يظهر في السماء أثناء العاصفة؟", correctAnswer: "البرق", distractors: ["قوس قزح", "الثلج", "الضباب"], grades: 0...2),
        BankQuestion(prompt: "🌪️\nماذا نسمّي الريح القويّة التي تدور كالعمود؟", correctAnswer: "تورنادو", distractors: ["قوس قزح", "قطرة ماء", "سحابة عاديّة"], grades: 2...4),
        BankQuestion(prompt: "☀️\nماذا نسمّي اليوم الخالي من الغيوم الذي تسطع فيه الشمس؟", correctAnswer: "يوم صافٍ", distractors: ["يوم ممطر", "يوم مثلج", "يوم عاصف"], grades: 0...2),
        BankQuestion(prompt: "🌡️\nفي أيّ فصل يكون الطقس أبرد ما يكون في إسرائيل؟", correctAnswer: "في الشتاء", distractors: ["في الصيف", "في الربيع", "في الخريف"], grades: 0...2),
        BankQuestion(prompt: "🍂\nفي أيّ فصل تتساقط الأوراق عن الأشجار؟", correctAnswer: "في الخريف", distractors: ["في الصيف", "في الربيع", "في كلّ فصول السنة"], grades: 0...2),
        BankQuestion(prompt: "🌷\nفي أيّ فصل يتفتّح أكبر عدد من الأزهار؟", correctAnswer: "في الربيع", distractors: ["في الشتاء", "في الخريف", "في الليل"], grades: 0...2),
        BankQuestion(prompt: "🌰\nما أوّل ما ينمو حين تبدأ البذرة بالنموّ في التربة؟", correctAnswer: "الجذر", distractors: ["الزهرة", "الثمرة", "الورقة الكبيرة"], grades: 2...4),
        BankQuestion(prompt: "🌿\nما لون معظم أوراق النباتات؟", correctAnswer: "أخضر", distractors: ["أزرق", "بنفسجيّ", "أسود"], grades: 0...2),
        BankQuestion(prompt: "🍋\nما طعم الليمون؟", correctAnswer: "حامض", distractors: ["حلو", "مالح", "حارّ"], grades: 0...2),
        BankQuestion(prompt: "🍯\nما طعم العسل؟", correctAnswer: "حلو", distractors: ["حامض", "مالح", "مُرّ"], grades: 0...2),
        BankQuestion(prompt: "🥶\nبماذا نشعر حين نلمس الجليد؟", correctAnswer: "بالبرودة", distractors: ["بالحرارة", "بالرطوبة والسخونة", "بالليونة"], grades: 0...2),
        BankQuestion(prompt: "🔥\nكيف يكون الطعام الخارج لتوّه من الفرن؟", correctAnswer: "ساخنًا", distractors: ["باردًا", "متجمّدًا", "صلبًا كالحجر"], grades: 0...2),
        BankQuestion(prompt: "💧\nماذا يحدث للثلج حين نسخّنه؟", correctAnswer: "يتحوّل إلى ماء", distractors: ["يتحوّل إلى حجر", "يتحوّل إلى رمل", "يبقى كما هو"], grades: 2...4),
        BankQuestion(prompt: "🪵\nمن أيّ مادّة تُصنع طاولة خشبية؟", correctAnswer: "من الخشب", distractors: ["من الزجاج", "من الحديد", "من البلاستيك"], grades: 0...2),
        BankQuestion(prompt: "👅\nبأيّ حاسّة نعرف إن كان الطعام حلوًا أم مالحًا؟", correctAnswer: "حاسّة التذوّق", distractors: ["حاسّة البصر", "حاسّة السمع", "حاسّة الشمّ"], grades: 2...4),
        BankQuestion(prompt: "أيّ عضو نستعمله في التنفّس؟", correctAnswer: "الرئتان", distractors: ["القلب", "الكبد", "المعدة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ حيوان يقول \"موو\"؟", correctAnswer: "البقرة", distractors: ["الكلب", "القطّ", "الديك"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما الحيوان الذي يحبّ أكل الجزر؟", correctAnswer: "الأرنب", distractors: ["السمكة", "العصفور", "الأفعى"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "بأيّ عضو نرى؟", correctAnswer: "العينان", distractors: ["الأذنان", "الأنف", "الفم"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "بأيّ عضو نسمع؟", correctAnswer: "الأذنان", distractors: ["العينان", "اليدان", "الرِّجلان"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أين تعيش الأسماك؟", correctAnswer: "في الماء", distractors: ["في الشجرة", "في الهواء", "في الرمل"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ماذا يحتاج النبات كي ينمو؟", correctAnswer: "الماء", distractors: ["السكّر", "الحجر", "البلاستيك"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ نجم يضيء لنا في النهار؟", correctAnswer: "الشمس", distractors: ["القمر", "الشهاب", "المرّيخ"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "في أيّ وقت يبدو ضوء القمر أوضح ما يكون؟", correctAnswer: "في الليل", distractors: ["في الصباح", "عند الظهيرة", "في منتصف النهار"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ماذا ينزل من السماء حين تمطر؟", correctAnswer: "الماء", distractors: ["الرمل", "الحجارة", "الأوراق"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان يستطيع الطيران؟", correctAnswer: "العصفور", distractors: ["السمكة", "الفيل", "السلحفاة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما الحيوان الذي يقول \"هاو هاو\"؟", correctAnswer: "الكلب", distractors: ["القطّ", "البقرة", "الحصان"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "بأيّ عضو نشمّ؟", correctAnswer: "الأنف", distractors: ["العين", "الأذن", "اليد"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ جزء من النبات يوجد في التربة؟", correctAnswer: "الجذر", distractors: ["الزهرة", "الورقة", "الثمرة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "كم رِجلًا للكلب؟", correctAnswer: "أربع", distractors: ["اثنتان", "ستّ", "ثماني"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "في أيّ فصل يتساقط الثلج في الأماكن الباردة؟", correctAnswer: "الشتاء", distractors: ["الصيف", "الربيع", "الخريف"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ماذا نسمّي الماء المتجمّد الصلب؟", correctAnswer: "الجليد", distractors: ["البخار", "القطرة", "السحابة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان يعطينا الحليب؟", correctAnswer: "البقرة", distractors: ["الديك", "السمكة", "القطّ"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما لون معظم الأوراق؟", correctAnswer: "أخضر", distractors: ["أزرق", "أحمر", "بنفسجيّ"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "بأيّ عضو نتذوّق؟", correctAnswer: "اللسان", distractors: ["الأذن", "العين", "الأنف"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان يعيش في البيت ويقول \"مياو\"؟", correctAnswer: "القطّ", distractors: ["الأسد", "الذئب", "الثعلب"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ماذا نستنشق من الهواء؟", correctAnswer: "الأكسجين", distractors: ["الماء", "الرمل", "السكّر"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ حيوان له خرطوم طويل؟", correctAnswer: "الفيل", distractors: ["الزرافة", "الحمار الوحشيّ", "القرد"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما الذي يساعد العصفور على الطيران؟", correctAnswer: "الجناحان", distractors: ["الزعنفة", "الذيل الطويل", "القرنان"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ ثمرة من هذه تنمو على شجرة؟", correctAnswer: "التفّاح", distractors: ["الفراولة", "البطّيخ", "الأناناس"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان يقفز ويحمل صغاره في جيب؟", correctAnswer: "الكنغر", distractors: ["الأرنب", "السنجاب", "الضفدع"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "متى تسطع الشمس في السماء؟", correctAnswer: "في النهار", distractors: ["في الليل", "في الشتاء فقط", "لا تسطع أبدًا"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما لون السماء في يوم صافٍ؟", correctAnswer: "أزرق", distractors: ["أخضر", "أحمر", "بنّيّ"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "من أيّ مادّة تُصنع طاولة خشبية؟", correctAnswer: "من الخشب", distractors: ["من الزجاج", "من المعدن", "من البلاستيك"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان ينبح؟", correctAnswer: "الكلب", distractors: ["القطّ", "البقرة", "الخروف"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ماذا يأكل الضفدع؟", correctAnswer: "الحشرات", distractors: ["العشب", "الحجارة", "الأزهار"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "بأيّ جزء من الجسم نفكّر؟", correctAnswer: "الدماغ", distractors: ["القلب", "اليد", "الرِّجل"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ فصل هو الأشدّ حرارة؟", correctAnswer: "الصيف", distractors: ["الشتاء", "الخريف", "الربيع"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان يعيش في الماء وله زعانف؟", correctAnswer: "السمكة", distractors: ["القطّ", "العصفور", "الحصان"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ماذا ينمو من بذرة نزرعها في التربة؟", correctAnswer: "نبات", distractors: ["حجر", "معدن", "ماء"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان له رقبة طويلة جدًّا؟", correctAnswer: "الزرافة", distractors: ["الأرنب", "الكلب", "الفأر"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "من أيّ مادّة تُصنع نافذة نرى من خلالها؟", correctAnswer: "من الزجاج", distractors: ["من الخشب", "من الحجر", "من القماش"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "كم إصبعًا في اليد الواحدة؟", correctAnswer: "خمس", distractors: ["ثلاث", "سبع", "عشر"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ أداة تساعدنا على الرؤية في الظلام؟", correctAnswer: "المصباح اليدويّ", distractors: ["الملعقة", "الكرسيّ", "الكتاب"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان يتسلّق الأشجار ويحبّ الموز؟", correctAnswer: "القرد", distractors: ["السمكة", "البقرة", "السلحفاة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ماذا تعطينا الدجاجة؟", correctAnswer: "البيض", distractors: ["الحليب", "الصوف", "العسل"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان يحمل بيته على ظهره؟", correctAnswer: "الحلزون", distractors: ["الأرنب", "العصفور", "القطّ"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ماذا نفعل بالرِّجلين؟", correctAnswer: "نمشي", distractors: ["نسمع", "نرى", "نشمّ"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان يعطينا الصوف؟", correctAnswer: "الخروف", distractors: ["السمكة", "الدجاجة", "السلحفاة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ماذا نشرب كي لا نعطش؟", correctAnswer: "الماء", distractors: ["الرمل", "الهواء", "الحجر"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ حيوان يمشي ببطء شديد وله دِرع؟", correctAnswer: "السلحفاة", distractors: ["النمر", "الأرنب", "الغزال"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "من أيّ مادّة تُصنع القدور التي نطبخ فيها؟", correctAnswer: "من المعدن", distractors: ["من الورق", "من القماش", "من البلاستيك"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "أيّ عضو يهضم الطعام في البطن؟", correctAnswer: "المعدة", distractors: ["الدماغ", "الرئتان", "الأذن"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "كم كوكبًا يدور حول الشمس في المجموعة الشمسية؟", correctAnswer: "ثمانية", distractors: ["ستّة", "عشرة", "أربعة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ماذا نسمّي العملية التي يتحوّل فيها الماء إلى بخار بفعل الحرارة؟", correctAnswer: "التبخّر", distractors: ["التجمّد", "الانصهار", "التكثّف"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ جزء من النبات يتحوّل إلى ثمرة؟", correctAnswer: "الزهرة", distractors: ["الجذر", "الورقة", "الساق"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ غاز تُطلقه النباتات في أثناء صنع غذائها بضوء الشمس، ونستنشقه نحن؟", correctAnswer: "الأكسجين", distractors: ["ثاني أكسيد الكربون", "بخار الماء", "الدخان"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ كوكب يُلقَّب بـ\"الكوكب الأحمر\"؟", correctAnswer: "المرّيخ", distractors: ["الزهرة", "المشتري", "زُحل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ مادّة تنجذب إلى المغناطيس؟", correctAnswer: "الحديد", distractors: ["الخشب", "الزجاج", "البلاستيك"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ماذا يحدث للماء حين نضعه في المجمّدة؟", correctAnswer: "يتجمّد ويصير جليدًا", distractors: ["يتبخّر", "يختفي", "يصير ساخنًا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما سبب النهار والليل؟", correctAnswer: "دوران الأرض حول محورها", distractors: ["القمر الذي يحجب الشمس", "الغيوم التي تحجب الضوء", "الشمس التي تنطفئ"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ حيوان ثدييّ يعيش في البحر ويتنفّس الهواء؟", correctAnswer: "الدلفين", distractors: ["القِرش", "الأخطبوط", "قنديل البحر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ حاسّة تتيح لنا أن نعرف إن كان الشيء ساخنًا أم باردًا؟", correctAnswer: "حاسّة اللمس", distractors: ["حاسّة الشمّ", "حاسّة السمع", "حاسّة البصر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ماذا يمتصّ النبات من الشمس كي يصنع غذاءه؟", correctAnswer: "الضوء", distractors: ["الجليد", "الحجر", "المعدن"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ حيوان يبيض وله ريش؟", correctAnswer: "العصفور", distractors: ["الكلب", "البقرة", "الحصان"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ حيوان يبدأ حياته شرغوفًا في الماء ثمّ يصير ذا أربع أرجل ويقفز على اليابسة؟", correctAnswer: "الضفدع", distractors: ["السلحفاة", "الأفعى", "السمكة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما الذي يجعل أوراق بعض الأشجار تتساقط في الخريف؟", correctAnswer: "تغيّر الفصل وبرودة الجوّ", distractors: ["نقص الماء في الصيف", "كثرة الشمس", "الريح التي تلوّنها"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ جرم سماويّ يدور حول الأرض؟", correctAnswer: "القمر", distractors: ["الشمس", "المرّيخ", "الزهرة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ماذا يحدث للجليد حين نتركه في الحرّ؟", correctAnswer: "ينصهر ويصير ماءً", distractors: ["يصير حجرًا", "يختفي", "يصير خشبًا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ حشرة تصنع العسل؟", correctAnswer: "النحلة", distractors: ["النملة", "الفراشة", "الذبابة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي الماء الذي يصعد إلى الهواء ويكوّن الغيوم؟", correctAnswer: "بخار الماء", distractors: ["الجليد", "الثلج", "الرمل"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ حاسّة تساعدنا على الاستمتاع بعبير الأزهار؟", correctAnswer: "حاسّة الشمّ", distractors: ["حاسّة البصر", "حاسّة السمع", "حاسّة التذوّق"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ جزء من النبات يمتصّ الماء من التربة؟", correctAnswer: "الجذر", distractors: ["الورقة", "الزهرة", "الثمرة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ حيوان يبدّل جلده ويتحرّك بلا أرجل؟", correctAnswer: "الأفعى", distractors: ["السحليّة", "السلحفاة", "الضفدع"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ عضو يضخّ الدم والأكسجين إلى الجسم كلّه؟", correctAnswer: "القلب", distractors: ["الدماغ", "الكبد", "العين"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما الظاهرة التي نرى فيها قوسًا ملوّنًا في السماء بعد المطر مع الشمس؟", correctAnswer: "قوس قزح", distractors: ["البرق", "الثلج", "الضباب"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ مادّة توصل الكهرباء بسهولة؟", correctAnswer: "المعدن", distractors: ["الخشب", "البلاستيك", "المطّاط"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ حيوان ينام كثيرًا في الشتاء في حالة سُبات؟", correctAnswer: "الدبّ", distractors: ["الكلب", "الحصان", "البقرة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما اسم الفصل الذي تتفتّح فيه أزهار كثيرة؟", correctAnswer: "الربيع", distractors: ["الشتاء", "الصيف", "الخريف"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ كوكب هو الأكبر في المجموعة الشمسية؟", correctAnswer: "المشتري", distractors: ["الأرض", "المرّيخ", "الزهرة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ جزء في العين يسمح للضوء بالدخول إليها؟", correctAnswer: "البؤبؤ", distractors: ["الحاجب", "الرمش", "الأذن"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ حيوان يتنفّس بالخياشيم؟", correctAnswer: "السمكة", distractors: ["الكلب", "العصفور", "القطّ"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي صغير البقرة؟", correctAnswer: "عِجل", distractors: ["جَدْي", "مُهْر", "جَرْو"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ جرم سماويّ يمنحنا الضوء والحرارة وهو في الحقيقة نجم؟", correctAnswer: "الشمس", distractors: ["القمر", "السحابة", "الشهاب"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ عملية تحدث حين يبرد بخار الماء ويعود قطرات؟", correctAnswer: "التكثّف", distractors: ["التجمّد", "التبخّر", "الانصهار"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ حيوان ينسج شبكة كي يصطاد بها؟", correctAnswer: "العنكبوت", distractors: ["النملة", "الفراشة", "الخنفساء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي الحيوان الذي يتغذّى على النباتات فقط؟", correctAnswer: "عاشبًا", distractors: ["مفترسًا", "طائرًا", "مائيًّا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ جزء من الجسم يحمي الدماغ؟", correctAnswer: "الجمجمة", distractors: ["الأضلاع", "كفّ اليد", "الركبة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ حيوان يغيّر لونه كي يندمج مع محيطه؟", correctAnswer: "الحرباء", distractors: ["الأرنب", "البقرة", "الحصان"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ قوّة تجذب الأشياء نحو الأسفل إلى الأرض؟", correctAnswer: "قوّة الجاذبية", distractors: ["قوّة الريح", "قوّة المغناطيس", "قوّة الشمس"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ماذا نسمّي أرضًا شديدة الجفاف، قليلة المطر، كثيرة الرمال؟", correctAnswer: "الصحراء", distractors: ["الغابة", "البحيرة", "المستنقع"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ عضو ينقّي الدم ويساعد على الهضم في الجسم؟", correctAnswer: "الكبد", distractors: ["القلب", "الدماغ", "الأذن"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما اسم العملية التي تصنع فيها النباتات غذاءها من ضوء الشمس؟", correctAnswer: "التركيب الضوئيّ", distractors: ["التبخّر", "التنفّس", "الهضم"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "في أثناء صنع الغذاء بضوء الشمس، أيّ غاز تمتصّه النباتات من الهواء؟", correctAnswer: "ثاني أكسيد الكربون", distractors: ["الأكسجين", "النيتروجين", "بخار الماء"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ كوكب هو الأقرب إلى الشمس؟", correctAnswer: "عُطارد", distractors: ["المرّيخ", "المشتري", "الأرض"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما اسم الدورة التي يتبخّر فيها الماء ويكوّن الغيوم ثمّ ينزل مطرًا؟", correctAnswer: "دورة الماء", distractors: ["دورة الفصول", "دورة القمر", "دورة التربة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ عضو في الجسم يتحكّم في أفكارنا وحركاتنا؟", correctAnswer: "الدماغ", distractors: ["القلب", "الكبد", "الرئتان"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ قوّة تجعل قطبَين مختلفَين من مغناطيسَين ينجذبان أحدهما إلى الآخر؟", correctAnswer: "القوّة المغناطيسية", distractors: ["قوّة الجاذبية", "قوّة الاحتكاك", "قوّة الريح"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ عضو مسؤول عن تصفية الدم وإخراج البول؟", correctAnswer: "الكلية", distractors: ["القلب", "الرئة", "الدماغ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما الشرط اللازم كي يغرق جسم في الماء بدل أن يطفو؟", correctAnswer: "كثافة أعلى من كثافة الماء", distractors: ["لون داكن", "شكل مستدير", "وزن خفيف جدًّا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ غاز هو المكوّن الرئيسيّ للهواء الذي نتنفّسه؟", correctAnswer: "النيتروجين", distractors: ["الأكسجين", "ثاني أكسيد الكربون", "بخار الماء"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ماذا نسمّي طبقة الغازات التي تحيط بالكرة الأرضية؟", correctAnswer: "الغلاف الجوّيّ", distractors: ["طبقة جليد", "طبقة رمل", "طبقة ماء"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ جزء من الأذن يساعدنا على حفظ التوازن؟", correctAnswer: "الأذن الداخلية", distractors: ["شحمة الأذن", "جلد الوجه", "عظم الخدّ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ حالة من حالات الماء هي الحالة الغازية؟", correctAnswer: "البخار", distractors: ["الجليد", "الثلج", "الصقيع"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ قوّة تُبقي القمر يدور حول الأرض؟", correctAnswer: "قوّة الجاذبية", distractors: ["قوّة الريح", "ضوء الشمس", "القوّة المغناطيسية"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ماذا نسمّي مجموعة هائلة جدًّا من النجوم مجتمعة في الفضاء؟", correctAnswer: "المجرّة", distractors: ["الكوكب", "القمر", "الكويكب"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ مادّة في الورقة تمنحها لونها الأخضر وتمتصّ الضوء؟", correctAnswer: "اليخضور (الكلوروفيل)", distractors: ["الماء", "الرمل", "السكّر"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ عضو ينقل الطعام من الفم إلى المعدة؟", correctAnswer: "المريء", distractors: ["القصبة الهوائية", "الشريان", "الوريد"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ كوكب يشتهر بالحلقات الساطعة التي تحيط به؟", correctAnswer: "زُحل", distractors: ["المرّيخ", "الزهرة", "عُطارد"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ عملية تصف تحوّل الماء السائل إلى جليد صلب؟", correctAnswer: "التجمّد", distractors: ["التبخّر", "الانصهار", "التكثّف"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ حاسّة تعمل بواسطة خلايا مستقبِلة للضوء داخل العين؟", correctAnswer: "حاسّة البصر", distractors: ["حاسّة السمع", "حاسّة التذوّق", "حاسّة اللمس"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ قوّة تُبطئ الأجسام التي تنزلق بعضها على بعض؟", correctAnswer: "قوّة الاحتكاك", distractors: ["قوّة المغناطيس", "قوّة الضوء", "قوّة الصوت"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ حيوان ثدييّ يبيض؟", correctAnswer: "خُلد الماء", distractors: ["الدبّ", "الدلفين", "الأرنب"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ مكوّن في الدم يحمل الأكسجين ويمنح الدم لونه الأحمر؟", correctAnswer: "كريات الدم الحمراء", distractors: ["كريات الدم البيضاء", "الماء وحده", "السكّر"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ماذا نسمّي جرمًا في الفضاء يدور حول كوكب؟", correctAnswer: "قمرًا", distractors: ["شمسًا", "مجرّة", "شهابًا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ نوع من الصخور يتكوّن من تبرّد الحمم وتصلّبها؟", correctAnswer: "الصخر الناريّ", distractors: ["صخر الجليد", "صخر السكّر", "صخر الخشب"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ عضو في الجسم يخزّن العصارة الصفراء التي تساعد على هضم الدهون؟", correctAnswer: "المرارة", distractors: ["القلب", "الرئة", "الدماغ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ ظاهرة جوّية تنشأ عن تفريغ كهربائيّ قويّ بين الغيوم؟", correctAnswer: "البرق", distractors: ["الثلج", "الضباب", "النَّدى"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ مكوّن في الدم يحارب الجراثيم ويحافظ على صحّتنا؟", correctAnswer: "كريات الدم البيضاء", distractors: ["كريات الدم الحمراء", "بخار الماء", "السكّر"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ عملية تصف بذرة تبدأ بالنموّ فتُخرج جذرًا وبُرعمًا؟", correctAnswer: "الإنبات", distractors: ["التجمّد", "التبخّر", "التكثّف"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ عضو في الجهاز التنفّسيّ ينقل الهواء من الحلق إلى الرئتين؟", correctAnswer: "القصبة الهوائية", distractors: ["المريء", "الشريان", "الأمعاء"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ حالة تحدث حين يمرّ القمر بين الشمس والأرض فيحجب ضوءها عنّا؟", correctAnswer: "كسوف الشمس", distractors: ["خسوف القمر", "قوس قزح", "الشروق"], tier: .hard, grades: 4...6),
    ]
}
