import Foundation

/// 🧩 المنطق — بالعربية. مأخوذ عن البنك العبريّ (261 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let logic: [BankQuestion] = [
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n1, 2, 3, ?", correctAnswer: "4", distractors: ["5", "6", "2"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n2, 4, 6, ?", correctAnswer: "8", distractors: ["7", "10", "9"], grades: 1...3),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n5, 10, 15, ?", correctAnswer: "20", distractors: ["25", "16", "18"], grades: 2...4),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n10, 9, 8, ?", correctAnswer: "7", distractors: ["6", "11", "5"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n🔴🟢🔴🟢🔴?", correctAnswer: "🟢", distractors: ["🔴", "🔵", "🟡"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n🐶🐱🐶🐱🐶?", correctAnswer: "🐱", distractors: ["🐶", "🐭", "🐰"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "🚗", distractors: ["🐶", "🐱", "🐰"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "🍎", distractors: ["🚗", "🚌", "🚲"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "📖", distractors: ["⚽", "🏀", "🎾"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "🌳", distractors: ["☀️", "🌙", "⭐"], grades: 0...2),
        BankQuestion(prompt: "إذا كان 🍎 = 2، فكم يساوي 🍎 + 🍎؟", correctAnswer: "4", distractors: ["3", "5", "2"], grades: 2...4),
        BankQuestion(prompt: "إذا كانت القطّة أكبر من الفأر، فمن الأكبر؟", correctAnswer: "🐱", distractors: ["🐭", "متساويان", "لا أعرف"], grades: 0...2),
        BankQuestion(prompt: "ما الشكل التالي؟\n🔺🔻🔺🔻🔺?", correctAnswer: "🔻", distractors: ["🔺", "⬛", "⚫"], grades: 0...2),
        BankQuestion(prompt: "كم رِجلًا لثلاثة كلاب؟", correctAnswer: "12", distractors: ["6", "8", "10"], grades: 2...4),
        BankQuestion(prompt: "إذا كانت ليان أكبر من مريم، ومريم أكبر من آدم، فمن الأكبر؟", correctAnswer: "ليان هي الأكبر", distractors: ["مريم هي الأكبر", "آدم هو الأكبر", "الثلاثة متساوون"], grades: 2...4),
        BankQuestion(prompt: "أيّ واحد لا يشبه البقيّة؟\n🍎 🍌 🍇 🐶", correctAnswer: "🐶 لا يشبه", distractors: ["🍎 لا يشبه", "🍌 لا يشبه", "🍇 لا يشبه"], grades: 0...2),
        BankQuestion(prompt: "إذا كان اليوم هو الثلاثاء، فماذا كان أمس؟", correctAnswer: "الاثنين", distractors: ["الأربعاء", "الأحد", "الخميس"], grades: 1...3),
        BankQuestion(prompt: "إذا كان على الشجرة 5 عصافير وطار منها 2، فكم بقي؟", correctAnswer: "3", distractors: ["7", "2", "4"], grades: 0...2),
        BankQuestion(prompt: "ما الحرف التالي؟\nA, B, C, ?", correctAnswer: "D", distractors: ["E", "A", "C"], grades: 3...5),
        BankQuestion(prompt: "أيّ شكل ليس له زوايا؟", correctAnswer: "⚪", distractors: ["🔺", "⬛", "⬢"], grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي في المتتالية؟\n2, 4, 8, 16, ...", correctAnswer: "32", distractors: ["24", "20", "18"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما العدد التالي في المتتالية؟\n1, 1, 2, 3, 5, 8, ...", correctAnswer: "13", distractors: ["11", "12", "16"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما العدد التالي في المتتالية؟\n100, 90, 81, 73, ...", correctAnswer: "66", distractors: ["65", "64", "63"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "مع ليان ضِعف عدد الكرات الزجاجيّة التي مع كرم. مع كرم ستّ كرات. فكم مع الاثنين معًا؟", correctAnswer: "18", distractors: ["12", "24", "16"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "إذا كانت كلّ التنانين تطير، وجاد تنّين — فما الصحيح أكيدًا؟", correctAnswer: "جاد يستطيع الطيران", distractors: ["جاد أخضر اللون", "كلّ من يطير فهو تنّين", "جاد لا يطير"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "في جرّة ثلاثة جوارب حمراء وثلاثة جوارب زرقاء. كم جوربًا يجب إخراجه دون النظر لنضمن الحصول على زوج بلون واحد؟", correctAnswer: "3", distractors: ["2", "4", "6"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "تشير الساعة إلى 3:00. كم ستكون الساعة بعد 50 دقيقة؟", correctAnswer: "3:50", distractors: ["4:00", "3:40", "4:10"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "أنا عدد. إذا ضربتموني في 3 وأضفتم 1 حصلتم على 22. فمن أنا؟", correctAnswer: "7", distractors: ["6", "8", "9"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "أيّ شكل لا ينتمي إلى المجموعة؟", correctAnswer: "دائرة", distractors: ["مثلّث", "مربّع", "مستطيل"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "هل والد ليان أصغر سنًّا من جدّها لأبيها؟", correctAnswer: "نعم، لأنّ الجدّ هو والد الأب فهو أكبر سنًّا", distractors: ["لا، أبدًا", "هما في العمر نفسه", "لا يمكن معرفة ذلك"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "2, 4, 6, 8, ?", correctAnswer: "10", distractors: ["9", "11", "12"], grades: 2...4),
        BankQuestion(prompt: "5, 10, 15, 20, ?", correctAnswer: "25", distractors: ["22", "30", "24"], grades: 2...4),
        BankQuestion(prompt: "1, 4, 9, 16, ?", correctAnswer: "25", distractors: ["20", "24", "30"], grades: 4...6),
        BankQuestion(prompt: "1, 1, 2, 3, 5, ?", correctAnswer: "8", distractors: ["6", "7", "10"], grades: 4...6),
        BankQuestion(prompt: "100, 90, 80, ?", correctAnswer: "70", distractors: ["75", "60", "85"], grades: 2...4),
        BankQuestion(prompt: "1, 3, 5, 7, ?", correctAnswer: "9", distractors: ["8", "10", "11"], grades: 2...4),
        BankQuestion(prompt: "10, 20, 40, 80, ?", correctAnswer: "160", distractors: ["100", "120", "200"], grades: 4...6),
        BankQuestion(prompt: "A, C, E, G, ?", correctAnswer: "I", distractors: ["H", "J", "K"], grades: 3...5),
        BankQuestion(prompt: "ب، ث، ح، ؟", correctAnswer: "د", distractors: ["خ", "ذ", "ر"], grades: 2...4),
        BankQuestion(prompt: "🔴🔵🔴🔵🔴?", correctAnswer: "🔵", distractors: ["🔴", "🟢", "🟡"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "كرة السلّة", distractors: ["تفّاحة", "موزة", "إجّاصة"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "طاولة", distractors: ["كلب", "قطّة", "أسد"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "درّاجة هوائيّة", distractors: ["سيّارة", "حافلة", "شاحنة"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "أسد", distractors: ["سمكة", "قرش", "أخطبوط"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "أحمر", distractors: ["ثلاثة", "خمسة", "سبعة"], grades: 0...2),
        BankQuestion(prompt: "ما الأكبر حجمًا؟", correctAnswer: "فيل", distractors: ["فأر", "نملة", "فراشة"], grades: 0...2),
        BankQuestion(prompt: "ما الأصغر حجمًا؟", correctAnswer: "نملة", distractors: ["حصان", "كلب", "قطّة"], grades: 0...2),
        BankQuestion(prompt: "ما الأسرع؟", correctAnswer: "طائرة", distractors: ["درّاجة هوائيّة", "قارب", "قطار"], grades: 0...2),
        BankQuestion(prompt: "ما الأثقل؟", correctAnswer: "فيل", distractors: ["ريشة", "تفّاحة", "كتاب"], grades: 0...2),
        BankQuestion(prompt: "ما الأطول قامةً؟", correctAnswer: "زرافة", distractors: ["كلب", "قطّة", "ديك"], grades: 0...2),
        BankQuestion(prompt: "أشرب الماء وليس لي فم. ما أنا؟", correctAnswer: "نبتة", distractors: ["طاولة", "نافذة", "كتاب"], grades: 2...4),
        BankQuestion(prompt: "لي أربع أرجل ولكنّي لا أمشي. من أنا؟", correctAnswer: "طاولة", distractors: ["حصان", "كلب", "سلحفاة"], grades: 2...4),
        BankQuestion(prompt: "أظهر في السماء ليلًا، وأكبر ثمّ أصغر كلّ شهر. من أنا؟", correctAnswer: "القمر", distractors: ["الشمس", "السحابة", "الطائرة"], grades: 2...4),
        BankQuestion(prompt: "أنا برتقاليّة من الخارج وخضراء من الأعلى. من أنا؟", correctAnswer: "جزرة", distractors: ["تفّاحة", "خيارة", "برتقالة"], grades: 2...4),
        BankQuestion(prompt: "لي أوراق ولستُ شجرة. من أنا؟", correctAnswer: "كتاب", distractors: ["نبتة", "زهرة", "فاكهة"], grades: 2...4),
        BankQuestion(prompt: "ما الذي ليس لونًا؟", correctAnswer: "طاولة", distractors: ["أحمر", "أزرق", "أخضر"], grades: 0...2),
        BankQuestion(prompt: "ما الذي ليس حيوانًا؟", correctAnswer: "سيّارة", distractors: ["حصان", "كلب", "عصفور"], grades: 0...2),
        BankQuestion(prompt: "ما الذي ليس فاكهة؟", correctAnswer: "خيار", distractors: ["تفّاح", "موز", "برتقال"], grades: 0...2),
        BankQuestion(prompt: "ما الذي ليس من الخُضار؟", correctAnswer: "برتقال", distractors: ["خيار", "جزر", "طماطم"], grades: 0...2),
        BankQuestion(prompt: "ما الذي ليس يومًا؟", correctAnswer: "كانون الثاني", distractors: ["الاثنين", "الثلاثاء", "الأربعاء"], grades: 0...2),
        BankQuestion(prompt: "كلّ الكلاب تنبح. فمن الذي ينبح؟", correctAnswer: "الكلب", distractors: ["القطّة", "الديك", "البقرة"], grades: 2...4),
        BankQuestion(prompt: "إذا كان 2 + 2 = 4، فكم يساوي 3 + 3؟", correctAnswer: "6", distractors: ["5", "7", "8"], grades: 0...2),
        BankQuestion(prompt: "ما العدد الذي يأتي بعد 7؟", correctAnswer: "8", distractors: ["6", "9", "10"], grades: 0...2),
        BankQuestion(prompt: "ما العدد الذي يأتي قبل 5؟", correctAnswer: "4", distractors: ["6", "3", "7"], grades: 0...2),
        BankQuestion(prompt: "كم يومًا في الأسبوع؟", correctAnswer: "7", distractors: ["5", "6", "8"], grades: 0...2),
        BankQuestion(prompt: "كم شهرًا في السنة؟", correctAnswer: "12", distractors: ["10", "11", "13"], grades: 2...4),
        BankQuestion(prompt: "كم ساعة في اليوم الكامل؟", correctAnswer: "24", distractors: ["12", "18", "30"], grades: 2...4),
        BankQuestion(prompt: "كم دقيقة في الساعة؟", correctAnswer: "60", distractors: ["50", "100", "30"], grades: 2...4),
        BankQuestion(prompt: "كم ثانية في الدقيقة؟", correctAnswer: "60", distractors: ["100", "30", "12"], grades: 2...4),
        BankQuestion(prompt: "ما عكس كلمة «كبير»؟", correctAnswer: "صغير", distractors: ["طويل", "عريض", "عالٍ"], grades: 0...2),
        BankQuestion(prompt: "ما عكس كلمة «حارّ»؟", correctAnswer: "بارد", distractors: ["لذيذ", "حلو", "جافّ"], grades: 0...2),
        BankQuestion(prompt: "ما عكس كلمة «سريع»؟", correctAnswer: "بطيء", distractors: ["قويّ", "طويل", "ثقيل"], grades: 0...2),
        BankQuestion(prompt: "ما عكس كلمة «نهار»؟", correctAnswer: "ليل", distractors: ["صباح", "مساء", "ظهيرة"], grades: 0...2),
        BankQuestion(prompt: "ما عكس كلمة «سعيد»؟", correctAnswer: "حزين", distractors: ["مضحك", "هادئ", "مندهش"], grades: 0...2),
        BankQuestion(prompt: "ما عكس كلمة «يمين»؟", correctAnswer: "يسار", distractors: ["فوق", "تحت", "أمام"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n3, 6, 9, ?", correctAnswer: "12", distractors: ["10", "11", "15"], grades: 2...4),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n20, 18, 16, ?", correctAnswer: "14", distractors: ["15", "12", "17"], grades: 2...4),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n🌟⬛🌟⬛🌟?", correctAnswer: "⬛", distractors: ["🌟", "🔵", "🔺"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n🍓🍋🍓🍋🍓?", correctAnswer: "🍋", distractors: ["🍓", "🍇", "🍊"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n☀️🌙☀️🌙☀️?", correctAnswer: "🌙", distractors: ["☀️", "⭐", "☁️"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n🐘🦒🐘🦒🐘?", correctAnswer: "🦒", distractors: ["🐘", "🦓", "🐅"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n4, 8, 12, ?", correctAnswer: "16", distractors: ["14", "18", "20"], grades: 2...4),
        BankQuestion(prompt: "ما الشكل التالي؟\n⬛⬜⬛⬜⬛?", correctAnswer: "⬜", distractors: ["⬛", "🔺", "🔵"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "🐟", distractors: ["🐦", "🦅", "🦜"], grades: 0...2),
        BankQuestion(prompt: "ما الذي ليس قطعة أثاث؟", correctAnswer: "مروحيّة", distractors: ["كرسي", "خزانة", "سرير"], grades: 0...2),
        BankQuestion(prompt: "ما الذي ليس آلة موسيقيّة؟", correctAnswer: "مقلاة", distractors: ["ناي", "طبل", "بيانو"], grades: 0...2),
        BankQuestion(prompt: "كم أذنًا لطفلين اثنين؟", correctAnswer: "4", distractors: ["2", "3", "6"], grades: 0...2),
        BankQuestion(prompt: "كم إصبعًا في يدين اثنتين؟", correctAnswer: "10", distractors: ["5", "8", "12"], grades: 0...2),
        BankQuestion(prompt: "إذا كان 🐞 = 3، فكم يساوي 🐞 + 🐞؟", correctAnswer: "6", distractors: ["5", "4", "9"], grades: 2...4),
        BankQuestion(prompt: "إذا كان في الصندوق كرتان وأضفنا كرتين أخريين، فكم صار فيه؟", correctAnswer: "4", distractors: ["3", "2", "5"], grades: 0...2),
        BankQuestion(prompt: "إذا كان اليوم هو الأربعاء، فما يوم الغد؟", correctAnswer: "الخميس", distractors: ["الثلاثاء", "الجمعة", "الاثنين"], grades: 0...2),
        BankQuestion(prompt: "أيّ يوم يأتي قبل يوم الأحد؟", correctAnswer: "السبت", distractors: ["الاثنين", "الجمعة", "الثلاثاء"], grades: 0...2),
        BankQuestion(prompt: "ما الحرف التالي؟\nث، ج، ح، ؟", correctAnswer: "خ", distractors: ["د", "ج", "ت"], grades: 0...2),
        BankQuestion(prompt: "أيّ حرف يأتي قبل حرف الزاي؟", correctAnswer: "الراء", distractors: ["السين", "الشين", "الذال"], grades: 0...2),
        BankQuestion(prompt: "ما العدد الذي يأتي بعد 14؟", correctAnswer: "15", distractors: ["13", "16", "20"], grades: 0...2),
        BankQuestion(prompt: "ما العدد الذي يأتي قبل 10؟", correctAnswer: "9", distractors: ["11", "8", "12"], grades: 0...2),
        BankQuestion(prompt: "ما الأطول؟", correctAnswer: "ثعبان", distractors: ["نملة", "ذبابة", "نحلة"], grades: 0...2),
        BankQuestion(prompt: "ما الأعرض؟", correctAnswer: "حافلة", distractors: ["قلم رصاص", "قشّة", "خيط"], grades: 0...2),
        BankQuestion(prompt: "ما الأثقل؟", correctAnswer: "حجر", distractors: ["ريشة", "ورقة شجر", "بالون"], grades: 0...2),
        BankQuestion(prompt: "إذا كان في الصحن 6 قطع بسكويت وأكلتُ 2، فكم بقي؟", correctAnswer: "4", distractors: ["8", "5", "3"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n🟦🟥🟨🟦🟥?", correctAnswer: "🟨", distractors: ["🟦", "🟥", "🟩"], grades: 0...2),
        BankQuestion(prompt: "ما الذي ليس شكلًا هندسيًّا؟", correctAnswer: "شمس", distractors: ["دائرة", "مربّع", "مثلّث"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n7, 14, 21, ?", correctAnswer: "28", distractors: ["27", "30", "35"], grades: 2...4),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n3, 6, 12, 24, ?", correctAnswer: "48", distractors: ["36", "30", "40"], grades: 2...4),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n50, 40, 30, ?", correctAnswer: "20", distractors: ["25", "10", "35"], grades: 2...4),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n🟢🟢🔴🟢🟢🔴🟢🟢?", correctAnswer: "🔴", distractors: ["🟢", "🔵", "🟡"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n🐢🐰🐢🐰🐢?", correctAnswer: "🐰", distractors: ["🐢", "🐭", "🦊"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n⭐🌙⭐⭐🌙⭐⭐⭐🌙?", correctAnswer: "⭐", distractors: ["🌙", "☀️", "🌟"], grades: 1...3),
        BankQuestion(prompt: "ما الشكل التالي؟\n🔴🟡🔵🔴🟡?", correctAnswer: "🔵", distractors: ["🔴", "🟡", "🟢"], grades: 0...2),
        BankQuestion(prompt: "ما الذي يأتي بعد؟\n9, 8, 7, 6, ?", correctAnswer: "5", distractors: ["4", "7", "10"], grades: 0...2),
        BankQuestion(prompt: "ما الحرف التالي؟\nأ، ت، ج، ؟", correctAnswer: "خ", distractors: ["ح", "د", "ب"], grades: 1...3),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "🌻", distractors: ["🐝", "🦋", "🐞"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "🍕", distractors: ["👕", "👖", "🧦"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "🦈", distractors: ["🐦", "🦅", "🦉"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي؟", correctAnswer: "☂️", distractors: ["✏️", "📕", "✂️"], grades: 0...2),
        BankQuestion(prompt: "ما الذي ليس رِجلًا؟", correctAnswer: "🪶", distractors: ["🐾", "🦵", "🦶"], grades: 0...2),
        BankQuestion(prompt: "كم عجلة للدرّاجة الهوائيّة؟", correctAnswer: "2", distractors: ["1", "3", "4"], grades: 0...2),
        BankQuestion(prompt: "كم إصبعًا في اليد الواحدة؟", correctAnswer: "5", distractors: ["4", "10", "6"], grades: 0...2),
        BankQuestion(prompt: "كم ذيلًا لأربع قطط؟", correctAnswer: "4", distractors: ["8", "2", "16"], grades: 0...2),
        BankQuestion(prompt: "كم جناحًا لعصفورين اثنين؟", correctAnswer: "4", distractors: ["2", "6", "8"], grades: 1...3),
        BankQuestion(prompt: "ما العدد الذي يأتي قبل 8؟", correctAnswer: "7", distractors: ["9", "6", "10"], grades: 0...2),
        BankQuestion(prompt: "ما العدد الذي يأتي بعد 19؟", correctAnswer: "20", distractors: ["18", "21", "29"], grades: 0...2),
        BankQuestion(prompt: "أيّ حرف يأتي بعد حرف الشين؟", correctAnswer: "الصاد", distractors: ["السين", "الضاد", "الزاي"], grades: 1...3),
        BankQuestion(prompt: "إذا كان اليوم هو الجمعة، فأيّ يوم كان أمس؟", correctAnswer: "الخميس", distractors: ["الأربعاء", "السبت", "الثلاثاء"], grades: 2...4),
        BankQuestion(prompt: "إذا كان 🍌 = 5، فكم يساوي 🍌 + 🍌؟", correctAnswer: "10", distractors: ["7", "15", "25"], grades: 1...3),
        BankQuestion(prompt: "كلّ الأسماك تجيد السباحة. فماذا تفعل السمكة في البحر؟", correctAnswer: "تسبح", distractors: ["تطير", "تقفز", "تركض"], grades: 0...2),
        BankQuestion(prompt: "إذا كان في الحديقة 4 زهرات وقطفنا واحدة، فكم بقي؟", correctAnswer: "3", distractors: ["5", "2", "4"], grades: 0...2),
        BankQuestion(prompt: "إذا كان الفيل أثقل من الفأر، فمن الأخفّ؟", correctAnswer: "🐭", distractors: ["🐘", "متساويان", "لا أعرف"], grades: 0...2),
        BankQuestion(prompt: "أين توجد الشمس؟\n☀️\n🏠", correctAnswer: "في الأعلى", distractors: ["في الأسفل", "في الجانب", "في الخلف"], grades: 0...2),
        BankQuestion(prompt: "أيّ شكل له 3 زوايا؟", correctAnswer: "🔺", distractors: ["⚪", "⬛", "⬢"], grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "كرسي", distractors: ["كلب", "قطّة", "حصان"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 1, 2, 3, ?", correctAnswer: "4", distractors: ["5", "6", "2"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 2, 4, 6, ?", correctAnswer: "8", distractors: ["7", "9", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما العدد الذي يأتي بعد 5؟", correctAnswer: "6", distractors: ["4", "7", "8"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد الذي يأتي قبل 4؟", correctAnswer: "3", distractors: ["5", "2", "6"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "النهار للشمس كما الليل لـ___؟", correctAnswer: "القمر", distractors: ["الغيمة", "المطر", "الشجرة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "سيّارة", distractors: ["برتقالة", "موزة", "تفّاحة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 5, 6, 7, ?", correctAnswer: "8", distractors: ["9", "10", "6"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما اليوم الذي يأتي بعد يوم الأحد؟", correctAnswer: "يوم الاثنين", distractors: ["يوم الثلاثاء", "يوم السبت", "يوم الأربعاء"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "سمكة", distractors: ["عصفور", "فراشة", "نحلة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 10, 9, 8, ?", correctAnswer: "7", distractors: ["6", "9", "10"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "كبير مقابل ___ كما حارّ مقابل بارد.", correctAnswer: "صغير", distractors: ["عريض", "طويل", "ثقيل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "حذاء", distractors: ["عين", "أذن", "أنف"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما الحرف الذي يأتي بعد حرف الألف؟", correctAnswer: "الباء", distractors: ["التاء", "الثاء", "الجيم"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 1, 3, 5, ?", correctAnswer: "7", distractors: ["6", "8", "9"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "طاولة", distractors: ["وردة", "زنبقة", "توليب"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "الصيف للحرّ كما الشتاء لـ___؟", correctAnswer: "البرد", distractors: ["الجفاف", "السطوع", "الدفء"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما اليوم الذي يأتي قبل يوم الجمعة؟", correctAnswer: "يوم الخميس", distractors: ["يوم السبت", "يوم الأحد", "يوم الأربعاء"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 0, 2, 4, ?", correctAnswer: "6", distractors: ["5", "7", "8"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "كتاب", distractors: ["موزة", "عنب", "إجّاصة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "العصفور يطير في ___ كما تسبح السمكة في الماء.", correctAnswer: "السماء", distractors: ["الغابة", "الرمل", "الجبل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما العدد الذي يأتي بعد 9؟", correctAnswer: "10", distractors: ["8", "11", "7"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "إصبع", distractors: ["أحمر", "أصفر", "برتقاليّ"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 3, 6, 9, ?", correctAnswer: "12", distractors: ["10", "11", "13"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "اليد للقفّاز كما القدم لـ___؟", correctAnswer: "الجورب", distractors: ["القبّعة", "الوشاح", "القميص"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "كلب", distractors: ["درّاجة هوائيّة", "سيّارة", "حافلة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 2, 4, 8, ?", correctAnswer: "16", distractors: ["10", "12", "14"], tier: .easy, grades: 4...6),
        BankQuestion(prompt: "ما الفصل الذي يأتي بعد الربيع؟", correctAnswer: "الصيف", distractors: ["الشتاء", "الخريف", "المطر"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "فيل", distractors: ["طاولة", "كرسي", "خزانة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "الأمّ للابن كما الأب لـ___؟", correctAnswer: "الابنة", distractors: ["العمّ", "الجدّ", "الأخ"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما العدد التالي؟ 5, 10, 15, ?", correctAnswer: "20", distractors: ["18", "25", "16"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الحرف الذي يأتي قبل حرف الثاء؟", correctAnswer: "التاء", distractors: ["الجيم", "الباء", "الحاء"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "طعام", distractors: ["أحمر", "أصفر", "أزرق"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 10, 20, 30, ?", correctAnswer: "40", distractors: ["35", "50", "31"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "تفّاحة", distractors: ["كلب", "قطّة", "أرنب"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 4, 8, 12, ?", correctAnswer: "16", distractors: ["14", "18", "20"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "النهار للنور كما الليل لـ___؟", correctAnswer: "الظلام", distractors: ["الشمس", "النجمة", "الصباح"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما اليوم الذي يأتي قبل يوم الثلاثاء؟", correctAnswer: "يوم الاثنين", distractors: ["يوم الأربعاء", "يوم الأحد", "يوم السبت"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "جزرة", distractors: ["تفّاحة", "إجّاصة", "برتقالة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 1, 4, 7, ?", correctAnswer: "10", distractors: ["8", "9", "11"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "السمكة تعيش في ___ كما يعيش العصفور على الشجرة.", correctAnswer: "الماء", distractors: ["الرمل", "الهواء", "النار"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما العدد الذي يأتي بعد 99؟", correctAnswer: "100", distractors: ["98", "101", "90"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "كوب", distractors: ["واحد", "اثنان", "ثلاثة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "ما العدد التالي؟ 2, 5, 8, ?", correctAnswer: "11", distractors: ["9", "10", "12"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "كبيرة مقابل صغيرة كما طويلة مقابل ___؟", correctAnswer: "قصيرة", distractors: ["عريضة", "ثقيلة", "عالية"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما العدد الذي يأتي قبل 1؟", correctAnswer: "0", distractors: ["2", "3", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي لا ينتمي إلى المجموعة؟", correctAnswer: "نجمة", distractors: ["دائرة", "مربّع", "مثلّث"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 3, 6, 12, 24, ?", correctAnswer: "48", distractors: ["36", "30", "40"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "الإصبع لليد كما السنّ لِـ___؟", correctAnswer: "الفم", distractors: ["الأذن", "الأنف", "العين"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 1، 4، 9، 16، ؟", correctAnswer: "25", distractors: ["20", "24", "36"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "كلب", distractors: ["نسر", "حمامة", "ببغاء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "الكاتب للقلم كما الرسّام لِـ___؟", correctAnswer: "الفرشاة", distractors: ["الورق", "اللون", "الكتاب"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 100، 90، 80، ؟", correctAnswer: "70", distractors: ["75", "60", "85"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "أربعة", distractors: ["الأحد", "الاثنين", "الثلاثاء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "الطبيب للمريض كما المعلّم لِـ___؟", correctAnswer: "التلميذ", distractors: ["الكتاب", "اللوح", "الصفّ"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 2، 6، 18، ؟", correctAnswer: "54", distractors: ["36", "24", "48"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "مثلّث", distractors: ["أحمر", "أزرق", "أخضر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "النحلة للعسل كما البقرة لِـ___؟", correctAnswer: "الحليب", distractors: ["الصوف", "البيض", "الماء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 5، 10، 20، 40، ؟", correctAnswer: "80", distractors: ["60", "50", "70"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الكرة", distractors: ["الشوكة", "الملعقة", "السكّين"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "الأسد للزئير كما الأفعى لِـ___؟", correctAnswer: "الفحيح", distractors: ["النباح", "التغريد", "الثغاء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 1، 2، 4، 7، 11، ؟", correctAnswer: "16", distractors: ["14", "15", "17"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "التفّاحة", distractors: ["الحيوان", "النبات", "الإنسان"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "السفينة للبحر كما الطائرة لِـ___؟", correctAnswer: "السماء", distractors: ["الشارع", "سكّة الحديد", "الرمل"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 81، 27، 9، ؟", correctAnswer: "3", distractors: ["6", "1", "4"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الدرّاجة الناريّة", distractors: ["الحصان", "الفيل", "الجمل"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "المَلِك للتاج كما الجنديّ لِـ___؟", correctAnswer: "الخوذة", distractors: ["الحذاء", "المعطف", "القفّاز"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 12، 10، 8، 6، ؟", correctAnswer: "4", distractors: ["5", "3", "2"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الحجر", distractors: ["الوردة", "شقائق النعمان", "النرجس"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "الشجرة للورقة كما الكتاب لِـ___؟", correctAnswer: "الصفحة", distractors: ["الغلاف", "الكلمة", "الحرف"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 7، 14، 21، 28، ؟", correctAnswer: "35", distractors: ["30", "32", "42"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الخريف", distractors: ["اثنان", "أربعة", "ستّة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "الخبّاز للخبز كما الفلّاح لِـ___؟", correctAnswer: "المحصول", distractors: ["الفرن", "الطحين", "الماء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 1، 1، 2، 3، 5، ؟", correctAnswer: "8", distractors: ["6", "7", "9"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "الأرنب للقفز كما السمكة لِـ___؟", correctAnswer: "السباحة", distractors: ["الركض", "الطيران", "الزحف"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 50، 45، 40، 35، ؟", correctAnswer: "30", distractors: ["25", "32", "28"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الدفتر", distractors: ["الإصبع", "كفّ اليد", "المرفق"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "السلحفاة بطيئة، وأمّا النمر فهو ___؟", correctAnswer: "سريع", distractors: ["ثقيل", "كبير", "قويّ"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 2، 3، 5، 8، 13، ؟", correctAnswer: "21", distractors: ["18", "20", "26"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الأسد", distractors: ["القرش", "الدلفين", "الحوت"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "الشتاء للمطر كما الصيف لِـ___؟", correctAnswer: "الشمس", distractors: ["الثلج", "الغيم", "الريح"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 6، 12، 24، 48، ؟", correctAnswer: "96", distractors: ["72", "60", "84"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الحصان", distractors: ["النحلة", "النملة", "الفراشة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "الطبّاخ للقِدر كما النجّار لِـ___؟", correctAnswer: "المطرقة", distractors: ["الصحن", "الكرسيّ", "الخشب"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 11، 22، 33، 44، ؟", correctAnswer: "55", distractors: ["50", "54", "66"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الصفّ", distractors: ["كانون الثاني", "آذار", "آب"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "اليد للقفّاز كما الرأس لِـ___؟", correctAnswer: "القبّعة", distractors: ["الجورب", "الحذاء", "الوشاح"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الطاولة", distractors: ["المنشار", "المفكّ", "المطرقة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "النجمة لليل كما الشمس لِـ___؟", correctAnswer: "النهار", distractors: ["القمر", "الغيمة", "السماء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما العدد التالي؟ 1، 3، 6، 10، 15، ؟", correctAnswer: "21", distractors: ["18", "20", "24"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "البرتقالة", distractors: ["العصير", "الحليب", "الماء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "كلّ القطط لها ذيل، وهذا الحيوان له ذيل — هل يجب أن يكون قطًّا؟", correctAnswer: "ليس بالضرورة", distractors: ["نعم، دائمًا", "لا، أبدًا", "لا يمكن معرفة أيّ شيء إطلاقًا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما العدد التالي؟ 2، 4، 8، 16، 32، ؟", correctAnswer: "64", distractors: ["48", "40", "56"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "آدم أطول من كرم، وكرم أطول من جاد. مَن الأقصر؟", correctAnswer: "جاد", distractors: ["آدم", "كرم", "كلّهم في الطول نفسه"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "ما العدد التالي؟ 1، 4، 9، 16، 25، ؟", correctAnswer: "36", distractors: ["30", "35", "49"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "إذا كان اليوم هو الأربعاء، فأيّ يوم سيكون بعد ثلاثة أيّام؟", correctAnswer: "السبت", distractors: ["الجمعة", "الأحد", "الخميس"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "ما العدد التالي؟ 3، 7، 15، 31، ؟", correctAnswer: "63", distractors: ["47", "55", "62"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "لكلّ الطيور أجنحة. وهناك شيء بلا أجنحة. ما الصحيح؟", correctAnswer: "هذا الشيء ليس طائرًا", distractors: ["هذا الشيء طائر", "هذا الشيء يطير", "لا يمكن معرفة ذلك"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما العدد التالي؟ 1، 2، 6، 24، ؟", correctAnswer: "120", distractors: ["48", "72", "96"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "إذا كان أمس يوم الاثنين، فأيّ يوم سيكون غدًا؟", correctAnswer: "الأربعاء", distractors: ["الثلاثاء", "الخميس", "الأحد"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "ما العدد التالي؟ 2، 5، 11، 23، ؟", correctAnswer: "47", distractors: ["35", "44", "46"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "لدى ليان قطع بسكويت أكثر من سارة، لكن أقلّ من مريم. مَن لديها أكبر عدد من قطع البسكويت؟", correctAnswer: "مريم", distractors: ["ليان", "سارة", "لديهنّ العدد نفسه"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "ما العدد التالي؟ 5، 11، 17، 23، ؟", correctAnswer: "29", distractors: ["27", "28", "30"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما العدد التالي؟ 100، 1، 99، 2، 98، ؟", correctAnswer: "3", distractors: ["97", "4", "96"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الخيار", distractors: ["الفراولة", "توت العليق", "الكرز"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كلّ الكرات في العلبة حمراء. أخرجتُ كرة واحدة. ما لونها؟", correctAnswer: "أحمر", distractors: ["أزرق", "أخضر", "غير معروف"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "ما العدد التالي؟ 4، 9، 16، 25، 36، ؟", correctAnswer: "49", distractors: ["42", "45", "48"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "إذا اصطادت قطّتان فأرين في دقيقتين، فكم فأرًا تصطاد ستّ قطط في أربع دقائق؟", correctAnswer: "12", distractors: ["6", "8", "24"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما العدد التالي؟ 1، 8، 27، 64، ؟", correctAnswer: "125", distractors: ["100", "81", "120"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ عدد لا ينتمي إلى المجموعة؟", correctAnswer: "12", distractors: ["10", "15", "20"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "لدى مريم أختان وأخ واحد. كم بنتًا في العائلة؟", correctAnswer: "3", distractors: ["2", "4", "1"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "ما العدد التالي؟ 90، 81، 72، 63، ؟", correctAnswer: "54", distractors: ["50", "55", "52"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "الجدّ للأب كما الأب لِـ___؟", correctAnswer: "أنا", distractors: ["العمّ", "الجدّة", "الأخ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "إذا كان كلّ أحمر ساخنًا، وكلّ ساخن خطِرًا، فما الصحيح عن شيء أحمر؟", correctAnswer: "إنّه خطِر", distractors: ["إنّه بارد", "إنّه آمن", "لا يمكن معرفة ذلك"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما العدد التالي؟ 2، 3، 5، 7، 11، ؟", correctAnswer: "13", distractors: ["12", "14", "15"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "الوسط", distractors: ["الأوّل", "الثاني", "الثالث"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "في علبة البيض 12 بيضة. أخذتُ نصفها ثمّ أخذتُ بيضتين إضافيّتين. كم بيضة بقيت؟", correctAnswer: "4", distractors: ["6", "5", "8"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما العدد التالي؟ 1، 3، 7، 13، 21، ؟", correctAnswer: "31", distractors: ["28", "29", "30"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "الغرفة مظلمة. أشعلتُ شمعة واحدة ثمّ 4 شموع أخرى، وانطفأت شمعتان — كم شمعة تبقى مشتعلة؟", correctAnswer: "3", distractors: ["5", "2", "4"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما العدد التالي؟ 64، 32، 16، 8، ؟", correctAnswer: "4", distractors: ["6", "2", "5"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيٌّ منها لا ينتمي إلى المجموعة؟", correctAnswer: "مربّع", distractors: ["1", "5", "9"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "بعد غدٍ سيكون يوم الجمعة. أيّ يوم كان أمس؟", correctAnswer: "الثلاثاء", distractors: ["الاثنين", "الأربعاء", "الخميس"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "ما العدد التالي؟ 3، 5، 9، 17، ؟", correctAnswer: "33", distractors: ["25", "29", "31"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "لكلّ يد 5 أصابع. كم إصبعًا لدى 3 أطفال؟", correctAnswer: "30", distractors: ["15", "25", "20"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "أيّ عدد لا ينتمي إلى المجموعة؟", correctAnswer: "23", distractors: ["10", "20", "30"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "تجلس ليان عن يمين سارة، وتجلس سارة عن يمين مريم. مَن تجلس في الوسط؟", correctAnswer: "سارة", distractors: ["ليان", "مريم", "لا يمكن معرفة ذلك"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "ما العدد التالي؟ 2، 6، 12، 20، 30، ؟", correctAnswer: "42", distractors: ["38", "40", "36"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "إذا كان غدًا يوم الأحد، فأيّ يوم كان قبل يومين؟", correctAnswer: "الخميس", distractors: ["الجمعة", "الأربعاء", "السبت"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "لدى كرم ضعف عدد التفّاحات التي لدى آدم. لدى آدم 4 تفّاحات. كم تفّاحة لديهما معًا؟", correctAnswer: "12", distractors: ["8", "10", "16"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "إذا كانت ليان أكبر سنًّا من سارة، وسارة أكبر سنًّا من مريم، فمَن الأصغر؟", correctAnswer: "مريم", distractors: ["ليان", "سارة", "كلّهنّ في العمر نفسه"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "ما العدد التالي؟ 7، 10، 16، 28، ؟", correctAnswer: "52", distractors: ["40", "44", "48"], tier: .hard, grades: 4...6),
    ]
}
