import Foundation

/// 🌍 الجغرافيا — بالعربية. مأخوذ عن البنك العبريّ (334 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let geography: [BankQuestion] = [
        BankQuestion(prompt: "🇮🇱\nما عاصمة إسرائيل؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "بئر السبع"], grades: 2...4),
        BankQuestion(prompt: "🌊\nأيّ بحر يقع غربَ إسرائيل؟", correctAnswer: "البحر المتوسّط", distractors: ["البحر الأحمر", "البحر الميّت", "المحيط الهنديّ"], grades: 2...4),
        BankQuestion(prompt: "🏞️\nما أكثر بحر ملوحةً في العالم؟", correctAnswer: "البحر الميّت", distractors: ["البحر المتوسّط", "البحر الأحمر", "البحر الأسود"], grades: 2...4),
        BankQuestion(prompt: "🌎\nفي أيّ قارّة تقع إسرائيل؟", correctAnswer: "آسيا", distractors: ["أفريقيا", "أوروبا", "أمريكا"], grades: 4...6),
        BankQuestion(prompt: "🗽\nما عاصمة الولايات المتّحدة؟", correctAnswer: "واشنطن", distractors: ["نيويورك", "لوس أنجلوس", "شيكاغو"], grades: 4...6),
        BankQuestion(prompt: "🗼\nفي أيّ دولة يقع برج إيفل؟", correctAnswer: "فرنسا", distractors: ["إيطاليا", "إنجلترا", "إسبانيا"], grades: 4...6),
        BankQuestion(prompt: "🐼\nأين تعيش حيوانات الباندا؟", correctAnswer: "الصين", distractors: ["اليابان", "أستراليا", "الهند"], grades: 2...4),
        BankQuestion(prompt: "🦘\nأين تعيش حيوانات الكنغر؟", correctAnswer: "أستراليا", distractors: ["أفريقيا", "أمريكا", "أوروبا"], grades: 2...4),
        BankQuestion(prompt: "🐧\nأين يعيش البطريق؟", correctAnswer: "في أنتاركتيكا", distractors: ["في البحر المتوسّط", "في الصحراء الكبرى", "في الغابة الاستوائيّة"], grades: 2...4),
        BankQuestion(prompt: "🏔️\nما أعلى جبل في العالم؟", correctAnswer: "إفرست", distractors: ["جبل الشيخ", "كليمنجارو", "مون بلان"], grades: 4...6),
        BankQuestion(prompt: "🌊\nما أكبر مسطَّح مائيّ في العالم؟", correctAnswer: "المحيط الهادئ", distractors: ["البحر المتوسّط", "المحيط الأطلسيّ", "المحيط الهنديّ"], grades: 4...6),
        BankQuestion(prompt: "🏞️\nما أطول نهر في العالم؟", correctAnswer: "النيل", distractors: ["نهر الأردن", "الأمازون", "المسيسيبي"], grades: 4...6),
        BankQuestion(prompt: "🌍\nكم قارّةً في العالم؟", correctAnswer: "7", distractors: ["5", "6", "8"], grades: 4...6),
        BankQuestion(prompt: "🐘\nأين تعيش الفِيَلة؟", correctAnswer: "في أفريقيا والهند", distractors: ["في إسرائيل", "في أستراليا", "في أنتاركتيكا"], grades: 2...4),
        BankQuestion(prompt: "🇮🇹\nما عاصمة إيطاليا؟", correctAnswer: "روما", distractors: ["ميلانو", "فلورنسا", "البندقيّة"], grades: 4...6),
        BankQuestion(prompt: "🇪🇸\nما عاصمة إسبانيا؟", correctAnswer: "مدريد", distractors: ["برشلونة", "إشبيلية", "بلنسية"], grades: 4...6),
        BankQuestion(prompt: "🇬🇧\nما عاصمة إنجلترا؟", correctAnswer: "لندن", distractors: ["مانشستر", "ليفربول", "أدنبرة"], grades: 4...6),
        BankQuestion(prompt: "🇯🇵\nما عاصمة اليابان؟", correctAnswer: "طوكيو", distractors: ["سيول", "بكين", "هونغ كونغ"], grades: 4...6),
        BankQuestion(prompt: "🏜️\nما أكبر صحراء في إسرائيل؟", correctAnswer: "النقب", distractors: ["الصحراء الكبرى", "سيناء", "وادي عربة"], grades: 2...4),
        BankQuestion(prompt: "🌍\nما أكبر قارّة في العالم؟", correctAnswer: "آسيا", distractors: ["أفريقيا", "أمريكا", "أوروبا"], grades: 4...6),
        BankQuestion(prompt: "ما هي عاصمة اليابان؟", correctAnswer: "طوكيو", distractors: ["بكين", "سيول", "بانكوك"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما أطول نهر في العالم؟", correctAnswer: "النيل", distractors: ["الأمازون", "نهر الأردن", "المسيسيبي"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "في أيّ قارّة تقع مصر؟", correctAnswer: "أفريقيا", distractors: ["آسيا", "أوروبا", "أمريكا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما أعلى جبل في العالم؟", correctAnswer: "إفرست", distractors: ["جبل الشيخ", "كليمنجارو", "مون بلان"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "أيّ بحر هو أخفض بقعة في العالم؟", correctAnswer: "البحر الميّت", distractors: ["البحر المتوسّط", "البحر الأحمر", "بحيرة طبريا"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "ما هي عاصمة أستراليا؟", correctAnswer: "كانبرا", distractors: ["سيدني", "ملبورن", "بيرث"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "كم قارّةً في العالم؟", correctAnswer: "7", distractors: ["5", "6", "8"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما أكبر محيط في العالم؟", correctAnswer: "الهادئ", distractors: ["الأطلسيّ", "الهنديّ", "المتجمّد الشماليّ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "في أيّ دولة يقع برج إيفل؟", correctAnswer: "فرنسا", distractors: ["إيطاليا", "إسبانيا", "إنجلترا"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "أيّ دولة هي قارّة كاملة أيضًا؟", correctAnswer: "أستراليا", distractors: ["الهند", "البرازيل", "روسيا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏛️\nما هي عاصمة إسرائيل؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "إيلات"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏙️\nأين يسكن كثير من الناس في مبانٍ عالية؟", correctAnswer: "في المدينة", distractors: ["في القرية", "في الغابة", "في الصحراء"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌅\nمن أيّ جهة تشرق الشمس صباحًا؟", correctAnswer: "الشرق", distractors: ["الغرب", "الشمال", "الجنوب"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌇\nفي أيّ جهة تغرب الشمس مساءً؟", correctAnswer: "الغرب", distractors: ["الشرق", "الشمال", "الجنوب"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🇮🇱\nما ألوان عَلَم إسرائيل؟", correctAnswer: "أزرق وأبيض", distractors: ["أحمر وأبيض", "أخضر وأصفر", "أسود وأبيض"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "✡️\nأيّ رمز يظهر في وسط عَلَم إسرائيل؟", correctAnswer: "نجمة داود", distractors: ["الشمعدان", "الشمس", "غصن الزيتون"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🗺️\nعلامَ يدلّ اللون الأزرق في الخريطة؟", correctAnswer: "البحر والماء", distractors: ["الجبال", "الغابات", "الصحراء"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌧️\nفي أيّ فصل يهطل معظم المطر في إسرائيل؟", correctAnswer: "في الشتاء", distractors: ["في الصيف", "في الربيع", "في الخريف"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "☀️\nأيّ فصل هو الأحرّ في إسرائيل؟", correctAnswer: "الصيف", distractors: ["الشتاء", "الربيع", "الخريف"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕎\nماذا يظهر في شعار دولة إسرائيل؟", correctAnswer: "شمعدان وغصنا زيتون", distractors: ["نجمة داود ونجوم", "أسد وعَلَم", "شمس وبحر"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏜️\nما اسم الصحراء الكبيرة في جنوب إسرائيل؟", correctAnswer: "النقب", distractors: ["الجليل", "الشارون", "الشفيلا"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "⛰️\nما اسم المنطقة الجبليّة في شمال إسرائيل؟", correctAnswer: "الجليل", distractors: ["النقب", "وادي عربة", "الشفيلا"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🧂\nما أخفض بقعة في العالم؟", correctAnswer: "البحر الميّت", distractors: ["بحيرة طبريا", "البحر المتوسّط", "البحر الأحمر"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🚰\nما اسم أكبر بحيرة مياه عذبة في إسرائيل؟", correctAnswer: "بحيرة طبريا", distractors: ["البحر الميّت", "البحر الأحمر", "البحر المتوسّط"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🏞️\nأيّ نهر يجري من بحيرة طبريا إلى البحر الميّت؟", correctAnswer: "نهر الأردن", distractors: ["النيل", "نهر الياركون", "نهر الإسكندر"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "⚓\nفي أيّ مدينة يوجد ميناء كبير وجبل الكرمل؟", correctAnswer: "حيفا", distractors: ["إيلات", "تل أبيب", "أشدود"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🐠\nعلى شاطئ أيّ بحر تقع مدينة إيلات؟", correctAnswer: "البحر الأحمر", distractors: ["البحر المتوسّط", "البحر الميّت", "بحيرة طبريا"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🐪\nأيّ مدينة تُلقَّب بعاصمة النقب؟", correctAnswer: "بئر السبع", distractors: ["ديمونة", "عراد", "إيلات"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🌡️\nأيّ مناخ يسود في النقب؟", correctAnswer: "صحراويّ — حارّ وجافّ", distractors: ["ممطر وبارد", "مثلج طوال السنة", "استوائيّ ورطب"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🧭\nأيّ دولة مجاورة تقع شمالَ إسرائيل؟", correctAnswer: "لبنان", distractors: ["مصر", "الأردن", "قبرص"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🧭\nأيّ دولة مجاورة تقع شرقَ إسرائيل؟", correctAnswer: "الأردن", distractors: ["لبنان", "مصر", "تركيا"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🐫\nأيّ دولة مجاورة تقع جنوبَ غربِ إسرائيل؟", correctAnswer: "مصر", distractors: ["الأردن", "لبنان", "اليونان"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🌏\nفي أيّ قارّة تقع إسرائيل؟", correctAnswer: "آسيا", distractors: ["أوروبا", "أفريقيا", "أمريكا"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "💧\nمن أين يأتي اليوم معظم ماء الشرب في إسرائيل؟", correctAnswer: "من تحلية مياه البحر", distractors: ["من ثلوج جبل الشيخ", "من الاستيراد من الخارج", "من آبار الصحراء فقط"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🚜\nما اسم التجمّع السكنيّ الذي يعيش أعضاؤه ويعملون فيه بالشراكة؟", correctAnswer: "كيبوتس", distractors: ["مدينة", "حيّ", "ضاحية"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🏙️\nما أكبر مدينة في إسرائيل من حيث عدد السكّان؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "ريشون لتسيون"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🚿\nما اسم المشروع الذي نقل الماء من بحيرة طبريا إلى جنوب البلاد؟", correctAnswer: "الناقل القطريّ للمياه", distractors: ["قناة السويس", "مشروع الياركون", "أنبوب إيلات"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "⛵\nبأيّ محيط يتّصل البحر المتوسّط عبر مضيق جبل طارق؟", correctAnswer: "المحيط الأطلسيّ", distractors: ["المحيط الهادئ", "المحيط الهنديّ", "المحيط المتجمّد"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🌊\nما أكبر محيط في العالم؟", correctAnswer: "المحيط الهادئ", distractors: ["المحيط الأطلسيّ", "المحيط الهنديّ", "المحيط المتجمّد"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🌏\nما أكبر قارّة في العالم؟", correctAnswer: "آسيا", distractors: ["أفريقيا", "أوروبا", "أمريكا الشماليّة"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🗼\nما هي عاصمة فرنسا؟", correctAnswer: "باريس", distractors: ["لندن", "روما", "مدريد"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🇺🇸\nما هي عاصمة الولايات المتّحدة؟", correctAnswer: "واشنطن", distractors: ["نيويورك", "لوس أنجلوس", "شيكاغو"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏞️\nأيّ نهر يُعدّ الأطول في العالم؟", correctAnswer: "النيل", distractors: ["الأمازون", "نهر الأردن", "الدانوب"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏔️\nما هو أعلى جبل في العالم؟", correctAnswer: "إفرست", distractors: ["جبل الشيخ", "كليمنجارو", "مون بلان"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏜️\nما أكبر صحراء حارّة في العالم؟", correctAnswer: "الصحراء الكبرى", distractors: ["النقب", "غوبي", "أتاكاما"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🧱\nفي أيّ دولة يقع السور العظيم؟", correctAnswer: "الصين", distractors: ["اليابان", "الهند", "مصر"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🐧\nما أبرد قارّة في العالم؟", correctAnswer: "أنتاركتيكا", distractors: ["أوروبا", "آسيا", "أستراليا"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🌴\nأيّ مناخ يسود حول خطّ الاستواء؟", correctAnswer: "استوائيّ — حارّ وممطر", distractors: ["قطبيّ — بارد جدًّا", "صحراويّ — جافّ جدًّا", "معتدل — لطيف البرودة"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🇫🇷\nما عاصمة فرنسا؟", correctAnswer: "باريس", distractors: ["مرسيليا", "ليون", "نيس"], grades: 4...6),
        BankQuestion(prompt: "🇩🇪\nما عاصمة ألمانيا؟", correctAnswer: "برلين", distractors: ["ميونخ", "هامبورغ", "فرانكفورت"], grades: 4...6),
        BankQuestion(prompt: "🇺🇸\nما عاصمة الولايات المتّحدة؟", correctAnswer: "واشنطن", distractors: ["نيويورك", "لوس أنجلوس", "شيكاغو"], grades: 4...6),
        BankQuestion(prompt: "🇨🇦\nما عاصمة كندا؟", correctAnswer: "أوتاوا", distractors: ["تورونتو", "فانكوفر", "مونتريال"], grades: 4...6),
        BankQuestion(prompt: "🇧🇷\nما عاصمة البرازيل؟", correctAnswer: "برازيليا", distractors: ["ريو دي جانيرو", "ساو باولو", "سلفادور"], grades: 4...6),
        BankQuestion(prompt: "🇦🇺\nما عاصمة أستراليا؟", correctAnswer: "كانبرا", distractors: ["سيدني", "ملبورن", "بيرث"], grades: 4...6),
        BankQuestion(prompt: "🇷🇺\nما عاصمة روسيا؟", correctAnswer: "موسكو", distractors: ["سانت بطرسبورغ", "كييف", "مينسك"], grades: 4...6),
        BankQuestion(prompt: "🇨🇳\nما عاصمة الصين؟", correctAnswer: "بكين", distractors: ["شنغهاي", "هونغ كونغ", "قوانغتشو"], grades: 4...6),
        BankQuestion(prompt: "🇮🇳\nما عاصمة الهند؟", correctAnswer: "نيودلهي", distractors: ["مومباي", "بنغالور", "كلكتّا"], grades: 4...6),
        BankQuestion(prompt: "🇲🇽\nما عاصمة المكسيك؟", correctAnswer: "مكسيكو سيتي", distractors: ["كانكون", "غوادالاخارا", "مونتيري"], grades: 4...6),
        BankQuestion(prompt: "🇦🇷\nما عاصمة الأرجنتين؟", correctAnswer: "بوينس آيرس", distractors: ["سانتياغو", "مونتيفيديو", "ليما"], grades: 4...6),
        BankQuestion(prompt: "🇪🇬\nما عاصمة مصر؟", correctAnswer: "القاهرة", distractors: ["الإسكندريّة", "الأقصر", "أسوان"], grades: 4...6),
        BankQuestion(prompt: "🇿🇦\nفي أيّ مدينة تتّخذ حكومة جنوب أفريقيا مقرّها؟", correctAnswer: "بريتوريا", distractors: ["كيب تاون", "جوهانسبرغ", "ديربان"], grades: 4...6),
        BankQuestion(prompt: "🇹🇷\nما عاصمة تركيا؟", correctAnswer: "أنقرة", distractors: ["إسطنبول", "إزمير", "بورصة"], grades: 4...6),
        BankQuestion(prompt: "🇸🇦\nما عاصمة السعوديّة؟", correctAnswer: "الرياض", distractors: ["مكّة", "جدّة", "المدينة المنوّرة"], grades: 4...6),
        BankQuestion(prompt: "🇦🇪\nما عاصمة الإمارات العربيّة المتّحدة؟", correctAnswer: "أبو ظبي", distractors: ["دبي", "الشارقة", "عجمان"], grades: 4...6),
        BankQuestion(prompt: "🇰🇷\nما عاصمة كوريا الجنوبيّة؟", correctAnswer: "سيول", distractors: ["بوسان", "إنتشون", "بيونغ يانغ"], grades: 4...6),
        BankQuestion(prompt: "🇮🇱\nما أكثر بحر ملوحةً في إسرائيل؟", correctAnswer: "البحر الميّت", distractors: ["بحيرة طبريا", "البحر المتوسّط", "البحر الأحمر"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nما أكبر بحيرة مياه عذبة في إسرائيل؟", correctAnswer: "بحيرة طبريا", distractors: ["البحر الميّت", "بحيرة مونفورت", "البحر الأحمر"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nما أعلى جبل في إسرائيل؟", correctAnswer: "جبل الشيخ", distractors: ["جبل ميرون", "جبل الطور", "جبل الكرمل"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nما أطول نهر في إسرائيل؟", correctAnswer: "نهر الأردن", distractors: ["نهر الياركون", "نهر المقطّع", "نهر الإسكندر"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nأيّ مدينة تقع قرب البحر الميّت؟", correctAnswer: "عراد", distractors: ["الناصرة", "صفد", "إيلات"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nأيّ مدينة هي الأبعد جنوبًا في إسرائيل؟", correctAnswer: "إيلات", distractors: ["بئر السبع", "عراد", "ديمونة"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nأيّ مدينة هي الأبعد شمالًا؟", correctAnswer: "المطلّة", distractors: ["كريات شمونة", "صفد", "طبريا"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nأيّ مدينة هي عاصمة إسرائيل؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "بئر السبع"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nكم لواءً إداريًّا في إسرائيل؟", correctAnswer: "6", distractors: ["4", "5", "8"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nأيّ بحر يقع في غرب إسرائيل؟", correctAnswer: "البحر المتوسّط", distractors: ["البحر الأحمر", "البحر الميّت", "المحيط الهنديّ"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nأيّ بحر يقع في جنوب إسرائيل؟", correctAnswer: "البحر الأحمر", distractors: ["البحر المتوسّط", "البحر الميّت", "البحر الأسود"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nأيّ دولة تحدّ إسرائيل من الشمال؟", correctAnswer: "لبنان", distractors: ["مصر", "تركيا", "الأردن"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nأيّ دولة تحدّ إسرائيل من الشرق؟", correctAnswer: "الأردن", distractors: ["لبنان", "مصر", "العراق"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nأيّ دولة تحدّ إسرائيل من الجنوب؟", correctAnswer: "مصر", distractors: ["السودان", "سوريا", "السعوديّة"], grades: 2...4),
        BankQuestion(prompt: "🌎\nكم محيطًا في العالم؟", correctAnswer: "5", distractors: ["3", "4", "7"], grades: 4...6),
        BankQuestion(prompt: "🌊\nأيّ محيط هو الأكبر؟", correctAnswer: "الهادئ", distractors: ["الأطلسيّ", "الهنديّ", "المتجمّد الشماليّ"], grades: 4...6),
        BankQuestion(prompt: "🌍\nما أصغر قارّة في العالم؟", correctAnswer: "أستراليا", distractors: ["أوروبا", "أنتاركتيكا", "أفريقيا"], grades: 4...6),
        BankQuestion(prompt: "🐧\nأيّ قارّة هي الأبرد؟", correctAnswer: "أنتاركتيكا", distractors: ["آسيا", "أوروبا", "أمريكا"], grades: 4...6),
        BankQuestion(prompt: "🦒\nأيّ قارّة هي الأحرّ في المعدّل؟", correctAnswer: "أفريقيا", distractors: ["آسيا", "أستراليا", "أمريكا"], grades: 4...6),
        BankQuestion(prompt: "🌍\nأيّ قارّة فيها أكبر عدد من الدول؟", correctAnswer: "أفريقيا", distractors: ["آسيا", "أوروبا", "أمريكا"], grades: 4...6),
        BankQuestion(prompt: "🗼\nبرج إيفل يقع في...؟", correctAnswer: "باريس", distractors: ["لندن", "روما", "برلين"], grades: 4...6),
        BankQuestion(prompt: "🗽\nتمثال الحرّيّة يقع في...؟", correctAnswer: "نيويورك", distractors: ["واشنطن", "شيكاغو", "ميامي"], grades: 4...6),
        BankQuestion(prompt: "🗿\nتماثيل المواي تقع في...؟", correctAnswer: "جزيرة الفصح", distractors: ["المكسيك", "بيرو", "إندونيسيا"], grades: 4...6),
        BankQuestion(prompt: "🏯\nلماذا بُني سور الصين العظيم؟", correctAnswer: "للدفاع ضدّ الغزاة", distractors: ["لتزيين المنظر", "لتخزين المحاصيل", "لسباقات الخيل"], grades: 4...6),
        BankQuestion(prompt: "🕌\nإلى أيّ مدينة يتّجه المسلمون في صلاتهم؟", correctAnswer: "مكّة", distractors: ["المدينة المنوّرة", "القاهرة", "إسطنبول"], grades: 4...6),
        BankQuestion(prompt: "🕍\nإلى أيّ مدينة يتّجه اليهود في صلاتهم؟", correctAnswer: "القدس", distractors: ["طبريا", "صفد", "تل أبيب"], grades: 4...6),
        BankQuestion(prompt: "⛪\nفي أيّ دولة يقيم البابا؟", correctAnswer: "الفاتيكان", distractors: ["فرنسا", "إسبانيا", "البرتغال"], grades: 4...6),
        BankQuestion(prompt: "🌊\nأيّ نهر هو الأطول في أفريقيا؟", correctAnswer: "النيل", distractors: ["الكونغو", "النيجر", "الزمبيزي"], grades: 4...6),
        BankQuestion(prompt: "🌊\nأيّ نهر هو الأطول في أمريكا الجنوبيّة؟", correctAnswer: "الأمازون", distractors: ["بارانا", "باراغواي", "أورينوكو"], grades: 4...6),
        BankQuestion(prompt: "🌊\nأيّ نهر هو الأطول في أوروبا؟", correctAnswer: "الفولغا", distractors: ["الدانوب", "الراين", "السين"], grades: 4...6),
        BankQuestion(prompt: "🏔️\nأيّ جبل يقع في فرنسا؟", correctAnswer: "مون بلان", distractors: ["إفرست", "كليمنجارو", "فوجي"], grades: 4...6),
        BankQuestion(prompt: "🏔️\nأيّ سلسلة جبال تقع في أمريكا الجنوبيّة؟", correctAnswer: "الأنديز", distractors: ["الألب", "الهيمالايا", "الأورال"], grades: 4...6),
        BankQuestion(prompt: "🦁\nأين تعيش الأسود في البرّيّة؟", correctAnswer: "في أفريقيا", distractors: ["في أنتاركتيكا", "في إسرائيل", "في كندا"], grades: 4...6),
        BankQuestion(prompt: "🐪\nأين نرى الجِمال في إسرائيل؟", correctAnswer: "في الصحراء", distractors: ["في البحر", "في الثلج", "في الغابة المطيرة"], grades: 2...4),
        BankQuestion(prompt: "🐨\nفي أيّ بلد يعيش الكوالا؟", correctAnswer: "أستراليا", distractors: ["الصين", "الهند", "البرازيل"], grades: 4...6),
        BankQuestion(prompt: "🐻‍❄️\nأين يعيش الدبّ الأبيض؟", correctAnswer: "في القطب الشماليّ", distractors: ["في الصحراء", "في الغابة المطيرة", "في أفريقيا"], grades: 4...6),
        BankQuestion(prompt: "🦓\nفي أيّ قارّة يعيش الحمار الوحشيّ؟", correctAnswer: "أفريقيا", distractors: ["أوروبا", "أستراليا", "أنتاركتيكا"], grades: 4...6),
        BankQuestion(prompt: "🦜\nأين تعيش الببّغاوات الملوّنة الكثيرة؟", correctAnswer: "في الغابة المطيرة", distractors: ["في القطب", "في الصحراء", "على الثلج"], grades: 4...6),
        BankQuestion(prompt: "🏖️\nأيّ مدينة كبيرة تقع على شاطئ البحر المتوسّط؟", correctAnswer: "تل أبيب", distractors: ["القدس", "بئر السبع", "ديمونة"], grades: 2...4),
        BankQuestion(prompt: "⚓\nأيّ مدينة ميناء كبيرة تقع في شمال إسرائيل؟", correctAnswer: "حيفا", distractors: ["إيلات", "طبريا", "صفد"], grades: 2...4),
        BankQuestion(prompt: "🌊\nعلى ضفاف أيّ بحر تقع مدينة إيلات؟", correctAnswer: "البحر الأحمر", distractors: ["البحر الميّت", "البحر المتوسّط", "بحيرة طبريا"], grades: 2...4),
        BankQuestion(prompt: "🐟\nما اسم البحيرة التي يُصطاد منها السمك في شمال إسرائيل؟", correctAnswer: "بحيرة طبريا", distractors: ["البحر الميّت", "البحر المتوسّط", "البحر الأحمر"], grades: 2...4),
        BankQuestion(prompt: "🏛️\nأيّ مدينة قديمة مشهورة تقع في الشمال على جبل؟", correctAnswer: "صفد", distractors: ["إيلات", "أشدود", "هرتسليا"], grades: 2...4),
        BankQuestion(prompt: "🧭\nفي الخريطة، أيّ اتّجاه يقع في الأعلى؟", correctAnswer: "الشمال", distractors: ["الجنوب", "الشرق", "الغرب"], grades: 2...4),
        BankQuestion(prompt: "☀️\nمن أيّ جهة تشرق الشمس صباحًا؟", correctAnswer: "الشرق", distractors: ["الغرب", "الشمال", "الجنوب"], grades: 2...4),
        BankQuestion(prompt: "🇬🇷\nما عاصمة اليونان؟", correctAnswer: "أثينا", distractors: ["روما", "إسطنبول", "القاهرة"], grades: 4...6),
        BankQuestion(prompt: "🇵🇹\nما عاصمة البرتغال؟", correctAnswer: "لشبونة", distractors: ["مدريد", "برشلونة", "باريس"], grades: 4...6),
        BankQuestion(prompt: "🇳🇱\nما عاصمة هولندا؟", correctAnswer: "أمستردام", distractors: ["بروكسل", "برلين", "باريس"], grades: 4...6),
        BankQuestion(prompt: "🇨🇭\nما عاصمة سويسرا؟", correctAnswer: "برن", distractors: ["زيورخ", "جنيف", "فيينا"], grades: 4...6),
        BankQuestion(prompt: "🇸🇪\nما عاصمة السويد؟", correctAnswer: "ستوكهولم", distractors: ["أوسلو", "كوبنهاغن", "هلسنكي"], grades: 4...6),
        BankQuestion(prompt: "🌋\nفي أيّ جهة من إسرائيل تقع مدينة إيلات؟", correctAnswer: "في الجنوب", distractors: ["في الشمال", "في الشرق", "في الغرب"], grades: 2...4),
        BankQuestion(prompt: "🏔️\nفي أيّ منطقة في إسرائيل يتساقط الثلج شتاءً؟", correctAnswer: "جبل الشيخ", distractors: ["إيلات", "النقب", "تل أبيب"], grades: 2...4),
        BankQuestion(prompt: "🐊\nفي أيّ نهر أفريقيّ تعيش التماسيح؟", correctAnswer: "النيل", distractors: ["الأمازون", "نهر الأردن", "نهر الياركون"], grades: 4...6),
        BankQuestion(prompt: "🦅\nفي أيّ قارّة توجد أكبر غابة مطيرة؟", correctAnswer: "أمريكا الجنوبيّة", distractors: ["أوروبا", "أستراليا", "أنتاركتيكا"], grades: 4...6),
        BankQuestion(prompt: "🐅\nفي أيّ قارّة يعيش نمر البنغال في البرّيّة؟", correctAnswer: "آسيا", distractors: ["أنتاركتيكا", "أستراليا", "أوروبا"], grades: 4...6),
        BankQuestion(prompt: "🏝️\nأستراليا قارّة، وهي أيضًا...؟", correctAnswer: "دولة", distractors: ["نهر", "جبل", "محيط"], grades: 4...6),
        BankQuestion(prompt: "🌍\nفي أيّ قارّة تقع مصر؟", correctAnswer: "أفريقيا", distractors: ["آسيا", "أوروبا", "أمريكا الجنوبيّة"], grades: 4...6),
        BankQuestion(prompt: "🌎\nفي أيّ قارّة تقع البرازيل؟", correctAnswer: "أمريكا الجنوبيّة", distractors: ["أفريقيا", "أوروبا", "آسيا"], grades: 4...6),
        BankQuestion(prompt: "🐫\nأيّ صحراء ضخمة تقع في شمال أفريقيا؟", correctAnswer: "الصحراء الكبرى", distractors: ["النقب", "سيناء", "غوبي"], grades: 4...6),
        BankQuestion(prompt: "🏞️\nأيّ نهر يجري في إسرائيل ويصبّ في البحر الميّت؟", correctAnswer: "نهر الأردن", distractors: ["النيل", "الأمازون", "نهر الياركون"], grades: 2...4),
        BankQuestion(prompt: "🌊\nأيّ بحيرة مالحة تقع في جنوب شرق إسرائيل؟", correctAnswer: "البحر الميّت", distractors: ["بحيرة طبريا", "البحر المتوسّط", "البحر الأحمر"], grades: 2...4),
        BankQuestion(prompt: "🦬\nفي أيّ قارّة يعيش البيسون الكبير في السهول؟", correctAnswer: "أمريكا الشماليّة", distractors: ["أنتاركتيكا", "أوروبا", "أستراليا"], grades: 4...6),
        BankQuestion(prompt: "🌐\nماذا نسمّي النموذج المستدير الذي يُظهر العالم كلّه؟", correctAnswer: "مُجسَّم الكرة الأرضيّة", distractors: ["البوصلة", "التلسكوب", "الساعة"], grades: 2...4),
        BankQuestion(prompt: "🗺️\nعلى ماذا نرسم القارّات والبحار؟", correctAnswer: "الخريطة", distractors: ["التقويم", "كتاب الطبخ", "الشهادة"], grades: 2...4),
        BankQuestion(prompt: "🐘\nفي أيّ قارّة تعيش أكبر الفِيَلة؟", correctAnswer: "أفريقيا", distractors: ["أوروبا", "أستراليا", "أنتاركتيكا"], grades: 4...6),
        BankQuestion(prompt: "🇮🇪\nما عاصمة إيرلندا؟", correctAnswer: "دبلن", distractors: ["لندن", "أدنبرة", "أمستردام"], grades: 4...6),
        BankQuestion(prompt: "🏜️\nأيّ منطقة تشغل معظم جنوب إسرائيل؟", correctAnswer: "النقب", distractors: ["الجليل", "الشارون", "الكرمل"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nما هي عاصمة إسرائيل؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "إيلات"], grades: 2...4),
        BankQuestion(prompt: "🗼\nفي أيّ مدينة يقع برج إيفل؟", correctAnswer: "باريس", distractors: ["لندن", "روما", "مدريد"], grades: 4...6),
        BankQuestion(prompt: "🌊\nماذا نسمّي أكثر بحر ملوحةً في إسرائيل؟", correctAnswer: "البحر الميّت", distractors: ["البحر المتوسّط", "بحيرة طبريا", "البحر الأحمر"], grades: 2...4),
        BankQuestion(prompt: "🐘\nفي أيّ قارّة تعيش الفِيَلة والأسود في البرّيّة؟", correctAnswer: "أفريقيا", distractors: ["أوروبا", "أنتاركتيكا", "أستراليا"], grades: 4...6),
        BankQuestion(prompt: "🐧\nأين يعيش البطريق في البرد الشديد؟", correctAnswer: "أنتاركتيكا", distractors: ["أوروبا", "إسرائيل", "الصحراء"], grades: 4...6),
        BankQuestion(prompt: "🦘\nفي أيّ بلد يعيش الكنغر؟", correctAnswer: "أستراليا", distractors: ["إسرائيل", "مصر", "كندا"], grades: 4...6),
        BankQuestion(prompt: "🐼\nفي أيّ بلد يعيش دبّ الباندا؟", correctAnswer: "الصين", distractors: ["فرنسا", "البرازيل", "اليونان"], grades: 4...6),
        BankQuestion(prompt: "🏰\nما هي عاصمة فرنسا؟", correctAnswer: "باريس", distractors: ["برلين", "أثينا", "القاهرة"], grades: 4...6),
        BankQuestion(prompt: "🎡\nما هي عاصمة إنجلترا؟", correctAnswer: "لندن", distractors: ["باريس", "روما", "لشبونة"], grades: 4...6),
        BankQuestion(prompt: "🍕\nما هي عاصمة إيطاليا؟", correctAnswer: "روما", distractors: ["ميلانو", "باريس", "فيينا"], grades: 4...6),
        BankQuestion(prompt: "🐪\nفي أيّ مكان يوجد رمل كثير ولا ماء تقريبًا؟", correctAnswer: "الصحراء", distractors: ["الغابة", "المحيط", "القطب"], grades: 0...2),
        BankQuestion(prompt: "⛰️\nما اسم الجبل المرتفع في شمال إسرائيل الذي يتساقط عليه الثلج؟", correctAnswer: "جبل الشيخ", distractors: ["جبل الطور", "جبل الكرمل", "مسادا"], grades: 2...4),
        BankQuestion(prompt: "💧\nما اسم البحيرة الكبيرة في إسرائيل التي نشرب من مائها؟", correctAnswer: "بحيرة طبريا", distractors: ["البحر الميّت", "نهر الياركون", "البحر المتوسّط"], grades: 2...4),
        BankQuestion(prompt: "🏖️\nما اسم المدينة في جنوب إسرائيل التي فيها بحر وشِعاب مرجانيّة؟", correctAnswer: "إيلات", distractors: ["حيفا", "صفد", "طبريا"], grades: 2...4),
        BankQuestion(prompt: "🚢\nفي أيّ مدينة في إسرائيل ميناء بحريّ كبير وجبل الكرمل؟", correctAnswer: "حيفا", distractors: ["القدس", "بئر السبع", "إيلات"], grades: 2...4),
        BankQuestion(prompt: "🇺🇸\nما عاصمة الولايات المتّحدة الأمريكيّة؟", correctAnswer: "واشنطن", distractors: ["نيويورك", "لوس أنجلوس", "شيكاغو"], grades: 4...6),
        BankQuestion(prompt: "🇪🇬\nما هي عاصمة مصر؟", correctAnswer: "القاهرة", distractors: ["القدس", "عمّان", "دمشق"], grades: 4...6),
        BankQuestion(prompt: "🐠\nما اسم بحر إيلات ذي الأسماك الملوّنة؟", correctAnswer: "البحر الأحمر", distractors: ["البحر الميّت", "بحيرة طبريا", "البحر المتوسّط"], grades: 2...4),
        BankQuestion(prompt: "🌍\nما القارّة التي تقع فيها إسرائيل؟", correctAnswer: "آسيا", distractors: ["أفريقيا", "أوروبا", "أستراليا"], grades: 4...6),
        BankQuestion(prompt: "🦁\nماذا نسمّي المكان الذي نرى فيه حيوانات خلف سياج؟", correctAnswer: "حديقة الحيوانات", distractors: ["الغابة", "الصحراء", "البحر"], grades: 0...2),
        BankQuestion(prompt: "🦅\nما اسم النهر الذي يمرّ في تل أبيب؟", correctAnswer: "نهر الياركون", distractors: ["نهر الأردن", "النيل", "نهر المقطّع"], grades: 2...4),
        BankQuestion(prompt: "🛶\nما اسم النهر الذي يشكّل الحدود الشرقيّة لإسرائيل؟", correctAnswer: "نهر الأردن", distractors: ["نهر الياركون", "النيل", "نهر المقطّع"], grades: 2...4),
        BankQuestion(prompt: "🐻\nفي أيّ مكان توجد أشجار عالية كثيرة وحيوانات برّيّة؟", correctAnswer: "الغابة", distractors: ["الصحراء", "المدينة", "الشاطئ"], grades: 0...2),
        BankQuestion(prompt: "🇯🇵\nفي أيّ بلد شمسٌ على العَلَم ويأكلون السوشي؟", correctAnswer: "اليابان", distractors: ["إسرائيل", "إيطاليا", "المكسيك"], grades: 4...6),
        BankQuestion(prompt: "🏛️\nما هي عاصمة اليونان؟", correctAnswer: "أثينا", distractors: ["روما", "القاهرة", "باريس"], grades: 4...6),
        BankQuestion(prompt: "🌐\nكم قارّةً في العالم؟", correctAnswer: "سبع", distractors: ["ثلاث", "خمس", "عشر"], grades: 4...6),
        BankQuestion(prompt: "🧱\nفي أي مدينة يقع الحائط الغربي، المعروف عند العرب بحائط البراق؟", correctAnswer: "القدس", distractors: ["تل أبيب", "إيلات", "حيفا"], grades: 2...4),
        BankQuestion(prompt: "🐫\nفي أي قارّة تقع الصحراء الكبرى العملاقة؟", correctAnswer: "أفريقيا", distractors: ["أوروبا", "آسيا", "أستراليا"], grades: 4...6),
        BankQuestion(prompt: "❄️\nما اسم المكان الأشدّ برودة في العالم والمليء بالجليد؟", correctAnswer: "القطب", distractors: ["الصحراء", "الغابة", "المزرعة"], grades: 0...2),
        BankQuestion(prompt: "كم قارّة في العالم؟", correctAnswer: "سبع", distractors: ["خمس", "ستّ", "ثماني"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "ما عاصمة إسرائيل؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "إيلات"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الأكبر من بين هذه؟", correctAnswer: "قارّة", distractors: ["جزيرة", "قرية", "مدينة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي المسطّح المائي الضخم جدًّا في العالم؟", correctAnswer: "محيط", distractors: ["بِركة سباحة", "بِركة ماء صغيرة", "كوب ماء"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "من أي جهة تشرق الشمس في الصباح؟", correctAnswer: "الشرق", distractors: ["الغرب", "الشمال", "الجنوب"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما اسم البحر الكبير الذي يقع غرب إسرائيل؟", correctAnswer: "البحر الأبيض المتوسّط", distractors: ["البحر الميت", "بحيرة طبريا", "البحر الأسود"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "في أي قارّة تقع إسرائيل؟", correctAnswer: "آسيا", distractors: ["أوروبا", "أفريقيا", "أستراليا"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "ماذا نسمّي الأرض المحاطة بالماء من كل الجهات؟", correctAnswer: "جزيرة", distractors: ["جبل", "صحراء", "وادٍ"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي الرسم الذي يُظهر البلدان والبحار؟", correctAnswer: "خريطة", distractors: ["كتاب", "ساعة", "لعبة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي الكرة الصغيرة التي تُظهر العالم كلّه؟", correctAnswer: "مجسّم الكرة الأرضية", distractors: ["منظار", "آلة تصوير", "كرة قدم"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا يوجد في الأعلى في معظم الخرائط؟", correctAnswer: "الشمال", distractors: ["الجنوب", "الشرق", "الغرب"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي مكانًا فيه رمل كثير وحرّ شديد وقليل من الماء؟", correctAnswer: "صحراء", distractors: ["غابة", "محيط", "بحيرة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي مكانًا مرتفعًا جدًّا له قمّة؟", correctAnswer: "جبل", distractors: ["وادٍ", "شاطئ", "شارع"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي الرمل الذي بجانب البحر؟", correctAnswer: "الشاطئ", distractors: ["الجبل", "الغابة", "الصحراء"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "في أي بحر في إسرائيل يمكن الطفو بسهولة؟", correctAnswer: "البحر الميت", distractors: ["بحيرة طبريا", "البحر الأبيض المتوسّط", "البحر الأحمر"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما اسم البحيرة الكبيرة في شمال إسرائيل؟", correctAnswer: "بحيرة طبريا", distractors: ["البحر الميت", "نهر الأردن", "البحر الأبيض المتوسّط"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما عاصمة فرنسا؟", correctAnswer: "باريس", distractors: ["لندن", "روما", "مدريد"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "ماذا نسمّي الماء الجاري الذي يشقّ طريقه في الأرض؟", correctAnswer: "نهر", distractors: ["جبل", "صحراء", "جزيرة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "كم محيطًا كبيرًا في العالم؟", correctAnswer: "خمسة", distractors: ["اثنان", "ثلاثة", "عشرة"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "أي مدينة تقع على شاطئ البحر الأحمر في جنوب إسرائيل؟", correctAnswer: "إيلات", distractors: ["القدس", "حيفا", "صفد"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الاتّجاه المقابل للشمال؟", correctAnswer: "الجنوب", distractors: ["الشرق", "الغرب", "الأعلى"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي مكانًا فيه أشجار كثيرة معًا؟", correctAnswer: "غابة", distractors: ["صحراء", "شاطئ", "جبل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "في أي قارّة تقع مصر بأهراماتها؟", correctAnswer: "أفريقيا", distractors: ["أوروبا", "آسيا", "أنتاركتيكا"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "أي قارّة مغطّاة كلّها بالجليد والثلج؟", correctAnswer: "أنتاركتيكا", distractors: ["أفريقيا", "آسيا", "أوروبا"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "ماذا نسمّي المكان المنخفض بين جبلين؟", correctAnswer: "وادٍ", distractors: ["القمّة", "الشاطئ", "الجزيرة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي المكان الذي يسكن فيه الناس معًا وفيه بيوت وشوارع كثيرة؟", correctAnswer: "مدينة", distractors: ["صحراء", "بحر", "جبل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الذي يغطّي الجزء الأكبر من سطح الكرة الأرضية؟", correctAnswer: "الماء", distractors: ["اليابسة", "الجبال", "الرمال"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما اسم الدولة التي نعيش فيها؟", correctAnswer: "إسرائيل", distractors: ["مصر", "فرنسا", "اليونان"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الاتّجاه المعاكس للشرق؟", correctAnswer: "الغرب", distractors: ["الشمال", "الجنوب", "الأسفل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما عاصمة إيطاليا؟", correctAnswer: "روما", distractors: ["باريس", "أثينا", "لشبونة"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "في أي دولة يوجد برج إيفل؟", correctAnswer: "فرنسا", distractors: ["إيطاليا", "إسبانيا", "إنجلترا"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "ما اسم الماء الذي يمكن شربه، مثل ماء بحيرة طبريا والأنهار؟", correctAnswer: "مياه عذبة", distractors: ["مياه مالحة", "رمل", "طين"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الذي يدلّنا على الاتّجاهات عندما نذهب في رحلة؟", correctAnswer: "البوصلة", distractors: ["الساعة", "المنظار", "المصباح"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما عاصمة مصر؟", correctAnswer: "القاهرة", distractors: ["باريس", "روما", "أثينا"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "أي مدينة كبيرة تقع على شاطئ البحر الأبيض المتوسّط في وسط إسرائيل؟", correctAnswer: "تل أبيب", distractors: ["صفد", "إيلات", "طبريا"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أي مدينة ميناء كبيرة تقع في شمال إسرائيل على البحر؟", correctAnswer: "حيفا", distractors: ["إيلات", "القدس", "بئر السبع"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أي قارّة هي أيضًا دولة واحدة كبيرة؟", correctAnswer: "أستراليا", distractors: ["آسيا", "أوروبا", "أفريقيا"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "ماذا نسمّي الطريق الواسعة التي تسير عليها السيارات؟", correctAnswer: "شارع", distractors: ["نهر", "جبل", "غابة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما عاصمة إنجلترا؟", correctAnswer: "لندن", distractors: ["باريس", "روما", "برلين"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "أي مكان في العالم هو الأشدّ برودة؟", correctAnswer: "القطب", distractors: ["الصحراء", "الشاطئ", "المدينة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الذي ينمو بكثرة في المكان الذي نسمّيه غابة؟", correctAnswer: "الأشجار", distractors: ["الرمل", "الجليد", "الحجارة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما اللون الذي يدلّ على الماء في معظم الخرائط؟", correctAnswer: "الأزرق", distractors: ["الأخضر", "البنّي", "الأحمر"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما اسم الحيوان الكبير الذي يعيش في أفريقيا وله خرطوم طويل؟", correctAnswer: "الفيل", distractors: ["الدبّ", "البطريق", "الجمل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "في أي مكان تعيش الجمال؟", correctAnswer: "في الصحراء", distractors: ["في القطب", "في البحر", "في المحيط"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي الرقائق البيضاء التي تتساقط في الأماكن المرتفعة والباردة؟", correctAnswer: "الثلج", distractors: ["الرمل", "المطر الحارّ", "الغبار"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الاتّجاه المقابل للجنوب؟", correctAnswer: "الشمال", distractors: ["الشرق", "الغرب", "الأعلى"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي المكان الذي تلتقي فيه اليابسة بالبحر؟", correctAnswer: "الشاطئ", distractors: ["القمّة", "الوادي", "الصحراء"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أي مسطّح مائي أكبر بكثير من البحيرة؟", correctAnswer: "المحيط", distractors: ["البِركة", "الغدير", "البئر"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما عاصمة إسبانيا؟", correctAnswer: "مدريد", distractors: ["لشبونة", "باريس", "روما"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "في أي دولة يوجد السور العظيم الذي بُني قديمًا لحماية البلاد؟", correctAnswer: "الصين", distractors: ["اليابان", "الهند", "فرنسا"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "أي قارّة هي الأكبر في العالم؟", correctAnswer: "آسيا", distractors: ["أوروبا", "أستراليا", "أنتاركتيكا"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي محيط هو الأكبر في العالم؟", correctAnswer: "المحيط الهادئ", distractors: ["المحيط الأطلسي", "المحيط الهندي", "المحيط المتجمّد الشمالي"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة اليونان؟", correctAnswer: "أثينا", distractors: ["روما", "مدريد", "أنقرة"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "في أي دولة يوجد برج بيزا المائل؟", correctAnswer: "إيطاليا", distractors: ["فرنسا", "إسبانيا", "اليونان"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما أخفض مكان على سطح الكرة الأرضية؟", correctAnswer: "البحر الميت", distractors: ["بحيرة طبريا", "البحر الأبيض المتوسّط", "البحر الأحمر"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما اسم النهر الطويل الذي يمرّ في مصر؟", correctAnswer: "نهر النيل", distractors: ["نهر الأردن", "نهر الياركون", "نهر الدانوب"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما اسم النهر الرئيسي في إسرائيل الذي يصبّ في بحيرة طبريا والبحر الميت؟", correctAnswer: "نهر الأردن", distractors: ["نهر النيل", "نهر الياركون", "نهر الأمازون"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما عاصمة ألمانيا؟", correctAnswer: "برلين", distractors: ["باريس", "فيينا", "أمستردام"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة روسيا؟", correctAnswer: "موسكو", distractors: ["وارسو", "كييف", "برلين"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "في أي دولة يوجد تمثال الحرية؟", correctAnswer: "الولايات المتحدة", distractors: ["كندا", "إنجلترا", "البرازيل"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي مدينة قديمة في شمال إسرائيل تقوم على جبل وتشتهر بالفنّ؟", correctAnswer: "صفد", distractors: ["إيلات", "تل أبيب", "أشدود"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أي مدينة كبيرة تقع في جنوب إسرائيل وتُعدّ عاصمة النقب؟", correctAnswer: "بئر السبع", distractors: ["حيفا", "طبريا", "نتانيا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "في أي قارّة تقع البرازيل؟", correctAnswer: "أمريكا الجنوبية", distractors: ["أمريكا الشمالية", "أفريقيا", "آسيا"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة الولايات المتحدة؟", correctAnswer: "واشنطن", distractors: ["نيويورك", "لوس أنجلوس", "شيكاغو"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة كندا؟", correctAnswer: "أوتاوا", distractors: ["تورونتو", "مونتريال", "فانكوفر"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي جبل هو الأعلى في العالم؟", correctAnswer: "جبل إفرست", distractors: ["جبل مونبلان", "جبل الشيخ", "جبل فوجي"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما أعلى جبل في إسرائيل؟", correctAnswer: "جبل الشيخ", distractors: ["جبل الطور", "جبل الكرمل", "مسادا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أي بحر يقع بين إيلات ومصر؟", correctAnswer: "البحر الأحمر", distractors: ["البحر الأبيض المتوسّط", "البحر الميت", "البحر الأسود"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما عاصمة اليابان؟", correctAnswer: "طوكيو", distractors: ["بكين", "سيول", "بانكوك"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة الصين؟", correctAnswer: "بكين", distractors: ["طوكيو", "شنغهاي", "هونغ كونغ"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة هولندا؟", correctAnswer: "أمستردام", distractors: ["بروكسل", "برلين", "باريس"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة البرتغال؟", correctAnswer: "لشبونة", distractors: ["مدريد", "روما", "باريس"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما اسم الخطّ الوهمي الذي يقسم الكرة الأرضية إلى شمال وجنوب؟", correctAnswer: "خطّ الاستواء", distractors: ["خطّ الشاطئ", "خطّ الحدود", "خطّ الأفق"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "في أي قارّة تقع دولة الهند؟", correctAnswer: "آسيا", distractors: ["أفريقيا", "أوروبا", "أستراليا"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما اسم أقصى نقطة في شمال الكرة الأرضية؟", correctAnswer: "القطب الشمالي", distractors: ["القطب الجنوبي", "خطّ الاستواء", "الشرق"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "في أي قطب تعيش الدببة البيضاء؟", correctAnswer: "القطب الشمالي", distractors: ["القطب الجنوبي", "خطّ الاستواء", "الصحراء"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "في أي مكان تعيش طيور البطريق؟", correctAnswer: "أنتاركتيكا", distractors: ["الصحراء الكبرى", "غابة الأمازون", "صحراء النقب"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما أكبر صحراء حارّة في العالم؟", correctAnswer: "الصحراء الكبرى", distractors: ["صحراء النقب", "صحراء يهودا", "صحراء غوبي"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي قارّة تقع بين المحيط الهادئ والمحيط الأطلسي في الجزء الشمالي؟", correctAnswer: "أمريكا الشمالية", distractors: ["أمريكا الجنوبية", "أوروبا", "آسيا"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة تركيا؟", correctAnswer: "أنقرة", distractors: ["إسطنبول", "أثينا", "روما"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي بحر يقع بين أوروبا وأفريقيا؟", correctAnswer: "البحر الأبيض المتوسّط", distractors: ["البحر الأحمر", "البحر الأسود", "البحر الميت"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "في أي دولة يوجد تاج محلّ؟", correctAnswer: "الهند", distractors: ["الصين", "اليابان", "مصر"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ماذا نسمّي مجموعة من الجزر القريبة بعضها من بعض؟", correctAnswer: "أرخبيل", distractors: ["قارّة", "خليج", "شبه جزيرة"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ماذا نسمّي شريط اليابسة الذي يمتدّ داخل البحر ويحيط به الماء من ثلاث جهات؟", correctAnswer: "شبه جزيرة", distractors: ["جزيرة", "خليج", "بحيرة"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "إلى أي اتّجاه يشير سهم البوصلة دائمًا؟", correctAnswer: "الشمال", distractors: ["الجنوب", "الشرق", "الغرب"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما اسم أصغر قارّة في العالم؟", correctAnswer: "أستراليا", distractors: ["أوروبا", "أفريقيا", "آسيا"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "في أي دولة يمكن رؤية الكنغر في الطبيعة؟", correctAnswer: "أستراليا", distractors: ["كندا", "فرنسا", "مصر"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي بحر يفصل بين أوروبا وآسيا ويحمل اسم لون؟", correctAnswer: "البحر الأسود", distractors: ["البحر الأحمر", "البحر الأصفر", "البحر الكاريبي"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة الأرجنتين؟", correctAnswer: "بوينس آيرس", distractors: ["ريو دي جانيرو", "سانتياغو", "ليما"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي دولة هي الأكبر مساحةً في العالم؟", correctAnswer: "روسيا", distractors: ["الصين", "كندا", "الولايات المتحدة"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي مدينة في إسرائيل تقع على شاطئ البحيرة الكبيرة في الشمال؟", correctAnswer: "طبريا", distractors: ["إيلات", "بئر السبع", "عسقلان"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أي قارّة تقع جنوب أوروبا، عبر البحر الأبيض المتوسّط؟", correctAnswer: "أفريقيا", distractors: ["آسيا", "أستراليا", "أمريكا الشمالية"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة أستراليا؟", correctAnswer: "كانبرا", distractors: ["سيدني", "ملبورن", "بيرث"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي محيط يقع بين أوروبا وأمريكا؟", correctAnswer: "المحيط الأطلسي", distractors: ["المحيط الهادئ", "المحيط الهندي", "المحيط المتجمّد الشمالي"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي جملة صحيحة عن بحيرة طبريا؟", correctAnswer: "هي بحيرة ماء عذب", distractors: ["هي بحر شديد الملوحة", "هي محيط", "هي صحراء"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "في أي اتّجاه من القدس تقع إيلات؟", correctAnswer: "الجنوب", distractors: ["الشمال", "الشرق", "الغرب"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ماذا نسمّي الممرّ المائي الرفيع بين قارّتين؟", correctAnswer: "مضيق", distractors: ["القمّة", "الوادي", "الشلّال"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أي موقع مرتفع مشهور في جنوب إسرائيل يقوم على قمّته حصن قديم؟", correctAnswer: "مسادا", distractors: ["جبل الشيخ", "جبل الطور", "جبل الكرمل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما أطول نهر في العالم؟", correctAnswer: "نهر النيل", distractors: ["نهر الأردن", "نهر التايمز", "نهر الياركون"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما النهر الأغزر مياهًا في العالم، والذي يمرّ في أمريكا الجنوبية؟", correctAnswer: "نهر الأمازون", distractors: ["نهر النيل", "نهر المسيسيبي", "نهر الدانوب"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي سلسلة جبال هي الأعلى في العالم وتقع في آسيا؟", correctAnswer: "الهيمالايا", distractors: ["جبال الألب", "جبال الأنديز", "جبال روكي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي سلسلة جبال مشهورة تمتدّ في أوروبا عبر فرنسا وسويسرا؟", correctAnswer: "جبال الألب", distractors: ["الهيمالايا", "جبال الأنديز", "جبال الأورال"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة سويسرا؟", correctAnswer: "برن", distractors: ["زيورخ", "جنيف", "فيينا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة النمسا؟", correctAnswer: "فيينا", distractors: ["برن", "ميونخ", "براتيسلافا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة السويد؟", correctAnswer: "ستوكهولم", distractors: ["أوسلو", "كوبنهاغن", "هلسنكي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة النرويج؟", correctAnswer: "أوسلو", distractors: ["ستوكهولم", "كوبنهاغن", "ريكيافيك"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة بولندا؟", correctAnswer: "وارسو", distractors: ["براغ", "بودابست", "برلين"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة المجر؟", correctAnswer: "بودابست", distractors: ["وارسو", "براغ", "فيينا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي محيط يقع جنوب آسيا وبجانب الهند؟", correctAnswer: "المحيط الهندي", distractors: ["المحيط الهادئ", "المحيط الأطلسي", "المحيط المتجمّد الشمالي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي دولة هي الأكبر عددًا في السكّان في العالم؟", correctAnswer: "الهند", distractors: ["الصين", "الولايات المتحدة", "روسيا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما اسم النهر الكبير الذي يمرّ في وسط الولايات المتحدة ويصبّ في خليج المكسيك؟", correctAnswer: "نهر المسيسيبي", distractors: ["نهر الأمازون", "نهر النيل", "نهر التايمز"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي نهر يمرّ في لندن؟", correctAnswer: "نهر التايمز", distractors: ["نهر السين", "نهر الدانوب", "نهر الراين"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي نهر يمرّ في باريس؟", correctAnswer: "نهر السين", distractors: ["نهر التايمز", "نهر الراين", "نهر الدانوب"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي جبل عالٍ ومشهور يقع في اليابان؟", correctAnswer: "جبل فوجي", distractors: ["جبل إفرست", "جبل كليمنجارو", "جبل مونبلان"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي جبل هو الأعلى في أفريقيا؟", correctAnswer: "جبل كليمنجارو", distractors: ["جبل إفرست", "جبل فوجي", "جبل مونبلان"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة البرازيل؟", correctAnswer: "برازيليا", distractors: ["ريو دي جانيرو", "ساو باولو", "بوينس آيرس"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة المكسيك؟", correctAnswer: "مكسيكو سيتي", distractors: ["كانكون", "غوادالاخارا", "ليما"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي بحر يقع جنوب إسرائيل ويتّصل بقناة السويس؟", correctAnswer: "البحر الأحمر", distractors: ["البحر الأبيض المتوسّط", "البحر الأسود", "البحر الميت"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي دولة كبيرة تقع جنوب الولايات المتحدة وتشتهر بحضارة المايا؟", correctAnswer: "المكسيك", distractors: ["كندا", "البرازيل", "الأرجنتين"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي سلسلة جبال طويلة تمتدّ على طول أمريكا الجنوبية؟", correctAnswer: "جبال الأنديز", distractors: ["جبال الألب", "الهيمالايا", "جبال روكي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة الدنمارك؟", correctAnswer: "كوبنهاغن", distractors: ["أوسلو", "ستوكهولم", "أمستردام"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة بلجيكا؟", correctAnswer: "بروكسل", distractors: ["أمستردام", "باريس", "لوكسمبورغ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي نهر طويل يمرّ في وسط أوروبا عبر فيينا وبودابست؟", correctAnswer: "نهر الدانوب", distractors: ["نهر السين", "نهر التايمز", "نهر النيل"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي مدينة إيطالية بُنيت على قنوات مائية كثيرة؟", correctAnswer: "البندقية", distractors: ["روما", "ميلانو", "نابولي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما أكبر بحيرة في العالم من حيث المساحة؟", correctAnswer: "بحر قزوين", distractors: ["بحيرة طبريا", "البحر الميت", "بحيرة فيكتوريا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي دولة تقع شمال الولايات المتحدة وهي الثانية في العالم من حيث المساحة؟", correctAnswer: "كندا", distractors: ["المكسيك", "روسيا", "البرازيل"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة رومانيا؟", correctAnswer: "بوخارست", distractors: ["بودابست", "صوفيا", "وارسو"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي محيط يحيط بالقطب الشمالي؟", correctAnswer: "المحيط المتجمّد الشمالي", distractors: ["المحيط الهادئ", "المحيط الهندي", "المحيط الأطلسي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي مدينة في مصر تقع بجانب الأهرامات الكبيرة؟", correctAnswer: "الجيزة", distractors: ["أثينا", "روما", "بابل"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي دولة جزيرة كبيرة تقع بجانب إنجلترا وعاصمتها دبلن؟", correctAnswer: "أيرلندا", distractors: ["آيسلندا", "اسكتلندا", "هولندا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة أيرلندا؟", correctAnswer: "دبلن", distractors: ["لندن", "أدنبرة", "ريكيافيك"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي دولة جزيرة جليدية تقع في شمال المحيط الأطلسي؟", correctAnswer: "آيسلندا", distractors: ["أيرلندا", "هولندا", "فنلندا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة فنلندا؟", correctAnswer: "هلسنكي", distractors: ["أوسلو", "ستوكهولم", "تالين"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي مدينة في الولايات المتحدة تشتهر بتمثال الحرية وبالمباني العالية؟", correctAnswer: "نيويورك", distractors: ["واشنطن", "لوس أنجلوس", "ميامي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي مضيق مشهور يفصل بين إسبانيا وأفريقيا؟", correctAnswer: "مضيق جبل طارق", distractors: ["قناة السويس", "مضيق بيرينغ", "قناة بنما"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي قناة مشهورة تصل بين المحيط الهادئ والمحيط الأطلسي في وسط أمريكا؟", correctAnswer: "قناة بنما", distractors: ["قناة السويس", "مضيق جبل طارق", "مضيق بيرينغ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي قناة تصل بين البحر الأبيض المتوسّط والبحر الأحمر؟", correctAnswer: "قناة السويس", distractors: ["قناة بنما", "مضيق جبل طارق", "مضيق بيرينغ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي دولة أوروبية تشتهر بطواحين الهواء وأزهار التوليب؟", correctAnswer: "هولندا", distractors: ["بلجيكا", "الدنمارك", "سويسرا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما أكبر غابة مطيرة في العالم، وتقع في أمريكا الجنوبية؟", correctAnswer: "غابة الأمازون", distractors: ["غابة التايغا", "غابة الكونغو", "الصحراء الكبرى"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي دولة طويلة وضيّقة تمتدّ على طول الساحل الغربي لأمريكا الجنوبية؟", correctAnswer: "تشيلي", distractors: ["البرازيل", "الأرجنتين", "باراغواي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة بيرو، بلاد الإنكا القديمة؟", correctAnswer: "ليما", distractors: ["بوغوتا", "سانتياغو", "كيتو"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي دولة في آسيا تشتهر بأزهار الكرز وبالقطارات السريعة جدًّا؟", correctAnswer: "اليابان", distractors: ["الصين", "الهند", "تايلاند"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة كوريا الجنوبية؟", correctAnswer: "سيول", distractors: ["طوكيو", "بكين", "بانكوك"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة تايلاند؟", correctAnswer: "بانكوك", distractors: ["سيول", "طوكيو", "هانوي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي مدينة إيطالية قديمة كانت عاصمة الإمبراطورية التي حكمت معظم أوروبا قديمًا؟", correctAnswer: "روما", distractors: ["ميلانو", "البندقية", "نابولي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي بحيرة في أفريقيا هي الأكبر في القارّة؟", correctAnswer: "بحيرة فيكتوريا", distractors: ["بحيرة طبريا", "بحيرة بايكال", "البحر الميت"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي مدينة تقع في جزء أوروبي وجزء آسيوي في الوقت نفسه؟", correctAnswer: "إسطنبول", distractors: ["أنقرة", "أثينا", "موسكو"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي دولة صغيرة جدًّا داخل مدينة روما هي أصغر دولة في العالم؟", correctAnswer: "الفاتيكان", distractors: ["موناكو", "سان مارينو", "لوكسمبورغ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي صحراء تقع في جنوب إسرائيل؟", correctAnswer: "النقب", distractors: ["الصحراء الكبرى", "صحراء غوبي", "صحراء أتاكاما"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "أي جبل يقع بجانب حيفا ومغطّى بنباتات خضراء؟", correctAnswer: "جبل الكرمل", distractors: ["جبل الشيخ", "جبل الطور", "مسادا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "أي بحيرة في روسيا هي الأعمق في العالم؟", correctAnswer: "بحيرة بايكال", distractors: ["بحيرة فيكتوريا", "بحر قزوين", "بحيرة طبريا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عاصمة الهند؟", correctAnswer: "نيودلهي", distractors: ["مومباي", "بكين", "بانكوك"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أي صحراء كبيرة وباردة تقع في آسيا بين الصين ومنغوليا؟", correctAnswer: "صحراء غوبي", distractors: ["الصحراء الكبرى", "صحراء أتاكاما", "صحراء النقب"], tier: .hard, grades: 4...6),
    ]
}
