import Foundation

/// ⚽ كرة القدم — بالعربية. مأخوذ عن البنك العبريّ (111 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let soccer: [BankQuestion] = [
        BankQuestion(prompt: "⚽\nكم لاعبًا من كلّ فريق يكون في أرض الملعب في وقت واحد؟", correctAnswer: "11", distractors: ["9", "10", "12"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧤\nماذا نسمّي اللاعب الذي يُسمح له بالإمساك بالكرة بيديه؟", correctAnswer: "حارس المرمى", distractors: ["المهاجم", "لاعب الوسط", "المدافع"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🥅\nماذا نسمّي دخول الكرة إلى المرمى؟", correctAnswer: "هدف", distractors: ["ركنيّة", "ركلة جزاء", "وقت مستقطع"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🙌\nبأيّ جزء من الجسم يُمنع لاعب الملعب من لمس الكرة؟", correctAnswer: "باليدين", distractors: ["بالقدمين", "بالرأس", "بالصدر"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🟥\nأيّ لون من البطاقات يُخرج اللاعب من المباراة؟", correctAnswer: "الأحمر", distractors: ["الأصفر", "الأخضر", "الأزرق"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🟨\nماذا ينال اللاعب على مخالفة غير خطيرة، على سبيل الإنذار؟", correctAnswer: "بطاقة صفراء", distractors: ["بطاقة حمراء", "ركلة جزاء", "هدفًا"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "📣\nمن الذي يصفر ويتّخذ القرارات في المباراة؟", correctAnswer: "الحكم", distractors: ["المدرّب", "حارس المرمى", "الكابتن"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⏱️\nكم شوطًا في مباراة كرة القدم؟", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⏱️\nكم دقيقة يستمرّ الشوط الواحد؟", correctAnswer: "45", distractors: ["30", "60", "90"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "⏱️\nكم دقيقة تستمرّ المباراة العاديّة (من دون وقت إضافيّ)؟", correctAnswer: "90", distractors: ["60", "100", "120"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎯\nماذا نسمّي ركلة من مسافة 11 مترًا، وجهًا لوجه مع الحارس؟", correctAnswer: "ركلة جزاء", distractors: ["ركنيّة", "ركلة حرّة", "رمية تماس"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🤾\nخرجت الكرة من الخطّ الجانبيّ. كيف تعود إلى اللعب؟", correctAnswer: "رمية تماس", distractors: ["ركلة جزاء", "ركلة مرمى", "كرة حكم"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🚩\nخرجت الكرة من خطّ المرمى بعد أن لمسها مدافع. ماذا ينال الفريق المهاجم؟", correctAnswer: "ركنيّة", distractors: ["ركلة جزاء", "رمية تماس", "هدفًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⚡\nماذا نسمّي اللاعب الذي مهمّته تسجيل الأهداف؟", correctAnswer: "المهاجم", distractors: ["حارس المرمى", "المدافع", "الحكم"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🛡️\nماذا نسمّي اللاعب الذي يدافع عن منطقة مرمى فريقه؟", correctAnswer: "المدافع", distractors: ["المهاجم", "الحكم", "المدرّب"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🏟️\nماذا نسمّي ملعب كرة قدم كبيرًا يتّسع للجمهور؟", correctAnswer: "استاد", distractors: ["صالة", "مسبح", "حديقة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🥅\nكم مرمى في ملعب كرة القدم؟", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🤝\nما هي «التمريرة»؟", correctAnswer: "أن يعطي اللاعب الكرة إلى زميله في الفريق", distractors: ["أن يسدّد اللاعب نحو المرمى", "أن يصفر الحكم", "أن يصفّق الجمهور"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🤝\nانتهت المباراة بنتيجة 2:2. كيف انتهت؟", correctAnswer: "بالتعادل", distractors: ["بالفوز", "بالخسارة", "بركلة جزاء"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧢\nماذا نسمّي اللاعب الذي يقود الفريق ويضع شريطًا على ذراعه؟", correctAnswer: "الكابتن", distractors: ["حارس المرمى", "الحكم", "المدرّب"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔁\nماذا نسمّي خروج لاعب ودخول لاعب آخر مكانه؟", correctAnswer: "تبديل", distractors: ["ركلة جزاء", "تسلّل", "ركنيّة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎯\nماذا نسمّي تسجيل لاعب واحد ثلاثة أهداف في مباراة واحدة؟", correctAnswer: "هاتريك", distractors: ["ديربي", "تسلّل", "ركلة جزاء"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "😬\nسجّل لاعب بالخطأ في مرمى فريقه. ماذا نسمّي ذلك؟", correctAnswer: "هدفًا عكسيًّا", distractors: ["هاتريك", "ركلة جزاء", "تسلّلًا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🟨🟨\nنال لاعب بطاقة صفراء ثانية في المباراة نفسها. ماذا يحدث؟", correctAnswer: "ينال بطاقة حمراء ويخرج", distractors: ["يواصل اللعب", "ينال فريقه ركلة جزاء", "تتوقّف المباراة"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "📏\nكم يبلغ طول ملعب كرة القدم تقريبًا؟", correctAnswer: "نحو 100 متر", distractors: ["نحو 30 مترًا", "نحو 10 أمتار", "نحو 1,000 متر"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "📺\nما هي تقنيّة VAR؟", correctAnswer: "حكم فيديو يساعد الحكم في الملعب", distractors: ["نوع من أحذية كرة القدم", "اسم استاد", "ركلة خاصّة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⏱️\nانتهت مباراة كأس بالتعادل. كم يستمرّ الوقت الإضافيّ؟", correctAnswer: "30 دقيقة", distractors: ["10 دقائق", "45 دقيقة", "90 دقيقة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🎯\nبقيت النتيجة تعادلًا حتّى بعد الوقت الإضافيّ. ما الذي يحسم المباراة؟", correctAnswer: "ركلات الترجيح", distractors: ["رمي قطعة نقديّة", "مباراة أخرى غدًا", "الفريق صاحب الركنيّات الأكثر"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🚫\nما هو «التسلّل» (الأوفسايد)؟", correctAnswer: "أن يكون المهاجم أقرب إلى المرمى من آخر مدافع لحظة تمرير الكرة إليه", distractors: ["كرة خرجت من الملعب", "مخالفة باليدين", "تسديدة قويّة أكثر من اللازم"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇮🇱\nما اللون الذي يشتهر به قميص فريق مكابي حيفا؟", correctAnswer: "الأخضر", distractors: ["الأحمر", "الأزرق", "الأصفر"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nفي أيّ مدينة يلعب فريق بني يهودا؟", correctAnswer: "تل أبيب", distractors: ["إيلات", "حيفا", "نتانيا"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🏟️\nفي أيّ مدينة يقع استاد «تيدي»؟", correctAnswer: "القدس", distractors: ["حيفا", "تل أبيب", "نتانيا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏟️\nفي أيّ مدينة يقع استاد «ساميّ عوفر»؟", correctAnswer: "حيفا", distractors: ["القدس", "بئر السبع", "بيتح تكفا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏟️\nفي أيّ مدينة يقع استاد «بلومفيلد»؟", correctAnswer: "تل أبيب", distractors: ["حيفا", "القدس", "ريشون لتسيون"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇮🇱\nمكابي تل أبيب ضدّ هبوعيل تل أبيب — ماذا نسمّي مباراة بين فريقين من المدينة نفسها؟", correctAnswer: "ديربي", distractors: ["ركلة جزاء", "مونديال", "هاتريك"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nما اسم البطولة الأعلى لأندية كرة القدم في إسرائيل؟", correctAnswer: "الدوري الإسرائيليّ الممتاز", distractors: ["دوري الدرجة الأولى", "البريميير ليغ", "الليغا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nما اسم الكأس المهمّة في إسرائيل التي تشارك فيها فرق من كلّ الدرجات؟", correctAnswer: "كأس الدولة", distractors: ["كأس العالم", "دوري أبطال أوروبا", "كأس السلام"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nأيّ فريق فاز بأكبر عدد من بطولات الدوري في إسرائيل؟", correctAnswer: "مكابي تل أبيب", distractors: ["هبوعيل بئر السبع", "بيتار القدس", "بني يهودا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nكم نقطة ينال الفريق الفائز بمباراة في الدوري الإسرائيليّ الممتاز؟", correctAnswer: "3", distractors: ["1", "2", "5"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇪🇸\nفي أيّ دولة يلعب فريق برشلونة؟", correctAnswer: "إسبانيا", distractors: ["إيطاليا", "فرنسا", "البرتغال"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🇪🇸\nما اللون التقليديّ لقميص فريق ريال مدريد؟", correctAnswer: "الأبيض", distractors: ["الأسود", "الأخضر", "البرتقاليّ"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏴󠁧󠁢󠁥󠁮󠁧󠁿\nفي أيّ دولة يلعب فريق مانشستر يونايتد؟", correctAnswer: "إنجلترا", distractors: ["ألمانيا", "إسبانيا", "هولندا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇩🇪\nفي أيّ دولة يلعب فريق بايرن ميونخ؟", correctAnswer: "ألمانيا", distractors: ["النمسا", "إيطاليا", "بلجيكا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇮🇹\nفي أيّ دولة يلعب فريق يوفنتوس؟", correctAnswer: "إيطاليا", distractors: ["إسبانيا", "فرنسا", "اليونان"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇫🇷\nفي أيّ مدينة يلعب فريق سان جيرمان؟", correctAnswer: "باريس", distractors: ["مرسيليا", "لندن", "روما"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏆\nما اسم الدوري الأعلى في إنجلترا؟", correctAnswer: "البريميير ليغ", distractors: ["الليغا", "سيري A", "البوندسليغا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nما اسم الدوري الأعلى في إسبانيا؟", correctAnswer: "الليغا", distractors: ["البريميير ليغ", "سيري A", "ليغ 1"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⭐\nدوري أبطال أوروبا هو مسابقة لِـ…", correctAnswer: "أفضل الأندية في أوروبا", distractors: ["منتخبات الدول", "فرق الأطفال", "أندية من إسرائيل فقط"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⭐\nأيّ فريق فاز بدوري أبطال أوروبا أكثر من أيّ فريق آخر؟", correctAnswer: "ريال مدريد", distractors: ["برشلونة", "ليفربول", "ميلان"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇧🇷\nما لون القميص المشهور لمنتخب البرازيل؟", correctAnswer: "الأصفر", distractors: ["الأحمر", "الأزرق", "الأسود"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🇦🇷\nما لونا قميص منتخب الأرجنتين؟", correctAnswer: "السماويّ والأبيض", distractors: ["الأحمر والأسود", "الأخضر والأصفر", "الأزرق والأحمر"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇦🇷\nفي أيّ دولة وُلد ليونيل ميسي؟", correctAnswer: "الأرجنتين", distractors: ["البرازيل", "إسبانيا", "البرتغال"], tier: .easy, grades: 2...6),
        BankQuestion(prompt: "🇵🇹\nفي أيّ دولة وُلد كريستيانو رونالدو؟", correctAnswer: "البرتغال", distractors: ["إسبانيا", "البرازيل", "إيطاليا"], tier: .easy, grades: 2...6),
        BankQuestion(prompt: "👑\nمن أيّ دولة كان بيليه، «ملك كرة القدم»؟", correctAnswer: "البرازيل", distractors: ["الأرجنتين", "البرتغال", "المكسيك"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔟\nأيّ رقم مشهور على القميص يلبسه عادةً اللاعبون المبدعون، مثل ميسي وبيليه؟", correctAnswer: "10", distractors: ["1", "5", "99"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nكلّ كم سنة يُقام المونديال؟", correctAnswer: "4", distractors: ["2", "3", "5"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nما هو المونديال؟", correctAnswer: "بطولة كأس العالم للمنتخبات", distractors: ["دوري لأندية من إسبانيا", "مباراة بين مدينتين", "مسابقة للأطفال"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏆\nأيّ منتخب فاز بكأس العالم خمس مرّات حتّى مونديال 2022؟", correctAnswer: "البرازيل", distractors: ["ألمانيا", "الأرجنتين", "إيطاليا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nأيّ منتخب فاز بمونديال 2022؟", correctAnswer: "الأرجنتين", distractors: ["فرنسا", "البرازيل", "ألمانيا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nأيّ منتخب فاز بمونديال 2018؟", correctAnswer: "فرنسا", distractors: ["كرواتيا", "البرازيل", "إسبانيا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nأيّ منتخب فاز بمونديال 2014 الذي أُقيم في البرازيل؟", correctAnswer: "ألمانيا", distractors: ["البرازيل", "الأرجنتين", "هولندا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nأيّ منتخب فاز بمونديال 2010؟", correctAnswer: "إسبانيا", distractors: ["هولندا", "ألمانيا", "إيطاليا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥇\nأيّ منتخب فاز بالمونديال الأوّل سنة 1930؟", correctAnswer: "الأوروغواي", distractors: ["البرازيل", "إيطاليا", "إنجلترا"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇶🇦\nفي أيّ دولة أُقيم مونديال 2022؟", correctAnswer: "قطر", distractors: ["روسيا", "البرازيل", "اليابان"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇮🇱\nفي أيّ سنة شارك منتخب إسرائيل في نهائيّات المونديال لأوّل مرّة؟", correctAnswer: "1970", distractors: ["1950", "1990", "2010"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥇\nمن هدّاف نهائيّات كأس العالم عبر التاريخ حتّى مونديال 2022؟", correctAnswer: "ميروسلاف كلوزه", distractors: ["بيليه", "ليونيل ميسي", "كريستيانو رونالدو"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏴󠁧󠁢󠁥󠁮󠁧󠁿\nفي أيّ دولة كُتبت قوانين كرة القدم الحديثة لأوّل مرّة؟", correctAnswer: "إنجلترا", distractors: ["البرازيل", "إيطاليا", "اليونان"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌎\nفي أيّ قارّة تقع البرازيل؟", correctAnswer: "أمريكا الجنوبيّة", distractors: ["أوروبا", "أفريقيا", "آسيا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nفي أيّ قارّة تقع ألمانيا؟", correctAnswer: "أوروبا", distractors: ["آسيا", "أمريكا الجنوبيّة", "أستراليا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nفي أيّ قارّة تقع المغرب، التي بلغت الدور نصف النهائيّ في مونديال 2022؟", correctAnswer: "أفريقيا", distractors: ["أوروبا", "آسيا", "أمريكا"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇪🇺\nكلّ كم سنة تُقام بطولة أمم أوروبا (اليورو)؟", correctAnswer: "4", distractors: ["1", "2", "6"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nسجّلت مكابي 3 أهداف وسجّل هبوعيل هدفًا واحدًا. بفارق كم هدفًا فازت مكابي؟", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔢\nانتهت مباراة بنتيجة 4:2. كم هدفًا سُجّل في المجموع؟", correctAnswer: "6", distractors: ["2", "4", "8"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔢\nفي الشوط الأوّل كانت النتيجة 1:0، وفي نهاية المباراة صارت ثلاثة مقابل واحد. كم هدفًا سُجّل في الشوط الثاني؟", correctAnswer: "3", distractors: ["2", "4", "1"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔢\nعلى الفوز ينال الفريق 3 نقاط، وعلى التعادل نقطة واحدة. فاز فريق مرّتين وتعادل مرّة واحدة. كم نقطة له؟", correctAnswer: "7", distractors: ["6", "5", "9"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔢\nعلى الفوز ينال الفريق 3 نقاط. فاز فريق في 5 مباريات وخسر في مباراتين. كم نقطة له؟", correctAnswer: "15", distractors: ["7", "10", "21"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔢\nفي مونديال 2014 فازت ألمانيا على البرازيل 7:1. بفارق كم هدفًا؟", correctAnswer: "6", distractors: ["7", "8", "5"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⏱️\nبدأت المباراة الساعة 20:00. في أيّ ساعة انتهت تقريبًا، بعد 90 دقيقة واستراحة مدّتها 15 دقيقة؟", correctAnswer: "21:45", distractors: ["21:30", "22:00", "21:00"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nسجّل لاعب 12 هدفًا في 8 مباريات. كم هدفًا سجّل في المباراة الواحدة في المعدّل؟", correctAnswer: "1.5", distractors: ["1", "2", "4"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🔢\nفي دوري 4 فرق، ويلعب كلّ فريق ضدّ كلّ فريق آخر مرّة واحدة. كم مباراة في المجموع؟", correctAnswer: "6", distractors: ["4", "8", "12"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🔢\nسجّل فريق هدفين في كلّ مباراة من 6 مباريات. كم هدفًا سجّل في المجموع؟", correctAnswer: "12", distractors: ["8", "10", "14"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⏱️\nأضاف الحكم 4 دقائق إلى الشوط الثاني. كم دقيقة استمرّ ذلك الشوط؟", correctAnswer: "49", distractors: ["45", "50", "94"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⚽\nما شكل كرة القدم؟", correctAnswer: "مستديرة", distractors: ["مربّعة", "مثلّثة", "على شكل قلب"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥅\nإلى أين يجب أن تدخل الكرة؟", correctAnswer: "إلى المرمى", distractors: ["إلى السلّة", "إلى الصندوق", "إلى المسبح"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦶\nبأيّ عضو نركل الكرة؟", correctAnswer: "بالقدم", distractors: ["بالأذن", "بالأنف", "بالبطن"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧤\nمن يحرس المرمى؟", correctAnswer: "حارس المرمى", distractors: ["المهاجم", "المدرّب", "الجمهور"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "👕\nكم فريقًا يلعب في المباراة الواحدة؟", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nبكم كرة يُلعب في المباراة الواحدة؟", correctAnswer: "بكرة واحدة", distractors: ["بكرتين", "بثلاث كرات", "بعشر كرات"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🟩\nما لون العشب في الملعب؟", correctAnswer: "أخضر", distractors: ["أحمر", "أزرق", "بنفسجيّ"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "📣\nمن يصفر في المباراة؟", correctAnswer: "الحكم", distractors: ["حارس المرمى", "الجمهور", "المدرّب"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🟨\nأيّ لون من البطاقات يعني إنذارًا؟", correctAnswer: "الأصفر", distractors: ["الأزرق", "الأخضر", "الأبيض"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏟️\nماذا نسمّي المكان الذي تُلعب فيه كرة القدم؟", correctAnswer: "ملعب", distractors: ["مسبح", "صفّ دراسيّ", "مطبخ"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "👟\nماذا ننتعل في القدمين أثناء المباراة؟", correctAnswer: "حذاء", distractors: ["قفّازات", "قبّعة", "نظّارات"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⏱️\nإلى كم قسم تنقسم مباراة كرة القدم؟", correctAnswer: "إلى قسمين", distractors: ["إلى قسم واحد", "إلى ثلاثة أقسام", "إلى عشرة أقسام"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧤\nمن يلبس القفّازات في المباراة؟", correctAnswer: "حارس المرمى", distractors: ["المهاجم", "الحكم", "المدرّب"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏆\nماذا ينال الفريق الفائز بالبطولة؟", correctAnswer: "كأسًا", distractors: ["كرة", "بطاقة", "صفّارة"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦵\nكم رِجلًا للاعب الواحد؟", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "↩️\nماذا نفعل عندما تخرج الكرة من الملعب؟", correctAnswer: "نرميها إلى داخل الملعب", distractors: ["ننهي المباراة", "نأتي بكرة جديدة", "يذهب الجميع إلى البيت"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🤝\nما الكلام الجميل الذي نقوله للفريق الخاسر؟", correctAnswer: "أحسنتم", distractors: ["خسرتم", "لا تستحقّون", "اذهبوا إلى بيوتكم"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nسجّل فريق هدفًا واحدًا ثمّ سجّل هدفًا آخر. كم هدفًا سجّل؟", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nهدفان وهدف واحد آخر. كم هدفًا في المجموع؟", correctAnswer: "3", distractors: ["2", "4", "5"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\n3 أهداف وهدفان آخران. كم هدفًا في المجموع؟", correctAnswer: "5", distractors: ["4", "6", "7"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\n4 أهداف و3 أهداف أخرى. كم هدفًا في المجموع؟", correctAnswer: "7", distractors: ["6", "8", "9"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "⚽\n5 أهداف و5 أهداف أخرى. كم هدفًا في المجموع؟", correctAnswer: "10", distractors: ["9", "11", "15"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nفي الشوط الأوّل سُجّلت 6 أهداف، وأُلغي منها هدفان. كم هدفًا بقي؟", correctAnswer: "4", distractors: ["3", "5", "8"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nكانت 5 كرات في الملعب وتدحرجت 3 منها إلى الخارج. كم كرة بقيت؟", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔢\nكان 7 لاعبين في الملعب وخرج 4 منهم للراحة. كم لاعبًا بقي؟", correctAnswer: "3", distractors: ["2", "4", "5"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🧮\n10 لاعبين في الملعب ومعهم حارس المرمى. كم لاعبًا في الفريق؟", correctAnswer: "11", distractors: ["10", "12", "9"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🥇\nسجّل فريق القمصان الزرقاء 3 أهداف، وسجّل فريق القمصان الحمراء هدفًا واحدًا. أيّ الفريقين فاز؟", correctAnswer: "الأزرق", distractors: ["الأحمر", "لا أحد منهما", "كلاهما"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🤷\nسجّل كلّ فريق هدفين. ماذا نسمّي هذه النتيجة؟", correctAnswer: "تعادل", distractors: ["فوز", "خسارة", "ركلة جزاء"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "👋\nماذا يفعل اللاعبون في نهاية المباراة؟", correctAnswer: "يتصافحون", distractors: ["يتشاجرون", "يهربون", "ينامون"], tier: .easy, grades: 1...2),
    ]
}
