import Foundation

/// 🐾 عالم الحيوان — بالعربية. مأخوذ عن البنك العبريّ (70 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let animals: [BankQuestion] = [
        BankQuestion(prompt: "🐄\nأيّ حيوان يقول \"مُو\"؟", correctAnswer: "بقرة", distractors: ["كلب", "قطّة", "ديك"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐱\nأيّ حيوان يقول \"مياو\"؟", correctAnswer: "قطّة", distractors: ["كلب", "بقرة", "حصان"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐶\nما الصوت الذي يُصدره الكلب؟", correctAnswer: "هَوْ هَوْ", distractors: ["مُو", "كوكوريكو", "مياو"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐓\nأيّ حيوان يصيح \"كوكوريكو\" في الصباح؟", correctAnswer: "الديك", distractors: ["البطّة", "الخروف", "الماعز"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐴\nماذا نسمّي صغير الحصان؟", correctAnswer: "مُهْر", distractors: ["جَدْي", "حَمَل", "عِجْل"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐄\nماذا نسمّي صغير البقرة؟", correctAnswer: "عِجْل", distractors: ["مُهْر", "جَدْي", "كَتْكوت"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐥\nماذا نسمّي صغير الدجاجة؟", correctAnswer: "كَتْكوت", distractors: ["حَمَل", "عِجْل", "جَدْي"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐑\nماذا نسمّي صغير النعجة؟", correctAnswer: "حَمَل", distractors: ["جَدْي", "عِجْل", "مُهْر"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐐\nماذا نسمّي صغير الماعز؟", correctAnswer: "جَدْي", distractors: ["حَمَل", "مُهْر", "عِجْل"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐶\nماذا نسمّي صغير الكلب؟", correctAnswer: "جَرْو", distractors: ["كَتْكوت", "عِجْل", "حَمَل"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐸\nماذا نسمّي صغير الضفدع الذي يعيش في الماء وله ذيل؟", correctAnswer: "شُرْغوف", distractors: ["يَرَقة", "كَتْكوت", "جَدْي"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦋\nمَن يتحوّل إلى فراشة عندما يكبر؟", correctAnswer: "اليَرَقة", distractors: ["الشُّرْغوف", "الكَتْكوت", "السمكة"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🍼\nماذا يشرب صغار الثدييات، مثل الجَرْو والعِجْل، عند ولادتها؟", correctAnswer: "حليب أمّها", distractors: ["الماء", "العصير", "العسل"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐦\nما الذي يبنيه الطائر ليضع فيه بيضه؟", correctAnswer: "العُشّ", distractors: ["خليّة النحل", "الجُحْر", "الإسطبل"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐕\nكم رِجلًا لدى الكلب؟", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐜\nكم رِجلًا لدى النملة؟", correctAnswer: "6", distractors: ["4", "8", "10"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦅\nكم جناحًا لدى الطائر؟", correctAnswer: "2", distractors: ["1", "4", "6"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🕷️\nكم رِجلًا لدى العنكبوت؟", correctAnswer: "8", distractors: ["6", "4", "10"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐘\nما أكبر حيوان يعيش اليوم على اليابسة؟", correctAnswer: "الفيل", distractors: ["الحصان", "البقرة", "الجمل"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐋\nما أكبر حيوان في العالم كلّه؟", correctAnswer: "الحوت الأزرق", distractors: ["الفيل", "القِرش", "الزرافة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦒\nما أطول حيوان في العالم؟", correctAnswer: "الزرافة", distractors: ["الفيل", "الجمل", "الدبّ"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐆\nما أسرع حيوان على اليابسة؟", correctAnswer: "الفهد الصيّاد", distractors: ["الحصان", "الأرنب", "الأسد"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦈\nما أكبر سمكة في العالم؟", correctAnswer: "القِرش الحوتيّ", distractors: ["التونة", "السلمون", "السمكة الذهبيّة"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐫\nماذا يوجد على ظهر الجمل؟", correctAnswer: "سَنام", distractors: ["قرون", "أجنحة", "حراشف"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐘\nماذا نسمّي أنف الفيل الطويل؟", correctAnswer: "خُرطوم", distractors: ["قَرْن", "سَنام", "مِنقار"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🦏\nماذا يوجد على أنف الكَرْكَدَّن؟", correctAnswer: "قَرْن", distractors: ["خُرطوم", "مِنقار", "سَنام"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦓\nأيّ حيوان له خطوط سوداء وبيضاء؟", correctAnswer: "الحمار الوحشيّ", distractors: ["الزرافة", "الفيل", "الدبّ"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐦\nماذا يغطّي جسم الطائر؟", correctAnswer: "الريش", distractors: ["الحراشف", "الفَرْو", "الأشواك"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐍\nماذا يغطّي جسم الأفعى؟", correctAnswer: "الحراشف", distractors: ["الريش", "الفَرْو", "الصوف"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐢\nأيّ حيوان يحمل بيته على ظهره؟", correctAnswer: "السلحفاة", distractors: ["الأرنب", "الضفدع", "الببغاء"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🦘\nأين تحمل أمّ الكنغر صغيرها؟", correctAnswer: "في جيب على بطنها", distractors: ["على ظهرها", "في فمها", "في ذيلها"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐟\nبماذا تتنفّس الأسماك تحت الماء؟", correctAnswer: "الخياشيم", distractors: ["الرئتان", "الأنف", "الزعانف"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦒\nلماذا للزرافة رقبة طويلة؟", correctAnswer: "لتصل إلى الأوراق في أعلى الأشجار", distractors: ["لتسبح بسرعة", "لتطير", "لتحفر في الأرض"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦎\nأيّ حيوان يغيّر لون جلده؟", correctAnswer: "الحِرباء", distractors: ["السلحفاة", "الأفعى", "الأرنب"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐧\nأيّ طائر لا يستطيع الطيران لكنّه يسبح ببراعة؟", correctAnswer: "البطريق", distractors: ["الحمامة", "النِّسر", "العصفور"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦜\nأيّ طائر يستطيع تقليد كلام الناس؟", correctAnswer: "الببغاء", distractors: ["الحمامة", "البطّة", "النِّسر"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐊\nإلى أيّ مجموعة ينتمي التمساح والسحليّة والسلحفاة؟", correctAnswer: "الزواحف", distractors: ["الثدييات", "الطيور", "الأسماك"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐞\nإلى أيّ مجموعة تنتمي النملة والنحلة والفراشة؟", correctAnswer: "الحشرات", distractors: ["الزواحف", "الطيور", "الثدييات"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐋\nيعيش الحوت في البحر، لكنّه ليس سمكة. إلى أيّ مجموعة ينتمي؟", correctAnswer: "الثدييات", distractors: ["الأسماك", "الزواحف", "البرمائيات"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🦇\nالخفّاش يطير، لكنّه ليس طائرًا. إلى أيّ مجموعة ينتمي؟", correctAnswer: "الثدييات", distractors: ["الطيور", "الحشرات", "الزواحف"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐸\nيعيش الضفدع في الماء وعلى اليابسة معًا. إلى أيّ مجموعة ينتمي؟", correctAnswer: "البرمائيات", distractors: ["الزواحف", "الأسماك", "الثدييات"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🦕\nأيّ حيوان ضخم عاش قبل ملايين السنين، ولا نرى اليوم إلّا عظامه في المتحف؟", correctAnswer: "الديناصور", distractors: ["الفيل", "الزرافة", "التمساح"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐄\nأيّ حيوان يعطينا الحليب؟", correctAnswer: "البقرة", distractors: ["الدجاجة", "النحلة", "الكلب"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐔\nأيّ حيوان يضع البيض الذي نأكله؟", correctAnswer: "الدجاجة", distractors: ["البقرة", "النعجة", "الحصان"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐝\nأيّ حيوان يصنع العسل؟", correctAnswer: "النحلة", distractors: ["الفراشة", "النملة", "الذبابة"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐝\nماذا تجمع النحلة من الأزهار؟", correctAnswer: "الرحيق", distractors: ["الماء", "الأوراق", "البذور"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐼\nماذا يأكل الباندا العملاق طوال النهار تقريبًا؟", correctAnswer: "البامبو", distractors: ["الأسماك", "العسل", "الجزر"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🌿\nماذا نسمّي الحيوان الذي يأكل النباتات فقط؟", correctAnswer: "آكل الأعشاب", distractors: ["آكل اللحوم", "آكل كلّ شيء", "حيوان طائر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦁\nالأسد يأكل اللحم. ماذا نسمّي الحيوان الذي يتغذّى على اللحم؟", correctAnswer: "آكل اللحوم", distractors: ["آكل الأعشاب", "حيوان زاحف", "حيوان طائر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐻\nالدبّ يأكل الأسماك والفواكه والعسل. ماذا نسمّي الحيوان الذي يأكل النباتات واللحوم معًا؟", correctAnswer: "آكل كلّ شيء", distractors: ["آكل الأعشاب", "آكل اللحوم", "حيوان طائر"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🐝\nلماذا النحل مهمّ للنباتات؟", correctAnswer: "لأنّه يُلقّح الأزهار ويساعد الثمار على النموّ", distractors: ["لأنّه يسقيها", "لأنّه يغنّي لها", "لأنّه يحفر لها الحُفر"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🐪\nأيّ حيوان يستطيع السير في الصحراء أيّامًا كثيرة دون أن يشرب؟", correctAnswer: "الجمل", distractors: ["البقرة", "الأرنب", "الضفدع"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐻\nماذا يفعل الدبّ البنّيّ في الشتاء؟", correctAnswer: "ينام نومًا شتويًّا", distractors: ["يطير إلى أفريقيا", "يسبح في البحر", "يغيّر لونه"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦢\nلماذا تطير طيور كثيرة جنوبًا في الخريف؟", correctAnswer: "لتصل إلى مكان دافئ فيه طعام كثير", distractors: ["لتتعلّم الطيران", "لأنّها تحبّ الثلج", "لتسبح في البحر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐨\nفي أيّ قارّة يعيش الكوالا والكنغر؟", correctAnswer: "أستراليا", distractors: ["أوروبا", "آسيا", "أفريقيا"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦁\nفي أيّ قارّة تعيش معظم الأسود في الطبيعة؟", correctAnswer: "أفريقيا", distractors: ["أوروبا", "أستراليا", "أنتاركتيكا"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐼\nفي أيّ دولة يعيش الباندا العملاق في الطبيعة؟", correctAnswer: "الصين", distractors: ["البرازيل", "مصر", "كندا"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐧\nفي أيّ قارّة متجمّدة تعيش بطاريق الإمبراطور؟", correctAnswer: "أنتاركتيكا", distractors: ["أفريقيا", "أوروبا", "آسيا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐯\nفي أيّ قارّة تعيش النمور في الطبيعة؟", correctAnswer: "آسيا", distractors: ["أفريقيا", "أوروبا", "أمريكا الجنوبيّة"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐐\nأيّ حيوان ذو قرون كبيرة يتسلّق الصخور في عين جدي؟", correctAnswer: "الوَعْل", distractors: ["الفيل", "الكنغر", "الباندا"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🪨\nأيّ حيوان صغير كثير الفَرْو يعيش بين الصخور في إسرائيل؟", correctAnswer: "الوَبْر الصخريّ", distractors: ["الكوالا", "البطريق", "الدبّ القطبيّ"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦌\nأيّ حيوان سريع ورشيق ذو قرون يركض في حقول إسرائيل وتلالها؟", correctAnswer: "الغزال", distractors: ["الحمار الوحشيّ", "الكنغر", "الباندا"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦎\nأيّ زاحف صغير يتسلّق جدران البيت في الصيف ويأكل البعوض؟", correctAnswer: "الوَزَغة", distractors: ["السلحفاة", "التمساح", "الضفدع"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦅\nأيّ طائر كبير يحلّق فوق صخور الجولان والنقب، ويحظى في إسرائيل بحماية خاصّة؟", correctAnswer: "النِّسر", distractors: ["الحمامة", "الديك", "البطريق"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🏞️\nأيّ حيوان يظهر في شعار سلطة الطبيعة والحدائق في إسرائيل؟", correctAnswer: "الوَعْل", distractors: ["الأسد", "الفيل", "الجمل"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🛡️\nماذا نسمّي حيوانًا لم يبقَ منه في العالم إلّا القليل جدًّا ويجب حمايته؟", correctAnswer: "حيوان مهدَّد بالانقراض", distractors: ["حيوان أليف", "حيوان مزرعة", "حيوان طائر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦤\nما معنى \"الانقراض\"؟", correctAnswer: "أن يختفي الحيوان نهائيًّا من العالم", distractors: ["أن ينام الحيوان طوال الشتاء", "أن ينتقل الحيوان إلى حديقة الحيوانات", "أن يبدّل الحيوان فَرْوه"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🌳\nلماذا من المهمّ المحافظة على الغابات؟", correctAnswer: "لأنّها بيت لحيوانات كثيرة", distractors: ["ليتّسع المكان لمزيد من السيّارات", "لأنّ الحيوانات لا تحتاج إليها", "لنبني فيها عمارات"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🏞️\nماذا نسمّي منطقة نحافظ فيها على الطبيعة والحيوانات؟", correctAnswer: "محميّة طبيعيّة", distractors: ["متجر حيوانات", "ملعب أطفال", "مركز تجاريّ"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐢\nماذا يستطيع كلّ طفل أن يفعل لمساعدة حيوانات البحر؟", correctAnswer: "ألّا يرمي البلاستيك في البحر", distractors: ["أن يُطعم الأسماك الحلوى", "أن يغنّي للبحر", "أن يرسم الأسماك"], tier: .medium, grades: 1...3),
    ]
}
