import Foundation

/// 🚀 الفضاء — بالعربية. مأخوذ عن البنك العبريّ (70 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let space: [BankQuestion] = [
        BankQuestion(prompt: "☀️\nالشمس في الحقيقة هي…", correctAnswer: "نجم", distractors: ["كوكب", "قمر", "سحابة كبيرة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌍\nما اسم الكوكب الذي نعيش عليه؟", correctAnswer: "الأرض", distractors: ["المرّيخ", "القمر", "المشتري"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌞\nمتى نرى الشمس في السماء؟", correctAnswer: "في النهار", distractors: ["في الليل", "في الشتاء فقط", "في أيّام العطلة فقط"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌅\nماذا تفعل الشمس في الصباح؟", correctAnswer: "تُشرق", distractors: ["تغرب", "تختفي", "تنام"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌍\nما شكل الأرض؟", correctAnswer: "كرة", distractors: ["مكعّب", "مثلّث", "صحن مسطّح"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "📏\nما الأكبر من بين هذه؟", correctAnswer: "الشمس", distractors: ["الأرض", "القمر", "المرّيخ"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌕\nما الأقرب إلى الأرض؟", correctAnswer: "القمر", distractors: ["الشمس", "المرّيخ", "المشتري"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌍\nكم قمرًا للأرض؟", correctAnswer: "1", distractors: ["0", "2", "3"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌕\nماذا نسمّي القمر حين يبدو مستديرًا كاملًا؟", correctAnswer: "البدر", distractors: ["نصف القمر", "المِحاق", "الهلال"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌙\nماذا نسمّي القمر حين لا نرى منه سوى خيط رفيع منحنٍ؟", correctAnswer: "الهلال", distractors: ["البدر", "نجمة", "الشمس"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌍\nحول ماذا تدور الأرض خلال سنة كاملة؟", correctAnswer: "حول الشمس", distractors: ["حول القمر", "حول المرّيخ", "حول المشتري"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌙\nحول ماذا يدور القمر؟", correctAnswer: "حول الأرض", distractors: ["حول الشمس", "حول المرّيخ", "حول زُحل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌞\nما الجرم الذي يقع في مركز منظومتنا الكوكبية وتدور حوله الكواكب كلّها؟", correctAnswer: "الشمس", distractors: ["الأرض", "المشتري", "القمر"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "📅\nكم يومًا في السنة العاديّة؟", correctAnswer: "365", distractors: ["100", "300", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕐\nكم تستغرق الأرض كي تُتمّ دورة كاملة حول نفسها؟", correctAnswer: "نحو 24 ساعة", distractors: ["نحو 12 ساعة", "أسبوع", "سنة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📅\nكم تستغرق الأرض كي تدور حول الشمس دورة واحدة؟", correctAnswer: "سنة", distractors: ["يوم", "أسبوع", "شهر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌙\nكم يستغرق القمر تقريبًا كي يدور حول الأرض دورة كاملة؟", correctAnswer: "نحو شهر", distractors: ["نحو يوم", "نحو أسبوع", "نحو سنة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌗\nلماذا يوجد نهار وليل؟", correctAnswer: "لأنّ الأرض تدور حول نفسها", distractors: ["لأنّ الشمس تنطفئ في الليل", "لأنّ القمر يحجب الشمس", "لأنّ الغيوم تغطّي الشمس"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌞\nالشمس نجم. ممّ تتكوّن أساسًا؟", correctAnswer: "من غازات ملتهبة", distractors: ["من الصخور", "من الماء", "من الجليد"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌕\nلماذا يضيء القمر في الليل؟", correctAnswer: "لأنّه يعكس ضوء الشمس", distractors: ["لأنّه يحترق مثل الشمس", "لأنّ عليه مصابيح", "لأنّه مصنوع من الذهب"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌍\nلماذا يُلقَّب كوكبنا بـ\"الكوكب الأزرق\"؟", correctAnswer: "لأنّ معظمه مغطّى بالماء", distractors: ["لأنّه شديد البرودة", "لأنّ السماء زرقاء", "لأنّه مطليّ بالدهان"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌑\nماذا نسمّي الحالة التي لا يكاد يُرى فيها القمر في السماء؟", correctAnswer: "المِحاق", distractors: ["البدر", "نصف القمر", "القمر الأزرق"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌸\nما سبب فصول السنة — الصيف والخريف والشتاء والربيع؟", correctAnswer: "ميل محور الأرض وهي تدور حول الشمس", distractors: ["الشمس تبرد في الشتاء", "القمر يقترب ويبتعد", "الأرض تتوقّف عن الدوران"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💡\nكم يستغرق ضوء الشمس تقريبًا كي يصل إلى الأرض؟", correctAnswer: "نحو 8 دقائق", distractors: ["ثانية واحدة", "نحو 8 ساعات", "نحو 8 أيّام"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌗\nلماذا يبدو القمر في كلّ ليلة مختلفًا قليلًا؟", correctAnswer: "لأنّنا نرى جزءًا آخر من وجهه المضيء", distractors: ["لأنّه يتغيّر في الحجم", "لأنّ الغيوم تغطّيه", "لأنّه يقترب ويبتعد"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nكم كوكبًا يدور حول الشمس؟", correctAnswer: "8", distractors: ["6", "9", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔴\nأيّ كوكب يُلقَّب بـ\"الكوكب الأحمر\"؟", correctAnswer: "المرّيخ", distractors: ["المشتري", "الزهرة", "زُحل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🪐\nأيّ كوكب له حلقات كبيرة وجميلة؟", correctAnswer: "زُحل", distractors: ["المرّيخ", "الأرض", "عُطارد"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🪐\nأيّ كوكب هو الأكبر في المجموعة الشمسية؟", correctAnswer: "المشتري", distractors: ["الأرض", "المرّيخ", "عُطارد"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔥\nأيّ كوكب هو الأقرب إلى الشمس؟", correctAnswer: "عُطارد", distractors: ["الزهرة", "الأرض", "المرّيخ"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌍\nأيّ كوكب هو الثالث بُعدًا عن الشمس؟", correctAnswer: "الأرض", distractors: ["الزهرة", "المرّيخ", "المشتري"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔴\nأيّ كوكب يأتي مباشرة بعد الأرض كلّما ابتعدنا عن الشمس؟", correctAnswer: "المرّيخ", distractors: ["الزهرة", "عُطارد", "زُحل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔵\nأيّ كوكب هو الأبعد عن الشمس؟", correctAnswer: "نبتون", distractors: ["أورانوس", "زُحل", "المشتري"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔢\nفي المجموعة الشمسية ثمانية كواكب، أربعة منها صخريّة. كم كوكبًا يبقى؟", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔴\nلماذا يبدو المرّيخ أحمر؟", correctAnswer: "بسبب الغبار الأحمر الذي يغطّيه", distractors: ["لأنّه يحترق", "لأنّه شديد الحرارة", "لأنّ عليه أزهارًا حمراء"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌡️\nأيّ كوكب هو الأشدّ حرارة؟ (تلميح: ليس الأقرب إلى الشمس)", correctAnswer: "الزهرة", distractors: ["عُطارد", "المرّيخ", "المشتري"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🪐\nأيّ كوكب يقع بين زُحل ونبتون؟", correctAnswer: "أورانوس", distractors: ["المشتري", "المرّيخ", "الزهرة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🪐\nكان بلوتو يُعَدّ الكوكب التاسع. كيف يُصنَّف اليوم؟", correctAnswer: "كوكب قزم", distractors: ["قمر تابع لنبتون", "مذنّب", "نجم"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧑‍🚀\nماذا نسمّي الشخص الذي يسافر إلى الفضاء؟", correctAnswer: "رائد فضاء", distractors: ["طيّار", "غوّاص", "إطفائيّ"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🚀\nبأيّ وسيلة تُطلَق المركبات إلى الفضاء؟", correctAnswer: "الصاروخ", distractors: ["الطائرة", "المروحية", "المنطاد"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🍎\nما الذي يجعل التفّاحة تسقط إلى الأسفل بدل أن تطير إلى الأعلى؟", correctAnswer: "الجاذبية", distractors: ["الريح", "الشمس", "المطر"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "👩‍🚀\nماذا يلبس رائد الفضاء حين يخرج من المركبة إلى الفضاء؟", correctAnswer: "بدلة فضاء", distractors: ["لباس السباحة", "معطف مطر", "منامة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🎈\nماذا يحدث لروّاد الفضاء داخل مركبة تدور حول الأرض؟", correctAnswer: "يطفون بلا وزن", distractors: ["يصغر حجمهم", "ينامون طوال الوقت", "يمشون على أيديهم"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "👣\nمَن أوّل إنسان وطئت قدمه سطح القمر؟", correctAnswer: "نيل أرمسترونغ", distractors: ["إيلان رامون", "يوري غاغارين", "ألبرت أينشتاين"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🇮🇱\nمَن كان أوّل رائد فضاء إسرائيليّ؟", correctAnswer: "إيلان رامون", distractors: ["نيل أرمسترونغ", "يوري غاغارين", "دافيد بن غوريون"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🛰️\nماذا نسمّي الجهاز الذي يدور حول الأرض في الفضاء ويساعدنا في الملاحة والاتّصالات؟", correctAnswer: "قمر اصطناعيّ", distractors: ["طائرة", "منطاد", "سيّارة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔢\nسافر 3 روّاد فضاء إلى القمر، ونزل 2 منهم إلى سطحه. كم رائدًا بقي في المركبة؟", correctAnswer: "1", distractors: ["0", "2", "3"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nالعدّ التنازليّ للإطلاق: 10، 9، 8، 7… أيّ عدد يأتي مباشرة بعد 3؟", correctAnswer: "2", distractors: ["4", "1", "0"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "👣\nفي أيّ سنة هبط البشر على القمر لأوّل مرّة؟", correctAnswer: "1969", distractors: ["1948", "1900", "2000"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚀\nما اسم المركبة التي حملت أوّل روّاد الفضاء إلى القمر؟", correctAnswer: "أبولو 11", distractors: ["بيريشيت", "سبوتنيك", "فوياجر"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚀\nمَن كان أوّل إنسان يسافر إلى الفضاء، سنة 1961؟", correctAnswer: "يوري غاغارين", distractors: ["نيل أرمسترونغ", "إيلان رامون", "غاليليو"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🇮🇱\nما اسم المركبة الإسرائيلية التي سافرت إلى القمر سنة 2019؟", correctAnswer: "بيريشيت", distractors: ["أبولو", "أوفيك", "سبوتنيك"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🇮🇱\nما كانت مهنة إيلان رامون قبل سفره إلى الفضاء؟", correctAnswer: "طيّار في سلاح الجوّ", distractors: ["لاعب كرة قدم", "مغنٍّ", "طبيب أسنان"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧑‍🚀\nماذا نسمّي البيت الكبير في الفضاء الذي يعيش فيه روّاد الفضاء ويعملون فيه شهورًا؟", correctAnswer: "محطّة الفضاء الدولية", distractors: ["تلسكوب هابل", "القمر", "المرّيخ"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍎\nأيّ عالِم يُروى أنّه فهم سرّ الجاذبية حين سقطت تفّاحة قربه؟", correctAnswer: "إسحاق نيوتن", distractors: ["غاليليو", "ألبرت أينشتاين", "توماس إديسون"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏋️\nالجاذبية على القمر أضعف. بماذا يشعر رائد الفضاء حين يقفز هناك؟", correctAnswer: "بأنّه خفيف ويقفز عاليًا", distractors: ["بأنّه ثقيل جدًّا", "بالشعور نفسه تمامًا كما في بيته", "بأنّه لا يستطيع الحركة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚀\nلماذا يجب أن يكون الصاروخ بهذه القوّة وهذه السرعة؟", correctAnswer: "كي يتغلّب على الجاذبية", distractors: ["كي يُحدث ضجيجًا قويًّا", "كي يسخن", "كي يرى بعيدًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛰️\nما اسم أوّل قمر اصطناعيّ أُطلق إلى الفضاء سنة 1957؟", correctAnswer: "سبوتنيك", distractors: ["أبولو", "هابل", "بيريشيت"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nيرى روّاد محطّة الفضاء نحو 16 شروقًا في اليوم الواحد. كم شروقًا يرون تقريبًا في يومين؟", correctAnswer: "32", distractors: ["16", "8", "24"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔭\nبأيّ جهاز ننظر إلى النجوم البعيدة؟", correctAnswer: "التلسكوب", distractors: ["المجهر", "الكاميرا", "الحاسوب"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌠\nما هو \"النجم الساقط\" في الحقيقة؟", correctAnswer: "حجر صغير من الفضاء يحترق في الهواء", distractors: ["نجم يسقط على الأرض", "قمر صغير", "طائرة في الليل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "✨\nماذا نسمّي النجوم التي تشكّل معًا صورة في السماء، كالدبّ أو الأسد؟", correctAnswer: "كوكبة نجميّة", distractors: ["مذنّب", "قمر اصطناعيّ", "سحابة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧭\nأيّ نجم يدلّنا على جهة الشمال في الليل؟", correctAnswer: "النجم القطبيّ", distractors: ["الشمس", "المرّيخ", "نجم الجنوب"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌌\nما هي المجرّة؟", correctAnswer: "مجموعة هائلة من النجوم", distractors: ["كوكب كبير", "نوع من المركبات الفضائية", "قمر تابع للمشتري"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "☄️\nما الذي يملكه المذنّب حين يقترب من الشمس ولا يملكه الكويكب؟", correctAnswer: "ذيل متوهّج", distractors: ["حلقات", "لون أحمر", "مدار حول الأرض"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🪨\nأين تقع معظم الكويكبات في المجموعة الشمسية؟", correctAnswer: "بين المرّيخ والمشتري", distractors: ["بين الشمس وعُطارد", "قرب القمر", "بين الأرض والزهرة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐻\nما اسم الكوكبة المشهورة التي تبدو سبعة من نجومها كعربة أو مغرفة؟", correctAnswer: "الدبّ الأكبر", distractors: ["الأسد", "العقرب", "الحوت"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌌\nما اسم المجرّة التي تقع فيها مجموعتنا الشمسية؟", correctAnswer: "درب التبّانة", distractors: ["أندروميدا", "الدبّ الأكبر", "حزام الجبّار"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔭\nمَن العالِم الذي اكتشف بالتلسكوب أقمار المشتري الأربعة الكبيرة؟", correctAnswer: "غاليليو غاليلي", distractors: ["إسحاق نيوتن", "ألبرت أينشتاين", "نيل أرمسترونغ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔭\nما اسم التلسكوب الشهير الذي يدور حول الأرض منذ سنة 1990 ويصوّر الفضاء؟", correctAnswer: "هابل", distractors: ["غاليليو", "سبوتنيك", "أبولو"], tier: .hard, grades: 4...6),
    ]
}
