import Foundation

/// 🇬🇧 اللغة الإنجليزية — بالعربية. مأخوذ عن البنك العبريّ (358 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let english: [BankQuestion] = [
        BankQuestion(prompt: "🐈\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "cat", distractors: ["dog", "fish", "bird"], grades: 3...4),
        BankQuestion(prompt: "🐕\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "dog", distractors: ["cat", "horse", "cow"], grades: 3...4),
        BankQuestion(prompt: "🌞\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "sun", distractors: ["moon", "star", "sky"], grades: 3...4),
        BankQuestion(prompt: "🍎\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "apple", distractors: ["banana", "orange", "pear"], grades: 3...4),
        BankQuestion(prompt: "🏠\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "house", distractors: ["car", "tree", "school"], grades: 3...5),
        BankQuestion(prompt: "📚\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "book", distractors: ["pen", "table", "chair"], grades: 3...5),
        BankQuestion(prompt: "🚗\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "car", distractors: ["bus", "bike", "boat"], grades: 3...5),
        BankQuestion(prompt: "🌳\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "tree", distractors: ["flower", "grass", "leaf"], grades: 3...4),
        BankQuestion(prompt: "💧\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "water", distractors: ["fire", "ice", "milk"], grades: 3...4),
        BankQuestion(prompt: "⭐\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "star", distractors: ["sun", "moon", "cloud"], grades: 3...4),
        BankQuestion(prompt: "🌙\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "moon", distractors: ["star", "sun", "night"], grades: 3...4),
        BankQuestion(prompt: "🥛\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "milk", distractors: ["water", "juice", "tea"], grades: 3...5),
        BankQuestion(prompt: "🍞\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "bread", distractors: ["cake", "rice", "egg"], grades: 3...5),
        BankQuestion(prompt: "🐟\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "fish", distractors: ["cat", "dog", "bird"], grades: 3...4),
        BankQuestion(prompt: "🐦\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "bird", distractors: ["fish", "frog", "duck"], grades: 3...4),
        BankQuestion(prompt: "🌸\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "flower", distractors: ["tree", "leaf", "grass"], grades: 3...4),
        BankQuestion(prompt: "🐘\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "elephant", distractors: ["lion", "bear", "tiger"], grades: 3...4),
        BankQuestion(prompt: "🦁\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "lion", distractors: ["tiger", "bear", "elephant"], grades: 3...4),
        BankQuestion(prompt: "🚲\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "bike", distractors: ["car", "bus", "train"], grades: 3...5),
        BankQuestion(prompt: "🎂\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "cake", distractors: ["bread", "milk", "fruit"], grades: 3...5),
        BankQuestion(prompt: "✋\nكيف نقول «اليد» بالإنجليزية؟", correctAnswer: "hand", distractors: ["foot", "head", "eye"], grades: 3...5),
        BankQuestion(prompt: "👁️\nكيف نقول «العين» بالإنجليزية؟", correctAnswer: "eye", distractors: ["ear", "nose", "mouth"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «apple»؟", correctAnswer: "تُفَّاحة", distractors: ["مَوْزة", "بُرْتُقالة", "كُمَّثْرى"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «book»؟", correctAnswer: "كِتاب", distractors: ["دَفْتَر", "قَلَم", "رِسالة"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «tree»؟", correctAnswer: "شَجَرة", distractors: ["زَهْرة", "وَرَقة", "غُصْن"], grades: 3...5),
        BankQuestion(prompt: "🦋\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "butterfly", distractors: ["dragonfly", "ladybug", "caterpillar"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "☂️\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "umbrella", distractors: ["raincoat", "shadow", "shelter"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كيف نقول «النَّظَّارة» بالإنجليزية؟", correctAnswer: "glasses", distractors: ["windows", "mirrors", "bottles"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كيف نقول «قريبًا» بالإنجليزية؟", correctAnswer: "soon", distractors: ["late", "never", "always"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما عكس كلمة «empty»؟", correctAnswer: "full", distractors: ["open", "heavy", "clean"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما عكس كلمة «expensive»؟", correctAnswer: "cheap", distractors: ["rich", "small", "easy"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "«I am thirsty» — ماذا تعني؟", correctAnswer: "أنا عَطْشان", distractors: ["أنا جائع", "أنا مُتْعَب", "أنا سعيد"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "«See you tomorrow» — ماذا تعني؟", correctAnswer: "أراكَ غدًا", distractors: ["إلى اللقاء أمس", "صباح الخير", "أراكَ الآن"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "أيُّ كلمة تدلُّ على حيوان؟", correctAnswer: "squirrel", distractors: ["mountain", "kitchen", "winter"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «المَكْتَبة» بالإنجليزية؟", correctAnswer: "library", distractors: ["laboratory", "bakery", "pharmacy"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔴\nكيف نقول هذا اللون بالإنجليزية؟", correctAnswer: "red", distractors: ["blue", "green", "yellow"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "🔵\nكيف نقول هذا اللون بالإنجليزية؟", correctAnswer: "blue", distractors: ["red", "green", "black"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "🟢\nكيف نقول هذا اللون بالإنجليزية؟", correctAnswer: "green", distractors: ["yellow", "blue", "orange"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "بأيِّ حرف تبدأ كلمة dog؟", correctAnswer: "D", distractors: ["B", "G", "O"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "بأيِّ حرف تبدأ كلمة sun؟", correctAnswer: "S", distractors: ["C", "N", "U"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "5️⃣\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "five", distractors: ["four", "six", "nine"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "3️⃣\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "three", distractors: ["two", "five", "eight"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "كيف نقول «الأب» بالإنجليزية؟", correctAnswer: "father", distractors: ["mother", "brother", "sister"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "كيف نقول «الأمّ» بالإنجليزية؟", correctAnswer: "mother", distractors: ["father", "sister", "teacher"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "ما معنى Good morning؟", correctAnswer: "صباح الخير", distractors: ["تُصبِح على خير", "إلى اللقاء", "شكرًا جزيلًا"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "ما معنى Thank you؟", correctAnswer: "شكرًا", distractors: ["عفوًا", "آسف", "مرحبًا"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "ما صيغة الجمع لكلمة cat؟", correctAnswer: "cats", distractors: ["cates", "caty", "catten"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "ما صيغة الجمع لكلمة book؟", correctAnswer: "books", distractors: ["bookes", "booky", "booken"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "كيف نقول «المُعَلِّم» بالإنجليزية؟", correctAnswer: "teacher", distractors: ["student", "doctor", "driver"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "كيف نقول «المدرسة» بالإنجليزية؟", correctAnswer: "school", distractors: ["park", "store", "house"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "كيف نقول «المَطَر» بالإنجليزية؟", correctAnswer: "rain", distractors: ["snow", "wind", "cloud"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "كيف نقول «الثَّلْج المتساقِط» بالإنجليزية؟", correctAnswer: "snow", distractors: ["rain", "wind", "storm"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "كيف نقول «الأنف» بالإنجليزية؟", correctAnswer: "nose", distractors: ["mouth", "hand", "eye"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "كيف نقول «اليد» بالإنجليزية؟", correctAnswer: "hand", distractors: ["foot", "head", "leg"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "✏️\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "pencil", distractors: ["pen", "paper", "eraser"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "The boy is eating an apple.\nماذا يفعل الولد؟", correctAnswer: "يأكل تُفَّاحة", distractors: ["يشرب عصيرًا", "يلعب بالكرة", "يقرأ كتابًا"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "The girl is reading a book.\nماذا تفعل البنت؟", correctAnswer: "تقرأ كتابًا", distractors: ["تكتب رسالة", "تأكل المُثَلَّجات", "ترسم رسمة"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "The dog is sleeping.\nماذا يفعل الكلب؟", correctAnswer: "ينام", distractors: ["يأكل", "يركض", "ينبح"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "بأيِّ كلمة إنجليزية نسأل عن المكان؟", correctAnswer: "Where", distractors: ["What", "Who", "When"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "ما معنى كلمة What؟", correctAnswer: "ماذا", distractors: ["مَن", "أين", "متى"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "ما معنى كلمة Who؟", correctAnswer: "مَن", distractors: ["ماذا", "كيف", "لماذا"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "ما عكس كلمة big بالإنجليزية؟", correctAnswer: "small", distractors: ["tall", "long", "wide"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "ما عكس كلمة hot بالإنجليزية؟", correctAnswer: "cold", distractors: ["warm", "wet", "dry"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "ما عكس كلمة day بالإنجليزية؟", correctAnswer: "night", distractors: ["morning", "noon", "evening"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "أيَّ ضميرٍ نستخدم عندما نتحدَّث عن ولد (سامي)؟", correctAnswer: "he", distractors: ["she", "it", "we"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "أيَّ ضميرٍ نستخدم عندما نتحدَّث عن بنت (ريم)؟", correctAnswer: "she", distractors: ["he", "it", "they"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "أيَّ ضميرٍ نستخدم عندما نتحدَّث عن طاولة؟", correctAnswer: "it", distractors: ["he", "she", "you"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "اختاروا الصيغة الصحيحة:\nEvery day Dan ___ to school.", correctAnswer: "walks", distractors: ["walking", "is walk", "walk"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "اختاروا الصيغة الصحيحة:\nLook! The baby ___ now.", correctAnswer: "is crying", distractors: ["cries", "cry", "crying"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "اختاروا الصيغة الصحيحة:\nShe ___ TV every evening.", correctAnswer: "watches", distractors: ["watching", "is watch", "watch"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "اختاروا الصيغة الصحيحة:\nRight now the children ___ in the park.", correctAnswer: "are playing", distractors: ["plays", "is playing", "played"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "الكتاب موضوع فوق الطاولة.\nThe book is ___ the table.", correctAnswer: "on", distractors: ["in", "under", "at"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "القطّة تحت السرير.\nThe cat is ___ the bed.", correctAnswer: "under", distractors: ["on", "in", "next"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "الكرة داخل الصندوق.\nThe ball is ___ the box.", correctAnswer: "in", distractors: ["on", "under", "at"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "ما صيغة الجمع لكلمة child؟", correctAnswer: "children", distractors: ["childs", "childes", "childrens"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "ما صيغة الجمع لكلمة foot؟", correctAnswer: "feet", distractors: ["foots", "feets", "footes"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "ما صيغة الجمع لكلمة mouse؟", correctAnswer: "mice", distractors: ["mouses", "mices", "meese"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Tom has a red bike. He rides it to school every day.\nما لون درّاجة Tom؟", correctAnswer: "أحمر", distractors: ["أزرق", "أخضر", "أصفر"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Anna lives in Haifa. She has two cats.\nكم قطّة عند Anna؟", correctAnswer: "اثنتان", distractors: ["واحدة", "ثلاث", "أربع"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🦓\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "zebra", distractors: ["horse", "cow", "donkey"], grades: 3...4),
        BankQuestion(prompt: "🦒\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "giraffe", distractors: ["elephant", "horse", "camel"], grades: 3...4),
        BankQuestion(prompt: "🐒\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "monkey", distractors: ["bear", "tiger", "lion"], grades: 3...4),
        BankQuestion(prompt: "🐻\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "bear", distractors: ["wolf", "fox", "dog"], grades: 3...4),
        BankQuestion(prompt: "🐺\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "wolf", distractors: ["dog", "fox", "bear"], grades: 3...4),
        BankQuestion(prompt: "🐰\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "rabbit", distractors: ["mouse", "hamster", "fox"], grades: 3...4),
        BankQuestion(prompt: "🐭\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "mouse", distractors: ["rabbit", "hamster", "cat"], grades: 3...4),
        BankQuestion(prompt: "🐢\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "turtle", distractors: ["snake", "frog", "fish"], grades: 3...4),
        BankQuestion(prompt: "🐸\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "frog", distractors: ["fish", "turtle", "lizard"], grades: 3...4),
        BankQuestion(prompt: "🐝\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "bee", distractors: ["fly", "ant", "butterfly"], grades: 3...4),
        BankQuestion(prompt: "🦊\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "fox", distractors: ["wolf", "dog", "cat"], grades: 3...4),
        BankQuestion(prompt: "🦄\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "unicorn", distractors: ["horse", "dragon", "pony"], grades: 3...4),
        BankQuestion(prompt: "🐬\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "dolphin", distractors: ["whale", "fish", "shark"], grades: 3...4),
        BankQuestion(prompt: "🦈\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "shark", distractors: ["whale", "fish", "dolphin"], grades: 3...4),
        BankQuestion(prompt: "🐢\nكيف نقول «بطيء» بالإنجليزية؟", correctAnswer: "slow", distractors: ["fast", "small", "old"], grades: 3...4),
        BankQuestion(prompt: "🔴\nما هذا اللون بالإنجليزية؟", correctAnswer: "red", distractors: ["blue", "yellow", "pink"], grades: 3...4),
        BankQuestion(prompt: "🔵\nما هذا اللون بالإنجليزية؟", correctAnswer: "blue", distractors: ["red", "green", "purple"], grades: 3...4),
        BankQuestion(prompt: "🟢\nما هذا اللون بالإنجليزية؟", correctAnswer: "green", distractors: ["yellow", "blue", "brown"], grades: 3...4),
        BankQuestion(prompt: "🟡\nما هذا اللون بالإنجليزية؟", correctAnswer: "yellow", distractors: ["orange", "gold", "white"], grades: 3...4),
        BankQuestion(prompt: "🟠\nما هذا اللون بالإنجليزية؟", correctAnswer: "orange", distractors: ["yellow", "red", "brown"], grades: 3...4),
        BankQuestion(prompt: "🟣\nما هذا اللون بالإنجليزية؟", correctAnswer: "purple", distractors: ["pink", "blue", "green"], grades: 3...4),
        BankQuestion(prompt: "⚫\nما هذا اللون بالإنجليزية؟", correctAnswer: "black", distractors: ["gray", "brown", "dark"], grades: 3...4),
        BankQuestion(prompt: "⚪\nما هذا اللون بالإنجليزية؟", correctAnswer: "white", distractors: ["gray", "silver", "light"], grades: 3...4),
        BankQuestion(prompt: "1\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "one", distractors: ["two", "three", "four"], grades: 3...4),
        BankQuestion(prompt: "2\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "two", distractors: ["three", "one", "five"], grades: 3...4),
        BankQuestion(prompt: "3\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "three", distractors: ["thirteen", "two", "four"], grades: 3...4),
        BankQuestion(prompt: "4\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "four", distractors: ["five", "fourteen", "forty"], grades: 3...4),
        BankQuestion(prompt: "5\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "five", distractors: ["four", "fifteen", "six"], grades: 3...4),
        BankQuestion(prompt: "10\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "ten", distractors: ["twenty", "tin", "eleven"], grades: 3...4),
        BankQuestion(prompt: "الأب بالإنجليزية؟", correctAnswer: "father", distractors: ["mother", "brother", "sister"], grades: 3...4),
        BankQuestion(prompt: "الأمّ بالإنجليزية؟", correctAnswer: "mother", distractors: ["father", "sister", "aunt"], grades: 3...4),
        BankQuestion(prompt: "الأخ بالإنجليزية؟", correctAnswer: "brother", distractors: ["sister", "father", "uncle"], grades: 3...4),
        BankQuestion(prompt: "الأخت بالإنجليزية؟", correctAnswer: "sister", distractors: ["brother", "mother", "aunt"], grades: 3...4),
        BankQuestion(prompt: "الجَدّ بالإنجليزية؟", correctAnswer: "grandfather", distractors: ["father", "uncle", "grandson"], grades: 3...4),
        BankQuestion(prompt: "الجَدّة بالإنجليزية؟", correctAnswer: "grandmother", distractors: ["mother", "aunt", "granddaughter"], grades: 3...4),
        BankQuestion(prompt: "الرَّكْض بالإنجليزية؟", correctAnswer: "run", distractors: ["jump", "walk", "swim"], grades: 3...5),
        BankQuestion(prompt: "القَفْز بالإنجليزية؟", correctAnswer: "jump", distractors: ["run", "fly", "climb"], grades: 3...5),
        BankQuestion(prompt: "الأَكْل بالإنجليزية؟", correctAnswer: "eat", distractors: ["drink", "sleep", "cook"], grades: 3...5),
        BankQuestion(prompt: "النَّوْم بالإنجليزية؟", correctAnswer: "sleep", distractors: ["eat", "play", "rest"], grades: 3...5),
        BankQuestion(prompt: "القِراءة بالإنجليزية؟", correctAnswer: "read", distractors: ["write", "look", "listen"], grades: 3...5),
        BankQuestion(prompt: "الكِتابة بالإنجليزية؟", correctAnswer: "write", distractors: ["read", "draw", "speak"], grades: 3...5),
        BankQuestion(prompt: "اللَّعِب بالإنجليزية؟", correctAnswer: "play", distractors: ["work", "study", "sleep"], grades: 3...5),
        BankQuestion(prompt: "الرُّؤْية بالإنجليزية؟", correctAnswer: "see", distractors: ["hear", "look", "watch"], grades: 3...5),
        BankQuestion(prompt: "السَّمْع بالإنجليزية؟", correctAnswer: "hear", distractors: ["see", "say", "smell"], grades: 3...5),
        BankQuestion(prompt: "التَّكَلُّم بالإنجليزية؟", correctAnswer: "speak", distractors: ["write", "tell", "say"], grades: 3...5),
        BankQuestion(prompt: "يوم الأحد بالإنجليزية؟", correctAnswer: "Sunday", distractors: ["Monday", "Saturday", "Friday"], grades: 3...5),
        BankQuestion(prompt: "يوم الاثنين بالإنجليزية؟", correctAnswer: "Monday", distractors: ["Sunday", "Tuesday", "Friday"], grades: 3...5),
        BankQuestion(prompt: "يوم الثلاثاء بالإنجليزية؟", correctAnswer: "Tuesday", distractors: ["Wednesday", "Monday", "Thursday"], grades: 3...5),
        BankQuestion(prompt: "يوم الأربعاء بالإنجليزية؟", correctAnswer: "Wednesday", distractors: ["Tuesday", "Thursday", "Sunday"], grades: 3...5),
        BankQuestion(prompt: "يوم الخميس بالإنجليزية؟", correctAnswer: "Thursday", distractors: ["Friday", "Wednesday", "Sunday"], grades: 3...5),
        BankQuestion(prompt: "يوم الجمعة بالإنجليزية؟", correctAnswer: "Friday", distractors: ["Saturday", "Thursday", "Sunday"], grades: 3...5),
        BankQuestion(prompt: "يوم السبت بالإنجليزية؟", correctAnswer: "Saturday", distractors: ["Sunday", "Friday", "Monday"], grades: 3...5),
        BankQuestion(prompt: "🌧\nالمَطَر بالإنجليزية؟", correctAnswer: "rain", distractors: ["snow", "wind", "cloud"], grades: 3...5),
        BankQuestion(prompt: "❄️\nالثَّلْج المتساقِط بالإنجليزية؟", correctAnswer: "snow", distractors: ["fog", "rain", "cold"], grades: 3...5),
        BankQuestion(prompt: "🌬\nالرِّيح بالإنجليزية؟", correctAnswer: "wind", distractors: ["rain", "storm", "weather"], grades: 3...5),
        BankQuestion(prompt: "☁️\nالغَيْمة بالإنجليزية؟", correctAnswer: "cloud", distractors: ["sky", "fog", "smoke"], grades: 3...5),
        BankQuestion(prompt: "⛈\nالعاصِفة بالإنجليزية؟", correctAnswer: "storm", distractors: ["rain", "thunder", "wind"], grades: 3...5),
        BankQuestion(prompt: "الرأس بالإنجليزية؟", correctAnswer: "head", distractors: ["hand", "neck", "hair"], grades: 3...4),
        BankQuestion(prompt: "الأنف بالإنجليزية؟", correctAnswer: "nose", distractors: ["mouth", "ear", "eye"], grades: 3...4),
        BankQuestion(prompt: "الفم بالإنجليزية؟", correctAnswer: "mouth", distractors: ["nose", "lip", "tongue"], grades: 3...4),
        BankQuestion(prompt: "الأُذُن بالإنجليزية؟", correctAnswer: "ear", distractors: ["eye", "nose", "head"], grades: 3...4),
        BankQuestion(prompt: "السَّاق بالإنجليزية؟", correctAnswer: "leg", distractors: ["hand", "arm", "knee"], grades: 3...4),
        BankQuestion(prompt: "كَفُّ اليد بالإنجليزية؟", correctAnswer: "hand", distractors: ["foot", "arm", "finger"], grades: 3...4),
        BankQuestion(prompt: "🧀\nالجُبْنة بالإنجليزية؟", correctAnswer: "cheese", distractors: ["butter", "milk", "yogurt"], grades: 3...4),
        BankQuestion(prompt: "🍕\nالبيتزا بالإنجليزية؟", correctAnswer: "pizza", distractors: ["pasta", "bread", "burger"], grades: 3...4),
        BankQuestion(prompt: "🍔\nالهمبرغر بالإنجليزية؟", correctAnswer: "burger", distractors: ["pizza", "hotdog", "fries"], grades: 3...4),
        BankQuestion(prompt: "🍌\nالموز بالإنجليزية؟", correctAnswer: "banana", distractors: ["apple", "lemon", "mango"], grades: 3...4),
        BankQuestion(prompt: "🍊\nالبرتقال بالإنجليزية؟", correctAnswer: "orange", distractors: ["lemon", "apple", "fruit"], grades: 3...4),
        BankQuestion(prompt: "🍓\nالفَراولة بالإنجليزية؟", correctAnswer: "strawberry", distractors: ["raspberry", "cherry", "apple"], grades: 3...4),
        BankQuestion(prompt: "🍉\nالبطّيخ الأحمر بالإنجليزية؟", correctAnswer: "watermelon", distractors: ["melon", "pumpkin", "apple"], grades: 3...4),
        BankQuestion(prompt: "🍇\nالعِنَب بالإنجليزية؟", correctAnswer: "grapes", distractors: ["berries", "cherry", "plum"], grades: 3...4),
        BankQuestion(prompt: "المُعَلِّم بالإنجليزية؟", correctAnswer: "teacher", distractors: ["student", "doctor", "parent"], grades: 3...5),
        BankQuestion(prompt: "التِّلْميذ بالإنجليزية؟", correctAnswer: "student", distractors: ["teacher", "kid", "child"], grades: 3...5),
        BankQuestion(prompt: "المدرسة بالإنجليزية؟", correctAnswer: "school", distractors: ["college", "class", "home"], grades: 3...5),
        BankQuestion(prompt: "الصَّفّ بالإنجليزية؟", correctAnswer: "class", distractors: ["school", "room", "lesson"], grades: 3...5),
        BankQuestion(prompt: "قلم الرَّصاص بالإنجليزية؟", correctAnswer: "pencil", distractors: ["pen", "paper", "eraser"], grades: 3...5),
        BankQuestion(prompt: "قلم الحِبْر بالإنجليزية؟", correctAnswer: "pen", distractors: ["pencil", "marker", "ink"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «dog»؟", correctAnswer: "كَلْب", distractors: ["قِطّة", "أرنب", "حِصان"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «cat»؟", correctAnswer: "قِطّة", distractors: ["كَلْب", "أسد", "نَمِر"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «house»؟", correctAnswer: "بَيْت", distractors: ["شقّة", "فيلّا", "غُرْفة"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «star»؟", correctAnswer: "نَجْمة", distractors: ["شمس", "قمر", "غَيْمة"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «water»؟", correctAnswer: "ماء", distractors: ["حليب", "عصير", "شاي"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «sun»؟", correctAnswer: "شمس", distractors: ["قمر", "نَجْمة", "ضَوْء"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «red»؟", correctAnswer: "أحمر", distractors: ["أزرق", "أخضر", "وَرْدي"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «happy»؟", correctAnswer: "سعيد", distractors: ["حزين", "غاضِب", "مُتْعَب"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «big»؟", correctAnswer: "كبير", distractors: ["صغير", "طويل", "عريض"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «small»؟", correctAnswer: "صغير", distractors: ["كبير", "ضيّق", "قصير"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «fast»؟", correctAnswer: "سريع", distractors: ["بطيء", "قويّ", "طويل"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «cold»؟", correctAnswer: "بارِد", distractors: ["حارّ", "دافِئ", "ماطِر"], grades: 3...5),
        BankQuestion(prompt: "ما معنى كلمة «hot»؟", correctAnswer: "حارّ", distractors: ["بارِد", "مُنْعِش", "عاصِف"], grades: 3...5),
        BankQuestion(prompt: "🐮\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "cow", distractors: ["goat", "sheep", "pig"], grades: 3...4),
        BankQuestion(prompt: "🐷\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "pig", distractors: ["cow", "dog", "sheep"], grades: 3...4),
        BankQuestion(prompt: "🐴\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "horse", distractors: ["donkey", "cow", "goat"], grades: 3...4),
        BankQuestion(prompt: "🐑\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "sheep", distractors: ["goat", "cow", "pig"], grades: 3...4),
        BankQuestion(prompt: "🐔\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "chicken", distractors: ["duck", "bird", "cow"], grades: 3...4),
        BankQuestion(prompt: "🦆\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "duck", distractors: ["chicken", "bird", "fish"], grades: 3...4),
        BankQuestion(prompt: "🍌\nما اسم هذا بالإنجليزية؟", correctAnswer: "banana", distractors: ["apple", "lemon", "orange"], grades: 3...5),
        BankQuestion(prompt: "🥚\nما اسم هذا بالإنجليزية؟", correctAnswer: "egg", distractors: ["milk", "bread", "cheese"], grades: 3...5),
        BankQuestion(prompt: "🍪\nما اسم هذا بالإنجليزية؟", correctAnswer: "cookie", distractors: ["cake", "candy", "bread"], grades: 3...5),
        BankQuestion(prompt: "🍦\nما اسم هذا بالإنجليزية؟", correctAnswer: "ice cream", distractors: ["cake", "candy", "milk"], grades: 3...5),
        BankQuestion(prompt: "🟤\nما اسم هذا اللون بالإنجليزية؟", correctAnswer: "brown", distractors: ["black", "gray", "orange"], grades: 3...4),
        BankQuestion(prompt: "🩷\nما اسم هذا اللون بالإنجليزية؟", correctAnswer: "pink", distractors: ["red", "purple", "orange"], grades: 3...4),
        BankQuestion(prompt: "🦶\nكيف نقول «قدم» بالإنجليزية؟", correctAnswer: "foot", distractors: ["leg", "hand", "arm"], grades: 3...5),
        BankQuestion(prompt: "💪\nكيف نقول «ذراع» بالإنجليزية؟", correctAnswer: "arm", distractors: ["leg", "hand", "foot"], grades: 3...5),
        BankQuestion(prompt: "🦷\nما اسم هذا العضو بالإنجليزية؟", correctAnswer: "tooth", distractors: ["nose", "mouth", "ear"], grades: 3...5),
        BankQuestion(prompt: "👶\nكيف نقول «رضيع» بالإنجليزية؟", correctAnswer: "baby", distractors: ["boy", "girl", "man"], grades: 3...5),
        BankQuestion(prompt: "6\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "six", distractors: ["seven", "sixteen", "sixty"], grades: 3...4),
        BankQuestion(prompt: "7\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "seven", distractors: ["six", "seventy", "eleven"], grades: 3...4),
        BankQuestion(prompt: "8\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "eight", distractors: ["nine", "eighteen", "eighty"], grades: 3...4),
        BankQuestion(prompt: "9\nكيف نقول هذا العدد بالإنجليزية؟", correctAnswer: "nine", distractors: ["eight", "ten", "ninety"], grades: 3...4),
        BankQuestion(prompt: "🎒\nما اسم هذا بالإنجليزية؟", correctAnswer: "bag", distractors: ["book", "box", "desk"], grades: 3...5),
        BankQuestion(prompt: "✂️\nما اسم هذا بالإنجليزية؟", correctAnswer: "scissors", distractors: ["pencil", "ruler", "glue"], grades: 3...5),
        BankQuestion(prompt: "🏔️\nكيف نقول «جبل» بالإنجليزية؟", correctAnswer: "mountain", distractors: ["river", "sea", "hill"], grades: 3...5),
        BankQuestion(prompt: "🌊\nكيف نقول «بحر» بالإنجليزية؟", correctAnswer: "sea", distractors: ["lake", "river", "rain"], grades: 3...5),
        BankQuestion(prompt: "🍃\nكيف نقول «ورقة شجر» بالإنجليزية؟", correctAnswer: "leaf", distractors: ["tree", "grass", "flower"], grades: 3...5),
        BankQuestion(prompt: "🚶\nكيف نقول «يمشي» بالإنجليزية؟", correctAnswer: "walk", distractors: ["run", "jump", "sit"], grades: 3...5),
        BankQuestion(prompt: "🥤\nكيف نقول «يشرب» بالإنجليزية؟", correctAnswer: "drink", distractors: ["eat", "cook", "wash"], grades: 3...5),
        BankQuestion(prompt: "👟\nكيف نقول «حذاء» بالإنجليزية؟", correctAnswer: "shoe", distractors: ["hat", "shirt", "sock"], grades: 3...5),
        BankQuestion(prompt: "🧢\nكيف نقول «قبعة» بالإنجليزية؟", correctAnswer: "hat", distractors: ["shoe", "shirt", "coat"], grades: 3...5),
        BankQuestion(prompt: "👩\nكيف نقول «أم» بالإنجليزية؟", correctAnswer: "mother", distractors: ["father", "sister", "grandma"], grades: 3...4),
        BankQuestion(prompt: "👨\nكيف نقول «أب» بالإنجليزية؟", correctAnswer: "father", distractors: ["mother", "brother", "uncle"], grades: 3...4),
        BankQuestion(prompt: "👵\nكيف نقول «جدة» بالإنجليزية؟", correctAnswer: "grandma", distractors: ["mother", "aunt", "sister"], grades: 3...4),
        BankQuestion(prompt: "👦\nكيف نقول «أخ» بالإنجليزية؟", correctAnswer: "brother", distractors: ["sister", "father", "friend"], grades: 3...4),
        BankQuestion(prompt: "😀\nما هذا الشعور بالإنجليزية؟", correctAnswer: "happy", distractors: ["sad", "angry", "tired"], grades: 3...4),
        BankQuestion(prompt: "😢\nما هذا الشعور بالإنجليزية؟", correctAnswer: "sad", distractors: ["happy", "scared", "hungry"], grades: 3...4),
        BankQuestion(prompt: "😠\nما هذا الشعور بالإنجليزية؟", correctAnswer: "angry", distractors: ["happy", "sleepy", "sad"], grades: 3...4),
        BankQuestion(prompt: "😴\nما هذا الشعور بالإنجليزية؟", correctAnswer: "tired", distractors: ["happy", "hungry", "angry"], grades: 3...4),
        BankQuestion(prompt: "☀️\nما اسم هذا بالإنجليزية؟", correctAnswer: "sun", distractors: ["rain", "cloud", "wind"], grades: 3...4),
        BankQuestion(prompt: "🌧️\nما اسم هذا بالإنجليزية؟", correctAnswer: "rain", distractors: ["sun", "snow", "cloud"], grades: 3...4),
        BankQuestion(prompt: "❄️\nما اسم هذا بالإنجليزية؟", correctAnswer: "snow", distractors: ["rain", "sun", "wind"], grades: 3...4),
        BankQuestion(prompt: "☁️\nما اسم هذا بالإنجليزية؟", correctAnswer: "cloud", distractors: ["sun", "rain", "snow"], grades: 3...4),
        BankQuestion(prompt: "🛏️\nما اسم الغرفة التي ننام فيها بالإنجليزية؟", correctAnswer: "bedroom", distractors: ["kitchen", "bathroom", "garden"], grades: 3...5),
        BankQuestion(prompt: "🍳\nما اسم الغرفة التي نطبخ فيها بالإنجليزية؟", correctAnswer: "kitchen", distractors: ["bedroom", "bathroom", "garden"], grades: 3...5),
        BankQuestion(prompt: "🛁\nما اسم الغرفة التي نستحم فيها بالإنجليزية؟", correctAnswer: "bathroom", distractors: ["kitchen", "bedroom", "garden"], grades: 3...5),
        BankQuestion(prompt: "🚪\nما اسم هذا بالإنجليزية؟", correctAnswer: "door", distractors: ["window", "wall", "floor"], grades: 3...5),
        BankQuestion(prompt: "👮\nما اسم هذه المهنة بالإنجليزية؟", correctAnswer: "police", distractors: ["doctor", "teacher", "farmer"], grades: 3...5),
        BankQuestion(prompt: "👨‍🍳\nما اسم هذه المهنة بالإنجليزية؟", correctAnswer: "cook", distractors: ["doctor", "teacher", "pilot"], grades: 3...5),
        BankQuestion(prompt: "👩‍⚕️\nما اسم هذه المهنة بالإنجليزية؟", correctAnswer: "doctor", distractors: ["teacher", "police", "cook"], grades: 3...5),
        BankQuestion(prompt: "🧑‍🚒\nما اسم هذه المهنة بالإنجليزية؟", correctAnswer: "firefighter", distractors: ["doctor", "teacher", "pilot"], grades: 3...5),
        BankQuestion(prompt: "👕\nما اسم هذا بالإنجليزية؟", correctAnswer: "shirt", distractors: ["pants", "socks", "dress"], grades: 3...5),
        BankQuestion(prompt: "👖\nما اسم هذا بالإنجليزية؟", correctAnswer: "pants", distractors: ["shirt", "socks", "coat"], grades: 3...5),
        BankQuestion(prompt: "🧦\nما اسم هذا بالإنجليزية؟", correctAnswer: "socks", distractors: ["shoes", "pants", "gloves"], grades: 3...5),
        BankQuestion(prompt: "🧥\nما اسم هذا بالإنجليزية؟", correctAnswer: "coat", distractors: ["shirt", "hat", "socks"], grades: 3...5),
        BankQuestion(prompt: "🥕\nما اسم هذا بالإنجليزية؟", correctAnswer: "carrot", distractors: ["tomato", "potato", "onion"], grades: 3...5),
        BankQuestion(prompt: "🍅\nما اسم هذا بالإنجليزية؟", correctAnswer: "tomato", distractors: ["carrot", "potato", "pepper"], grades: 3...5),
        BankQuestion(prompt: "🥔\nما اسم هذا بالإنجليزية؟", correctAnswer: "potato", distractors: ["tomato", "carrot", "onion"], grades: 3...5),
        BankQuestion(prompt: "🌽\nما اسم هذا بالإنجليزية؟", correctAnswer: "corn", distractors: ["carrot", "tomato", "potato"], grades: 3...5),
        BankQuestion(prompt: "🐶\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "dog", distractors: ["cat", "cow", "pig"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐱\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "cat", distractors: ["dog", "fish", "bird"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐟\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "fish", distractors: ["frog", "duck", "bird"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐦\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "bird", distractors: ["fish", "bee", "cat"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐄\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "cow", distractors: ["pig", "dog", "goat"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐷\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "pig", distractors: ["cow", "dog", "cat"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐭\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "mouse", distractors: ["cat", "frog", "bird"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐰\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "rabbit", distractors: ["mouse", "cat", "dog"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍎\nما اسم هذا بالإنجليزية؟", correctAnswer: "apple", distractors: ["banana", "orange", "lemon"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍊\nما اسم هذا بالإنجليزية؟", correctAnswer: "orange", distractors: ["apple", "lemon", "banana"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍋\nما اسم هذا بالإنجليزية؟", correctAnswer: "lemon", distractors: ["orange", "apple", "grape"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍇\nما اسم هذا بالإنجليزية؟", correctAnswer: "grapes", distractors: ["apple", "banana", "cherry"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍓\nما اسم هذا بالإنجليزية؟", correctAnswer: "strawberry", distractors: ["cherry", "apple", "grape"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🥛\nما اسم هذا بالإنجليزية؟", correctAnswer: "milk", distractors: ["water", "juice", "tea"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍞\nما اسم هذا بالإنجليزية؟", correctAnswer: "bread", distractors: ["cake", "rice", "egg"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🧀\nما اسم هذا بالإنجليزية؟", correctAnswer: "cheese", distractors: ["egg", "milk", "bread"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "💧\nما اسم هذا بالإنجليزية؟", correctAnswer: "water", distractors: ["milk", "juice", "fire"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🔴\nما اسم هذا اللون بالإنجليزية؟", correctAnswer: "red", distractors: ["blue", "green", "yellow"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🔵\nما اسم هذا اللون بالإنجليزية؟", correctAnswer: "blue", distractors: ["red", "green", "black"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🟢\nما اسم هذا اللون بالإنجليزية؟", correctAnswer: "green", distractors: ["blue", "red", "yellow"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🟡\nما اسم هذا اللون بالإنجليزية؟", correctAnswer: "yellow", distractors: ["green", "red", "orange"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "⚫\nما اسم هذا اللون بالإنجليزية؟", correctAnswer: "black", distractors: ["white", "blue", "brown"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "⚪\nما اسم هذا اللون بالإنجليزية؟", correctAnswer: "white", distractors: ["black", "yellow", "red"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🖐️\nما اسم هذا العضو بالإنجليزية؟", correctAnswer: "hand", distractors: ["foot", "head", "leg"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "👁️\nما اسم هذا العضو بالإنجليزية؟", correctAnswer: "eye", distractors: ["ear", "nose", "mouth"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "👂\nما اسم هذا العضو بالإنجليزية؟", correctAnswer: "ear", distractors: ["eye", "nose", "hand"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "👃\nما اسم هذا العضو بالإنجليزية؟", correctAnswer: "nose", distractors: ["ear", "eye", "mouth"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "👄\nما اسم هذا العضو بالإنجليزية؟", correctAnswer: "mouth", distractors: ["nose", "ear", "eye"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌙\nما اسم هذا بالإنجليزية؟", correctAnswer: "moon", distractors: ["sun", "star", "sky"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "⭐\nما اسم هذا بالإنجليزية؟", correctAnswer: "star", distractors: ["moon", "sun", "cloud"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌳\nما اسم هذا بالإنجليزية؟", correctAnswer: "tree", distractors: ["flower", "grass", "leaf"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌸\nما اسم هذا بالإنجليزية؟", correctAnswer: "flower", distractors: ["tree", "grass", "leaf"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🏠\nما اسم هذا بالإنجليزية؟", correctAnswer: "house", distractors: ["door", "window", "room"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🚗\nما اسم هذا بالإنجليزية؟", correctAnswer: "car", distractors: ["bus", "train", "bike"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🚌\nما اسم هذا بالإنجليزية؟", correctAnswer: "bus", distractors: ["car", "train", "boat"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "✈️\nما اسم هذا بالإنجليزية؟", correctAnswer: "airplane", distractors: ["car", "boat", "train"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "📖\nما اسم هذا بالإنجليزية؟", correctAnswer: "book", distractors: ["pen", "bag", "desk"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "✏️\nما اسم هذا بالإنجليزية؟", correctAnswer: "pencil", distractors: ["book", "bag", "ruler"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "كيف نقول العدد 1 بالإنجليزية؟", correctAnswer: "one", distractors: ["two", "three", "four"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "كيف نقول العدد 2 بالإنجليزية؟", correctAnswer: "two", distractors: ["one", "three", "five"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "كيف نقول العدد 3 بالإنجليزية؟", correctAnswer: "three", distractors: ["two", "four", "six"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "كيف نقول العدد 4 بالإنجليزية؟", correctAnswer: "four", distractors: ["three", "five", "two"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "كيف نقول العدد 5 بالإنجليزية؟", correctAnswer: "five", distractors: ["four", "six", "three"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "كيف نقول «مرحبًا» بالإنجليزية؟", correctAnswer: "hello", distractors: ["goodbye", "thanks", "please"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐴\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "horse", distractors: ["cow", "goat", "sheep"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐑\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "sheep", distractors: ["goat", "cow", "horse"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦁\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "lion", distractors: ["tiger", "bear", "wolf"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐯\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "tiger", distractors: ["lion", "bear", "fox"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐻\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "bear", distractors: ["lion", "wolf", "fox"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐘\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "elephant", distractors: ["giraffe", "lion", "zebra"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦒\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "giraffe", distractors: ["elephant", "zebra", "horse"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐒\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "monkey", distractors: ["bear", "lion", "fox"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐸\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "frog", distractors: ["fish", "snake", "turtle"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐝\nما اسم هذا بالإنجليزية؟", correctAnswer: "bee", distractors: ["ant", "fly", "bird"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👟\nما اسم هذا بالإنجليزية؟", correctAnswer: "shoes", distractors: ["socks", "hat", "shirt"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نقول «أخ» بالإنجليزية؟", correctAnswer: "brother", distractors: ["sister", "father", "mother"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نقول «أخت» بالإنجليزية؟", correctAnswer: "sister", distractors: ["brother", "mother", "father"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما عكس كلمة up بالإنجليزية؟", correctAnswer: "down", distractors: ["left", "right", "top"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما عكس كلمة open بالإنجليزية؟", correctAnswer: "close", distractors: ["push", "pull", "lock"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما عكس كلمة happy بالإنجليزية؟", correctAnswer: "sad", distractors: ["mad", "tired", "shy"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما عكس كلمة fast بالإنجليزية؟", correctAnswer: "slow", distractors: ["quick", "soft", "loud"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما عكس كلمة new بالإنجليزية؟", correctAnswer: "old", distractors: ["young", "fresh", "clean"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نقول العدد 6 بالإنجليزية؟", correctAnswer: "six", distractors: ["seven", "five", "eight"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نقول العدد 7 بالإنجليزية؟", correctAnswer: "seven", distractors: ["six", "eight", "nine"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نقول العدد 8 بالإنجليزية؟", correctAnswer: "eight", distractors: ["seven", "nine", "six"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نقول العدد 9 بالإنجليزية؟", correctAnswer: "nine", distractors: ["eight", "ten", "seven"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نقول العدد 10 بالإنجليزية؟", correctAnswer: "ten", distractors: ["nine", "eight", "seven"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🪑\nما اسم هذا بالإنجليزية؟", correctAnswer: "chair", distractors: ["table", "bed", "door"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛏️\nكيف نقول «سرير» بالإنجليزية؟", correctAnswer: "bed", distractors: ["chair", "table", "sofa"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🪟\nما اسم هذا بالإنجليزية؟", correctAnswer: "window", distractors: ["door", "wall", "floor"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚲\nما اسم هذا بالإنجليزية؟", correctAnswer: "bicycle", distractors: ["car", "bus", "train"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚂\nما اسم هذا بالإنجليزية؟", correctAnswer: "train", distractors: ["bus", "car", "boat"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⛵\nما اسم هذا بالإنجليزية؟", correctAnswer: "boat", distractors: ["car", "train", "plane"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نقول «شكرًا» بالإنجليزية؟", correctAnswer: "thank you", distractors: ["please", "hello", "sorry"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نقول «من فضلك» بالإنجليزية؟", correctAnswer: "please", distractors: ["thanks", "sorry", "hello"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نقول «نعم» بالإنجليزية؟", correctAnswer: "yes", distractors: ["no", "maybe", "now"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كيف نجيب بكلمة «لا» بالإنجليزية؟", correctAnswer: "no", distractors: ["yes", "maybe", "never"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌈\nما اسم هذا بالإنجليزية؟", correctAnswer: "rainbow", distractors: ["cloud", "rain", "sky"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐔\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "chicken", distractors: ["duck", "bird", "goose"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦆\nما اسم هذا الحيوان بالإنجليزية؟", correctAnswer: "duck", distractors: ["chicken", "bird", "goose"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍰\nما اسم هذا بالإنجليزية؟", correctAnswer: "cake", distractors: ["bread", "cookie", "pie"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما عكس كلمة good بالإنجليزية؟", correctAnswer: "bad", distractors: ["nice", "kind", "fine"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما عكس كلمة clean بالإنجليزية؟", correctAnswer: "dirty", distractors: ["wet", "old", "dark"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عكس كلمة full بالإنجليزية؟", correctAnswer: "empty", distractors: ["heavy", "light", "open"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عكس كلمة heavy بالإنجليزية؟", correctAnswer: "light", distractors: ["full", "soft", "thin"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عكس كلمة strong بالإنجليزية؟", correctAnswer: "weak", distractors: ["soft", "small", "thin"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عكس كلمة easy بالإنجليزية؟", correctAnswer: "hard", distractors: ["soft", "slow", "weak"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عكس كلمة first بالإنجليزية؟", correctAnswer: "last", distractors: ["next", "best", "near"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عكس كلمة near بالإنجليزية؟", correctAnswer: "far", distractors: ["close", "next", "here"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عكس كلمة loud بالإنجليزية؟", correctAnswer: "quiet", distractors: ["proud", "slow", "calm"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «يركض» بالإنجليزية؟", correctAnswer: "run", distractors: ["walk", "jump", "swim"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «يقفز» بالإنجليزية؟", correctAnswer: "jump", distractors: ["run", "walk", "climb"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «يسبح» بالإنجليزية؟", correctAnswer: "swim", distractors: ["run", "jump", "fly"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «يأكل» بالإنجليزية؟", correctAnswer: "eat", distractors: ["drink", "cook", "sleep"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «يشرب» بالإنجليزية؟", correctAnswer: "drink", distractors: ["eat", "cook", "wash"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «ينام» بالإنجليزية؟", correctAnswer: "sleep", distractors: ["eat", "wake", "rest"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «يقرأ» بالإنجليزية؟", correctAnswer: "read", distractors: ["write", "draw", "speak"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «يكتب» بالإنجليزية؟", correctAnswer: "write", distractors: ["read", "draw", "talk"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «يمشي» بالإنجليزية؟", correctAnswer: "walk", distractors: ["run", "jump", "stand"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما جمع كلمة cat بالإنجليزية؟", correctAnswer: "cats", distractors: ["cates", "caties", "cat"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "ما جمع كلمة dog بالإنجليزية؟", correctAnswer: "dogs", distractors: ["doges", "dogies", "dog"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "ما جمع كلمة box بالإنجليزية؟", correctAnswer: "boxes", distractors: ["boxs", "boxies", "box"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "ما جمع كلمة baby بالإنجليزية؟", correctAnswer: "babies", distractors: ["babys", "babyes", "baby"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "ما جمع كلمة child بالإنجليزية؟", correctAnswer: "children", distractors: ["childs", "childes", "childrens"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "ما جمع كلمة mouse بالإنجليزية؟", correctAnswer: "mice", distractors: ["mouses", "mouse", "mices"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "ما جمع كلمة foot بالإنجليزية؟", correctAnswer: "feet", distractors: ["foots", "feets", "foot"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "كيف نقول العدد 11 بالإنجليزية؟", correctAnswer: "eleven", distractors: ["twelve", "ten", "seven"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول العدد 12 بالإنجليزية؟", correctAnswer: "twelve", distractors: ["eleven", "twenty", "ten"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول العدد 20 بالإنجليزية؟", correctAnswer: "twenty", distractors: ["twelve", "thirty", "two"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول العدد 100 بالإنجليزية؟", correctAnswer: "hundred", distractors: ["thousand", "twenty", "ten"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐍\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "snake", distractors: ["turtle", "frog", "worm"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦉\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "owl", distractors: ["duck", "bat", "eagle"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐙\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "octopus", distractors: ["fish", "crab", "squid"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦀\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "crab", distractors: ["fish", "octopus", "shrimp"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌽\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "corn", distractors: ["carrot", "potato", "pea"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍉\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "watermelon", distractors: ["banana", "apple", "orange"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍍\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "pineapple", distractors: ["apple", "mango", "lemon"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧤\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "gloves", distractors: ["socks", "hat", "scarf"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧥\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "coat", distractors: ["shirt", "hat", "dress"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "👗\nكيف نقول هذا بالإنجليزية؟", correctAnswer: "dress", distractors: ["shirt", "coat", "skirt"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «جَدّ» بالإنجليزية؟", correctAnswer: "grandfather", distractors: ["grandmother", "father", "uncle"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «جَدّة» بالإنجليزية؟", correctAnswer: "grandmother", distractors: ["grandfather", "mother", "aunt"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «مُعلِّم» بالإنجليزية؟", correctAnswer: "teacher", distractors: ["student", "doctor", "driver"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «تلميذ» بالإنجليزية؟", correctAnswer: "student", distractors: ["teacher", "doctor", "friend"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «طبيب» بالإنجليزية؟", correctAnswer: "doctor", distractors: ["teacher", "nurse", "driver"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما هي صيغة الجمع لكلمة tooth بالإنجليزية؟", correctAnswer: "teeth", distractors: ["tooths", "teeths", "tooth"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "ما عكس كلمة wet بالإنجليزية؟", correctAnswer: "dry", distractors: ["hot", "cold", "clean"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ما عكس كلمة light (بمعنى مُضيء) بالإنجليزية؟", correctAnswer: "dark", distractors: ["white", "bright", "gray"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «الشتاء» بالإنجليزية؟", correctAnswer: "winter", distractors: ["summer", "spring", "autumn"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «الصيف» بالإنجليزية؟", correctAnswer: "summer", distractors: ["winter", "spring", "autumn"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «يوم الأحد» بالإنجليزية؟", correctAnswer: "Sunday", distractors: ["Monday", "Friday", "Saturday"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كيف نقول «صباح» بالإنجليزية؟", correctAnswer: "morning", distractors: ["evening", "night", "noon"], tier: .hard, grades: 4...6),
    ]
}
