import Foundation

/// 🧠 للموهوبين — بالعربية. مأخوذ عن البنك العبريّ (70 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let gifted: [BankQuestion] = [
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 2، 4، 6، 8، ؟", correctAnswer: "10", distractors: ["9", "11", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🖐️\nما العدد التالي في المتتالية: 5، 10، 15، 20، ؟", correctAnswer: "25", distractors: ["21", "24", "30"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 1، 3، 5، 7، ؟", correctAnswer: "9", distractors: ["8", "10", "11"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⬇️\nما العدد التالي في المتتالية: 10، 9، 8، 7، ؟", correctAnswer: "6", distractors: ["5", "4", "11"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 3، 6، 9، 12، ؟", correctAnswer: "15", distractors: ["13", "14", "16"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "✨\nما العدد التالي في المتتالية: 1، 2، 4، 8، ؟", correctAnswer: "16", distractors: ["10", "12", "14"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "💯\nما العدد التالي في المتتالية: 100، 90، 80، 70، ؟", correctAnswer: "60", distractors: ["65", "50", "69"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧤\nاليد : القفّاز كما القدم : ؟", correctAnswer: "الحذاء", distractors: ["القبّعة", "القميص", "الوشاح"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐦\nالطائر : السماء كما السمكة : ؟", correctAnswer: "البحر", distractors: ["الشجرة", "الصحراء", "الجبل"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐄\nالبقرة : الحليب كما الدجاجة : ؟", correctAnswer: "البيضة", distractors: ["الصوف", "العسل", "الجبنة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐘\nكبير : صغير كما ساخن : ؟", correctAnswer: "بارد", distractors: ["دافئ", "مبلول", "عالٍ"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧺\nأيٌّ لا ينتمي إلى المجموعة: تفّاحة، موزة، جزرة، إجّاصة؟", correctAnswer: "جزرة", distractors: ["تفّاحة", "موزة", "إجّاصة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎨\nأيٌّ لا ينتمي إلى المجموعة: أحمر، أزرق، دائريّ، أخضر؟", correctAnswer: "دائريّ", distractors: ["أحمر", "أزرق", "أخضر"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "📅\nأيٌّ لا ينتمي إلى المجموعة: الأحد، الاثنين، كانون الثاني، الثلاثاء؟", correctAnswer: "كانون الثاني", distractors: ["الأحد", "الاثنين", "الثلاثاء"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔤\nما الحرف التالي في المتتالية: أ، ب، ت، ث، ؟", correctAnswer: "ج", distractors: ["ح", "خ", "د"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔤\nما الحرف التالي في المتتالية: أ، ت، ج، خ، ؟", correctAnswer: "ذ", distractors: ["د", "ر", "ز"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔁\nما الشكل التالي في المتتالية: دائرة، مربّع، دائرة، مربّع، ؟", correctAnswer: "دائرة", distractors: ["مربّع", "مثلّث", "نجمة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌈\nما اللون التالي في المتتالية: أحمر، أحمر، أزرق، أحمر، أحمر، أزرق، أحمر، ؟", correctAnswer: "أحمر", distractors: ["أزرق", "أخضر", "أصفر"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍎\nلدى آدم 3 تفّاحات. أعطى واحدة لصديقه وأخذ 2 من أمّه. كم تفّاحة لديه الآن؟", correctAnswer: "4", distractors: ["3", "5", "6"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🚌\nكان في الحافلة 5 أطفال. في المحطّة صعد 3 ونزل 2. كم طفلًا في الحافلة الآن؟", correctAnswer: "6", distractors: ["4", "5", "10"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍬\nلدى سارة 6 حبّات حلوى، ولدى كرم أكثر منها بحبّتين. كم حبّة حلوى لدى كرم؟", correctAnswer: "8", distractors: ["4", "6", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕐\nالساعة الآن 3. كم ستكون الساعة بعد ساعتين؟", correctAnswer: "5", distractors: ["1", "4", "6"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐔\nكم رِجلًا لدى 3 دجاجات معًا؟", correctAnswer: "6", distractors: ["3", "9", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐶\nكم رِجلًا لدى كلبين ودجاجة واحدة معًا؟", correctAnswer: "10", distractors: ["6", "8", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🪑\nفي الصفّ 4 طاولات، وبجانب كلّ طاولة كرسيّان. كم كرسيًّا في الصفّ؟", correctAnswer: "8", distractors: ["4", "6", "10"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 1، 4، 9، 16، ؟", correctAnswer: "25", distractors: ["20", "24", "32"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 2، 3، 5، 8، 12، ؟", correctAnswer: "17", distractors: ["15", "16", "18"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐚\nما العدد التالي في المتتالية: 1، 1، 2، 3، 5، 8، ؟", correctAnswer: "13", distractors: ["10", "11", "16"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 3، 6، 12، 24، ؟", correctAnswer: "48", distractors: ["30", "36", "72"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 1، 2، 4، 7، 11، ؟", correctAnswer: "16", distractors: ["14", "15", "22"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔤\nما الحرف التالي في المتتالية: أ، ث، خ، ر، ؟", correctAnswer: "ش", distractors: ["س", "ص", "ض"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔤\nما الحرف التالي في المتتالية: ي، و، ه، ن، ؟", correctAnswer: "م", distractors: ["ل", "ك", "ق"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔷\nما الشكل التالي في المتتالية: مثلّث، مربّع، مخمّس، ؟", correctAnswer: "مسدّس", distractors: ["دائرة", "شبه منحرف", "مستطيل"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "📖\nالكتاب : القراءة كما قلم الرصاص : ؟", correctAnswer: "الكتابة", distractors: ["الغناء", "الركض", "الشرب"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "☀️\nساخن : الصيف كما بارد : ؟", correctAnswer: "الشتاء", distractors: ["الربيع", "الخريف", "الليل"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🩺\nالطبيب : المستشفى كما المعلّمة : ؟", correctAnswer: "المدرسة", distractors: ["المكتبة", "الدكّان", "المكتب"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nأيّ عدد لا ينتمي إلى المجموعة: 3، 5، 7، 8، 11؟", correctAnswer: "8", distractors: ["3", "7", "11"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥛\nأيٌّ لا ينتمي إلى المجموعة: ماء، حليب، عصير، خبز؟", correctAnswer: "خبز", distractors: ["ماء", "حليب", "عصير"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍂\nأيٌّ لا ينتمي إلى المجموعة: الصيف، الشتاء، الخريف، تمّوز؟", correctAnswer: "تمّوز", distractors: ["الصيف", "الشتاء", "الخريف"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🪞\nيقف آدم ووجهه نحو الشمال. يستدير نصف دورة. إلى أين يتّجه وجهه الآن؟", correctAnswer: "نحو الجنوب", distractors: ["نحو الشمال", "نحو الشرق", "نحو الغرب"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔄\nسهم يشير إلى الأعلى. ندوّره ربع دورة باتّجاه عقارب الساعة. إلى أين يشير الآن؟", correctAnswer: "إلى اليمين", distractors: ["إلى اليسار", "إلى الأسفل", "إلى الأعلى"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔄\nسهم يشير إلى اليمين. ندوّره نصف دورة. إلى أين يشير الآن؟", correctAnswer: "إلى اليسار", distractors: ["إلى الأعلى", "إلى الأسفل", "إلى اليمين"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "📄\nنطوي ورقة إلى نصفين، ثمّ نطويها إلى نصفين مرّة أخرى، ثمّ نفتحها. إلى كم جزءًا متساويًا انقسمت الورقة؟", correctAnswer: "4", distractors: ["2", "3", "8"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧦\nفي الدُّرج جوربان أحمران وجوربان أزرقان. كم جوربًا يجب إخراجه دون النظر لنكون متأكّدين من وجود زوج بلون واحد؟", correctAnswer: "3", distractors: ["1", "2", "4"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "⚖️\nأيّهما أثقل: كيلو ريش أم كيلو حديد؟", correctAnswer: "الوزن نفسه", distractors: ["كيلو الحديد", "كيلو الريش", "لا يمكن معرفة ذلك"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "📅\nإذا كان غدًا يوم الأربعاء، فأيّ يوم كان أمس؟", correctAnswer: "الاثنين", distractors: ["الثلاثاء", "الخميس", "الأحد"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🏃\nآدم يركض أسرع من كرم، وكرم يركض أسرع من جاد. مَن الأبطأ؟", correctAnswer: "جاد", distractors: ["آدم", "كرم", "لا يمكن معرفة ذلك"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐝\nما المشترك بين النملة والنحلة والذبابة؟", correctAnswer: "كلّها حشرات", distractors: ["كلّها طيور", "كلّها أسماك", "كلّها ثدييّات"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🏫\nفي الصفّ 12 ولدًا و14 بنتًا. ذهب 6 أطفال إلى المكتبة. كم طفلًا بقي في الصفّ؟", correctAnswer: "20", distractors: ["18", "22", "26"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "💰\nلدى جاد 20 شيكلًا. اشترى ممحاتين، ثمن كلّ ممحاة 3 شواكل. كم شيكلًا بقي معه؟", correctAnswer: "14", distractors: ["12", "16", "17"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🎂\nسارة عمرها 8 سنوات، وأخوها أكبر منها بـ3 سنوات. ما مجموع عمريهما؟", correctAnswer: "19", distractors: ["11", "16", "21"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🚗\nفي الموقف 3 سيّارات و4 درّاجات هوائيّة. كم عجلة في المجموع؟", correctAnswer: "20", distractors: ["14", "16", "24"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nكم عددًا من 1 حتّى 20 (بما في ذلك 20) يقبل القسمة على 5 دون باقٍ؟", correctAnswer: "4", distractors: ["2", "3", "5"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 2، 5، 11، 23، ؟", correctAnswer: "47", distractors: ["35", "45", "46"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 81، 27، 9، ؟", correctAnswer: "3", distractors: ["0", "1", "6"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 1، 2، 6، 24، ؟", correctAnswer: "120", distractors: ["48", "96", "100"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔀\nما العدد التالي في المتتالية: 1، 10، 2، 20، 3، 30، 4، ؟", correctAnswer: "40", distractors: ["5", "34", "50"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔢\nما العدد التالي في المتتالية: 3، 4، 6، 9، 13، ؟", correctAnswer: "18", distractors: ["16", "17", "20"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔤\nما الحرف التالي في المتتالية: ب، ث، ح، د، ؟", correctAnswer: "ر", distractors: ["ذ", "ز", "س"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔄\nسهم يشير إلى الأعلى. ندوّره 3 أرباع دورة باتّجاه عقارب الساعة. إلى أين يشير الآن؟", correctAnswer: "إلى اليسار", distractors: ["إلى اليمين", "إلى الأسفل", "إلى الأعلى"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔄\nسهم يشير إلى اليسار. ندوّره 5 أرباع دورة عكس اتّجاه عقارب الساعة. إلى أين يشير الآن؟", correctAnswer: "إلى الأسفل", distractors: ["إلى الأعلى", "إلى اليمين", "إلى اليسار"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "📄\nنطوي ورقة إلى نصفين ونقصّ مثلّثًا صغيرًا في منتصف خطّ الطيّ. عندما نفتح الورقة، أيّ شكل يظهر في وسطها؟", correctAnswer: "ثقب على شكل مُعيَّن", distractors: ["ثقب دائريّ", "ثقبان صغيران", "لا يوجد ثقب"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "👨‍👧‍👧\nلدى أب 3 بنات، ولكلّ بنت أخ واحد. كم طفلًا لدى الأب؟", correctAnswer: "4", distractors: ["3", "6", "7"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "7️⃣\nكم مرّة يظهر الرقم 7 في الأعداد من 1 إلى 50؟", correctAnswer: "5", distractors: ["4", "6", "10"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🤝\nيتصافح 4 أطفال، كلّ واحد مع كلّ واحد مرّة واحدة بالضبط. كم مصافحة في المجموع؟", correctAnswer: "6", distractors: ["4", "8", "12"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "📏\nجاد أطول من آدم، وآدم أقصر من كرم، وكرم أقصر من جاد. مَن الأوسط في الطول؟", correctAnswer: "كرم", distractors: ["جاد", "آدم", "لا يمكن معرفة ذلك"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "📅\nاليوم هو الثلاثاء. أيّ يوم سيكون بعد 10 أيّام؟", correctAnswer: "الجمعة", distractors: ["الأربعاء", "الخميس", "السبت"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🐇\nفي الساحة أرانب ودجاجات. المجموع 5 رؤوس و14 رِجلًا. كم أرنبًا في الساحة؟", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "✏️\nفي الدكّان 3 علب، في كلّ علبة 8 أقلام رصاص. نوزّع كلّ الأقلام بالتساوي على 4 أطفال. كم قلمًا يأخذ كلّ طفل؟", correctAnswer: "6", distractors: ["4", "8", "12"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🎂\nكرم عمره 10 سنوات وعمر أمّه 40 سنة. بعد كم سنة يصبح عمر أمّه 3 أضعاف عمره؟", correctAnswer: "5", distractors: ["3", "4", "10"], tier: .hard, grades: 4...5),
    ]
}
