import Foundation

/// 📜 التاريخ — بالعربية. مأخوذ عن البنك العبريّ (277 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let history: [BankQuestion] = [
        BankQuestion(prompt: "🇮🇱\nفي أي عام قامت دولة إسرائيل؟", correctAnswer: "1948", distractors: ["1945", "1950", "1967"], grades: 2...4),
        BankQuestion(prompt: "👨‍💼\nمن كان أول رئيس حكومة لإسرائيل؟", correctAnswer: "دافيد بن غوريون", distractors: ["إسحاق رابين", "مناحيم بيغن", "غولدا مئير"], grades: 2...4),
        BankQuestion(prompt: "🕯️\nفي أي عيد يهودي تُضاء الشموع ثماني ليالٍ متتالية؟", correctAnswer: "حانوكا", distractors: ["بيساح", "سوكوت", "بوريم"], grades: 0...2),
        BankQuestion(prompt: "🫓\nفي أي عيد يهودي يأكل الناس الفطير (مَتْسا)؟", correctAnswer: "بيساح", distractors: ["حانوكا", "رأس السنة العبرية", "شفوعوت"], grades: 0...2),
        BankQuestion(prompt: "🎭\nفي أي عيد يهودي يتنكّر الأطفال بالأزياء؟", correctAnswer: "بوريم", distractors: ["سوكوت", "حانوكا", "بيساح"], grades: 0...2),
        BankQuestion(prompt: "🌳\nفي أي عيد يهودي يخرج الناس لغرس الشتلات؟", correctAnswer: "طو بشفاط", distractors: ["عيد الاستقلال", "شفوعوت", "لاج بعومير"], grades: 1...3),
        BankQuestion(prompt: "🇮🇱\nما الرمز الذي يتوسّط علم إسرائيل؟", correctAnswer: "نجمة داود", distractors: ["الهلال", "الصليب", "النسر"], grades: 2...4),
        BankQuestion(prompt: "📜\nما الذي أعلنته وثيقة الاستقلال الإسرائيلية عام 1948؟", correctAnswer: "قيام دولة إسرائيل", distractors: ["قصة عيد الفصح اليهودي", "وصفة طبخ", "قصيدة غنائية"], grades: 3...5),
        BankQuestion(prompt: "👑\nحسب الرواية التوراتية، من كان أول ملك لبني إسرائيل؟", correctAnswer: "شاول", distractors: ["داود", "سليمان", "إبراهيم"], grades: 3...5),
        BankQuestion(prompt: "🏛️\nحسب الرواية التوراتية، من بنى الهيكل الأول في القدس؟", correctAnswer: "سليمان", distractors: ["داود", "موسى", "شاول"], grades: 3...5),
        BankQuestion(prompt: "🏺\nحسب الرواية اليهودية، ماذا وجد المكابيون في الهيكل بعد تطهيره؟", correctAnswer: "إبريق زيت صغير", distractors: ["رغيف فطير", "بوقًا", "كتابًا"], grades: 1...3),
        BankQuestion(prompt: "🐑\nحسب الرواية التوراتية، من قاد بني إسرائيل في خروجهم من مصر؟", correctAnswer: "موسى", distractors: ["يوسف", "إبراهيم", "داود"], grades: 1...3),
        BankQuestion(prompt: "🏛️\nهل بنى المصريون القدماء أهرامات الجيزة؟", correctAnswer: "نعم", distractors: ["لا", "بناها الرومان", "بناها اليونانيون"], grades: 4...6),
        BankQuestion(prompt: "🇺🇸\nإلى أي قارة وصل كولومبوس عام 1492؟", correctAnswer: "أمريكا", distractors: ["إفريقيا", "أستراليا", "آسيا"], grades: 4...6),
        BankQuestion(prompt: "📡\nمن اخترع الهاتف؟", correctAnswer: "ألكسندر غراهام بيل", distractors: ["ألبرت أينشتاين", "توماس إديسون", "بيل غيتس"], grades: 3...5),
        BankQuestion(prompt: "💡\nمن طوّر أول مصباح كهربائي صالح للاستعمال اليومي؟", correctAnswer: "توماس إديسون", distractors: ["ألبرت أينشتاين", "إسحاق نيوتن", "نيكولا تسلا"], grades: 3...5),
        BankQuestion(prompt: "📕\nما اللغة الأساسية التي كُتب بها التناخ (الكتاب المقدّس العبري)؟", correctAnswer: "العبرية", distractors: ["الإنجليزية", "العربية", "اليونانية"], grades: 2...4),
        BankQuestion(prompt: "📜\nحسب الرواية التوراتية، في أي أرض عاش الآباء إبراهيم وإسحاق ويعقوب؟", correctAnswer: "في أرض كنعان", distractors: ["في مصر", "في أمريكا", "في أوروبا"], grades: 2...4),
        BankQuestion(prompt: "📚\nكم سِفرًا يضمّ التوراة عند اليهود؟", correctAnswer: "5", distractors: ["7", "10", "3"], grades: 2...4),
        BankQuestion(prompt: "🛡️\nحسب الرواية التوراتية، من حارب جُلْيات؟", correctAnswer: "داود", distractors: ["موسى", "سليمان", "شاول"], grades: 2...4),
        BankQuestion(prompt: "في أي عام أُعلن قيام دولة إسرائيل؟", correctAnswer: "1948", distractors: ["1918", "1967", "1938"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "من كان أول رئيس حكومة في إسرائيل؟", correctAnswer: "دافيد بن غوريون", distractors: ["حاييم وايزمان", "غولدا مئير", "مناحيم بيغن"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "أي شعب قديم بنى الأهرامات في مصر؟", correctAnswer: "المصريون القدماء", distractors: ["الرومان", "اليونانيون", "البابليون"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "من أول إنسان وطئت قدمه سطح القمر؟", correctAnswer: "نيل أرمسترونغ", distractors: ["يوري غاغارين", "باز ألدرين", "ألبرت أينشتاين"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "ماذا تُسمّى الكتابة التي استعملها المصريون القدماء؟", correctAnswer: "الكتابة الهيروغليفية", distractors: ["الكتابة المسمارية", "الأبجدية اللاتينية", "الكتابة الصينية"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أي مخترع أمريكي اشتهر بتطوير المصباح الكهربائي؟", correctAnswer: "توماس إديسون", distractors: ["ألبرت أينشتاين", "إسحاق نيوتن", "ليوناردو دافنشي"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أي مدينة قديمة دُفنت تحت رماد بركان فيزوف؟", correctAnswer: "بومبي", distractors: ["أثينا", "روما", "القدس"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "من رسم لوحة الموناليزا؟", correctAnswer: "ليوناردو دافنشي", distractors: ["بيكاسو", "فان غوخ", "مايكل أنجلو"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "في التقليد اليهودي، بأي حدث يرتبط عيد حانوكا؟", correctAnswer: "بانتصار المكابيين ومعجزة إبريق الزيت", distractors: ["بالخروج من مصر", "بإنقاذ يهود بلاد فارس", "بتلقّي التوراة"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "من أول امرأة تولّت رئاسة الحكومة في إسرائيل؟", correctAnswer: "غولدا مئير", distractors: ["تسيبي ليفني", "شولاميت ألوني", "حنّة سينيش"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🫓\nفي التقليد اليهودي، أي حدث يُحييه عيد الفصح (بيساح)؟", correctAnswer: "الخروج من مصر", distractors: ["تلقّي التوراة", "معجزة إبريق الزيت", "قيام دولة إسرائيل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🕎\nفي التقليد اليهودي، أي حدث يُحييه عيد حانوكا؟", correctAnswer: "معجزة إبريق الزيت وانتصار المكابيين", distractors: ["الخروج من مصر", "تلقّي التوراة", "قيام دولة إسرائيل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎭\nفي التقليد اليهودي، أي حدث يُحييه عيد بوريم؟", correctAnswer: "إنقاذ اليهود في أيام إستير ومردخاي", distractors: ["الخروج من مصر", "معجزة إبريق الزيت", "غرس الأشجار"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "📜\nفي التقليد اليهودي، أي حدث يُحييه عيد شفوعوت؟", correctAnswer: "تلقّي التوراة في جبل سيناء", distractors: ["الخروج من مصر", "تدشين الهيكل", "إنقاذ يهود بلاد فارس"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎉\nماذا يُحيي عيد الاستقلال في إسرائيل؟", correctAnswer: "إعلان قيام الدولة عام 1948", distractors: ["تلقّي التوراة", "الخروج من مصر", "رأس السنة العبرية"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧱\nالحائط الغربي في القدس، المعروف عند العرب بحائط البراق، هو بقيّة من سور أي مبنى قديم؟", correctAnswer: "الهيكل اليهودي", distractors: ["قصر الملك", "سور أريحا", "قلعة مسادا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎩\nمن مؤسّس الحركة الصهيونية السياسية الذي دعا إلى إقامة دولة يهودية؟", correctAnswer: "بنيامين زئيف (تيودور) هرتسل", distractors: ["دافيد بن غوريون", "حاييم وايزمان", "إسحاق رابين"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📣\nمن أعلن قيام دولة إسرائيل عام 1948؟", correctAnswer: "دافيد بن غوريون", distractors: ["بنيامين زئيف هرتسل", "غولدا مئير", "إسحاق رابين"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🙏\nفي أي مدينة يقع الحائط الغربي (حائط البراق)؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "صفد"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🛖\nفي التقليد اليهودي، ذكرى أي حدث يجلس الناس في العريشة أيام عيد سوكوت؟", correctAnswer: "ذكرى التيه في الصحراء بعد الخروج من مصر", distractors: ["ذكرى بناء الهيكل", "ذكرى معجزة إبريق الزيت", "ذكرى تلقّي التوراة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📯\nفي أي آلة يُنفخ في الكنيس في رأس السنة العبرية؟", correctAnswer: "الشوفار (قرن الكبش)", distractors: ["البوق النحاسي", "الطبل", "الناي"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔥\nماذا يُشعل اليهود في ليلة لاج بعومير؟", correctAnswer: "نيرانًا كبيرة في الخلاء", distractors: ["شموع حانوكا", "الألعاب النارية", "الفوانيس الورقية"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔺\nفي أي بلد قديم بُنيت الأهرامات الكبرى؟", correctAnswer: "مصر", distractors: ["اليونان", "روما", "بابل"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "📜\nماذا تُسمّى الكتابة القديمة في مصر؟", correctAnswer: "الكتابة الهيروغليفية", distractors: ["الكتابة المسمارية", "الأبجدية العبرية", "الأبجدية اللاتينية"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🧱\nماذا تُسمّى الكتابة القديمة في بابل وسومر؟", correctAnswer: "الكتابة المسمارية", distractors: ["الكتابة الهيروغليفية", "الكتابة اليونانية", "الكتابة الصينية"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🏅\nفي أي بلد قديم وُلدت الألعاب الأولمبية؟", correctAnswer: "اليونان", distractors: ["روما", "مصر", "بلاد فارس"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🏛️\nأي إمبراطورية حكمت هذه البلاد قبل نحو ألفَي سنة؟", correctAnswer: "الإمبراطورية الرومانية", distractors: ["الإمبراطورية اليونانية", "مملكة مصر القديمة", "مملكة بابل"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🕍\nفي أي مدينة كان يقوم الهيكل اليهودي؟", correctAnswer: "القدس", distractors: ["الخليل", "أريحا", "بئر السبع"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🏞️\nبجوار أي نهر كبير قامت حضارة مصر القديمة؟", correctAnswer: "النيل", distractors: ["الأردن", "الفرات", "الأمازون"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🦉\nأي مدينة يونانية قديمة اشتهرت بالحكمة والفلاسفة؟", correctAnswer: "أثينا", distractors: ["إسبرطة", "روما", "الإسكندرية"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "👑\nبأي لقب كان يُعرف ملوك مصر القديمة؟", correctAnswer: "فرعون", distractors: ["قيصر", "سلطان", "تسار"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🏰\nأي قلعة قديمة تقوم على جبل قرب البحر الميت؟", correctAnswer: "مسادا", distractors: ["برج داود في القدس", "قلعة عكا", "قلعة النمرود"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "📜\nأي دولة أصدرت وعد بلفور عام 1917؟", correctAnswer: "بريطانيا", distractors: ["فرنسا", "الولايات المتحدة", "تركيا"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🧳\nماذا تعني كلمة «عَلِيّاه» في تاريخ الشعب اليهودي؟", correctAnswer: "هجرة اليهود إلى أرض إسرائيل", distractors: ["رحلة سياحية إلى خارج البلاد", "تسلّق الجبال", "الانتقال إلى بيت جديد في المدينة"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏘️\nأي مستعمَرة يهودية أُقيمت في فترة «العَلِيّاه الأولى»؟", correctAnswer: "ريشون لتسيون", distractors: ["تل أبيب", "إيلات", "كرميئيل"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "📅\nفي أي شهر عبري يقع عيد استقلال إسرائيل؟", correctAnswer: "إيّار", distractors: ["نيسان", "تِشري", "آذار"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🗓️\nفي أي عام وقعت حرب الأيام الستة؟", correctAnswer: "1967", distractors: ["1948", "1956", "1973"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏙️\nفي حرب الأيام الستة سيطرت إسرائيل على الجزء الشرقي من أي مدينة؟", correctAnswer: "القدس", distractors: ["حيفا", "بئر السبع", "طبريا"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "👩‍💼\nمن أول امرأة شغلت منصب رئيس الحكومة في إسرائيل؟", correctAnswer: "غولدا مئير", distractors: ["حنّة سينيش", "نعمي شيمر", "سارة أهرونسون"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🕊️\nأي جائزة نالها رئيس الحكومة إسحاق رابين عام 1994؟", correctAnswer: "جائزة نوبل للسلام", distractors: ["جائزة إسرائيل", "ميدالية أولمبية", "جائزة الأوسكار"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🌍\nماذا تعني كلمة «غالوت» في تاريخ الشعب اليهودي؟", correctAnswer: "عيش اليهود بعيدًا عن أرض إسرائيل", distractors: ["عيد يهودي قديم", "اسم مدينة قديمة", "سِفر من أسفار التناخ"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🎪\nفي أي مدينة عُقد المؤتمر الصهيوني الأول عام 1897؟", correctAnswer: "بازل", distractors: ["فيينا", "باريس", "القدس"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏺\nأي حضارة قديمة بنت الأهرامات؟", correctAnswer: "المصريون القدماء", distractors: ["الرومان", "اليونانيون", "الفايكنغ"], grades: 5...6),
        BankQuestion(prompt: "👑\nمن كان أول إمبراطور لروما؟", correctAnswer: "أوغسطس", distractors: ["يوليوس قيصر", "نيرون", "هادريان"], grades: 5...6),
        BankQuestion(prompt: "⚔️\nأي إمبراطورية دمّرت الهيكل الثاني في القدس سنة 70 للميلاد؟", correctAnswer: "الرومان", distractors: ["اليونانيون", "البابليون", "الفرس"], grades: 5...6),
        BankQuestion(prompt: "✡️\nحسب الرواية التوراتية، ما اسم الذي قاد الشعب في الخروج من مصر؟", correctAnswer: "موسى", distractors: ["داود", "سليمان", "إبراهيم"], grades: 2...4),
        BankQuestion(prompt: "🏛️\nأين عُقدت الجلسة الأولى للكنيست عام 1949؟", correctAnswer: "في القدس", distractors: ["في تل أبيب", "في حيفا", "في بئر السبع"], grades: 2...4),
        BankQuestion(prompt: "🎺\nحسب الرواية التوراتية، ما الذي جعل أسوار أريحا تنهار؟", correctAnswer: "صوت الأبواق", distractors: ["هزّة أرضية", "عاصفة رملية", "الطوفان"], grades: 2...4),
        BankQuestion(prompt: "🏰\nحسب الرواية التوراتية، أي ملك بنى الهيكل الأول؟", correctAnswer: "الملك سليمان", distractors: ["الملك داود", "الملك شاول", "الملك حزقيا"], grades: 2...4),
        BankQuestion(prompt: "⚖️\nحسب الرواية التوراتية، من مَلَك بعد داود؟", correctAnswer: "سليمان", distractors: ["شاول", "يربعام", "رحبعام"], grades: 2...4),
        BankQuestion(prompt: "🦁\nحسب سِفر دانيال، أي ملك ألقى دانيال في جُبّ الأسود؟", correctAnswer: "الملك داريوس", distractors: ["نبوخذ نصّر", "أحشويروش", "كورش"], grades: 2...4),
        BankQuestion(prompt: "👑\nمن كانت الملكة إستير حسب الرواية التوراتية؟", correctAnswer: "ملكة فارس", distractors: ["ملكة مصر", "ملكة بابل", "ملكة روما"], grades: 2...4),
        BankQuestion(prompt: "📜\nما اللغة الأساسية التي كُتب بها التناخ؟", correctAnswer: "العبرية", distractors: ["اليونانية", "الآرامية", "العربية"], grades: 2...4),
        BankQuestion(prompt: "🛤️\nمتى قامت دولة إسرائيل؟", correctAnswer: "1948", distractors: ["1917", "1967", "1973"], grades: 2...4),
        BankQuestion(prompt: "📜\nمن تلا وثيقة إعلان الاستقلال عام 1948؟", correctAnswer: "دافيد بن غوريون", distractors: ["حاييم وايزمان", "مناحيم بيغن", "غولدا مئير"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nفي أي مدينة أُعلن قيام دولة إسرائيل عام 1948؟", correctAnswer: "تل أبيب", distractors: ["القدس", "حيفا", "طبريا"], grades: 2...4),
        BankQuestion(prompt: "👵\nمن أول امرأة ترأّست الحكومة في إسرائيل؟", correctAnswer: "غولدا مئير", distractors: ["شولاميت ألوني", "تسيبي ليفني", "ميري ريغيف"], grades: 3...5),
        BankQuestion(prompt: "🦅\nأي رمز يظهر في وسط علم إسرائيل؟", correctAnswer: "نجمة داود", distractors: ["الأسد", "النسر", "غصن الزيتون"], grades: 2...4),
        BankQuestion(prompt: "🇺🇸\nفي أي عام أُعلن استقلال الولايات المتحدة؟", correctAnswer: "1776", distractors: ["1620", "1492", "1800"], grades: 5...6),
        BankQuestion(prompt: "🧭\nمن الرحّالة الذي وصل إلى أمريكا عام 1492؟", correctAnswer: "كريستوفر كولومبوس", distractors: ["ماجلان", "فاسكو دا غاما", "ماركو بولو"], grades: 5...6),
        BankQuestion(prompt: "🚀\nمن أول إنسان مشى على سطح القمر؟", correctAnswer: "نيل أرمسترونغ", distractors: ["يوري غاغارين", "باز ألدرين", "جون غلين"], grades: 3...5),
        BankQuestion(prompt: "🚀\nمن أول إنسان سافر إلى الفضاء؟", correctAnswer: "يوري غاغارين", distractors: ["نيل أرمسترونغ", "آلان شيبرد", "باز ألدرين"], grades: 3...5),
        BankQuestion(prompt: "🎨\nأي فنان من عصر النهضة رسم لوحة الموناليزا؟", correctAnswer: "ليوناردو دافنشي", distractors: ["مايكل أنجلو", "بيكاسو", "فان غوخ"], grades: 4...6),
        BankQuestion(prompt: "🎼\nمن ألّف مقطوعة «موسيقى ليلية صغيرة»؟", correctAnswer: "موتسارت", distractors: ["بيتهوفن", "باخ", "شوبان"], grades: 4...6),
        BankQuestion(prompt: "💡\nأي مخترع يرتبط اسمه بالمصباح الكهربائي؟", correctAnswer: "إديسون", distractors: ["أينشتاين", "نيوتن", "غراهام بيل"], grades: 3...5),
        BankQuestion(prompt: "📞\nمن اخترع الهاتف؟", correctAnswer: "ألكسندر غراهام بيل", distractors: ["إديسون", "ماركوني", "نيوتن"], grades: 3...5),
        BankQuestion(prompt: "🌌\nمن العالم الذي صاغ قانون الجاذبية العام؟", correctAnswer: "نيوتن", distractors: ["أينشتاين", "غاليليو", "كوبرنيكوس"], grades: 3...5),
        BankQuestion(prompt: "🧪\nمن اكتشف البنسلين؟", correctAnswer: "ألكسندر فليمنغ", distractors: ["لويس باستور", "توماس إديسون", "ماري كوري"], grades: 5...6),
        BankQuestion(prompt: "👩‍🔬\nمن أول امرأة نالت جائزة نوبل؟", correctAnswer: "ماري كوري", distractors: ["روزاليند فرانكلين", "فلورنس نايتنغيل", "آدا لافليس"], grades: 5...6),
        BankQuestion(prompt: "🏛️\nأي بلد قديم يُعدّ مهد الديمقراطية؟", correctAnswer: "اليونان", distractors: ["روما", "مصر", "الصين"], grades: 5...6),
        BankQuestion(prompt: "📜\nما أقدم ملحمة أدبية معروفة في العالم؟", correctAnswer: "ملحمة جلجامش", distractors: ["الإلياذة", "الأوديسة", "التناخ"], grades: 5...6),
        BankQuestion(prompt: "🏯\nفي أي قارة يقع السور العظيم الذي بناه أباطرة الصين؟", correctAnswer: "آسيا", distractors: ["أوروبا", "إفريقيا", "أستراليا"], grades: 3...5),
        BankQuestion(prompt: "🗡️\nمن قاد الجيش الفرنسي في مطلع القرن التاسع عشر؟", correctAnswer: "نابليون بونابرت", distractors: ["جورج واشنطن", "ونستون تشرشل", "بسمارك"], grades: 5...6),
        BankQuestion(prompt: "👑\nمن كانت الملكة إليزابيث الأولى؟", correctAnswer: "ملكة إنجلترا", distractors: ["ملكة فرنسا", "ملكة إسبانيا", "ملكة روسيا"], grades: 5...6),
        BankQuestion(prompt: "🇪🇬\nمن كانت كليوباترا؟", correctAnswer: "ملكة مصر", distractors: ["ملكة روما", "ملكة اليونان", "ملكة بابل"], grades: 5...6),
        BankQuestion(prompt: "⚔️\nفي أي عام بدأت الحرب العالمية الأولى؟", correctAnswer: "1914", distractors: ["1900", "1939", "1918"], grades: 5...6),
        BankQuestion(prompt: "⚔️\nفي أي عام انتهت الحرب العالمية الثانية؟", correctAnswer: "1945", distractors: ["1918", "1939", "1950"], grades: 5...6),
        BankQuestion(prompt: "🌐\nفي أي فترة ظهرت أولى شبكات الإنترنت؟", correctAnswer: "في ستينيات القرن العشرين", distractors: ["في عام 1900", "في خمسينيات القرن التاسع عشر", "في عام 2000"], grades: 3...5),
        BankQuestion(prompt: "📱\nفي أي عام صدر أول هاتف آيفون؟", correctAnswer: "2007", distractors: ["1990", "2000", "2015"], grades: 3...5),
        BankQuestion(prompt: "🚂\nمن بنى قاطرة «الصاروخ» وأنشأ أول سكة حديد للركاب؟", correctAnswer: "جورج ستيفنسون", distractors: ["جيمس واط", "توماس إديسون", "هنري فورد"], grades: 3...5),
        BankQuestion(prompt: "🚗\nمن بنى أول سيارة تعمل بمحرّك البنزين؟", correctAnswer: "كارل بنز", distractors: ["هنري فورد", "توماس إديسون", "جيمس واط"], grades: 3...5),
        BankQuestion(prompt: "✈️\nمن حقّق أول طيران بطائرة ذات محرّك؟", correctAnswer: "الأخوان رايت", distractors: ["أينشتاين", "إديسون", "جيمس واط"], grades: 3...5),
        BankQuestion(prompt: "🇮🇱\nما الاسم الذي حملته هذه البلاد تحت الانتداب البريطاني قبل عام 1948؟", correctAnswer: "فلسطين", distractors: ["إسرائيل", "الأرض المقدّسة", "كنعان"], grades: 3...5),
        BankQuestion(prompt: "🇮🇱\nما طبيعة منصب رئيس الدولة في إسرائيل؟", correctAnswer: "منصب تمثيلي شرفي", distractors: ["إدارة الحكومة", "قيادة الجيش", "رئاسة المحكمة العليا"], grades: 4...6),
        BankQuestion(prompt: "🏛️\nكم عضوًا في الكنيست الإسرائيلي؟", correctAnswer: "120", distractors: ["100", "150", "200"], grades: 4...6),
        BankQuestion(prompt: "👴\nمن كان أول رئيس أركان للجيش الإسرائيلي؟", correctAnswer: "يعقوب دوري", distractors: ["دافيد بن غوريون", "موشيه ديان", "إسحاق رابين"], grades: 3...5),
        BankQuestion(prompt: "🏰\nمن القائد الذي استعاد القدس من الصليبيين سنة 1187 للميلاد؟", correctAnswer: "صلاح الدين الأيوبي", distractors: ["هارون الرشيد", "طارق بن زياد", "خالد بن الوليد"], grades: 2...4),
        BankQuestion(prompt: "🍯🍎\nفي أي عيد يهودي يُغمس التفاح بالعسل؟", correctAnswer: "رأس السنة العبرية", distractors: ["حانوكا", "بوريم", "شفوعوت"], grades: 2...4),
        BankQuestion(prompt: "🛖\nفي أي عيد يهودي يجلس الناس سبعة أيام في أكواخ مسقوفة بسعف النخيل؟", correctAnswer: "سوكوت", distractors: ["بيساح", "حانوكا", "بوريم"], grades: 2...4),
        BankQuestion(prompt: "🥛🧀\nفي أي عيد يهودي يُكثِر الناس من أكل الأطعمة المصنوعة من الحليب؟", correctAnswer: "شفوعوت", distractors: ["بيساح", "سوكوت", "بوريم"], grades: 2...4),
        BankQuestion(prompt: "🎁\nماذا تُسمّى هدايا الطعام التي يتبادلها اليهود في عيد بوريم؟", correctAnswer: "مشلوَح مانوت", distractors: ["أفيقومان", "سفيفون", "مَتْسا"], grades: 2...4),
        BankQuestion(prompt: "🥔\nأي طعام مقلي جرت العادة أن يُؤكل في عيد حانوكا؟", correctAnswer: "أقراص البطاطا المقلية (لِفيفوت)", distractors: ["الفطير", "خبز الحلّة", "التفاح بالعسل"], grades: 2...4),
        BankQuestion(prompt: "🍩\nأي حلوى جرت العادة أن تُؤكل في عيد حانوكا؟", correctAnswer: "سوفغانيّا (كعكة محشوّة بالمربّى)", distractors: ["كعكة الجزر", "الفطير", "خبز الحلّة"], grades: 2...4),
        BankQuestion(prompt: "🔄\nماذا تُسمّى اللعبة الدوّارة المرتبطة بعيد حانوكا؟", correctAnswer: "السفيفون (الخذروف)", distractors: ["الشوفار", "الخشخيشة", "الناي"], grades: 2...4),
        BankQuestion(prompt: "📣\nفي أي عيد يهودي يُحدث الأطفال ضجيجًا بالخشخيشة؟", correctAnswer: "بوريم", distractors: ["بيساح", "سوكوت", "طو بشفاط"], grades: 2...4),
        BankQuestion(prompt: "🍇\nفي أي عيد يهودي جرت العادة أن تُؤكل الفواكه المجفّفة؟", correctAnswer: "طو بشفاط", distractors: ["حانوكا", "بوريم", "يوم الغفران"], grades: 2...4),
        BankQuestion(prompt: "📖\nماذا يُسمّى الكتاب الذي يُقرأ في ليلة عيد الفصح اليهودي؟", correctAnswer: "الهَجّاداه", distractors: ["المِجِلّة", "كتاب الصلوات", "أسفار موسى"], grades: 2...4),
        BankQuestion(prompt: "🐍\nحسب الرواية التوراتية، إلى ماذا تحوّلت عصا موسى أمام فرعون؟", correctAnswer: "إلى أفعى", distractors: ["إلى ضفدع", "إلى أسد", "إلى حمامة"], grades: 2...4),
        BankQuestion(prompt: "🌊\nحسب الرواية التوراتية، أي بحر انشقّ أمام بني إسرائيل؟", correctAnswer: "بحر سوف (البحر الأحمر)", distractors: ["بحيرة طبريا", "البحر الميت", "نهر الأردن"], grades: 2...4),
        BankQuestion(prompt: "🛶\nحسب الرواية التوراتية، من بنى سفينة كبيرة وأدخل إليها الحيوانات؟", correctAnswer: "نوح", distractors: ["موسى", "إبراهيم", "داود"], grades: 2...4),
        BankQuestion(prompt: "🌈\nحسب الرواية التوراتية، أي علامة ظهرت في السماء بعد الطوفان؟", correctAnswer: "قوس قزح", distractors: ["نجمة", "سُلّم", "بوق"], grades: 2...4),
        BankQuestion(prompt: "🪜\nحسب الرواية التوراتية، من رأى في منامه سُلّمًا تصعد عليه الملائكة؟", correctAnswer: "يعقوب", distractors: ["يوسف", "موسى", "صموئيل"], grades: 2...4),
        BankQuestion(prompt: "🎨\nحسب الرواية التوراتية، من كان صاحب القميص المُلوَّن؟", correctAnswer: "يوسف", distractors: ["داود", "هارون", "إسحاق"], grades: 2...4),
        BankQuestion(prompt: "👶\nحسب الرواية التوراتية، أين وُجد الطفل موسى داخل سلّة؟", correctAnswer: "في نهر النيل", distractors: ["في الصحراء", "في العريشة", "على الجبل"], grades: 2...4),
        BankQuestion(prompt: "🗿\nحسب الرواية التوراتية، على ماذا كُتبت الوصايا العشر؟", correctAnswer: "على ألواح من حجر", distractors: ["على ورق", "على خشب", "على رمل"], grades: 2...4),
        BankQuestion(prompt: "🏔️\nحسب الرواية التوراتية، على أي جبل تلقّى موسى التوراة؟", correctAnswer: "جبل سيناء", distractors: ["جبل الشيخ (حرمون)", "جبل الكرمل", "جبل الجرمق"], grades: 2...4),
        BankQuestion(prompt: "🐑\nحسب الرواية التوراتية، ماذا كان عمل داود قبل أن يصير ملكًا؟", correctAnswer: "راعي غنم", distractors: ["نجّار", "صيّاد سمك", "كاهن"], grades: 2...4),
        BankQuestion(prompt: "🪨\nحسب الرواية التوراتية، بماذا هزم داود جُلْيات؟", correctAnswer: "بمقلاع وحجر", distractors: ["بسيف", "بقوس ونشّاب", "بعصا"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nكم لونًا في علم إسرائيل؟", correctAnswer: "لونان", distractors: ["ثلاثة ألوان", "أربعة ألوان", "لون واحد"], grades: 2...4),
        BankQuestion(prompt: "🎵\nماذا يُسمّى النشيد الوطني لدولة إسرائيل؟", correctAnswer: "«هَتِكفا»", distractors: ["«القدس الذهبية»", "«جئنا بالسلام»", "«الأرض الطيّبة»"], grades: 2...4),
        BankQuestion(prompt: "💰\nما اسم العملة المستعملة في إسرائيل؟", correctAnswer: "الشيكل", distractors: ["الدولار", "اليورو", "الليرة"], grades: 2...4),
        BankQuestion(prompt: "🌴\nعلى أي شجرة ينمو التمر؟", correctAnswer: "النخلة", distractors: ["البلّوط", "السرو", "الصنوبر"], grades: 2...4),
        BankQuestion(prompt: "🐪\nأي حيوان يُلقَّب بـ«سفينة الصحراء»؟", correctAnswer: "الجمل", distractors: ["الحصان", "الحمار", "البقرة"], grades: 2...4),
        BankQuestion(prompt: "💡\nما الاختراع الذي يرتبط باسم توماس إديسون ويضيء البيوت؟", correctAnswer: "المصباح الكهربائي", distractors: ["الهاتف", "الطائرة", "القطار"], grades: 3...5),
        BankQuestion(prompt: "✈️\nما الاختراع الذي قدّمه الأخوان رايت ويطير في السماء؟", correctAnswer: "الطائرة", distractors: ["السفينة", "الدرّاجة النارية", "الغوّاصة"], grades: 3...5),
        BankQuestion(prompt: "☎️\nما الجهاز الذي اخترعه غراهام بيل ويساعدنا على الكلام من بعيد؟", correctAnswer: "الهاتف", distractors: ["آلة التصوير", "الساعة", "الحاسوب"], grades: 3...5),
        BankQuestion(prompt: "🕯️\nكم شمعة تُضاء في الليلة الأخيرة من عيد حانوكا؟", correctAnswer: "ثماني شموع", distractors: ["شمعة واحدة", "شمعتان", "أربع شموع"], grades: 2...4),
        BankQuestion(prompt: "📜\nأي مِجِلّة تُقرأ في عيد بوريم؟", correctAnswer: "مِجِلّة إستير", distractors: ["مِجِلّة راعوث", "الهَجّاداه", "التوراة"], grades: 2...4),
        BankQuestion(prompt: "🍞\nأي طعام يمتنع اليهود عن أكله في عيد الفصح؟", correctAnswer: "الخبز المخمّر", distractors: ["الفطير", "التفاح", "الجوز"], grades: 2...4),
        BankQuestion(prompt: "🌳\nفي أي عيد يهودي يغرس الأطفال الشتلات في المدرسة؟", correctAnswer: "طو بشفاط", distractors: ["بوريم", "شفوعوت", "سوكوت"], grades: 2...4),
        BankQuestion(prompt: "🎭\nماذا جرت العادة أن يلبس الأطفال في عيد بوريم؟", correctAnswer: "زيًّا تنكّريًّا", distractors: ["معطف مطر", "لباس البحر", "لباس النوم"], grades: 2...4),
        BankQuestion(prompt: "🐸\nحسب الرواية التوراتية، أي حيوان كان إحدى ضربات مصر العشر؟", correctAnswer: "الضفدع", distractors: ["الفيل", "الدبّ", "الزرافة"], grades: 2...4),
        BankQuestion(prompt: "👑\nحسب الرواية التوراتية، أي ملك حكيم بنى الهيكل في القدس؟", correctAnswer: "سليمان", distractors: ["شاول", "يوسف", "هارون"], grades: 2...4),
        BankQuestion(prompt: "🐋\nحسب الرواية التوراتية، ما الذي ابتلع النبي يونس في البحر؟", correctAnswer: "سمكة كبيرة", distractors: ["تمساح", "أخطبوط", "قرش"], grades: 2...4),
        BankQuestion(prompt: "⭐\nماذا يُسمّى الرمز السداسي الأطراف الذي يتوسّط علم إسرائيل؟", correctAnswer: "نجمة داود", distractors: ["الشمعدان", "الشوفار", "التاج"], grades: 2...4),
        BankQuestion(prompt: "🕎\nأي رمز ذي سبع شُعب هو شعار دولة إسرائيل؟", correctAnswer: "الشمعدان (المينوراه)", distractors: ["السفيفون", "الخشخيشة", "البوق"], grades: 2...4),
        BankQuestion(prompt: "🏛️\nما عاصمة دولة إسرائيل؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "إيلات"], grades: 2...4),
        BankQuestion(prompt: "🌸\nفي أي فصل من السنة يقع عيد الفصح اليهودي؟", correctAnswer: "في الربيع", distractors: ["في الشتاء", "في الصيف", "في الخريف"], grades: 2...4),
        BankQuestion(prompt: "🍯\nفي رأس السنة العبرية يتمنّى اليهود أن تكون السنة الجديدة...؟", correctAnswer: "حلوة", distractors: ["باردة", "طويلة", "ممطرة"], grades: 2...4),
        BankQuestion(prompt: "📯\nفي أي آلة يُنفخ في رأس السنة العبرية؟", correctAnswer: "الشوفار", distractors: ["الناي", "الطبل", "البيانو"], grades: 2...4),
        BankQuestion(prompt: "🌿\nأي ثمرة تُرفع مع سعفة النخيل (اللولاب) في عيد سوكوت؟", correctAnswer: "الأُترُجّ", distractors: ["التفاحة", "البندورة", "الوردة"], grades: 2...4),
        BankQuestion(prompt: "👫\nحسب الرواية التوراتية، من أول رجل وأول امرأة؟", correctAnswer: "آدم وحوّاء", distractors: ["نوح وسارة", "موسى وراعوث", "داود وإستير"], grades: 2...4),
        BankQuestion(prompt: "🏰\nأي مدينة قديمة في شمال البلاد يحيط بها سور بحري وفيها ميناء قديم؟", correctAnswer: "عكا", distractors: ["الناصرة", "بئر السبع", "طبريا"], grades: 2...4),
        BankQuestion(prompt: "🐑\nحسب الرواية التوراتية، أي حيوان قدّمه إبراهيم قربانًا بدل إسحاق؟", correctAnswer: "كبش", distractors: ["بقرة", "حمامة", "سمكة"], grades: 2...4),
        BankQuestion(prompt: "💍\nحسب الرواية التوراتية، من زوجة إسحاق التي التقاها عند البئر؟", correctAnswer: "رفقة", distractors: ["سارة", "ليئة", "دبورة"], grades: 2...4),
        BankQuestion(prompt: "🦁\nأي حيوان يظهر في شعار مدينة القدس؟", correctAnswer: "الأسد", distractors: ["الجمل", "السمكة", "الحمامة"], grades: 2...4),
        BankQuestion(prompt: "🥖\nأي خبز خاص يأكله اليهود في يوم السبت؟", correctAnswer: "خبز الحلّة", distractors: ["الفطير", "الخبز العربي", "الباغيت"], grades: 2...4),
        BankQuestion(prompt: "🕯️🕯️\nمتى يُشعل اليهود الشموع استقبالًا للسبت؟", correctAnswer: "مساء يوم الجمعة", distractors: ["يوم الأحد", "عند الظهر", "في ليلة حانوكا"], grades: 2...4),
        BankQuestion(prompt: "🏜️\nحسب الرواية التوراتية، كم سنة تاه بنو إسرائيل في الصحراء؟", correctAnswer: "أربعون سنة", distractors: ["سنة واحدة", "عشر سنوات", "مئة سنة"], grades: 2...4),
        BankQuestion(prompt: "🌊\nأي بحيرة في البلاد تزوّدنا بالمياه العذبة للشرب؟", correctAnswer: "بحيرة طبريا", distractors: ["البحر الميت", "البحر المتوسط", "البحر الأحمر"], grades: 2...4),
        BankQuestion(prompt: "🚲\nفي يوم الغفران تخلو الشوارع في إسرائيل من السيارات، فماذا يركب الأطفال فيها عادةً؟", correctAnswer: "الدرّاجات الهوائية", distractors: ["الخيل", "القطار", "السفينة"], grades: 2...4),
        BankQuestion(prompt: "في أي بلد قديم بُنيت الأهرامات؟", correctAnswer: "مصر", distractors: ["اليونان", "الصين", "إيطاليا"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "في أي عيد يهودي تُضاء شمعة إضافية كل ليلة حتى ثماني شموع؟", correctAnswer: "حانوكا", distractors: ["بوريم", "بيساح", "سوكوت"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "في أي عيد يهودي يتنكّر الناس ويأكلون حلوى «آذان هامان»؟", correctAnswer: "بوريم", distractors: ["حانوكا", "بيساح", "شفوعوت"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "في أي عيد يهودي يأكل الناس الفطير بدل الخبز؟", correctAnswer: "بيساح", distractors: ["بوريم", "حانوكا", "سوكوت"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "في أي عيد يهودي يبني الناس كوخًا صغيرًا في الساحة ويأكلون فيه؟", correctAnswer: "سوكوت", distractors: ["بوريم", "بيساح", "حانوكا"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أي اختراع يعطينا الضوء في الغرفة ليلًا؟", correctAnswer: "المصباح الكهربائي", distractors: ["الهاتف", "السيارة", "الساعة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "بأي اختراع نستطيع أن نتكلّم مع شخص بعيد؟", correctAnswer: "الهاتف", distractors: ["المصباح", "الدرّاجة", "المقصّ"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أي وسيلة نقل تطير في الهواء؟", correctAnswer: "الطائرة", distractors: ["السفينة", "القطار", "السيارة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أي وسيلة نقل تسير على الماء؟", correctAnswer: "السفينة", distractors: ["الطائرة", "السيارة", "الدرّاجة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "كم عجلة للدرّاجة الهوائية العادية؟", correctAnswer: "عجلتان", distractors: ["عجلة واحدة", "ثلاث عجلات", "أربع عجلات"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "بماذا كان الناس يتنقّلون قبل اختراع السيارات والقطارات؟", correctAnswer: "على ظهور الخيل", distractors: ["بالطائرة", "بالحافلة", "بالدرّاجة النارية"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "في أي عيد يهودي يُنفخ في الشوفار؟", correctAnswer: "رأس السنة العبرية", distractors: ["بوريم", "حانوكا", "بيساح"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "بأي طعام حلو يُغمس التفاح في رأس السنة العبرية؟", correctAnswer: "العسل", distractors: ["الملح", "الزبدة", "الزيت"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ماذا يُضيء اليهود في عيد حانوكا؟", correctAnswer: "الشموع", distractors: ["البالونات", "الأزهار", "الحجارة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أي لعبة يديرها الأطفال في عيد حانوكا؟", correctAnswer: "السفيفون", distractors: ["الكرة", "الدمية", "الطائرة الورقية"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أي وسيلة نقل تسير على سكة حديدية؟", correctAnswer: "القطار", distractors: ["الطائرة", "السفينة", "الدرّاجة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا رسم الناس على جدران الكهوف قبل آلاف السنين؟", correctAnswer: "رسومًا لحيوانات", distractors: ["أرقامًا", "خرائط حاسوب", "صورًا من الهاتف"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أي أداة تساعدنا على معرفة الوقت؟", correctAnswer: "الساعة", distractors: ["آلة التصوير", "المضخّة", "المكنسة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا يُسمّى الكوخ المؤقّت الذي يبنيه اليهود ويجلسون فيه سبعة أيام في الخريف؟", correctAnswer: "السُّكّة (العريشة)", distractors: ["الخيمة", "البرج", "المغارة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "في أيّ عيد يهوديّ تُقام ليلة السيدر ويُقرأ فيها كتاب الهاغادا؟", correctAnswer: "عيد الفصح", distractors: ["عيد بوريم", "عيد حانوكا", "عيد المظالّ"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "بماذا كان الناس يكتبون قبل أن يوجد الحاسوب؟", correctAnswer: "القلم والورق", distractors: ["الطائرة", "السيّارة", "التلفاز"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ حيوان كان يحمل الأحمال في الصحراء قبل سنوات طويلة؟", correctAnswer: "الجمل", distractors: ["السمكة", "العصفور", "الأرنب"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ اختراع يساعدنا على مشاهدة الأفلام والبرامج في البيت؟", correctAnswer: "التلفاز", distractors: ["السيّارة", "الدرّاجة الهوائيّة", "الطاولة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما اسم الضوء الكبير الذي يُنير لنا في النهار؟", correctAnswer: "الشمس", distractors: ["المصباح", "نار المخيّم", "الكشّاف اليدويّ"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ وسيلة نقل كبيرة تنقل كثيرًا من الناس داخل المدينة؟", correctAnswer: "الحافلة", distractors: ["الدرّاجة الهوائيّة", "الحصان", "السكوتر"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ عيد يهوديّ يُحتفل به في الربيع ويُنظَّف البيت فيه تنظيفًا كبيرًا؟", correctAnswer: "عيد الفصح", distractors: ["عيد حانوكا", "عيد بوريم", "رأس السنة العبريّة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما اسم الدولة التي تقع فيها مدن القدس وحيفا وبئر السبع؟", correctAnswer: "إسرائيل", distractors: ["مصر", "اليونان", "إيطاليا"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ماذا كان الناس يشعلون للإنارة قبل وجود الكهرباء؟", correctAnswer: "الشمعة", distractors: ["الهاتف", "الحاسوب", "التلفاز"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ طعام مميّز يُؤكل في عيد الأسابيع اليهوديّ (شفوعوت)؟", correctAnswer: "مأكولات الألبان", distractors: ["خبز الفطير (متسا)", "أذان هامان", "السفغانيّات"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أيّ حلوى مقليّة وحلوة المذاق تُؤكل في عيد حانوكا؟", correctAnswer: "السفغانيّة (دونات)", distractors: ["خبز الفطير (متسا)", "أذان هامان", "التفّاح بالعسل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ماذا نسمّي الشخص الذي يسافر إلى الفضاء في مركبة فضائيّة؟", correctAnswer: "رائد فضاء", distractors: ["سائق", "طبّاخ", "طبيب"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ جهاز يساعدنا على سماع الموسيقى؟", correctAnswer: "المذياع", distractors: ["السيّارة", "الكرسيّ", "المنظار"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نلبس في أقدامنا، قديمًا واليوم؟", correctAnswer: "الحذاء", distractors: ["القفّازات", "القبّعة", "النظّارات"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ وسيلة نقل تسير على أربع عجلات في الشارع؟", correctAnswer: "السيّارة", distractors: ["الطائرة", "السفينة", "القطار"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا يشرب الناس كي لا يعطشوا، قديمًا واليوم؟", correctAnswer: "الماء", distractors: ["الوقود", "الدهان", "الرمل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "في أيّ يوم يهوديّ مقدّس يصوم البالغون بعد رأس السنة العبريّة؟", correctAnswer: "يوم الغفران", distractors: ["عيد بوريم", "عيد حانوكا", "عيد الفصح"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أيّ جهاز يساعدنا على التقاط الصور؟", correctAnswer: "الكاميرا", distractors: ["الساعة", "الملعقة", "المشط"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا بنى الناس للعبور من ضفّة النهر إلى الضفّة الأخرى؟", correctAnswer: "الجسر", distractors: ["البرج", "السلّم", "الخزانة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ طعام مميّز يُؤكل في «تو بشفاط»، المناسبة اليهوديّة التي تُغرس فيها الشتلات؟", correctAnswer: "الفواكه المجفّفة", distractors: ["خبز الفطير (متسا)", "السفغانيّات", "أذان هامان"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما اسم الكتاب الذي يُقرأ في ليلة السيدر في عيد الفصح اليهوديّ؟", correctAnswer: "الهاغادا", distractors: ["القاموس", "الأطلس", "الدفتر"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أيّ وسيلة نقل تغوص تحت الماء؟", correctAnswer: "الغوّاصة", distractors: ["الطائرة", "القطار", "الحافلة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ جهاز صغير نحمله في اليد لكتابة الرسائل وللّعب؟", correctAnswer: "الهاتف المحمول", distractors: ["المكنسة", "الكرة", "المقلاة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما هي عاصمة دولة إسرائيل؟", correctAnswer: "القدس", distractors: ["باريس", "لندن", "روما"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ وسيلة استعملها الناس قديمًا لإرسال الرسائل إلى أماكن بعيدة قبل اختراع الهاتف؟", correctAnswer: "الحمام الزاجل", distractors: ["الحاسوب", "التلفاز", "المذياع"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أيّ جهاز يساعدنا على رؤية أشياء بعيدة جدًّا مثل النجوم؟", correctAnswer: "التلسكوب (المِقراب)", distractors: ["النظّارات الشمسيّة", "المشط", "الملعقة الصغيرة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ شعب قديم بنى مدرّج الكولوسيوم الكبير في مدينة روما؟", correctAnswer: "الرومان", distractors: ["المصريّون القدماء", "الصينيّون", "اليابانيّون"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "كيف وصل كريستوفر كولومبوس إلى قارّة أمريكا؟", correctAnswer: "بالإبحار في البحر", distractors: ["بالطيران في طائرة", "بالسفر في قطار", "بتسلّق جبل"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيّ اختراع أتاح طباعة كثير من الكتب بسرعة بدل نسخ كلّ كتاب باليد؟", correctAnswer: "المطبعة", distractors: ["الحاسوب", "الهاتف", "المذياع"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "في أيّ بلد قديم أُقيمت أوّل الألعاب الأولمبيّة؟", correctAnswer: "اليونان", distractors: ["مصر", "الصين", "إنجلترا"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيّ نهر كبير كان يجري في مصر القديمة وساعد الناس على زراعة طعامهم؟", correctAnswer: "النيل", distractors: ["الأردنّ", "الأمازون", "التايمز"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيّ مادّة مصنوعة من نبات استعملها المصريّون القدماء للكتابة؟", correctAnswer: "ورق البَرْديّ", distractors: ["البلاستيك", "الزجاج", "الحديد"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "ماذا كان لقب الملك الذي حكم في مصر القديمة؟", correctAnswer: "فرعون", distractors: ["قيصر", "شوغون", "مهراجا"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيّ اختراع قديم جدًّا يتدحرج وساعد الناس على نقل الأشياء الثقيلة؟", correctAnswer: "العجلة", distractors: ["الحاسوب", "الهاتف", "الكاميرا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ مخترع اشتهر بتطوير مصباح كهربائيّ ناجح للبيوت؟", correctAnswer: "توماس إديسون", distractors: ["ألبرت أينشتاين", "كريستوفر كولومبوس", "ليوناردو دافينشي"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ أخوين اخترعا أوّل طائرة طارت في الهواء؟", correctAnswer: "الأخوان رايت", distractors: ["الأخوان غريم", "الأخوان لوميير", "الأخوان ماركس"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ اختراع يساعدنا على حفظ الطعام باردًا وطازجًا في المطبخ؟", correctAnswer: "الثلّاجة", distractors: ["الفرن", "الحاسوب", "المروحة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ عيد يهوديّ يُحيي ذكرى خروج بني إسرائيل من مصر إلى الحرّيّة؟", correctAnswer: "عيد الفصح", distractors: ["عيد حانوكا", "عيد بوريم", "عيد الأسابيع"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ عيد يهوديّ يُحيي ذكرى تلقّي التوراة؟", correctAnswer: "عيد الأسابيع (شفوعوت)", distractors: ["عيد بوريم", "عيد حانوكا", "عيد المظالّ"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ أداة قديمة ساعدت الناس على معرفة الاتّجاه في البحر بإبرة تشير إلى الشمال؟", correctAnswer: "البوصلة", distractors: ["الساعة", "المنظار", "الهاتف"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ بناء مشهور أقامه المصريّون القدماء ليكون مقبرة لملوكهم؟", correctAnswer: "الهرم", distractors: ["برج الجرس", "القلعة", "الجسر"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيّ وسيلة نقل بدأت تسير بالبخار والفحم قبل سنوات طويلة؟", correctAnswer: "قطار البخار", distractors: ["الطائرة النفّاثة", "المركبة الفضائيّة", "الدرّاجة الناريّة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ برج حديديّ عالٍ ومشهور يقف في مدينة باريس؟", correctAnswer: "برج إيفل", distractors: ["الهرم الأكبر", "برج بيزا المائل", "سور الصين العظيم"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيّ سور طويل جدًّا بُني في الصين قبل سنوات طويلة؟", correctAnswer: "سور الصين العظيم", distractors: ["جدار برلين", "برج إيفل", "الكولوسيوم"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيّ وسيلة نقل تصعد وتهبط عموديًّا وفوقها ريش دوّار كبير؟", correctAnswer: "المروحيّة", distractors: ["السفينة", "القطار", "الدرّاجة الهوائيّة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ مادّة جديدة وخفيفة اختُرعت، وتُصنع منها اليوم زجاجات وألعاب كثيرة؟", correctAnswer: "البلاستيك", distractors: ["الورق", "الذهب", "الحجر"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما الاسم الآخر لـ«تو بشفاط»، المناسبة اليهوديّة التي تُغرس فيها الشتلات؟", correctAnswer: "رأس السنة للأشجار", distractors: ["عيد الباكورات", "عيد الفطير", "عيد الأنوار"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما اسم الكتاب المقدّس المهمّ عند اليهود الذي يُقرأ في الكنيس؟", correctAnswer: "التوراة", distractors: ["الأطلس", "القاموس", "الصحيفة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ عالِم طبيعة مشهور اكتشف أمورًا كثيرة عن قوّة الجاذبيّة؟", correctAnswer: "إسحاق نيوتن", distractors: ["كريستوفر كولومبوس", "توماس إديسون", "هنري فورد"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيّ أداة قديمة قاست الزمن برمل ينساب من وعاء إلى آخر؟", correctAnswer: "الساعة الرمليّة", distractors: ["الحاسوب", "الهاتف", "الكاميرا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "في أيّ آلة نفخ قديمة يُنفخ في رأس السنة العبريّة؟", correctAnswer: "البوق (الشوفار)", distractors: ["الناي", "الطبل", "الكمان"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ اختراع يتيح تسخين الطعام في ثوانٍ معدودة؟", correctAnswer: "فرن الميكروويف", distractors: ["الثلّاجة", "الكاميرا", "المذياع"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ أداة قديمة ساعدت على العدّ والحساب بخرزات تنزلق على أسلاك؟", correctAnswer: "المِعداد", distractors: ["الحاسوب", "الهاتف", "الساعة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما اسم مجلس النوّاب (البرلمان) في إسرائيل؟", correctAnswer: "الكنيست", distractors: ["الكونغرس", "مجلس الشيوخ", "المحكمة العليا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ نبات مهمّ زرعه الناس قبل سنوات طويلة ليصنعوا منه الطحين والخبز؟", correctAnswer: "القمح", distractors: ["الوردة", "الصبّار", "الطحلب"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ وسيلة نقل كبيرة وثقيلة تحمل بضائع كثيرة على الطرق؟", correctAnswer: "الشاحنة", distractors: ["الدرّاجة الهوائيّة", "السكوتر", "الطائرة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "في أيّ عيد يهوديّ يتبادل الناس أطباق الحلوى ويقدّمون العطايا للفقراء؟", correctAnswer: "عيد بوريم", distractors: ["عيد حانوكا", "عيد الفصح", "عيد المظالّ"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "أيّ عالِم مشهور بحث في الزمن والفضاء؟", correctAnswer: "ألبرت أينشتاين", distractors: ["توماس إديسون", "كريستوفر كولومبوس", "يوليوس قيصر"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "من أوّل إنسان مشى على سطح القمر؟", correctAnswer: "نيل أرمسترونغ", distractors: ["توماس إديسون", "كريستوفر كولومبوس", "ألبرت أينشتاين"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيّ لون غالي الثمن كان مخصّصًا لثياب الملوك في العصور القديمة؟", correctAnswer: "الأرجوانيّ", distractors: ["الرماديّ", "البنّيّ", "الشفّاف"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "أيّ وسيلة نقل سريعة تطير عاليًا وتنقل المسافرين بين الدول؟", correctAnswer: "طائرة الركّاب", distractors: ["قارب الشراع", "عربة الخيل", "السكوتر"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ أداة قديمة ساعدت الفلّاحين على حفر الأرض وقلبها قبل البذار؟", correctAnswer: "المحراث", distractors: ["الكاميرا", "التلسكوب", "الساعة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ مدينة قديمة مشهورة في اليونان كانت مركزًا للعلم والحكمة؟", correctAnswer: "أثينا", distractors: ["القاهرة", "طوكيو", "موسكو"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "من القائد الذي أخرج بني إسرائيل من مصر بحسب قصّة عيد الفصح؟", correctAnswer: "النبيّ موسى", distractors: ["الملك داود", "الملك سليمان", "النبيّ إبراهيم"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "أيّ كتابة قديمة مكوّنة من رسوم ورموز استعملها المصريّون القدماء؟", correctAnswer: "الكتابة الهيروغليفيّة", distractors: ["كتابة الحاسوب", "الكتابة الموسيقيّة", "كتابة الأرقام فقط"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ فنّان ومخترع من إيطاليا رسم الموناليزا وصمّم اختراعات كثيرة؟", correctAnswer: "ليوناردو دافينشي", distractors: ["توماس إديسون", "إسحاق نيوتن", "كريستوفر كولومبوس"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ مخترع اشتهر باختراع أوّل هاتف؟", correctAnswer: "ألكسندر غراهام بيل", distractors: ["توماس إديسون", "هنري فورد", "إسحاق نيوتن"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ شعب قديم طوّر الديمقراطيّة، وهي نظام يصوّت فيه الناس ويقرّرون معًا؟", correctAnswer: "الإغريق", distractors: ["المصريّون القدماء", "الصينيّون", "الفايكنغ"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ شعب بحّار مشهور من شمال أوروبّا أبحر في قوارب طويلة واستكشف بلادًا بعيدة؟", correctAnswer: "الفايكنغ", distractors: ["المصريّون القدماء", "اليابانيّون", "الرومان"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ عالِمة مشهورة بحثت في الإشعاع وفازت بجائزة نوبل مرّتين؟", correctAnswer: "ماري كوري", distractors: ["ماري أنطوانيت", "فلورنس نايتنغيل", "أنّا فرانك"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ بلد قديم اخترع الورق والحرير؟", correctAnswer: "الصين", distractors: ["مصر", "اليونان", "فرنسا"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ عيد يهوديّ يُحيي ذكرى جرّة الزيت الصغيرة التي أضاءت ثمانية أيّام في الهيكل؟", correctAnswer: "عيد حانوكا", distractors: ["عيد بوريم", "عيد الفصح", "عيد الأسابيع"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "أيّ ملكة شجاعة في قصّة عيد بوريم ساعدت على إنقاذ اليهود؟", correctAnswer: "الملكة إستير", distractors: ["النبيّة مريم", "القاضية دبورة", "راعوث المؤابيّة"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "أيّ ملك مشهور بنى الهيكل الأوّل في القدس؟", correctAnswer: "الملك سليمان", distractors: ["النبيّ موسى", "النبيّ إبراهيم", "النبيّ يعقوب"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "أيّ جهاز علميّ يساعد على رؤية أشياء دقيقة جدًّا مثل الخلايا والجراثيم؟", correctAnswer: "المجهر", distractors: ["التلسكوب", "البوصلة", "الساعة الرمليّة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ مستكشف قاد أوّل رحلة بحريّة دارت حول الكرة الأرضيّة؟", correctAnswer: "فرديناند ماجلان", distractors: ["توماس إديسون", "إسحاق نيوتن", "هنري فورد"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ حجر قديم ساعد الباحثين على فكّ رموز الكتابة المصريّة القديمة؟", correctAnswer: "حجر رشيد", distractors: ["لوحا الوصايا", "حجر الفلاسفة", "جدول الضرب"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ عالِم مشهور استعمل التلسكوب لدراسة النجوم والقمر؟", correctAnswer: "غاليليو", distractors: ["كولومبوس", "إديسون", "فورد"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ مركبة سريعة تخرج من جاذبيّة الأرض بمحرّك قويّ جدًّا؟", correctAnswer: "صاروخ الفضاء", distractors: ["السفينة", "الدرّاجة الهوائيّة", "عربة الخيل"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ شعب قديم بنى طرقًا طويلة وقنوات مائيّة لنقل الماء إلى مدنه؟", correctAnswer: "الرومان", distractors: ["الفايكنغ", "اليابانيّون", "الإسكيمو"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ اختراع للأخوين لوميير أتاح عرض صور متحرّكة على شاشة كبيرة؟", correctAnswer: "السينما", distractors: ["المذياع", "الهاتف", "الثلّاجة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ عيد يهوديّ يُحيي ذكرى تلقّي التوراة في جبل سيناء، ويُزيَّن البيت فيه بالخضرة والزهور؟", correctAnswer: "عيد الأسابيع (شفوعوت)", distractors: ["عيد المظالّ", "عيد بوريم", "عيد حانوكا"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "أيّ مستكشف إنجليزيّ مشهور أبحر واستكشف بلادًا كثيرة في المحيط الهادئ؟", correctAnswer: "جيمس كوك", distractors: ["توماس إديسون", "هنري فورد", "ألبرت أينشتاين"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ أداة قديمة قاست الزمن بظلّ عصًا يتحرّك مع حركة الشمس؟", correctAnswer: "المِزوَلة (الساعة الشمسيّة)", distractors: ["ساعة اليد", "الحاسوب", "الكاميرا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ لغة قديمة تكلّم بها أهل روما القديمة وتُعدّ أمًّا للغات كثيرة في أوروبّا؟", correctAnswer: "اللاتينيّة", distractors: ["الصينيّة", "اليابانيّة", "العربيّة"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ اختراع أتاح إرسال الرسائل إلى مسافات بعيدة بشيفرة من نقاط وخطوط؟", correctAnswer: "التلغراف", distractors: ["الثلّاجة", "الكاميرا", "المحراث"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "من الرجل الذي أعاد إحياء اللغة العبريّة لتصبح لغة محكيّة من جديد؟", correctAnswer: "إليعيزر بن يهودا", distractors: ["تيودور هرتسل", "ألبرت أينشتاين", "توماس إديسون"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "أيّ معدن قويّ بدأ الإنسان يصهره ويشكّله أدوات عمل، وسُمّي به عصر كامل؟", correctAnswer: "الحديد", distractors: ["البلاستيك", "الزجاج", "المطّاط"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ شعب قديم نحت مدينة البتراء في الصخر الورديّ؟", correctAnswer: "الأنباط", distractors: ["الرومان", "الفايكنغ", "اليابانيّون"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "أيّ نجم ساعد البحّارة على معرفة طريقهم ليلًا لأنّه يشير إلى الشمال؟", correctAnswer: "النجم القطبيّ", distractors: ["القمر البدر", "الشمس", "السحابة"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ بلد قديم كان مقسّمًا إلى دول-مدن مثل أثينا وإسبرطة؟", correctAnswer: "اليونان", distractors: ["مصر", "الصين", "إنجلترا"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "من بنى أسوار البلدة القديمة في القدس التي نراها اليوم؟", correctAnswer: "العثمانيّون في عهد السلطان سليمان القانونيّ", distractors: ["الفايكنغ", "الإغريق القدماء", "المصريّون القدماء"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "أيّ وسيلة نقل قديمة سارت على اليابسة حين جرّت الخيول عربة ذات عجلات؟", correctAnswer: "عربة الخيل", distractors: ["الغوّاصة", "الطائرة", "المركبة الفضائيّة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ اختراع ليوهان غوتنبرغ أتاح طباعة الكتب بسرعة؟", correctAnswer: "المطبعة", distractors: ["الكاميرا", "الهاتف", "السيّارة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "في أيّ مناسبة يهوديّة تُشعل النيران في الليل في أنحاء البلاد؟", correctAnswer: "لاغ بعومير", distractors: ["عيد بوريم", "عيد الفصح", "عيد الأسابيع"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "أيّ شعب قديم في أمريكا الجنوبيّة بنى مدنًا في الجبال العالية؟", correctAnswer: "الإنكا", distractors: ["الرومان", "الفايكنغ", "اليابانيّون"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "أيّ مادّة شفّافة اختُرعت قبل سنوات طويلة وتُصنع منها النوافذ وأدوات الشرب؟", correctAnswer: "الزجاج", distractors: ["الحديد", "الخشب", "الحجر"], tier: .hard, grades: 4...6),
    ]
}
