import Foundation

/// 🧍 جسم الإنسان — بالعربية. مأخوذ عن البنك العبريّ (70 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let body: [BankQuestion] = [
        BankQuestion(prompt: "❤️\nأيّ عضو يضخّ الدم في الجسم؟", correctAnswer: "القلب", distractors: ["الرئتان", "الدماغ", "المعدة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🫁\nبأيّ أعضاء نتنفّس؟", correctAnswer: "الرئتان", distractors: ["القلب", "المعدة", "الجلد"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧠\nأيّ عضو يساعدنا على التفكير والتذكّر؟", correctAnswer: "الدماغ", distractors: ["القلب", "الرئتان", "الكبد"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "👀\nبأيّ عضو نرى؟", correctAnswer: "العينان", distractors: ["الأذنان", "الأنف", "الفم"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "👂\nبأيّ عضو نسمع؟", correctAnswer: "الأذنان", distractors: ["العينان", "الأنف", "اليدان"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "👃\nبأيّ عضو نشمّ؟", correctAnswer: "الأنف", distractors: ["الفم", "الأذنان", "العينان"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "👅\nبأيّ عضو نتذوّق؟", correctAnswer: "اللسان", distractors: ["الأنف", "الأسنان", "الأذنان"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🤲\nبأيّ حاسّة نشعر أنّ شيئًا ساخن أو بارد؟", correctAnswer: "حاسّة اللمس", distractors: ["حاسّة البصر", "حاسّة السمع", "حاسّة الشمّ"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🖐️\nكم عدد الحواسّ الأساسيّة التي نتعلّم عنها عادةً؟", correctAnswer: "5", distractors: ["3", "4", "6"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "✋\nكم إصبعًا في اليدين معًا؟", correctAnswer: "10", distractors: ["5", "8", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦶\nكم إصبعًا في قدم واحدة؟", correctAnswer: "5", distractors: ["4", "6", "10"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦷\nما الذي يساعدنا على مضغ الطعام؟", correctAnswer: "الأسنان", distractors: ["الأنف", "الأذنان", "العينان"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "👄\nعبر أيّ عضو يدخل الطعام إلى الجسم؟", correctAnswer: "الفم", distractors: ["الأنف", "الأذن", "العين"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍎\nإلى أين يصل الطعام بعد أن نبتلعه؟", correctAnswer: "إلى المعدة", distractors: ["إلى الرئتين", "إلى القلب", "إلى الدماغ"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "💪\nما الذي يحرّك عظامنا؟", correctAnswer: "العضلات", distractors: ["الشعر", "الجلد", "الأظافر"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦴\nماذا نسمّي كلّ عظام الجسم معًا؟", correctAnswer: "الهيكل العظميّ", distractors: ["العضلة", "الجلد", "القلب"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧍\nأيّ عضو يغطّي الجسم كلّه من الخارج؟", correctAnswer: "الجلد", distractors: ["الهيكل العظميّ", "القلب", "الدماغ"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🫀\nأين يقع القلب؟", correctAnswer: "في الصدر", distractors: ["في الرأس", "في الرِّجل", "في اليد"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧠\nأين يقع الدماغ؟", correctAnswer: "في الرأس", distractors: ["في البطن", "في اليد", "في الرِّجل"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦴\nأيّ عظمة تحمي الدماغ؟", correctAnswer: "الجمجمة", distractors: ["الضِّلع", "عظم الفخذ", "عظم العَضُد"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🩸\nما الذي يجري في الجسم ويحمل الأكسجين إلى كلّ مكان؟", correctAnswer: "الدم", distractors: ["الماء", "الهواء", "الحليب"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🪥\nكم مرّة يُستحسن أن ننظّف أسناننا؟", correctAnswer: "مرّتان في اليوم", distractors: ["مرّة في الأسبوع", "مرّة في الشهر", "مرّة في السنة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦷\nماذا نفعل بفرشاة الأسنان والمعجون؟", correctAnswer: "نُنظّف أسناننا", distractors: ["نُسرّح شعرنا", "نغسل أيدينا", "ننظّف أحذيتنا"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧼\nماذا يُستحسن أن نفعل قبل الأكل؟", correctAnswer: "نغسل أيدينا", distractors: ["نركض", "ننام", "نغنّي"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "☀️\nماذا ندهن على الجلد لحمايته من الشمس؟", correctAnswer: "كريم واقٍ من الشمس", distractors: ["الماء", "زيت الزيتون", "الغِراء"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🛌\nماذا يفعل الجسم في الليل كي يرتاح ويتجدّد؟", correctAnswer: "ينام", distractors: ["يركض", "يأكل", "يقفز"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "💧\nماذا يُستحسن أن نشرب كثيرًا كي يبقى الجسم سليمًا؟", correctAnswer: "الماء", distractors: ["الزيت", "العصير المُحلّى", "القهوة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏃\nما الذي يساعد العضلات على أن تكون قويّة؟", correctAnswer: "الرياضة", distractors: ["الحلويّات", "التلفاز", "ألعاب الحاسوب"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦴\nكم عظمة في جسم الإنسان البالغ؟", correctAnswer: "206", distractors: ["106", "306", "520"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦴\nما أطول عظمة في الجسم؟", correctAnswer: "عظم الفخذ", distractors: ["عظم العَضُد", "الضِّلع", "الجمجمة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦴\nكم ضِلعًا لدى الإنسان؟", correctAnswer: "24", distractors: ["12", "20", "30"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦴\nأيّ جزء من الهيكل العظميّ يحمي القلب والرئتين؟", correctAnswer: "الأضلاع", distractors: ["الجمجمة", "عظم الفخذ", "الأصابع"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦴\nماذا نسمّي الموضع الذي تلتقي فيه عظمتان ويسمح بالحركة؟", correctAnswer: "مِفصل", distractors: ["عضلة", "وتر", "جلد"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦵\nالرُّكبة مثال على…", correctAnswer: "مِفصل", distractors: ["عضلة", "عضو داخليّ", "عظمة واحدة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦷\nكم سِنًّا لبنيًّا لدى الطفل؟", correctAnswer: "20", distractors: ["10", "24", "32"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦷\nكم سِنًّا لدى الإنسان البالغ، مع أضراس العقل؟", correctAnswer: "32", distractors: ["20", "28", "36"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦷\nماذا نسمّي الأسنان الأولى التي تسقط وتحلّ محلّها أسنان دائمة؟", correctAnswer: "الأسنان اللبنيّة", distractors: ["أضراس العقل", "أسنان ذهبيّة", "أسنان حديديّة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🫀\nالقلب في الحقيقة هو…", correctAnswer: "عضلة", distractors: ["عظمة", "مِفصل", "غُدّة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "❤️\nماذا يضخّ القلب إلى جميع أنحاء الجسم عبر الأوعية؟", correctAnswer: "الدم", distractors: ["الهواء", "الماء", "الطعام"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🩸\nماذا يحمل الدم إلى جميع خلايا الجسم؟", correctAnswer: "الأكسجين والموادّ الغذائيّة", distractors: ["الضوء", "الصوت", "الرمل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🩸\nما الصحيح بشأن دم البشر؟", correctAnswer: "هناك فصائل دم مختلفة", distractors: ["لجميع الناس الفصيلة نفسها", "الدم مكوَّن من الماء فقط", "لون الدم أخضر داخل الجسم"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🩸\nأيّ من هذه الأسماء اسم فصيلة دم؟", correctAnswer: "الفصيلة O", distractors: ["الفصيلة X", "الفصيلة Z", "الفصيلة Q"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🫁\nكم رئة لدى الإنسان؟", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🫁\nأيّ غاز نستنشقه من الهواء ويحتاج إليه الجسم؟", correctAnswer: "الأكسجين", distractors: ["ثاني أكسيد الكربون", "الهيليوم", "الهيدروجين"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌬️\nأيّ غاز يضيفه الجسم إلى الهواء الذي نزفره؟", correctAnswer: "ثاني أكسيد الكربون", distractors: ["الأكسجين", "الهيليوم", "الهيدروجين"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌡️\nكم تبلغ حرارة جسم الإنسان الطبيعيّة تقريبًا؟", correctAnswer: "37 درجة", distractors: ["20 درجة", "50 درجة", "100 درجة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧠\nعبر ماذا يرسل الدماغ الرسائل إلى الجسم كلّه؟", correctAnswer: "الأعصاب", distractors: ["الأوعية الدمويّة", "الشعر", "العظام"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧍\nما أكبر عضو في الجسم؟", correctAnswer: "الجلد", distractors: ["القلب", "الدماغ", "الكبد"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "💪\nكم عضلة في جسم الإنسان تقريبًا؟", correctAnswer: "نحو 600", distractors: ["نحو 6", "نحو 60", "نحو 60,000"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👂\nغير السمع، فيمَ تساعد الأذن الداخليّة؟", correctAnswer: "في حفظ التوازن", distractors: ["في الرؤية في الظلام", "في تذوّق الطعام", "في هضم الطعام"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👅\nأيّ طعم يشعر به اللسان عند أكل الليمون؟", correctAnswer: "حامض", distractors: ["حلو", "مالح", "مُرّ"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍽️\nماذا يحدث للطعام في المعدة؟", correctAnswer: "يتفكّك إلى أجزاء صغيرة", distractors: ["يتحوّل إلى عظم", "يبقى كما هو تمامًا", "يصعد إلى الرئتين"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍽️\nماذا نسمّي العمليّة التي يفكّك بها الجسم الطعام؟", correctAnswer: "الهضم", distractors: ["التنفّس", "النوم", "النموّ"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛌\nلماذا من المهمّ أن ننام كفايةً؟", correctAnswer: "كي يرتاح الجسم والدماغ ويتجدّدا", distractors: ["كي تنمو الأسنان في الليل فقط", "كي يقصر الشعر", "كي تغيّر العينان لونهما"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "😴\nكم ساعة نوم يحتاج طفل في سنّ المدرسة كلّ ليلة تقريبًا؟", correctAnswer: "نحو 10 ساعات", distractors: ["نحو ساعتين", "نحو 5 ساعات", "نحو 16 ساعة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧼\nلماذا نغسل أيدينا بالصابون؟", correctAnswer: "كي نُبعد الجراثيم", distractors: ["كي تكبر أيدينا", "كي تدفأ أيدينا", "كي يتغيّر لون الجلد"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👂\nأين توجد أصغر عظمة في الجسم؟", correctAnswer: "في الأذن", distractors: ["في الإصبع", "في الأنف", "في الرُّكبة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦴\nماذا يُصنع داخل نُخاع العظم؟", correctAnswer: "خلايا الدم", distractors: ["الأسنان", "الشعر", "الأظافر"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🫀\nكم تجويفًا (بُطينًا وأُذَينًا) في القلب؟", correctAnswer: "4", distractors: ["1", "2", "6"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🩸\nماذا نسمّي الأوعية التي تنقل الدم من القلب إلى الجسم؟", correctAnswer: "الشرايين", distractors: ["الأوردة", "الأعصاب", "الأوتار"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🩸\nما وظيفة خلايا الدم الحمراء؟", correctAnswer: "حمل الأكسجين", distractors: ["هضم الطعام", "بناء العظام", "إنتاج الشعر"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💓\nماذا نقيس عندما نضع إصبعًا على المِعصم ونَعُدّ الضربات؟", correctAnswer: "النبض", distractors: ["الحرارة", "الطول", "الوزن"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🫁\nماذا نسمّي العضلة الكبيرة تحت الرئتين التي تساعدنا على التنفّس؟", correctAnswer: "الحجاب الحاجز", distractors: ["عضلة العَضُد", "عضلة القلب", "عضلة الفخذ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦷\nما أقسى مادّة في جسم الإنسان؟", correctAnswer: "مينا الأسنان", distractors: ["العظم", "الظُّفر", "الشعر"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧠\nأيّ جزء من الدماغ مسؤول أساسًا عن التوازن وتنسيق الحركات؟", correctAnswer: "المُخَيخ", distractors: ["المُخّ", "جذع الدماغ", "النخاع الشوكيّ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦴\nماذا يحمي العمود الفقريّ؟", correctAnswer: "النخاع الشوكيّ", distractors: ["المعدة", "العينان", "الأسنان"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🫘\nأيّ عضو يُصفّي الدم ويُخرج منه الماء الزائد؟", correctAnswer: "الكليتان", distractors: ["الرئتان", "القلب", "الدماغ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍽️\nفي أيّ عضو تُمتصّ معظم الموادّ الغذائيّة إلى الدم؟", correctAnswer: "الأمعاء الدقيقة", distractors: ["المعدة", "الفم", "الرئتان"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "👁️\nماذا نسمّي النقطة السوداء في وسط العين التي يدخل منها الضوء؟", correctAnswer: "البُؤْبُؤ", distractors: ["القزحيّة", "الرِّمش", "الحاجب"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧍\nما أكبر عضو داخليّ في الجسم؟", correctAnswer: "الكبد", distractors: ["القلب", "الدماغ", "الكلية"], tier: .hard, grades: 4...6),
    ]
}
