import Foundation

/// 🌊 البحر — بالعربية. مأخوذ عن البنك العبريّ (70 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let sea: [BankQuestion] = [
        BankQuestion(prompt: "🦈\nمَن مِن هؤلاء يعيش في البحر؟", correctAnswer: "قِرش", distractors: ["بقرة", "حصان", "ديك"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐬\nأيّ حيوان بحريّ معروف بذكائه ولطفه، ويحبّ القفز خارج الماء؟", correctAnswer: "الدلفين", distractors: ["التمساح", "السلحفاة", "الأرنب"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐙\nكم ذراعًا للأخطبوط؟", correctAnswer: "8", distractors: ["4", "6", "10"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐙\nماذا نسمّي الحيوان الرخو الذي له 8 أذرع؟", correctAnswer: "الأخطبوط", distractors: ["القِرش", "السلحفاة", "السرطان"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐙\nكم قلبًا للأخطبوط؟", correctAnswer: "3", distractors: ["1", "2", "5"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐢\nماذا يوجد على ظهر سلحفاة البحر؟", correctAnswer: "دِرع صلب", distractors: ["جناحان", "فَرْو", "قرنان"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐢\nأين تضع سلحفاة البحر بيضها؟", correctAnswer: "في الرمل على الشاطئ", distractors: ["في أعماق البحر", "على شجرة", "في الثلج"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐋\nما أكبر حيوان في العالم؟", correctAnswer: "الحوت الأزرق", distractors: ["الفيل", "القِرش", "الزرافة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐬\nماذا يفعل الدلفين حين يصعد إلى سطح الماء؟", correctAnswer: "يتنفّس الهواء", distractors: ["ينام", "يأكل الرمل", "يجفّ"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐟\nبماذا تتنفّس السمكة تحت الماء؟", correctAnswer: "بالخياشيم", distractors: ["بالرئتين", "بالأنف", "بالفم"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐠\nما الذي يساعد السمكة على السباحة؟", correctAnswer: "الزعانف", distractors: ["الأرجل", "الأجنحة", "اليدان"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐟\nبماذا يُغطّى جسم معظم الأسماك؟", correctAnswer: "بالحراشف", distractors: ["بالفَرْو", "بالريش", "بالشعر"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐟\nأين تعيش الأسماك؟", correctAnswer: "في الماء", distractors: ["في الهواء", "على الأشجار", "في الصحراء"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🦈\nما الذي يملك القِرش منه عددًا كبيرًا جدًّا، ويتبدّل عنده باستمرار؟", correctAnswer: "الأسنان", distractors: ["العيون", "الآذان", "الأرجل"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪼\nأيّ كائن بحريّ رخو وشفّاف، له لوامس طويلة، ويصل إلى شواطئ إسرائيل في الصيف؟", correctAnswer: "قنديل البحر", distractors: ["السلحفاة", "الدلفين", "السرطان"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦀\nأيّ حيوان يمشي جانبيًّا على الشاطئ وله كمّاشتان؟", correctAnswer: "السرطان", distractors: ["السمكة", "قنديل البحر", "السلحفاة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "⭐\nأيّ كائن بحريّ يشبه النجمة وله 5 أذرع؟", correctAnswer: "نجم البحر", distractors: ["فرس البحر", "سمك أبو سيف", "قنديل البحر"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐴\nأيّ سمكة صغيرة تشبه الحصان وتسبح منتصبة؟", correctAnswer: "فرس البحر", distractors: ["نجم البحر", "القِرش", "ثعبان البحر"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦭\nأيّ حيوان يسبح في البحر ويستريح على الصخور، وله شارب؟", correctAnswer: "الفُقمة", distractors: ["القِرش", "السمكة الذهبية", "قنديل البحر"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐚\nماذا يمكن أن نجد على شاطئ البحر؟", correctAnswer: "أصداف", distractors: ["أكواز صنوبر", "فطريات", "ثلج"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🧂\nما طعم ماء البحر؟", correctAnswer: "مالح", distractors: ["حلو", "حامض", "بلا طعم"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌍\nمعظم سطح الكرة الأرضية مغطّى بـ…", correctAnswer: "الماء", distractors: ["الرمل", "الجليد", "الغابات"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪸\nفي أيّ مدينة في إسرائيل يمكن أن نرى شعابًا مرجانية؟", correctAnswer: "في إيلات", distractors: ["في تل أبيب", "في القدس", "في حيفا"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌊\nماذا نسمّي الماء الذي يعلو ويهبط على الشاطئ مرّة بعد مرّة؟", correctAnswer: "الأمواج", distractors: ["الغيوم", "الأمطار", "الرياح"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🏖️\nماذا نسمّي المكان الذي يلتقي فيه البحر باليابسة؟", correctAnswer: "الشاطئ", distractors: ["الجبل", "الغابة", "الصحراء"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌡️\nأين يكون ماء البحر أدفأ عادةً؟", correctAnswer: "قرب السطح", distractors: ["في العمق البعيد", "متساوٍ تمامًا في كلّ مكان", "في منتصف الطريق"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⛵\nما الذي يسير على سطح الماء؟", correctAnswer: "القارب", distractors: ["السيّارة", "الدرّاجة", "القطار"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚢\nماذا نسمّي المركبة التي تسير تحت الماء؟", correctAnswer: "الغوّاصة", distractors: ["الطائرة", "القطار", "الحافلة"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🤿\nماذا نسمّي مَن ينزل تحت الماء بقناع وأسطوانة هواء؟", correctAnswer: "الغوّاص", distractors: ["الطيّار", "السائق", "حارس المرمى"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔢\nيسبح دلفينان، وانضمّ إليهما 3 دلافين. كم دلفينًا هناك الآن؟", correctAnswer: "5", distractors: ["4", "6", "3"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🔢\nفي الشعاب المرجانية تسبح 4 أسماك صفراء و3 أسماك زرقاء. كم سمكة في المجموع؟", correctAnswer: "7", distractors: ["6", "8", "1"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nكان على الشاطئ 6 أصداف، فجمعتُ منها 2. كم صدفة بقيت على الشاطئ؟", correctAnswer: "4", distractors: ["8", "3", "2"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐬\nالدلفين هو…", correctAnswer: "ثدييّ", distractors: ["سمكة", "زاحف", "طائر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐋\nالحوت يتنفّس الهواء مثل الإنسان. بماذا يتنفّس؟", correctAnswer: "بالرئتين", distractors: ["بالخياشيم", "بالزعانف", "بالحراشف"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐬\nكيف يأتي الدلفين الصغير إلى الحياة؟", correctAnswer: "يُولَد من أمّه", distractors: ["يفقس من بيضة", "ينمو من طحلب", "يخرج من صَدَفة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐟\nما الذي تملكه السمكة ولا يملكه الدلفين؟", correctAnswer: "الخياشيم", distractors: ["الذيل", "العينان", "الزعانف"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐢\nسلحفاة البحر هي…", correctAnswer: "زاحف", distractors: ["سمكة", "ثدييّ", "حشرة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐢\nماذا تفعل صغار السلاحف البحرية فور فقسها من البيض؟", correctAnswer: "تركض نحو البحر", distractors: ["تتسلّق شجرة", "تنام سنة كاملة", "تطير في الهواء"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦈\nممّ يتكوّن هيكل القِرش؟", correctAnswer: "من الغضاريف", distractors: ["من العظام", "من الخشب", "من المعدن"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🦈\nما أكبر قِرش في العالم، وهو يتغذّى أساسًا على كائنات دقيقة؟", correctAnswer: "القِرش الحوتيّ", distractors: ["القِرش الأبيض", "قِرش المطرقة", "القِرش النمر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐙\nماذا يفعل الأخطبوط كي يختبئ؟", correctAnswer: "يغيّر لونه", distractors: ["يغمض عينيه", "يقفز خارج الماء", "يغنّي بصوت عالٍ"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐙\nأيّ سحابة يطلقها الأخطبوط حين يريد الهرب؟", correctAnswer: "سحابة حبر", distractors: ["سحابة مطر", "سحابة غبار", "سحابة دخان"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🪼\nما الصحيح بشأن قنديل البحر؟", correctAnswer: "ليست له عظام", distractors: ["له دِرع صلب", "له أرجل", "له ريش"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪸\nما هو المرجان؟", correctAnswer: "كائن حيّ صغير", distractors: ["نبات", "حجر ملوّن", "نوع من الأسماك"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐠\nأين تعيش معظم الأسماك الملوّنة؟", correctAnswer: "قرب الشعاب المرجانية", distractors: ["في الأعماق المظلمة", "قرب القطب المتجمّد", "في الصحراء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔦\nحين ننزل عميقًا جدًّا في البحر، ماذا يحدث للضوء؟", correctAnswer: "يقلّ حتّى يسود الظلام", distractors: ["يصير أشدّ سطوعًا", "يبقى كما هو", "يصير أصفر"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪸\nفي أيّ بحر تقع الشعاب المرجانية في إيلات؟", correctAnswer: "في البحر الأحمر", distractors: ["في البحر المتوسّط", "في البحر الميّت", "في بحيرة طبريا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌊\nأيّ بحر يقع غرب إسرائيل، قرب تل أبيب وحيفا؟", correctAnswer: "البحر المتوسّط", distractors: ["البحر الأحمر", "البحر الميّت", "المحيط الهادئ"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🧂\nفي أيّ بحر يسهل الطفو جدًّا لشدّة ملوحته؟", correctAnswer: "البحر الميّت", distractors: ["البحر المتوسّط", "البحر الأحمر", "بحيرة طبريا"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🛟\nلماذا نطفو في البحر الميّت بلا جهد؟", correctAnswer: "لأنّ ماءه شديد الملوحة", distractors: ["لأنّ ماءه دافئ", "لأنّه ضحل", "لأنّه بلا أمواج"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🗺️\nما المميَّز في البحر الميّت؟", correctAnswer: "هو أخفض بقعة يابسة في العالم", distractors: ["هو أكبر بحر في العالم", "هو أعمق بحر في العالم", "هو أبرد بحر في العالم"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🌍\nما أكبر محيط في العالم؟", correctAnswer: "المحيط الهادئ", distractors: ["المحيط الأطلسيّ", "المحيط الهنديّ", "المحيط المتجمّد الشماليّ"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🌊\nماذا يحدث في البحر وقت \"المدّ\"؟", correctAnswer: "يرتفع الماء ويغطّي جزءًا أكبر من الشاطئ", distractors: ["يختفي الماء", "يتجمّد الماء", "يصير الماء عذبًا"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🌙\nما الذي يسبّب المدّ والجزر في البحر؟", correctAnswer: "جاذبية القمر أساسًا", distractors: ["الرياح", "الأسماك", "الغيوم"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🤿\nلماذا يحمل الغوّاص معه أسطوانة غوص؟", correctAnswer: "كي يتنفّس تحت الماء", distractors: ["كي يطفو إلى الأعلى", "كي يشرب ماءً", "كي يضيء في الظلام"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🤿\nماذا يلبس الغوّاص في قدميه كي يسبح أسرع؟", correctAnswer: "زعانف", distractors: ["جزمة طويلة", "عجلات", "صنادل"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚢\nماذا تفعل الغوّاصة حين تريد أن تهبط إلى الأعماق؟", correctAnswer: "تملأ خزّاناتها بالماء", distractors: ["تشغّل الأضواء", "تفتح النوافذ", "تُطفئ المحرّك"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nللأخطبوط 8 أذرع. كم ذراعًا لأخطبوطَين؟", correctAnswer: "16", distractors: ["10", "12", "18"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nفي السرب 10 دلافين، قفز منها 4 خارج الماء. كم دلفينًا بقي تحت الماء؟", correctAnswer: "6", distractors: ["14", "5", "4"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🔢\nلنجم البحر 5 أذرع. كم ذراعًا لـ3 نجوم بحر؟", correctAnswer: "15", distractors: ["8", "10", "20"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌍\nأيّ محيط يقع بين أوروبا وأفريقيا من جهة والأمريكتين من جهة أخرى؟", correctAnswer: "المحيط الأطلسيّ", distractors: ["المحيط الهادئ", "المحيط الهنديّ", "المحيط المتجمّد الشماليّ"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🌊\nما أعمق مكان في المحيطات؟", correctAnswer: "خندق ماريانا", distractors: ["البحر المتوسّط", "البحر الميّت", "قناة السويس"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔦\nهناك أسماك في أعماق البحر تضيء في الظلام. من أين يأتي هذا الضوء؟", correctAnswer: "من أجسامها نفسها", distractors: ["من الشمس", "من مصباح غوّاص", "من القمر"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐬\nبماذا \"يرى\" الدلفين في الظلام ويعثر على الأسماك؟", correctAnswer: "بصدى الأصوات", distractors: ["بمصباح", "بحاسّة الشمّ", "بشواربه"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🦈\nماذا يحدث حين تسقط سنّ من أسنان القِرش؟", correctAnswer: "تحلّ محلّها سنّ جديدة", distractors: ["تبقى فجوة إلى الأبد", "يتوقّف عن الأكل", "يذهب إلى طبيب الأسنان"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐋\nماذا يأكل الحوت الأزرق، أكبر حيوان في العالم؟", correctAnswer: "الكريل — قشريّات دقيقة", distractors: ["أسماك القِرش", "الدلافين", "الطحالب"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🧂\nلماذا البحر الميّت شديد الملوحة؟", correctAnswer: "ماؤه يتبخّر ويبقى الملح", distractors: ["يسكبون فيه الملح", "لأنّه متّصل بالمحيط", "لأنّ فيه أسماكًا كثيرة"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🌙\nكم مرّة في اليوم يحدث المدّ عادةً؟", correctAnswer: "مرّتان", distractors: ["مرّة واحدة", "5 مرّات", "10 مرّات"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🚢\nما هو \"البيريسكوب\" في الغوّاصة؟", correctAnswer: "أنبوب للنظر فوق سطح الماء", distractors: ["محرّك الغوّاصة", "نوع من الأسماك", "جهاز للطبخ"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🔢\nنزلت غوّاصة إلى عمق 300 متر، ثمّ صعدت 120 مترًا. على أيّ عمق هي الآن؟", correctAnswer: "180 مترًا", distractors: ["420 مترًا", "200 متر", "150 مترًا"], tier: .hard, grades: 3...5),
    ]
}
