import Foundation

/// 🎊 الأعياد — بالعربية. مأخوذ عن البنك العبريّ (72 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let holidays: [BankQuestion] = [
        BankQuestion(prompt: "🌙\nفي أيّ شهر من السنة الهجريّة يصوم المسلمون؟", correctAnswer: "رمضان", distractors: ["شعبان", "شوّال", "رجب"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🍽️\nما اسم الوجبة التي يتناولها الصائم عند غروب الشمس؟", correctAnswer: "الإفطار", distractors: ["السحور", "الغداء", "وجبة المدرسة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌅\nما اسم الوجبة التي يتناولها الصائم قبل طلوع الفجر؟", correctAnswer: "السحور", distractors: ["الإفطار", "الغداء", "العشاء"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🏮\nما الزينة المضيئة التي يحملها الأطفال ويعلّقونها في ليالي رمضان؟", correctAnswer: "الفانوس", distractors: ["المظلّة", "الطائرة الورقيّة", "الميزان"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🎁\nما اسم النقود التي يهديها الكبار للأطفال في أيّام العيد؟", correctAnswer: "العيديّة", distractors: ["الأجرة", "الغرامة", "المصروف المدرسيّ"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🥞\nما الحلوى المطويّة على شكل نصف دائرة، تُحشى بالجوز أو الجبنة، وتشتهر في رمضان؟", correctAnswer: "القطايف", distractors: ["المعمول", "الكنافة", "البقلاوة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕌\nبعد انتهاء أيّ شهر هجريّ يأتي عيد الفطر مباشرة؟", correctAnswer: "شهر رمضان", distractors: ["شهر محرّم", "شهر صفر", "شهر رجب"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🤝\nما التحيّة الجميلة التي يتبادلها الناس في الأعياد؟", correctAnswer: "كلّ عام وأنتم بخير", distractors: ["تصبحون على خير", "رحلة سعيدة", "بالشفاء العاجل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🎅\nفي أيّ مدينة في الجليل يخرج موكب الميلاد الكبير كلّ سنة؟", correctAnswer: "الناصرة", distractors: ["صفد", "طبريّا", "عكّا"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎄\nماذا يزيّن الأطفال بالأضواء والكرات الملوّنة استعدادًا لعيد الميلاد؟", correctAnswer: "الشجرة", distractors: ["الطاولة", "الدرّاجة", "الحقيبة"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥚\nماذا يلوّن الأطفال المسيحيّون في عيد الفصح؟", correctAnswer: "البيض", distractors: ["الحجارة", "الأحذية", "الملاعق"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⭐\nفي أيّ مدينة وُلد السيّد المسيح حسب الإنجيل؟", correctAnswer: "بيت لحم", distractors: ["الناصرة", "القدس", "حيفا"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🫒\nفي أيّ فصل من السنة يقطف الناس الزيتون في بلادنا؟", correctAnswer: "الخريف", distractors: ["الربيع", "الصيف", "الشتاء"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌸\nأيّ شجرة تتفتّح أزهارها البيضاء أوّلًا وتبشّر بقدوم الربيع؟", correctAnswer: "اللوز", distractors: ["الزيتون", "التين", "العنب"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "💐\nأعطى الجدّ لكلّ واحد من أحفاده الثلاثة عشرة شواقل عيديّة. كم شيكلًا وزّع الجدّ؟", correctAnswer: "30 شيكلًا", distractors: ["13 شيكلًا", "20 شيكلًا", "40 شيكلًا"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍪\nاشترت أمّ سميرة أربع علب من كعك العيد، في كلّ علبة خمس قطع. كم قطعة اشترت؟", correctAnswer: "20 قطعة", distractors: ["9 قطع", "16 قطعة", "25 قطعة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "📆\nكم يومًا يصوم المسلمون في رمضان تقريبًا؟", correctAnswer: "نحو ثلاثين يومًا", distractors: ["نحو سبعة أيّام", "نحو مئة يوم", "نحو ثلاثمئة يوم"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌇\nمتى يبدأ الصائم في رمضان بتناول الطعام والشراب؟", correctAnswer: "عند غروب الشمس", distractors: ["عند الظهر", "عند شروق الشمس", "عند منتصف الليل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "👕\nما العادة الجميلة التي يفعلها الأطفال في صباح العيد؟", correctAnswer: "يلبسون ثيابًا جديدة", distractors: ["يذهبون إلى المدرسة", "ينامون طوال النهار", "يصومون كالكبار"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐑\nفي أيّ عيد يوزّع الناس اللحم على الأهل والجيران والفقراء؟", correctAnswer: "عيد الأضحى", distractors: ["عيد الفطر", "المولد النبويّ", "رأس السنة الهجريّة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕋\nإلى أيّ مدينة يسافر الحجّاج لأداء فريضة الحجّ؟", correctAnswer: "مكّة المكرّمة", distractors: ["المدينة المنوّرة", "القدس", "دمشق"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎆\nبأيّ شهر تبدأ السنة الميلاديّة الجديدة؟", correctAnswer: "كانون الثاني", distractors: ["آذار", "أيلول", "تشرين الأوّل"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🗓️\nما اسم الشهر الأوّل في السنة الهجريّة؟", correctAnswer: "محرّم", distractors: ["رمضان", "شوّال", "رجب"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌴\nماذا يحمل الأطفال في أيديهم في أحد الشعانين؟", correctAnswer: "أغصان الزيتون وسعف النخيل", distractors: ["مظلّات ملوّنة", "أكياس الرمل", "صحون الفخّار"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🥁\nما اسم الرجل الذي يجول في الأحياء ليلًا بطبلته ليوقظ الناس لتناول السحور؟", correctAnswer: "المسحّراتي", distractors: ["المؤذّن", "الحارس", "الطبّاخ"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🕌\nما اسم الصلاة التي يؤدّيها المسلمون جماعةً في ليالي رمضان بعد صلاة العشاء؟", correctAnswer: "صلاة التراويح", distractors: ["صلاة الاستسقاء", "صلاة الجنازة", "صلاة الاستخارة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "💰\nما الصدقة الواجبة التي يخرجها المسلمون قبل صلاة عيد الفطر لتُدخل الفرح على الفقراء؟", correctAnswer: "زكاة الفطر", distractors: ["الأضحية", "العيديّة", "زكاة المال"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍖\nماذا يفعل الناس عادةً بلحم الأضحية في عيد الأضحى؟", correctAnswer: "يوزّعونه على الأهل والجيران والفقراء", distractors: ["يبيعونه كلّه في السوق", "يحتفظون به كلّه لأنفسهم", "يخبّئونه حتّى العيد المقبل"], tier: .medium, grades: 2...5),
        BankQuestion(prompt: "🌗\nعلى ماذا تعتمد شهور السنة الهجريّة في بدايتها ونهايتها؟", correctAnswer: "على دورة القمر", distractors: ["على دورة الشمس", "على فصول السنة", "على حركة الرياح"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🎉\nفي أيّ شهر هجريّ يُحتفل بالمولد النبويّ الشريف؟", correctAnswer: "ربيع الأوّل", distractors: ["رجب", "شعبان", "ذو القعدة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐫\nفي أيّ شهر هجريّ يؤدّي المسلمون فريضة الحجّ؟", correctAnswer: "ذو الحجّة", distractors: ["ذو القعدة", "محرّم", "صفر"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔭\nكيف يعرف المسلمون أنّ شهر رمضان قد بدأ؟", correctAnswer: "برؤية الهلال", distractors: ["بتغيّر فصول السنة", "ببداية العام الدراسيّ", "بهطول أوّل مطر"], tier: .medium, grades: 2...5),
        BankQuestion(prompt: "🌱\nما العيد المسيحيّ الذي يأتي في الربيع ويسبقه أسبوع الآلام؟", correctAnswer: "عيد الفصح", distractors: ["عيد الميلاد", "عيد البشارة", "عيد الغطاس"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🕊️\nفي عيد البشارة، مَن الملاك الذي حمل البُشرى إلى السيّدة مريم العذراء؟", correctAnswer: "جبرائيل", distractors: ["ميخائيل", "رفائيل", "إسرافيل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⛪\nفي أيّ مدينة تقوم كنيسة البشارة الكبيرة؟", correctAnswer: "الناصرة", distractors: ["بيت لحم", "القدس", "حيفا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔥\nفي أيّ مدينة تُقام صلاة سبت النور في كنيسة القيامة؟", correctAnswer: "القدس", distractors: ["الناصرة", "بيت لحم", "يافا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🎼\nما اسم الأناشيد الدينيّة العذبة التي تُرفع في الكنائس ليلة عيد الميلاد؟", correctAnswer: "الترانيم", distractors: ["الأهازيج", "المواويل", "الأمثال"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🎊\nما اسم الليلة التي تودّع فيها العائلات السنة الميلاديّة وتستقبل التي بعدها؟", correctAnswer: "ليلة رأس السنة", distractors: ["ليلة القدر", "سبت النور", "ليلة السحور"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🏛️\nقرب أيّ قرية في الجليل يقع مقام النبيّ شعيب الذي يزوره الدروز كلّ سنة؟", correctAnswer: "حطّين قرب طبريّا", distractors: ["دالية الكرمل", "بيت جنّ", "المغار"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "📅\nفي أيّ شهر تُقام زيارة النبيّ شعيب السنويّة عند الدروز؟", correctAnswer: "نيسان", distractors: ["شباط", "تمّوز", "تشرين الثاني"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🐏\nأيّ عيد يحتفل به الدروز في بلادنا مع إخوانهم المسلمين؟", correctAnswer: "عيد الأضحى", distractors: ["عيد الفطر", "المولد النبويّ", "رأس السنة الهجريّة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛢️\nإلى أين يُنقل الزيتون بعد قطافه ليتحوّل إلى زيت؟", correctAnswer: "إلى المعصرة", distractors: ["إلى المشتل", "إلى الفرن", "إلى المكتبة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧺\nلماذا يفرش الفلّاحون الأغطية على الأرض تحت أشجار الزيتون في موسم القطاف؟", correctAnswer: "لئلّا تضيع الحبّات المتساقطة", distractors: ["لتدفئة جذع الشجرة", "لمنع وصول الشمس إلى الأوراق", "لتزيين الحقل للضيوف"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "❄️\nفي أيّ شهر تتفتّح أزهار اللوز البيضاء في بلادنا؟", correctAnswer: "شباط", distractors: ["آب", "تشرين الأوّل", "كانون الأوّل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🫒\nقطفت العائلة 18 كيلوغرامًا من الزيتون في اليوم الأوّل و22 كيلوغرامًا في اليوم الثاني. كم كيلوغرامًا قطفت في اليومين؟", correctAnswer: "40 كيلوغرامًا", distractors: ["30 كيلوغرامًا", "38 كيلوغرامًا", "42 كيلوغرامًا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍮\nما الحلوى المصنوعة من الجبنة والشعيريّة، وتُسقى بالقطر، وتشتهر بها مدينة نابلس؟", correctAnswer: "الكنافة", distractors: ["البقلاوة", "المعمول", "القطايف"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥮\nأيّ حلوى محشوّة بالتمر أو الجوز يصنعها المسلمون والمسيحيّون معًا في أعيادهم؟", correctAnswer: "المعمول", distractors: ["القطايف", "الكنافة", "البوظة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🎄\nعند الطوائف الكاثوليكيّة واللاتينيّة، في أيّ يوم من كانون الأوّل يُحتفل بعيد الميلاد؟", correctAnswer: "في الخامس والعشرين", distractors: ["في الأوّل", "في العاشر", "في الخامس عشر"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌟\nفي أيّ ليالٍ من رمضان يترقّب المسلمون ليلة القدر المباركة؟", correctAnswer: "في العشر الأواخر", distractors: ["في العشر الأُوَل", "في العشر الأواسط", "في الليلة الأولى"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📖\nبماذا وصف القرآن الكريم ليلة القدر في عِظَم فضلها؟", correctAnswer: "بأنّها خير من ألف شهر", distractors: ["بأنّها خير من ألف يوم", "بأنّها خير من مئة سنة", "بأنّها خير من ألف ليلة"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🧭\nمن أيّ حدث يبدأ التقويم الهجريّ عدّ سنواته؟", correctAnswer: "من هجرة النبيّ محمّد ﷺ من مكّة إلى المدينة", distractors: ["من فتح مكّة", "من بناء الكعبة", "من حجّة الوداع"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔄\nلماذا يتنقّل شهر رمضان كلّ عام بين فصول السنة؟", correctAnswer: "لأنّ السنة الهجريّة أقصر من الميلاديّة بنحو أحد عشر يومًا", distractors: ["لأنّ عدد شهوره يتغيّر كلّ عام", "لأنّ الناس يختارون موعده كلّ عام", "لأنّه يتبع فصل الحصاد"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "⏳\nالسنة الهجريّة أقصر من الميلاديّة بنحو أحد عشر يومًا. بعد كم سنة تقريبًا يعود رمضان إلى الفصل نفسه؟", correctAnswer: "نحو ثلاث وثلاثين سنة", distractors: ["نحو عشر سنوات", "نحو عشرين سنة", "نحو خمسين سنة"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "⛰️\nما اسم الجبل الذي يقف عنده الحجّاج في اليوم التاسع من ذي الحجّة؟", correctAnswer: "جبل عرفات", distractors: ["جبل الطور", "جبل الكرمل", "جبل الشيخ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🗿\nما اسم البناء المكعّب الذي يطوف حوله الحجّاج في المسجد الحرام؟", correctAnswer: "الكعبة المشرّفة", distractors: ["قبّة الصخرة", "مقام إبراهيم", "بئر زمزم"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🎈\nكم يومًا يستمرّ عيد الأضحى؟", correctAnswer: "أربعة أيّام", distractors: ["يوم واحد", "يومان", "سبعة أيّام"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💚\nمَن رخّص لهم الإسلام أن يفطروا في رمضان ويقضوا الصيام بعد ذلك؟", correctAnswer: "المريض والمسافر", distractors: ["الطالب في يوم امتحان", "من يسكن بعيدًا عن المسجد", "من يعمل في مكتب"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🤲\nما الصلاة الخاصّة التي يؤدّيها المسلمون جماعةً في صباح أوّل أيّام الفطر والأضحى؟", correctAnswer: "صلاة العيد", distractors: ["صلاة الجمعة", "صلاة الاستسقاء", "صلاة التراويح"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🕌\nأيّ ركن من أركان الإسلام يؤدّيه المسلم مرّة واحدة في العمر إن استطاع إليه سبيلًا؟", correctAnswer: "الحجّ", distractors: ["الصلاة", "الصوم", "الزكاة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌴\nبماذا يبدأ كثير من الصائمين إفطارهم اتّباعًا للسنّة النبويّة؟", correctAnswer: "بالتمر والماء", distractors: ["بالشاي والكعك", "باللحم والأرزّ", "بالحلوى الباردة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🗺️\nلماذا يحتفل بعض المسيحيّين في بلادنا بعيد الميلاد في السابع من كانون الثاني؟", correctAnswer: "لأنّهم يتبعون التقويم الشرقيّ القديم", distractors: ["لأنّ الطقس يكون أشدّ برودة", "لأنّ العطلة المدرسيّة تبدأ حينها", "لأنّ السنة الميلاديّة تبدأ حينها"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "✝️\nما اسم الصوم الطويل الذي يسبق عيد الفصح عند المسيحيّين؟", correctAnswer: "الصوم الكبير", distractors: ["صوم الميلاد", "صوم الرسل", "صوم العذراء"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "📿\nكم يومًا يستمرّ الصوم الكبير عند المسيحيّين؟", correctAnswer: "أربعين يومًا", distractors: ["عشرة أيّام", "ثلاثة أيّام", "مئة يوم"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "💌\nأيّ عيد مسيحيّ يُحتفل به في الخامس والعشرين من آذار، أي قبل الميلاد بتسعة أشهر؟", correctAnswer: "عيد البشارة", distractors: ["عيد الغطاس", "عيد الصليب", "أحد الشعانين"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "💧\nما اسم العيد الذي يُذكر فيه اعتماد السيّد المسيح في نهر الأردنّ؟", correctAnswer: "عيد الغطاس", distractors: ["عيد البشارة", "عيد الصليب", "عيد الفصح"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏰\nما اسم الكنيسة التي بُنيت في بيت لحم فوق مغارة ميلاد السيّد المسيح؟", correctAnswer: "كنيسة المهد", distractors: ["كنيسة القيامة", "كنيسة البشارة", "كنيسة الجثمانيّة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐑\nحسب إنجيل لوقا، مَن أوّل مَن حمل إليهم الملاك بُشرى ولادة السيّد المسيح؟", correctAnswer: "الرعاة", distractors: ["الملوك", "الجنود", "التجّار"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🐣\nإلى ماذا يرمز بيض الفصح الملوّن عند المسيحيّين؟", correctAnswer: "إلى الحياة الجديدة", distractors: ["إلى فصل الشتاء", "إلى الحصاد الوفير", "إلى السفر الطويل"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💵\nوزّعت الجدّة 120 شيكلًا عيديّة بالتساوي على ثمانية أحفاد. كم نال كلّ حفيد؟", correctAnswer: "15 شيكلًا", distractors: ["12 شيكلًا", "14 شيكلًا", "18 شيكلًا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📦\nصنعت أمّ خالد 96 قطعة معمول ووزّعتها على علب، في كلّ علبة 12 قطعة. كم علبة احتاجت؟", correctAnswer: "8 علب", distractors: ["6 علب", "9 علب", "12 علبة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍰\nقُسّمت صينيّة كنافة إلى 12 قطعة، فأكل الضيوف ثلاثة أرباعها. كم قطعة أكلوا؟", correctAnswer: "9 قطع", distractors: ["3 قطع", "6 قطع", "8 قطع"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🧮\nإذا بدأ رمضان يوم الاثنين واستمرّ ثلاثين يومًا، ففي أيّ يوم من الأسبوع يكون أوّل أيّام عيد الفطر؟", correctAnswer: "الأربعاء", distractors: ["الثلاثاء", "الخميس", "الجمعة"], tier: .hard, grades: 5...6),
    ]
}
