import Foundation

/// 💰 المال — بالعربية. مأخوذ عن البنك العبريّ (246 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let money: [BankQuestion] = [
        BankQuestion(prompt: "💰\nكم أغورة في الشاقل الواحد؟", correctAnswer: "100", distractors: ["10", "50", "1000"], grades: 2...3),
        BankQuestion(prompt: "🪙🪙🪙🪙🪙\n5 قطع نقديّة من فئة 1 ₪ — كم تساوي معًا؟", correctAnswer: "5 ₪", distractors: ["3 ₪", "4 ₪", "6 ₪"], grades: 1...3),
        BankQuestion(prompt: "🍦\nمعك 10 ₪ والبوظة ثمنها 6 ₪. كم سيكون الباقي؟", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "5 ₪"], grades: 3...4),
        BankQuestion(prompt: "💵\nأيّ ورقة نقديّة قيمتها الأكبر؟", correctAnswer: "200 ₪", distractors: ["20 ₪", "50 ₪", "100 ₪"], grades: 1...2),
        BankQuestion(prompt: "🐷\nماذا نفعل بالحصّالة؟", correctAnswer: "نضع فيها مالًا للمستقبل", distractors: ["نحفظ فيها الحلويات", "نملؤها بالماء", "نضعها على الرفّ للزينة"], grades: 1...3),
        BankQuestion(prompt: "🛒\nتريدون شراء لعبة غالية. ماذا يُستحسن أن تفعلوا؟", correctAnswer: "أن توفّروا قليلًا كلّ أسبوع", distractors: ["أن تصرفوا كلّ شيء فورًا", "أن تطلبوا المزيد والمزيد", "ألّا تفكّروا في الأمر"], grades: 2...5),
        BankQuestion(prompt: "🥤\nأيّ ممّا يلي 'حاجة' مهمّة؟", correctAnswer: "طعام وماء", distractors: ["لعبة جديدة", "ملصقات", "لعبة على الهاتف"], grades: 2...5),
        BankQuestion(prompt: "🪙🪙\nقطعتان نقديّتان من فئة 5 ₪ — كم تساويان؟", correctAnswer: "10 ₪", distractors: ["7 ₪", "12 ₪", "15 ₪"], grades: 2...3),
        BankQuestion(prompt: "🛍️\nاشتريت بـ12 ₪ ودفعت بورقة من فئة 20 ₪. كم الباقي؟", correctAnswer: "8 ₪", distractors: ["6 ₪", "7 ₪", "10 ₪"], grades: 3...4),
        BankQuestion(prompt: "💳\nما هي بطاقة الائتمان؟", correctAnswer: "طريقة للدفع دون نقود", distractors: ["لعبة", "بطاقة للّعب", "صورة"], grades: 3...5),
        BankQuestion(prompt: "🏷️\nأيّ منتج أرخص — الذي ثمنه 8 ₪ أم الذي ثمنه 12 ₪؟", correctAnswer: "الذي يكلّف 8 ₪", distractors: ["الذي يكلّف 12 ₪", "كلاهما متساويان", "لا يمكن أن نعرف"], grades: 2...3),
        BankQuestion(prompt: "💝\nنسي صديق أن يُحضر مالًا للطعام. ما اللطيف أن نفعل؟", correctAnswer: "أن أشاركه طعامي", distractors: ["أن أتجاهله", "أن آكل وحدي بهدوء", "أن آكل بسرعة"], grades: 0...2),
        BankQuestion(prompt: "🪙\nكم أغورة تساوي قطعة نصف شاقل؟", correctAnswer: "50", distractors: ["5", "10", "100"], grades: 3...4),
        BankQuestion(prompt: "📋\nما هي 'الميزانيّة'؟", correctAnswer: "خطّة تحدّد كم من المال يُسمح بصرفه", distractors: ["نوع من الحلوى", "لعبة علبة", "نوع من القطع النقديّة"], grades: 4...6),
        BankQuestion(prompt: "💰\nمعك 3 ₪ وحصلت على 5 ₪ إضافيّة. كم صار معك الآن؟", correctAnswer: "8 ₪", distractors: ["2 ₪", "7 ₪", "9 ₪"], grades: 1...3),
        BankQuestion(prompt: "🤔\nمتى يُستحسن شراء شيء ما؟", correctAnswer: "عندما نحتاج إليه فعلًا", distractors: ["دائمًا وفورًا", "عندما يشتريه صديق", "أبدًا في أيّ وقت"], grades: 2...5),
        BankQuestion(prompt: "🏦\nأين يحفظ الكبار أموالهم بأمان؟", correctAnswer: "في البنك", distractors: ["في الشارع", "في سلّة المهملات", "في الشجرة"], grades: 1...3),
        BankQuestion(prompt: "🎁\nوفّرت 50 ₪ والهديّة ثمنها 80 ₪. كم ينقصك بعد؟", correctAnswer: "30 ₪", distractors: ["20 ₪", "40 ₪", "50 ₪"], grades: 3...4),
        BankQuestion(prompt: "♻️\nكيف يمكن توفير المال في البيت؟", correctAnswer: "إطفاء الضوء الذي لا نحتاج إليه", distractors: ["ترك كلّ شيء مضاءً", "رمي الطعام", "شراء كلّ شيء مرّتين"], grades: 2...5),
        BankQuestion(prompt: "🪙🪙🪙\n3 قطع نقديّة من فئة 2 ₪ — كم تساوي؟", correctAnswer: "6 ₪", distractors: ["5 ₪", "8 ₪", "9 ₪"], grades: 2...3),
        BankQuestion(prompt: "لعبة ثمنها 45 شاقلًا. دفعتم بورقة من فئة 50. كم سيكون الباقي؟", correctAnswer: "5 شواقل", distractors: ["10 شواقل", "15 شاقلًا", "45 شاقلًا"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "البوظة ثمنها 12 شاقلًا. كم تكلّف 3 بوظات؟", correctAnswer: "36 شاقلًا", distractors: ["24 شاقلًا", "30 شاقلًا", "42 شاقلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "معكم 100 شاقل. اشتريتم كتابًا بـ35 ولعبة بـ40. كم بقي؟", correctAnswer: "25 شاقلًا", distractors: ["35 شاقلًا", "15 شاقلًا", "30 شاقلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما هو \"الادّخار\"؟", correctAnswer: "مال نحفظه للمستقبل بدل أن نصرفه", distractors: ["مال نصرفه بسرعة", "هديّة من الأصدقاء", "نوع من القطع النقديّة"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "إذا وفّرنا 10 شواقل كلّ أسبوع، فكم يصير معنا بعد شهر (4 أسابيع)؟", correctAnswer: "40 شاقلًا", distractors: ["10 شواقل", "30 شاقلًا", "50 شاقلًا"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "ما هو \"سعر العرض\"؟", correctAnswer: "سعر أرخص من المعتاد لفترة محدودة", distractors: ["أغلى سعر في المتجر", "سعر لا يتغيّر أبدًا", "سعر ندفعه في الصيف فقط"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "قميص كان ثمنه 60 شاقلًا والآن بنصف السعر. كم يكلّف؟", correctAnswer: "30 شاقلًا", distractors: ["20 شاقلًا", "40 شاقلًا", "55 شاقلًا"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "لماذا يُستحسن مقارنة الأسعار قبل الشراء؟", correctAnswer: "لنجد المنتج نفسه بسعر أرخص", distractors: ["لنضيّع وقتًا أطول", "لأنّ ذلك واجب بحسب القانون", "لنشتري أكبر قدر ممكن"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "ماذا يفعل البنك بالمال الذي ندّخره عنده؟", correctAnswer: "يحفظه ويعطي عليه فائدة", distractors: ["يصرفه", "يرميه", "يبدّله بالحلويات"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "في الوجبة: بيتزا بـ28 شاقلًا ومشروب بـ7. كم المجموع؟", correctAnswer: "35 شاقلًا", distractors: ["33 شاقلًا", "37 شاقلًا", "38 شاقلًا"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🪙\nما اسم عملة دولة إسرائيل؟", correctAnswer: "الشاقل", distractors: ["الدولار", "اليورو", "الين"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙\nكم يساوي شاقل وشاقل آخر؟", correctAnswer: "2 شاقل", distractors: ["1 شاقل", "3 شواقل", "10 شواقل"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙\nكم تساوي قطعتان نقديّتان من فئة 5 شواقل؟", correctAnswer: "10 شواقل", distractors: ["5 شواقل", "7 شواقل", "20 شاقلًا"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🛒\nأين ندفع ثمن المشتريات في المتجر؟", correctAnswer: "عند الصندوق", distractors: ["عند المدخل", "في المستودع", "في الموقف"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏷️\nماذا يخبرنا سعر المنتج؟", correctAnswer: "كم من المال ندفع ثمنًا له", distractors: ["كم يزن", "ما لونه", "متى يُغلق المتجر"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙\nكم أغورة في الشاقل الواحد؟", correctAnswer: "100", distractors: ["10", "50", "1000"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧸\nلعبة ثمنها 7 شواقل ومعكم 10 شواقل. هل يمكنكم شراؤها؟", correctAnswer: "نعم، وسيبقى لكم باقٍ أيضًا", distractors: ["لا، المال لا يكفي", "فقط إذا كان هناك خصم", "لا يمكن أن نعرف"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙\nكم تساوي قطعة من فئة 2 شاقل وقطعة أخرى من فئة شاقل واحد؟", correctAnswer: "3 شواقل", distractors: ["2 شاقل", "4 شواقل", "5 شواقل"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "💵\nدفعتم 20 شاقلًا ثمن لعبة تكلّف 12 شاقلًا. كم سيكون الباقي؟", correctAnswer: "8 شواقل", distractors: ["6 شواقل", "10 شواقل", "12 شاقلًا"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "💵\nدفعتم 50 شاقلًا ثمن كتاب يكلّف 35 شاقلًا. كم سيكون الباقي؟", correctAnswer: "15 شاقلًا", distractors: ["25 شاقلًا", "10 شواقل", "20 شاقلًا"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧃\nعصير ثمنه 6 شواقل وعصير آخر ثمنه 9 شواقل. أيّهما أرخص؟", correctAnswer: "الذي يكلّف 6 شواقل", distractors: ["الذي يكلّف 9 شواقل", "كلاهما بالسعر نفسه", "لا يمكن أن نعرف"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐷\nماذا يعني أن ندّخر المال؟", correctAnswer: "أن نحفظ مالًا جانبًا لهدف مهمّ", distractors: ["أن نصرف كلّ شيء فورًا", "أن نخبّئ المال وننسى أين", "أن نعطي كلّ شيء هديّة"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍞\nأيّ من هذه الأشياء حاجة وليس رغبة؟", correctAnswer: "خبز للوجبة", distractors: ["حلوى إضافيّة", "لعبة جديدة", "ملصقات لامعة"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🎮\nأيّ من هذه الأشياء رغبة وليس حاجة؟", correctAnswer: "لعبة حاسوب جديدة", distractors: ["ماء للشرب", "معطف للشتاء", "دواء عند المرض"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🪙\nتوفّرون 5 شواقل كلّ أسبوع. كم توفّرون في 4 أسابيع؟", correctAnswer: "20 شاقلًا", distractors: ["9 شواقل", "15 شاقلًا", "25 شاقلًا"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🛒\nاشتريتم دفترًا بـ7 شواقل وقلمًا بـ8 شواقل. كم دفعتم في المجموع؟", correctAnswer: "15 شاقلًا", distractors: ["14 شاقلًا", "16 شاقلًا", "13 شاقلًا"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐷\nأين يُستحسن أن نحفظ في البيت المال الذي ندّخره؟", correctAnswer: "في الحصّالة", distractors: ["على أرض غرفة الجلوس", "داخل صندوق الألعاب", "في جيب معطف قديم"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍫\nالوجبة الخفيفة نفسها ثمنها 4 شواقل في متجر و5 شواقل في متجر آخر. أين يُجدي شراؤها؟", correctAnswer: "في المتجر الذي تكلّف فيه 4 شواقل", distractors: ["في المتجر الذي تكلّف فيه 5 شواقل", "لا فرق بين المتجرين", "في المتجر الأبعد"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🏷️\nقميص ثمنه 30 شاقلًا وعليه عرض بنصف السعر. كم تدفعون؟", correctAnswer: "15 شاقلًا", distractors: ["10 شواقل", "20 شاقلًا", "25 شاقلًا"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏷️\nلعبة ثمنها 40 شاقلًا وعليها خصم 25%. كم تدفعون؟", correctAnswer: "30 شاقلًا", distractors: ["25 شاقلًا", "35 شاقلًا", "10 شواقل"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏷️\nكتاب ثمنه 50 شاقلًا وعليه خصم 10%. كم تدفعون؟", correctAnswer: "45 شاقلًا", distractors: ["40 شاقلًا", "48 شاقلًا", "5 شواقل"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏦\nما هو البنك؟", correctAnswer: "مكان يحفظ المال ويمنح القروض", distractors: ["متجر للحلويات", "مكان يوزّع المال مجّانًا", "لعبة ورق"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "📈\nما اسم الإضافة التي يضيفها البنك إلى المال المدّخر عنده مع مرور الوقت؟", correctAnswer: "الفائدة", distractors: ["الخصم", "الباقي", "الغرامة"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🐷\nمصروفكم الأسبوعيّ عشرون شاقلًا وتصرفون منه 15 شاقلًا. كم توفّرون في 4 أسابيع؟", correctAnswer: "20 شاقلًا", distractors: ["5 شواقل", "15 شاقلًا", "60 شاقلًا"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "📋\nما هي الميزانيّة؟", correctAnswer: "خطّة تحدّد كم من المال نصرف وعلى ماذا", distractors: ["قائمة ألعاب", "نوع من القطع النقديّة", "اسم بنك"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🧠\nماذا يفعل المستهلك الذكيّ قبل عمليّة شراء كبيرة؟", correctAnswer: "يقارن الأسعار بين المتاجر", distractors: ["يشتري من أوّل متجر يراه", "يختار المنتج الأغلى", "يشتري دون أن ينظر إلى السعر"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🎁\nفي عرض 1+1 نأخذ منتجين بسعر 10 شواقل. كم يكلّف كلّ منتج فعليًّا؟", correctAnswer: "5 شواقل", distractors: ["10 شواقل", "20 شاقلًا", "2 شاقل"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🎯\nلعبة ثمنها 60 شاقلًا وتوفّرون 10 شواقل في الأسبوع. خلال كم أسبوعًا تستطيعون شراءها؟", correctAnswer: "6 أسابيع", distractors: ["4 أسابيع", "5 أسابيع", "10 أسابيع"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🪙🪙🪙🪙\nأربع قطع نقديّة من فئة 1 ₪ — كم تساوي معًا؟", correctAnswer: "4 ₪", distractors: ["3 ₪", "5 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "🪙🪙\nقطعة من فئة 2 ₪ وقطعة أخرى من فئة 2 ₪ — كم تساويان؟", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "🍬\nمعك 5 ₪ والحلوى ثمنها 2 ₪. كم سيكون الباقي؟", correctAnswer: "3 ₪", distractors: ["1 ₪", "2 ₪", "4 ₪"], grades: 3...4),
        BankQuestion(prompt: "🥨\nاشتريت كعكة مملّحة بـ4 ₪ ودفعت بـ10 ₪. كم الباقي؟", correctAnswer: "6 ₪", distractors: ["4 ₪", "5 ₪", "7 ₪"], grades: 3...4),
        BankQuestion(prompt: "🍌\nالموزة ثمنها 3 ₪. دفعت بـ5 ₪. كم الباقي؟", correctAnswer: "2 ₪", distractors: ["1 ₪", "3 ₪", "4 ₪"], grades: 3...4),
        BankQuestion(prompt: "💰\nمعك 2 ₪ وحصلت على 6 ₪ إضافيّة. كم صار معك الآن؟", correctAnswer: "8 ₪", distractors: ["4 ₪", "7 ₪", "9 ₪"], grades: 2...3),
        BankQuestion(prompt: "🪙🪙🪙\nثلاث قطع نقديّة من فئة 1 ₪ وقطعة أخرى من فئة 1 ₪ — كم تساوي؟", correctAnswer: "4 ₪", distractors: ["3 ₪", "5 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "🥕\nالجزرة ثمنها 2 ₪. كم تكلّف ثلاث جزرات؟", correctAnswer: "6 ₪", distractors: ["4 ₪", "5 ₪", "8 ₪"], grades: 2...3),
        BankQuestion(prompt: "🪙\nأيّ قطعة نقديّة قيمتها الأكبر؟", correctAnswer: "10 ₪", distractors: ["1 ₪", "2 ₪", "5 ₪"], grades: 1...2),
        BankQuestion(prompt: "💵\nأيّ ورقة نقديّة قيمتها الأقلّ؟", correctAnswer: "20 ₪", distractors: ["50 ₪", "100 ₪", "200 ₪"], grades: 1...2),
        BankQuestion(prompt: "🪙\nكم قطعة نقديّة من فئة 1 ₪ نحتاج لنصل إلى 5 ₪؟", correctAnswer: "5 قطع", distractors: ["قطعتان", "3 قطع", "10 قطع"], grades: 2...3),
        BankQuestion(prompt: "🧃\nأيّ ممّا يلي 'رغبة' وليس 'حاجة'؟", correctAnswer: "لعبة جديدة", distractors: ["ماء للشرب", "طعام صحّيّ", "ثياب دافئة"], grades: 3...4),
        BankQuestion(prompt: "🛏️\nأيّ ممّا يلي 'حاجة' مهمّة؟", correctAnswer: "مكان للنوم", distractors: ["بالون ملوّن", "ملصقات", "لعبة جديدة"], grades: 3...4),
        BankQuestion(prompt: "🐷\nكيف تمتلئ الحصّالة؟", correctAnswer: "نضيف إليها قليلًا من المال في كلّ مرّة", distractors: ["نخرج منها كلّ يوم", "نتركها فارغة", "نرميها"], grades: 3...4),
        BankQuestion(prompt: "💡\nلماذا يُستحسن ادّخار المال؟", correctAnswer: "لكي يكون لدينا ما يكفي لشيء كبير في المستقبل", distractors: ["لكي نصرفه أسرع", "لكي نضيّعه", "لكي نخبّئه"], grades: 3...4),
        BankQuestion(prompt: "🛒\nمعك 10 ₪ واللعبة ثمنها 15 ₪. كم ينقصك لشرائها؟", correctAnswer: "ينقصك 5 ₪", distractors: ["ينقصك 10 ₪", "ينقصك 15 ₪", "ينقصك 25 ₪"], grades: 3...4),
        BankQuestion(prompt: "🍕\nعندكم بيتزا واحدة لـ4 أصدقاء. ما الأعدل؟", correctAnswer: "تقسيمها بالتساوي", distractors: ["أن يأخذ كلّ واحد حصّة بحجم مختلف", "إعطاؤها لاثنين منهم فقط", "حفظها كلّها للغد"], grades: 3...4),
        BankQuestion(prompt: "💝\nأخوك لا يملك مالًا لملصق وعندك ملصقان. ما اللطيف أن تفعل؟", correctAnswer: "أن تعطيه ملصقًا واحدًا", distractors: ["أن تحتفظ بالاثنين لنفسك", "أن تعطيه ربّما غدًا", "أن تشتري ملصقات أخرى"], grades: 3...4),
        BankQuestion(prompt: "🏷️\nاللعبة نفسها ثمنها 9 ₪ في متجر و7 ₪ في متجر آخر. أين هي أرخص؟", correctAnswer: "حيث تكلّف 7 ₪", distractors: ["حيث تكلّف 9 ₪", "السعر نفسه", "لا يمكن أن نعرف"], grades: 3...4),
        BankQuestion(prompt: "📋\nماذا يُستحسن أن نفعل قبل شراء أشياء كثيرة؟", correctAnswer: "أن نكتب قائمة ونتحقّق كم معنا من المال", distractors: ["أن نشتري كلّ شيء دون تفكير", "ألّا نتحقّق كم معنا من المال", "أن نشتري الأغلى فقط"], grades: 4...6),
        BankQuestion(prompt: "💰\nوفّرت 4 ₪ وحصلت على 4 ₪ أخرى من جدّتك. كم صار معك؟", correctAnswer: "8 ₪", distractors: ["4 ₪", "6 ₪", "10 ₪"], grades: 2...3),
        BankQuestion(prompt: "🪙\nأيّ قطعة نقديّة أكبر قيمة — 2 ₪ أم 5 ₪؟", correctAnswer: "قطعة 5 ₪", distractors: ["قطعة 2 ₪", "كلتاهما متساويتان", "لا يمكن أن نعرف"], grades: 1...2),
        BankQuestion(prompt: "🛍️\nدفعت 7 ₪ بورقة من فئة 10 ₪. كم الباقي؟", correctAnswer: "3 ₪", distractors: ["2 ₪", "4 ₪", "5 ₪"], grades: 3...4),
        BankQuestion(prompt: "🍫\nالشوكولاتة ثمنها 6 ₪ ودفعت بـ6 ₪. كم الباقي؟", correctAnswer: "0 ₪", distractors: ["1 ₪", "2 ₪", "6 ₪"], grades: 3...4),
        BankQuestion(prompt: "🤝\nأنت وصديقك تريدان شراء كرة بـ10 ₪ معًا. كم يدفع كلّ واحد بالتساوي؟", correctAnswer: "5 ₪", distractors: ["2 ₪", "10 ₪", "20 ₪"], grades: 3...4),
        BankQuestion(prompt: "🐖\nفي الحصّالة 5 ₪ وأضفت 3 ₪. كم صار فيها الآن؟", correctAnswer: "8 ₪", distractors: ["2 ₪", "7 ₪", "9 ₪"], grades: 2...3),
        BankQuestion(prompt: "🧾\nماذا نأخذ في المتجر بعد أن ندفع؟", correctAnswer: "إيصال", distractors: ["لعبة هديّة", "مال إضافيّ", "مفتاح المتجر"], grades: 4...6),
        BankQuestion(prompt: "💸\nماذا يحدث إذا صرفنا كلّ المال فورًا؟", correctAnswer: "لا يبقى مال لأشياء أخرى", distractors: ["يعود المال وحده", "نحصل على مال إضافيّ", "لا يحدث شيء أبدًا"], grades: 3...4),
        BankQuestion(prompt: "🎈\nالبالون ثمنه 2 ₪. كم يكلّف بالونان؟", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "🪙🪙🪙🪙🪙\nخمس قطع نقديّة من فئة 1 ₪ — كم تساوي معًا؟", correctAnswer: "5 ₪", distractors: ["4 ₪", "6 ₪", "10 ₪"], grades: 1...2),
        BankQuestion(prompt: "🪙🪙🪙\nثلاث قطع نقديّة من فئة 2 ₪ — كم تساوي معًا؟", correctAnswer: "6 ₪", distractors: ["3 ₪", "5 ₪", "8 ₪"], grades: 2...3),
        BankQuestion(prompt: "🍎\nالتفّاحة ثمنها 3 ₪ ودفعت بـ10 ₪. كم الباقي؟", correctAnswer: "7 ₪", distractors: ["5 ₪", "6 ₪", "8 ₪"], grades: 3...4),
        BankQuestion(prompt: "🥛\nشربت حليبًا بـ4 ₪ ودفعت بـ5 ₪. كم الباقي؟", correctAnswer: "1 ₪", distractors: ["2 ₪", "3 ₪", "4 ₪"], grades: 3...4),
        BankQuestion(prompt: "🍦\nالبوظة ثمنها 8 ₪ ودفعت بـ10 ₪. كم الباقي؟", correctAnswer: "2 ₪", distractors: ["1 ₪", "3 ₪", "4 ₪"], grades: 3...4),
        BankQuestion(prompt: "🪙\nكم قطعة نقديّة من فئة 2 ₪ نحتاج لنصل إلى 10 ₪؟", correctAnswer: "5 قطع", distractors: ["قطعتان", "3 قطع", "10 قطع"], grades: 2...3),
        BankQuestion(prompt: "💧\nأيّ ممّا يلي 'حاجة' مهمّة للجسم؟", correctAnswer: "ماء للشرب", distractors: ["حاسوب ألعاب", "حلوى كبيرة", "قبّعة مضحكة"], grades: 3...4),
        BankQuestion(prompt: "🎮\nأيّ ممّا يلي 'رغبة' وليس 'حاجة'؟", correctAnswer: "لعبة حاسوب جديدة", distractors: ["حذاء للمشي", "طعام صحّيّ", "مكان دافئ للنوم"], grades: 3...4),
        BankQuestion(prompt: "🐷\nما أفضل ما نفعله بمال حصلنا عليه ولا نحتاج إليه الآن؟", correctAnswer: "أن نضعه في الحصّالة", distractors: ["أن نصرفه كلّه فورًا", "أن نضيّعه", "أن نرميه في سلّة المهملات"], grades: 4...6),
        BankQuestion(prompt: "🏷️\nالكتاب نفسه ثمنه 8 ₪ في متجر و6 ₪ في المتجر الثاني. أين هو أرخص؟", correctAnswer: "حيث يكلّف 6 ₪", distractors: ["حيث يكلّف 8 ₪", "السعر نفسه", "لا يمكن أن نعرف"], grades: 3...4),
        BankQuestion(prompt: "🍪\nالبسكويتة ثمنها 2 ₪. كم تكلّف ثلاث بسكويتات؟", correctAnswer: "6 ₪", distractors: ["4 ₪", "5 ₪", "8 ₪"], grades: 2...3),
        BankQuestion(prompt: "💰\nوفّرت 3 ₪ وحصلت على 2 ₪ إضافيّة. كم صار معك الآن؟", correctAnswer: "5 ₪", distractors: ["1 ₪", "4 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "🤝\nثلاث كعكات لـ3 أطفال. كم يأخذ كلّ واحد في التقسيم العادل؟", correctAnswer: "كعكة واحدة", distractors: ["كعكتان", "ثلاث كعكات", "لا شيء"], grades: 2...3),
        BankQuestion(prompt: "🪙\nأيّ قطعة نقديّة أقلّ قيمة — 1 ₪ أم 5 ₪؟", correctAnswer: "قطعة 1 ₪", distractors: ["قطعة 5 ₪", "كلتاهما متساويتان", "لا يمكن أن نعرف"], grades: 1...2),
        BankQuestion(prompt: "📋\nخطّطت لشراء 3 أشياء لكنّ المال يكفي لاثنين فقط. ماذا يُستحسن؟", correctAnswer: "أن تختار أهمّ شيئين", distractors: ["أن تشتري الأغلى فقط", "أن تتخلّى عن كلّ شيء وتذهب", "أن تشتري الأرخص فقط"], grades: 3...4),
        BankQuestion(prompt: "🍇\nعنقود العنب ثمنه 5 ₪ ودفعت بـ5 ₪. كم الباقي؟", correctAnswer: "0 ₪", distractors: ["1 ₪", "2 ₪", "5 ₪"], grades: 3...4),
        BankQuestion(prompt: "🐖\nفي الحصّالة 6 ₪ وأخرجت منها 2 ₪. كم بقي؟", correctAnswer: "4 ₪", distractors: ["2 ₪", "6 ₪", "8 ₪"], grades: 2...3),
        BankQuestion(prompt: "🎁\nأردت هديّة بـ12 ₪ لكن معك 9 ₪ فقط. ماذا يُستحسن أن تفعل؟", correctAnswer: "أن توفّر قليلًا بعد حتّى يكفي المبلغ", distractors: ["أن تشتريها رغم ذلك وتصير مدينًا", "أن تتخلّى عن الهديّة تمامًا", "أن تطلب هديّة أغلى منها"], grades: 4...6),
        BankQuestion(prompt: "🪙🪙\nقطعة من فئة 5 ₪ وقطعة أخرى من فئة 2 ₪ — كم تساويان معًا؟", correctAnswer: "7 ₪", distractors: ["3 ₪", "6 ₪", "10 ₪"], grades: 2...3),
        BankQuestion(prompt: "🧺\nأعطتك أمّك 10 ₪ للفواكه فقط. ما الصواب أن تفعل؟", correctAnswer: "أن تشتري بها فاكهة", distractors: ["أن تشتري بها لعبة", "أن تشتري بها حلويات", "أن تخبّئ المال"], grades: 3...4),
        BankQuestion(prompt: "🍭\nالمصّاصة ثمنها 1 ₪. كم تكلّف أربع مصّاصات؟", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "5 ₪"], grades: 2...3),
        BankQuestion(prompt: "💝\nصديقتك لا تملك مالًا للعصير وعندك أكثر منها قليلًا. ما اللطيف أن تفعل؟", correctAnswer: "أن تشاركها وتشتري عصيرًا لكليكما", distractors: ["أن تشتري عصيرًا لنفسك فقط", "أن تحتفظ بالمال للغد", "أن تشتري لنفسك عصيرًا أكبر"], grades: 3...4),
        BankQuestion(prompt: "🪙\nكم قطعة نقديّة من فئة 1 ₪ تساوي قطعة من فئة 2 ₪؟", correctAnswer: "قطعتان", distractors: ["قطعة واحدة", "3 قطع", "5 قطع"], grades: 1...2),
        BankQuestion(prompt: "🛒\nمعك 8 ₪ واشتريت شيئًا بـ3 ₪. كم بقي معك؟", correctAnswer: "5 ₪", distractors: ["3 ₪", "4 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "💡\nما معنى ادّخار المال؟", correctAnswer: "أن نحفظ قليلًا من المال بدل أن نصرف كلّ شيء", distractors: ["أن نصرف كلّ شيء بسرعة", "أن نعطي كلّ المال", "أن نضيّع المال"], grades: 4...6),
        BankQuestion(prompt: "🎪\nتذكرة العرض ثمنها 9 ₪ ودفعت بـ10 ₪. كم الباقي؟", correctAnswer: "1 ₪", distractors: ["2 ₪", "3 ₪", "0 ₪"], grades: 3...4),
        BankQuestion(prompt: "⚖️\nما الأولى بالشراء حين يكون المال قليلًا؟", correctAnswer: "شيء نحتاج إليه فعلًا", distractors: ["شيء نرغب فيه للحظة فقط", "أغلى شيء في المتجر", "لا شيء أبدًا"], grades: 4...6),
        BankQuestion(prompt: "كم أغورة في الشاقل الواحد؟", correctAnswer: "100", distractors: ["10", "50", "1000"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي النقود المستعملة في إسرائيل؟", correctAnswer: "الشاقل", distractors: ["الدولار", "اليورو", "الين"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي قيمته أكبر؟", correctAnswer: "10 شواقل", distractors: ["5 شواقل", "2 شاقل", "1 شاقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي قيمته أكبر؟", correctAnswer: "5 شواقل", distractors: ["2 شاقل", "1 شاقل", "نصف شاقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أيّ قطعة نقديّة قيمتها أصغر؟", correctAnswer: "1 شاقل", distractors: ["10 شواقل", "5 شواقل", "2 شاقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ماذا نسمّي العلبة التي نحفظ فيها المال؟", correctAnswer: "حصّالة", distractors: ["ثلّاجة", "صندوق أدوات", "قِدر"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "كم شاقلًا تساوي القطعة النقديّة من فئة شاقلين؟", correctAnswer: "2", distractors: ["1", "5", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ماذا يمكن أن نشتري بالمال؟", correctAnswer: "الخبز", distractors: ["الشمس", "الهواء", "المطر"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ نقود هي ورقة وليست قطعة معدنيّة؟", correctAnswer: "20 شاقلًا", distractors: ["1 شاقل", "5 شواقل", "10 شواقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أيّ نقود هي قطعة معدنيّة؟", correctAnswer: "5 شواقل", distractors: ["50 شاقلًا", "100 شاقل", "200 شاقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "كم شاقلًا تساوي الورقة النقديّة من فئة خمسين؟", correctAnswer: "50", distractors: ["5", "15", "500"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي قيمته أكبر؟", correctAnswer: "100 شاقل", distractors: ["50 شاقلًا", "20 شاقلًا", "10 شواقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "إذا كان شيء يكلّف 2 شاقل وشيء آخر يكلّف 5 شواقل، فأيّهما أرخص؟", correctAnswer: "الذي ثمنه 2 شاقل", distractors: ["الذي ثمنه 5 شواقل", "كلاهما متساويان", "لا يمكن أن نعرف"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما معنى \"أن ندّخر\"؟", correctAnswer: "أن نحفظ المال للمستقبل", distractors: ["أن نصرف كلّ شيء فورًا", "أن نضيّع المال", "أن نرمي المال"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "كم شاقلًا تساوي الورقة النقديّة من فئة مئة؟", correctAnswer: "100", distractors: ["10", "1000", "50"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أيّ شيء نحتاج إليه فعلًا (حاجة)؟", correctAnswer: "الطعام", distractors: ["لعبة إضافيّة", "ملصقات", "حلوى"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ شيء هو رغبة فقط (وليس ضرورة)؟", correctAnswer: "لعبة جديدة", distractors: ["الطعام", "الماء", "الثياب"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أين نحفظ المال بأمان لمدّة طويلة؟", correctAnswer: "في البنك", distractors: ["في الشارع", "في سلّة المهملات", "في الثلّاجة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الذي قيمته أكبر؟", correctAnswer: "2 شاقل", distractors: ["1 شاقل", "نصف شاقل", "10 أغورات"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "كم شاقلًا تساوي الورقة النقديّة من فئة عشرين؟", correctAnswer: "20", distractors: ["2", "200", "12"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ماذا نفعل في المتجر لنحصل على منتج؟", correctAnswer: "ندفع المال", distractors: ["نأخذه دون أن ندفع", "نطلبه هديّة دائمًا", "نرمي المال"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ ورقة نقديّة هي الأكبر قيمة في إسرائيل؟", correctAnswer: "200 شاقل", distractors: ["100 شاقل", "50 شاقلًا", "20 شاقلًا"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "إذا كان معك 1 شاقل، فكم أغورة يساوي؟", correctAnswer: "100", distractors: ["1", "10", "50"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الأرخص؟", correctAnswer: "شيء ثمنه 3 شواقل", distractors: ["شيء ثمنه 8 شواقل", "شيء ثمنه 10 شواقل", "شيء ثمنه 6 شواقل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ قطعة نقديّة قيمتها الأكبر؟", correctAnswer: "10 شواقل", distractors: ["5 شواقل", "2 شاقل", "1 شاقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما هو السعر؟", correctAnswer: "كم من المال يكلّف الشيء", distractors: ["لون الشيء", "حجم الشيء", "وزن الشيء"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "إذا دفعت 10 شواقل ثمن شيء يكلّف 9 شواقل، فكم سيكون الباقي؟", correctAnswer: "1 شاقل", distractors: ["2 شاقل", "5 شواقل", "9 شواقل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي المال القليل الذي نستردّه بعد الدفع؟", correctAnswer: "الباقي", distractors: ["الغرامة", "الهديّة", "الدَّين"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الأهمّ أن نشتريه أوّلًا؟", correctAnswer: "الطعام", distractors: ["الملصقات", "البالون", "اللعبة"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "كم قطعة نقديّة من فئة 1 شاقل نحتاج لنصل إلى 2 شاقل؟", correctAnswer: "قطعتان", distractors: ["قطعة واحدة", "3 قطع", "5 قطع"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ما الذي قيمته أكبر؟", correctAnswer: "ورقة من فئة 20 شاقلًا", distractors: ["قطعة من فئة 10 شواقل", "قطعة من فئة 5 شواقل", "قطعة من فئة 2 شاقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أيّ نقود مصنوعة من الورق؟", correctAnswer: "ورقة من فئة 50 شاقلًا", distractors: ["قطعة من فئة 1 شاقل", "قطعة من فئة 2 شاقل", "قطعة من فئة 10 شواقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "إذا اشتريت حلوى بشاقل واحد من أصل 2 شاقل، فكم بقي معك؟", correctAnswer: "1 شاقل", distractors: ["2 شاقل", "3 شواقل", "0 شاقل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا يُستحسن أن نفعل بمال حصلنا عليه هديّة؟", correctAnswer: "أن ندّخر جزءًا منه", distractors: ["أن نضيّعه", "أن نرميه", "أن نمزّقه"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نفعل في الحصّالة؟", correctAnswer: "نجمع المال", distractors: ["نطبخ الطعام", "نخبّئ الأحذية", "نحفظ الألعاب"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ قطعة نقديّة قيمتها أصغر؟", correctAnswer: "نصف شاقل", distractors: ["1 شاقل", "2 شاقل", "5 شواقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "كم شاقلًا تساوي القطعة النقديّة من فئة خمسة شواقل؟", correctAnswer: "5", distractors: ["1", "2", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ماذا يمكن أن نفعل إذا لم يكن المال كافيًا لشراء لعبة الآن؟", correctAnswer: "أن ندّخر حتّى يصبح المبلغ كافيًا", distractors: ["أن نأخذها دون أن ندفع", "أن نغضب ونبكي", "أن نتنازل عن الطعام"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ شيء لا غنى لنا عنه (حاجة)؟", correctAnswer: "ماء للشرب", distractors: ["لعبة جديدة", "مقطع في الهاتف", "ملصقات"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا نسمّي المكان الذي نشتري منه المنتجات؟", correctAnswer: "المتجر", distractors: ["حديقة الحيوانات", "المدرسة", "ملعب الأطفال"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "كم أغورة في نصف شاقل؟", correctAnswer: "50", distractors: ["10", "100", "5"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا يُستحسن أن نفعل قبل أن نشتري شيئًا؟", correctAnswer: "أن نتحقّق كم يكلّف", distractors: ["أن نشتري دون أن ننظر", "ألّا نعرف السعر", "أن ندفع مرّتين"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "إذا كان معك ورقة من فئة 100 شاقل، فماذا تقول عن هذا المبلغ؟", correctAnswer: "إنّه مبلغ كبير", distractors: ["إنّه مبلغ صغير جدًّا", "إنّه لا شيء", "إنّه أقلّ من شاقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "ما الذي قيمته أكبر؟", correctAnswer: "1 شاقل", distractors: ["50 أغورة", "10 أغورات", "20 أغورة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "أيّ نقود قيمتها الأكبر؟", correctAnswer: "ورقة من فئة 50 شاقلًا", distractors: ["ورقة من فئة 20 شاقلًا", "قطعة من فئة 10 شواقل", "قطعة من فئة 5 شواقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "إذا دفعت 5 شواقل ثمن شيء يكلّف 4 شواقل، فكم الباقي؟", correctAnswer: "1 شاقل", distractors: ["2 شاقل", "4 شواقل", "5 شواقل"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا تعني كلمة \"غالٍ\"؟", correctAnswer: "أنّه يكلّف مالًا كثيرًا", distractors: ["أنّه يكلّف مالًا قليلًا", "أنّه لا يكلّف شيئًا", "أنّه صغير الحجم"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "ماذا تعني كلمة \"رخيص\"؟", correctAnswer: "أنّه يكلّف مالًا قليلًا", distractors: ["أنّه يكلّف مالًا كثيرًا", "أنّه مكسور", "أنّه كبير جدًّا"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "أيّ قطعة نقديّة قيمتها الأقلّ؟", correctAnswer: "10 أغورات", distractors: ["1 شاقل", "2 شاقل", "5 شواقل"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "كم قطعة نقديّة من فئة 1 شاقل نحتاج لنصل إلى 5 شواقل؟", correctAnswer: "5 قطع", distractors: ["قطعتان", "3 قطع", "10 قطع"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "دفعت 10 شواقل ثمن شيء يكلّف 7 شواقل — كم سيكون الباقي؟", correctAnswer: "3 شواقل", distractors: ["2 شاقل", "4 شواقل", "7 شواقل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا قطعة من فئة 5 شواقل وقطعة من فئة 2 شاقل؟", correctAnswer: "7 شواقل", distractors: ["3 شواقل", "10 شواقل", "52 شاقلًا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "كم قطعة نقديّة من فئة 2 شاقل نحتاج لنصل إلى 10 شواقل؟", correctAnswer: "5 قطع", distractors: ["قطعتان", "4 قطع", "10 قطع"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "كم قطعة نقديّة من فئة 5 شواقل تساوي معًا 10 شواقل؟", correctAnswer: "قطعتان", distractors: ["قطعة واحدة", "3 قطع", "5 قطع"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "دفعت 20 شاقلًا ثمن شيء يكلّف 15 شاقلًا — كم الباقي؟", correctAnswer: "5 شواقل", distractors: ["3 شواقل", "10 شواقل", "15 شاقلًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "معك 8 شواقل وتريد شراء شيء بـ10 شواقل. كم ينقصك؟", correctAnswer: "2 شاقل", distractors: ["1 شاقل", "3 شواقل", "8 شواقل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا قطعتان نقديّتان من فئة 10 شواقل؟", correctAnswer: "20 شاقلًا", distractors: ["10 شواقل", "15 شاقلًا", "100 شاقل"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "كم قطعة نقديّة من فئة 1 شاقل تساوي معًا قطعة من فئة 10 شواقل؟", correctAnswer: "10 قطع", distractors: ["5 قطع", "قطعتان", "20 قطعة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "اشتريت شيئين: واحدًا بـ3 شواقل وآخر بـ4 شواقل. كم دفعت في المجموع؟", correctAnswer: "7 شواقل", distractors: ["1 شاقل", "6 شواقل", "12 شاقلًا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ماذا يُستحسن أن نفعل إذا أردنا شراء شيء غالٍ في المستقبل؟", correctAnswer: "أن ندّخر قليلًا من المال في كلّ مرّة", distractors: ["أن نصرف كلّ شيء فورًا", "ألّا ندّخر أبدًا", "أن نشتري أشياء أخرى"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ ممّا يلي \"حاجة\" وليس مجرّد \"رغبة\"؟", correctAnswer: "دواء عند المرض", distractors: ["لعبة حاسوب جديدة", "كتاب تلوين إضافيّ", "قبّعة أخرى بلون مختلف"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا قطعة من فئة 10 شواقل وقطعة من فئة 5 شواقل؟", correctAnswer: "15 شاقلًا", distractors: ["5 شواقل", "20 شاقلًا", "50 شاقلًا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "إذا كان شيء يكلّف 12 شاقلًا ودفعت بورقة من فئة 20، فكم الباقي؟", correctAnswer: "8 شواقل", distractors: ["2 شاقل", "12 شاقلًا", "20 شاقلًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ مجموعة قطع نقديّة تساوي 7 شواقل؟", correctAnswer: "5 شواقل و2 شاقل", distractors: ["5 شواقل و5 شواقل", "10 شواقل و2 شاقل", "2 شاقل و2 شاقل"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "معك 6 شواقل وحصلت على 4 شواقل إضافيّة. كم صار معك الآن؟", correctAnswer: "10 شواقل", distractors: ["2 شاقل", "8 شواقل", "14 شاقلًا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما الأرخص: شيء بـ15 شاقلًا أم شيء بـ12 شاقلًا؟", correctAnswer: "الذي ثمنه 12 شاقلًا", distractors: ["الذي ثمنه 15 شاقلًا", "كلاهما متساويان", "لا يمكن أن نعرف"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "كم قطعة نقديّة من فئة شيكلين تساوي معًا 6 شواكل؟", correctAnswer: "3", distractors: ["2", "4", "6"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "دفعتَ 50 شيكلًا ثمنًا لشيء سعره 45 شيكلًا — كم الباقي؟", correctAnswer: "5 شواكل", distractors: ["3 شواكل", "10 شواكل", "45 شيكلًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا ورقة من فئة 20 شيكلًا وقطعة من فئة 10 شواكل؟", correctAnswer: "30 شيكلًا", distractors: ["20 شيكلًا", "25 شيكلًا", "210 شواكل"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "إذا ادّخرتَ شيكلين كلّ يوم، فكم تدّخر بعد 3 أيّام؟", correctAnswer: "6 شواكل", distractors: ["شيكلان", "5 شواكل", "23 شيكلًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما أفضل نصيحة عند تلقّي مصروف الجيب؟", correctAnswer: "أن تُنفق قليلًا وتدّخر قليلًا", distractors: ["أن تبذّره كلّه فورًا", "ألّا تستعمله أبدًا", "أن تُضيعه"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كم شيكلًا تساوي ورقة من فئة 20 شيكلًا مع قطعة من فئة 5 شواكل؟", correctAnswer: "25 شيكلًا", distractors: ["15 شيكلًا", "20 شيكلًا", "30 شيكلًا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "معك 10 شواكل. اشتريتَ شيئًا بـ 6 شواكل. كم بقي معك؟", correctAnswer: "4 شواكل", distractors: ["3 شواكل", "6 شواكل", "16 شيكلًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ماذا يجدر بك أن تقارن قبل أن تشتري المنتج نفسه من متجرَين؟", correctAnswer: "السعر", distractors: ["لون المتجر", "الساعة", "حالة الطقس"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كم قطعة من فئة نصف شيكل نحتاج للوصول إلى شيكل واحد؟", correctAnswer: "2", distractors: ["1", "5", "10"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "اشتريتَ ثلاثة أشياء ثمن كلّ واحد منها شيكلان. كم دفعتَ؟", correctAnswer: "6 شواكل", distractors: ["شيكلان", "5 شواكل", "8 شواكل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّهما أغلى: شيئان ثمن كلّ واحد منهما 5 شواكل، أم شيء واحد بـ 8 شواكل؟", correctAnswer: "الشيئان معًا", distractors: ["الشيء الذي بـ 8 شواكل", "الاثنان متساويان في الثمن", "لا يمكن معرفة ذلك"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "دفعتَ 100 شيكل ثمنًا لشيء سعره 90 شيكلًا — كم الباقي؟", correctAnswer: "10 شواكل", distractors: ["5 شواكل", "20 شيكلًا", "90 شيكلًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ مجموعة من القطع النقديّة تساوي 12 شيكلًا؟", correctAnswer: "10 شواكل وشيكلان", distractors: ["5 شواكل و5 شواكل", "10 شواكل و10 شواكل", "شيكلان وشيكلان"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "كم ورقة من فئة 20 شيكلًا تساوي معًا 100 شيكل؟", correctAnswer: "5", distractors: ["2", "4", "10"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "معك 14 شيكلًا، وأنفقتَ 4 شواكل. كم بقي؟", correctAnswer: "10 شواكل", distractors: ["8 شواكل", "12 شيكلًا", "18 شيكلًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ما معنى «الميزانيّة»؟", correctAnswer: "خطّة تحدّد كم من المال يمكن أن نُنفق", distractors: ["نوع من القطع النقديّة", "متجر كبير", "لعبة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "إذا كانت ميزانيّتك 10 شواكل، فكم يمكنك أن تُنفق منها؟", correctAnswer: "حتى 10 شواكل", distractors: ["20 شيكلًا", "50 شيكلًا", "100 شيكل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا ثلاث قطع من فئة شيكلين؟", correctAnswer: "6 شواكل", distractors: ["شيكلان", "5 شواكل", "8 شواكل"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "ما الأفضل لمن يريد أن يدّخر؟", correctAnswer: "أن يشتري ما يحتاج إليه حقًّا فقط", distractors: ["أن يشتري كلّ ما يراه", "أن يبذّر ماله على كلّ شيء", "ألّا يحفظ مالًا أبدًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كم يكون الباقي من 5 شواكل إذا اشتريتَ شيئًا بشيكلين؟", correctAnswer: "3 شواكل", distractors: ["شيكل واحد", "شيكلان", "5 شواكل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا قطعة من فئة شيكلين وقطعة من فئة شيكل واحد؟", correctAnswer: "3 شواكل", distractors: ["شيكل واحد", "شيكلان", "21 شيكلًا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "إذا ادّخرتَ 5 شواكل في الأسبوع الأوّل و5 شواكل في الأسبوع الثاني، فكم ادّخرتَ؟", correctAnswer: "10 شواكل", distractors: ["5 شواكل", "15 شيكلًا", "55 شيكلًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "شيء ثمنه 18 شيكلًا. دفعتَ بورقة من فئة 20. كم الباقي؟", correctAnswer: "شيكلان", distractors: ["شيكل واحد", "3 شواكل", "18 شيكلًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "أيّ مجموعة تساوي 15 شيكلًا؟", correctAnswer: "10 شواكل و5 شواكل", distractors: ["10 شواكل و10 شواكل", "5 شواكل و5 شواكل", "شيكلان و5 شواكل"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "كم تساوي معًا ورقتان من فئة 50 شيكلًا؟", correctAnswer: "100 شيكل", distractors: ["50 شيكلًا", "150 شيكلًا", "500 شيكل"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "معك 20 شيكلًا واشتريتَ كتابًا بـ 13 شيكلًا. كم بقي؟", correctAnswer: "7 شواكل", distractors: ["3 شواكل", "13 شيكلًا", "33 شيكلًا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "ماذا يجدر بك أن تفعل قبل أن تشتري لعبة غالية؟", correctAnswer: "أن تسأل نفسك إن كنتَ تحتاج إليها حقًّا", distractors: ["أن تشتريها دون تفكير", "أن تشتري اثنتين منها", "أن تتجاهل السعر"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "كم قطعة نقديّة من فئة شيكل واحد تساوي قطعة من فئة خمسة شواكل؟", correctAnswer: "5", distractors: ["2", "3", "10"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "كم أغورة يجب أن تُضيف إلى خمسين أغورة للوصول إلى شيكل كامل؟", correctAnswer: "50", distractors: ["10", "100", "5"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "شيء ثمنه 23 شيكلًا ودفعتَ بورقة من فئة 50 شيكلًا — كم الباقي؟", correctAnswer: "27 شيكلًا", distractors: ["17 شيكلًا", "23 شيكلًا", "37 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا ورقة من فئة 50 شيكلًا وقطعة من فئة 10 شواكل وقطعة من فئة 5 شواكل؟", correctAnswer: "65 شيكلًا", distractors: ["55 شيكلًا", "60 شيكلًا", "70 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "تدّخر 5 شواكل كلّ أسبوع. كم تدّخر بعد 4 أسابيع؟", correctAnswer: "20 شيكلًا", distractors: ["10 شواكل", "15 شيكلًا", "25 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "اشتريتَ شيئين: واحدًا بـ 12 شيكلًا وآخر بـ 13 شيكلًا. كم دفعتَ؟", correctAnswer: "25 شيكلًا", distractors: ["15 شيكلًا", "23 شيكلًا", "35 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "شيء ثمنه 35 شيكلًا ودفعتَ بورقة من فئة 50 — كم الباقي؟", correctAnswer: "15 شيكلًا", distractors: ["5 شواكل", "10 شواكل", "25 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "معك 30 شيكلًا ولعبة ثمنها 45 شيكلًا. كم ينقصك؟", correctAnswer: "15 شيكلًا", distractors: ["10 شواكل", "20 شيكلًا", "45 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كم ورقة من فئة 50 شيكلًا تساوي معًا 200 شيكل؟", correctAnswer: "4", distractors: ["2", "3", "5"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "اشتريتَ 4 دفاتر بـ 5 شواكل للدفتر الواحد. كم دفعتَ؟", correctAnswer: "20 شيكلًا", distractors: ["9 شواكل", "15 شيكلًا", "25 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "شيء ثمنه 64 شيكلًا ودفعتَ بورقة من فئة 100 — كم الباقي؟", correctAnswer: "36 شيكلًا", distractors: ["26 شيكلًا", "46 شيكلًا", "64 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "تريد أن تشتري شيئًا بـ 60 شيكلًا، ومعك 25 شيكلًا. كم يلزمك أن تدّخر بعد؟", correctAnswer: "35 شيكلًا", distractors: ["25 شيكلًا", "30 شيكلًا", "45 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا ورقتان من فئة 20 شيكلًا وقطعة من فئة 10 شواكل؟", correctAnswer: "50 شيكلًا", distractors: ["40 شيكلًا", "45 شيكلًا", "60 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما الأفضل لمن يدّخر للمستقبل؟", correctAnswer: "أن يضع جزءًا من ماله جانبًا في كلّ مرّة", distractors: ["أن يُنفق كلّ ماله في يوم واحد", "ألّا يدّخر أبدًا", "أن يشتري أشياء لا يحتاج إليها"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "معك 40 شيكلًا. أنفقتَ 18 شيكلًا. كم بقي؟", correctAnswer: "22 شيكلًا", distractors: ["12 شيكلًا", "28 شيكلًا", "32 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كم أغورة في شيكلين؟", correctAnswer: "200", distractors: ["20", "100", "2"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "أيّ مجموعة من النقود تساوي 70 شيكلًا؟", correctAnswer: "50 شيكلًا و20 شيكلًا", distractors: ["50 شيكلًا و10 شواكل", "20 شيكلًا و20 شيكلًا", "100 شيكل و20 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "اشتريتَ 3 قناني ماء بـ 4 شواكل للقنينة الواحدة. كم دفعتَ؟", correctAnswer: "12 شيكلًا", distractors: ["7 شواكل", "9 شواكل", "16 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "تدّخر 10 شواكل في الشهر. كم تدّخر بعد 3 أشهر؟", correctAnswer: "30 شيكلًا", distractors: ["13 شيكلًا", "20 شيكلًا", "300 شيكل"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "شيء ثمنه 48 شيكلًا. دفعتَ بورقة من فئة 50 — كم الباقي؟", correctAnswer: "شيكلان", distractors: ["شيكل واحد", "5 شواكل", "48 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا ورقة من فئة 100 شيكل وورقة من فئة 50 شيكلًا؟", correctAnswer: "150 شيكلًا", distractors: ["105 شواكل", "140 شيكلًا", "200 شيكل"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "معك 100 شيكل. اشتريتَ حذاءً بـ 75 شيكلًا. كم بقي؟", correctAnswer: "25 شيكلًا", distractors: ["15 شيكلًا", "20 شيكلًا", "35 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما الطريقة الذكيّة لتقسيم مصروف جيب قدره 10 شواكل؟", correctAnswer: "جزء للإنفاق وجزء للادّخار", distractors: ["كلّه فورًا على الحلويات", "ألّا نمسّه أبدًا", "أن نُضيعه"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "اشتريتَ 5 ملصقات بشيكلين للملصق الواحد. كم دفعتَ؟", correctAnswer: "10 شواكل", distractors: ["7 شواكل", "12 شيكلًا", "15 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "شيء ثمنه 88 شيكلًا ودفعتَ بورقة من فئة 100 — كم الباقي؟", correctAnswer: "12 شيكلًا", distractors: ["8 شواكل", "18 شيكلًا", "22 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "تريد دراجة هوائيّة ثمنها مئة وخمسون شيكلًا، وقد ادّخرتَ 100 شيكل. كم يلزمك بعد؟", correctAnswer: "50 شيكلًا", distractors: ["40 شيكلًا", "60 شيكلًا", "100 شيكل"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا ثلاث قطع من فئة 10 شواكل؟", correctAnswer: "30 شيكلًا", distractors: ["13 شيكلًا", "20 شيكلًا", "40 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "معك 50 شيكلًا. اشتريتَ هديّة بـ 32 شيكلًا. كم بقي؟", correctAnswer: "18 شيكلًا", distractors: ["12 شيكلًا", "22 شيكلًا", "28 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما الأفضل حين تريد أن تشتري شيئًا ولا يكفيك المال؟", correctAnswer: "أن تنتظر وتدّخر أكثر", distractors: ["أن تأخذه من المتجر دون أن تدفع", "أن تغضب على البائع", "أن تنسى كيف يُدَّخَر المال"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "أيّ مجموعة من النقود تساوي 120 شيكلًا؟", correctAnswer: "100 شيكل و20 شيكلًا", distractors: ["100 شيكل و10 شواكل", "50 شيكلًا و50 شيكلًا", "200 شيكل و20 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "شيء ثمنه 19 شيكلًا. اشتريتَ منه اثنين. كم دفعتَ؟", correctAnswer: "38 شيكلًا", distractors: ["21 شيكلًا", "29 شيكلًا", "40 شيكلًا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "تدّخر 3 شواكل كلّ يوم مدّة أسبوع (7 أيّام). كم ادّخرتَ؟", correctAnswer: "21 شيكلًا", distractors: ["10 شواكل", "18 شيكلًا", "24 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "كم تساوي معًا ورقة من فئة 200 شيكل وورقة من فئة 50 شيكلًا؟", correctAnswer: "250 شيكلًا", distractors: ["205 شواكل", "240 شيكلًا", "300 شيكل"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "معك 25 شيكلًا وحصلتَ على 15 شيكلًا إضافيًّا. كم معك الآن؟", correctAnswer: "40 شيكلًا", distractors: ["10 شواكل", "30 شيكلًا", "45 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "شيء ثمنه 55 شيكلًا ودفعتَ بورقة من فئة 100 — كم الباقي؟", correctAnswer: "45 شيكلًا", distractors: ["35 شيكلًا", "40 شيكلًا", "55 شيكلًا"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "ما أفضل نصيحة قبل عمليّة شراء كبيرة؟", correctAnswer: "مقارنة الأسعار في عدّة متاجر", distractors: ["الشراء دون مقارنة", "دفع أعلى سعر ممكن", "عدم السؤال عن السعر"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "كم قطعة نقديّة من فئة 10 شواكل تساوي ورقة من فئة خمسين شيكلًا؟", correctAnswer: "5", distractors: ["2", "4", "10"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "تريد تقسيم 30 شيكلًا بالتساوي بين الإنفاق والادّخار والعطاء. كم لكلّ قسم؟", correctAnswer: "10 شواكل", distractors: ["5 شواكل", "15 شيكلًا", "30 شيكلًا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "شيء ثمنه 14 شيكلًا. اشتريتَ منه ثلاثة. كم دفعتَ؟", correctAnswer: "42 شيكلًا", distractors: ["17 شيكلًا", "28 شيكلًا", "44 شيكلًا"], tier: .hard, grades: 4...6),
    ]
}
