import Foundation

/// 🇮🇱 إسرائيل — بالعربية. مأخوذ عن البنك العبريّ (70 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let israel: [BankQuestion] = [
        BankQuestion(prompt: "🏛️\nما هي عاصمة دولة إسرائيل؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "بئر السبع"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌧️\nفي أيّ فصل من فصول السنة تهطل معظم الأمطار في البلاد؟", correctAnswer: "الشتاء", distractors: ["الصيف", "الخريف", "الربيع"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐪\nأيّ حيوان يستطيع السير أيّامًا في صحراء النقب من دون أن يشرب؟", correctAnswer: "الجمل", distractors: ["الفيل", "الدبّ القطبيّ", "البطريق"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🪙\nكم أغورة في الشيكل الواحد؟", correctAnswer: "100", distractors: ["10", "50", "1000"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏰\nأيّ مدينة ساحليّة في الشمال تشتهر بأسوارها ومدينتها القديمة المدرجة في قائمة التراث العالميّ؟", correctAnswer: "عكّا", distractors: ["إيلات", "بئر السبع", "طبريا"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌲\nعلى أيّ جبل يقع أكبر متنزّه وطنيّ حرجيّ في البلاد؟", correctAnswer: "جبل الكرمل", distractors: ["جبل طابور", "جبل الجرمق", "جبل الحرمون"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏛️\nكم عضوًا يجلس في الكنيست، برلمان إسرائيل؟", correctAnswer: "120", distractors: ["60", "100", "200"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐦\nما هو الطائر الوطنيّ لإسرائيل؟", correctAnswer: "الهدهد", distractors: ["الحمامة", "النسر", "الببغاء"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌸\nما هي الزهرة الوطنيّة لإسرائيل؟", correctAnswer: "شقائق النعمان", distractors: ["الوردة", "عبّاد الشمس", "النرجس"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🪙\nما اسم العملة التي يُدفع بها في إسرائيل؟", correctAnswer: "الشيكل", distractors: ["الدولار", "اليورو", "الليرة"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕎\nفي أيّ عيد يهوديّ يُشعلون شمعدانًا من ثماني شمعات ويلعبون بالخُذروف؟", correctAnswer: "عيد حانوكا", distractors: ["عيد بوريم", "عيد الفصح", "عيد المظالّ"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍩\nأيّ حلوى مقليّة تُؤكل في عيد حانوكا؟", correctAnswer: "السفغانيّة (دونات)", distractors: ["أذان هامان", "خبز الفطير (متسا)", "التفّاح بالعسل"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎭\nفي أيّ عيد يهوديّ يرتدي الأولاد أزياء تنكّريّة؟", correctAnswer: "عيد بوريم", distractors: ["عيد حانوكا", "عيد الأسابيع", "عيد الفصح"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍪\nأيّ كعكة مثلّثة الشكل تُؤكل في عيد بوريم؟", correctAnswer: "أذان هامان", distractors: ["السفغانيّة", "فطائر البطاطا المقليّة", "خبز الفطير (متسا)"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🫓\nفي أيّ عيد يهوديّ يُؤكل خبز الفطير بدل الخبز العاديّ؟", correctAnswer: "عيد الفصح", distractors: ["عيد المظالّ", "عيد حانوكا", "عيد بوريم"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍎\nفي أيّ مناسبة يهوديّة يُغمس التفّاح بالعسل؟", correctAnswer: "رأس السنة العبريّة", distractors: ["عيد بوريم", "عيد الفصح", "تو بشفاط"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🛖\nفي أيّ عيد يهوديّ يُبنى كوخ من السعف ويجلسون فيه؟", correctAnswer: "عيد المظالّ (سوكوت)", distractors: ["عيد الفصح", "عيد حانوكا", "عيد الأسابيع"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌳\nفي أيّ مناسبة يهوديّة تُغرَس الشتلات والأشجار؟", correctAnswer: "تو بشفاط", distractors: ["عيد بوريم", "عيد المظالّ", "عيد حانوكا"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏙️\nأيّ مدينة هي كبرى المدن العربيّة في إسرائيل؟", correctAnswer: "الناصرة", distractors: ["عكّا", "طبريا", "صفد"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⚓\nأيّ مدينة ساحليّة عريقة اشتهرت بمينائها منذ آلاف السنين وتقع جنوبيّ تل أبيب؟", correctAnswer: "يافا", distractors: ["صفد", "بئر السبع", "طبريا"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌊\nأيّ بحر يقع قرب تل أبيب وحيفا؟", correctAnswer: "البحر المتوسّط", distractors: ["البحر الميت", "البحر الأحمر", "بحيرة طبريا"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏖️\nأيّ مدينة تقع في أقصى جنوب البلاد على شاطئ البحر الأحمر؟", correctAnswer: "إيلات", distractors: ["حيفا", "نهاريا", "طبريا"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧂\nفي أيّ بحر تكون المياه مالحة جدًّا حتّى يطفو فيها الإنسان بلا جهد؟", correctAnswer: "البحر الميت", distractors: ["البحر المتوسّط", "بحيرة طبريا", "البحر الأحمر"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏜️\nما اسم الصحراء الكبيرة في جنوب البلاد؟", correctAnswer: "النقب", distractors: ["الكرمل", "الجليل", "منطقة الشارون"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⛷️\nعلى أيّ جبل يقع موقع التزلّج الوحيد في إسرائيل؟", correctAnswer: "جبل الحرمون", distractors: ["جبل الكرمل", "جبل طابور", "جبل الزيتون"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⛰️\nأيّ مدينة مبنيّة على جبل الكرمل؟", correctAnswer: "حيفا", distractors: ["تل أبيب", "إيلات", "بئر السبع"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏙️\nما هي المدينة الكبرى في النقب؟", correctAnswer: "بئر السبع", distractors: ["إيلات", "حيفا", "نتانيا"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏺\nفي أيّ مدينة أثريّة على ساحل البحر المتوسّط يقف مدرّج رومانيّ قديم ما زالت تُقام فيه الحفلات؟", correctAnswer: "قيصاريّة", distractors: ["صفد", "بئر السبع", "طبريا"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏙️\nأيّ مدينة تُلقَّب بـ«المدينة البيضاء» بفضل مبانيها البيضاء؟", correctAnswer: "تل أبيب", distractors: ["حيفا", "القدس", "إيلات"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐠\nأيّ مدينة تشتهر بشعابها المرجانيّة وأسماكها الملوّنة؟", correctAnswer: "إيلات", distractors: ["حيفا", "طبريا", "أسدود"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍊\nأيّ فاكهة مشهورة في العالم سُمّيت باسم مدينة يافا؟", correctAnswer: "البرتقال", distractors: ["الموز", "التفّاح", "البطّيخ"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛥️\nأيّ مدينة تقع على شاطئ البحيرة الكبيرة في الجليل؟", correctAnswer: "طبريا", distractors: ["صفد", "نهاريا", "عكّا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🎨\nأيّ مدينة في الجليل تشتهر بأزقّتها القديمة وبمعارض الفنّانين فيها؟", correctAnswer: "صفد", distractors: ["بئر السبع", "إيلات", "حولون"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏛️\nفي أيّ مدينة يقع مبنى الكنيست؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "بئر السبع"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏰\nما اسم القلعة الأثريّة على قمّة جبل قرب البحر الميت، التي يُصعد إليها بالتلفريك أو سيرًا في «درب الأفعى»؟", correctAnswer: "مسادا", distractors: ["رأس الناقورة", "قيصاريّة", "برج داود"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌊\nأين تقع المغاور البيضاء التي نحتها البحر في الصخر، في أقصى شمال ساحل البلاد؟", correctAnswer: "رأس الناقورة", distractors: ["إيلات", "مسادا", "يافا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🕳️\nفي أيّ منطقة يقع مكتيش رامون؟", correctAnswer: "في النقب", distractors: ["في الجليل", "في الكرمل", "في الشارون"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🗺️\nالبحر المتوسّط، البحر الميت، البحر الأحمر وبحيرة طبريا — كم مسطّحًا مائيًّا كبيرًا في إسرائيل؟", correctAnswer: "4", distractors: ["2", "3", "5"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🚰\nأيّ مسطّح مائيّ في إسرائيل هو بحيرة مياه عذبة صالحة للشرب؟", correctAnswer: "بحيرة طبريا", distractors: ["البحر الميت", "البحر المتوسّط", "البحر الأحمر"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧭\nفي أيّ جهة من البلاد يقع البحر الميت؟", correctAnswer: "في الشرق", distractors: ["في الغرب", "في الشمال", "في الجنوب"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏞️\nما اسم النهر الذي يجري من بحيرة طبريا إلى البحر الميت؟", correctAnswer: "نهر الأردنّ", distractors: ["نهر الياركون", "نهر المقطّع", "نهر النيل"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📉\nأيّ مكان في إسرائيل هو الأخفض في العالم على سطح اليابسة؟", correctAnswer: "البحر الميت", distractors: ["بحيرة طبريا", "النقب", "إيلات"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏔️\nما هو أعلى جبل في إسرائيل؟", correctAnswer: "جبل الحرمون", distractors: ["جبل الكرمل", "جبل الجلبوع", "جبل طابور"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌍\nفي أيّ قارّة تقع إسرائيل؟", correctAnswer: "آسيا", distractors: ["أوروبّا", "أفريقيا", "أمريكا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🪶\nأيّ محميّة في الجليل الأعلى تشتهر بآلاف طيور الكركيّ التي تقضي الشتاء فيها؟", correctAnswer: "محميّة الحولة", distractors: ["مكتيش رامون", "البحر الميت", "رأس الناقورة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦌\nأيّ حيوان ذو قرون معقوفة يتسلّق الصخور في عين جدي؟", correctAnswer: "الوعل", distractors: ["الحمار الوحشيّ", "الفيل", "الدبّ"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌺\nما لون معظم شقائق النعمان التي تملأ سهول الجنوب في الشتاء؟", correctAnswer: "الأحمر", distractors: ["الأزرق", "الأصفر", "الأسود"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐦\nما المميّز في شكل الهدهد؟", correctAnswer: "عُرف من الريش على رأسه", distractors: ["ذيل طويل مثل ذيل الطاووس", "رقبة طويلة جدًّا", "أرجل ورديّة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧀\nفي أيّ عيد يهوديّ تُؤكل مأكولات الألبان ويُتزيَّن بأكاليل الزهور؟", correctAnswer: "عيد الأسابيع (شفوعوت)", distractors: ["عيد المظالّ", "عيد بوريم", "عيد حانوكا"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔥\nفي أيّ مناسبة يهوديّة تُشعل النيران في الليل؟", correctAnswer: "لاغ بعومير", distractors: ["عيد حانوكا", "عيد الفصح", "عيد الأسابيع"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📅\nفي أيّ سنة أُعلن قيام دولة إسرائيل؟", correctAnswer: "1948", distractors: ["1900", "1967", "2000"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👔\nمن كان أوّل رئيس حكومة في إسرائيل؟", correctAnswer: "دافيد بن غوريون", distractors: ["تيودور هرتسل", "حاييم فايتسمان", "غولدا مئير"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦊\nأيّ حيوان بريّ من فصيلة الكلاب ينتشر في أنحاء البلاد وينشط في الليل؟", correctAnswer: "ابن آوى", distractors: ["الأسد", "الفيل", "الدبّ القطبيّ"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚗\nأيّ تطبيق ملاحة مشهور طُوّر في إسرائيل؟", correctAnswer: "Waze", distractors: ["خرائط غوغل", "يوتيوب", "تيك توك"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍅\nأيّ نوع من الطماطم حظي بتطوير زراعيّ مهمّ في إسرائيل؟", correctAnswer: "الطماطم الكرزيّة", distractors: ["الطماطم الخضراء", "طماطم الحقل", "الطماطم البرّيّة"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "💧\nأيّ طريقة سقي توصل الماء قطرة قطرة إلى جذر النبتة، وقد طُوّرت في إسرائيل؟", correctAnswer: "الريّ بالتنقيط", distractors: ["الريّ بالرشّاشات", "الريّ بالدلاء", "الريّ بالخرطوم"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📖\nمن أعاد إحياء اللغة العبريّة وجعلها لغة محكيّة من جديد؟", correctAnswer: "إليعيزر بن يهودا", distractors: ["تيودور هرتسل", "دافيد بن غوريون", "حاييم نحمان بياليك"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💊\nأيّ اختراع طبّيّ إسرائيليّ هو كاميرا صغيرة بحجم حبّة الدواء تُبتلع لتصوير الأمعاء من الداخل؟", correctAnswer: "الكبسولة المصوّرة (PillCam)", distractors: ["جهاز تخطيط القلب", "المجهر الإلكترونيّ", "جهاز الأشعّة السينيّة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📜\nأين عُثر على مخطوطات البحر الميت الشهيرة؟", correctAnswer: "في كهوف قمران", distractors: ["في كهوف جبل الكرمل", "في أسوار عكّا", "في مدرّج قيصاريّة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏗️\nأيّ مدينة تأسّست عام 1909 وصارت اليوم من كبرى مدن البلاد؟", correctAnswer: "تل أبيب", distractors: ["حيفا", "ريشون لتسيون", "بتح تكفا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "👥\nأيّ مدينة هي الأكبر في إسرائيل من حيث عدد السكّان؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "ريشون لتسيون"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🚇\nفي أيّ مدينة يسير قطار «الكرمليت» تحت الأرض؟", correctAnswer: "حيفا", distractors: ["تل أبيب", "القدس", "بئر السبع"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏞️\nما اسم النهر الذي يجري عبر تل أبيب إلى البحر المتوسّط؟", correctAnswer: "نهر الياركون", distractors: ["نهر الأردنّ", "نهر المقطّع", "نهر النيل"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏜️\nأيّ جزء من مساحة دولة إسرائيل تشغله صحراء النقب؟", correctAnswer: "أكثر من النصف", distractors: ["أقلّ من العُشر", "نحو الرُّبع", "نحو الثلث"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🚰\nما اسم المشروع الكبير الذي ينقل المياه من بحيرة طبريا جنوبًا حتّى النقب؟", correctAnswer: "الناقل القطريّ", distractors: ["قناة السويس", "نهر الياركون", "سكّة الحديد القطريّة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌊\nما اسم العمليّة التي تُحوَّل بها مياه البحر إلى مياه شرب في إسرائيل؟", correctAnswer: "التحلية", distractors: ["التجميد", "الغليان", "الترشيح بالرمل"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💾\nأيّ جهاز صغير لتخزين الملفّات يُوصَل بالحاسوب طُوّر في إسرائيل؟", correctAnswer: "ذاكرة الفلاش (ديسك أون كي)", distractors: ["الفأرة", "الطابعة", "لوحة المفاتيح"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "☀️\nأيّ جهاز على سطوح البيوت في البلاد يسخّن الماء من دون كهرباء؟", correctAnswer: "السخّان الشمسيّ", distractors: ["المكيّف", "الهوائيّ (الأنتينا)", "الثلّاجة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌳\nأيّ شجرة اختيرت شجرة وطنيّة لإسرائيل؟", correctAnswer: "الزيتون", distractors: ["الصنوبر", "الكينا", "النخيل"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏘️\nكم عدد سكّان إسرائيل تقريبًا اليوم؟", correctAnswer: "نحو 10 ملايين", distractors: ["نحو نصف مليون", "نحو مليون واحد", "نحو 100 مليون"], tier: .hard, grades: 4...6),
    ]
}
