import Foundation

/// 🎵 الموسيقى — بالعربية. مأخوذ عن البنك العبريّ (70 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let music: [BankQuestion] = [
        BankQuestion(prompt: "🎸\nكم وترًا للجيتار العاديّ؟", correctAnswer: "6", distractors: ["4", "5", "8"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🎻\nكم وترًا للكمان؟", correctAnswer: "4", distractors: ["3", "5", "6"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🎹\nبأيّ لونين مفاتيح البيانو؟", correctAnswer: "أسود وأبيض", distractors: ["أحمر وأزرق", "أخضر وأصفر", "برتقاليّ وبنفسجيّ"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥁\nكيف نعزف على الطبل؟", correctAnswer: "نقرع عليه", distractors: ["ننفخ فيه", "نمرّ على أوتاره", "ندير مفاتيحه"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎸\nكيف نعزف على الجيتار؟", correctAnswer: "نداعب الأوتار بالأصابع", distractors: ["ننفخ فيه", "نقرعه بالعصيّ", "نضغط على مفاتيحه"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎻\nبماذا نمرّ على أوتار الكمان كي نعزف؟", correctAnswer: "بالقوس", distractors: ["بالمطرقة", "بعصا الطبل", "بالملعقة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎹\nفي أيّ آلة موسيقيّة نضغط على المفاتيح؟", correctAnswer: "البيانو", distractors: ["الطبل", "الكمان", "البوق"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪈\nفي أيّ آلة موسيقيّة ننفخ؟", correctAnswer: "الناي", distractors: ["الطبل", "الجيتار", "البيانو"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥁\nأيّ آلة من هذه هي آلة إيقاع؟", correctAnswer: "الطبل", distractors: ["الكمان", "الناي", "الجيتار"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪕\nأيّ آلة من هذه هي آلة وتريّة؟", correctAnswer: "العود", distractors: ["الطبل", "البوق", "الصنوج"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪘\nكيف نعزف على الدربكّة؟", correctAnswer: "نضرب عليها باليدين", distractors: ["ننفخ فيها", "نمرّ عليها بالقوس", "نضغط على مفاتيحها"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪈\nأيّ آلة نفخ صغيرة يتعلّم كثير من الأطفال العزف عليها في المدرسة؟", correctAnswer: "الريكوردر", distractors: ["البوق", "البيانو", "الكونترباص"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🎤\nما الذي يساعد المغنّي على أن يُسمَع بصوت أعلى؟", correctAnswer: "الميكروفون", distractors: ["النظّارات", "القبّعة", "عصا المايسترو"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎧\nماذا نسمّي مَن يعزف على آلة موسيقيّة؟", correctAnswer: "عازفًا", distractors: ["مغنّيًا", "رسّامًا", "حلّاقًا"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎵\nكم نغمة في السُّلَّم: دو، ري، مي، فا، صول، لا، سي؟", correctAnswer: "7", distractors: ["5", "8", "10"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🎵\nما النغمة الأولى في السُّلَّم؟", correctAnswer: "دو", distractors: ["ري", "صول", "سي"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎵\nأيّ نغمة تأتي مباشرة بعد «دو»؟", correctAnswer: "ري", distractors: ["مي", "فا", "لا"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎼\nماذا نسمّي العلامات التي تُكتب بها الموسيقى؟", correctAnswer: "النوتات الموسيقيّة", distractors: ["الحروف", "الأرقام", "النقاط"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔉\nما عكس الموسيقى الصاخبة؟", correctAnswer: "موسيقى هادئة", distractors: ["موسيقى سريعة", "موسيقى طويلة", "موسيقى مرحة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐇\nما عكس الموسيقى البطيئة؟", correctAnswer: "موسيقى سريعة", distractors: ["موسيقى صاخبة", "موسيقى هادئة", "موسيقى حزينة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎵\nما عكس النغمة العالية؟", correctAnswer: "نغمة منخفضة", distractors: ["نغمة قويّة", "نغمة سريعة", "نغمة طويلة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐦\nأيّ صوت من هذه هو الأعلى نغمةً؟", correctAnswer: "زقزقة عصفور", distractors: ["خُوار بقرة", "زئير أسد", "صوت التوبا"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "👏\nحين نصفّق مع الموسيقى، على أيّ شيء نصفّق؟", correctAnswer: "على الإيقاع", distractors: ["على اللون", "على الارتفاع", "على الطعم"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "👏\nصفّقنا مرّتين، ثمّ مرّتين أخريين. كم تصفيقة في المجموع؟", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🎤\nماذا نسمّي مجموعة من الناس يغنّون معًا؟", correctAnswer: "جوقة", distractors: ["أوركسترا", "فرقة رقص", "فريق كرة قدم"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎼\nماذا نسمّي مجموعة كبيرة من العازفين يعزفون معًا؟", correctAnswer: "أوركسترا", distractors: ["جوقة", "صفًّا دراسيًّا", "عائلة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪄\nمَن يقف أمام الأوركسترا ويشير إلى العازفين متى يعزفون وكيف؟", correctAnswer: "المايسترو", distractors: ["الحَكَم", "السائق", "الرسّام"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌙\nماذا نسمّي الأغنية التي تُغنّى للرضيع كي ينام؟", correctAnswer: "تهويدة", distractors: ["نشيدًا وطنيًّا", "نشيد مسيرة", "أغنية عيد ميلاد"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌳\nعن ماذا تحكي أغنية «عصفور طلّ من الشبّاك»؟", correctAnswer: "عن طائر صغير وقف عند النافذة", distractors: ["عن قطّة شربت الحليب", "عن سفينة في البحر", "عن دبّ صغير ذهب لينام"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎠\nعن ماذا تحكي أغنية «طلعت يا محلا نورها»؟", correctAnswer: "عن شروق الشمس", distractors: ["عن المطر", "عن القمر في الليل", "عن البحر"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎂\nأيّ أغنية نغنّيها عند إشعال الشموع على كعكة عيد الميلاد؟", correctAnswer: "«سنة حلوة يا جميل»", distractors: ["«عصفور طلّ من الشبّاك»", "«طلعت يا محلا نورها»", "«يا ليل يا عين»"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🥁\nفي أيّ شهر يطوف المسحّراتي في الأحياء وهو يقرع طبلته؟", correctAnswer: "شهر رمضان", distractors: ["شهر كانون الثاني", "شهر أيلول", "شهر آذار"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎸\nإلى أيّ عائلة ينتمي الجيتار؟", correctAnswer: "الآلات الوتريّة", distractors: ["آلات النفخ", "آلات الإيقاع", "آلات لوحة المفاتيح"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎺\nإلى أيّ عائلة ينتمي البوق؟", correctAnswer: "آلات النفخ", distractors: ["الآلات الوتريّة", "آلات الإيقاع", "آلات لوحة المفاتيح"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🥁\nإلى أيّ عائلة تنتمي الطبول؟", correctAnswer: "آلات الإيقاع", distractors: ["الآلات الوتريّة", "آلات النفخ", "آلات لوحة المفاتيح"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎷\nإلى أيّ عائلة ينتمي الساكسفون؟", correctAnswer: "آلات النفخ", distractors: ["الآلات الوتريّة", "آلات الإيقاع", "آلات لوحة المفاتيح"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎹\nالأورغ والسينثسايزر — إلى أيّ عائلة ينتميان؟", correctAnswer: "آلات لوحة المفاتيح", distractors: ["الآلات الوتريّة", "آلات النفخ", "آلات الإيقاع"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔔\nالصنوج لوحان معدنيّان مستديران. كيف نعزف عليهما؟", correctAnswer: "نضرب أحدهما بالآخر", distractors: ["ننفخ فيهما", "نداعب أوتارهما", "نضغط على مفاتيحهما"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎻\nأيّ آلة تشبه الكمان لكنّها أكبر منه، ويُعزف عليها جالسًا؟", correctAnswer: "التشيلو", distractors: ["الناي", "التوبا", "القيثارة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎻\nأيّ آلة من هذه تُصدر أخفض النغمات؟", correctAnswer: "الكونترباص", distractors: ["الكمان", "الريكوردر", "البيكولو"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎺\nالتوبا آلة نفخ كبيرة جدًّا. أيّ نغمات تُصدر؟", correctAnswer: "نغمات منخفضة", distractors: ["نغمات عالية جدًّا", "نغمات حادّة كالصفير", "نغمات رفيعة كالجرس"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪕\nأيّ آلة وتريّة كبيرة على شكل مثلّث يُعزف عليها بالأصابع؟", correctAnswer: "القيثارة", distractors: ["الكمان", "التوبا", "الأكورديون"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪗\nأيّ آلة موسيقيّة نمدّها ونضمّها باليدين، ولها مفاتيح أيضًا؟", correctAnswer: "الأكورديون", distractors: ["البيانو", "الناي", "الطبل"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎸\nكم وترًا لجيتار الباس عادةً؟", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎹\nالمفاتيح السوداء في البيانو مرتّبة في مجموعات من…", correctAnswer: "2 و3", distractors: ["1 و4", "4 و5", "3 و6"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥁\nأيّ آلة تحافظ عادةً على الإيقاع في الفرقة الموسيقيّة؟", correctAnswer: "الطبول", distractors: ["الناي", "الكمان", "الميكروفون"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎵\nأيّ نغمة تأتي مباشرة بعد «مي»؟", correctAnswer: "فا", distractors: ["ري", "صول", "سي"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎵\nأيّ نغمة تأتي مباشرة قبل «صول»؟", correctAnswer: "فا", distractors: ["مي", "لا", "دو"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎵\nأيّ نغمة تأتي مباشرة بعد «لا»؟", correctAnswer: "سي", distractors: ["صول", "فا", "ري"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎼\nعلى كم خطًّا تُكتب النوتات في المدرَج الموسيقيّ؟", correctAnswer: "5", distractors: ["3", "4", "7"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "⏩\nماذا نسمّي سرعة الموسيقى؟", correctAnswer: "التِّمبو", distractors: ["الميلوديا", "الهارموني", "السُّلَّم"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎶\nما الكلمة الأجنبيّة التي تدلّ على «اللحن»؟", correctAnswer: "ميلوديا", distractors: ["تِمبو", "ريتم", "سولو"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nفي أغنية نعدّ فيها: واحد، اثنان، ثلاثة، أربعة، واحد، اثنان، ثلاثة، أربعة… كم نبضة في كلّ مازورة؟", correctAnswer: "4", distractors: ["2", "3", "8"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎶\nماذا نسمّي الجزء الذي يتكرّر في الأغنية عدّة مرّات؟", correctAnswer: "اللازمة", distractors: ["المقطع", "النوتة", "عصا المايسترو"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✍️\nماذا يفعل المُلحِّن؟", correctAnswer: "يؤلّف موسيقى جديدة", distractors: ["يصلّح الآلات الموسيقيّة", "يبيع التذاكر", "يصوّر الحفلات"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎼\nكان باخ وموتسارت وبيتهوفن…", correctAnswer: "مُلحِّنين", distractors: ["رسّامين", "لاعبي كرة قدم", "طبّاخين"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "👂\nأيّ مُلحِّن مشهور واصل تأليف أعمال رائعة حتّى بعدما كاد يفقد سمعه كلّه؟", correctAnswer: "بيتهوفن", distractors: ["موتسارت", "باخ", "فيفالدي"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🇮🇱\nما اسم النشيد الوطنيّ لدولة إسرائيل؟", correctAnswer: "«هَتِكفا»", distractors: ["«سنة حلوة يا جميل»", "«عصفور طلّ من الشبّاك»", "«طلعت يا محلا نورها»"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "💃\nأيّ رقصة شعبيّة في البلاد تُرقَص في صفّ، يدًا بيد؟", correctAnswer: "الدبكة", distractors: ["الباليه", "التانغو", "الهيب هوب"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🔔\nفي أيّ عيد تُنشَد الترانيم وتُقرَع أجراس الكنائس؟", correctAnswer: "عيد الميلاد", distractors: ["عيد الفطر", "عيد الأضحى", "رأس السنة الهجريّة"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎹\nكم مفتاحًا في البيانو العاديّ؟", correctAnswer: "88", distractors: ["50", "100", "120"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🔊\nفي الموسيقى، ما معنى كلمة «فورتي»؟", correctAnswer: "العزف بصوت قويّ", distractors: ["العزف بصوت خافت", "العزف بسرعة", "العزف ببطء"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "📈\nما معنى «كريشندو»؟", correctAnswer: "الموسيقى تعلو شيئًا فشيئًا", distractors: ["الموسيقى تخفت شيئًا فشيئًا", "الموسيقى تتوقّف", "الموسيقى تعود إلى البداية"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "💃\nفي رقصة الفالس نعدّ في كلّ مازورة حتّى…", correctAnswer: "3", distractors: ["2", "4", "5"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🎼\nما اسم العلامة الملتوية التي تظهر في بداية المدرَج الموسيقيّ؟", correctAnswer: "مفتاح صول", distractors: ["علامة التعجّب", "السُّلَّم الموسيقيّ", "النبضة"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🔁\nما هي الأغنية على طريقة «الكانون»؟", correctAnswer: "كلّ مجموعة تبدأ اللحن نفسه بعد المجموعة التي قبلها بقليل", distractors: ["أغنية بلا كلمات", "أغنية طويلة جدًّا", "أغنية تُغنّى همسًا"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🇦🇹\nفي أيّ دولة وُلد المُلحِّن موتسارت؟", correctAnswer: "النمسا", distractors: ["إسرائيل", "اليابان", "البرازيل"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "👶\nكان موتسارت طفلًا معجزة. في أيّ سنّ تقريبًا بدأ التلحين؟", correctAnswer: "5", distractors: ["15", "20", "30"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🍂\nمَن لحّن عمل «الفصول الأربعة»؟", correctAnswer: "فيفالدي", distractors: ["موتسارت", "بيتهوفن", "باخ"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🇩🇪\nمن أيّ دولة كان المُلحِّن باخ؟", correctAnswer: "ألمانيا", distractors: ["إيطاليا", "إسبانيا", "روسيا"], tier: .hard, grades: 3...4),
    ]
}
