import Foundation

/// 🦕 الديناصورات — بالعربية. مأخوذ عن البنك العبريّ (70 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let dinosaurs: [BankQuestion] = [
        BankQuestion(prompt: "🦖\nهل يمكن أن نلتقي اليوم بتيرانوصورس حيّ؟", correctAnswer: "لا، لقد انقرض منذ زمن بعيد", distractors: ["نعم، في الغابة", "نعم، في حديقة الحيوانات", "نعم، في الصحراء"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥚\nمن أين خرجت صغار الديناصورات؟", correctAnswer: "من البيض", distractors: ["من بطن الأمّ", "من داخل الأزهار", "من داخل الصخور"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪺\nماذا نسمّي المكان الذي وضعت فيه أمّ الديناصور بيضها؟", correctAnswer: "عُشّ", distractors: ["جُحْر", "خليّة نحل", "حوض أسماك"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐣\nماذا خرج من بيضة الديناصور؟", correctAnswer: "صغير ديناصور", distractors: ["كتكوت دجاجة", "سمكة صغيرة", "فراشة"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦴\nعظمة ديناصور تحوّلت إلى حجر خلال ملايين السنين تُسمّى…", correctAnswer: "أُحفورة", distractors: ["صَدَفة", "عملة معدنية", "حصاة نهر"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🐊\nإلى أيّ مجموعة من الحيوانات تنتمي الديناصورات؟", correctAnswer: "الزواحف", distractors: ["الأسماك", "الحشرات", "الثدييات"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌍\nأين عاشت الديناصورات؟", correctAnswer: "في كلّ أنحاء العالم", distractors: ["في أفريقيا فقط", "في القطب فقط", "في إسرائيل فقط"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🦕\nأيّ ديناصور مشهور بعنقه الطويل جدًّا؟", correctAnswer: "براكيوصورس", distractors: ["تيرانوصورس", "ترايسيراتوبس", "فيلوسيرابتور"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦖\nأيّ ديناصور مشهور كان مفترسًا عملاقًا بأسنان كبيرة ويدين صغيرتين؟", correctAnswer: "تيرانوصورس ريكس", distractors: ["براكيوصورس", "ترايسيراتوبس", "ستيغوصورس"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦏\nأيّ ديناصور كان له ثلاثة قرون على وجهه؟", correctAnswer: "ترايسيراتوبس", distractors: ["تيرانوصورس", "براكيوصورس", "فيلوسيرابتور"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🛡️\nأيّ ديناصور كانت له ألواح كبيرة على ظهره وأشواك في ذيله؟", correctAnswer: "ستيغوصورس", distractors: ["براكيوصورس", "تيرانوصورس", "ديبلودوكس"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🏃\nكان الفيلوسيرابتور ديناصورًا…", correctAnswer: "صغيرًا وسريعًا", distractors: ["عملاقًا وبطيئًا", "طائرًا", "يسبح في البحر"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌿\nماذا كان يأكل البراكيوصورس؟", correctAnswer: "أوراق الأشجار", distractors: ["الأسماك", "اللحم", "الحشرات"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍖\nماذا كان يأكل التيرانوصورس ريكس؟", correctAnswer: "اللحم", distractors: ["الأوراق", "الفواكه", "العشب"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦏\nماذا كان يأكل الترايسيراتوبس؟", correctAnswer: "النباتات", distractors: ["الأسماك", "اللحم", "الحشرات"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥬\nالستيغوصورس هو…", correctAnswer: "آكل نباتات", distractors: ["مفترس", "آكل أسماك", "آكل حشرات"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌱\nماذا نسمّي ديناصورًا كان يأكل النباتات فقط؟", correctAnswer: "عاشب", distractors: ["مفترس", "صيّاد أسماك", "آكل كلّ شيء"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🦕\nبماذا ساعد العنق الطويل البراكيوصورس؟", correctAnswer: "في الوصول إلى الأوراق العالية", distractors: ["في السباحة بسرعة", "في الطيران", "في الحفر في الأرض"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🦵\nعلى كم ساقًا كان يمشي التيرانوصورس؟", correctAnswer: "2", distractors: ["4", "6", "8"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦵\nعلى كم ساقًا كان يمشي الترايسيراتوبس؟", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤏\nما الذي كان صغيرًا بشكل خاصّ في جسم التيرانوصورس؟", correctAnswer: "اليدان", distractors: ["الرأس", "الذيل", "الساقان"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🐔\nهل كانت كلّ الديناصورات عملاقة؟", correctAnswer: "لا، كان منها ما هو صغير بحجم دجاجة", distractors: ["نعم، كلّها بحجم بيت", "نعم، كلّها أكبر من فيل", "لا، كلّها كانت أصغر من قطّة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🪨\nأين نجد عادةً أحافير الديناصورات؟", correctAnswer: "داخل الصخور", distractors: ["على قمم الأشجار", "داخل الغيوم", "داخل الأزهار"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🖌️\nبأيّ أداة تُنظَّف الأحفورة برفق من التراب؟", correctAnswer: "فُرشاة", distractors: ["مِجرفة", "مِنشار", "شوكة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🏛️\nأين يمكن رؤية هيكل عظميّ كبير لديناصور؟", correctAnswer: "في متحف", distractors: ["في حديقة حيوانات", "في سوبرماركت", "في بِركة سباحة"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "➕\nللترايسيراتوبس ثلاثة قرون. كم قرنًا لترايسيراتوبسين اثنين؟", correctAnswer: "6", distractors: ["3", "5", "9"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦵\nالتيرانوصورس يمشي على ساقين والترايسيراتوبس على أربع. كم ساقًا لهما معًا؟", correctAnswer: "6", distractors: ["2", "4", "8"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥚\nكان في العُشّ 5 بيضات، ووضعت أمّ الديناصور 3 بيضات أخرى. كم بيضة في العُشّ الآن؟", correctAnswer: "8", distractors: ["2", "7", "9"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔍\nماذا نسمّي العالِم الذي يدرس أحافير الديناصورات؟", correctAnswer: "عالِم الأحافير", distractors: ["رائد فضاء", "طبيب أسنان", "مهندس معماريّ"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐦\nأيّ حيوانات تعيش اليوم هي من نسل الديناصورات؟", correctAnswer: "الطيور", distractors: ["الأسماك", "الفراشات", "الكلاب"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦃\nأيّ ديناصور كان صغيرًا، بحجم ديك رومي تقريبًا؟", correctAnswer: "فيلوسيرابتور", distractors: ["تيرانوصورس", "براكيوصورس", "ديبلودوكس"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪶\nماذا كان يغطّي جسم الفيلوسيرابتور؟", correctAnswer: "الريش", distractors: ["الفَرْو", "الصوف", "درع قاسٍ"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "☄️\nقبل كم سنة تقريبًا انقرضت الديناصورات؟", correctAnswer: "قبل 66 مليون سنة", distractors: ["قبل 100 سنة", "قبل 1,000 سنة", "قبل 6,000 سنة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "☄️\nما الذي سبّب انقراض الديناصورات بحسب العلماء؟", correctAnswer: "اصطدام كويكب عملاق بالأرض", distractors: ["مطر غزير", "رياح قويّة", "ثلج كثيف"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "👣\nأيّ اكتشاف مميّز للديناصورات يوجد في بيت زايت قرب القدس؟", correctAnswer: "آثار أقدام ديناصورات", distractors: ["بيض ديناصورات", "هيكل كامل لتيرانوصورس", "ديناصور حيّ"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧍\nهل عاش البشر مع الديناصورات؟", correctAnswer: "لا، انقرضت قبل ذلك بزمن طويل", distractors: ["نعم، في الكهوف نفسها", "نعم، وركبوا عليها", "نعم، وربّوها في المزارع"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📖\nما معنى كلمة «ديناصور»؟", correctAnswer: "سحلية مُرعبة", distractors: ["حيوان كبير", "ملك الغابة", "زاحف طويل"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📖\nما معنى اسم «ترايسيراتوبس»؟", correctAnswer: "وجه بثلاثة قرون", distractors: ["ذيل طويل", "سحلية السقف", "لصّ سريع"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🦅\nالتيروصورات كانت زواحف طائرة عاشت إلى جانب الديناصورات. فهل هي ديناصورات؟", correctAnswer: "لا، هي أقارب لها فقط", distractors: ["نعم، ديناصورات طائرة", "نعم، ديناصورات صغيرة", "نعم، ديناصورات بحريّة"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🏞️\nأين عاشت معظم الديناصورات؟", correctAnswer: "على اليابسة", distractors: ["في البحر", "في الهواء", "تحت الأرض"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧩\nماذا يفعل علماء الأحافير بعظام الديناصور التي يجدونها؟", correctAnswer: "يركّبون منها هيكلًا عظميًّا", distractors: ["يرمونها", "يزرعونها", "يطبخونها"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "👣\nماذا يمكن أن نتعلّم من آثار أقدام ديناصور؟", correctAnswer: "كيف كان يمشي وكم كان كبيرًا", distractors: ["ما لونه", "ما اسمه", "أيّ صوت كان يُصدر"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧱\nالعظام التي دُفنت في الطين والرمل، خلال ملايين السنين…", correctAnswer: "تتحوّل إلى حجر", distractors: ["تذوب", "تنمو", "تتحوّل إلى ذهب"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📅\nما اسم إحدى الحِقَب التي عاشت فيها الديناصورات؟", correctAnswer: "العصر الجوراسيّ", distractors: ["العصر الحجريّ", "العصر الحديديّ", "القرون الوسطى"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐦\nما المشترك بين الطيور والديناصورات؟", correctAnswer: "كلاهما يضع البيض", distractors: ["لكليهما فَرْو", "كلاهما يعيش في البحر", "كلاهما يأكل العشب فقط"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📏\nكم كان طول التيرانوصورس ريكس البالغ تقريبًا؟", correctAnswer: "نحو 12 مترًا", distractors: ["نحو متر واحد", "نحو 120 مترًا", "نحو 12 سنتيمترًا"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🏢\nكان ارتفاع البراكيوصورس تقريبًا مثل…", correctAnswer: "مبنى من 4 طوابق", distractors: ["طفل", "كلب كبير", "عربة أطفال"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦷\nكان طول سنّ التيرانوصورس تقريبًا مثل…", correctAnswer: "موزة", distractors: ["زِرّ", "حبّة أرز", "حافلة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦕\nأيّ ديناصور كان له ذيل طويل جدًّا كالسوط، وعنق طويل أيضًا؟", correctAnswer: "ديبلودوكس", distractors: ["ترايسيراتوبس", "تيرانوصورس", "ستيغوصورس"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🛡️\nأيّ ديناصور كان له درع يغطّي جسمه كلّه وكرة عظميّة قاسية في طرف ذيله؟", correctAnswer: "أنكيلوصورس", distractors: ["براكيوصورس", "فيلوسيرابتور", "ديبلودوكس"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "📏\nطول التيرانوصورس 12 مترًا وطول الترايسيراتوبس 9 أمتار. كم يبلغ طولهما معًا؟", correctAnswer: "21 مترًا", distractors: ["3 أمتار", "20 مترًا", "22 مترًا"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "📏\nطول الديبلودوكس 26 مترًا وطول التيرانوصورس 12 مترًا. بكم مترًا يزيد طول الديبلودوكس؟", correctAnswer: "14", distractors: ["12", "16", "38"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✖️\nثلاثة ترايسيراتوبسات تمشي معًا، ولكلّ واحد منها 4 أرجل. كم رِجلًا لها جميعًا؟", correctAnswer: "12", distractors: ["7", "9", "16"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✖️\nللستيغوصورس 4 أشواك في ذيله. كم شوكة لثلاثة ستيغوصورسات؟", correctAnswer: "12", distractors: ["7", "8", "16"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "➗\n20 بيضة ديناصور تُقسَّم بالتساوي على 4 أعشاش. كم بيضة في كلّ عُشّ؟", correctAnswer: "5", distractors: ["4", "6", "16"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🦖\nكان للتيرانوصورس إصبعان في كلّ يد. كم إصبعًا في يديه معًا؟", correctAnswer: "4", distractors: ["2", "6", "10"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🇲🇽\nقرب أيّ دولة سقط الكويكب الذي سبّب انقراض الديناصورات؟", correctAnswer: "المكسيك", distractors: ["إسرائيل", "اليابان", "فرنسا"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐚\nفي حفرة رامون (مكتيش رامون) في النقب يمكن رؤية أحافير…", correctAnswer: "الأمونيتات — حيوانات بحريّة قديمة", distractors: ["التيرانوصورسات", "الفِيَلة", "البطاريق"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "📖\nما معنى اسم «فيلوسيرابتور»؟", correctAnswer: "لصّ سريع", distractors: ["سحلية مُرعبة", "وجه بقرون", "سحلية السقف"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📖\nما معنى اسم «ستيغوصورس»؟", correctAnswer: "سحلية السقف", distractors: ["سحلية الذراع", "لصّ سريع", "ملك السحالي"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧑‍🔬\nأيّ عالِم ابتكر كلمة «ديناصور» سنة 1842؟", correctAnswer: "ريتشارد أوين", distractors: ["ألبرت أينشتاين", "تشارلز داروين", "إسحاق نيوتن"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🎨\nما الذي ما زال العلماء لا يعرفونه بيقين عن معظم الديناصورات؟", correctAnswer: "ما لونها", distractors: ["كم رِجلًا كانت لها", "ماذا كانت تأكل", "كم كان طولها"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌵\nلماذا يسهل البحث عن الأحافير في الصحراء؟", correctAnswer: "لأنّ الصخور هناك مكشوفة", distractors: ["لأنّ الجوّ هناك حارّ", "لأنّ فيها ماء كثيرًا", "لأنّ الديناصورات أحبّت الرمل"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🗺️\nفي أيّ قارّة عُثر على أحافير الفيلوسيرابتور؟", correctAnswer: "آسيا", distractors: ["أوروبا", "أفريقيا", "أمريكا الجنوبيّة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥚\nاسم «مايازورا» معناه «السحلية الأمّ الصالحة». لماذا سُمّيت كذلك؟", correctAnswer: "لأنّه عُثر على أعشاشها ومعها صغارها", distractors: ["لأنّها كانت الأكبر", "لأنّه كان لها قرن", "لأنّها كانت تعرف الطيران"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧠\nكان دماغ الستيغوصورس الكبير صغيرًا جدًّا — بحجم…", correctAnswer: "ليمونة", distractors: ["بطّيخة", "كرة سلّة", "سيّارة"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐟\nأيّ ديناصور كان له «شراع» كبير على ظهره، وكان يحبّ أكل السمك؟", correctAnswer: "سبينوصورس", distractors: ["ترايسيراتوبس", "ستيغوصورس", "أنكيلوصورس"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "⏳\nكم من الوقت عاشت الديناصورات على كوكب الأرض؟", correctAnswer: "أكثر من 150 مليون سنة", distractors: ["10 سنوات", "100 سنة", "1,000 سنة"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📅\nفي أيّ عصر عاش التيرانوصورس والترايسيراتوبس، قُبَيل الانقراض مباشرة؟", correctAnswer: "العصر الطباشيريّ", distractors: ["العصر الجوراسيّ", "العصر الترياسيّ", "العصر الجليديّ"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nانقرضت الديناصورات قبل 66 مليون سنة. كيف نكتب 66 مليونًا بالأرقام؟", correctAnswer: "66,000,000", distractors: ["66,000", "6,600,000", "660,000,000"], tier: .hard, grades: 4...6),
    ]
}
