import Foundation

/// 🍎 الطعام — بالعربية. مأخوذ عن البنك العبريّ (70 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let food: [BankQuestion] = [
        BankQuestion(prompt: "🐄\nمِنْ أَيِّ حَيَوَانٍ نَحْصُلُ عَلَى الحَلِيب؟", correctAnswer: "بَقَرَة", distractors: ["دَجَاجَة", "سَمَكَة", "فَرَاشَة"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥚\nأَيُّ حَيَوَانٍ يَبِيضُ البَيْضَ الَّذِي نَأْكُلُهُ؟", correctAnswer: "الدَّجَاجَة", distractors: ["البَقَرَة", "الكَلْب", "القِطّ"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍯\nمَنْ يَصْنَعُ العَسَل؟", correctAnswer: "النَّحْل", distractors: ["النَّمْل", "الفَرَاشَات", "العَصَافِير"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍞\nمِمَّ يُخْبَزُ الخُبْز؟", correctAnswer: "مِنَ الطَّحِين", distractors: ["مِنَ الرَّمْل", "مِنَ الجُبْنَة", "مِنَ الشُّوكُولَاتَة"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧀\nمِمَّ تُصْنَعُ الجُبْنَة؟", correctAnswer: "مِنَ الحَلِيب", distractors: ["مِنَ المَاء", "مِنَ العَصِير", "مِنَ الطَّحِين"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍫\nمِمَّ تُصْنَعُ الشُّوكُولَاتَة؟", correctAnswer: "مِنْ حُبُوبِ الكَاكَاو", distractors: ["مِنَ التُّفَّاح", "مِنَ الأَرُزّ", "مِنَ الجَزَر"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍇\nمِنْ أَيِّ فَاكِهَةٍ يُصْنَعُ الزَّبِيب؟", correctAnswer: "مِنَ العِنَب", distractors: ["مِنَ التُّفَّاح", "مِنَ المَوْز", "مِنَ البَطِّيخ"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍟\nمِنْ أَيِّ خُضَارٍ نَصْنَعُ الأَصَابِعَ المَقْلِيَّةَ الذَّهَبِيَّة؟", correctAnswer: "مِنَ البَطَاطَا", distractors: ["مِنَ الجَزَر", "مِنَ البَنَدُورَة", "مِنَ البَصَل"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍅\nمِمَّ يُصْنَعُ الكَاتْشُوب؟", correctAnswer: "مِنَ البَنَدُورَة", distractors: ["مِنَ الجَزَر", "مِنَ البَطَاطَا", "مِنَ الخَسّ"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌳\nأَيُّ فَاكِهَةٍ تَنْمُو عَلَى شَجَرَة؟", correctAnswer: "التُّفَّاح", distractors: ["الجَزَر", "البَطَاطَا", "الخِيَار"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥔\nأَيُّ خُضَارٍ يَنْمُو تَحْتَ الأَرْض؟", correctAnswer: "البَطَاطَا", distractors: ["البَنَدُورَة", "الخِيَار", "الخَسّ"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🫓\nمَا اسْمُ الخُبْزِ المُدَوَّرِ الَّذِي لَهُ جَيْبٌ فِي دَاخِلِه؟", correctAnswer: "البِيتَا", distractors: ["خُبْزُ الطَّابُون", "الرَّغِيفُ الفَرَنْسِيّ", "الكْرُوَاسَان"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍎\nالتُّفَّاحَةُ هِيَ…", correctAnswer: "فَاكِهَة", distractors: ["خُضَار", "جُبْنَة", "خُبْز"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥕\nالجَزَرُ هُوَ…", correctAnswer: "خُضَار", distractors: ["فَاكِهَة", "سَمَكَة", "كَعْكَة"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍌\nمَا لَوْنُ المَوْزَةِ النَّاضِجَة؟", correctAnswer: "أَصْفَر", distractors: ["أَزْرَق", "بَنَفْسَجِيّ", "أَسْوَد"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍊\nمَا لَوْنُ اليُوسُفِيِّ النَّاضِج؟", correctAnswer: "بُرْتُقَالِيّ", distractors: ["أَزْرَق", "أَبْيَض", "وَرْدِيّ"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍎\nمَاذَا يَجِبُ أَنْ نَأْكُلَ كُلَّ يَوْم؟", correctAnswer: "الفَوَاكِهَ وَالخُضَار", distractors: ["الحَلْوَى", "الشُّوكُولَاتَة", "البَطَاطَا المَقْلِيَّة"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "💧\nمَا أَفْضَلُ شَيْءٍ نَشْرَبُهُ عِنْدَ العَطَش؟", correctAnswer: "المَاء", distractors: ["الزَّيْت", "الخَلّ", "الكَاتْشُوب"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧊\nمَاذَا يَحْدُثُ لِقِطْعَةِ ثَلْجٍ نَتْرُكُهَا فِي الشَّمْس؟", correctAnswer: "تَذُوب", distractors: ["تَتَجَمَّد", "تَكْبَر", "تُصْبِحُ زَرْقَاء"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "💧\nالمَاءُ الَّذِي نَضَعُهُ فِي المُجَمِّدِ يَتَحَوَّلُ إِلَى…", correctAnswer: "ثَلْج", distractors: ["بُخَار", "عَصِير", "حَلِيب"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧼\nمَاذَا نَفْعَلُ قَبْلَ أَنْ نَبْدَأَ الطَّبْخ؟", correctAnswer: "نَغْسِلُ أَيْدِيَنَا", distractors: ["نُمَشِّطُ شَعْرَنَا", "نَلْبَسُ الحِذَاء", "نُطْفِئُ النُّور"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔥\nمَنْ يَجِبُ أَنْ يُسَاعِدَنَا عِنْدَ اسْتِعْمَالِ الفُرْنِ السَّاخِن؟", correctAnswer: "شَخْصٌ كَبِير", distractors: ["أَخٌ صَغِير", "الكَلْب", "الدُّمْيَة"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍲\nكَيْفَ نَحْمِلُ صَحْنَ الحَسَاءِ السَّاخِن؟", correctAnswer: "بِبُطْءٍ وَحَذَر", distractors: ["وَنَحْنُ نَرْكُض", "بِيَدٍ وَاحِدَةٍ فَوْقَ الرَّأْس", "وَنَحْنُ نَقْفِز"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥄\nبِمَاذَا نَأْكُلُ الحَسَاء؟", correctAnswer: "بِالمِلْعَقَة", distractors: ["بِالشَّوْكَة", "بِالسِّكِّين", "بِالمِقَصّ"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔪\nبِمَاذَا نَقْطَعُ الخُبْز؟", correctAnswer: "بِالسِّكِّين", distractors: ["بِالمِلْعَقَة", "بِالشَّوْكَة", "بِالكَأْس"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧁\nكُلُّ كَعْكَةٍ تَحْتَاجُ بَيْضَتَيْن. كَمْ بَيْضَةً تَحْتَاجُ كَعْكَتَان؟", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍪\nفِي الوَصْفَةِ مَكْتُوبٌ 3 مَلَاعِقِ سُكَّر، وَقَدْ وَضَعْنَا مِلْعَقَةً وَاحِدَة. كَمْ مِلْعَقَةً بَقِيَتْ؟", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍕\nقَطَعْنَا البِيتْزَا إِلَى 8 مُثَلَّثَاتٍ وَأَكَلْنَا 3. كَمْ مُثَلَّثًا بَقِيَ؟", correctAnswer: "5", distractors: ["3", "4", "6"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧆\nمِمَّ تُصْنَعُ الفَلَافِل؟", correctAnswer: "مِنَ الحُمُّص", distractors: ["مِنَ اللَّحْم", "مِنَ الجُبْنَة", "مِنَ البَطَاطَا"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌱\nمِمَّ تُصْنَعُ الطَّحِينَة؟", correctAnswer: "مِنَ السِّمْسِم", distractors: ["مِنَ الجَوْز", "مِنَ الفُولِ السُّودَانِيّ", "مِنَ القَمْح"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥛\nكَيْفَ يَتَحَوَّلُ الحَلِيبُ إِلَى لَبَن؟", correctAnswer: "بِإِضَافَةِ بَكْتِيرْيَا نَافِعَة", distractors: ["بِتَجْمِيدِه", "بِإِضَافَةِ السُّكَّر", "بِتَصْفِيَتِه"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍞\nمَا الَّذِي يَجْعَلُ عَجِينَ الخُبْزِ يَنْتَفِخ؟", correctAnswer: "الخَمِيرَة", distractors: ["المِلْح", "المَاءُ البَارِد", "مَسْحُوقُ الكَاكَاو"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌾\nمِنْ أَيِّ نَبْتَةٍ يُصْنَعُ عَادَةً طَحِينُ الخُبْز؟", correctAnswer: "القَمْح", distractors: ["القُطْن", "الجَزَر", "البُرْتُقَال"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🍚\nأَيْنَ تُزْرَعُ أَنْوَاعٌ كَثِيرَةٌ مِنَ الأَرُزّ؟", correctAnswer: "فِي حُقُولٍ مَغْمُورَةٍ بِالمَاء", distractors: ["عَلَى أَشْجَارٍ عَالِيَة", "دَاخِلَ البَحْر", "فِي الصَّحْرَاءِ الجَافَّة"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍓\nأَيْنَ تَنْمُو الفَرَاوِلَة؟", correctAnswer: "عَلَى نَبْتَةٍ قَصِيرَةٍ قَرِيبَةٍ مِنَ الأَرْض", distractors: ["عَلَى شَجَرَةٍ عَالِيَة", "تَحْتَ الأَرْض", "دَاخِلَ المَاء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥜\nأَيْنَ يَنْمُو الفُولُ السُّودَانِيّ؟", correctAnswer: "تَحْتَ الأَرْض", distractors: ["عَلَى الشَّجَر", "عَلَى الدَّالِيَة", "فِي المَاء"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍇\nعَلَى مَاذَا يَنْمُو العِنَب؟", correctAnswer: "عَلَى الدَّالِيَة", distractors: ["عَلَى شَجَرَةِ التُّفَّاح", "عَلَى شُجَيْرَةِ الوَرْد", "عَلَى النَّخْلَة"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌴\nأَيُّ فَاكِهَةٍ تَنْمُو عَلَى النَّخْلَة؟", correctAnswer: "التَّمْر", distractors: ["التُّفَّاح", "الإِجَّاص", "الكَرَز"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧂\nمِنْ أَيْنَ نَحْصُلُ عَلَى المِلْح؟", correctAnswer: "مِنْ مَاءِ البَحْرِ وَمِنَ المَنَاجِم", distractors: ["مِنَ الأَشْجَار", "مِنَ الأَبْقَار", "مِنَ البَيْض"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍯\nلِمَاذَا العَسَلُ حُلْوُ المَذَاق؟", correctAnswer: "لِأَنَّ فِيهِ سُكَّرِيَّاتٍ طَبِيعِيَّةً كَثِيرَة", distractors: ["لِأَنَّهُمْ يُضِيفُونَ إِلَيْهِ السُّكَّرَ فِي المَصْنَع", "لِأَنَّهُ مَصْنُوعٌ مِنَ الحَلِيب", "لِأَنَّهُ يَنْمُو عَلَى الأَشْجَار"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥬\nأَيٌّ مِنْ هَذِهِ يَنْتَمِي إِلَى مَجْمُوعَةِ الخُضَار؟", correctAnswer: "الخَسّ", distractors: ["الخُبْز", "الجُبْنَة", "البَيْضَة"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🥛\nالحَلِيبُ وَالجُبْنَةُ وَالزُّبْدَةُ تَنْتَمِي إِلَى مَجْمُوعَةِ…", correctAnswer: "مُنْتَجَاتِ الأَلْبَان", distractors: ["الفَوَاكِه", "الحُبُوب", "الخُضَار"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍞\nالخُبْزُ وَالأَرُزُّ وَالمَعْكَرُونَةُ تَنْتَمِي إِلَى مَجْمُوعَةِ…", correctAnswer: "الحُبُوب", distractors: ["الفَوَاكِه", "مُنْتَجَاتِ الأَلْبَان", "الخُضَار"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥛\nكَمْ كَأْسًا سَعَةُ كُلٍّ مِنْهَا 250 مِلِّلِتْرًا فِي لِتْرٍ وَاحِد؟", correctAnswer: "4", distractors: ["2", "3", "5"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "⚖️\nكَمْ غْرَامًا فِي الكِيلُوغْرَامِ الوَاحِد؟", correctAnswer: "1,000", distractors: ["100", "10", "500"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥄\nفِي الوَصْفَةِ مَكْتُوبٌ «مِلْعَقَةُ شَاي». أَيَّ أَدَاةٍ نَأْخُذ؟", correctAnswer: "مِلْعَقَةٌ صَغِيرَة", distractors: ["مِلْعَقَةٌ كَبِيرَة", "كَأْس", "مِغْرَفَة"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🧁\nالكَعْكَةُ الوَاحِدَةُ تَحْتَاجُ 3 بَيْضَات. كَمْ بَيْضَةً تَحْتَاجُ 3 كَعْكَات؟", correctAnswer: "9", distractors: ["6", "3", "12"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥞\nالوَصْفَةُ تَحْتَاجُ كَأْسَيْنِ مِنَ الطَّحِين. ضَاعَفْنَا الوَصْفَة. كَمْ كَأْسًا مِنَ الطَّحِينِ نَحْتَاج؟", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🍪\nالوَصْفَةُ تَحْتَاجُ 6 مَلَاعِقِ سُكَّر، وَنَحْنُ نُحَضِّرُ نِصْفَ الوَصْفَةِ فَقَط. كَمْ مِلْعَقَةً نَحْتَاج؟", correctAnswer: "3", distractors: ["2", "4", "12"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "⏲️\nالكَعْكَةُ تَحْتَاجُ 40 دَقِيقَةً فِي الفُرْن. أَدْخَلْنَاهَا السَّاعَةَ 4:00. مَتَى نُخْرِجُهَا؟", correctAnswer: "4:40", distractors: ["4:20", "4:30", "5:00"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔥\nعِنْدَ أَيِّ دَرَجَةِ حَرَارَةٍ يَغْلِي المَاء؟", correctAnswer: "100 دَرَجَةٍ مِئَوِيَّة", distractors: ["10 دَرَجَاتٍ مِئَوِيَّة", "50 دَرَجَةً مِئَوِيَّة", "200 دَرَجَةٍ مِئَوِيَّة"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧊\nعِنْدَ أَيِّ دَرَجَةِ حَرَارَةٍ يَتَحَوَّلُ المَاءُ إِلَى ثَلْج؟", correctAnswer: "0 دَرَجَة مِئَوِيَّة", distractors: ["10 دَرَجَاتٍ مِئَوِيَّة", "50 دَرَجَةً مِئَوِيَّة", "100 دَرَجَةٍ مِئَوِيَّة"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "♨️\nمَا اسْمُ الغَازِ الَّذِي يَتَصَاعَدُ مِنْ قِدْرِ المَاءِ الَّذِي يَغْلِي؟", correctAnswer: "البُخَار", distractors: ["الدُّخَان", "الغَيْمَة", "الثَّلْج"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥚\nمَاذَا يَحْدُثُ لِلزُّلَالِ الشَّفَّافِ عِنْدَ سَلْقِ البَيْضَة؟", correctAnswer: "يُصْبِحُ أَبْيَضَ وَمُتَمَاسِكًا", distractors: ["يَخْتَفِي", "يُصْبِحُ أَزْرَق", "يَتَحَوَّلُ إِلَى مَاء"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍽️\nالطَّعَامُ فِي الصَّحْنِ سَاخِنٌ جِدًّا. مَاذَا نَفْعَلُ قَبْلَ التَّذَوُّق؟", correctAnswer: "نَنْتَظِرُ حَتَّى يَبْرُدَ قَلِيلًا", distractors: ["نَأْكُلُ بِسُرْعَة", "نَضَعُهُ فِي المُجَمِّدِ سَاعَةً كَامِلَة", "نَسْكُبُ عَلَيْهِ المَاء"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🧊\nلِمَاذَا نَضَعُ الحَلِيبَ فِي الثَّلَّاجَة؟", correctAnswer: "لِيَبْقَى طَازِجًا وَقْتًا أَطْوَل", distractors: ["لِيُصْبِحَ حُلْوًا", "لِيَتَحَوَّلَ إِلَى ثَلْج", "لِيُصْبِحَ سَاخِنًا"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🫧\nأَيُّ غَازٍ تُنْتِجُهُ الخَمِيرَةُ فِي العَجِين، فَيَجْعَلُهُ يَنْتَفِخ؟", correctAnswer: "ثَانِي أُكْسِيدِ الكَرْبُون", distractors: ["الأُكْسِجِين", "الهِيلْيُوم", "النِّيتْرُوجِين"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🦠\nمَا اسْمُ العَمَلِيَّةِ الَّتِي تُحَوِّلُ فِيهَا الكَائِنَاتُ الدَّقِيقَةُ الحَلِيبَ إِلَى لَبَنٍ وَالعَجِينَ إِلَى خُبْزٍ مُنْتَفِخ؟", correctAnswer: "التَّخْمِير", distractors: ["التَّجْمِيد", "التَّبْخِير", "القَلْي"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🥛\nمَا اسْمُ تَسْخِينِ الحَلِيبِ فِي المَعْمَلِ لِيُصْبِحَ آمِنًا لِلشُّرْب؟", correctAnswer: "البَسْتَرَة", distractors: ["القَلْي", "التَّجْمِيد", "الخَبْز"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "💨\nغَلَى المَاءُ فِي القِدْرِ وَقْتًا طَوِيلًا، وَالقِدْرُ يَفْرُغُ شَيْئًا فَشَيْئًا. إِلَى أَيْنَ ذَهَبَ المَاء؟", correctAnswer: "تَحَوَّلَ إِلَى بُخَار", distractors: ["امْتَصَّهُ القِدْر", "تَحَوَّلَ إِلَى مِلْح", "تَجَمَّدَ فِي القَاع"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🧊\nلِمَاذَا تَطْفُو قِطْعَةُ الثَّلْجِ عَلَى المَاء؟", correctAnswer: "لِأَنَّ الثَّلْجَ أَخَفُّ مِنَ المَاءِ بِنَفْسِ الحَجْم", distractors: ["لِأَنَّهُ بَارِد", "لِأَنَّهُ أَبْيَض", "لِأَنَّهُ لَامِع"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🍯\nلِمَاذَا يَبْقَى العَسَلُ سِنِينَ طَوِيلَةً دُونَ أَنْ يَفْسُد؟", correctAnswer: "لِأَنَّ فِيهِ مَاءً قَلِيلًا جِدًّا وَسُكَّرًا كَثِيرًا", distractors: ["لِأَنَّنَا نَحْفَظُهُ فِي المُجَمِّد", "لِأَنَّنَا نُضِيفُ إِلَيْهِ المِلْح", "لِأَنَّ النَّحْلَ يَحْرُسُهُ"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🍫\nأَيْنَ تَنْمُو أَشْجَارُ الكَاكَاو؟", correctAnswer: "فِي المَنَاطِقِ الحَارَّةِ الرَّطْبَةِ قُرْبَ خَطِّ الاسْتِوَاء", distractors: ["فِي القُطْبِ الشَّمَالِيّ", "فِي الصَّحْرَاء", "فِي الجِبَالِ المُثْلِجَة"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🍅\nالبَنَدُورَةُ تَنْمُو مِنْ زَهْرَةٍ وَفِيهَا بُذُور، لِذَلِكَ هِيَ عِلْمِيًّا…", correctAnswer: "فَاكِهَة", distractors: ["جَذْر", "وَرَقَة", "سَاق"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🥕\nأَيُّ جُزْءٍ مِنَ النَّبْتَةِ هُوَ الجَزَر؟", correctAnswer: "الجَذْر", distractors: ["الوَرَقَة", "الزَّهْرَة", "الثَّمَرَة"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🥬\nأَيَّ جُزْءٍ مِنَ النَّبْتَةِ نَأْكُلُ عِنْدَمَا نَأْكُلُ الخَسّ؟", correctAnswer: "الأَوْرَاق", distractors: ["الجَذْر", "الثَّمَرَة", "البُذُور"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🥦\nالبْرُوكُولِي فِي الحَقِيقَةِ هُوَ…", correctAnswer: "أَزْهَارٌ لَمْ تَتَفَتَّحْ بَعْد", distractors: ["جَذْر", "ثَمَرَة", "بَذْرَة"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🍚\nوَصْفَةٌ لِأَرْبَعَةِ أَشْخَاصٍ تَحْتَاجُ 200 غْرَامٍ مِنَ الأَرُزّ. كَمْ غْرَامًا نَحْتَاجُ لِثَمَانِيَةِ أَشْخَاص؟", correctAnswer: "400", distractors: ["200", "300", "800"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🥛\nوَصْفَةٌ تَحْتَاجُ لِتْرَ حَلِيبٍ (1,000 مِلِّلِتْر)، وَنَحْنُ نُحَضِّرُ رُبْعَ الوَصْفَةِ فَقَط. كَمْ مِلِّلِتْرًا مِنَ الحَلِيبِ نَحْتَاج؟", correctAnswer: "250", distractors: ["500", "100", "750"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "⏲️\nالكَعْكَةُ تُخْبَزُ سَاعَةً وَ15 دَقِيقَة. أَدْخَلْنَاهَا الفُرْنَ السَّاعَةَ 3:30. مَتَى نُخْرِجُهَا؟", correctAnswer: "4:45", distractors: ["4:15", "4:30", "5:00"], tier: .hard, grades: 3...5),
    ]
}
