import Foundation

/// 🚩 الأعلام — بالعربية. مأخوذ عن البنك العبريّ (70 سؤالًا)،
/// مع الحفاظ على الواقع الإسرائيليّ والشيكل.
extension ArabicContent {
    static let flags: [BankQuestion] = [
        BankQuestion(prompt: "🇮🇱\nلأيّ دولة هذا العلم؟", correctAnswer: "إسرائيل", distractors: ["فرنسا", "إيطاليا", "الولايات المتحدة"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇺🇸\nلأيّ دولة العلم ذو النجوم والخطوط؟", correctAnswer: "الولايات المتحدة", distractors: ["كندا", "بريطانيا", "أستراليا"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇫🇷\nلأيّ دولة هذا العلم الأزرق والأبيض والأحمر؟", correctAnswer: "فرنسا", distractors: ["إيطاليا", "ألمانيا", "إسبانيا"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇮🇹\nلأيّ دولة هذا العلم الأخضر والأبيض والأحمر؟", correctAnswer: "إيطاليا", distractors: ["فرنسا", "إسبانيا", "اليونان"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇯🇵\nلأيّ دولة العلم ذو الدائرة الحمراء؟", correctAnswer: "اليابان", distractors: ["الصين", "الهند", "تايلاند"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇨🇦\nلأيّ دولة العلم ذو الورقة الحمراء؟", correctAnswer: "كندا", distractors: ["الولايات المتحدة", "سويسرا", "اليابان"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇧🇷\nلأيّ دولة هذا العلم الأخضر والأصفر؟", correctAnswer: "البرازيل", distractors: ["البرتغال", "الأرجنتين", "المكسيك"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇬🇧\nلأيّ دولة هذا العلم؟", correctAnswer: "المملكة المتحدة (بريطانيا)", distractors: ["فرنسا", "النرويج", "الولايات المتحدة"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇩🇪\nلأيّ دولة هذا العلم الأسود والأحمر والأصفر؟", correctAnswer: "ألمانيا", distractors: ["هولندا", "النمسا", "إسبانيا"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🗼\nفي أيّ دولة يقع برج إيفل؟", correctAnswer: "فرنسا", distractors: ["إيطاليا", "إنجلترا", "إسبانيا"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐪\nفي أيّ دولة تقع الأهرامات الشهيرة؟", correctAnswer: "مصر", distractors: ["اليونان", "المغرب", "تركيا"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🗽\nفي أيّ دولة يقع تمثال الحرية؟", correctAnswer: "الولايات المتحدة", distractors: ["فرنسا", "كندا", "البرازيل"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🧱\nفي أيّ دولة يقع السور العظيم الذي يمتدّ آلاف الكيلومترات؟", correctAnswer: "الصين", distractors: ["اليابان", "الهند", "روسيا"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🕰️\nفي أيّ دولة تقع ساعة \"بيغ بن\"؟", correctAnswer: "إنجلترا", distractors: ["فرنسا", "ألمانيا", "إيطاليا"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🏙️\nما هي عاصمة إسرائيل؟", correctAnswer: "القدس", distractors: ["تل أبيب", "حيفا", "بئر السبع"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🥐\nما هي عاصمة فرنسا؟", correctAnswer: "باريس", distractors: ["لندن", "روما", "مدريد"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍕\nما هي عاصمة إيطاليا؟", correctAnswer: "روما", distractors: ["ميلانو", "باريس", "أثينا"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🎡\nما هي عاصمة إنجلترا؟", correctAnswer: "لندن", distractors: ["باريس", "برلين", "دبلن"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌏\nفي أيّ قارّة تقع إسرائيل؟", correctAnswer: "آسيا", distractors: ["أوروبا", "أفريقيا", "أمريكا"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌍\nكم قارّة في العالم حسب ما يُدرَّس عادةً؟", correctAnswer: "7", distractors: ["5", "6", "9"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌊\nكم محيطًا في العالم، بما في ذلك المحيط الجنوبي؟", correctAnswer: "5", distractors: ["3", "4", "7"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌍\nفي أيّ قارّة تقع فرنسا؟", correctAnswer: "أوروبا", distractors: ["آسيا", "أفريقيا", "أستراليا"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌍\nفي أيّ قارّة تقع مصر؟", correctAnswer: "أفريقيا", distractors: ["آسيا", "أوروبا", "أمريكا الجنوبية"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇮🇱\nما هما لونا علم إسرائيل؟", correctAnswer: "أزرق وأبيض", distractors: ["أحمر وأبيض", "أزرق وأحمر", "أخضر وأبيض"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "✡️\nأيّ رمز يظهر في وسط علم إسرائيل؟", correctAnswer: "نجمة داوود", distractors: ["الشمعدان", "الهلال", "غصن الزيتون"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "⭐\nكم نجمة في علم الولايات المتحدة؟", correctAnswer: "50", distractors: ["13", "52", "100"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🗣️\nما هي اللغة التي يتكلّمها الناس في فرنسا؟", correctAnswer: "الفرنسية", distractors: ["الإسبانية", "الإيطالية", "الألمانية"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🪙\nما هي عملة إسرائيل؟", correctAnswer: "الشيكل", distractors: ["الدولار", "اليورو", "الليرة"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇨🇳\nلأيّ دولة العلم الأحمر ذو النجوم الصفراء الخمس؟", correctAnswer: "الصين", distractors: ["اليابان", "كوريا الجنوبية", "تايلاند"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇦🇺\nلأيّ دولة هذا العلم؟", correctAnswer: "أستراليا", distractors: ["بريطانيا", "كندا", "الولايات المتحدة"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇲🇽\nلأيّ دولة العلم ذو النسر في وسطه؟", correctAnswer: "المكسيك", distractors: ["البرازيل", "إسبانيا", "الأرجنتين"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇦🇷\nلأيّ دولة العلم السماويّ والأبيض مع الشمس؟", correctAnswer: "الأرجنتين", distractors: ["البرازيل", "المكسيك", "البرتغال"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇬🇷\nلأيّ دولة العلم الأزرق والأبيض ذو الخطوط والصليب؟", correctAnswer: "اليونان", distractors: ["تركيا", "إيطاليا", "إسبانيا"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇹🇷\nلأيّ دولة العلم الأحمر ذو الهلال والنجمة؟", correctAnswer: "تركيا", distractors: ["اليونان", "المغرب", "مصر"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇷🇺\nلأيّ دولة هذا العلم الأبيض والأزرق والأحمر؟", correctAnswer: "روسيا", distractors: ["البرتغال", "بولندا", "اليونان"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇰🇷\nلأيّ دولة العلم ذو الدائرة الحمراء والزرقاء؟", correctAnswer: "كوريا الجنوبية", distractors: ["اليابان", "الصين", "تايلاند"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇮🇳\nلأيّ دولة العلم البرتقاليّ والأبيض والأخضر مع العجلة؟", correctAnswer: "الهند", distractors: ["الصين", "اليابان", "مصر"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇨🇭\nلأيّ دولة العلم الأحمر المربّع ذو الصليب الأبيض في وسطه؟", correctAnswer: "سويسرا", distractors: ["السويد", "بلجيكا", "بولندا"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇪🇬\nلأيّ دولة العلم الأحمر والأبيض والأسود مع النسر الذهبيّ؟", correctAnswer: "مصر", distractors: ["تركيا", "المغرب", "اليونان"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nما هي عاصمة إسبانيا؟", correctAnswer: "مدريد", distractors: ["برشلونة", "لشبونة", "روما"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nما هي عاصمة ألمانيا؟", correctAnswer: "برلين", distractors: ["ميونخ", "فيينا", "باريس"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nما هي عاصمة اليابان؟", correctAnswer: "طوكيو", distractors: ["بكين", "سيول", "أوساكا"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nما هي عاصمة روسيا؟", correctAnswer: "موسكو", distractors: ["سانت بطرسبرغ", "وارسو", "برلين"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nما هي عاصمة مصر؟", correctAnswer: "القاهرة", distractors: ["الإسكندرية", "عمّان", "الرباط"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nما هي عاصمة الولايات المتحدة؟", correctAnswer: "واشنطن", distractors: ["نيويورك", "لوس أنجلوس", "شيكاغو"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🌏\nما هي أكبر قارّة في العالم؟", correctAnswer: "آسيا", distractors: ["أفريقيا", "أوروبا", "أمريكا الشمالية"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🗺️\nما هي أكبر دولة في العالم من حيث المساحة؟", correctAnswer: "روسيا", distractors: ["الصين", "كندا", "الولايات المتحدة"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🌊\nما هو أكبر محيط في العالم؟", correctAnswer: "المحيط الهادئ", distractors: ["المحيط الأطلسيّ", "المحيط الهنديّ", "المحيط المتجمّد الشماليّ"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🌎\nفي أيّ قارّة تقع البرازيل؟", correctAnswer: "أمريكا الجنوبية", distractors: ["أمريكا الشمالية", "أفريقيا", "أوروبا"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🧭\nأيّ دولة مجاورة تقع إلى الشمال من إسرائيل؟", correctAnswer: "لبنان", distractors: ["مصر", "الأردن", "تركيا"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🧭\nأيّ دولة مجاورة تقع إلى الشرق من إسرائيل؟", correctAnswer: "الأردن", distractors: ["لبنان", "مصر", "اليونان"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🧭\nأيّ دولة مجاورة تقع إلى الجنوب الغربيّ من إسرائيل؟", correctAnswer: "مصر", distractors: ["لبنان", "سوريا", "قبرص"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "💶\nبأيّ عملة يُدفَع في فرنسا وألمانيا وإيطاليا؟", correctAnswer: "اليورو", distractors: ["الدولار", "الشيكل", "الليرة"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "💵\nما هي عملة الولايات المتحدة؟", correctAnswer: "الدولار", distractors: ["اليورو", "الشيكل", "الين"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🍁\nورقة أيّ شجرة تظهر في علم كندا؟", correctAnswer: "ورقة القيقب", distractors: ["ورقة الزيتون", "ورقة النخيل", "ورقة البلّوط"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇯🇵\nإلامَ ترمز الدائرة الحمراء في علم اليابان؟", correctAnswer: "الشمس", distractors: ["القمر", "كرة", "زهرة"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇸🇪\nلأيّ دولة العلم الأزرق ذو الصليب الأصفر؟", correctAnswer: "السويد", distractors: ["النرويج", "فنلندا", "الدنمارك"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇩🇰\nلأيّ دولة العلم الأحمر ذو الصليب الأبيض المُزاح نحو السارية؟", correctAnswer: "الدنمارك", distractors: ["السويد", "فنلندا", "بولندا"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇵🇹\nلأيّ دولة هذا العلم الأخضر والأحمر؟", correctAnswer: "البرتغال", distractors: ["إسبانيا", "إيطاليا", "المغرب"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇿🇦\nلأيّ دولة هذا العلم المُلوَّن الذي فيه شكل حرف Y؟", correctAnswer: "جنوب أفريقيا", distractors: ["كينيا", "نيجيريا", "مصر"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🦘\nما هي عاصمة أستراليا؟", correctAnswer: "كانبرا", distractors: ["سيدني", "ملبورن", "بيرث"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🍁\nما هي عاصمة كندا؟", correctAnswer: "أوتاوا", distractors: ["تورونتو", "فانكوفر", "مونتريال"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏙️\nما هي عاصمة البرازيل؟", correctAnswer: "برازيليا", distractors: ["ريو دي جانيرو", "ساو باولو", "لشبونة"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🌏\nما هي أصغر قارّة في العالم؟", correctAnswer: "أستراليا", distractors: ["أوروبا", "أنتاركتيكا", "أفريقيا"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "⛪\nما هي أصغر دولة في العالم؟", correctAnswer: "الفاتيكان", distractors: ["موناكو", "مالطا", "إسرائيل"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🧊\nأيّ قارّة تكاد تكون مغطّاة كلّها بالجليد ولا توجد فيها دول؟", correctAnswer: "أنتاركتيكا", distractors: ["أستراليا", "أوروبا", "أمريكا الشمالية"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🗣️\nما هي اللغة التي يتكلّمها الناس في البرازيل؟", correctAnswer: "البرتغالية", distractors: ["الإسبانية", "الفرنسية", "الإيطالية"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "💴\nما هي عملة اليابان؟", correctAnswer: "الين", distractors: ["الدولار", "اليوان", "اليورو"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "💷\nما هي عملة بريطانيا؟", correctAnswer: "الجنيه الإسترلينيّ", distractors: ["اليورو", "الدولار", "الفرنك"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇺🇸\nكم خطًّا في علم الولايات المتحدة؟", correctAnswer: "13", distractors: ["50", "10", "15"], tier: .hard, grades: 5...6),
    ]
}
