import Foundation

/// 🦕 Динозавры — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let dinosaurs: [BankQuestion] = [
        BankQuestion(prompt: "🦖\nМожно ли сегодня встретить живого тираннозавра?", correctAnswer: "Нет, он вымер очень давно", distractors: ["Да, в лесу", "Да, в зоопарке", "Да, в пустыне"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥚\nОткуда появлялись детёныши динозавров?", correctAnswer: "Из яиц", distractors: ["Из маминого живота", "Из цветов", "Из камней"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪺\nКак называется место, куда мама-динозавр откладывала яйца?", correctAnswer: "Гнездо", distractors: ["Нора", "Улей", "Аквариум"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐣\nМама-динозавр отложила яйцо. Кто из него вылупился?", correctAnswer: "Детёныш динозавра", distractors: ["Цыплёнок курицы", "Маленькая рыбка", "Бабочка"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦴\nКость динозавра, которая за миллионы лет превратилась в камень, называется…", correctAnswer: "Окаменелость", distractors: ["Ракушка", "Монета", "Речная галька"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🐊\nК какой группе животных относятся динозавры?", correctAnswer: "Пресмыкающиеся", distractors: ["Рыбы", "Насекомые", "Млекопитающие"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌍\nГде жили динозавры?", correctAnswer: "По всему миру", distractors: ["Только в Африке", "Только на полюсе", "Только в Израиле"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🦕\nКакой динозавр знаменит своей очень длинной шеей?", correctAnswer: "Брахиозавр", distractors: ["Тираннозавр", "Трицератопс", "Велоцираптор"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦖\nКакой знаменитый динозавр был огромным хищником с большими зубами и маленькими передними лапами?", correctAnswer: "Тираннозавр рекс", distractors: ["Брахиозавр", "Трицератопс", "Стегозавр"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦏\nУ какого динозавра было 3 рога на морде?", correctAnswer: "Трицератопс", distractors: ["Тираннозавр", "Брахиозавр", "Велоцираптор"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🛡️\nУ какого динозавра были большие пластины на спине и шипы на хвосте?", correctAnswer: "Стегозавр", distractors: ["Брахиозавр", "Тираннозавр", "Диплодок"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🏃\nВелоцираптор был динозавром…", correctAnswer: "Маленьким и быстрым", distractors: ["Огромным и медленным", "Летающим", "Плавающим в море"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌿\nЧем питался брахиозавр?", correctAnswer: "Листьями деревьев", distractors: ["Рыбой", "Мясом", "Насекомыми"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍖\nЧем питался тираннозавр рекс?", correctAnswer: "Мясом", distractors: ["Листьями", "Фруктами", "Травой"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦏\nЧем питался трицератопс?", correctAnswer: "Растениями", distractors: ["Рыбой", "Мясом", "Насекомыми"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥬\nСтегозавр был…", correctAnswer: "Растительноядным", distractors: ["Хищником", "Рыбоядным", "Насекомоядным"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌱\nКак называют динозавра, который ел только растения?", correctAnswer: "Травоядный", distractors: ["Хищник", "Рыболов", "Всеядный"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🦕\nЧем длинная шея помогала брахиозавру?", correctAnswer: "Дотягиваться до высоких листьев", distractors: ["Быстро плавать", "Летать", "Копать землю"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🦵\nНа скольких ногах ходил тираннозавр?", correctAnswer: "2", distractors: ["4", "6", "8"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦵\nНа скольких ногах ходил трицератопс?", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤏\nЧто было особенно маленьким у тираннозавра?", correctAnswer: "Передние лапы", distractors: ["Голова", "Хвост", "Задние ноги"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🐔\nВсе ли динозавры были огромными?", correctAnswer: "Нет, были и маленькие, размером с курицу", distractors: ["Да, все были размером с дом", "Да, все были больше слона", "Нет, все были меньше кошки"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🪨\nГде обычно находят окаменелости динозавров?", correctAnswer: "Внутри камней", distractors: ["На верхушках деревьев", "Внутри облаков", "Внутри цветов"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🖌️\nКаким инструментом осторожно очищают окаменелость от земли?", correctAnswer: "Кисточкой", distractors: ["Граблями", "Пилой", "Вилкой"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🏛️\nГде можно увидеть большой скелет динозавра?", correctAnswer: "В музее", distractors: ["В зоопарке", "В супермаркете", "В бассейне"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "➕\nУ трицератопса 3 рога. Сколько рогов у двух трицератопсов?", correctAnswer: "6", distractors: ["3", "5", "9"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦵\nТираннозавр ходит на 2 ногах, а трицератопс — на 4. Сколько ног у них вместе?", correctAnswer: "6", distractors: ["2", "4", "8"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥚\nВ гнезде было 5 яиц, и мама-динозавр отложила ещё 3. Сколько яиц теперь в гнезде?", correctAnswer: "8", distractors: ["2", "7", "9"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔍\nКак называется учёный, который изучает окаменелости динозавров?", correctAnswer: "Палеонтолог", distractors: ["Астронавт", "Зубной врач", "Архитектор"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐦\nКакие животные, живущие сегодня, произошли от динозавров?", correctAnswer: "Птицы", distractors: ["Рыбы", "Бабочки", "Собаки"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦃\nКакой динозавр был маленьким, примерно с индюка?", correctAnswer: "Велоцираптор", distractors: ["Тираннозавр", "Брахиозавр", "Диплодок"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪶\nЧем было покрыто тело велоцираптора?", correctAnswer: "Перьями", distractors: ["Мехом", "Гладкой кожей", "Твёрдым панцирем"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "☄️\nПримерно сколько лет назад вымерли динозавры?", correctAnswer: "66 миллионов лет назад", distractors: ["100 лет назад", "1000 лет назад", "6000 лет назад"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "☄️\nЧто, по мнению учёных, привело к вымиранию динозавров?", correctAnswer: "Падение огромного астероида", distractors: ["Сильный дождь", "Сильный ветер", "Обильный снег"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "👣\nКакая особая находка, связанная с динозаврами, есть в Бейт-Зайт рядом с Иерусалимом?", correctAnswer: "Отпечатки лап динозавров", distractors: ["Яйца динозавров", "Целый скелет тираннозавра", "Живой динозавр"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧍\nЖили ли люди вместе с динозаврами?", correctAnswer: "Нет, динозавры вымерли задолго до людей", distractors: ["Да, в одних и тех же пещерах", "Да, люди ездили на них верхом", "Да, люди разводили их на фермах"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📖\nЧто означает слово «динозавр»?", correctAnswer: "Ужасный ящер", distractors: ["Большой зверь", "Царь леса", "Длинное пресмыкающееся"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📖\nЧто означает название «трицератопс»?", correctAnswer: "Морда с тремя рогами", distractors: ["Длинный хвост", "Ящер с крышей", "Быстрый вор"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🦅\nПтерозавры были летающими пресмыкающимися и жили рядом с динозаврами. Были ли они динозаврами?", correctAnswer: "Нет, они только близкие родственники", distractors: ["Да, это летающие динозавры", "Да, это маленькие динозавры", "Да, это морские динозавры"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🏞️\nГде жило большинство динозавров?", correctAnswer: "На суше", distractors: ["В море", "В воздухе", "Под землёй"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧩\nЧто делают палеонтологи с найденными костями динозавра?", correctAnswer: "Собирают из них скелет", distractors: ["Выбрасывают их", "Сажают их в землю", "Варят их"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "👣\nЧто можно узнать по отпечаткам лап динозавра?", correctAnswer: "Как он ходил и каким он был большим", distractors: ["Какого он был цвета", "Как его звали", "Какие звуки он издавал"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧱\nКости, которые пролежали в иле и песке миллионы лет…", correctAnswer: "Превращаются в камень", distractors: ["Растворяются", "Прорастают", "Превращаются в золото"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📅\nКак называется одна из эпох, когда жили динозавры?", correctAnswer: "Юрский период", distractors: ["Каменный век", "Железный век", "Средние века"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐦\nЧто общего у птиц и динозавров?", correctAnswer: "И те и другие откладывают яйца", distractors: ["И у тех и у других есть мех", "И те и другие живут в море", "И те и другие едят только траву"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📏\nКакой примерно была длина взрослого тираннозавра рекса?", correctAnswer: "Около 12 метров", distractors: ["Около 1 метра", "Около 120 метров", "Около 12 сантиметров"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🏢\nБрахиозавр был высотой примерно как…", correctAnswer: "Дом в 4 этажа", distractors: ["Ребёнок", "Большая собака", "Детская коляска"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦷\nЗуб тираннозавра был длиной примерно как…", correctAnswer: "Банан", distractors: ["Пуговица", "Рисовое зёрнышко", "Автобус"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦕\nУ какого динозавра был очень длинный хвост, как кнут, и длинная шея?", correctAnswer: "Диплодок", distractors: ["Трицератопс", "Тираннозавр", "Стегозавр"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🛡️\nУ какого динозавра было панцирное покрытие по всему телу и твёрдый костяной шар на конце хвоста?", correctAnswer: "Анкилозавр", distractors: ["Брахиозавр", "Велоцираптор", "Диплодок"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "📏\nТираннозавр длиной 12 метров, а трицератопс — 9 метров. Какова их длина вместе?", correctAnswer: "21 метр", distractors: ["3 метра", "20 метров", "22 метра"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "📏\nДиплодок длиной 26 метров, а тираннозавр — 12 метров. На сколько метров диплодок длиннее?", correctAnswer: "14", distractors: ["12", "16", "38"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✖️\nВместе идут 3 трицератопса, у каждого 4 ноги. Сколько у них ног всего?", correctAnswer: "12", distractors: ["7", "9", "16"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✖️\nУ стегозавра 4 шипа на хвосте. Сколько шипов у трёх стегозавров?", correctAnswer: "12", distractors: ["7", "8", "16"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "➗\n20 яиц динозавра поровну разложили в 4 гнезда. Сколько яиц в каждом гнезде?", correctAnswer: "5", distractors: ["4", "6", "16"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🦖\nУ тираннозавра было 2 пальца на каждой передней лапе. Сколько пальцев было на двух лапах?", correctAnswer: "4", distractors: ["2", "6", "10"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🇲🇽\nРядом с какой страной упал астероид, погубивший динозавров?", correctAnswer: "Мексика", distractors: ["Израиль", "Япония", "Франция"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐚\nВ махтеше Рамон в Негеве можно увидеть окаменелости…", correctAnswer: "Аммонитов — древних морских животных", distractors: ["Тираннозавров", "Слонов", "Пингвинов"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "📖\nЧто означает название «велоцираптор»?", correctAnswer: "Быстрый вор", distractors: ["Ужасный ящер", "Рогатая морда", "Ящер с крышей"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📖\nЧто означает название «стегозавр»?", correctAnswer: "Ящер с крышей", distractors: ["Ящер с рукой", "Быстрый вор", "Царь ящеров"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧑‍🔬\nКакой учёный придумал слово «динозавр» в 1842 году?", correctAnswer: "Ричард Оуэн", distractors: ["Альберт Эйнштейн", "Чарльз Дарвин", "Исаак Ньютон"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🎨\nЧего учёные до сих пор точно не знают о большинстве динозавров?", correctAnswer: "Какого они были цвета", distractors: ["Сколько у них было ног", "Чем они питались", "Какой они были длины"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌵\nПочему в пустыне удобно искать окаменелости?", correctAnswer: "Потому что камни там открыты, их не закрывают растения", distractors: ["Потому что там жарко", "Потому что там много воды", "Потому что динозавры любили песок"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🗺️\nНа каком континенте нашли окаменелости велоцираптора?", correctAnswer: "Азия", distractors: ["Европа", "Африка", "Южная Америка"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥚\nНазвание «майязавра» означает «ящерица — хорошая мама». Почему её так назвали?", correctAnswer: "Потому что нашли её гнёзда с детёнышами", distractors: ["Потому что она была самой большой", "Потому что у неё был рог", "Потому что она умела летать"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧠\nУ большого стегозавра был очень маленький мозг — примерно размером с…", correctAnswer: "Лимон", distractors: ["Арбуз", "Баскетбольный мяч", "Автомобиль"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐟\nУ какого динозавра был большой «парус» на спине и он любил есть рыбу?", correctAnswer: "Спинозавр", distractors: ["Трицератопс", "Стегозавр", "Анкилозавр"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "⏳\nСколько времени динозавры прожили на Земле?", correctAnswer: "Больше 150 миллионов лет", distractors: ["10 лет", "100 лет", "1000 лет"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📅\nВ какую эпоху жили тираннозавр и трицератопс, прямо перед вымиранием?", correctAnswer: "Меловой период", distractors: ["Юрский период", "Триасовый период", "Ледниковый период"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nДинозавры вымерли 66 миллионов лет назад. Как записать 66 миллионов цифрами?", correctAnswer: "66 000 000", distractors: ["66 000", "6 600 000", "660 000 000"], tier: .hard, grades: 4...6),
    ]
}
