import Foundation

/// 🐾 Животные — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let animals: [BankQuestion] = [
        BankQuestion(prompt: "🐄\nКакое животное говорит «му»?", correctAnswer: "Корова", distractors: ["Собака", "Кошка", "Петух"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐱\nКакое животное говорит «мяу»?", correctAnswer: "Кошка", distractors: ["Собака", "Корова", "Лошадь"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐶\nКакой звук издаёт собака?", correctAnswer: "Гав-гав", distractors: ["Му", "Кукареку", "Мяу"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐓\nКакое животное кричит «кукареку» по утрам?", correctAnswer: "Петух", distractors: ["Утка", "Овца", "Коза"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐴\nКак называется детёныш лошади?", correctAnswer: "Жеребёнок", distractors: ["Козлёнок", "Ягнёнок", "Телёнок"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐄\nКак называется детёныш коровы?", correctAnswer: "Телёнок", distractors: ["Жеребёнок", "Козлёнок", "Цыплёнок"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐥\nКак называется детёныш курицы?", correctAnswer: "Цыплёнок", distractors: ["Ягнёнок", "Телёнок", "Козлёнок"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐑\nКак называется детёныш овцы?", correctAnswer: "Ягнёнок", distractors: ["Козлёнок", "Телёнок", "Жеребёнок"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐐\nКак называется детёныш козы?", correctAnswer: "Козлёнок", distractors: ["Ягнёнок", "Жеребёнок", "Телёнок"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐶\nКак называют малыша собаки?", correctAnswer: "Щенок", distractors: ["Цыплёнок", "Телёнок", "Ягнёнок"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐸\nКак называется детёныш лягушки, который живёт в воде и у которого есть хвост?", correctAnswer: "Головастик", distractors: ["Гусеница", "Цыплёнок", "Козлёнок"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦋\nКто превращается в бабочку, когда вырастает?", correctAnswer: "Гусеница", distractors: ["Головастик", "Цыплёнок", "Рыба"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🍼\nЧто пьют детёныши млекопитающих — например щенок или телёнок, — когда рождаются?", correctAnswer: "Мамино молоко", distractors: ["Воду", "Сок", "Мёд"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐦\nКак называется дом, который птица строит для своих яиц?", correctAnswer: "Гнездо", distractors: ["Улей", "Берлога", "Конюшня"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐕\nСколько лап у собаки?", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐜\nСколько лапок у муравья?", correctAnswer: "6", distractors: ["4", "8", "10"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦅\nСколько крыльев у птицы?", correctAnswer: "2", distractors: ["1", "4", "6"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🕷️\nСколько лап у паука?", correctAnswer: "8", distractors: ["6", "4", "10"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐘\nКакое самое большое животное живёт сегодня на суше?", correctAnswer: "Слон", distractors: ["Лошадь", "Корова", "Верблюд"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐋\nКакое животное самое большое во всём мире?", correctAnswer: "Синий кит", distractors: ["Слон", "Акула", "Жираф"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦒\nКакое животное самое высокое в мире?", correctAnswer: "Жираф", distractors: ["Слон", "Верблюд", "Медведь"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐆\nКакое животное самое быстрое на суше?", correctAnswer: "Гепард", distractors: ["Лошадь", "Заяц", "Лев"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦈\nКакая рыба самая большая в мире?", correctAnswer: "Китовая акула", distractors: ["Тунец", "Лосось", "Золотая рыбка"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐫\nЧто есть у верблюда на спине?", correctAnswer: "Горб", distractors: ["Рога", "Крылья", "Чешуя"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐘\nКак называется длинный нос слона?", correctAnswer: "Хобот", distractors: ["Рог", "Горб", "Клюв"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🦏\nУ какого животного прямо на носу растёт большой рог?", correctAnswer: "Носорог", distractors: ["Слон", "Зебра", "Бегемот"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦓\nУ какого животного чёрно-белые полоски?", correctAnswer: "Зебра", distractors: ["Жираф", "Слон", "Медведь"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐦\nЧто покрывает тело птицы?", correctAnswer: "Перья", distractors: ["Чешуя", "Мех", "Иголки"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐍\nЧто покрывает тело змеи?", correctAnswer: "Чешуя", distractors: ["Перья", "Мех", "Пух"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐢\nКакое животное носит свой дом на спине?", correctAnswer: "Черепаха", distractors: ["Заяц", "Лягушка", "Попугай"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🦘\nГде мама-кенгуру носит своего детёныша?", correctAnswer: "В сумке на животе", distractors: ["На спине", "Во рту", "На хвосте"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐟\nКакой орган помогает рыбам дышать под водой?", correctAnswer: "Жабры", distractors: ["Лёгкие", "Нос", "Плавники"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦒\nЗачем жирафу длинная шея?", correctAnswer: "Чтобы доставать листья с верхушек деревьев", distractors: ["Чтобы быстро плавать", "Чтобы летать", "Чтобы копать землю"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦎\nКакое животное умеет менять цвет своей кожи?", correctAnswer: "Хамелеон", distractors: ["Черепаха", "Змея", "Слон"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐧\nКакая птица не умеет летать, но отлично плавает?", correctAnswer: "Пингвин", distractors: ["Голубь", "Орёл", "Воробей"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦜\nКакая птица умеет повторять человеческие слова?", correctAnswer: "Попугай", distractors: ["Голубь", "Утка", "Орёл"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐊\nК какой группе относятся крокодил, ящерица и черепаха?", correctAnswer: "Рептилии", distractors: ["Млекопитающие", "Птицы", "Рыбы"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐞\nК какой группе относятся муравей, пчела и бабочка?", correctAnswer: "Насекомые", distractors: ["Рептилии", "Птицы", "Млекопитающие"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐋\nКит живёт в море, но он не рыба. К какой группе животных он относится?", correctAnswer: "Млекопитающие", distractors: ["Рыбы", "Рептилии", "Земноводные"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🦇\nЛетучая мышь летает, но она не птица. К какой группе она относится?", correctAnswer: "Млекопитающие", distractors: ["Птицы", "Насекомые", "Рептилии"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐸\nЛягушка живёт и в воде, и на суше. К какой группе она относится?", correctAnswer: "Земноводные", distractors: ["Рептилии", "Рыбы", "Млекопитающие"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🦕\nКакое огромное животное жило миллионы лет назад, а сегодня мы видим только его кости в музее?", correctAnswer: "Динозавр", distractors: ["Слон", "Жираф", "Крокодил"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐄\nКакое животное даёт нам молоко?", correctAnswer: "Корова", distractors: ["Курица", "Пчела", "Собака"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐔\nКакое животное несёт яйца, которые мы едим?", correctAnswer: "Курица", distractors: ["Корова", "Овца", "Лошадь"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐝\nКакое насекомое делает мёд?", correctAnswer: "Пчела", distractors: ["Бабочка", "Муравей", "Муха"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐝\nЧто пчела собирает с цветов?", correctAnswer: "Нектар", distractors: ["Воду", "Листья", "Семена"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐼\nЧто большая панда ест почти целый день?", correctAnswer: "Бамбук", distractors: ["Рыбу", "Мёд", "Морковь"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🌿\nКак называют животное, которое ест только растения?", correctAnswer: "Травоядное", distractors: ["Хищник", "Всеядное", "Летающее"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦁\nЛев ест мясо. Как называют животное, которое ест мясо?", correctAnswer: "Хищник", distractors: ["Травоядное", "Ползающее", "Летающее"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐻\nМедведь ест и рыбу, и ягоды, и мёд. Как называют животное, которое ест и растения, и мясо?", correctAnswer: "Всеядное", distractors: ["Травоядное", "Хищник", "Летающее"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🐝\nПочему пчёлы так важны для растений?", correctAnswer: "Они опыляют цветы, и из них вырастают плоды", distractors: ["Они поливают растения", "Они поют растениям песни", "Они копают растениям ямки"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🐪\nКакое животное может много дней идти по пустыне и не пить?", correctAnswer: "Верблюд", distractors: ["Корова", "Свинья", "Лягушка"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐻\nЧто делает бурый медведь зимой?", correctAnswer: "Спит зимним сном", distractors: ["Улетает в Африку", "Плавает в море", "Меняет цвет"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦢\nПочему осенью многие птицы улетают на юг?", correctAnswer: "Чтобы попасть туда, где тепло и много еды", distractors: ["Чтобы научиться летать", "Потому что они любят снег", "Чтобы плавать в море"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐨\nНа каком континенте живут коала и кенгуру?", correctAnswer: "Австралия", distractors: ["Европа", "Азия", "Африка"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦁\nНа каком континенте живёт в природе больше всего львов?", correctAnswer: "Африка", distractors: ["Европа", "Австралия", "Антарктида"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐼\nВ какой стране большая панда живёт в природе?", correctAnswer: "Китай", distractors: ["Бразилия", "Египет", "Канада"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐧\nНа каком ледяном континенте живут императорские пингвины?", correctAnswer: "Антарктида", distractors: ["Африка", "Европа", "Азия"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐯\nНа каком континенте тигры живут в природе?", correctAnswer: "Азия", distractors: ["Африка", "Европа", "Южная Америка"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐐\nКакое израильское животное с большими рогами лазает по скалам в Эйн-Геди?", correctAnswer: "Горный козёл", distractors: ["Слон", "Кенгуру", "Панда"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🪨\nКакой маленький пушистый зверёк живёт среди камней и скал в Израиле?", correctAnswer: "Даман", distractors: ["Коала", "Пингвин", "Белый медведь"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦌\nКакое быстрое и изящное животное с рожками бегает по полям и холмам Израиля?", correctAnswer: "Газель", distractors: ["Зебра", "Кенгуру", "Панда"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦎\nКакое маленькое пресмыкающееся летом бегает по стенам в доме и ловит комаров?", correctAnswer: "Геккон", distractors: ["Черепаха", "Крокодил", "Лягушка"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦅\nКакая большая птица парит над скалами Голан и Негева, и в Израиле её особенно охраняют?", correctAnswer: "Гриф", distractors: ["Голубь", "Петух", "Пингвин"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🏞️\nКакое животное нарисовано на эмблеме Управления природы и парков Израиля?", correctAnswer: "Горный козёл", distractors: ["Лев", "Слон", "Верблюд"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🛡️\nКак называют животных, которых осталось в мире очень мало и которых нужно беречь?", correctAnswer: "Животные под угрозой исчезновения", distractors: ["Домашние питомцы", "Животные с фермы", "Летающие животные"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦤\nЧто такое «вымирание»?", correctAnswer: "Когда животное совсем исчезает с Земли", distractors: ["Когда животное спит всю зиму", "Когда животное переезжает в зоопарк", "Когда животное меняет мех"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🌳\nПочему важно беречь леса?", correctAnswer: "Потому что это дом для множества животных", distractors: ["Чтобы было место для новых машин", "Потому что животным они не нужны", "Чтобы строить в них дома"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🏞️\nКак называется место, где охраняют природу и животных?", correctAnswer: "Заповедник", distractors: ["Зоомагазин", "Детская площадка", "Торговый центр"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐢\nЧто может сделать каждый ребёнок, чтобы помочь морским животным?", correctAnswer: "Не бросать пластик в море", distractors: ["Кормить рыб конфетами", "Петь морю песни", "Рисовать рыб"], tier: .medium, grades: 1...3),
    ]
}
