import Foundation

/// 🚀 Космос — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let space: [BankQuestion] = [
        BankQuestion(prompt: "☀️\nСолнце — это на самом деле…", correctAnswer: "Звезда", distractors: ["Планета", "Луна", "Большое облако"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌍\nКак называется планета, на которой мы живём?", correctAnswer: "Земля", distractors: ["Марс", "Луна", "Юпитер"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌞\nКогда на небе видно Солнце?", correctAnswer: "Днём", distractors: ["Ночью", "Только зимой", "Только по субботам"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌅\nЧто делает Солнце утром?", correctAnswer: "Восходит", distractors: ["Заходит", "Исчезает", "Засыпает"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌍\nКакой формы наша планета Земля?", correctAnswer: "Шар", distractors: ["Куб", "Треугольник", "Плоская тарелка"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "📏\nЧто из этого самое большое?", correctAnswer: "Солнце", distractors: ["Земля", "Луна", "Марс"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌕\nЧто находится ближе всего к Земле?", correctAnswer: "Луна", distractors: ["Солнце", "Марс", "Юпитер"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌍\nСколько лун у Земли?", correctAnswer: "1", distractors: ["0", "2", "3"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌕\nКак называется ночь, когда виден весь круглый диск Луны?", correctAnswer: "Полнолуние", distractors: ["Новолуние", "Половинка луны", "Полумесяц"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌙\nКак называют Луну, когда от неё виден только тонкий изогнутый краешек?", correctAnswer: "Полумесяц", distractors: ["Полнолуние", "Звезда", "Солнце"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌍\nВокруг чего Земля пролетает целый круг за год?", correctAnswer: "Вокруг Солнца", distractors: ["Вокруг Луны", "Вокруг Марса", "Вокруг Юпитера"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌙\nВокруг чего вращается Луна?", correctAnswer: "Вокруг Земли", distractors: ["Вокруг Солнца", "Вокруг Марса", "Вокруг Сатурна"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌞\nЧто находится в самом центре нашей планетной системы, и всё вращается вокруг него?", correctAnswer: "Солнце", distractors: ["Земля", "Юпитер", "Луна"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "📅\nСколько дней в обычном году?", correctAnswer: "365", distractors: ["100", "300", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕐\nСколько времени нужно Земле, чтобы сделать полный оборот вокруг своей оси?", correctAnswer: "Около 24 часов", distractors: ["Около 12 часов", "Неделя", "Год"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📅\nСколько времени нужно Земле, чтобы один раз облететь Солнце?", correctAnswer: "Год", distractors: ["День", "Неделя", "Месяц"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌙\nСколько примерно времени нужно Луне, чтобы облететь вокруг Земли?", correctAnswer: "Около месяца", distractors: ["Около суток", "Около недели", "Около года"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌗\nПочему бывают день и ночь?", correctAnswer: "Потому что Земля вращается вокруг своей оси", distractors: ["Потому что Солнце гаснет на ночь", "Потому что Луна закрывает Солнце", "Потому что облака закрывают Солнце"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌞\nСолнце — это звезда. Из чего она в основном состоит?", correctAnswer: "Из раскалённых газов", distractors: ["Из камней", "Из воды", "Изо льда"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌕\nПочему Луна светится ночью?", correctAnswer: "Она отражает свет Солнца", distractors: ["Она горит, как Солнце", "На ней стоят фонари", "Она сделана из золота"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌍\nПочему Землю называют «голубой планетой»?", correctAnswer: "Потому что почти вся она покрыта водой", distractors: ["Потому что на ней очень холодно", "Потому что небо голубое", "Потому что её покрасили краской"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌑\nКак называется время, когда Луну на небе почти совсем не видно?", correctAnswer: "Новолуние", distractors: ["Полнолуние", "Половинка луны", "Голубая луна"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌸\nИз-за чего бывают времена года — лето, осень, зима и весна?", correctAnswer: "Земля наклонена, пока летит вокруг Солнца", distractors: ["Солнце остывает зимой", "Луна то приближается, то удаляется", "Земля перестаёт вращаться"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💡\nСколько примерно времени свет Солнца летит до Земли?", correctAnswer: "Около 8 минут", distractors: ["Одну секунду", "Около 8 часов", "Около 8 дней"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌗\nПочему Луна каждую ночь выглядит немного иначе?", correctAnswer: "Мы видим разную часть её освещённой стороны", distractors: ["Она меняется в размере", "Её закрывают облака", "Она то приближается, то удаляется"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nСколько планет вращается вокруг Солнца?", correctAnswer: "8", distractors: ["6", "9", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔴\nКакую планету называют «красной планетой»?", correctAnswer: "Марс", distractors: ["Юпитер", "Венера", "Сатурн"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🪐\nУ какой планеты есть большие и красивые кольца?", correctAnswer: "Сатурн", distractors: ["Марс", "Земля", "Меркурий"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🪐\nКакая планета самая большая в Солнечной системе?", correctAnswer: "Юпитер", distractors: ["Земля", "Марс", "Меркурий"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔥\nКакая планета ближе всех к Солнцу?", correctAnswer: "Меркурий", distractors: ["Венера", "Земля", "Марс"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌍\nКакая планета третья по расстоянию от Солнца?", correctAnswer: "Земля", distractors: ["Венера", "Марс", "Юпитер"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔴\nКакая планета идёт сразу за Землёй, если удаляться от Солнца?", correctAnswer: "Марс", distractors: ["Венера", "Меркурий", "Сатурн"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔵\nКакая планета дальше всех от Солнца?", correctAnswer: "Нептун", distractors: ["Уран", "Сатурн", "Юпитер"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔢\nВ Солнечной системе 8 планет. Три первые от Солнца — это Меркурий, Венера и Земля. Сколько планет остаётся?", correctAnswer: "5", distractors: ["3", "6", "8"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔴\nПочему Марс кажется нам красным?", correctAnswer: "Из-за красной пыли, которая его покрывает", distractors: ["Потому что он горит", "Потому что он очень горячий", "Потому что на нём растут красные цветы"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌡️\nКакая планета самая горячая? (Подсказка: не та, что ближе всех к Солнцу)", correctAnswer: "Венера", distractors: ["Меркурий", "Марс", "Юпитер"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🪐\nКакая планета находится между Сатурном и Нептуном?", correctAnswer: "Уран", distractors: ["Юпитер", "Марс", "Венера"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🪐\nРаньше Плутон считали девятой большой планетой. Как его называют учёные сегодня?", correctAnswer: "Карликовая планета", distractors: ["Спутник Нептуна", "Комета", "Звезда"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧑‍🚀\nКак называют человека, который летает в космос?", correctAnswer: "Космонавт", distractors: ["Лётчик", "Водолаз", "Пожарный"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🚀\nС помощью чего космический корабль отправляют в космос?", correctAnswer: "Ракета", distractors: ["Самолёт", "Вертолёт", "Воздушный шар"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🍎\nЧто заставляет яблоко падать вниз, а не улетать вверх?", correctAnswer: "Сила притяжения", distractors: ["Ветер", "Солнце", "Дождь"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "👩‍🚀\nЧто надевает космонавт, когда выходит из корабля наружу?", correctAnswer: "Скафандр", distractors: ["Купальник", "Плащ от дождя", "Пижаму"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🎈\nЧто происходит с космонавтами внутри корабля, который летает вокруг Земли?", correctAnswer: "Они парят в воздухе", distractors: ["Они становятся маленькими", "Они всё время спят", "Они ходят на руках"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "👣\nКто первым из людей ступил на Луну?", correctAnswer: "Нил Армстронг", distractors: ["Илан Рамон", "Юрий Гагарин", "Альберт Эйнштейн"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🇮🇱\nКто был первым израильским космонавтом?", correctAnswer: "Илан Рамон", distractors: ["Нил Армстронг", "Юрий Гагарин", "Давид Бен-Гурион"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🛰️\nКак называется аппарат, который летает вокруг Земли и помогает нам находить дорогу и говорить по телефону?", correctAnswer: "Спутник", distractors: ["Самолёт", "Воздушный шар", "Машина"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔢\n3 космонавта полетели к Луне, и только 2 спустились на её поверхность. Сколько осталось в корабле?", correctAnswer: "1", distractors: ["0", "2", "3"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nОбратный отсчёт до старта: 10, 9, 8, 7… Какое число идёт сразу после 3?", correctAnswer: "2", distractors: ["4", "1", "0"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "👣\nВ каком году люди впервые высадились на Луне?", correctAnswer: "1969", distractors: ["1948", "1900", "2000"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚀\nКак назывался корабль, который привёз первых людей на Луну?", correctAnswer: "Аполлон-11", distractors: ["Берешит", "Спутник-1", "Вояджер"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚀\nКто первым в мире полетел в космос, в 1961 году?", correctAnswer: "Юрий Гагарин", distractors: ["Нил Армстронг", "Илан Рамон", "Галилей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🇮🇱\nКак назывался израильский космический аппарат, который полетел к Луне в 2019 году?", correctAnswer: "Берешит", distractors: ["Аполлон", "Офек", "Спутник-1"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🇮🇱\nКем работал Илан Рамон до того, как полетел в космос?", correctAnswer: "Лётчиком военной авиации", distractors: ["Футболистом", "Певцом", "Зубным врачом"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧑‍🚀\nКак называется большой дом в космосе, где космонавты живут и работают месяцами?", correctAnswer: "Международная космическая станция", distractors: ["Телескоп «Хаббл»", "Луна", "Марс"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍎\nПро какого учёного рассказывают, что он понял, как работает притяжение, когда рядом с ним упало яблоко?", correctAnswer: "Исаак Ньютон", distractors: ["Галилей", "Альберт Эйнштейн", "Томас Эдисон"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏋️\nНа Луне притяжение слабее. Что почувствует космонавт, который там подпрыгнет?", correctAnswer: "Что он лёгкий и прыгает высоко", distractors: ["Что он очень тяжёлый", "Точно то же, что и дома", "Что он совсем не может двигаться"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚀\nПочему ракета должна быть такой мощной и быстрой?", correctAnswer: "Чтобы преодолеть силу притяжения", distractors: ["Чтобы громко шуметь", "Чтобы нагреться", "Чтобы видеть далеко"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛰️\nКак назывался первый в истории аппарат, который люди вывели на орбиту в 1957 году?", correctAnswer: "Спутник-1", distractors: ["Аполлон", "Хаббл", "Берешит"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nКосмонавты на космической станции видят около 16 восходов за сутки. Сколько примерно восходов они увидят за 2 дня?", correctAnswer: "32", distractors: ["16", "8", "24"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔭\nВ какой прибор смотрят на далёкие звёзды?", correctAnswer: "Телескоп", distractors: ["Микроскоп", "Фотоаппарат", "Компьютер"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌠\nЧто такое на самом деле «падающая звезда»?", correctAnswer: "Маленький камешек из космоса, который сгорает в воздухе", distractors: ["Настоящая звезда, упавшая на Землю", "Маленькая луна", "Самолёт в ночном небе"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "✨\nКак называют группу звёзд, которые вместе складываются в фигуру на небе — медведицу или льва?", correctAnswer: "Созвездие", distractors: ["Комета", "Спутник", "Облако"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧭\nКакая звезда помогает найти ночью направление на север?", correctAnswer: "Полярная звезда", distractors: ["Солнце", "Марс", "Южная звезда"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌌\nЧто такое галактика?", correctAnswer: "Огромное скопление звёзд", distractors: ["Большая планета", "Вид космического корабля", "Спутник Юпитера"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "☄️\nЧто появляется у кометы, когда она подлетает к Солнцу, и чего нет у астероида?", correctAnswer: "Светящийся хвост", distractors: ["Кольца", "Красный цвет", "Свой собственный свет"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🪨\nГде находится большинство астероидов Солнечной системы?", correctAnswer: "Между Марсом и Юпитером", distractors: ["Между Солнцем и Меркурием", "Рядом с Луной", "Между Землёй и Венерой"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐻\nКак называется знаменитое созвездие, семь звёзд которого складываются в ковш?", correctAnswer: "Большая Медведица", distractors: ["Лев", "Скорпион", "Рыбы"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌌\nКак называется галактика, в которой находится наша Солнечная система?", correctAnswer: "Млечный Путь", distractors: ["Андромеда", "Большая Медведица", "Орион"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔭\nКакой учёный открыл в телескоп 4 больших спутника Юпитера?", correctAnswer: "Галилео Галилей", distractors: ["Исаак Ньютон", "Альберт Эйнштейн", "Нил Армстронг"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔭\nКак называется знаменитый телескоп, который с 1990 года летает вокруг Земли и фотографирует космос?", correctAnswer: "Хаббл", distractors: ["Галилей", "Спутник-1", "Аполлон"], tier: .hard, grades: 4...6),
    ]
}
