import Foundation

/// 🌊 Море — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let sea: [BankQuestion] = [
        BankQuestion(prompt: "🦈\nКто из них живёт в море?", correctAnswer: "Акула", distractors: ["Корова", "Лошадь", "Петух"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐬\nКакое морское животное считают умным и дружелюбным, и оно любит выпрыгивать из воды?", correctAnswer: "Дельфин", distractors: ["Крокодил", "Черепаха", "Заяц"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐙\nСколько щупалец у осьминога?", correctAnswer: "8", distractors: ["4", "6", "10"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐙\nКак называется мягкое животное с восемью щупальцами?", correctAnswer: "Осьминог", distractors: ["Акула", "Черепаха", "Краб"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐙\nСколько сердец у осьминога?", correctAnswer: "3", distractors: ["1", "2", "5"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐢\nЧто есть у морской черепахи на спине?", correctAnswer: "Панцирь", distractors: ["Крылья", "Шерсть", "Рога"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐢\nГде морская черепаха откладывает яйца?", correctAnswer: "В песке на берегу", distractors: ["На дне моря", "На дереве", "В снегу"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐋\nКто самое большое животное на свете?", correctAnswer: "Синий кит", distractors: ["Слон", "Акула", "Жираф"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐬\nЧто делает дельфин, когда поднимается к поверхности?", correctAnswer: "Дышит воздухом", distractors: ["Спит", "Ест песок", "Сохнет"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐟\nС помощью чего рыба дышит под водой?", correctAnswer: "Жабры", distractors: ["Лёгкие", "Нос", "Рот"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐠\nЧто помогает рыбе плавать?", correctAnswer: "Плавники", distractors: ["Ноги", "Крылья", "Руки"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐟\nЧем покрыто тело большинства рыб?", correctAnswer: "Чешуя", distractors: ["Шерсть", "Перья", "Волосы"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐟\nГде живут рыбы?", correctAnswer: "В воде", distractors: ["В воздухе", "На деревьях", "В пустыне"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🦈\nЧего у акулы очень много, и оно всё время сменяется?", correctAnswer: "Зубы", distractors: ["Глаза", "Уши", "Ноги"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪼\nКакое морское животное мягкое и прозрачное, с длинными щупальцами, и летом приплывает к берегам Израиля?", correctAnswer: "Медуза", distractors: ["Черепаха", "Дельфин", "Краб"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦀\nКакое животное ходит боком по берегу, и у него есть клешни?", correctAnswer: "Краб", distractors: ["Рыба", "Медуза", "Черепаха"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "⭐\nУ какого морского животного пять лучей, и оно медленно ползает по дну?", correctAnswer: "Морская звезда", distractors: ["Морской конёк", "Рыба-меч", "Медуза"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐴\nКакая маленькая рыбка похожа на лошадку и плавает стоя, вертикально?", correctAnswer: "Морской конёк", distractors: ["Морская звезда", "Акула", "Угорь"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦭\nКакое животное плавает в море, отдыхает на скалах, и у него есть усы?", correctAnswer: "Тюлень", distractors: ["Акула", "Золотая рыбка", "Медуза"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐚\nЧто можно найти на морском берегу?", correctAnswer: "Ракушки", distractors: ["Шишки", "Грибы", "Снег"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🧂\nКакой вкус у морской воды?", correctAnswer: "Солёный", distractors: ["Сладкий", "Кислый", "Совсем без вкуса"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌍\nБольшая часть нашей планеты покрыта…", correctAnswer: "Водой", distractors: ["Песком", "Льдом", "Лесом"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪸\nВ каком городе Израиля можно увидеть коралловый риф?", correctAnswer: "В Эйлате", distractors: ["В Тель-Авиве", "В Иерусалиме", "В Хайфе"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌊\nКак называется вода, которая снова и снова набегает на берег и отступает?", correctAnswer: "Волны", distractors: ["Облака", "Дожди", "Ветры"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🏖️\nКак называется место, где море встречается с сушей?", correctAnswer: "Берег", distractors: ["Гора", "Лес", "Пустыня"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌡️\nГде морская вода обычно теплее всего?", correctAnswer: "У самой поверхности", distractors: ["На большой глубине", "На самом дне", "Везде совершенно одинаково"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⛵\nЧто плавает по воде?", correctAnswer: "Лодка", distractors: ["Машина", "Велосипед", "Поезд"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚢\nКак называется судно, которое умеет погружаться и плыть в глубине моря?", correctAnswer: "Подводная лодка", distractors: ["Самолёт", "Поезд", "Автобус"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🤿\nКак называют того, кто опускается на глубину с маской и баллоном воздуха?", correctAnswer: "Водолаз", distractors: ["Лётчик", "Водитель", "Вратарь"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔢\nПлавали 2 дельфина, и к ним подплыли ещё 3. Сколько дельфинов теперь?", correctAnswer: "5", distractors: ["4", "6", "3"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🔢\nУ рифа плавают 4 жёлтые рыбки и 3 синие. Сколько рыбок всего?", correctAnswer: "7", distractors: ["6", "8", "1"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nНа берегу лежали 6 ракушек, и я собрал 2. Сколько ракушек осталось на берегу?", correctAnswer: "4", distractors: ["8", "3", "2"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐬\nДельфин — это…", correctAnswer: "Млекопитающее", distractors: ["Рыба", "Пресмыкающееся", "Птица"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐋\nКит дышит воздухом, как люди. С помощью чего?", correctAnswer: "Лёгкие", distractors: ["Жабры", "Плавники", "Чешуя"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐬\nКак появляется на свет маленький дельфин?", correctAnswer: "Рождается у мамы", distractors: ["Вылупляется из яйца", "Вырастает из водоросли", "Выходит из ракушки"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐟\nЧто есть у рыбы, но нет у дельфина?", correctAnswer: "Жабры", distractors: ["Хвост", "Глаза", "Плавники"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐢\nМорская черепаха — это…", correctAnswer: "Пресмыкающееся", distractors: ["Рыба", "Млекопитающее", "Насекомое"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐢\nЧто делают маленькие черепашки сразу после того, как вылупятся из яйца?", correctAnswer: "Бегут к морю", distractors: ["Забираются на дерево", "Спят целый год", "Улетают в небо"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦈\nИз чего состоит скелет акулы?", correctAnswer: "Из хряща", distractors: ["Из костей", "Из дерева", "Из металла"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🦈\nКакая акула самая большая в мире и питается в основном крошечными существами?", correctAnswer: "Китовая акула", distractors: ["Белая акула", "Акула-молот", "Тигровая акула"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐙\nЧто делает осьминог, чтобы спрятаться?", correctAnswer: "Меняет свой цвет", distractors: ["Закрывает глаза", "Выпрыгивает из воды", "Громко поёт"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐙\nКакое облако выпускает осьминог, когда хочет убежать?", correctAnswer: "Чернильное", distractors: ["Дождевое", "Пыльное", "Дымовое"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🪼\nЧто верно про медузу?", correctAnswer: "У неё нет костей", distractors: ["У неё есть панцирь", "У неё есть ноги", "У неё есть перья"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪸\nЧто такое коралл?", correctAnswer: "Крошечное животное", distractors: ["Растение", "Цветной камень", "Вид рыбы"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐠\nГде живёт большинство разноцветных рыбок?", correctAnswer: "Рядом с коралловыми рифами", distractors: ["В тёмной глубине", "Возле полюса", "В пустыне"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔦\nЧто происходит со светом, когда опускаешься очень глубоко в море?", correctAnswer: "Становится темно", distractors: ["Становится светлее", "Остаётся точно так же", "Всё делается жёлтым"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪸\nВ каком море находится коралловый риф Эйлата?", correctAnswer: "В Красном", distractors: ["В Средиземном", "В Мёртвом", "В озере Кинерет"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌊\nКакое море находится к западу от Израиля, рядом с Тель-Авивом и Хайфой?", correctAnswer: "Средиземное море", distractors: ["Красное море", "Мёртвое море", "Тихий океан"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🧂\nВ каком море очень легко держаться на плаву, потому что оно жутко солёное?", correctAnswer: "Мёртвое море", distractors: ["Средиземное море", "Красное море", "Озеро Кинерет"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🛟\nПочему в Мёртвом море люди плавают без всяких усилий?", correctAnswer: "Потому что вода очень солёная", distractors: ["Потому что вода тёплая", "Потому что там мелко", "Потому что там не бывает волн"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🗺️\nЧем знаменито Мёртвое море?", correctAnswer: "Это самое низкое место суши на Земле", distractors: ["Это самое большое море на Земле", "Это самое глубокое море на Земле", "Это самое холодное море на Земле"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🌍\nКакой океан самый большой в мире?", correctAnswer: "Тихий океан", distractors: ["Атлантический океан", "Индийский океан", "Северный Ледовитый океан"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🌊\nЧто происходит в море во время прилива?", correctAnswer: "Вода поднимается и закрывает больше берега", distractors: ["Вода исчезает совсем", "Вода замерзает", "Вода делается пресной"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🌙\nИз-за чего в море бывают приливы и отливы?", correctAnswer: "В основном из-за притяжения Луны", distractors: ["Из-за ветра", "Из-за рыб", "Из-за облаков"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🤿\nЗачем водолаз берёт с собой баллон?", correctAnswer: "Чтобы дышать под водой", distractors: ["Чтобы всплыть наверх", "Чтобы пить воду", "Чтобы светить в темноте"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🤿\nЧто водолаз надевает на ноги, чтобы плыть быстрее?", correctAnswer: "Ласты", distractors: ["Сапоги", "Ролики", "Сандалии"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚢\nЧто делает подводная лодка, когда хочет опуститься вниз?", correctAnswer: "Наполняет баки водой", distractors: ["Включает фонари", "Открывает окна", "Выключает мотор"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nУ осьминога 8 щупалец. Сколько щупалец у двух осьминогов?", correctAnswer: "16", distractors: ["10", "12", "18"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nВ стае плавают 10 дельфинов. 4 выпрыгнули из воды. Сколько осталось под водой?", correctAnswer: "6", distractors: ["14", "5", "4"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🔢\nУ морской звезды 5 лучей. Сколько лучей у трёх морских звёзд?", correctAnswer: "15", distractors: ["8", "10", "20"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌍\nКакой океан лежит между Европой с Африкой и Америкой?", correctAnswer: "Атлантический океан", distractors: ["Тихий океан", "Индийский океан", "Северный Ледовитый океан"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🌊\nКакое место в океанах самое глубокое?", correctAnswer: "Марианская впадина", distractors: ["Средиземное море", "Мёртвое море", "Суэцкий канал"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔦\nВ глубине моря есть рыбы, которые светятся в темноте. Откуда берётся этот свет?", correctAnswer: "Из их собственного тела", distractors: ["От солнца", "От фонаря водолаза", "От луны"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐬\nС помощью чего дельфин «видит» в темноте и находит рыбу?", correctAnswer: "По эху звуков", distractors: ["По фонарику", "По запаху", "По усам"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🦈\nЧто происходит, когда у акулы выпадает зуб?", correctAnswer: "На его место вырастает новый", distractors: ["Дырка остаётся навсегда", "Акула перестаёт есть", "Акула идёт к зубному врачу"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🐋\nЧем питается синий кит, самое большое животное на свете?", correctAnswer: "Крилем — крошечными рачками", distractors: ["Акулами", "Дельфинами", "Водорослями"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🧂\nПочему Мёртвое море такое солёное?", correctAnswer: "Вода испаряется, а соль остаётся", distractors: ["В него высыпают соль", "Оно соединено с океаном", "В нём много рыбы"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🌙\nСколько раз в сутки в море обычно бывает прилив?", correctAnswer: "2", distractors: ["1", "5", "10"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🚢\nЧто такое перископ на подводной лодке?", correctAnswer: "Труба, чтобы выглянуть над водой", distractors: ["Мотор подводной лодки", "Вид рыбы", "Прибор для готовки"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🔢\nПодводная лодка опустилась на глубину 300 метров, а потом поднялась на 120 метров. На какой она глубине теперь?", correctAnswer: "180 метров", distractors: ["420 метров", "200 метров", "150 метров"], tier: .hard, grades: 3...5),
    ]
}
