import Foundation

/// 🧍 Тело человека — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let body: [BankQuestion] = [
        BankQuestion(prompt: "❤️\nКакой орган гонит кровь по всему телу?", correctAnswer: "Сердце", distractors: ["Лёгкие", "Мозг", "Желудок"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🫁\nКакие органы помогают нам дышать?", correctAnswer: "Лёгкие", distractors: ["Сердце", "Желудок", "Кожа"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧠\nКакой орган помогает нам думать и запоминать?", correctAnswer: "Мозг", distractors: ["Сердце", "Лёгкие", "Печень"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "👀\nКакой орган помогает нам видеть?", correctAnswer: "Глаза", distractors: ["Уши", "Нос", "Рот"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "👂\nКакой орган помогает нам слышать?", correctAnswer: "Уши", distractors: ["Глаза", "Нос", "Руки"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "👃\nКакой орган помогает нам чувствовать запахи?", correctAnswer: "Нос", distractors: ["Рот", "Уши", "Глаза"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "👅\nКакой орган помогает нам чувствовать вкус?", correctAnswer: "Язык", distractors: ["Нос", "Зубы", "Уши"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🤲\nКакое чувство подсказывает нам, что предмет горячий или холодный?", correctAnswer: "Осязание", distractors: ["Зрение", "Слух", "Обоняние"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🖐️\nСколько основных чувств обычно изучают в школе?", correctAnswer: "5", distractors: ["3", "4", "6"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "✋\nСколько пальцев на двух руках вместе?", correctAnswer: "10", distractors: ["5", "8", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦶\nСколько пальцев на одной ноге?", correctAnswer: "5", distractors: ["4", "6", "10"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦷\nЧто помогает нам пережёвывать пищу?", correctAnswer: "Зубы", distractors: ["Нос", "Уши", "Глаза"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "👄\nЧерез какой орган еда попадает внутрь тела?", correctAnswer: "Рот", distractors: ["Нос", "Ухо", "Глаз"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍎\nКуда попадает еда после того, как мы её проглотили?", correctAnswer: "В желудок", distractors: ["В лёгкие", "В сердце", "В мозг"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "💪\nЧто двигает наши кости?", correctAnswer: "Мышцы", distractors: ["Волосы", "Кожа", "Ногти"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦴\nКак называются все кости тела вместе?", correctAnswer: "Скелет", distractors: ["Мышца", "Кожа", "Сердце"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧍\nКакой орган покрывает всё тело снаружи?", correctAnswer: "Кожа", distractors: ["Скелет", "Сердце", "Мозг"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🫀\nГде находится сердце?", correctAnswer: "В груди", distractors: ["В голове", "В ноге", "В руке"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧠\nГде находится мозг?", correctAnswer: "В голове", distractors: ["В животе", "В руке", "В ноге"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦴\nКакая кость защищает мозг?", correctAnswer: "Череп", distractors: ["Ребро", "Бедренная кость", "Плечевая кость"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🩸\nЧто течёт внутри тела и приносит кислород во все его уголки?", correctAnswer: "Кровь", distractors: ["Вода", "Воздух", "Молоко"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🪥\nКак часто нужно чистить зубы?", correctAnswer: "Два раза в день", distractors: ["Раз в неделю", "Раз в месяц", "Раз в год"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦷\nДля чего нужны щётка и паста?", correctAnswer: "Чтобы чистить зубы", distractors: ["Чтобы расчёсывать волосы", "Чтобы мыть руки", "Чтобы мыть посуду"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧼\nЧто стоит сделать перед едой?", correctAnswer: "Помыть руки", distractors: ["Побегать", "Поспать", "Спеть"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "☀️\nЧто наносят на кожу, чтобы защитить её от солнца?", correctAnswer: "Солнцезащитный крем", distractors: ["Воду", "Оливковое масло", "Клей"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🛌\nЧто тело делает ночью, чтобы отдохнуть и набраться сил?", correctAnswer: "Спит", distractors: ["Бегает", "Ест", "Прыгает"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "💧\nЧто полезно пить почаще, чтобы тело было здоровым?", correctAnswer: "Воду", distractors: ["Масло", "Сладкий сок", "Кофе"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏃\nЧто помогает мышцам стать сильными?", correctAnswer: "Спорт", distractors: ["Сладости", "Телевизор", "Компьютерные игры"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🦴\nСколько костей в теле взрослого человека?", correctAnswer: "206", distractors: ["106", "306", "520"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦴\nКакая кость в теле самая длинная?", correctAnswer: "Бедренная кость", distractors: ["Плечевая кость", "Ребро", "Череп"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦴\nСколько рёбер у человека?", correctAnswer: "24", distractors: ["12", "20", "30"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦴\nКакая часть скелета защищает сердце и лёгкие?", correctAnswer: "Рёбра", distractors: ["Череп", "Бедренная кость", "Пальцы"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦴\nКак называется место, где две кости соединяются и дают телу двигаться?", correctAnswer: "Сустав", distractors: ["Мышца", "Сухожилие", "Кожа"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦵\nКолено — это пример…", correctAnswer: "Сустава", distractors: ["Мышцы", "Внутреннего органа", "Одной кости"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦷\nСколько молочных зубов у ребёнка?", correctAnswer: "20", distractors: ["10", "24", "32"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦷\nСколько зубов у взрослого человека вместе с зубами мудрости?", correctAnswer: "32", distractors: ["20", "28", "36"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦷\nКак называются первые зубы, которые выпадают, а на их месте вырастают постоянные?", correctAnswer: "Молочные зубы", distractors: ["Зубы мудрости", "Золотые зубы", "Железные зубы"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🫀\nСердце — это на самом деле…", correctAnswer: "Мышца", distractors: ["Кость", "Сустав", "Железа"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "❤️\nЧто сердце гонит по кровеносным сосудам?", correctAnswer: "Кровь", distractors: ["Воздух", "Воду", "Еду"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🩸\nЧто кровь приносит всем клеткам тела?", correctAnswer: "Кислород и питательные вещества", distractors: ["Свет", "Звук", "Песок"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🩸\nЧто верно про кровь человека?", correctAnswer: "Есть несколько разных групп крови", distractors: ["У всех людей одна и та же группа крови", "Кровь состоит только из воды", "Внутри тела кровь зелёная"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🩸\nКакое из этих названий — название группы крови?", correctAnswer: "Группа O", distractors: ["Группа X", "Группа Z", "Группа Q"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🫁\nСколько лёгких у человека?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🫁\nКакой газ мы вдыхаем из воздуха, потому что он нужен телу?", correctAnswer: "Кислород", distractors: ["Углекислый газ", "Гелий", "Водород"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌬️\nКакой газ тело добавляет в воздух, который мы выдыхаем?", correctAnswer: "Углекислый газ", distractors: ["Кислород", "Гелий", "Водород"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌡️\nКакая примерно нормальная температура тела человека?", correctAnswer: "37 градусов", distractors: ["20 градусов", "50 градусов", "100 градусов"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧠\nПо чему мозг посылает сигналы всему телу?", correctAnswer: "По нервам", distractors: ["По кровеносным сосудам", "По волосам", "По костям"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧍\nКакой орган в теле самый большой?", correctAnswer: "Кожа", distractors: ["Сердце", "Мозг", "Печень"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "💪\nСколько примерно мышц в теле человека?", correctAnswer: "Около 600", distractors: ["Около 6", "Около 60", "Около 60 000"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👂\nКроме слуха, в чём ещё помогает внутреннее ухо?", correctAnswer: "Держать равновесие", distractors: ["Видеть в темноте", "Чувствовать вкус еды", "Переваривать пищу"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👅\nКакой вкус чувствует язык, когда мы едим лимон?", correctAnswer: "Кислый", distractors: ["Сладкий", "Солёный", "Горький"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍽️\nЧто происходит с едой в желудке?", correctAnswer: "Она распадается на маленькие кусочки", distractors: ["Она превращается в кость", "Она остаётся точно такой же", "Она поднимается в лёгкие"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍽️\nКак называется процесс, при котором тело расщепляет еду?", correctAnswer: "Пищеварение", distractors: ["Дыхание", "Сон", "Рост"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛌\nПочему важно высыпаться?", correctAnswer: "Тело и мозг отдыхают и набираются сил", distractors: ["Зубы растут только ночью", "Волосы становятся короче", "Глаза меняют цвет"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "😴\nСколько примерно нужно спать школьнику каждую ночь?", correctAnswer: "Около 10 часов", distractors: ["Около 2 часов", "Около 5 часов", "Около 16 часов"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧼\nЗачем мыть руки с мылом?", correctAnswer: "Чтобы прогнать микробов", distractors: ["Чтобы руки выросли", "Чтобы согреть руки", "Чтобы изменить цвет кожи"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👂\nГде находится самая маленькая кость в теле?", correctAnswer: "В ухе", distractors: ["В пальце", "В носу", "В колене"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦴\nЧто образуется внутри костного мозга?", correctAnswer: "Клетки крови", distractors: ["Зубы", "Волосы", "Ногти"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🫀\nСколько полостей (желудочков и предсердий) в сердце?", correctAnswer: "4", distractors: ["1", "2", "6"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🩸\nКак называются сосуды, которые несут кровь от сердца к телу?", correctAnswer: "Артерии", distractors: ["Вены", "Нервы", "Сухожилия"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🩸\nКакая работа у красных клеток крови?", correctAnswer: "Переносить кислород", distractors: ["Переваривать еду", "Строить кости", "Выращивать волосы"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💓\nЧто измеряют, когда кладут палец на запястье и считают удары?", correctAnswer: "Пульс", distractors: ["Температуру", "Рост", "Вес"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🫁\nКак называется большая мышца под лёгкими, которая помогает нам дышать?", correctAnswer: "Диафрагма", distractors: ["Мышца руки", "Сердечная мышца", "Мышца бедра"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦷\nКакое вещество в теле человека самое твёрдое?", correctAnswer: "Зубная эмаль", distractors: ["Кость", "Ноготь", "Волос"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧠\nКакая часть мозга в основном отвечает за равновесие и согласованность движений?", correctAnswer: "Мозжечок", distractors: ["Большие полушария", "Ствол мозга", "Спинной мозг"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦴\nЧто находится внутри позвоночника и защищено им?", correctAnswer: "Спинной мозг", distractors: ["Желудок", "Глаза", "Зубы"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🫘\nКакой орган очищает кровь и выводит из неё лишнюю воду?", correctAnswer: "Почки", distractors: ["Лёгкие", "Сердце", "Мозг"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍽️\nВ каком органе большая часть питательных веществ всасывается в кровь?", correctAnswer: "Тонкая кишка", distractors: ["Желудок", "Рот", "Лёгкие"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "👁️\nКак называется чёрная точка в центре глаза, через которую внутрь входит свет?", correctAnswer: "Зрачок", distractors: ["Радужка", "Ресница", "Бровь"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧍\nКакой внутренний орган в теле самый большой?", correctAnswer: "Печень", distractors: ["Сердце", "Мозг", "Почка"], tier: .hard, grades: 4...6),
    ]
}
