import Foundation

/// 🚗 Транспорт — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let vehicles: [BankQuestion] = [
        BankQuestion(prompt: "🚗\nСколько колёс у машины?", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚲\nСколько колёс у велосипеда?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🛺\nСколько колёс у трёхколёсного велосипеда?", correctAnswer: "3", distractors: ["2", "4", "5"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚂\nПо чему едет поезд?", correctAnswer: "По рельсам", distractors: ["По воде", "По воздуху", "По песку"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚢\nГде плавает корабль?", correctAnswer: "В море", distractors: ["В небе", "По дороге", "По рельсам"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "✈️\nГде летает самолёт?", correctAnswer: "В небе", distractors: ["В море", "По дороге", "Под землёй"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚗\nГде ездят машины?", correctAnswer: "По дороге", distractors: ["По тротуару", "По морю", "По небу"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚶\nГде ходят пешеходы?", correctAnswer: "По тротуару", distractors: ["Посередине дороги", "По рельсам", "По морю"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚤\nКакое маленькое судно плавает по воде?", correctAnswer: "Лодка", distractors: ["Машина", "Самолёт", "Велосипед"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚁\nКакой летательный аппарат поднимается прямо вверх с помощью большого винта?", correctAnswer: "Вертолёт", distractors: ["Самолёт", "Поезд", "Автобус"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚀\nЧто летает до самого космоса?", correctAnswer: "Космический корабль", distractors: ["Самолёт", "Вертолёт", "Воздушный змей"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🧑‍✈️\nКто управляет самолётом?", correctAnswer: "Пилот", distractors: ["Водитель", "Капитан корабля", "Полицейский"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚌\nКто ведёт автобус?", correctAnswer: "Водитель", distractors: ["Пилот", "Капитан корабля", "Врач"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚑\nКакая машина везёт людей в больницу?", correctAnswer: "Скорая помощь", distractors: ["Грузовик", "Такси", "Трактор"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚒\nКакая красная машина ездит с длинной лестницей и водяными шлангами?", correctAnswer: "Пожарная машина", distractors: ["Скорая помощь", "Автобус", "Такси"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚜\nКакая машина помогает фермеру в поле?", correctAnswer: "Трактор", distractors: ["Такси", "Велосипед", "Поезд"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚕\nКакая машина возит пассажиров за плату, и её можно остановить на улице?", correctAnswer: "Такси", distractors: ["Трактор", "Велосипед", "Вертолёт"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚌\nКакой большой транспорт возит много пассажиров по городу?", correctAnswer: "Автобус", distractors: ["Велосипед", "Самокат", "Такси"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚚\nКакая большая машина перевозит товары и грузы?", correctAnswer: "Грузовик", distractors: ["Велосипед", "Такси", "Самокат"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🛴\nНа чём стоят одной ногой, а другой отталкиваются?", correctAnswer: "Самокат", distractors: ["Велосипед", "Машина", "Лодка"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚲\nКак приводят в движение велосипед?", correctAnswer: "Крутят педали ногами", distractors: ["Тянут за верёвку", "Машут руками", "Заводят мотор"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚦\nНа какой цвет светофора можно ехать?", correctAnswer: "Зелёный", distractors: ["Красный", "Жёлтый", "Синий"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🛑\nНа какой цвет светофора нужно остановиться?", correctAnswer: "Красный", distractors: ["Зелёный", "Синий", "Белый"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚦\nСколько цветов у светофора для машин?", correctAnswer: "3", distractors: ["1", "2", "5"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🦓\nГде переходят дорогу?", correctAnswer: "По пешеходному переходу", distractors: ["Посередине дороги", "Рядом с полосками зебры", "Между машинами"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "⛑️\nЧто надевают на голову, когда катаются на велосипеде?", correctAnswer: "Шлем", distractors: ["Шерстяную шапку", "Очки", "Корону"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚗\nЧто пристёгивают в машине перед поездкой?", correctAnswer: "Ремень безопасности", distractors: ["Шарф", "Куртку", "Шапку"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚗\nЧто крутит водитель, чтобы повернуть направо или налево?", correctAnswer: "Руль", distractors: ["Окно", "Зеркало", "Дверь"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "⛽\nКак называется место, где машине заливают топливо?", correctAnswer: "Заправка", distractors: ["Железнодорожная станция", "Магазин", "Зоопарк"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚉\nГде садятся на поезд?", correctAnswer: "На железнодорожной станции", distractors: ["В порту", "В аэропорту", "В магазине"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🛫\nГде самолёты взлетают и садятся?", correctAnswer: "В аэропорту", distractors: ["На железнодорожной станции", "В порту", "В парке"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "⚓\nГде стоят на якоре корабли?", correctAnswer: "В порту", distractors: ["В аэропорту", "На парковке", "На железнодорожной станции"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "📢\nЧто у машины издаёт громкий звук?", correctAnswer: "Клаксон", distractors: ["Колокольчик", "Флейта", "Барабан"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🔔\nЧто нажимают на велосипеде, чтобы услышали, что мы едем?", correctAnswer: "Звонок", distractors: ["Автомобильный клаксон", "Шофар", "Часы"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌙\nЧто включают в машине, когда на улице темно?", correctAnswer: "Фары", distractors: ["Радио", "Кондиционер", "Дворники"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚲🚲\nСколько колёс всего у 2 велосипедов?", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚗🚗\nСколько колёс всего у 2 машин?", correctAnswer: "8", distractors: ["4", "6", "10"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚗🚲\nСколько колёс всего у одной машины и одного велосипеда?", correctAnswer: "6", distractors: ["4", "5", "8"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚂\nКак называется машина во главе поезда, которая тянет все вагоны?", correctAnswer: "Локомотив", distractors: ["Вагон", "Лодка", "Грузовик"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🧑‍✈️\nКто командует кораблём?", correctAnswer: "Капитан", distractors: ["Пилот", "Водитель", "Механик"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚋\nКак называется поезд, который едет по рельсам прямо по улицам города?", correctAnswer: "Лёгкий поезд", distractors: ["Грузовой поезд", "Такси", "Лодка"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🇮🇱\nВ каком городе поехал первый в Израиле лёгкий поезд?", correctAnswer: "Иерусалим", distractors: ["Эйлат", "Тверия", "Цфат"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚆\nКак называется компания, которая управляет поездами в Израиле?", correctAnswer: "Израильские железные дороги", distractors: ["Эгед", "Эль-Аль", "Дан"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🛫\nКак называется большой аэропорт Израиля?", correctAnswer: "Аэропорт имени Бен-Гуриона", distractors: ["Порт Хайфы", "Станция «Шалом»", "Порт Ашдода"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "⛴️\nКак называется судно, которое перевозит машины и людей через море?", correctAnswer: "Паром", distractors: ["Гребная лодка", "Подводная лодка", "Парусник"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "⛵\nЧто движет парусную лодку?", correctAnswer: "Ветер", distractors: ["Солнце", "Дождь", "Песок"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚁\nЧто умеет вертолёт, чего не умеет обычный самолёт?", correctAnswer: "Висеть на одном месте в воздухе", distractors: ["Долететь до Луны", "Ездить по рельсам", "Плыть по морю"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎈\nЧто поднимает воздушный шар в небо?", correctAnswer: "Горячий воздух", distractors: ["Реактивный двигатель", "Колёса", "Парус"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚀\nКто летает выше всех?", correctAnswer: "Космический корабль", distractors: ["Самолёт", "Вертолёт", "Воздушный шар"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🌕\nКуда может долететь космический корабль, а самолёт — нет?", correctAnswer: "До Луны", distractors: ["До Эйлата", "До Европы", "До моря"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "⛽\nЧто заливают в бак обычной машины, чтобы работал мотор?", correctAnswer: "Топливо", distractors: ["Воду", "Молоко", "Песок"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🔌\nЧто нужно сделать, чтобы электрическая машина могла ехать?", correctAnswer: "Зарядить её электричеством", distractors: ["Залить бензин", "Залить воду", "Крутить педали"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🔋\nЧто есть у электрической машины вместо бака с топливом?", correctAnswer: "Большая батарея", distractors: ["Бак с водой", "Парус", "Труба"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🌿\nПочему электрическая машина полезна для воздуха, которым мы дышим?", correctAnswer: "У неё нет выхлопных газов во время поездки", distractors: ["Она больше по размеру", "У неё больше колёс", "Она громче сигналит"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🏎️\nЧто едет быстрее всех?", correctAnswer: "Гоночная машина", distractors: ["Велосипед", "Самокат", "Трёхколёсный велосипед"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐢\nЧто движется медленнее всех?", correctAnswer: "Велосипед", distractors: ["Самолёт", "Поезд", "Гоночная машина"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚦\nЧто означает жёлтый свет, который загорается после зелёного?", correctAnswer: "Приготовиться остановиться", distractors: ["Ехать быстрее", "Сигналить", "Парковаться"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚶\nЧто показывает зелёный человечек на светофоре для пешеходов?", correctAnswer: "Что переходить можно", distractors: ["Что нужно бежать", "Что переходить нельзя", "Что дорога закрыта"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "👀\nЧто делают перед тем, как перейти дорогу?", correctAnswer: "Останавливаются и смотрят в обе стороны", distractors: ["Бегут быстро", "Закрывают глаза", "Поют песню"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚗\nЗачем пристёгивают ремень безопасности?", correctAnswer: "Чтобы в дороге было безопасно", distractors: ["Чтобы было тепло", "Чтобы машина ехала быстрее", "Чтобы слушать радио"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🚲🚲🚲\nСколько колёс всего у 3 велосипедов и одного трёхколёсного велосипеда?", correctAnswer: "9", distractors: ["7", "8", "10"], tier: .hard, grades: 2...3),
        BankQuestion(prompt: "🚗🚗🚲\nСколько колёс всего у 2 машин и одного велосипеда?", correctAnswer: "10", distractors: ["8", "9", "12"], tier: .hard, grades: 2...3),
        BankQuestion(prompt: "🚄\nМежду какими городами ходит скоростной поезд?", correctAnswer: "Тель-Авив и Иерусалим", distractors: ["Эйлат и Хайфа", "Цфат и Тверия", "Ашдод и Ашкелон"], tier: .hard, grades: 2...3),
        BankQuestion(prompt: "🚋\nОткуда лёгкий поезд получает свою энергию?", correctAnswer: "От электричества", distractors: ["От бензина", "От угля", "От ветра"], tier: .hard, grades: 2...3),
        BankQuestion(prompt: "⚓\nВ каком городе Израиля есть большой порт для кораблей?", correctAnswer: "Хайфа", distractors: ["Иерусалим", "Беэр-Шева", "Цфат"], tier: .hard, grades: 2...3),
        BankQuestion(prompt: "🛞\nЗачем на шинах есть канавки?", correctAnswer: "Чтобы хорошо держаться за дорогу", distractors: ["Чтобы было красиво", "Чтобы шуметь", "Чтобы меньше весить"], tier: .hard, grades: 2...3),
        BankQuestion(prompt: "✈️\nЧто держит самолёт в воздухе во время полёта?", correctAnswer: "Крылья", distractors: ["Колёса", "Окна", "Кресла"], tier: .hard, grades: 2...3),
        BankQuestion(prompt: "🚀\nЧто толкает ракету вверх при взлёте?", correctAnswer: "Горячий газ, который вырывается снизу", distractors: ["Сильный ветер", "Колёса", "Парус"], tier: .hard, grades: 2...3),
        BankQuestion(prompt: "🚂\nЧто приводило в движение первые локомотивы, до электричества и дизеля?", correctAnswer: "Пар", distractors: ["Батарейка", "Ветер", "Солнце"], tier: .hard, grades: 2...3),
        BankQuestion(prompt: "🚦\nЧто означает светофор, когда красный и жёлтый горят вместе?", correctAnswer: "Сейчас загорится зелёный", distractors: ["Нужно припарковаться", "Светофор сломался", "Ночью ехать нельзя"], tier: .hard, grades: 2...3),
    ]
}
