import Foundation

/// 🧩 Логика — русский. Переведено с ивритского банка (262 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let logic: [BankQuestion] = [
        BankQuestion(prompt: "Что идёт дальше?\n1, 2, 3, ?", correctAnswer: "4", distractors: ["5", "6", "2"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n2, 4, 6, ?", correctAnswer: "8", distractors: ["7", "10", "9"], grades: 1...3),
        BankQuestion(prompt: "Что идёт дальше?\n5, 10, 15, ?", correctAnswer: "20", distractors: ["25", "16", "18"], grades: 2...4),
        BankQuestion(prompt: "Что идёт дальше?\n10, 9, 8, ?", correctAnswer: "7", distractors: ["6", "11", "5"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n🔴🟢🔴🟢🔴?", correctAnswer: "🟢 Зелёный", distractors: ["🔴 Красный", "🔵 Синий", "🟡 Жёлтый"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n🐶🐱🐶🐱🐶?", correctAnswer: "🐱 Кошка", distractors: ["🐶 Собака", "🐭 Мышка", "🐰 Кролик"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "🚗", distractors: ["🐶", "🐱", "🐰"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "🍎", distractors: ["🚗", "🚌", "🚲"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "📖", distractors: ["⚽", "🏀", "🎾"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "🌳", distractors: ["☀️", "🌙", "⭐"], grades: 0...2),
        BankQuestion(prompt: "Если 🍎=2, то 🍎+🍎=?", correctAnswer: "4", distractors: ["3", "5", "2"], grades: 2...4),
        BankQuestion(prompt: "🐱 больше, чем 🐭. Кто больше?", correctAnswer: "Кошка", distractors: ["Мышка", "Они одинаковые", "Никто"], grades: 0...2),
        BankQuestion(prompt: "Какая фигура дальше?\n🔺🔻🔺🔻🔺?", correctAnswer: "🔻 Треугольник вниз", distractors: ["🔺 Треугольник вверх", "⬛ Квадрат", "⚫ Круг"], grades: 0...2),
        BankQuestion(prompt: "Сколько лап у трёх собак?", correctAnswer: "12", distractors: ["6", "8", "10"], grades: 2...4),
        BankQuestion(prompt: "🦒 выше 🐴, а 🐴 выше 🐕. Кто самый низкий?", correctAnswer: "Собака", distractors: ["Жираф", "Лошадь", "Все одного роста"], grades: 2...4),
        BankQuestion(prompt: "Что не похоже на остальные?\n🍎 🍌 🍇 🐶", correctAnswer: "🐶 лишний", distractors: ["🍎 лишний", "🍌 лишний", "🍇 лишний"], grades: 0...2),
        BankQuestion(prompt: "Если сегодня вторник, какой день был вчера?", correctAnswer: "Понедельник", distractors: ["Среда", "Воскресенье", "Четверг"], grades: 1...3),
        BankQuestion(prompt: "На дереве сидели 5 птиц, 2 улетели. Сколько осталось?", correctAnswer: "3", distractors: ["7", "2", "4"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\nA, B, C, ?", correctAnswer: "D", distractors: ["E", "A", "C"], grades: 3...5),
        BankQuestion(prompt: "У какой фигуры нет углов?", correctAnswer: "⚪", distractors: ["🔺", "⬛", "⬢"], grades: 0...2),
        BankQuestion(prompt: "Какое число дальше в ряду?\n2, 4, 8, 16, ...", correctAnswer: "32", distractors: ["24", "20", "18"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какое число дальше в ряду?\n1, 1, 2, 3, 5, 8, ...", correctAnswer: "13", distractors: ["11", "12", "16"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое число дальше в ряду?\n100, 90, 81, 73, ...", correctAnswer: "66", distractors: ["65", "64", "63"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "У Даны в два раза больше шариков, чем у Йоси. У Йоси 6 шариков. Сколько шариков у них вместе?", correctAnswer: "18", distractors: ["12", "24", "16"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Все драконы умеют летать. Рони — дракон. Что точно верно?", correctAnswer: "Рони умеет летать", distractors: ["Рони зелёный", "Все, кто летает, — драконы", "Рони не умеет летать"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "В тёмной комнате лежат носки: красные и синие, поровну. Сколько носков надо достать не глядя, чтобы точно получилась пара одного цвета?", correctAnswer: "3", distractors: ["2", "4", "6"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Часы показывают 3:00. Сколько времени будет через 50 минут?", correctAnswer: "3:50", distractors: ["4:00", "3:40", "4:10"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Я число. Умножь меня на 3 и прибавь 1 — получится 22. Какое я число?", correctAnswer: "7", distractors: ["6", "8", "9"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какая фигура здесь лишняя?", correctAnswer: "Круг", distractors: ["Треугольник", "Квадрат", "Прямоугольник"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "Папа Даны старше или младше своего собственного папы?", correctAnswer: "Младше — ведь он его сын", distractors: ["Старше — он же взрослый", "Они одного возраста", "Узнать невозможно"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "2, 4, 6, 8, ?", correctAnswer: "10", distractors: ["9", "11", "12"], grades: 2...4),
        BankQuestion(prompt: "5, 10, 15, 20, ?", correctAnswer: "25", distractors: ["22", "30", "24"], grades: 2...4),
        BankQuestion(prompt: "1, 4, 9, 16, ?", correctAnswer: "25", distractors: ["20", "24", "30"], grades: 4...6),
        BankQuestion(prompt: "1, 1, 2, 3, 5, ?", correctAnswer: "8", distractors: ["6", "7", "10"], grades: 4...6),
        BankQuestion(prompt: "100, 90, 80, ?", correctAnswer: "70", distractors: ["75", "60", "85"], grades: 2...4),
        BankQuestion(prompt: "1, 3, 5, 7, ?", correctAnswer: "9", distractors: ["8", "10", "11"], grades: 2...4),
        BankQuestion(prompt: "10, 20, 40, 80, ?", correctAnswer: "160", distractors: ["100", "120", "200"], grades: 4...6),
        BankQuestion(prompt: "A, C, E, G, ?", correctAnswer: "I", distractors: ["H", "J", "K"], grades: 3...5),
        BankQuestion(prompt: "ב, ד, ו, ?", correctAnswer: "ח", distractors: ["ז", "ט", "י"], grades: 2...4),
        BankQuestion(prompt: "🔴🔵🔴🔵🔴?", correctAnswer: "🔵 Синий", distractors: ["🔴 Красный", "🟢 Зелёный", "🟡 Жёлтый"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "Баскетбол", distractors: ["Яблоко", "Банан", "Груша"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "Стол", distractors: ["Собака", "Кошка", "Лев"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "Велосипед", distractors: ["Машина", "Автобус", "Скутер"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "Лев", distractors: ["Рыба", "Акула", "Осьминог"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "Красный", distractors: ["Три", "Пять", "Семь"], grades: 0...2),
        BankQuestion(prompt: "Кто больше?", correctAnswer: "Слон", distractors: ["Мышь", "Муравей", "Бабочка"], grades: 0...2),
        BankQuestion(prompt: "Кто меньше?", correctAnswer: "Муравей", distractors: ["Лошадь", "Собака", "Кошка"], grades: 0...2),
        BankQuestion(prompt: "Что быстрее?", correctAnswer: "Самолёт", distractors: ["Велосипед", "Лодка", "Поезд"], grades: 0...2),
        BankQuestion(prompt: "Что тяжелее?", correctAnswer: "Слон", distractors: ["Перо", "Яблоко", "Книга"], grades: 0...2),
        BankQuestion(prompt: "Кто выше?", correctAnswer: "Жираф", distractors: ["Собака", "Кошка", "Петух"], grades: 0...2),
        BankQuestion(prompt: "Я пью воду, но у меня нет рта. Кто я?", correctAnswer: "Растение", distractors: ["Стол", "Окно", "Книга"], grades: 2...4),
        BankQuestion(prompt: "У меня четыре ноги, но я не хожу. Кто я?", correctAnswer: "Стол", distractors: ["Лошадь", "Собака", "Черепаха"], grades: 2...4),
        BankQuestion(prompt: "Я появляюсь на небе ночью: то круглая, то тонкий серп. Кто я?", correctAnswer: "Луна", distractors: ["Солнце", "Облако", "Радуга"], grades: 2...4),
        BankQuestion(prompt: "Я оранжевая, а сверху у меня зелёный хвостик. Кто я?", correctAnswer: "Морковь", distractors: ["Яблоко", "Огурец", "Апельсин"], grades: 2...4),
        BankQuestion(prompt: "У меня много листов и есть обложка, но я не дерево. Кто я?", correctAnswer: "Книга", distractors: ["Камень", "Окно", "Стул"], grades: 2...4),
        BankQuestion(prompt: "Что не цвет?", correctAnswer: "Стол", distractors: ["Красный", "Синий", "Зелёный"], grades: 0...2),
        BankQuestion(prompt: "Кто не животное?", correctAnswer: "Машина", distractors: ["Лошадь", "Собака", "Птица"], grades: 0...2),
        BankQuestion(prompt: "Что не фрукт?", correctAnswer: "Огурец", distractors: ["Яблоко", "Банан", "Апельсин"], grades: 0...2),
        BankQuestion(prompt: "Что не овощ?", correctAnswer: "Апельсин", distractors: ["Огурец", "Морковь", "Помидор"], grades: 0...2),
        BankQuestion(prompt: "Что не день недели?", correctAnswer: "Январь", distractors: ["Понедельник", "Вторник", "Среда"], grades: 0...2),
        BankQuestion(prompt: "Если все псы лают, какой звук издаёт собака?", correctAnswer: "Лает", distractors: ["Мяукает", "Кукарекает", "Мычит"], grades: 2...4),
        BankQuestion(prompt: "Если 2+2=4, то 3+3=?", correctAnswer: "6", distractors: ["5", "7", "8"], grades: 0...2),
        BankQuestion(prompt: "Какое число идёт после 7?", correctAnswer: "8", distractors: ["6", "9", "10"], grades: 0...2),
        BankQuestion(prompt: "Какое число идёт перед 5?", correctAnswer: "4", distractors: ["6", "3", "7"], grades: 0...2),
        BankQuestion(prompt: "Сколько дней в неделе?", correctAnswer: "7", distractors: ["5", "6", "8"], grades: 0...2),
        BankQuestion(prompt: "Сколько месяцев в году?", correctAnswer: "12", distractors: ["10", "11", "13"], grades: 2...4),
        BankQuestion(prompt: "Сколько часов в сутках?", correctAnswer: "24", distractors: ["12", "18", "30"], grades: 2...4),
        BankQuestion(prompt: "Сколько минут в часе?", correctAnswer: "60", distractors: ["50", "100", "30"], grades: 2...4),
        BankQuestion(prompt: "Сколько секунд в минуте?", correctAnswer: "60", distractors: ["100", "30", "12"], grades: 2...4),
        BankQuestion(prompt: "Что противоположно слову «большой»?", correctAnswer: "Маленький", distractors: ["Длинный", "Широкий", "Высокий"], grades: 0...2),
        BankQuestion(prompt: "Что противоположно слову «горячий»?", correctAnswer: "Холодный", distractors: ["Вкусный", "Сладкий", "Сухой"], grades: 0...2),
        BankQuestion(prompt: "Что противоположно слову «быстрый»?", correctAnswer: "Медленный", distractors: ["Сильный", "Длинный", "Тяжёлый"], grades: 0...2),
        BankQuestion(prompt: "Что противоположно слову «день»?", correctAnswer: "Ночь", distractors: ["Утро", "Вечер", "Полдень"], grades: 0...2),
        BankQuestion(prompt: "Что противоположно слову «весёлый»?", correctAnswer: "Грустный", distractors: ["Смешной", "Спокойный", "Растерянный"], grades: 0...2),
        BankQuestion(prompt: "Что противоположно слову «направо»?", correctAnswer: "Налево", distractors: ["Наверх", "Вниз", "Вперёд"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n3, 6, 9, ?", correctAnswer: "12", distractors: ["10", "11", "15"], grades: 2...4),
        BankQuestion(prompt: "Что идёт дальше?\n20, 18, 16, ?", correctAnswer: "14", distractors: ["15", "12", "17"], grades: 2...4),
        BankQuestion(prompt: "Что идёт дальше?\n🌟⬛🌟⬛🌟?", correctAnswer: "⬛ Чёрный квадрат", distractors: ["🌟 Звезда", "🔵 Синий круг", "🔺 Треугольник"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n🍓🍋🍓🍋🍓?", correctAnswer: "🍋 Лимон", distractors: ["🍓 Клубника", "🍇 Виноград", "🍊 Апельсин"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n☀️🌙☀️🌙☀️?", correctAnswer: "🌙 Луна", distractors: ["☀️ Солнце", "⭐ Звезда", "☁️ Облако"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n🐘🦒🐘🦒🐘?", correctAnswer: "🦒 Жираф", distractors: ["🐘 Слон", "🦓 Зебра", "🐅 Тигр"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n4, 8, 12, ?", correctAnswer: "16", distractors: ["14", "18", "20"], grades: 2...4),
        BankQuestion(prompt: "Какая фигура дальше?\n⬛⬜⬛⬜⬛?", correctAnswer: "⬜ Белый квадрат", distractors: ["⬛ Чёрный квадрат", "🔺 Треугольник", "🔵 Круг"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "🐟", distractors: ["🐦", "🦅", "🦜"], grades: 0...2),
        BankQuestion(prompt: "Что не мебель?", correctAnswer: "Вертолёт", distractors: ["Стул", "Шкаф", "Кровать"], grades: 0...2),
        BankQuestion(prompt: "Что не музыкальный инструмент?", correctAnswer: "Сковорода", distractors: ["Флейта", "Барабан", "Пианино"], grades: 0...2),
        BankQuestion(prompt: "Сколько ушей у двух детей?", correctAnswer: "4", distractors: ["2", "3", "6"], grades: 0...2),
        BankQuestion(prompt: "Сколько пальцев на двух руках?", correctAnswer: "10", distractors: ["5", "8", "12"], grades: 0...2),
        BankQuestion(prompt: "Если 🐞=3, то 🐞+🐞=?", correctAnswer: "6", distractors: ["5", "4", "9"], grades: 2...4),
        BankQuestion(prompt: "В коробке было два мяча, положили ещё два. Сколько стало?", correctAnswer: "4", distractors: ["3", "2", "5"], grades: 0...2),
        BankQuestion(prompt: "Если сегодня среда, какой день будет завтра?", correctAnswer: "Четверг", distractors: ["Вторник", "Пятница", "Понедельник"], grades: 0...2),
        BankQuestion(prompt: "Какой день идёт перед воскресеньем?", correctAnswer: "Суббота", distractors: ["Понедельник", "Пятница", "Вторник"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\nד, ה, ו, ?", correctAnswer: "ז", distractors: ["ח", "ה", "ג"], grades: 0...2),
        BankQuestion(prompt: "Какая буква стоит перед буквой כ?", correctAnswer: "י", distractors: ["ל", "מ", "ט"], grades: 0...2),
        BankQuestion(prompt: "Какое число идёт после 14?", correctAnswer: "15", distractors: ["13", "16", "20"], grades: 0...2),
        BankQuestion(prompt: "Какое число идёт перед 10?", correctAnswer: "9", distractors: ["11", "8", "12"], grades: 0...2),
        BankQuestion(prompt: "Кто длиннее всех?", correctAnswer: "Змея", distractors: ["Муравей", "Муха", "Пчела"], grades: 0...2),
        BankQuestion(prompt: "Что шире всех?", correctAnswer: "Автобус", distractors: ["Карандаш", "Соломинка", "Нитка"], grades: 0...2),
        BankQuestion(prompt: "Что тяжелее всех?", correctAnswer: "Камень", distractors: ["Перо", "Листик", "Воздушный шарик"], grades: 0...2),
        BankQuestion(prompt: "На тарелке было 6 печений, я съел 2. Сколько осталось?", correctAnswer: "4", distractors: ["8", "5", "3"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n🟦🟥🟨🟦🟥?", correctAnswer: "🟨 Жёлтый", distractors: ["🟦 Синий", "🟥 Красный", "🟩 Зелёный"], grades: 0...2),
        BankQuestion(prompt: "Что не фигура?", correctAnswer: "Солнце", distractors: ["Круг", "Квадрат", "Треугольник"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n7, 14, 21, ?", correctAnswer: "28", distractors: ["27", "30", "35"], grades: 2...4),
        BankQuestion(prompt: "Что идёт дальше?\n3, 6, 12, 24, ?", correctAnswer: "48", distractors: ["36", "30", "40"], grades: 2...4),
        BankQuestion(prompt: "Что идёт дальше?\n50, 40, 30, ?", correctAnswer: "20", distractors: ["25", "10", "35"], grades: 2...4),
        BankQuestion(prompt: "Что идёт дальше?\n🟢🟢🔴🟢🟢🔴🟢🟢?", correctAnswer: "🔴 Красный", distractors: ["🟢 Зелёный", "🔵 Синий", "🟡 Жёлтый"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n🐢🐰🐢🐰🐢?", correctAnswer: "🐰 Заяц", distractors: ["🐢 Черепаха", "🐭 Мышка", "🦊 Лиса"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n⭐🌙⭐⭐🌙⭐⭐⭐🌙?", correctAnswer: "⭐ Звезда", distractors: ["🌙 Луна", "☀️ Солнце", "☁️ Облако"], grades: 1...3),
        BankQuestion(prompt: "Какая фигура дальше?\n🔴🟡🔵🔴🟡?", correctAnswer: "🔵 Синий", distractors: ["🔴 Красный", "🟡 Жёлтый", "🟢 Зелёный"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\n9, 8, 7, 6, ?", correctAnswer: "5", distractors: ["4", "3", "10"], grades: 0...2),
        BankQuestion(prompt: "Что идёт дальше?\nא, ג, ה, ?", correctAnswer: "ז", distractors: ["ו", "ח", "ב"], grades: 1...3),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "🌻", distractors: ["🐝", "🦋", "🐞"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "🍕", distractors: ["👕", "👖", "🧦"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "🦈", distractors: ["🐦", "🦅", "🦉"], grades: 0...2),
        BankQuestion(prompt: "Что лишнее?", correctAnswer: "☂️", distractors: ["✏️", "📕", "✂️"], grades: 0...2),
        BankQuestion(prompt: "Что не помогает ходить?", correctAnswer: "🪶 Перо", distractors: ["🐾 Лапа", "🦵 Нога", "🦶 Ступня"], grades: 0...2),
        BankQuestion(prompt: "Сколько колёс у велосипеда?", correctAnswer: "2", distractors: ["1", "3", "4"], grades: 0...2),
        BankQuestion(prompt: "Сколько пальцев на одной руке?", correctAnswer: "5", distractors: ["4", "10", "6"], grades: 0...2),
        BankQuestion(prompt: "Сколько хвостов у четырёх кошек?", correctAnswer: "4", distractors: ["8", "2", "16"], grades: 0...2),
        BankQuestion(prompt: "Сколько крыльев у двух птиц?", correctAnswer: "4", distractors: ["2", "6", "8"], grades: 1...3),
        BankQuestion(prompt: "Какое число идёт перед 8?", correctAnswer: "7", distractors: ["9", "6", "10"], grades: 0...2),
        BankQuestion(prompt: "Какое число идёт после 19?", correctAnswer: "20", distractors: ["18", "21", "29"], grades: 0...2),
        BankQuestion(prompt: "Какая буква идёт после буквы מ?", correctAnswer: "נ", distractors: ["ל", "ס", "כ"], grades: 1...3),
        BankQuestion(prompt: "Если сегодня пятница, какой день был вчера?", correctAnswer: "Четверг", distractors: ["Среда", "Суббота", "Вторник"], grades: 2...4),
        BankQuestion(prompt: "Если 🍌=5, то 🍌+🍌=?", correctAnswer: "10", distractors: ["7", "15", "25"], grades: 1...3),
        BankQuestion(prompt: "Рыба не умеет ни летать, ни бегать. Что она делает в воде?", correctAnswer: "Плавает", distractors: ["Летает", "Прыгает", "Бежит"], grades: 0...2),
        BankQuestion(prompt: "В саду росли 4 цветка, один сорвали. Сколько осталось?", correctAnswer: "3", distractors: ["5", "2", "4"], grades: 0...2),
        BankQuestion(prompt: "🐘 тяжелее, чем 🐭. Кто легче?", correctAnswer: "Мышка", distractors: ["Слон", "Они весят одинаково", "Никто не знает"], grades: 0...2),
        BankQuestion(prompt: "Где находится солнце?\n☀️\n🏠", correctAnswer: "Наверху", distractors: ["Внизу", "Сбоку", "Сзади"], grades: 0...2),
        BankQuestion(prompt: "У какой фигуры 3 угла?", correctAnswer: "🔺", distractors: ["⚪", "⬛", "⬢"], grades: 0...2),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Стул", distractors: ["Собака", "Кошка", "Лошадь"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 1, 2, 3, ?", correctAnswer: "4", distractors: ["5", "6", "2"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 2, 4, 6, ?", correctAnswer: "8", distractors: ["7", "9", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какое число идёт после 5?", correctAnswer: "6", distractors: ["4", "7", "8"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число идёт перед 4?", correctAnswer: "3", distractors: ["5", "2", "6"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "День — это солнце, а ночь — это ___?", correctAnswer: "Луна", distractors: ["Облако", "Дождь", "Дерево"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Машина", distractors: ["Апельсин", "Банан", "Яблоко"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 5, 6, 7, ?", correctAnswer: "8", distractors: ["9", "10", "6"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какой день идёт после воскресенья?", correctAnswer: "Понедельник", distractors: ["Вторник", "Суббота", "Среда"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Рыба", distractors: ["Птица", "Бабочка", "Пчела"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 10, 9, 8, ?", correctAnswer: "7", distractors: ["6", "9", "10"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Горячий — холодный, а большой — ___?", correctAnswer: "Маленький", distractors: ["Широкий", "Длинный", "Тяжёлый"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Ботинок", distractors: ["Глаз", "Ухо", "Нос"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какая буква идёт после буквы א?", correctAnswer: "ב", distractors: ["ג", "ד", "ה"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 1, 3, 5, ?", correctAnswer: "7", distractors: ["6", "8", "9"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Стол", distractors: ["Роза", "Лилия", "Тюльпан"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Лето — тёплое, а зима — ___?", correctAnswer: "Холодная", distractors: ["Сухая", "Светлая", "Приятная"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какой день идёт перед пятницей?", correctAnswer: "Четверг", distractors: ["Суббота", "Воскресенье", "Среда"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 0, 2, 4, ?", correctAnswer: "6", distractors: ["5", "7", "8"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Книга", distractors: ["Банан", "Виноград", "Груша"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Рыба плавает в воде, а птица летает в ___?", correctAnswer: "В небе", distractors: ["В лесу", "В песке", "В земле"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какое число идёт после 9?", correctAnswer: "10", distractors: ["8", "11", "7"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Палец", distractors: ["Красный", "Жёлтый", "Оранжевый"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 3, 6, 9, ?", correctAnswer: "12", distractors: ["10", "11", "13"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "На руку надевают перчатку, а на ногу — ___?", correctAnswer: "Носок", distractors: ["Шапку", "Шарф", "Рубашку"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Собака", distractors: ["Велосипед", "Машина", "Автобус"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 2, 4, 8, ?", correctAnswer: "16", distractors: ["10", "12", "14"], tier: .easy, grades: 4...6),
        BankQuestion(prompt: "Какое время года идёт после весны?", correctAnswer: "Лето", distractors: ["Зима", "Осень", "Дождь"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Слон", distractors: ["Стол", "Стул", "Шкаф"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Мальчик — сын, а девочка — ___?", correctAnswer: "Дочь", distractors: ["Дядя", "Бабушка", "Брат"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какое число дальше? 5, 10, 15, ?", correctAnswer: "20", distractors: ["18", "25", "16"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какая буква идёт перед буквой ד?", correctAnswer: "ג", distractors: ["ה", "ב", "ו"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Еда", distractors: ["Красный", "Жёлтый", "Синий"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 10, 20, 30, ?", correctAnswer: "40", distractors: ["35", "50", "31"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Яблоко", distractors: ["Собака", "Кошка", "Кролик"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 4, 8, 12, ?", correctAnswer: "16", distractors: ["14", "18", "20"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "День — это свет, а ночь — это ___?", correctAnswer: "Темнота", distractors: ["Солнце", "Звезда", "Лампа"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какой день идёт перед вторником?", correctAnswer: "Понедельник", distractors: ["Среда", "Воскресенье", "Суббота"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Морковь", distractors: ["Яблоко", "Груша", "Апельсин"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 1, 4, 7, ?", correctAnswer: "10", distractors: ["8", "9", "11"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Птица живёт на дереве, а рыба живёт в ___?", correctAnswer: "В воде", distractors: ["В песке", "В воздухе", "В огне"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какое число идёт после 99?", correctAnswer: "100", distractors: ["98", "101", "90"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Стакан", distractors: ["Один", "Два", "Три"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое число дальше? 2, 5, 8, ?", correctAnswer: "11", distractors: ["9", "10", "12"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Большая — маленькая, а длинная — ___?", correctAnswer: "Короткая", distractors: ["Широкая", "Тяжёлая", "Высокая"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какое число идёт перед 1?", correctAnswer: "0", distractors: ["2", "3", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Кто лишний?", correctAnswer: "Ложка", distractors: ["Круг", "Квадрат", "Треугольник"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число дальше? 3, 6, 12, 24, ?", correctAnswer: "48", distractors: ["36", "30", "40"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Палец — для руки, а пятка — для ___?", correctAnswer: "Нога", distractors: ["Голова", "Спина", "Шея"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 1, 4, 9, 16, ?", correctAnswer: "25", distractors: ["20", "24", "36"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Кто здесь лишний?", correctAnswer: "Собака", distractors: ["Орёл", "Голубь", "Попугай"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Писателю нужна ручка, а художнику — ___?", correctAnswer: "Кисть", distractors: ["Бумага", "Книга", "Тетрадь"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 100, 90, 80, ?", correctAnswer: "70", distractors: ["75", "60", "85"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Четыре", distractors: ["Воскресенье", "Понедельник", "Вторник"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Врач лечит больного, а учитель учит ___?", correctAnswer: "Ученика", distractors: ["Книгу", "Доску", "Портфель"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 2, 6, 18, ?", correctAnswer: "54", distractors: ["36", "24", "48"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Треугольник", distractors: ["Красный", "Синий", "Зелёный"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Пчела даёт мёд, а корова даёт ___?", correctAnswer: "Молоко", distractors: ["Шерсть", "Яйцо", "Воду"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 5, 10, 20, 40, ?", correctAnswer: "80", distractors: ["60", "50", "70"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Мяч", distractors: ["Вилка", "Ложка", "Нож"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Лев рычит, а змея ___?", correctAnswer: "Шипит", distractors: ["Лает", "Чирикает", "Блеет"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 1, 2, 4, 7, 11, ?", correctAnswer: "16", distractors: ["14", "15", "17"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Яблоко", distractors: ["Стол", "Стул", "Кровать"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Корабль плывёт по морю, а самолёт летит по ___?", correctAnswer: "Небу", distractors: ["Дороге", "Рельсам", "Песку"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 81, 27, 9, ?", correctAnswer: "3", distractors: ["6", "1", "4"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Мотоцикл", distractors: ["Лошадь", "Слон", "Верблюд"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "У короля на голове корона, а у солдата — ___?", correctAnswer: "Каска", distractors: ["Ботинок", "Пальто", "Перчатка"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 12, 10, 8, 6, ?", correctAnswer: "4", distractors: ["5", "3", "2"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Камень", distractors: ["Роза", "Анемон", "Нарцисс"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "У дерева — листья, а у книги — ___?", correctAnswer: "Страницы", distractors: ["Обложки", "Корни", "Колёса"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 7, 14, 21, 28, ?", correctAnswer: "35", distractors: ["30", "32", "42"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Осень", distractors: ["Два", "Четыре", "Шесть"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Пекарь печёт хлеб, а фермер выращивает ___?", correctAnswer: "Урожай", distractors: ["Печь", "Муку", "Воду"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 1, 1, 2, 3, 5, ?", correctAnswer: "8", distractors: ["6", "7", "9"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Заяц прыгает, а рыба ___?", correctAnswer: "Плавает", distractors: ["Бегает", "Летает", "Ползает"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 50, 45, 40, 35, ?", correctAnswer: "30", distractors: ["25", "32", "28"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Тетрадь", distractors: ["Палец", "Ладонь", "Локоть"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Черепаха ползёт медленно, а леопард бежит ___?", correctAnswer: "Быстро", distractors: ["Тяжело", "Громко", "Высоко"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 2, 3, 5, 8, 13, ?", correctAnswer: "21", distractors: ["18", "20", "26"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Кто здесь лишний?", correctAnswer: "Лев", distractors: ["Акула", "Дельфин", "Кит"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Зимой у нас идёт дождь, а летом светит ___?", correctAnswer: "Солнце", distractors: ["Снег", "Туча", "Ветер"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 6, 12, 24, 48, ?", correctAnswer: "96", distractors: ["72", "60", "84"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Кто здесь лишний?", correctAnswer: "Лошадь", distractors: ["Пчела", "Муравей", "Бабочка"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Повару нужна кастрюля, а плотнику — ___?", correctAnswer: "Молоток", distractors: ["Тарелка", "Стул", "Ложка"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 11, 22, 33, 44, ?", correctAnswer: "55", distractors: ["50", "54", "66"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Класс", distractors: ["Январь", "Март", "Август"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "На руку надевают перчатку, а на голову — ___?", correctAnswer: "Шапку", distractors: ["Носок", "Ботинок", "Шарф"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Стол", distractors: ["Пила", "Отвёртка", "Молоток"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Звёзды видны ночью, а солнце — ___?", correctAnswer: "Днём", distractors: ["Ночью", "Зимой", "Никогда"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое число следующее? 1, 3, 6, 10, 15, ?", correctAnswer: "21", distractors: ["18", "20", "24"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Апельсин", distractors: ["Сок", "Молоко", "Вода"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "У всех кошек есть хвост. У Мици тоже есть хвост. Мици точно кошка?", correctAnswer: "Не обязательно", distractors: ["Да, всегда", "Нет, никогда", "Совсем нельзя узнать"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое число следующее? 2, 4, 8, 16, 32, ?", correctAnswer: "64", distractors: ["48", "40", "56"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Дани выше Йоси, а Йоси выше Гиля. Кто самый низкий?", correctAnswer: "Гиль", distractors: ["Дани", "Йоси", "Все одного роста"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое число следующее? 1, 4, 9, 16, 25, ?", correctAnswer: "36", distractors: ["30", "35", "49"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Сегодня среда. Какой день будет через три дня?", correctAnswer: "Суббота", distractors: ["Пятница", "Воскресенье", "Четверг"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое число следующее? 3, 7, 15, 31, ?", correctAnswer: "63", distractors: ["47", "55", "62"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "У всех птиц есть крылья. У чего-то крыльев нет. Что верно?", correctAnswer: "Это не птица", distractors: ["Это птица", "Оно летает", "Нельзя узнать"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое число следующее? 1, 2, 6, 24, ?", correctAnswer: "120", distractors: ["48", "72", "96"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Вчера был понедельник. Какой день будет завтра?", correctAnswer: "Среда", distractors: ["Вторник", "Четверг", "Воскресенье"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое число следующее? 2, 5, 11, 23, ?", correctAnswer: "47", distractors: ["35", "44", "46"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "У Рони печенья больше, чем у Даны, но меньше, чем у Ширы. У кого печенья больше всех?", correctAnswer: "Шира", distractors: ["Рони", "Дана", "У всех поровну"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое число следующее? 5, 11, 17, 23, ?", correctAnswer: "29", distractors: ["27", "28", "30"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое число следующее? 100, 1, 99, 2, 98, ?", correctAnswer: "3", distractors: ["97", "4", "96"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Огурец", distractors: ["Клубника", "Малина", "Вишня"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Все шары в коробке красные. Я достал один шар, не глядя. Какого он цвета?", correctAnswer: "Красный", distractors: ["Синий", "Зелёный", "Неизвестно"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое число следующее? 4, 9, 16, 25, 36, ?", correctAnswer: "49", distractors: ["42", "45", "48"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Если 2 кошки ловят 2 мышек за 2 минуты, сколько мышек поймают 2 кошки за четыре минуты?", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое число следующее? 1, 8, 27, 64, ?", correctAnswer: "125", distractors: ["100", "81", "120"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое число здесь лишнее?", correctAnswer: "12", distractors: ["10", "15", "20"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "У Майи две сестры и один брат. Сколько девочек в семье?", correctAnswer: "3", distractors: ["2", "4", "1"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое число следующее? 90, 81, 72, 63, ?", correctAnswer: "54", distractors: ["50", "55", "52"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Дедушка для папы — как папа для ___?", correctAnswer: "Сын", distractors: ["Дядя", "Бабушка", "Брат"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Всё красное — горячее, а всё горячее — опасное. Что верно про красный предмет?", correctAnswer: "Он опасный", distractors: ["Он холодный", "Он безопасный", "Нельзя узнать"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое число следующее? 2, 3, 5, 7, 11, ?", correctAnswer: "13", distractors: ["12", "14", "15"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Середина", distractors: ["Первый", "Второй", "Третий"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "В коробке 12 яиц. Я взял половину, а потом ещё 2. Сколько яиц осталось?", correctAnswer: "4", distractors: ["6", "5", "8"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое число следующее? 1, 3, 7, 13, 21, ?", correctAnswer: "31", distractors: ["28", "29", "30"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "В тёмной комнате я зажёг одну свечу, потом ещё 4, а 2 погасли. Сколько свечей горит?", correctAnswer: "3", distractors: ["5", "2", "4"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое число следующее? 80, 40, 20, 10, ?", correctAnswer: "5", distractors: ["15", "2", "8"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Квадрат", distractors: ["1", "5", "9"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Послезавтра будет пятница. Какой день был вчера?", correctAnswer: "Вторник", distractors: ["Понедельник", "Среда", "Четверг"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое число следующее? 3, 5, 9, 17, ?", correctAnswer: "33", distractors: ["25", "29", "31"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "На каждой руке 5 пальцев. Сколько пальцев у троих детей?", correctAnswer: "30", distractors: ["15", "25", "20"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое число здесь лишнее?", correctAnswer: "23", distractors: ["10", "20", "30"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Рути сидит справа от Даны, а Майя — слева от Даны. Кто сидит посередине?", correctAnswer: "Дана", distractors: ["Рути", "Майя", "Нельзя узнать"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое число следующее? 2, 6, 12, 20, 30, ?", correctAnswer: "42", distractors: ["38", "40", "36"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Завтра воскресенье. Какой день был два дня назад?", correctAnswer: "Четверг", distractors: ["Пятница", "Среда", "Суббота"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Что здесь лишнее?", correctAnswer: "Шар", distractors: ["Квадрат", "Треугольник", "Прямоугольник"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "У Йоси в два раза больше яблок, чем у Ори. У Ори 4 яблока. Сколько яблок у них вместе?", correctAnswer: "12", distractors: ["8", "10", "16"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Рони старше Даны, а Дана старше Ширы. Кто самая младшая?", correctAnswer: "Шира", distractors: ["Рони", "Дана", "Все одного возраста"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое число следующее? 7, 10, 16, 28, ?", correctAnswer: "52", distractors: ["40", "44", "48"], tier: .hard, grades: 4...6),
    ]
}
