import Foundation

/// 🚩 Флаги — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let flags: [BankQuestion] = [
        BankQuestion(prompt: "🇮🇱\nФлаг какой страны ты видишь?", correctAnswer: "Израиль", distractors: ["Франция", "Италия", "США"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇺🇸\nУ какой страны флаг со звёздами и полосками?", correctAnswer: "США", distractors: ["Канада", "Великобритания", "Австралия"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇫🇷\nФлаг какой страны сине-бело-красный, из трёх стоячих полос?", correctAnswer: "Франция", distractors: ["Италия", "Германия", "Испания"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇮🇹\nФлаг какой страны зелёно-бело-красный?", correctAnswer: "Италия", distractors: ["Франция", "Испания", "Греция"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇯🇵\nУ какой страны на флаге красный круг?", correctAnswer: "Япония", distractors: ["Китай", "Индия", "Таиланд"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇨🇦\nУ какой страны на флаге красный лист?", correctAnswer: "Канада", distractors: ["США", "Швейцария", "Япония"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇧🇷\nФлаг какой страны зелёный с жёлтым ромбом?", correctAnswer: "Бразилия", distractors: ["Португалия", "Аргентина", "Мексика"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇬🇧\nФлаг какой страны ты видишь?", correctAnswer: "Великобритания (Соединённое Королевство)", distractors: ["Франция", "Норвегия", "США"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇩🇪\nФлаг какой страны чёрно-красно-жёлтый?", correctAnswer: "Германия", distractors: ["Нидерланды", "Австрия", "Испания"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🗼\nВ какой стране находится Эйфелева башня?", correctAnswer: "Франция", distractors: ["Италия", "Англия", "Испания"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐪\nВ какой стране находятся знаменитые пирамиды?", correctAnswer: "Египет", distractors: ["Греция", "Марокко", "Турция"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🗽\nВ какой стране находится статуя Свободы?", correctAnswer: "США", distractors: ["Франция", "Канада", "Бразилия"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🧱\nВ какой стране находится Великая стена длиной в тысячи километров?", correctAnswer: "Китай", distractors: ["Япония", "Индия", "Россия"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🕰️\nВ какой стране находится башня с часами «Биг-Бен»?", correctAnswer: "Англия", distractors: ["Франция", "Германия", "Италия"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🏙️\nКакой город — столица Израиля?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Беэр-Шева"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🥐\nКакой город — столица Франции?", correctAnswer: "Париж", distractors: ["Лондон", "Рим", "Мадрид"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍕\nКакой город — столица Италии?", correctAnswer: "Рим", distractors: ["Милан", "Париж", "Афины"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🎡\nКакой город — столица Англии?", correctAnswer: "Лондон", distractors: ["Париж", "Берлин", "Дублин"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌏\nНа каком континенте находится Израиль?", correctAnswer: "Азия", distractors: ["Европа", "Африка", "Америка"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌍\nЕсли считать Европу и Азию отдельно, сколько всего континентов получается?", correctAnswer: "7", distractors: ["5", "6", "9"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌊\nСколько в мире океанов, если считать и Южный океан?", correctAnswer: "5", distractors: ["3", "4", "7"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌍\nНа каком континенте находится Франция?", correctAnswer: "Европа", distractors: ["Азия", "Африка", "Австралия"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌍\nНа каком континенте находится Египет?", correctAnswer: "Африка", distractors: ["Азия", "Европа", "Южная Америка"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇮🇱\nКакие цвета у флага Израиля?", correctAnswer: "синий и белый", distractors: ["красный и белый", "синий и красный", "зелёный и белый"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "✡️\nКакой знак нарисован в центре флага Израиля?", correctAnswer: "щит Давида (маген давид)", distractors: ["менора", "корона", "оливковая ветвь"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "⭐\nСколько звёзд на флаге США?", correctAnswer: "50", distractors: ["13", "52", "100"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🗣️\nНа каком языке говорят во Франции?", correctAnswer: "французский", distractors: ["испанский", "итальянский", "немецкий"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🪙\nКакие деньги в Израиле?", correctAnswer: "шекель", distractors: ["доллар", "евро", "лира"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🇨🇳\nУ какой страны флаг красный с пятью жёлтыми звёздами?", correctAnswer: "Китай", distractors: ["Япония", "Южная Корея", "Таиланд"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇦🇺\nФлаг какой страны ты видишь?", correctAnswer: "Австралия", distractors: ["Великобритания", "Канада", "США"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇲🇽\nУ какой страны на флаге орёл в центре?", correctAnswer: "Мексика", distractors: ["Бразилия", "Испания", "Аргентина"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇦🇷\nУ какой страны флаг голубой с белым и с солнцем?", correctAnswer: "Аргентина", distractors: ["Бразилия", "Мексика", "Португалия"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇬🇷\nУ какой страны флаг сине-белый в полоску и с крестом в углу?", correctAnswer: "Греция", distractors: ["Турция", "Италия", "Испания"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇹🇷\nУ какой страны флаг красный с полумесяцем и звездой?", correctAnswer: "Турция", distractors: ["Греция", "Марокко", "Египет"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇷🇺\nФлаг какой страны бело-сине-красный, из трёх лежачих полос?", correctAnswer: "Россия", distractors: ["Португалия", "Польша", "Греция"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇰🇷\nУ какой страны на флаге круг из красной и синей половинок?", correctAnswer: "Южная Корея", distractors: ["Япония", "Китай", "Таиланд"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇮🇳\nУ какой страны флаг оранжево-бело-зелёный с колесом посередине?", correctAnswer: "Индия", distractors: ["Китай", "Япония", "Египет"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇨🇭\nУ какой страны флаг красный с белым крестом посередине?", correctAnswer: "Швейцария", distractors: ["Швеция", "Бельгия", "Польша"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇪🇬\nУ какой страны флаг красно-бело-чёрный с золотым орлом?", correctAnswer: "Египет", distractors: ["Турция", "Марокко", "Греция"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nКакой город — столица Испании?", correctAnswer: "Мадрид", distractors: ["Барселона", "Лиссабон", "Рим"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nКакой город — столица Германии?", correctAnswer: "Берлин", distractors: ["Мюнхен", "Вена", "Париж"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nКакой город — столица Японии?", correctAnswer: "Токио", distractors: ["Пекин", "Сеул", "Осака"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nКакой город — столица России?", correctAnswer: "Москва", distractors: ["Санкт-Петербург", "Варшава", "Берлин"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nКакой город — столица Египта?", correctAnswer: "Каир", distractors: ["Александрия", "Амман", "Рабат"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏙️\nКакой город — столица США?", correctAnswer: "Вашингтон", distractors: ["Нью-Йорк", "Лос-Анджелес", "Чикаго"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🌏\nКакой континент самый большой в мире?", correctAnswer: "Азия", distractors: ["Африка", "Европа", "Северная Америка"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🗺️\nКакая страна самая большая в мире по площади?", correctAnswer: "Россия", distractors: ["Китай", "Канада", "США"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🌊\nКакой океан самый большой в мире?", correctAnswer: "Тихий океан", distractors: ["Атлантический океан", "Индийский океан", "Северный Ледовитый океан"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🌎\nНа каком континенте находится Бразилия?", correctAnswer: "Южная Америка", distractors: ["Северная Америка", "Африка", "Европа"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🧭\nКакая соседняя страна находится к северу от Израиля?", correctAnswer: "Ливан", distractors: ["Египет", "Иордания", "Турция"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🧭\nКакая соседняя страна находится к востоку от Израиля?", correctAnswer: "Иордания", distractors: ["Ливан", "Египет", "Греция"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🧭\nКакая соседняя страна находится к юго-западу от Израиля?", correctAnswer: "Египет", distractors: ["Ливан", "Сирия", "Кипр"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "💶\nКакими деньгами платят во Франции, Германии и Италии?", correctAnswer: "евро", distractors: ["доллар", "шекель", "лира"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "💵\nКакие деньги в США?", correctAnswer: "доллар", distractors: ["евро", "шекель", "иена"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🍁\nЛист какого дерева нарисован на флаге Канады?", correctAnswer: "клён", distractors: ["олива", "пальма", "дуб"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇯🇵\nЧто означает красный круг на флаге Японии?", correctAnswer: "солнце", distractors: ["луна", "мяч", "цветок"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🇸🇪\nУ какой страны флаг синий с жёлтым крестом?", correctAnswer: "Швеция", distractors: ["Норвегия", "Финляндия", "Дания"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇩🇰\nУ какой страны флаг красный с белым крестом, сдвинутым к древку?", correctAnswer: "Дания", distractors: ["Швеция", "Финляндия", "Польша"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇵🇹\nФлаг какой страны зелёно-красный с гербом посередине?", correctAnswer: "Португалия", distractors: ["Испания", "Италия", "Марокко"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇿🇦\nУ какой страны разноцветный флаг с полосой в виде буквы Y?", correctAnswer: "Южная Африка (ЮАР)", distractors: ["Кения", "Нигерия", "Египет"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🦘\nКакой город — столица Австралии?", correctAnswer: "Канберра", distractors: ["Сидней", "Мельбурн", "Перт"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🍁\nКакой город — столица Канады?", correctAnswer: "Оттава", distractors: ["Торонто", "Ванкувер", "Монреаль"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏙️\nКакой город — столица Бразилии?", correctAnswer: "Бразилиа", distractors: ["Рио-де-Жанейро", "Сан-Паулу", "Лиссабон"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🌏\nКакой континент самый маленький в мире?", correctAnswer: "Австралия", distractors: ["Европа", "Антарктида", "Африка"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "⛪\nКакая страна самая маленькая в мире?", correctAnswer: "Ватикан", distractors: ["Монако", "Мальта", "Израиль"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🧊\nКакой континент почти весь покрыт льдом, и стран на нём нет?", correctAnswer: "Антарктида", distractors: ["Австралия", "Европа", "Северная Америка"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🗣️\nНа каком языке говорят в Бразилии?", correctAnswer: "португальский", distractors: ["испанский", "французский", "итальянский"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "💴\nКакие деньги в Японии?", correctAnswer: "иена", distractors: ["доллар", "юань", "евро"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "💷\nКакие деньги в Великобритании?", correctAnswer: "фунт стерлингов", distractors: ["евро", "доллар", "франк"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇺🇸\nСколько полосок на флаге США?", correctAnswer: "13", distractors: ["50", "10", "15"], tier: .hard, grades: 5...6),
    ]
}
