import Foundation

/// ⚽ Футбол — русский. Переведено с ивритского банка (112 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let soccer: [BankQuestion] = [
        BankQuestion(prompt: "⚽\nСколько игроков одной команды находятся на поле одновременно?", correctAnswer: "11", distractors: ["9", "10", "12"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧤\nКак называют игрока, которому можно ловить мяч руками?", correctAnswer: "Вратарь", distractors: ["Нападающий", "Полузащитник", "Защитник"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🥅\nКак называется момент, когда мяч попадает в ворота?", correctAnswer: "Гол", distractors: ["Угловой", "Пенальти", "Тайм-аут"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🙌\nКакой частью тела полевому игроку нельзя трогать мяч?", correctAnswer: "Руками", distractors: ["Ногами", "Головой", "Грудью"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🟥\nКарточка какого цвета удаляет игрока с поля?", correctAnswer: "Красная", distractors: ["Жёлтая", "Зелёная", "Синяя"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🟨\nЧто получает игрок за не очень грубое нарушение — предупреждение?", correctAnswer: "Жёлтую карточку", distractors: ["Красную карточку", "Пенальти", "Гол"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "📣\nКто свистит и принимает решения в матче?", correctAnswer: "Судья", distractors: ["Тренер", "Вратарь", "Капитан"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⏱️\nСколько таймов в футбольном матче?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⏱️\nСколько минут длится один тайм?", correctAnswer: "45", distractors: ["30", "60", "90"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "⏱️\nСколько минут длится обычный матч, без добавленного времени?", correctAnswer: "90", distractors: ["60", "100", "120"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎯\nКак называется удар с одиннадцати метров, один на один с вратарём?", correctAnswer: "Пенальти", distractors: ["Угловой", "Штрафной удар", "Вбрасывание из-за боковой"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🤾\nМяч вышел за боковую линию. Как его возвращают в игру?", correctAnswer: "Вбрасыванием из-за боковой", distractors: ["Пенальти", "Ударом от ворот", "Спорным мячом"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🚩\nМяч ушёл за линию ворот, задев защитника. Что получает атакующая команда?", correctAnswer: "Угловой", distractors: ["Пенальти", "Вбрасывание из-за боковой", "Гол"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⚡\nКак называют игрока, чья задача — забивать голы?", correctAnswer: "Нападающий", distractors: ["Вратарь", "Защитник", "Судья"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🛡️\nКак называют игрока, который мешает соперникам подойти к своим воротам?", correctAnswer: "Защитник", distractors: ["Нападающий", "Судья", "Тренер"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🏟️\nКак называется большое футбольное поле с трибунами для зрителей?", correctAnswer: "Стадион", distractors: ["Спортзал", "Бассейн", "Сад"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🥅\nСколько ворот на футбольном поле?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🤝\nЧто такое «пас»?", correctAnswer: "Игрок передаёт мяч партнёру по команде", distractors: ["Игрок бьёт по воротам", "Судья свистит", "Зрители хлопают"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🤝\nСчёт в конце матча — 2:2. Чем закончился матч?", correctAnswer: "Ничьёй", distractors: ["Победой", "Поражением", "Пенальти"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧢\nКак называют игрока, который ведёт команду и носит повязку на рукаве?", correctAnswer: "Капитан", distractors: ["Вратарь", "Судья", "Тренер"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔁\nКак называется момент, когда один игрок уходит с поля, а другой выходит вместо него?", correctAnswer: "Замена", distractors: ["Пенальти", "Офсайд", "Угловой"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎯\nКак называют три гола одного игрока в одном матче?", correctAnswer: "Хет-трик", distractors: ["Дерби", "Офсайд", "Пенальти"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "😬\nИгрок случайно забил в ворота своей команды. Как это называется?", correctAnswer: "Автогол", distractors: ["Хет-трик", "Пенальти", "Офсайд"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🟨🟨\nИгрок получил вторую жёлтую карточку в одном матче. Что происходит?", correctAnswer: "Он получает красную и уходит с поля", distractors: ["Он продолжает играть", "Соперник получает пенальти", "Матч останавливают"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "📏\nКакова примерно длина футбольного поля?", correctAnswer: "Около 100 метров", distractors: ["Около 30 метров", "Около 10 метров", "Около 1000 метров"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "📺\nЧто такое VAR?", correctAnswer: "Видеосудья, который помогает судье на поле", distractors: ["Марка футбольных бутс", "Название стадиона", "Особый удар"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⏱️\nКубковый матч закончился вничью. Сколько длится дополнительное время?", correctAnswer: "30 минут", distractors: ["10 минут", "45 минут", "90 минут"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🎯\nПосле дополнительного времени счёт всё ещё равный. Что решает исход матча?", correctAnswer: "Серия пенальти", distractors: ["Бросок монеты", "Ещё один матч завтра", "Команда, у которой больше угловых"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🚫\nЧто такое офсайд («вне игры»)?", correctAnswer: "Атакующий оказался за спиной последнего защитника в момент паса", distractors: ["Мяч вышел за пределы поля", "Игра рукой", "Слишком сильный удар"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇮🇱\nВ каком северном портовом городе Израиля играет «Маккаби» в зелёной форме?", correctAnswer: "Хайфа", distractors: ["Тель-Авив", "Иерусалим", "Беэр-Шева"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nВ каком городе на юге Израиля, в столице Негева, играет «Хапоэль»?", correctAnswer: "Беэр-Шева", distractors: ["Эйлат", "Хайфа", "Нетания"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🏟️\nВ каком городе находится стадион «Тедди»?", correctAnswer: "Иерусалим", distractors: ["Хайфа", "Тель-Авив", "Нетания"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏟️\nВ каком городе находится стадион «Самми Офер»?", correctAnswer: "Хайфа", distractors: ["Иерусалим", "Беэр-Шева", "Петах-Тиква"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏟️\nВ каком городе находится стадион «Блумфилд»?", correctAnswer: "Тель-Авив", distractors: ["Хайфа", "Иерусалим", "Ришон-ле-Цион"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇮🇱\n«Маккаби Тель-Авив» против «Хапоэля Тель-Авив» — как называют матч двух команд из одного города?", correctAnswer: "Дерби", distractors: ["Пенальти", "Мундиаль", "Хет-трик"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nКак называется высшая футбольная лига Израиля?", correctAnswer: "Лигат ха-Аль", distractors: ["Лига Алеф", "Премьер-лига", "Ла Лига"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nКак называется главный кубок Израиля, в котором играют команды из всех лиг?", correctAnswer: "Кубок государства", distractors: ["Кубок мира", "Лига чемпионов", "Кубок дружбы"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nКакой клуб за всю историю выиграл больше всего чемпионатов Израиля?", correctAnswer: "Маккаби Тель-Авив", distractors: ["Хапоэль Беэр-Шева", "Бейтар Иерусалим", "Бней Иегуда"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nВ чемпионате Израиля за победу дают 3 очка, а за ничью — 1. Сколько очков даётся за поражение?", correctAnswer: "0", distractors: ["1", "2", "3"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇪🇸\nВ какой стране играет «Барселона»?", correctAnswer: "Испания", distractors: ["Италия", "Франция", "Португалия"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🇪🇸\nВ каком городе — столице Испании — играет клуб «Реал»?", correctAnswer: "Мадрид", distractors: ["Барселона", "Лондон", "Париж"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏴󠁧󠁢󠁥󠁮󠁧󠁿\nВ какой стране играет «Манчестер Юнайтед»?", correctAnswer: "Англия", distractors: ["Германия", "Испания", "Голландия"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇩🇪\nВ какой стране играет «Бавария Мюнхен»?", correctAnswer: "Германия", distractors: ["Австрия", "Италия", "Бельгия"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇮🇹\nВ какой стране играет «Ювентус»?", correctAnswer: "Италия", distractors: ["Испания", "Франция", "Греция"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇫🇷\nВ каком городе играет клуб ПСЖ?", correctAnswer: "Париж", distractors: ["Марсель", "Лондон", "Рим"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏆\nКак называется высшая футбольная лига Англии?", correctAnswer: "Премьер-лига", distractors: ["Ла Лига", "Серия А", "Бундеслига"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nКак называется высшая футбольная лига Испании?", correctAnswer: "Ла Лига", distractors: ["Премьер-лига", "Серия А", "Лига 1"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⭐\nЛига чемпионов — это турнир…", correctAnswer: "Лучших клубов Европы", distractors: ["Сборных стран", "Детских команд", "Только израильских клубов"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⭐\nКакой клуб выигрывал Лигу чемпионов больше всех?", correctAnswer: "Реал Мадрид", distractors: ["Барселона", "Ливерпуль", "Милан"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇧🇷\nКакого цвета знаменитая футболка сборной Бразилии?", correctAnswer: "Жёлтая", distractors: ["Красная", "Синяя", "Чёрная"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🇦🇷\nКакого цвета футболка сборной Аргентины?", correctAnswer: "Голубая с белым", distractors: ["Красная с чёрным", "Зелёная с жёлтым", "Синяя с красным"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇦🇷\nВ какой стране родился Лионель Месси?", correctAnswer: "Аргентина", distractors: ["Бразилия", "Испания", "Португалия"], tier: .easy, grades: 2...6),
        BankQuestion(prompt: "🇵🇹\nВ какой стране родился Криштиану Роналду?", correctAnswer: "Португалия", distractors: ["Испания", "Бразилия", "Италия"], tier: .easy, grades: 2...6),
        BankQuestion(prompt: "👑\nИз какой страны был Пеле, «король футбола»?", correctAnswer: "Бразилия", distractors: ["Аргентина", "Португалия", "Мексика"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔟\nКакой знаменитый номер на футболке обычно носят самые изобретательные игроки, как Месси и Пеле?", correctAnswer: "10", distractors: ["1", "5", "99"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nРаз в сколько лет проходит мундиаль?", correctAnswer: "4", distractors: ["2", "3", "5"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nЧто такое мундиаль?", correctAnswer: "Чемпионат мира среди сборных стран", distractors: ["Лига испанских клубов", "Матч между двумя городами", "Соревнование для детей"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏆\nКакая сборная первой в истории выиграла чемпионат мира пять раз?", correctAnswer: "Бразилия", distractors: ["Германия", "Аргентина", "Италия"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nКакая сборная выиграла чемпионат мира 2022 года?", correctAnswer: "Аргентина", distractors: ["Франция", "Бразилия", "Германия"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nКакая сборная выиграла чемпионат мира 2018 года?", correctAnswer: "Франция", distractors: ["Хорватия", "Бразилия", "Испания"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nКакая сборная выиграла чемпионат мира 2014 года, который проходил в Бразилии?", correctAnswer: "Германия", distractors: ["Бразилия", "Аргентина", "Голландия"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nКакая сборная выиграла чемпионат мира 2010 года?", correctAnswer: "Испания", distractors: ["Голландия", "Германия", "Италия"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥇\nКакая сборная выиграла самый первый чемпионат мира, в 1930 году?", correctAnswer: "Уругвай", distractors: ["Бразилия", "Италия", "Англия"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇶🇦\nВ какой стране проходил чемпионат мира 2022 года?", correctAnswer: "Катар", distractors: ["Россия", "Бразилия", "Япония"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇮🇱\nВ каком году сборная Израиля впервые сыграла на чемпионате мира?", correctAnswer: "1970", distractors: ["1950", "1990", "2010"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥇\nВ 2014 году немецкий нападающий забил свой 16-й мяч и стал лучшим бомбардиром в истории чемпионатов мира. Кто это?", correctAnswer: "Мирослав Клозе", distractors: ["Пеле", "Месси", "Роналдо"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏴󠁧󠁢󠁥󠁮󠁧󠁿\nВ какой стране впервые записали правила современного футбола?", correctAnswer: "Англия", distractors: ["Бразилия", "Италия", "Греция"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌎\nНа каком континенте находится Бразилия?", correctAnswer: "Южная Америка", distractors: ["Европа", "Африка", "Азия"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nНа каком континенте находится Германия?", correctAnswer: "Европа", distractors: ["Азия", "Южная Америка", "Австралия"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nЧемпионат мира 2010 года проходил в ЮАР. На каком это континенте?", correctAnswer: "Африка", distractors: ["Европа", "Азия", "Америка"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇪🇺\nРаз в сколько лет проходит чемпионат Европы (Евро)?", correctAnswer: "4", distractors: ["1", "2", "6"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\n«Маккаби» забила 3 гола, «Хапоэль» — 1. С каким перевесом победила «Маккаби»?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔢\nМатч закончился 4:2. Сколько всего голов забили?", correctAnswer: "6", distractors: ["2", "4", "8"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔢\nВ перерыве счёт был один-ноль, а в конце матча — три-один. Сколько голов забили во втором тайме?", correctAnswer: "3", distractors: ["2", "4", "1"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔢\nЗа победу дают 3 очка, за ничью — одно. Команда выиграла два матча и один раз сыграла вничью. Сколько у неё очков?", correctAnswer: "7", distractors: ["6", "5", "9"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔢\nЗа победу дают 3 очка. Команда выиграла 5 матчей и проиграла 2. Сколько у неё очков?", correctAnswer: "15", distractors: ["7", "10", "21"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔢\nНа чемпионате мира 2014 года Германия обыграла Бразилию 7:1. С каким перевесом?", correctAnswer: "6", distractors: ["7", "8", "5"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⏱️\nМатч начался в 20:00. Примерно во сколько он закончился, если было 90 минут игры и перерыв 15 минут?", correctAnswer: "21:45", distractors: ["21:30", "22:00", "21:00"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nИгрок забил 12 голов в 8 матчах. Сколько голов за матч в среднем?", correctAnswer: "1.5", distractors: ["1", "2", "4"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🔢\nВ лиге 4 команды, и каждая играет с каждой по одному разу. Сколько всего матчей?", correctAnswer: "6", distractors: ["4", "8", "12"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🔢\nКоманда забивала по 2 гола в каждом из 6 матчей. Сколько голов всего?", correctAnswer: "12", distractors: ["8", "10", "14"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⏱️\nСудья добавил 4 минуты ко второму тайму. Сколько минут длился этот тайм?", correctAnswer: "49", distractors: ["45", "50", "94"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⚽\nКакой формы футбольный мяч?", correctAnswer: "Круглый", distractors: ["Квадратный", "Треугольный", "Как сердечко"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥅\nКуда нужно забить мяч?", correctAnswer: "В ворота", distractors: ["В корзину", "В коробку", "В бассейн"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦶\nЧем бьют по мячу в футболе?", correctAnswer: "Ногой", distractors: ["Ухом", "Носом", "Животом"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧤\nКто защищает ворота?", correctAnswer: "Вратарь", distractors: ["Нападающий", "Тренер", "Зрители"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "👕\nСколько команд играет в одном матче?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥅\nСколько ворот стоит на футбольном поле?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nСколько мячей на поле во время одного матча?", correctAnswer: "Один", distractors: ["Два", "Три", "Десять"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🟩\nКакого цвета трава на поле?", correctAnswer: "Зелёная", distractors: ["Красная", "Синяя", "Фиолетовая"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "📣\nКто свистит в свисток во время матча?", correctAnswer: "Судья", distractors: ["Вратарь", "Зрители", "Тренер"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🟨\nКарточка какого цвета — это предупреждение?", correctAnswer: "Жёлтая", distractors: ["Синяя", "Зелёная", "Белая"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏟️\nКак называется место, где играют в футбол?", correctAnswer: "Поле", distractors: ["Бассейн", "Класс", "Кухня"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "👟\nЧто надевают на ноги во время матча?", correctAnswer: "Бутсы", distractors: ["Перчатки", "Шапку", "Очки"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⏱️\nНа сколько частей делится футбольный матч?", correctAnswer: "На две", distractors: ["На одну", "На три", "На десять"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧤\nКто надевает перчатки во время матча?", correctAnswer: "Вратарь", distractors: ["Нападающий", "Судья", "Тренер"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏆\nЧто получает команда, победившая в турнире?", correctAnswer: "Кубок", distractors: ["Мяч", "Карточку", "Свисток"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦵\nСколько ног у одного игрока?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "↩️\nЧто делают, когда мяч улетел за пределы поля?", correctAnswer: "Бросают его обратно в игру", distractors: ["Заканчивают матч", "Приносят новый мяч", "Все идут домой"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🤝\nЧто красиво сказать команде, которая проиграла?", correctAnswer: "Молодцы", distractors: ["Вы проиграли", "Играть не умеете", "Идите домой"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nКоманда забила один гол и ещё один гол. Сколько голов?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\n2 гола и ещё 1 гол. Сколько голов всего?", correctAnswer: "3", distractors: ["2", "4", "5"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\n3 гола и ещё 2 гола. Сколько голов?", correctAnswer: "5", distractors: ["4", "6", "7"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\n4 гола и ещё 3 гола. Сколько голов?", correctAnswer: "7", distractors: ["6", "8", "9"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "⚽\n5 голов и ещё 5 голов. Сколько голов?", correctAnswer: "10", distractors: ["9", "11", "15"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nВ первом тайме было 6 голов, 2 из них отменили. Сколько осталось?", correctAnswer: "4", distractors: ["3", "5", "8"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nНа поле было 5 мячей, 3 укатились наружу. Сколько осталось?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔢\nНа поле было 7 игроков, 4 ушли отдыхать. Сколько осталось?", correctAnswer: "3", distractors: ["2", "4", "5"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🧮\nНа поле 10 игроков и ещё вратарь. Сколько игроков в команде?", correctAnswer: "11", distractors: ["10", "12", "9"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🥇\nОдна команда забила 3 гола, другая — 1. Кто победил?", correctAnswer: "Та, что забила 3 гола", distractors: ["Та, что забила 1 гол", "Никто не победил", "Обе победили"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🤷\nКаждая команда забила по 2 гола. Как называется такой результат?", correctAnswer: "Ничья", distractors: ["Победа", "Поражение", "Пенальти"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "👋\nЧто делают игроки в конце матча?", correctAnswer: "Пожимают друг другу руки", distractors: ["Ссорятся", "Убегают", "Спят"], tier: .easy, grades: 1...2),
    ]
}
