import Foundation

/// 🧠 Для одарённых — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let gifted: [BankQuestion] = [
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 2, 4, 6, 8, ?", correctAnswer: "10", distractors: ["9", "11", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🖐️\nКакое число следующее в ряду: 5, 10, 15, 20, ?", correctAnswer: "25", distractors: ["21", "24", "30"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 1, 3, 5, 7, ?", correctAnswer: "9", distractors: ["8", "10", "11"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⬇️\nКакое число следующее в ряду: 10, 9, 8, 7, ?", correctAnswer: "6", distractors: ["5", "4", "11"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 3, 6, 9, 12, ?", correctAnswer: "15", distractors: ["13", "14", "16"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "✨\nКакое число следующее в ряду: 1, 2, 4, 8, ?", correctAnswer: "16", distractors: ["10", "12", "14"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "💯\nКакое число следующее в ряду: 100, 90, 80, 70, ?", correctAnswer: "60", distractors: ["65", "50", "69"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧤\nРука : перчатка, как нога : ?", correctAnswer: "Ботинок", distractors: ["Шапка", "Рубашка", "Шарф"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐦\nПтица : небо, как рыба : ?", correctAnswer: "Море", distractors: ["Дерево", "Пустыня", "Гора"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐄\nКорова : молоко, как курица : ?", correctAnswer: "Яйцо", distractors: ["Шерсть", "Мёд", "Сыр"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐘\nБольшой : маленький, как горячий : ?", correctAnswer: "Холодный", distractors: ["Тёплый", "Мокрый", "Высокий"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🥕\nЧто здесь лишнее?", correctAnswer: "Морковь", distractors: ["Яблоко", "Банан", "Груша"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎨\nЧто здесь лишнее?", correctAnswer: "Круглый", distractors: ["Красный", "Синий", "Зелёный"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "📅\nЧто здесь лишнее?", correctAnswer: "Январь", distractors: ["Воскресенье", "Понедельник", "Вторник"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔤\nКакая буква следующая в ряду: א‎, ב‎, ג‎, ד‎, ?", correctAnswer: "ה", distractors: ["ו", "ז", "ח"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔤\nКакая буква следующая в ряду: א‎, ג‎, ה‎, ז‎, ?", correctAnswer: "ט", distractors: ["ח", "י", "כ"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔵\nКакая фигура следующая в ряду: 🔵 🟦 🔵 🟦 ?", correctAnswer: "Круг", distractors: ["Квадрат", "Треугольник", "Звезда"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔴\nКакой цвет следующий в ряду: 🔴 🔴 🔵 🔴 🔴 🔵 🔴 ?", correctAnswer: "Красный", distractors: ["Синий", "Зелёный", "Жёлтый"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍎\nУ Ноама 3 яблока. Он отдал 1 другу и получил 2 от мамы. Сколько яблок у него теперь?", correctAnswer: "4", distractors: ["3", "5", "6"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🚌\nВ автобусе было 5 детей. На остановке зашли 3, а вышли 2. Сколько детей теперь в автобусе?", correctAnswer: "6", distractors: ["4", "5", "10"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍬\nУ Даны 6 конфет, а у Йоси на 2 больше. Сколько конфет у Йоси?", correctAnswer: "8", distractors: ["4", "6", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕐\nСейчас 3 часа. Сколько будет на часах через два часа?", correctAnswer: "5", distractors: ["1", "4", "6"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐔\nСколько ног у 3 куриц вместе?", correctAnswer: "6", distractors: ["3", "9", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐶\nСколько ног у 2 собак и одной курицы вместе?", correctAnswer: "10", distractors: ["6", "8", "12"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🪑\nВ классе 4 стола, и у каждого стола 2 стула. Сколько стульев в классе?", correctAnswer: "8", distractors: ["4", "6", "10"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 1, 4, 9, 16, ?", correctAnswer: "25", distractors: ["20", "24", "32"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 2, 3, 5, 8, 12, ?", correctAnswer: "17", distractors: ["15", "16", "18"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐚\nКакое число следующее в ряду: 1, 1, 2, 3, 5, 8, ?", correctAnswer: "13", distractors: ["10", "11", "16"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 3, 6, 12, 24, ?", correctAnswer: "48", distractors: ["30", "36", "72"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 1, 2, 4, 7, 11, ?", correctAnswer: "16", distractors: ["14", "15", "22"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔤\nКакая буква следующая в ряду: א‎, ד‎, ז‎, י‎, ?", correctAnswer: "מ", distractors: ["כ", "ל", "נ"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔤\nКакая буква следующая в ряду: ת‎, ש‎, ר‎, ק‎, ?", correctAnswer: "צ", distractors: ["פ", "ס", "ע"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔷\nКакая фигура следующая в ряду: треугольник, квадрат, пятиугольник, ?", correctAnswer: "Шестиугольник", distractors: ["Круг", "Треугольник", "Прямоугольник"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "📖\nКнига : чтение, как карандаш : ?", correctAnswer: "Письмо", distractors: ["Пение", "Бег", "Питьё"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "☀️\nЖарко : лето, как холодно : ?", correctAnswer: "Зима", distractors: ["Весна", "Осень", "Ночь"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🩺\nВрач : больница, как учительница : ?", correctAnswer: "Школа", distractors: ["Библиотека", "Магазин", "Офис"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nКакое число здесь лишнее?", correctAnswer: "8", distractors: ["3", "7", "11"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥛\nЧто здесь лишнее?", correctAnswer: "Хлеб", distractors: ["Вода", "Молоко", "Сок"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍂\nЧто здесь лишнее?", correctAnswer: "Июль", distractors: ["Лето", "Зима", "Осень"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🪞\nИлан стоит лицом на север. Он поворачивается на пол-оборота. Куда он смотрит теперь?", correctAnswer: "На юг", distractors: ["На север", "На восток", "На запад"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔄\nСтрелка показывает вверх. Её повернули на четверть оборота по часовой стрелке. Куда она показывает теперь?", correctAnswer: "Направо", distractors: ["Налево", "Вниз", "Вверх"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔄\nСтрелка показывает направо. Её повернули на пол-оборота. Куда она показывает теперь?", correctAnswer: "Налево", distractors: ["Вверх", "Вниз", "Направо"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "📄\nЛист бумаги сложили пополам, потом ещё раз пополам и развернули. На сколько одинаковых частей разделён лист?", correctAnswer: "4", distractors: ["2", "3", "8"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧦\nВ ящике 2 красных носка и 2 синих носка. Сколько носков нужно достать не глядя, чтобы точно была пара одного цвета?", correctAnswer: "3", distractors: ["1", "2", "4"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "⚖️\nЧто тяжелее: кило перьев или кило железа?", correctAnswer: "Одинаково", distractors: ["Кило железа", "Кило перьев", "Нельзя узнать"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "📅\nЕсли завтра среда, какой день был вчера?", correctAnswer: "Понедельник", distractors: ["Вторник", "Четверг", "Воскресенье"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🏃\nДани бегает быстрее Гиля, а Гиль быстрее Майи. Кто самый медленный?", correctAnswer: "Майя", distractors: ["Дани", "Гиль", "Нельзя узнать"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐝\nЧто общего у муравья, пчелы и мухи?", correctAnswer: "Все они насекомые", distractors: ["Все они птицы", "Все они рыбы", "Все они звери"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🏫\nВ классе 12 мальчиков и 14 девочек. 6 детей ушли в библиотеку. Сколько детей осталось в классе?", correctAnswer: "20", distractors: ["18", "22", "26"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "💰\nУ Рона 20 шекелей. Он купил 2 ластика по 3 шекеля каждый. Сколько шекелей у него осталось?", correctAnswer: "14", distractors: ["12", "16", "17"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🎂\nДане 8 лет, а её брат старше её на 3 года. Сколько им лет вместе?", correctAnswer: "19", distractors: ["11", "16", "21"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🚗\nНа стоянке 3 машины и 4 велосипеда. Сколько всего колёс?", correctAnswer: "20", distractors: ["14", "16", "24"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nСколько чисел от 1 до 20 (включая 20) делятся на 5 без остатка?", correctAnswer: "4", distractors: ["2", "3", "5"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 2, 5, 11, 23, ?", correctAnswer: "47", distractors: ["35", "45", "46"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 81, 27, 9, ?", correctAnswer: "3", distractors: ["0", "1", "6"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 1, 2, 6, 24, ?", correctAnswer: "120", distractors: ["48", "96", "100"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔀\nКакое число следующее в ряду: 1, 10, 2, 20, 3, 30, 4, ?", correctAnswer: "40", distractors: ["5", "34", "50"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔢\nКакое число следующее в ряду: 3, 4, 6, 9, 13, ?", correctAnswer: "18", distractors: ["16", "17", "20"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔤\nКакая буква следующая в ряду: ב‎, ד‎, ו‎, ח‎, ?", correctAnswer: "י", distractors: ["ט", "כ", "ל"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔄\nСтрелка показывает вверх. Её повернули на 3 четверти оборота по часовой стрелке. Куда она показывает теперь?", correctAnswer: "Налево", distractors: ["Направо", "Вниз", "Вверх"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔄\nСтрелка показывает налево. Её повернули на 5 четвертей оборота против часовой стрелки. Куда она показывает теперь?", correctAnswer: "Вниз", distractors: ["Вверх", "Направо", "Налево"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "📄\nЛист сложили пополам и вырезали маленький треугольник на середине линии сгиба. Какая фигура получится в середине листа, когда его развернут?", correctAnswer: "Дырка в форме ромба", distractors: ["Круглая дырка", "Две дырки", "Дырки не будет"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "👨‍👧‍👧\nУ папы 3 дочери, и у каждой дочери есть один брат. Сколько всего детей у папы?", correctAnswer: "4", distractors: ["3", "6", "7"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "7️⃣\nСколько раз цифра 7 встречается в числах от одного до пятидесяти?", correctAnswer: "5", distractors: ["4", "6", "10"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🤝\n4 ребёнка здороваются за руку, каждый с каждым ровно один раз. Сколько всего рукопожатий?", correctAnswer: "6", distractors: ["4", "8", "12"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "📏\nРон выше Дани. Дани ниже Гиля. Рон выше Гиля. Кто средний по росту?", correctAnswer: "Гиль", distractors: ["Рон", "Дани", "Нельзя узнать"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "📅\nСегодня вторник. Какой день будет через 10 дней?", correctAnswer: "Пятница", distractors: ["Среда", "Четверг", "Суббота"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🐇\nВо дворе кролики и куры. Всего 5 голов и 14 ног. Сколько во дворе кроликов?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "✏️\nВ магазине 3 коробки, и в каждой коробке 8 карандашей. Все карандаши поделили поровну между 4 детьми. Сколько карандашей получит каждый?", correctAnswer: "6", distractors: ["4", "8", "12"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🎂\nЙоси 10 лет, а его маме 40. Через сколько лет мама будет старше его ровно в 3 раза?", correctAnswer: "5", distractors: ["3", "4", "10"], tier: .hard, grades: 4...5),
    ]
}
