import Foundation

/// 🇮🇱 Израиль — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let israel: [BankQuestion] = [
        BankQuestion(prompt: "🏛️\nКакой город — столица Израиля?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Беэр-Шева"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🇮🇱\nКакие цвета есть на флаге Израиля?", correctAnswer: "Синий и белый", distractors: ["Красный и белый", "Зелёный и белый", "Синий и красный"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "✡️\nКакой знак нарисован в середине флага Израиля?", correctAnswer: "Звезда Давида", distractors: ["Сердце", "Солнце", "Менора"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "📏\nСколько синих полос на флаге Израиля?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕎\nЧто нарисовано в середине герба Государства Израиль?", correctAnswer: "Менора", distractors: ["Флаг", "Лев", "Звезда Давида"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🫒\nВетви какого дерева стоят по обе стороны от меноры на гербе страны?", correctAnswer: "Олива", distractors: ["Пальма", "Инжир", "Сосна"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎵\nКак называется гимн Государства Израиль?", correctAnswer: "Ха-Тиква", distractors: ["Золотой Иерусалим", "Песня мира", "Песня долины"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐦\nКакая птица — национальная птица Израиля?", correctAnswer: "Удод", distractors: ["Голубь", "Орёл", "Попугай"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌸\nКакой цветок — национальный цветок Израиля?", correctAnswer: "Анемон (калания)", distractors: ["Роза", "Подсолнух", "Нарцисс"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🪙\nКак называются деньги, которыми платят в Израиле?", correctAnswer: "Шекель", distractors: ["Доллар", "Евро", "Лира"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕎\nВ какой праздник зажигают свечи в особом светильнике на восемь огоньков и играют в волчок-севивон?", correctAnswer: "Ханука", distractors: ["Пурим", "Песах", "Суккот"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍩\nКакое сладкое лакомство едят на Хануку?", correctAnswer: "Пончики", distractors: ["Уши Амана", "Маца", "Яблоко в мёду"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎭\nВ какой праздник наряжаются в костюмы?", correctAnswer: "Пурим", distractors: ["Ханука", "Шавуот", "Песах"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍪\nКакое треугольное печенье едят в Пурим?", correctAnswer: "Уши Амана", distractors: ["Пончики", "Латкес", "Маца"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🫓\nВ какой праздник едят мацу вместо хлеба?", correctAnswer: "Песах", distractors: ["Суккот", "Ханука", "Пурим"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍎\nВ какой праздник макают яблоко в мёд?", correctAnswer: "Рош ха-Шана", distractors: ["Пурим", "Песах", "Ту би-Шват"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🛖\nВ какой праздник строят во дворе шалаш с крышей из веток и сидят в нём?", correctAnswer: "Суккот", distractors: ["Песах", "Ханука", "Шавуот"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌳\nВ какой праздник сажают деревья?", correctAnswer: "Ту би-Шват", distractors: ["Пурим", "Суккот", "Ханука"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎆\nЧто принято делать в День независимости Израиля?", correctAnswer: "Жарить мангал и смотреть фейерверк", distractors: ["Строить сукку", "Наряжаться в костюмы", "Есть мацу"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎂\nКакой праздник — «день рождения» Государства Израиль?", correctAnswer: "День независимости", distractors: ["Рош ха-Шана", "Пурим", "Ту би-Шват"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌊\nКакое море плещется рядом с Тель-Авивом и Хайфой?", correctAnswer: "Средиземное море", distractors: ["Мёртвое море", "Красное море", "Озеро Кинерет"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏖️\nКакой город стоит на самом юге Израиля, на берегу Красного моря?", correctAnswer: "Эйлат", distractors: ["Хайфа", "Нагария", "Тверия"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧂\nВ каком море вода такая солёная, что человек плавает в ней без всяких усилий?", correctAnswer: "Мёртвое море", distractors: ["Средиземное море", "Озеро Кинерет", "Красное море"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏜️\nКак называется большая пустыня на юге Израиля?", correctAnswer: "Негев", distractors: ["Кармель", "Галилея", "Шарон"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⛷️\nНа какой горе находится единственный в Израиле горнолыжный курорт?", correctAnswer: "Хермон", distractors: ["Кармель", "Гора Тавор", "Масличная гора"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⛰️\nКакой город построен на горе Кармель?", correctAnswer: "Хайфа", distractors: ["Тель-Авив", "Эйлат", "Беэр-Шева"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏙️\nКакой город — самый большой город Негева?", correctAnswer: "Беэр-Шева", distractors: ["Эйлат", "Хайфа", "Нетания"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧱\nКак называется древнее святое место в Иерусалиме, куда люди вкладывают записки между камнями?", correctAnswer: "Стена Плача", distractors: ["Великая Китайская стена", "Масада", "Башня Давида"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏙️\nКакой город называют «Белым городом» из-за его светлых домов?", correctAnswer: "Тель-Авив", distractors: ["Хайфа", "Иерусалим", "Эйлат"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐠\nКакой город знаменит коралловым рифом и разноцветными рыбами?", correctAnswer: "Эйлат", distractors: ["Хайфа", "Тверия", "Ашдод"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍊\nКакой знаменитый на весь мир фрукт назвали по имени города Яффо?", correctAnswer: "Апельсин", distractors: ["Банан", "Яблоко", "Арбуз"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛥️\nКакой город стоит на берегу озера Кинерет?", correctAnswer: "Тверия", distractors: ["Цфат", "Нагария", "Акко"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🎨\nКакой город в Галилее славится старинными переулками и галереями художников?", correctAnswer: "Цфат", distractors: ["Беэр-Шева", "Эйлат", "Холон"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏛️\nВ каком городе находится здание Кнессета?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Беэр-Шева"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏰\nКак называется древняя крепость на вершине горы у Мёртвого моря, куда поднимаются по канатной дороге или по Змеиной тропе?", correctAnswer: "Масада", distractors: ["Рош-ха-Никра", "Кейсария", "Башня Давида"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌊\nГде находятся белые гроты, которые море выточило в скале на самом севере израильского берега?", correctAnswer: "Рош-ха-Никра", distractors: ["Эйлат", "Масада", "Яффо"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🕳️\nВ каком районе страны находится кратер Махтеш-Рамон?", correctAnswer: "В Негеве", distractors: ["В Галилее", "На Кармеле", "В Шароне"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🗺️\nСколько «морей» насчитывают в Израиле, если считать и озеро Кинерет?", correctAnswer: "4", distractors: ["2", "3", "5"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🚰\nКакое из израильских «морей» — озеро с пресной водой, которую можно пить?", correctAnswer: "Кинерет", distractors: ["Мёртвое море", "Средиземное море", "Красное море"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧭\nС какой стороны Израиля находится Мёртвое море?", correctAnswer: "На востоке", distractors: ["На западе", "На севере", "На северо-западе"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏞️\nКак называется река, которая течёт из Кинерета в Мёртвое море?", correctAnswer: "Иордан", distractors: ["Яркон", "Кишон", "Нил"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📉\nКакое место в Израиле — самое низкое место на суше во всём мире?", correctAnswer: "Мёртвое море", distractors: ["Кинерет", "Негев", "Эйлат"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏔️\nКакая гора самая высокая в Израиле?", correctAnswer: "Хермон", distractors: ["Кармель", "Гора Гильбоа", "Гора Тавор"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌍\nНа каком материке находится Израиль?", correctAnswer: "Азия", distractors: ["Европа", "Африка", "Америка"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍯\nЗемлю Израиля называют «страной, текущей…» — чем же?", correctAnswer: "Молоком и мёдом", distractors: ["Водой и вином", "Хлебом и солью", "Маслом и оливками"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦌\nКакое животное с изогнутыми рогами скачет по скалам в Эйн-Геди?", correctAnswer: "Горный козёл (нубийский козерог)", distractors: ["Зебра", "Слон", "Медведь"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌺\nКакого цвета почти все калании, которыми зимой покрываются поля юга?", correctAnswer: "Красного", distractors: ["Синего", "Жёлтого", "Чёрного"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐦\nЧто особенного во внешности удода?", correctAnswer: "Хохолок из перьев на голове", distractors: ["Длинный хвост, как у павлина", "Очень длинная шея", "Розовые ноги"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧀\nВ какой праздник принято есть молочную еду и украшать голову венками из цветов?", correctAnswer: "Шавуот", distractors: ["Суккот", "Пурим", "Ханука"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔥\nВ какой праздник жгут костры?", correctAnswer: "Лаг ба-Омер", distractors: ["Ханука", "Песах", "Шавуот"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📅\nВ каком году появилось Государство Израиль?", correctAnswer: "1948", distractors: ["1900", "1967", "2000"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👔\nКто был первым главой правительства Израиля?", correctAnswer: "Давид Бен-Гурион", distractors: ["Теодор Герцль", "Хаим Вейцман", "Голда Меир"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🎩\nКого называют провидцем еврейского государства?", correctAnswer: "Теодор Герцль", distractors: ["Давид Бен-Гурион", "Элиэзер Бен-Йехуда", "Хаим Нахман Бялик"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚗\nКакое знаменитое приложение для навигации создали в Израиле?", correctAnswer: "Waze", distractors: ["Google Maps", "YouTube", "TikTok"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍅\nКакой сорт помидоров получил важное развитие благодаря израильским учёным?", correctAnswer: "Помидоры черри", distractors: ["Помидоры с поля", "Зелёные помидоры", "Дикие помидоры"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "💧\nКакой способ полива, при котором вода поступает прямо к корню по тонкой трубочке, придумали в Израиле?", correctAnswer: "Капельное орошение", distractors: ["Полив дождевателями", "Полив из вёдер", "Полив из шланга"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📖\nКто вернул иврит к жизни и снова сделал его разговорным языком?", correctAnswer: "Элиэзер Бен-Йехуда", distractors: ["Теодор Герцль", "Давид Бен-Гурион", "Хаим Нахман Бялик"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🎼\nКто написал слова гимна «Ха-Тиква»?", correctAnswer: "Нафтали Герц Имбер", distractors: ["Хаим Нахман Бялик", "Наоми Шемер", "Леа Гольдберг"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📜\nВ каком городе Давид Бен-Гурион объявил о создании Государства Израиль?", correctAnswer: "Тель-Авив", distractors: ["Иерусалим", "Хайфа", "Беэр-Шева"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏗️\nКакой город основали в 1909 году и считают первым еврейским городом нового времени?", correctAnswer: "Тель-Авив", distractors: ["Хайфа", "Ришон-ле-Цион", "Петах-Тиква"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "👥\nВ каком городе Израиля живёт больше всего жителей?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Ришон-ле-Цион"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🚇\nВ каком городе ездит «Кармелит»?", correctAnswer: "Хайфа", distractors: ["Тель-Авив", "Иерусалим", "Беэр-Шева"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏞️\nКак называется река, которая течёт через Тель-Авив в Средиземное море?", correctAnswer: "Яркон", distractors: ["Иордан", "Кишон", "Нил"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏜️\nКакую часть площади Израиля занимает Негев?", correctAnswer: "Больше половины", distractors: ["Меньше десятой части", "Примерно четверть", "Примерно треть"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🚰\nКак называется большое сооружение, которое ведёт воду из Кинерета на юг, до самого Негева?", correctAnswer: "Всеизраильский водовод", distractors: ["Суэцкий канал", "Яркон", "Всеизраильская железная дорога"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌊\nКак называется способ, которым в Израиле превращают морскую воду в питьевую?", correctAnswer: "Опреснение", distractors: ["Заморозка", "Кипячение", "Фильтрация через песок"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💾\nКакое маленькое устройство для хранения файлов, которое подключают к компьютеру, придумали в Израиле?", correctAnswer: "Флешка (диск-он-кей)", distractors: ["Мышка", "Принтер", "Клавиатура"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "☀️\nКакое устройство на крышах домов в Израиле нагревает воду без электричества?", correctAnswer: "Солнечный бойлер", distractors: ["Кондиционер", "Антенна", "Холодильник"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌳\nКакое дерево выбрали национальным деревом Израиля?", correctAnswer: "Олива", distractors: ["Сосна", "Эвкалипт", "Пальма"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🗓️\nВ каком еврейском месяце отмечают День независимости?", correctAnswer: "Ияр", distractors: ["Тишрей", "Нисан", "Кислев"], tier: .hard, grades: 4...6),
    ]
}
