import Foundation

/// 🍯 Праздники тишрея — русский. Переведено с ивритского банка (72 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let tishrei: [BankQuestion] = [
        BankQuestion(prompt: "🍎\nВо что макают яблоко в Рош ха-Шана?", correctAnswer: "В мёд", distractors: ["В соль", "В воду", "В масло"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍯\nПочему в Рош ха-Шана едят яблоко с мёдом?", correctAnswer: "Чтобы год был сладким", distractors: ["Потому что это полезно для зубов", "Потому что нет хлеба", "Потому что пчёлы так попросили"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📯\nВ какой инструмент трубят в Рош ха-Шана?", correctAnswer: "Шофар", distractors: ["Труба", "Барабан", "Флейта"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐏\nИз чего сделан шофар?", correctAnswer: "Из бараньего рога", distractors: ["Из дерева", "Из пластика", "Из стекла"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "👋\nЧто желают друг другу в Рош ха-Шана?", correctAnswer: "«Шана това» — хорошего года", distractors: ["«Хаг Пурим самеах»", "«Спокойной ночи»", "«Приятного аппетита»"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🎉\nЧто празднуют в Рош ха-Шана?", correctAnswer: "Начало нового еврейского года", distractors: ["День рождения государства Израиль", "Конец учебного года", "Начало зимы"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🍎\nКакой фрукт — символ Рош ха-Шана?", correctAnswer: "Яблоко", distractors: ["Арбуз", "Банан", "Клубника"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🥖\nКакой формы хала на Рош ха-Шана?", correctAnswer: "Круглая", distractors: ["Треугольная", "Квадратная", "Длинная и тонкая"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌰\nКакой красный плод с множеством зёрнышек едят в Рош ха-Шана?", correctAnswer: "Гранат", distractors: ["Апельсин", "Груша", "Дыня"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nСколько дней длится Рош ха-Шана?", correctAnswer: "Два дня", distractors: ["Один день", "Неделю", "Месяц"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🍎\nУ Тофи было 3 яблока, и мама дала ему ещё 2 на Рош ха-Шана. Сколько у него яблок?", correctAnswer: "5", distractors: ["4", "6", "3"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐝\nКто делает мёд, который едят в праздник?", correctAnswer: "Пчёлы", distractors: ["Бабочки", "Муравьи", "Птицы"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤍\nКакого цвета одежду принято надевать в Йом Кипур?", correctAnswer: "Белую", distractors: ["Чёрную", "Красную", "Зелёную"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🙏\nО чём просят друг друга перед Йом Кипуром?", correctAnswer: "О прощении", distractors: ["О подарке", "О деньгах", "О еде"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🚲\nЧто видно на дорогах в Израиле в Йом Кипур?", correctAnswer: "Детей, которые катаются на велосипедах", distractors: ["Длинные пробки", "Футбольные матчи", "Праздничные шествия"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🍽️\nЧто делают в Йом Кипур многие взрослые?", correctAnswer: "Постятся — не едят и не пьют", distractors: ["Едят пончики", "Жарят мясо на мангале", "Наряжаются в костюмы"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "📆\nКакой праздник приходится на десятый день месяца тишрей?", correctAnswer: "Йом Кипур", distractors: ["Ханука", "Суккот", "Песах"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "💬\nЧто говорят тому, кого обидели?", correctAnswer: "«Прости меня»", distractors: ["«Спасибо»", "«Пожалуйста»", "«До свидания»"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🛖\nГде сидят и едят в праздник Суккот?", correctAnswer: "В сукке", distractors: ["В машине", "В палатке на море", "В школе"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌿\nИз чего сделана крыша сукки?", correctAnswer: "Из веток и листьев — это схах", distractors: ["Из бетона", "Из стекла", "Из железа"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎨\nЧто принято вешать в сукке?", correctAnswer: "Украшения", distractors: ["Ханукальные свечи", "Карнавальные костюмы", "Мацу"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌴\nКак называется самая длинная зелёная ветвь из четырёх видов растений, которой машут в Суккот?", correctAnswer: "Лулав", distractors: ["Хадас", "Арава", "Этрог"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🍋\nКакой жёлтый душистый плод входит в четыре вида растений праздника Суккот?", correctAnswer: "Этрог", distractors: ["Лимон", "Грейпфрут", "Банан"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌿\nЧто из этого входит в четыре вида растений праздника Суккот?", correctAnswer: "Лулав", distractors: ["Яблоко", "Пончик", "Маца"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "⭐\nЧто видно ночью сквозь схах — крышу сукки?", correctAnswer: "Звёзды", distractors: ["Солнце", "Море", "Школу"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📆\nСколько дней длится праздник Суккот?", correctAnswer: "Семь дней", distractors: ["Один день", "Два дня", "Месяц"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🎏\nВ какой праздник танцуют со свитком Торы, а дети машут флажками?", correctAnswer: "Симхат Тора", distractors: ["Йом Кипур", "Песах", "Ту би-Шват"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🛖\nВ сукке у Даны было 4 украшения, и она повесила ещё 3. Сколько украшений теперь?", correctAnswer: "7", distractors: ["6", "8", "5"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "📅\nВ каком еврейском месяце наступает Рош ха-Шана?", correctAnswer: "Тишрей", distractors: ["Нисан", "Кислев", "Ав"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🗓️\nНа какую еврейскую дату приходится Рош ха-Шана?", correctAnswer: "1 тишрея", distractors: ["15 швата", "10 тишрея", "25 кислева"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐟\nЗачем на праздничный стол в Рош ха-Шана кладут рыбью голову?", correctAnswer: "Чтобы быть впереди — «головой, а не хвостом»", distractors: ["Потому что рыба в праздник дешёвая", "Потому что это сладкое блюдо", "Потому что рыба — символ зимы"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌰\nЧто желают, когда едят гранат в Рош ха-Шана?", correctAnswer: "Чтобы наших добрых дел стало столько же, сколько зёрнышек в гранате", distractors: ["Чтобы мы были сильными, как лев", "Чтобы выпало много дождя", "Чтобы мы не уставали"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥕\nКак называются особые блюда, которые едят в вечер Рош ха-Шана, и на каждое говорят своё пожелание?", correctAnswer: "Симаним", distractors: ["Порции", "Сухофрукты", "Сладости"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📯\nКак называется длинный непрерывный звук шофара?", correctAnswer: "Ткиа", distractors: ["Шварим", "Труа", "Пение"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📯\nКак называются короткие быстрые звуки шофара?", correctAnswer: "Труа", distractors: ["Ткиа", "Шварим", "Ткиа гдола"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌊\nКак называется обычай, когда в Рош ха-Шана идут к воде и «сбрасывают» в неё ошибки прошедшего года?", correctAnswer: "Ташлих", distractors: ["Хакафот", "Слихот", "Капарот"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌙\nНа чём основан еврейский календарь?", correctAnswer: "На луне — с поправкой по солнцу", distractors: ["Только на солнце", "На звёздах", "На погоде"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍎\nВ магазине было 12 яблок. Мама купила 5 к Рош ха-Шана. Сколько осталось в магазине?", correctAnswer: "7", distractors: ["6", "8", "17"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🍯\nБанка мёда стоит 10 шекелей. Сколько будут стоить 3 банки?", correctAnswer: "30 шекелей", distractors: ["13 шекелей", "20 шекелей", "33 шекеля"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🗓️\nНа какую еврейскую дату приходится Йом Кипур?", correctAnswer: "10 тишрея", distractors: ["1 тишрея", "15 тишрея", "25 кислева"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔟\nКак называются дни между Рош ха-Шана и Йом Кипуром?", correctAnswer: "Асерет йемей тшува — десять дней раскаяния", distractors: ["Семь дней пира", "Дни счёта омера", "Холь ха-моэд"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⏳\nСколько примерно часов длится пост Йом Кипура?", correctAnswer: "Около 25 часов", distractors: ["Около 3 часов", "Около 12 часов", "Около 48 часов"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🎵\nКак называется знаменитая молитва, которой открывается вечер Йом Кипура?", correctAnswer: "Коль нидрей", distractors: ["Халель", "Кидуш", "«Ха-Тиква»"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "💬\nЧто желают друг другу в Йом Кипур?", correctAnswer: "«Гмар хатима това»", distractors: ["«Хаг самеах ве-кашер»", "«Шавуа тов»", "«Мазаль тов»"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🙏\nКак правильно поступить, когда кто-то по-настоящему просит прощения?", correctAnswer: "Простить и начать заново", distractors: ["Не обращать внимания", "Отплатить тем же", "Накричать в ответ"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🕯️\nКак называется молитва, которая завершает Йом Кипур, перед самым концом поста?", correctAnswer: "Неила", distractors: ["Шахарит", "Минха", "Хавдала"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌿\nКакие растения входят в четыре вида праздника Суккот?", correctAnswer: "Лулав, этрог, хадас и арава", distractors: ["Яблоко, мёд, гранат и рыба", "Олива, инжир, виноград и финик", "Пшеница, ячмень, кукуруза и рис"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌳\nС какого дерева берут лулав?", correctAnswer: "С финиковой пальмы", distractors: ["С оливы", "С яблони", "С сосны"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌱\nКакой из четырёх видов растёт у воды, и у него длинные листья?", correctAnswer: "Арава", distractors: ["Хадас", "Этрог", "Лулав"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌿\nУ какого из четырёх видов маленькие листочки и приятный запах?", correctAnswer: "Хадас", distractors: ["Арава", "Лулав", "Этрог"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🗓️\nС какой еврейской даты начинается праздник Суккот?", correctAnswer: "15 тишрея", distractors: ["1 тишрея", "10 тишрея", "15 швата"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏜️\nО чём напоминает нам сукка?", correctAnswer: "О шалашах, в которых сыны Израиля жили в пустыне после исхода из Египта", distractors: ["О царских дворцах в Иерусалиме", "О Ноевом ковчеге", "О домах в Европе"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "👥\nКак называют особых гостей, которых каждый вечер «приглашают» в сукку?", correctAnswer: "Ушпизин", distractors: ["Шошвиним", "Друзья", "Соседи"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "📖\nЧто празднуют в Симхат Тора?", correctAnswer: "То, что дочитали всю Тору до конца и начинают её сначала", distractors: ["Конец лета", "Исход из Египта", "Дарование Торы"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "💃\nКак называются танцы по кругу со свитками Торы в Симхат Тора?", correctAnswer: "Хакафот", distractors: ["Ташлих", "Слихот", "Хавдала"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌾\nКакое ещё название есть у праздника Суккот — по сбору урожая с полей?", correctAnswer: "Хаг ха-асиф", distractors: ["Хаг ха-бикурим", "Хаг ха-урим", "Хаг ха-мацот"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🛖\nВ районе 6 домов, и возле каждого дома по 2 сукки. Сколько всего сукк в районе?", correctAnswer: "12", distractors: ["8", "10", "14"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📅\nСколько месяцев в обычном еврейском году?", correctAnswer: "12", distractors: ["10", "13", "14"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "📅\nКак называется еврейский год, в который добавляют ещё один месяц — адар бет?", correctAnswer: "Шана меуберет — високосный год", distractors: ["Двойной год", "Длинный год", "Год шмиты"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nКакое число обозначает еврейский год תשפ״ז?", correctAnswer: "5787", distractors: ["2026", "5687", "6787"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍎\nКак называют Рош ха-Шана и Йом Кипур вместе?", correctAnswer: "Ямим нораим — Грозные дни", distractors: ["Великие дни", "Дни каникул", "Шлошет ха-регалим"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🎶\nКак называются особые молитвы, которые читают перед рассветом в дни перед Рош ха-Шана и Йом Кипуром?", correctAnswer: "Слихот", distractors: ["Халель", "Хакафот", "Ханукальные пиюты"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📯\nВ каком порядке трубят в шофар?", correctAnswer: "Ткиа, шварим, труа, ткиа", distractors: ["Труа, ткиа, шварим", "Шварим, шварим, ткиа", "Ткиа, ткиа, труа"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🛖\nЧто обязательно должно быть в сукке, чтобы она считалась настоящей?", correctAnswer: "Схах — крыша из растений, срезанных с земли", distractors: ["Стол и стулья", "Цветные украшения", "Деревянный пол"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🌧️\nКакую особую молитву читают в конце праздника Суккот, в Шмини Ацерет, перед зимой?", correctAnswer: "Молитву о дожде — тфилат гешем", distractors: ["Молитву о росе — тфилат таль", "Дорожную молитву — тфилат ха-дерех", "Биркат ха-хама — благословение солнца"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📖\nКак называется праздник сразу после семи дней Суккота, в который в Израиле отмечают и Симхат Тора?", correctAnswer: "Шмини Ацерет", distractors: ["Холь ха-моэд", "Йом Кипур", "Ту бе-Ав"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🌾\nКакие праздники называют «шлошет ха-регалим» — праздниками восхождения в Иерусалим?", correctAnswer: "Песах, Шавуот и Суккот", distractors: ["Рош ха-Шана, Йом Кипур и Ханука", "Пурим, Ту би-Шват и Лаг ба-омер", "Три ежедневные молитвы"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🕊️\nЧто означает слово «Кипур»?", correctAnswer: "Прощение и отпущение плохих поступков", distractors: ["Праздник света", "День отдыха", "Радость и танцы"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🍎\nВ семье Леви 5 человек, и каждый съедает 2 дольки яблока с мёдом. В одном яблоке 5 долек. Сколько яблок нужно?", correctAnswer: "2 яблока", distractors: ["1 яблоко", "5 яблок", "10 яблок"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🛖\nДлина сукки 3 метра, а ширина — 2 метра. Какова площадь сукки?", correctAnswer: "6 квадратных метров", distractors: ["5 квадратных метров", "10 квадратных метров", "12 квадратных метров"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📅\nЕсли Рош ха-Шана выпал на вторник, в какой день недели будет Йом Кипур (через 9 дней)?", correctAnswer: "В четверг", distractors: ["Во вторник", "В субботу", "В воскресенье"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌿\nЗачем машут четырьмя видами растений во все стороны?", correctAnswer: "Как знак, что Бог везде и правит всеми сторонами света", distractors: ["Чтобы листья высохли", "Чтобы отогнать комаров", "Потому что это детская игра"], tier: .hard, grades: 3...5),
    ]
}
