import Foundation

/// 🌍 География — русский. Переведено с ивритского банка (328 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let geography: [BankQuestion] = [
        BankQuestion(prompt: "🇮🇱\nКакая столица Израиля?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Беэр-Шева"], grades: 2...4),
        BankQuestion(prompt: "🌊\nКакое море находится к западу от Израиля?", correctAnswer: "Средиземное море", distractors: ["Красное море", "Мёртвое море", "Чёрное море"], grades: 2...4),
        BankQuestion(prompt: "🏞️\nКакое море самое солёное в мире?", correctAnswer: "Мёртвое море", distractors: ["Средиземное море", "Красное море", "Чёрное море"], grades: 2...4),
        BankQuestion(prompt: "🌎\nНа каком материке находится Израиль?", correctAnswer: "Азия", distractors: ["Африка", "Европа", "Америка"], grades: 4...6),
        BankQuestion(prompt: "🗽\nКакая столица США?", correctAnswer: "Вашингтон", distractors: ["Нью-Йорк", "Лос-Анджелес", "Чикаго"], grades: 4...6),
        BankQuestion(prompt: "🗼\nВ какой стране стоит Эйфелева башня?", correctAnswer: "Франция", distractors: ["Италия", "Англия", "Испания"], grades: 4...6),
        BankQuestion(prompt: "🐼\nГде живут панды?", correctAnswer: "Китай", distractors: ["Япония", "Австралия", "Индия"], grades: 2...4),
        BankQuestion(prompt: "🦘\nГде живут кенгуру?", correctAnswer: "Австралия", distractors: ["Африка", "Америка", "Европа"], grades: 2...4),
        BankQuestion(prompt: "🐧\nГде живут пингвины в самом сильном холоде?", correctAnswer: "В Антарктиде", distractors: ["В Средиземном море", "В пустыне Сахара", "На Северном полюсе"], grades: 2...4),
        BankQuestion(prompt: "🏔️\nКакая гора самая высокая в мире?", correctAnswer: "Эверест", distractors: ["Хермон", "Килиманджаро", "Монблан"], grades: 4...6),
        BankQuestion(prompt: "🌊\nКакое море или океан самое большое в мире?", correctAnswer: "Тихий океан", distractors: ["Средиземное море", "Атлантический океан", "Индийский океан"], grades: 4...6),
        BankQuestion(prompt: "🏞️\nКакая река самая длинная в мире?", correctAnswer: "Нил", distractors: ["Иордан", "Амазонка", "Миссисипи"], grades: 4...6),
        BankQuestion(prompt: "🌍\nСколько материков в мире?", correctAnswer: "7", distractors: ["5", "6", "8"], grades: 4...6),
        BankQuestion(prompt: "🐘\nГде живут слоны?", correctAnswer: "В Африке и в Индии", distractors: ["В Израиле", "В Австралии", "В Антарктиде"], grades: 2...4),
        BankQuestion(prompt: "🇮🇹\nКакая столица Италии?", correctAnswer: "Рим", distractors: ["Милан", "Флоренция", "Венеция"], grades: 4...6),
        BankQuestion(prompt: "🇪🇸\nКакая столица Испании?", correctAnswer: "Мадрид", distractors: ["Барселона", "Севилья", "Валенсия"], grades: 4...6),
        BankQuestion(prompt: "🇬🇧\nКакая столица Англии?", correctAnswer: "Лондон", distractors: ["Манчестер", "Ливерпуль", "Эдинбург"], grades: 4...6),
        BankQuestion(prompt: "🇯🇵\nКакая столица Японии?", correctAnswer: "Токио", distractors: ["Сеул", "Пекин", "Гонконг"], grades: 4...6),
        BankQuestion(prompt: "🏜️\nКакая пустыня самая большая в Израиле?", correctAnswer: "Негев", distractors: ["Сахара", "Синай", "Гоби"], grades: 2...4),
        BankQuestion(prompt: "🌍\nКакой материк самый большой?", correctAnswer: "Азия", distractors: ["Африка", "Америка", "Европа"], grades: 4...6),
        BankQuestion(prompt: "Какой город — столица Японии?", correctAnswer: "Токио", distractors: ["Пекин", "Сеул", "Бангкок"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая река самая длинная в мире?", correctAnswer: "Нил", distractors: ["Амазонка", "Иордан", "Миссисипи"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "На каком материке находится большая часть Египта?", correctAnswer: "Африка", distractors: ["Азия", "Европа", "Америка"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какая гора самая высокая в мире?", correctAnswer: "Эверест", distractors: ["Хермон", "Килиманджаро", "Монблан"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какое море — самое низкое место на Земле?", correctAnswer: "Мёртвое море", distractors: ["Средиземное море", "Красное море", "озеро Кинерет"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Какой город — столица Австралии?", correctAnswer: "Канберра", distractors: ["Сидней", "Мельбурн", "Перт"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Сколько материков в мире?", correctAnswer: "7", distractors: ["5", "6", "8"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какой океан самый большой в мире?", correctAnswer: "Тихий океан", distractors: ["Атлантический океан", "Индийский океан", "Северный Ледовитый океан"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "В какой стране стоит Эйфелева башня?", correctAnswer: "Франция", distractors: ["Италия", "Испания", "Англия"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Какая страна занимает целый материк?", correctAnswer: "Австралия", distractors: ["Индия", "Бразилия", "Россия"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏛️\nКакой город — столица Израиля?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Эйлат"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏙️\nГде живёт очень много людей в высоких домах?", correctAnswer: "В городе", distractors: ["В деревне", "В лесу", "В пустыне"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌅\nС какой стороны встаёт солнце утром?", correctAnswer: "Восток", distractors: ["Запад", "Север", "Юг"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌇\nС какой стороны садится солнце вечером?", correctAnswer: "Запад", distractors: ["Восток", "Север", "Юг"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🇮🇱\nКакие цвета на флаге Израиля?", correctAnswer: "Голубой и белый", distractors: ["Красный и белый", "Зелёный и жёлтый", "Чёрный и белый"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "✡️\nКакой знак нарисован в середине флага Израиля?", correctAnswer: "Щит Давида", distractors: ["Менора", "Лев", "Солнце"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🗺️\nЧто обозначает синий цвет на карте?", correctAnswer: "Море и вода", distractors: ["Горы", "Леса", "Пустыня"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🌧️\nВ какое время года в Израиле идёт больше всего дождя?", correctAnswer: "Зимой", distractors: ["Летом", "Весной", "Осенью"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "☀️\nКакое время года в Израиле самое жаркое?", correctAnswer: "Лето", distractors: ["Зима", "Весна", "Осень"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🕎\nЧто нарисовано на гербе Израиля?", correctAnswer: "Менора и оливковые ветви", distractors: ["Щит Давида и звёзды", "Лев и флаг", "Солнце и море"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏜️\nКак называется большая пустыня на юге Израиля?", correctAnswer: "Негев", distractors: ["Галилея", "Шарон", "Шфела"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "⛰️\nКак называется горный край на севере Израиля?", correctAnswer: "Галилея", distractors: ["Негев", "Арава", "Шфела"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🧂\nКакое самое низкое место на Земле?", correctAnswer: "Мёртвое море", distractors: ["Озеро Кинерет", "Средиземное море", "Красное море"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🚰\nКак называется самое большое пресное озеро в Израиле?", correctAnswer: "Кинерет", distractors: ["Мёртвое море", "Красное море", "Средиземное море"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🏞️\nКакая река течёт из Кинерета в Мёртвое море?", correctAnswer: "Река Иордан", distractors: ["Нил", "Ручей Яркон", "Ручей Александр"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "⚓\nВ каком городе есть большой порт и гора Кармель?", correctAnswer: "Хайфа", distractors: ["Эйлат", "Тель-Авив", "Ашдод"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🐠\nНа берегу какого моря стоит город Эйлат?", correctAnswer: "Красное море", distractors: ["Средиземное море", "Мёртвое море", "Озеро Кинерет"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🐪\nКакой город называют столицей Негева?", correctAnswer: "Беэр-Шева", distractors: ["Димона", "Арад", "Эйлат"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🌡️\nКакая погода стоит в Негеве?", correctAnswer: "Пустынная — жарко и сухо", distractors: ["Дождливо и холодно", "Снег круглый год", "Жарко и очень влажно"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "🧭\nКакая соседняя страна находится к северу от Израиля?", correctAnswer: "Ливан", distractors: ["Египет", "Иордания", "Кипр"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🧭\nКакая соседняя страна находится к востоку от Израиля?", correctAnswer: "Иордания", distractors: ["Ливан", "Египет", "Турция"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🐫\nКакая соседняя страна находится к юго-западу от Израиля?", correctAnswer: "Египет", distractors: ["Иордания", "Ливан", "Греция"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🌏\nНа каком материке находится Израиль?", correctAnswer: "Азия", distractors: ["Европа", "Африка", "Америка"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "💧\nОткуда сегодня берут почти всю питьевую воду в Израиле?", correctAnswer: "Из опреснения морской воды", distractors: ["Из снега на Хермоне", "Из привоза из других стран", "Только из колодцев в пустыне"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🚜\nКак называется посёлок, где жители живут и работают вместе, сообща?", correctAnswer: "Кибуц", distractors: ["Город", "Квартал", "Пригород"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🏙️\nКакой город в Израиле самый большой по числу жителей?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Ришон-ле-Цион"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🚿\nКак называется стройка, которая повела воду из Кинерета на юг страны?", correctAnswer: "Всеизраильский водовод", distractors: ["Суэцкий канал", "Водовод Яркон — Негев", "Трубопровод в Эйлат"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "⛵\nС каким океаном Средиземное море соединяется через Гибралтарский пролив?", correctAnswer: "Атлантический океан", distractors: ["Тихий океан", "Индийский океан", "Северный Ледовитый океан"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🌊\nКакой океан самый большой в мире?", correctAnswer: "Тихий океан", distractors: ["Атлантический океан", "Индийский океан", "Северный Ледовитый океан"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🌏\nКакой материк самый большой в мире?", correctAnswer: "Азия", distractors: ["Африка", "Европа", "Северная Америка"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🗼\nКакой город — столица Франции?", correctAnswer: "Париж", distractors: ["Лондон", "Рим", "Мадрид"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🇺🇸\nКакой город — столица Соединённых Штатов Америки?", correctAnswer: "Вашингтон", distractors: ["Нью-Йорк", "Лос-Анджелес", "Чикаго"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏞️\nКакую реку считают самой длинной в мире?", correctAnswer: "Нил", distractors: ["Амазонка", "Иордан", "Дунай"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏜️\nКакая жаркая пустыня самая большая в мире?", correctAnswer: "Сахара", distractors: ["Негев", "Гоби", "Атакама"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🧱\nВ какой стране стоит Великая стена?", correctAnswer: "Китай", distractors: ["Япония", "Индия", "Египет"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🐧\nКакой материк самый холодный в мире?", correctAnswer: "Антарктида", distractors: ["Европа", "Азия", "Австралия"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🌴\nКакая погода стоит вокруг экватора?", correctAnswer: "Тропическая — жарко и дождливо", distractors: ["Полярная — очень холодно", "Пустынная — очень сухо", "Умеренная — прохладно"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🇫🇷\nКакая столица Франции?", correctAnswer: "Париж", distractors: ["Марсель", "Лион", "Ницца"], grades: 4...6),
        BankQuestion(prompt: "🇩🇪\nКакая столица Германии?", correctAnswer: "Берлин", distractors: ["Мюнхен", "Гамбург", "Франкфурт"], grades: 4...6),
        BankQuestion(prompt: "🇺🇸\nКакая столица Соединённых Штатов Америки?", correctAnswer: "Вашингтон", distractors: ["Нью-Йорк", "Лос-Анджелес", "Чикаго"], grades: 4...6),
        BankQuestion(prompt: "🇨🇦\nКакая столица Канады?", correctAnswer: "Оттава", distractors: ["Торонто", "Ванкувер", "Монреаль"], grades: 4...6),
        BankQuestion(prompt: "🇧🇷\nКакая столица Бразилии?", correctAnswer: "Бразилиа", distractors: ["Рио-де-Жанейро", "Сан-Паулу", "Салвадор"], grades: 4...6),
        BankQuestion(prompt: "🇦🇺\nКакая столица Австралии?", correctAnswer: "Канберра", distractors: ["Сидней", "Мельбурн", "Перт"], grades: 4...6),
        BankQuestion(prompt: "🇷🇺\nКакая столица России?", correctAnswer: "Москва", distractors: ["Санкт-Петербург", "Киев", "Минск"], grades: 4...6),
        BankQuestion(prompt: "🇨🇳\nКакая столица Китая?", correctAnswer: "Пекин", distractors: ["Шанхай", "Гонконг", "Гуанчжоу"], grades: 4...6),
        BankQuestion(prompt: "🇮🇳\nКакая столица Индии?", correctAnswer: "Нью-Дели", distractors: ["Мумбаи", "Бангалор", "Калькутта"], grades: 4...6),
        BankQuestion(prompt: "🇲🇽\nКакая столица Мексики?", correctAnswer: "Мехико", distractors: ["Канкун", "Гвадалахара", "Монтеррей"], grades: 4...6),
        BankQuestion(prompt: "🇦🇷\nКакая столица Аргентины?", correctAnswer: "Буэнос-Айрес", distractors: ["Сантьяго", "Монтевидео", "Лима"], grades: 4...6),
        BankQuestion(prompt: "🇪🇬\nКакая столица Египта?", correctAnswer: "Каир", distractors: ["Александрия", "Луксор", "Асуан"], grades: 4...6),
        BankQuestion(prompt: "🇿🇦\nВ каком городе работает правительство Южной Африки?", correctAnswer: "Претория", distractors: ["Кейптаун", "Йоханнесбург", "Дурбан"], grades: 4...6),
        BankQuestion(prompt: "🇹🇷\nКакая столица Турции?", correctAnswer: "Анкара", distractors: ["Стамбул", "Измир", "Бурса"], grades: 4...6),
        BankQuestion(prompt: "🇸🇦\nКакая столица Саудовской Аравии?", correctAnswer: "Эр-Рияд", distractors: ["Мекка", "Джидда", "Медина"], grades: 4...6),
        BankQuestion(prompt: "🇦🇪\nКакая столица Объединённых Арабских Эмиратов?", correctAnswer: "Абу-Даби", distractors: ["Дубай", "Шарджа", "Аджман"], grades: 4...6),
        BankQuestion(prompt: "🇰🇷\nКакая столица Южной Кореи?", correctAnswer: "Сеул", distractors: ["Пусан", "Инчхон", "Пхеньян"], grades: 4...6),
        BankQuestion(prompt: "🇮🇱\nКакое море самое солёное в Израиле?", correctAnswer: "Мёртвое море", distractors: ["Озеро Кинерет", "Средиземное море", "Красное море"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакое пресное озеро самое большое в Израиле?", correctAnswer: "Кинерет", distractors: ["Мёртвое море", "Озеро Хула", "Красное море"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакая гора самая высокая в Израиле?", correctAnswer: "Хермон", distractors: ["Мерон", "Тавор", "Кармель"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакая река самая длинная в Израиле?", correctAnswer: "Иордан", distractors: ["Яркон", "Кишон", "Александр"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакой город находится рядом с Мёртвым морем?", correctAnswer: "Арад", distractors: ["Назарет", "Цфат", "Эйлат"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакой город самый южный в Израиле?", correctAnswer: "Эйлат", distractors: ["Беэр-Шева", "Арад", "Димона"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакой город самый северный в Израиле?", correctAnswer: "Метула", distractors: ["Кирьят-Шмона", "Цфат", "Тверия"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакой город — столица Израиля?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Беэр-Шева"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nСколько округов в Израиле?", correctAnswer: "6", distractors: ["4", "5", "8"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакое море находится на западе Израиля?", correctAnswer: "Средиземное море", distractors: ["Красное море", "Мёртвое море", "Чёрное море"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакое море находится на юге Израиля?", correctAnswer: "Красное море", distractors: ["Средиземное море", "Мёртвое море", "Чёрное море"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакая страна граничит с Израилем на севере?", correctAnswer: "Ливан", distractors: ["Египет", "Турция", "Иордания"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакая страна граничит с Израилем на востоке?", correctAnswer: "Иордания", distractors: ["Ливан", "Египет", "Ирак"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nКакая страна граничит с Израилем на юге?", correctAnswer: "Египет", distractors: ["Судан", "Сирия", "Саудовская Аравия"], grades: 2...4),
        BankQuestion(prompt: "🌎\nСколько океанов в мире?", correctAnswer: "5", distractors: ["3", "4", "7"], grades: 4...6),
        BankQuestion(prompt: "🌊\nКакой океан самый большой?", correctAnswer: "Тихий океан", distractors: ["Атлантический океан", "Индийский океан", "Северный Ледовитый океан"], grades: 4...6),
        BankQuestion(prompt: "🌍\nКакой материк самый маленький?", correctAnswer: "Австралия", distractors: ["Европа", "Антарктида", "Африка"], grades: 4...6),
        BankQuestion(prompt: "🐧\nКакой материк самый холодный?", correctAnswer: "Антарктида", distractors: ["Азия", "Европа", "Америка"], grades: 4...6),
        BankQuestion(prompt: "🦒\nНа каком материке в среднем жарче всего?", correctAnswer: "Африка", distractors: ["Азия", "Австралия", "Америка"], grades: 4...6),
        BankQuestion(prompt: "🌍\nНа каком материке больше всего стран?", correctAnswer: "Африка", distractors: ["Азия", "Европа", "Америка"], grades: 4...6),
        BankQuestion(prompt: "🗼\nЭйфелева башня стоит в...?", correctAnswer: "В Париже", distractors: ["В Лондоне", "В Риме", "В Берлине"], grades: 4...6),
        BankQuestion(prompt: "🗽\nСтатуя Свободы стоит в...?", correctAnswer: "В Нью-Йорке", distractors: ["В Вашингтоне", "В Чикаго", "В Майами"], grades: 4...6),
        BankQuestion(prompt: "🗿\nСтатуи моаи стоят...?", correctAnswer: "На острове Пасхи", distractors: ["В Мексике", "В Перу", "В Индонезии"], grades: 4...6),
        BankQuestion(prompt: "🏯\nЗачем построили Великую Китайскую стену?", correctAnswer: "Чтобы защищаться от врагов", distractors: ["Чтобы украсить вид", "Чтобы хранить зерно", "Для скачек на лошадях"], grades: 4...6),
        BankQuestion(prompt: "🕌\nК какому городу мусульмане поворачиваются во время молитвы?", correctAnswer: "Мекка", distractors: ["Медина", "Иерусалим", "Каир"], grades: 4...6),
        BankQuestion(prompt: "🕍\nКакой город — главное место молитвы для евреев?", correctAnswer: "Иерусалим", distractors: ["Тверия", "Цфат", "Тель-Авив"], grades: 4...6),
        BankQuestion(prompt: "⛪\nВ каком государстве живёт Папа Римский?", correctAnswer: "Ватикан", distractors: ["Франция", "Испания", "Португалия"], grades: 4...6),
        BankQuestion(prompt: "🌊\nКакая река самая длинная в Африке?", correctAnswer: "Нил", distractors: ["Конго", "Нигер", "Замбези"], grades: 4...6),
        BankQuestion(prompt: "🌊\nКакая река самая длинная в Южной Америке?", correctAnswer: "Амазонка", distractors: ["Парана", "Парагвай", "Ориноко"], grades: 4...6),
        BankQuestion(prompt: "🌊\nКакая река самая длинная в Европе?", correctAnswer: "Волга", distractors: ["Дунай", "Рейн", "Сена"], grades: 4...6),
        BankQuestion(prompt: "🏔️\nКакая гора находится во Франции?", correctAnswer: "Монблан", distractors: ["Эверест", "Килиманджаро", "Фудзияма"], grades: 4...6),
        BankQuestion(prompt: "🏔️\nКакие горы тянутся через Южную Америку?", correctAnswer: "Анды", distractors: ["Альпы", "Гималаи", "Уральские горы"], grades: 4...6),
        BankQuestion(prompt: "🦁\nГде живут львы на воле?", correctAnswer: "В Африке", distractors: ["В Антарктиде", "В Израиле", "В Канаде"], grades: 4...6),
        BankQuestion(prompt: "🐪\nГде в Израиле можно увидеть верблюдов?", correctAnswer: "В пустыне", distractors: ["В море", "В снегу", "В тропическом лесу"], grades: 2...4),
        BankQuestion(prompt: "🐨\nВ какой стране живёт коала?", correctAnswer: "Австралия", distractors: ["Китай", "Индия", "Бразилия"], grades: 4...6),
        BankQuestion(prompt: "🐻‍❄️\nГде живёт белый медведь?", correctAnswer: "На Северном полюсе", distractors: ["В пустыне", "В тропическом лесу", "В Африке"], grades: 4...6),
        BankQuestion(prompt: "🦓\nНа каком материке живёт зебра?", correctAnswer: "Африка", distractors: ["Европа", "Австралия", "Антарктида"], grades: 4...6),
        BankQuestion(prompt: "🦜\nГде живёт много разноцветных попугаев?", correctAnswer: "В тропическом лесу", distractors: ["На полюсе", "В пустыне", "На снегу"], grades: 4...6),
        BankQuestion(prompt: "🏖️\nКакой большой город стоит на берегу Средиземного моря?", correctAnswer: "Тель-Авив", distractors: ["Иерусалим", "Беэр-Шева", "Димона"], grades: 2...4),
        BankQuestion(prompt: "⚓\nКакой большой портовый город находится на севере Израиля?", correctAnswer: "Хайфа", distractors: ["Эйлат", "Тверия", "Цфат"], grades: 2...4),
        BankQuestion(prompt: "🌊\nНа берегу какого моря стоит город Эйлат?", correctAnswer: "Красное море", distractors: ["Мёртвое море", "Средиземное море", "Озеро Кинерет"], grades: 2...4),
        BankQuestion(prompt: "🐟\nНа берегу какого озера стоит город Тверия?", correctAnswer: "Кинерет", distractors: ["Мёртвое море", "Средиземное море", "Красное море"], grades: 2...4),
        BankQuestion(prompt: "🏛️\nКакой старинный город на севере знаменит тем, что стоит на горе?", correctAnswer: "Цфат", distractors: ["Эйлат", "Ашдод", "Герцлия"], grades: 2...4),
        BankQuestion(prompt: "🧭\nКакая сторона света находится на карте сверху?", correctAnswer: "Север", distractors: ["Юг", "Восток", "Запад"], grades: 2...4),
        BankQuestion(prompt: "☀️\nС какой стороны встаёт солнце утром?", correctAnswer: "Восток", distractors: ["Запад", "Север", "Юг"], grades: 2...4),
        BankQuestion(prompt: "🇬🇷\nКакая столица Греции?", correctAnswer: "Афины", distractors: ["Рим", "Стамбул", "Каир"], grades: 4...6),
        BankQuestion(prompt: "🇵🇹\nКакая столица Португалии?", correctAnswer: "Лиссабон", distractors: ["Мадрид", "Барселона", "Париж"], grades: 4...6),
        BankQuestion(prompt: "🇳🇱\nКакая столица Нидерландов?", correctAnswer: "Амстердам", distractors: ["Брюссель", "Берлин", "Париж"], grades: 4...6),
        BankQuestion(prompt: "🇨🇭\nКакая столица Швейцарии?", correctAnswer: "Берн", distractors: ["Цюрих", "Женева", "Вена"], grades: 4...6),
        BankQuestion(prompt: "🇸🇪\nКакая столица Швеции?", correctAnswer: "Стокгольм", distractors: ["Осло", "Копенгаген", "Хельсинки"], grades: 4...6),
        BankQuestion(prompt: "🌋\nВ какой части Израиля находится город Эйлат?", correctAnswer: "На юге", distractors: ["На севере", "На востоке", "На западе"], grades: 2...4),
        BankQuestion(prompt: "🏔️\nВ каком месте в Израиле зимой выпадает снег?", correctAnswer: "Хермон", distractors: ["Эйлат", "Негев", "Тель-Авив"], grades: 2...4),
        BankQuestion(prompt: "🐊\nВ какой реке в Африке живут крокодилы?", correctAnswer: "Нил", distractors: ["Амазонка", "Иордан", "Яркон"], grades: 4...6),
        BankQuestion(prompt: "🦅\nНа каком материке находится самый большой тропический лес?", correctAnswer: "Южная Америка", distractors: ["Европа", "Австралия", "Антарктида"], grades: 4...6),
        BankQuestion(prompt: "🐅\nНа каком материке тигр живёт на воле?", correctAnswer: "Азия", distractors: ["Антарктида", "Австралия", "Европа"], grades: 4...6),
        BankQuestion(prompt: "🏝️\nАвстралия — это и материк, и...?", correctAnswer: "Страна", distractors: ["Река", "Гора", "Океан"], grades: 4...6),
        BankQuestion(prompt: "🌍\nНа каком материке находится большая часть Египта?", correctAnswer: "Африка", distractors: ["Азия", "Европа", "Южная Америка"], grades: 4...6),
        BankQuestion(prompt: "🌎\nНа каком материке находится Бразилия?", correctAnswer: "Южная Америка", distractors: ["Африка", "Европа", "Азия"], grades: 4...6),
        BankQuestion(prompt: "🐫\nКакая огромная пустыня находится на севере Африки?", correctAnswer: "Сахара", distractors: ["Негев", "Синай", "Гоби"], grades: 4...6),
        BankQuestion(prompt: "🏞️\nКакая река течёт по Израилю и впадает в Мёртвое море?", correctAnswer: "Иордан", distractors: ["Нил", "Амазонка", "Яркон"], grades: 2...4),
        BankQuestion(prompt: "🌊\nКакое солёное озеро находится на юго-востоке Израиля?", correctAnswer: "Мёртвое море", distractors: ["Озеро Кинерет", "Средиземное море", "Красное море"], grades: 2...4),
        BankQuestion(prompt: "🦬\nНа каком материке живут большие бизоны в прериях?", correctAnswer: "Северная Америка", distractors: ["Антарктида", "Европа", "Австралия"], grades: 4...6),
        BankQuestion(prompt: "🌐\nКак называется шар, на котором виден весь мир?", correctAnswer: "Глобус", distractors: ["Компас", "Телескоп", "Часы"], grades: 2...4),
        BankQuestion(prompt: "🗺️\nНа чём рисуют материки и моря?", correctAnswer: "Карта", distractors: ["Календарь", "Книга рецептов", "Грамота"], grades: 2...4),
        BankQuestion(prompt: "🐘\nНа каком материке живут самые большие слоны?", correctAnswer: "Африка", distractors: ["Европа", "Австралия", "Антарктида"], grades: 4...6),
        BankQuestion(prompt: "🇮🇪\nКакая столица Ирландии?", correctAnswer: "Дублин", distractors: ["Лондон", "Эдинбург", "Амстердам"], grades: 4...6),
        BankQuestion(prompt: "🏜️\nКакая область занимает почти весь юг Израиля?", correctAnswer: "Негев", distractors: ["Галилея", "Шарон", "Кармель"], grades: 2...4),
        BankQuestion(prompt: "🗼\nВ каком городе стоит Эйфелева башня?", correctAnswer: "Париж", distractors: ["Лондон", "Рим", "Мадрид"], grades: 4...6),
        BankQuestion(prompt: "🌊\nКак называется самое солёное море в Израиле?", correctAnswer: "Мёртвое море", distractors: ["Средиземное море", "Озеро Кинерет", "Красное море"], grades: 2...4),
        BankQuestion(prompt: "🐘\nНа каком материке живут на воле слоны и львы?", correctAnswer: "Африка", distractors: ["Европа", "Антарктида", "Австралия"], grades: 4...6),
        BankQuestion(prompt: "🐧\nГде живут пингвины в самом сильном холоде?", correctAnswer: "Антарктида", distractors: ["Северный полюс", "Израиль", "Пустыня"], grades: 4...6),
        BankQuestion(prompt: "🦘\nВ какой стране живут кенгуру?", correctAnswer: "Австралия", distractors: ["Израиль", "Египет", "Канада"], grades: 4...6),
        BankQuestion(prompt: "🐼\nВ какой стране живёт медведь панда?", correctAnswer: "Китай", distractors: ["Франция", "Бразилия", "Греция"], grades: 4...6),
        BankQuestion(prompt: "🏰\nКакая столица Франции?", correctAnswer: "Париж", distractors: ["Берлин", "Афины", "Каир"], grades: 4...6),
        BankQuestion(prompt: "🎡\nКакая столица Англии?", correctAnswer: "Лондон", distractors: ["Париж", "Рим", "Лиссабон"], grades: 4...6),
        BankQuestion(prompt: "🍕\nКакая столица Италии?", correctAnswer: "Рим", distractors: ["Милан", "Париж", "Вена"], grades: 4...6),
        BankQuestion(prompt: "🐪\nГде много песка и почти нет воды?", correctAnswer: "Пустыня", distractors: ["Лес", "Океан", "Полюс"], grades: 0...2),
        BankQuestion(prompt: "⛰️\nКак называется высокая гора на севере Израиля, на которую выпадает снег?", correctAnswer: "Хермон", distractors: ["Гора Тавор", "Гора Кармель", "Масада"], grades: 2...4),
        BankQuestion(prompt: "💧\nКак называется большое озеро в Израиле, из которого пьют воду?", correctAnswer: "Кинерет", distractors: ["Мёртвое море", "Яркон", "Средиземное море"], grades: 2...4),
        BankQuestion(prompt: "🏖️\nКак называется город на юге Израиля с морем и коралловым рифом?", correctAnswer: "Эйлат", distractors: ["Хайфа", "Цфат", "Тверия"], grades: 2...4),
        BankQuestion(prompt: "🚢\nВ каком городе Израиля есть большой морской порт и гора Кармель?", correctAnswer: "Хайфа", distractors: ["Иерусалим", "Беэр-Шева", "Эйлат"], grades: 2...4),
        BankQuestion(prompt: "🐠\nКак называется море возле Эйлата с разноцветными рыбками?", correctAnswer: "Красное море", distractors: ["Мёртвое море", "Озеро Кинерет", "Средиземное море"], grades: 2...4),
        BankQuestion(prompt: "🌍\nНа каком материке находится Израиль?", correctAnswer: "Азия", distractors: ["Африка", "Европа", "Австралия"], grades: 4...6),
        BankQuestion(prompt: "🦁\nКак называется место, где смотрят на зверей за оградой?", correctAnswer: "Зоопарк", distractors: ["Лес", "Пустыня", "Море"], grades: 0...2),
        BankQuestion(prompt: "🦅\nКак называется река, которая течёт через Тель-Авив?", correctAnswer: "Яркон", distractors: ["Иордан", "Нил", "Кинерет"], grades: 2...4),
        BankQuestion(prompt: "🛶\nКак называется река на границе Израиля с восточным соседом?", correctAnswer: "Иордан", distractors: ["Яркон", "Нил", "Кинерет"], grades: 2...4),
        BankQuestion(prompt: "🐻\nГде растёт много высоких деревьев и живут дикие звери?", correctAnswer: "Лес", distractors: ["Пустыня", "Город", "Пляж"], grades: 0...2),
        BankQuestion(prompt: "🇯🇵\nВ какой стране солнце на флаге и едят суши?", correctAnswer: "Япония", distractors: ["Израиль", "Италия", "Мексика"], grades: 4...6),
        BankQuestion(prompt: "🏛️\nКакая столица Греции?", correctAnswer: "Афины", distractors: ["Рим", "Каир", "Париж"], grades: 4...6),
        BankQuestion(prompt: "🌐\nСколько материков в мире?", correctAnswer: "семь", distractors: ["три", "пять", "десять"], grades: 4...6),
        BankQuestion(prompt: "🕌\nВ каком городе находится Стена Плача?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Эйлат", "Хайфа"], grades: 2...4),
        BankQuestion(prompt: "🐫\nНа каком континенте находится огромная пустыня Сахара?", correctAnswer: "Африка", distractors: ["Европа", "Азия", "Австралия"], grades: 4...6),
        BankQuestion(prompt: "❄️\nКак называется самое холодное место на Земле, где очень много льда?", correctAnswer: "полюс", distractors: ["пустыня", "лес", "ферма"], grades: 0...2),
        BankQuestion(prompt: "Сколько континентов на Земле?", correctAnswer: "семь", distractors: ["пять", "четыре", "восемь"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Какая столица у Израиля?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Эйлат"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что из этого самое большое?", correctAnswer: "континент", distractors: ["остров", "деревня", "город"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется очень большое скопление воды на Земле?", correctAnswer: "океан", distractors: ["лужа", "бассейн", "стакан"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "С какой стороны восходит солнце утром?", correctAnswer: "восток", distractors: ["запад", "север", "юг"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется большое море к западу от Израиля?", correctAnswer: "Средиземное море", distractors: ["Мёртвое море", "Кинерет", "Чёрное море"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "На каком континенте находится Израиль?", correctAnswer: "Азия", distractors: ["Европа", "Африка", "Австралия"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Как называется суша, со всех сторон окружённая водой?", correctAnswer: "остров", distractors: ["гора", "пустыня", "долина"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется рисунок, на котором показаны страны и моря?", correctAnswer: "карта", distractors: ["книга", "часы", "игрушка"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется маленький шар, на котором виден весь мир?", correctAnswer: "глобус", distractors: ["бинокль", "фотоаппарат", "футбольный мяч"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что находится сверху на большинстве карт?", correctAnswer: "север", distractors: ["юг", "восток", "запад"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется место, где много песка и жары и почти нет воды?", correctAnswer: "пустыня", distractors: ["лес", "океан", "озеро"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется очень высокое место с вершиной?", correctAnswer: "гора", distractors: ["долина", "пляж", "шоссе"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется песчаное место у самого моря?", correctAnswer: "пляж", distractors: ["гора", "лес", "пустыня"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "В каком водоёме Израиля легко держаться на воде?", correctAnswer: "Мёртвое море", distractors: ["Кинерет", "Средиземное море", "Красное море"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется большое озеро на севере Израиля?", correctAnswer: "Кинерет", distractors: ["Мёртвое море", "Яркон", "Средиземное море"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какая столица у Франции?", correctAnswer: "Париж", distractors: ["Лондон", "Рим", "Мадрид"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Как называется поток воды, который течёт по суше?", correctAnswer: "река", distractors: ["гора", "пустыня", "остров"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Сколько больших океанов есть на Земле?", correctAnswer: "пять", distractors: ["два", "три", "десять"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Какой город стоит на берегу Красного моря на юге Израиля?", correctAnswer: "Эйлат", distractors: ["Иерусалим", "Хайфа", "Цфат"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется направление, противоположное северу?", correctAnswer: "юг", distractors: ["восток", "запад", "вверх"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется место, где растёт очень много деревьев?", correctAnswer: "лес", distractors: ["пустыня", "пляж", "гора"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "На каком континенте находится Египет с пирамидами?", correctAnswer: "Африка", distractors: ["Европа", "Азия", "Антарктида"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Какой континент весь покрыт льдом и снегом?", correctAnswer: "Антарктида", distractors: ["Африка", "Азия", "Европа"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Как называется низкое место между двумя горами?", correctAnswer: "долина", distractors: ["вершина", "пляж", "остров"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется место, где вместе живут люди, много домов и улиц?", correctAnswer: "город", distractors: ["пустыня", "море", "гора"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что покрывает большую часть нашей планеты?", correctAnswer: "вода", distractors: ["суша", "песок", "лёд"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется наша страна?", correctAnswer: "Израиль", distractors: ["Египет", "Франция", "Греция"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какое направление противоположно востоку?", correctAnswer: "запад", distractors: ["север", "юг", "вниз"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какая столица у Италии?", correctAnswer: "Рим", distractors: ["Париж", "Афины", "Лиссабон"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "В какой стране находится Эйфелева башня?", correctAnswer: "Франция", distractors: ["Италия", "Испания", "Англия"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Как называется вода, которую можно пить, — такая, как в Кинерете и в реках?", correctAnswer: "пресная вода", distractors: ["солёная вода", "камни", "песок"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что показывает нам стороны света, когда мы идём в поход?", correctAnswer: "компас", distractors: ["часы", "бинокль", "фонарик"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какая столица у Египта?", correctAnswer: "Каир", distractors: ["Париж", "Рим", "Афины"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Какой большой город стоит на берегу Средиземного моря в центре Израиля?", correctAnswer: "Тель-Авив", distractors: ["Цфат", "Эйлат", "Тверия"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой большой портовый город находится на севере Израиля, на берегу моря?", correctAnswer: "Хайфа", distractors: ["Эйлат", "Иерусалим", "Беэр-Шева"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой континент — это одна большая страна?", correctAnswer: "Австралия", distractors: ["Азия", "Европа", "Африка"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Как называется широкая дорога, по которой едут машины?", correctAnswer: "шоссе", distractors: ["река", "гора", "лес"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какая столица у Англии?", correctAnswer: "Лондон", distractors: ["Париж", "Рим", "Берлин"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Какое место на Земле самое холодное?", correctAnswer: "полюс", distractors: ["пустыня", "пляж", "город"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что растёт в большом количестве в месте, которое называют лесом?", correctAnswer: "деревья", distractors: ["песок", "лёд", "камни"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Каким цветом обозначают воду на большинстве карт?", correctAnswer: "синим", distractors: ["зелёным", "коричневым", "красным"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется большое африканское животное с длинным хоботом?", correctAnswer: "слон", distractors: ["медведь", "пингвин", "верблюд"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Где живут верблюды?", correctAnswer: "в пустыне", distractors: ["на полюсе", "в море", "в океане"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называются белые хлопья, которые падают в высоком холодном месте?", correctAnswer: "снег", distractors: ["песок", "тёплый дождь", "пыль"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какое направление противоположно югу?", correctAnswer: "север", distractors: ["восток", "запад", "вверх"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется место, где суша встречается с морем?", correctAnswer: "берег", distractors: ["вершина", "долина", "пустыня"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Где воды больше всего?", correctAnswer: "в океане", distractors: ["в озере", "в луже", "везде одинаково"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какая столица у Испании?", correctAnswer: "Мадрид", distractors: ["Лиссабон", "Париж", "Рим"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "В какой стране находится Великая стена длиной тысячи километров?", correctAnswer: "Китай", distractors: ["Япония", "Индия", "Франция"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "Какой из семи континентов самый большой?", correctAnswer: "Азия", distractors: ["Европа", "Австралия", "Антарктида"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой океан самый большой на Земле?", correctAnswer: "Тихий океан", distractors: ["Атлантический океан", "Индийский океан", "Северный Ледовитый океан"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Греции?", correctAnswer: "Афины", distractors: ["Рим", "Мадрид", "Анкара"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "В какой стране находится падающая Пизанская башня?", correctAnswer: "Италия", distractors: ["Франция", "Испания", "Греция"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какое место на суше самое низкое на Земле?", correctAnswer: "Мёртвое море", distractors: ["Кинерет", "Средиземное море", "Красное море"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как называется длинная река, которая течёт через Египет?", correctAnswer: "Нил", distractors: ["Иордан", "Яркон", "Дунай"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Как называется главная река Израиля, которая течёт в Кинерет и в Мёртвое море?", correctAnswer: "Иордан", distractors: ["Нил", "Яркон", "Амазонка"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какая столица у Германии?", correctAnswer: "Берлин", distractors: ["Париж", "Вена", "Амстердам"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая столица у России?", correctAnswer: "Москва", distractors: ["Варшава", "Киев", "Берлин"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "В какой стране стоит статуя Свободы?", correctAnswer: "США", distractors: ["Германия", "Канада", "Англия"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой древний город на севере Израиля стоит на горе и знаменит художниками?", correctAnswer: "Цфат", distractors: ["Эйлат", "Тель-Авив", "Ашдод"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой большой город на юге Израиля называют столицей Негева?", correctAnswer: "Беэр-Шева", distractors: ["Хайфа", "Тверия", "Нетания"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "На каком континенте находится Бразилия?", correctAnswer: "Южная Америка", distractors: ["Северная Америка", "Африка", "Азия"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая столица у США?", correctAnswer: "Вашингтон", distractors: ["Нью-Йорк", "Лос-Анджелес", "Чикаго"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Канады?", correctAnswer: "Оттава", distractors: ["Торонто", "Монреаль", "Ванкувер"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая гора самая высокая в Израиле?", correctAnswer: "Хермон", distractors: ["Тавор", "Кармель", "Масада"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое море находится между Эйлатом и Египтом?", correctAnswer: "Красное море", distractors: ["Средиземное море", "Мёртвое море", "Чёрное море"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какая столица у Японии?", correctAnswer: "Токио", distractors: ["Пекин", "Сеул", "Бангкок"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Китая?", correctAnswer: "Пекин", distractors: ["Токио", "Шанхай", "Гонконг"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Голландии?", correctAnswer: "Амстердам", distractors: ["Брюссель", "Берлин", "Париж"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Португалии?", correctAnswer: "Лиссабон", distractors: ["Мадрид", "Рим", "Париж"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Как называется воображаемая линия, которая делит Землю на север и юг?", correctAnswer: "экватор", distractors: ["береговая линия", "линия границы", "линия горизонта"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "На каком континенте находится Индия?", correctAnswer: "Азия", distractors: ["Африка", "Европа", "Австралия"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Как называется самая северная точка Земли?", correctAnswer: "Северный полюс", distractors: ["Южный полюс", "экватор", "восток"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "На каком полюсе живут белые медведи?", correctAnswer: "на Северном полюсе", distractors: ["на Южном полюсе", "на экваторе", "в пустыне"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Где живут пингвины?", correctAnswer: "в Антарктиде", distractors: ["в Сахаре", "в амазонских джунглях", "в пустыне Негев"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая песчаная пустыня самая большая в мире?", correctAnswer: "Сахара", distractors: ["пустыня Негев", "Иудейская пустыня", "пустыня Гоби"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой континент находится между Тихим и Атлантическим океанами в северной части Земли?", correctAnswer: "Северная Америка", distractors: ["Южная Америка", "Европа", "Азия"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Турции?", correctAnswer: "Анкара", distractors: ["Стамбул", "Афины", "Рим"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какое море находится между Европой и Африкой?", correctAnswer: "Средиземное море", distractors: ["Красное море", "Чёрное море", "Мёртвое море"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "В какой стране находится Тадж-Махал?", correctAnswer: "Индия", distractors: ["Китай", "Япония", "Египет"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Как называется группа островов, расположенных рядом друг с другом?", correctAnswer: "архипелаг", distractors: ["континент", "залив", "полуостров"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Как называется полоска суши, которая уходит в море и окружена водой с трёх сторон?", correctAnswer: "полуостров", distractors: ["остров", "залив", "озеро"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Что всегда показывает стрелка компаса?", correctAnswer: "север", distractors: ["юг", "восток", "запад"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой из семи континентов самый маленький?", correctAnswer: "Австралия", distractors: ["Европа", "Африка", "Азия"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "В какой стране можно увидеть кенгуру в дикой природе?", correctAnswer: "Австралия", distractors: ["Канада", "Франция", "Египет"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какое море отделяет Европу от Азии и названо по цвету?", correctAnswer: "Чёрное море", distractors: ["Красное море", "Жёлтое море", "Белое море"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Аргентины?", correctAnswer: "Буэнос-Айрес", distractors: ["Рио-де-Жанейро", "Сантьяго", "Лима"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая страна самая большая в мире по площади?", correctAnswer: "Россия", distractors: ["Китай", "Канада", "США"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой израильский город стоит на берегу Кинерета?", correctAnswer: "Тверия", distractors: ["Эйлат", "Беэр-Шева", "Ашкелон"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой континент находится южнее Европы, за Средиземным морем?", correctAnswer: "Африка", distractors: ["Азия", "Австралия", "Северная Америка"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Австралии?", correctAnswer: "Канберра", distractors: ["Сидней", "Мельбурн", "Перт"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой океан находится между Европой и Америкой?", correctAnswer: "Атлантический океан", distractors: ["Тихий океан", "Индийский океан", "Северный Ледовитый океан"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какое утверждение о Кинерете верное?", correctAnswer: "это озеро с пресной водой", distractors: ["это очень солёное море", "это океан", "это пустыня"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "В какой стороне от Иерусалима находится Эйлат?", correctAnswer: "на юге", distractors: ["на севере", "на востоке", "на западе"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как называется узкая полоса воды между двумя материками?", correctAnswer: "пролив", distractors: ["вершина", "долина", "водопад"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая известная гора на юге Израиля, на которой стоит древняя крепость?", correctAnswer: "Масада", distractors: ["Хермон", "Тавор", "Кармель"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какая река самая полноводная в мире и течёт по Южной Америке?", correctAnswer: "Амазонка", distractors: ["Нил", "Миссисипи", "Дунай"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой горный хребет самый высокий в мире и находится в Азии?", correctAnswer: "Гималаи", distractors: ["Альпы", "Анды", "Скалистые горы"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой известный горный хребет проходит по Европе через Францию и Швейцарию?", correctAnswer: "Альпы", distractors: ["Гималаи", "Анды", "Урал"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Швейцарии?", correctAnswer: "Берн", distractors: ["Цюрих", "Женева", "Вена"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Австрии?", correctAnswer: "Вена", distractors: ["Берн", "Мюнхен", "Братислава"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Швеции?", correctAnswer: "Стокгольм", distractors: ["Осло", "Копенгаген", "Хельсинки"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Норвегии?", correctAnswer: "Осло", distractors: ["Стокгольм", "Копенгаген", "Рейкьявик"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Польши?", correctAnswer: "Варшава", distractors: ["Прага", "Будапешт", "Берлин"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Венгрии?", correctAnswer: "Будапешт", distractors: ["Варшава", "Прага", "Вена"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой океан находится южнее Азии, рядом с Индией?", correctAnswer: "Индийский океан", distractors: ["Тихий океан", "Атлантический океан", "Северный Ледовитый океан"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "В какой стране живёт больше всего людей в мире?", correctAnswer: "Индия", distractors: ["Китай", "США", "Россия"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая большая река течёт через США и впадает в Мексиканский залив?", correctAnswer: "Миссисипи", distractors: ["Амазонка", "Нил", "Темза"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая река течёт через Лондон?", correctAnswer: "Темза", distractors: ["Сена", "Дунай", "Рейн"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая река течёт через Париж?", correctAnswer: "Сена", distractors: ["Темза", "Рейн", "Дунай"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая высокая и знаменитая гора находится в Японии?", correctAnswer: "Фудзи", distractors: ["Эверест", "Килиманджаро", "Монблан"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая гора самая высокая в Африке?", correctAnswer: "Килиманджаро", distractors: ["Эверест", "Фудзи", "Монблан"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Бразилии?", correctAnswer: "Бразилиа", distractors: ["Рио-де-Жанейро", "Сан-Паулу", "Буэнос-Айрес"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Мексики?", correctAnswer: "Мехико", distractors: ["Канкун", "Гвадалахара", "Лима"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое море находится южнее Израиля и соединяется с Суэцким каналом?", correctAnswer: "Красное море", distractors: ["Средиземное море", "Чёрное море", "Мёртвое море"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая большая страна находится южнее США и знаменита культурой майя?", correctAnswer: "Мексика", distractors: ["Канада", "Бразилия", "Аргентина"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой длинный горный хребет тянется вдоль Южной Америки?", correctAnswer: "Анды", distractors: ["Альпы", "Гималаи", "Скалистые горы"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Дании?", correctAnswer: "Копенгаген", distractors: ["Осло", "Стокгольм", "Амстердам"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Бельгии?", correctAnswer: "Брюссель", distractors: ["Амстердам", "Париж", "Люксембург"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая длинная река течёт по центру Европы через Вену и Будапешт?", correctAnswer: "Дунай", distractors: ["Сена", "Темза", "Нил"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой итальянский город построен на множестве водных каналов?", correctAnswer: "Венеция", distractors: ["Рим", "Милан", "Неаполь"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое озеро самое большое в мире по площади?", correctAnswer: "Каспийское море", distractors: ["Кинерет", "Мёртвое море", "озеро Виктория"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая страна находится севернее США и является второй по величине в мире?", correctAnswer: "Канада", distractors: ["Мексика", "Россия", "Бразилия"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Румынии?", correctAnswer: "Бухарест", distractors: ["Будапешт", "София", "Варшава"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой океан окружает Северный полюс?", correctAnswer: "Северный Ледовитый океан", distractors: ["Тихий океан", "Индийский океан", "Атлантический океан"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой египетский город находится рядом с большими пирамидами?", correctAnswer: "Гиза", distractors: ["Афины", "Рим", "Вавилон"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая большая островная страна находится рядом с Англией, а её столица — Дублин?", correctAnswer: "Ирландия", distractors: ["Исландия", "Шотландия", "Голландия"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Ирландии?", correctAnswer: "Дублин", distractors: ["Лондон", "Эдинбург", "Рейкьявик"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая ледяная островная страна находится на севере Атлантического океана?", correctAnswer: "Исландия", distractors: ["Ирландия", "Голландия", "Финляндия"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Финляндии?", correctAnswer: "Хельсинки", distractors: ["Осло", "Стокгольм", "Таллин"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой американский город знаменит статуей Свободы и высокими небоскрёбами?", correctAnswer: "Нью-Йорк", distractors: ["Вашингтон", "Лос-Анджелес", "Майами"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой известный пролив отделяет Испанию от Африки?", correctAnswer: "Гибралтарский пролив", distractors: ["Суэцкий канал", "Берингов пролив", "Панамский канал"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой знаменитый канал соединяет Тихий океан с Атлантическим в Центральной Америке?", correctAnswer: "Панамский канал", distractors: ["Суэцкий канал", "Гибралтарский пролив", "Берингов пролив"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой канал соединяет Средиземное море с Красным морем?", correctAnswer: "Суэцкий канал", distractors: ["Панамский канал", "Гибралтарский пролив", "Берингов пролив"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая европейская страна знаменита ветряными мельницами и полями тюльпанов?", correctAnswer: "Голландия", distractors: ["Бельгия", "Дания", "Швейцария"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой самый большой и самый дождливый лес в мире находится в Южной Америке?", correctAnswer: "амазонские джунгли", distractors: ["тайга", "джунгли Конго", "Сахара"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая длинная и узкая страна тянется вдоль западного побережья Южной Америки?", correctAnswer: "Чили", distractors: ["Бразилия", "Аргентина", "Перу"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Перу, страны древних инков?", correctAnswer: "Лима", distractors: ["Богота", "Сантьяго", "Кито"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая страна в Азии знаменита цветением сакуры и поездами синкансэн?", correctAnswer: "Япония", distractors: ["Китай", "Индия", "Корея"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Южной Кореи?", correctAnswer: "Сеул", distractors: ["Токио", "Пекин", "Бангкок"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Таиланда?", correctAnswer: "Бангкок", distractors: ["Сеул", "Токио", "Ханой"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой древний город в Италии был столицей огромной империи две тысячи лет назад?", correctAnswer: "Рим", distractors: ["Милан", "Венеция", "Неаполь"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое озеро самое большое в Африке?", correctAnswer: "озеро Виктория", distractors: ["Кинерет", "Байкал", "Мёртвое море"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой город находится одновременно в Европе и в Азии?", correctAnswer: "Стамбул", distractors: ["Анкара", "Афины", "Москва"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая крошечная страна внутри Рима — самая маленькая в мире?", correctAnswer: "Ватикан", distractors: ["Монако", "Сан-Марино", "Люксембург"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая пустыня находится на юге Израиля?", correctAnswer: "Негев", distractors: ["Сахара", "Гоби", "Атакама"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какая гора рядом с Хайфой покрыта зелёной растительностью?", correctAnswer: "Кармель", distractors: ["Хермон", "Тавор", "Масада"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какое озеро в России самое глубокое в мире?", correctAnswer: "Байкал", distractors: ["озеро Виктория", "Каспийское море", "Кинерет"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая столица у Индии?", correctAnswer: "Нью-Дели", distractors: ["Мумбаи", "Пекин", "Бангкок"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая большая и холодная пустыня в Азии находится между Китаем и Монголией?", correctAnswer: "Гоби", distractors: ["Сахара", "Атакама", "Негев"], tier: .hard, grades: 4...6),
    ]
}
