import Foundation

/// 🍎 Еда — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let food: [BankQuestion] = [
        BankQuestion(prompt: "🐄\nОт какого животного получают молоко?", correctAnswer: "Корова", distractors: ["Курица", "Рыба", "Бабочка"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥚\nКакое животное несёт яйца, которые мы едим?", correctAnswer: "Курица", distractors: ["Корова", "Собака", "Кошка"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍯\nКто делает мёд?", correctAnswer: "Пчёлы", distractors: ["Муравьи", "Бабочки", "Птицы"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍞\nИз чего пекут хлеб?", correctAnswer: "Из муки", distractors: ["Из песка", "Из сыра", "Из шоколада"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧀\nИз чего делают сыр?", correctAnswer: "Из молока", distractors: ["Из воды", "Из сока", "Из муки"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍫\nИз чего делают шоколад?", correctAnswer: "Из какао-бобов", distractors: ["Из яблок", "Из риса", "Из моркови"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍇\nИз какого фрукта делают изюм?", correctAnswer: "Из винограда", distractors: ["Из яблок", "Из бананов", "Из арбуза"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍟\nИз какого овоща делают чипсы?", correctAnswer: "Из картофеля", distractors: ["Из моркови", "Из помидоров", "Из лука"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍅\nИз чего делают кетчуп?", correctAnswer: "Из помидоров", distractors: ["Из моркови", "Из картофеля", "Из салата-латука"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌳\nКакой фрукт растёт на дереве?", correctAnswer: "Яблоко", distractors: ["Морковь", "Картофель", "Огурец"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥔\nКакой овощ растёт под землёй?", correctAnswer: "Картофель", distractors: ["Помидор", "Огурец", "Салат-латук"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🫓\nКак называется круглый хлеб, у которого внутри кармашек?", correctAnswer: "Пита", distractors: ["Хала", "Багет", "Круассан"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍎\nЯблоко — это…", correctAnswer: "Фрукт", distractors: ["Овощ", "Сыр", "Хлеб"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥕\nМорковь — это…", correctAnswer: "Овощ", distractors: ["Фрукт", "Рыба", "Торт"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍌\nКакого цвета спелый банан?", correctAnswer: "Жёлтый", distractors: ["Синий", "Фиолетовый", "Чёрный"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍊\nКакого цвета апельсин?", correctAnswer: "Оранжевый", distractors: ["Синий", "Белый", "Розовый"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍎\nЧто стоит есть каждый день?", correctAnswer: "Фрукты и овощи", distractors: ["Конфеты", "Шоколад", "Чипсы"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "💧\nЧто лучше всего пить, когда мучает жажда?", correctAnswer: "Воду", distractors: ["Масло", "Уксус", "Кетчуп"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧊\nЧто будет со льдом, если оставить его на солнце?", correctAnswer: "Он растает", distractors: ["Он замёрзнет", "Он вырастет", "Он станет синим"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "💧\nВода, которую поставили в морозилку, превращается в…", correctAnswer: "Лёд", distractors: ["Пар", "Сок", "Молоко"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧼\nЧто делают перед тем, как начать готовить?", correctAnswer: "Моют руки", distractors: ["Причёсываются", "Надевают ботинки", "Выключают свет"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔥\nКто должен помочь, когда включают горячую духовку?", correctAnswer: "Взрослый", distractors: ["Младший брат", "Собака", "Кукла"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍲\nКак несут тарелку с горячим супом?", correctAnswer: "Медленно и осторожно", distractors: ["Бегом", "Одной рукой над головой", "Подпрыгивая на ходу"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥄\nЧем едят суп?", correctAnswer: "Ложкой", distractors: ["Вилкой", "Ножом", "Ножницами"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔪\nЧем режут хлеб?", correctAnswer: "Ножом", distractors: ["Ложкой", "Вилкой", "Стаканом"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧁\nНа каждый торт нужно 2 яйца. Сколько яиц нужно на два торта?", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍪\nВ рецепте написано 3 ложки сахара. Одну ложку мы уже положили. Сколько ложек ещё нужно?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🍕\nМы разрезали пиццу на 8 кусочков и съели 3. Сколько кусочков осталось?", correctAnswer: "5", distractors: ["3", "4", "6"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧆\nИз чего делают фалафель?", correctAnswer: "Из нута", distractors: ["Из мяса", "Из сыра", "Из картофеля"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌱\nИз чего делают тхину?", correctAnswer: "Из кунжута", distractors: ["Из орехов", "Из арахиса", "Из пшеницы"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥛\nКак молоко превращают в йогурт?", correctAnswer: "Добавляют полезные бактерии", distractors: ["Замораживают его", "Добавляют сахар", "Процеживают его"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍞\nЧто заставляет хлебное тесто подниматься?", correctAnswer: "Дрожжи", distractors: ["Соль", "Холодная вода", "Какао-порошок"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌾\nИз какого растения обычно делают муку для хлеба?", correctAnswer: "Из пшеницы", distractors: ["Из хлопка", "Из моркови", "Из апельсинов"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🍚\nГде выращивают многие сорта риса?", correctAnswer: "На полях, залитых водой", distractors: ["На высоких деревьях", "На дне моря", "В сухой пустыне"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍓\nГде растёт садовая клубника?", correctAnswer: "На низком кустике у самой земли", distractors: ["На высоком дереве", "Под землёй", "В воде"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥜\nГде растёт арахис?", correctAnswer: "Под землёй", distractors: ["На дереве", "На лозе", "В воде"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍇\nНа чём растёт виноград?", correctAnswer: "На лозе", distractors: ["На яблоне", "На кусте роз", "На пальме"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌴\nКакой плод растёт на пальме?", correctAnswer: "Финик", distractors: ["Яблоко", "Груша", "Вишня"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧂\nОткуда берут соль?", correctAnswer: "Из морской воды и из шахт", distractors: ["Из деревьев", "Из коров", "Из яиц"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍯\nПочему мёд сладкий?", correctAnswer: "В нём много природных сахаров", distractors: ["Ему добавляют сахар на заводе", "Он сделан из молока", "Он растёт на деревьях"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥬\nЧто из этого относится к овощам?", correctAnswer: "Салат-латук", distractors: ["Хлеб", "Сыр", "Яйцо"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🥛\nМолоко, сыр и йогурт относятся к группе…", correctAnswer: "Молочные продукты", distractors: ["Фрукты", "Злаки", "Овощи"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍞\nХлеб, рис и макароны относятся к группе…", correctAnswer: "Злаки", distractors: ["Фрукты", "Молочные продукты", "Овощи"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥛\nСколько стаканов по 250 мл помещается в одном литре?", correctAnswer: "4", distractors: ["2", "3", "5"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "⚖️\nСколько граммов в одном килограмме?", correctAnswer: "1000", distractors: ["100", "10", "500"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥄\nВ рецепте написано «чайная ложка». Что нужно взять?", correctAnswer: "Маленькую ложку", distractors: ["Большую ложку", "Стакан", "Половник"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🧁\nНа один торт нужно 3 яйца. Сколько яиц нужно на 3 торта?", correctAnswer: "9", distractors: ["6", "3", "12"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥞\nВ рецепте нужно 2 стакана муки. Рецепт удваивают. Сколько стаканов муки нужно?", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🍪\nВ рецепте нужно 6 ложек сахара. Готовят только половину рецепта. Сколько ложек нужно?", correctAnswer: "3", distractors: ["2", "4", "12"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "⏲️\nТорт должен печься 40 минут. Мы поставили его в духовку в 4:00. Когда доставать?", correctAnswer: "4:40", distractors: ["4:20", "4:30", "5:00"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔥\nПри какой температуре кипит вода?", correctAnswer: "100 градусов Цельсия", distractors: ["10 градусов Цельсия", "50 градусов Цельсия", "200 градусов Цельсия"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧊\nПри какой температуре вода превращается в лёд?", correctAnswer: "0 градусов Цельсия", distractors: ["10 градусов Цельсия", "50 градусов Цельсия", "100 градусов Цельсия"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "♨️\nЧто поднимается над кастрюлей с кипящей водой?", correctAnswer: "Пар", distractors: ["Дым", "Облако", "Снег"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥚\nЧто происходит с прозрачным белком, когда яйцо варят?", correctAnswer: "Он становится белым и твёрдым", distractors: ["Он исчезает", "Он становится синим", "Он превращается в воду"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍽️\nЕда в тарелке слишком горячая. Что сделать перед тем, как пробовать?", correctAnswer: "Подождать, пока она немного остынет", distractors: ["Съесть её быстро", "Положить её в морозилку на час", "Полить её водой"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🧊\nЗачем молоко ставят в холодильник?", correctAnswer: "Чтобы оно дольше оставалось свежим", distractors: ["Чтобы оно стало сладким", "Чтобы оно превратилось в лёд", "Чтобы оно было горячим"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🫧\nКакой газ выделяют дрожжи в тесте, из-за чего оно поднимается?", correctAnswer: "Углекислый газ", distractors: ["Кислород", "Гелий", "Азот"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🦠\nКак называется процесс, в котором бактерии или дрожжи превращают молоко в йогурт, а тесто — в пышный хлеб?", correctAnswer: "Брожение", distractors: ["Заморозка", "Испарение", "Жарка"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🥛\nКак называется нагревание молока на молочном заводе, после которого его безопасно пить?", correctAnswer: "Пастеризация", distractors: ["Жарка", "Заморозка", "Выпечка"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "💨\nВода долго кипит в кастрюле, и кастрюля медленно пустеет. Куда делась вода?", correctAnswer: "Она превратилась в пар", distractors: ["Кастрюля её впитала", "Она превратилась в соль", "Она замёрзла"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🧊\nПочему кубик льда плавает на поверхности воды?", correctAnswer: "Лёд легче воды при одинаковом объёме", distractors: ["Потому что он холодный", "Потому что он белый", "Потому что он блестит"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🍯\nПочему мёд может храниться много лет и не портиться?", correctAnswer: "В нём очень мало воды и очень много сахара", distractors: ["Его держат в морозилке", "В него добавляют соль", "Его охраняют пчёлы"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🍫\nГде растут деревья какао?", correctAnswer: "В жарких и влажных краях возле экватора", distractors: ["На Северном полюсе", "В пустыне", "В снежных горах"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🍅\nПомидор вырастает из цветка, и внутри у него семена. Значит, с научной точки зрения он…", correctAnswer: "Плод", distractors: ["Корень", "Лист", "Стебель"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🥕\nКакая часть растения — морковка?", correctAnswer: "Корень", distractors: ["Лист", "Цветок", "Плод"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🥬\nКакую часть растения мы едим, когда едим салат-латук?", correctAnswer: "Листья", distractors: ["Корень", "Плод", "Семена"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🥦\nБрокколи — это на самом деле…", correctAnswer: "Нераскрывшиеся цветки", distractors: ["Корень", "Плод", "Семя"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🍚\nПо рецепту на 4 человек нужно 200 граммов риса. Сколько граммов нужно на 8 человек?", correctAnswer: "400", distractors: ["200", "300", "800"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🥛\nПо рецепту нужен литр молока (1000 мл). Готовят только четверть рецепта. Сколько мл молока нужно?", correctAnswer: "250", distractors: ["500", "100", "750"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "⏲️\nТорт печётся час и 15 минут. Мы поставили его в духовку в 3:30. Когда доставать?", correctAnswer: "4:45", distractors: ["4:15", "4:30", "5:00"], tier: .hard, grades: 3...5),
    ]
}
