import Foundation

/// 📜 История — русский. Переведено с ивритского банка (276 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let history: [BankQuestion] = [
        BankQuestion(prompt: "🇮🇱\nВ каком году было основано Государство Израиль?", correctAnswer: "1948", distractors: ["1945", "1950", "1967"], grades: 2...4),
        BankQuestion(prompt: "👨‍💼\nКто был первым премьер-министром Израиля?", correctAnswer: "Давид Бен-Гурион", distractors: ["Ицхак Рабин", "Менахем Бегин", "Голда Меир"], grades: 2...4),
        BankQuestion(prompt: "🕯️\nВ какой праздник зажигают свечи восемь дней подряд?", correctAnswer: "Ханука", distractors: ["Песах", "Суккот", "Пурим"], grades: 0...2),
        BankQuestion(prompt: "🫓\nВ какой праздник едят мацу?", correctAnswer: "Песах", distractors: ["Ханука", "Рош ха-Шана", "Шавуот"], grades: 0...2),
        BankQuestion(prompt: "🎭\nВ какой праздник наряжаются в костюмы?", correctAnswer: "Пурим", distractors: ["Суккот", "Ханука", "Песах"], grades: 0...2),
        BankQuestion(prompt: "🌳\nВ какой праздник сажают деревья?", correctAnswer: "Ту би-Шват", distractors: ["День независимости", "Шавуот", "Лаг ба-Омер"], grades: 1...3),
        BankQuestion(prompt: "🇮🇱\nКакой знак находится в центре флага Израиля?", correctAnswer: "Маген Давид (звезда Давида)", distractors: ["Полумесяц", "Крест", "Солнце"], grades: 2...4),
        BankQuestion(prompt: "📜\nЧто написано в Декларации независимости Израиля?", correctAnswer: "Провозглашение Государства Израиль", distractors: ["История выхода из Египта", "Кулинарный рецепт", "Слова песни"], grades: 3...5),
        BankQuestion(prompt: "👑\nКто был первым царём Израиля?", correctAnswer: "Шауль", distractors: ["Давид", "Шломо", "Авраам"], grades: 3...5),
        BankQuestion(prompt: "🏛️\nКто построил Первый Храм?", correctAnswer: "Шломо", distractors: ["Давид", "Моше", "Шауль"], grades: 3...5),
        BankQuestion(prompt: "🏺\nЧто нашли Маккавеи в Храме, когда победили греков?", correctAnswer: "Кувшинчик с маслом", distractors: ["Мацу", "Шофар", "Свиток Эстер"], grades: 1...3),
        BankQuestion(prompt: "🐑\nКто вывел сынов Израиля из Египта?", correctAnswer: "Моше", distractors: ["Йосеф", "Авраам", "Давид"], grades: 1...3),
        BankQuestion(prompt: "🏛️\nЗачем древние египтяне строили пирамиды?", correctAnswer: "Как гробницы для фараонов", distractors: ["Как дома для крестьян", "Как крепости от врагов", "Как маяки для кораблей"], grades: 4...6),
        BankQuestion(prompt: "🇺🇸\nКакой материк открыл Колумб?", correctAnswer: "Америку", distractors: ["Африку", "Австралию", "Азию"], grades: 4...6),
        BankQuestion(prompt: "📡\nКто изобрёл телефон?", correctAnswer: "Александр Грэм Белл", distractors: ["Альберт Эйнштейн", "Томас Эдисон", "Билл Гейтс"], grades: 3...5),
        BankQuestion(prompt: "💡\nКто изобрёл электрическую лампочку?", correctAnswer: "Томас Эдисон", distractors: ["Альберт Эйнштейн", "Исаак Ньютон", "Никола Тесла"], grades: 3...5),
        BankQuestion(prompt: "📕\nНа каком языке написан ТаНаХ?", correctAnswer: "На иврите", distractors: ["На английском", "На арабском", "На латыни"], grades: 2...4),
        BankQuestion(prompt: "📜\nГде жили праотцы Авраам, Ицхак и Яаков?", correctAnswer: "В Стране Израиля", distractors: ["В Египте", "В Америке", "В Европе"], grades: 2...4),
        BankQuestion(prompt: "📚\nСколько книг в Торе?", correctAnswer: "5", distractors: ["7", "10", "3"], grades: 2...4),
        BankQuestion(prompt: "🛡️\nКто сражался с Голиафом?", correctAnswer: "Давид", distractors: ["Моше", "Шломо", "Шауль"], grades: 2...4),
        BankQuestion(prompt: "В каком году возникло Государство Израиль?", correctAnswer: "1948", distractors: ["1918", "1967", "1938"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Кто был первым премьер-министром государства Израиль?", correctAnswer: "Давид Бен-Гурион", distractors: ["Хаим Вейцман", "Голда Меир", "Менахем Бегин"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Какой народ построил пирамиды?", correctAnswer: "Древние египтяне", distractors: ["Римляне", "Греки", "Вавилоняне"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Кто первым ступил на Луну?", correctAnswer: "Нил Армстронг", distractors: ["Юрий Гагарин", "Базз Олдрин", "Альберт Эйнштейн"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как называлось письмо древних египтян?", correctAnswer: "Иероглифы", distractors: ["Клинопись", "Алфавит", "Китайское письмо"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Кто изобрёл электрическую лампу?", correctAnswer: "Томас Эдисон", distractors: ["Альберт Эйнштейн", "Исаак Ньютон", "Леонардо да Винчи"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какой древний город засыпало извержение вулкана?", correctAnswer: "Помпеи", distractors: ["Афины", "Рим", "Иерусалим"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Кто написал картину «Мона Лиза»?", correctAnswer: "Леонардо да Винчи", distractors: ["Пабло Пикассо", "Ван Гог", "Микеланджело"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "О чём рассказывает праздник Ханука?", correctAnswer: "О победе Маккавеев и чуде с кувшинчиком масла", distractors: ["О выходе из Египта", "О спасении евреев в Персии", "О даровании Торы"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "Кто была первой женщиной — главой правительства Израиля?", correctAnswer: "Голда Меир", distractors: ["Ципи Ливни", "Шуламит Алони", "Пророчица Мирьям"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🫓\nЧто отмечают в праздник Песах?", correctAnswer: "Выход из Египта", distractors: ["Дарование Торы", "Чудо с кувшинчиком масла", "Основание государства"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🕎\nЧто отмечают в праздник Ханука?", correctAnswer: "Чудо с кувшинчиком масла и победу Маккавеев", distractors: ["Выход из Египта", "Дарование Торы", "Основание государства"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎭\nЧто отмечают в праздник Пурим?", correctAnswer: "Спасение евреев во времена Эстер и Мордехая", distractors: ["Выход из Египта", "Чудо с кувшинчиком масла", "Посадку деревьев"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "📜\nЧто отмечают в праздник Шавуот?", correctAnswer: "Дарование Торы", distractors: ["Выход из Египта", "Освящение Храма", "Спасение евреев в Персии"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎉\nЧто празднуют в День независимости Израиля?", correctAnswer: "Основание Государства Израиль", distractors: ["Дарование Торы", "Выход из Египта", "Начало нового года"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧱\nОстатком чего является Стена Плача?", correctAnswer: "Храма в Иерусалиме", distractors: ["Царского дворца", "Стены Иерихона", "Крепости Масада"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎩\nКого называют провидцем еврейского государства?", correctAnswer: "Биньямин Зеэв Герцль", distractors: ["Давид Бен-Гурион", "Хаим Вейцман", "Моше Рабейну"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📣\nКто провозгласил создание Государства Израиль?", correctAnswer: "Давид Бен-Гурион", distractors: ["Биньямин Зеэв Герцль", "Голда Меир", "Ицхак Рабин"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🙏\nВ каком городе находится Стена Плача?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Цфат"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🛖\nВ память о чём сидят в шалаше в праздник Суккот?", correctAnswer: "О странствии по пустыне после выхода из Египта", distractors: ["О строительстве Храма", "О чуде с кувшинчиком масла", "О даровании Торы"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📯\nВо что трубят в Рош ха-Шана?", correctAnswer: "В шофар", distractors: ["В трубу", "В барабан", "В флейту"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔥\nЧто зажигают в Лаг ба-Омер?", correctAnswer: "Костры", distractors: ["Ханукальные свечи", "Фейерверки", "Фонарики"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔺\nВ какой древней стране построили большие пирамиды?", correctAnswer: "Египет", distractors: ["Греция", "Рим", "Вавилон"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "📜\nКак называется древнее письмо Египта?", correctAnswer: "Иероглифы", distractors: ["Клинопись", "Еврейский алфавит", "Латиница"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🧱\nКак называется древнее письмо Вавилона и Шумера?", correctAnswer: "Клинопись", distractors: ["Иероглифы", "Греческое письмо", "Китайское письмо"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🏅\nВ какой древней стране родились Олимпийские игры?", correctAnswer: "Греция", distractors: ["Рим", "Египет", "Персия"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🏛️\nКакая империя правила Страной Израиля около двух тысяч лет назад?", correctAnswer: "Римская", distractors: ["Греческая", "Египетская", "Вавилонская"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🕍\nВ каком городе стоял Храм?", correctAnswer: "Иерусалим", distractors: ["Хеврон", "Иерихон", "Беэр-Шева"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🏞️\nВозле какой большой реки возник Древний Египет?", correctAnswer: "Нил", distractors: ["Иордан", "Евфрат", "Амазонка"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🦉\nКакой древнегреческий город прославился мудростью и философами?", correctAnswer: "Афины", distractors: ["Спарта", "Рим", "Троя"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "👑\nКак называли правителей Древнего Египта?", correctAnswer: "Фараон", distractors: ["Цезарь", "Султан", "Царь"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "🏰\nКакая древняя крепость стоит на горе у Мёртвого моря?", correctAnswer: "Масада", distractors: ["Башня Давида", "Акко", "Крепость Нимрод"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "📜\nКакая страна опубликовала Декларацию Бальфура в 1917 году?", correctAnswer: "Британия", distractors: ["Франция", "США", "Турция"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🧳\nЧто означает слово «алия» в истории еврейского народа?", correctAnswer: "Переезд евреев в Страну Израиля", distractors: ["Поездка за границу", "Подъём в горы", "Переезд в другую квартиру в городе"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏘️\nКакое поселение было основано во времена Первой алии?", correctAnswer: "Ришон ле-Цион", distractors: ["Тель-Авив", "Эйлат", "Кармиэль"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "📅\nВ каком еврейском месяце отмечают День независимости?", correctAnswer: "Ияр", distractors: ["Нисан", "Тишрей", "Адар"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🗓️\nВ каком году была Шестидневная война?", correctAnswer: "1967", distractors: ["1948", "1956", "1973"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏙️\nКакой город снова стал единым в Шестидневную войну?", correctAnswer: "Иерусалим", distractors: ["Хайфа", "Беэр-Шева", "Тверия"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "👩‍💼\nКто была первой женщиной на посту премьер-министра Израиля?", correctAnswer: "Голда Меир", distractors: ["Хана Сенеш", "Наоми Шемер", "Сара Ааронсон"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🕊️\nКакую премию получил премьер-министр Ицхак Рабин в 1994 году?", correctAnswer: "Нобелевскую премию мира", distractors: ["Премию Израиля", "Олимпийскую медаль", "«Оскар»"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🌍\nЧто означает слово «галут»?", correctAnswer: "Жизнь еврейского народа вдали от Страны Израиля", distractors: ["Древний еврейский праздник", "Название древнего города", "Книга в ТаНаХе"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🎪\nВ каком городе прошёл Первый сионистский конгресс в 1897 году?", correctAnswer: "Базель", distractors: ["Вена", "Париж", "Иерусалим"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🏺\nКакая цивилизация построила пирамиды в долине Нила?", correctAnswer: "Древние египтяне", distractors: ["Римляне", "Греки", "Викинги"], grades: 5...6),
        BankQuestion(prompt: "👑\nКто был первым императором Рима?", correctAnswer: "Август", distractors: ["Юлий Цезарь", "Нерон", "Адриан"], grades: 5...6),
        BankQuestion(prompt: "⚔️\nКакой народ разрушил Второй Храм в 70 году?", correctAnswer: "Римляне", distractors: ["Греки", "Вавилоняне", "Персы"], grades: 5...6),
        BankQuestion(prompt: "✡️\nКак звали вождя народа при выходе из Египта?", correctAnswer: "Моше", distractors: ["Давид", "Шломо", "Авраам"], grades: 2...4),
        BankQuestion(prompt: "🏛️\nГде прошло первое заседание Кнессета?", correctAnswer: "В Иерусалиме", distractors: ["В Тель-Авиве", "В Хайфе", "В Беэр-Шеве"], grades: 2...4),
        BankQuestion(prompt: "🎺\nОтчего, по рассказу ТаНаХа, рухнули стены Иерихона?", correctAnswer: "От звука шофаров", distractors: ["От землетрясения", "От песчаной бури", "От потопа"], grades: 2...4),
        BankQuestion(prompt: "🏰\nКто построил Первый Храм в Иерусалиме?", correctAnswer: "Царь Шломо", distractors: ["Царь Давид", "Царь Шауль", "Царь Хизкияху"], grades: 2...4),
        BankQuestion(prompt: "⚖️\nКто царствовал после Давида?", correctAnswer: "Шломо", distractors: ["Шауль", "Яровам", "Рехавам"], grades: 2...4),
        BankQuestion(prompt: "🦁\nКто бросил Даниэля в ров со львами?", correctAnswer: "Царь Дарий", distractors: ["Навуходоносор", "Ахашверош", "Кир"], grades: 2...4),
        BankQuestion(prompt: "👑\nКем была царица Эстер?", correctAnswer: "Царицей Персии", distractors: ["Царицей Египта", "Царицей Вавилона", "Царицей Рима"], grades: 2...4),
        BankQuestion(prompt: "📜\nКакой главный язык ТаНаХа?", correctAnswer: "Иврит", distractors: ["Греческий", "Арамейский", "Арабский"], grades: 2...4),
        BankQuestion(prompt: "🛤️\nКогда было основано Государство Израиль?", correctAnswer: "В 1948 году", distractors: ["В 1917 году", "В 1967 году", "В 1973 году"], grades: 2...4),
        BankQuestion(prompt: "📜\nКто зачитал Декларацию независимости Израиля?", correctAnswer: "Давид Бен-Гурион", distractors: ["Хаим Вейцман", "Менахем Бегин", "Голда Меир"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nВ каком городе провозгласили создание Государства Израиль?", correctAnswer: "Тель-Авив", distractors: ["Иерусалим", "Хайфа", "Тверия"], grades: 2...4),
        BankQuestion(prompt: "👵\nКак звали первую женщину — премьер-министра Израиля?", correctAnswer: "Голда Меир", distractors: ["Шуламит Алони", "Ципи Ливни", "Мири Регев"], grades: 3...5),
        BankQuestion(prompt: "🦅\nКакой символ изображён на флаге Израиля?", correctAnswer: "Маген Давид (звезда Давида)", distractors: ["Лев", "Орёл", "Оливковая ветвь"], grades: 2...4),
        BankQuestion(prompt: "🇺🇸\nКогда возникли Соединённые Штаты Америки?", correctAnswer: "1776", distractors: ["1620", "1492", "1800"], grades: 5...6),
        BankQuestion(prompt: "🧭\nКто открыл Америку в 1492 году?", correctAnswer: "Христофор Колумб", distractors: ["Магеллан", "Васко да Гама", "Марко Поло"], grades: 5...6),
        BankQuestion(prompt: "🚀\nКто был первым человеком на Луне?", correctAnswer: "Нил Армстронг", distractors: ["Юрий Гагарин", "Базз Олдрин", "Джон Гленн"], grades: 3...5),
        BankQuestion(prompt: "🚀\nКто был первым человеком в космосе?", correctAnswer: "Юрий Гагарин", distractors: ["Нил Армстронг", "Алан Шепард", "Базз Олдрин"], grades: 3...5),
        BankQuestion(prompt: "🎨\nКто нарисовал «Мону Лизу»?", correctAnswer: "Леонардо да Винчи", distractors: ["Микеланджело", "Пабло Пикассо", "Ван Гог"], grades: 4...6),
        BankQuestion(prompt: "🎼\nКто написал «Маленькую ночную серенаду»?", correctAnswer: "Моцарт", distractors: ["Бетховен", "Бах", "Шопен"], grades: 4...6),
        BankQuestion(prompt: "💡\nКто изобрёл лампочку?", correctAnswer: "Томас Эдисон", distractors: ["Альберт Эйнштейн", "Исаак Ньютон", "Александр Грэм Белл"], grades: 3...5),
        BankQuestion(prompt: "📞\nКто изобрёл телефон?", correctAnswer: "Александр Грэм Белл", distractors: ["Томас Эдисон", "Гульельмо Маркони", "Исаак Ньютон"], grades: 3...5),
        BankQuestion(prompt: "🌌\nКто объяснил, почему предметы падают на землю?", correctAnswer: "Исаак Ньютон", distractors: ["Альберт Эйнштейн", "Галилео Галилей", "Николай Коперник"], grades: 3...5),
        BankQuestion(prompt: "🧪\nКто открыл пенициллин?", correctAnswer: "Александр Флеминг", distractors: ["Луи Пастер", "Томас Эдисон", "Мария Кюри"], grades: 5...6),
        BankQuestion(prompt: "👩‍🔬\nКто была первой женщиной, получившей Нобелевскую премию?", correctAnswer: "Мария Кюри", distractors: ["Альберт Эйнштейн", "Александр Флеминг", "Исаак Ньютон"], grades: 5...6),
        BankQuestion(prompt: "🏛️\nКакую страну считают колыбелью демократии?", correctAnswer: "Древняя Греция", distractors: ["Древний Рим", "Древний Египет", "Древний Китай"], grades: 5...6),
        BankQuestion(prompt: "📜\nКакой рассказ — самый древний из известных нам?", correctAnswer: "Эпос о Гильгамеше", distractors: ["ТаНаХ", "«Одиссея»", "«Илиада»"], grades: 5...6),
        BankQuestion(prompt: "🏯\nНа каком материке находится Великая Китайская стена?", correctAnswer: "Азия", distractors: ["Европа", "Африка", "Австралия"], grades: 3...5),
        BankQuestion(prompt: "🗡️\nКто вёл французскую армию в начале XIX века?", correctAnswer: "Наполеон", distractors: ["Джордж Вашингтон", "Уинстон Черчилль", "Отто фон Бисмарк"], grades: 5...6),
        BankQuestion(prompt: "👑\nКем была королева Елизавета I?", correctAnswer: "Королевой Англии", distractors: ["Королевой Франции", "Королевой Испании", "Королевой России"], grades: 5...6),
        BankQuestion(prompt: "🇪🇬\nКем была Клеопатра?", correctAnswer: "Царицей Египта", distractors: ["Царицей Рима", "Царицей Греции", "Царицей Вавилона"], grades: 5...6),
        BankQuestion(prompt: "⚔️\nКогда началась Первая мировая война?", correctAnswer: "В 1914 году", distractors: ["В 1900 году", "В 1939 году", "В 1918 году"], grades: 5...6),
        BankQuestion(prompt: "⚔️\nКогда закончилась Вторая мировая война?", correctAnswer: "В 1945 году", distractors: ["В 1918 году", "В 1939 году", "В 1950 году"], grades: 5...6),
        BankQuestion(prompt: "🌐\nКогда придумали интернет?", correctAnswer: "В 1960-е годы", distractors: ["В 1900-е годы", "В 1850-е годы", "В 2000-е годы"], grades: 3...5),
        BankQuestion(prompt: "📱\nКогда вышел первый айфон?", correctAnswer: "В 2007 году", distractors: ["В 1990 году", "В 2000 году", "В 2015 году"], grades: 3...5),
        BankQuestion(prompt: "🚂\nКто прославился созданием первых паровозов?", correctAnswer: "Джордж Стефенсон", distractors: ["Джеймс Уатт", "Томас Эдисон", "Генри Форд"], grades: 3...5),
        BankQuestion(prompt: "🚗\nКто изобрёл автомобиль?", correctAnswer: "Карл Бенц", distractors: ["Генри Форд", "Томас Эдисон", "Джеймс Уатт"], grades: 3...5),
        BankQuestion(prompt: "✈️\nКто изобрёл самолёт?", correctAnswer: "Братья Райт", distractors: ["Альберт Эйнштейн", "Томас Эдисон", "Джеймс Уатт"], grades: 3...5),
        BankQuestion(prompt: "🇮🇱\nКак называлась эта земля под британским правлением до 1948 года?", correctAnswer: "Подмандатная Палестина", distractors: ["Израиль", "Ханаан", "Иудея"], grades: 3...5),
        BankQuestion(prompt: "🇮🇱\nКакая роль у президента Израиля?", correctAnswer: "Представительская", distractors: ["Управлять страной", "Командовать армией", "Возглавлять суд"], grades: 4...6),
        BankQuestion(prompt: "🏛️\nСколько депутатов в Кнессете?", correctAnswer: "120", distractors: ["100", "150", "200"], grades: 4...6),
        BankQuestion(prompt: "👴\nКто был первым начальником Генштаба ЦАХАЛа?", correctAnswer: "Яаков Дори", distractors: ["Давид Бен-Гурион", "Моше Даян", "Ицхак Рабин"], grades: 3...5),
        BankQuestion(prompt: "🎖️\nКакого цвета берет у военно-воздушных сил Израиля?", correctAnswer: "Синий", distractors: ["Красный", "Чёрный", "Зелёный"], grades: 2...4),
        BankQuestion(prompt: "🍯🍎\nВ какой праздник макают яблоко в мёд?", correctAnswer: "Рош ха-Шана", distractors: ["Ханука", "Пурим", "Шавуот"], grades: 2...4),
        BankQuestion(prompt: "🛖\nВ какой праздник машут лулавом и этрогом?", correctAnswer: "Суккот", distractors: ["Песах", "Ханука", "Пурим"], grades: 2...4),
        BankQuestion(prompt: "🥛🧀\nВ какой праздник принято есть молочные блюда?", correctAnswer: "Шавуот", distractors: ["Песах", "Суккот", "Пурим"], grades: 2...4),
        BankQuestion(prompt: "🎁\nКак называются подарочные наборы еды, которые дарят в Пурим?", correctAnswer: "Мишлоах манот", distractors: ["Афикоман", "Севивон", "Маца"], grades: 2...4),
        BankQuestion(prompt: "🥔\nКакое жареное блюдо принято есть в Хануку?", correctAnswer: "Оладьи-латкес", distractors: ["Мацу", "Халу", "Яблоко в мёде"], grades: 2...4),
        BankQuestion(prompt: "🍩\nКакое сладкое угощение принято есть в Хануку?", correctAnswer: "Пончик-суфгания", distractors: ["Морковный торт", "Мацу", "Халу"], grades: 2...4),
        BankQuestion(prompt: "🔄\nКак называется вращающаяся игрушка Хануки?", correctAnswer: "Севивон (волчок)", distractors: ["Шофар", "Трещотка", "Дудочка"], grades: 2...4),
        BankQuestion(prompt: "📣\nВ какой праздник шумят трещотками?", correctAnswer: "Пурим", distractors: ["Песах", "Суккот", "Ту би-Шват"], grades: 2...4),
        BankQuestion(prompt: "🍇\nВ какой праздник принято есть сухофрукты?", correctAnswer: "Ту би-Шват", distractors: ["Ханука", "Пурим", "Йом Кипур"], grades: 2...4),
        BankQuestion(prompt: "📖\nКак называется книга, которую читают в пасхальный вечер?", correctAnswer: "Агада", distractors: ["Мегила", "Сидур", "Хумаш"], grades: 2...4),
        BankQuestion(prompt: "🐍\nВо что превратился посох Моше перед фараоном?", correctAnswer: "В змею", distractors: ["В лягушку", "В льва", "В голубя"], grades: 2...4),
        BankQuestion(prompt: "🌊\nКакое море расступилось перед сынами Израиля?", correctAnswer: "Красное море (Ям Суф)", distractors: ["Кинерет", "Мёртвое море", "Река Иордан"], grades: 2...4),
        BankQuestion(prompt: "🛶\nКто построил большой ковчег и взял в него животных?", correctAnswer: "Ноах (Ной)", distractors: ["Моше", "Авраам", "Давид"], grades: 2...4),
        BankQuestion(prompt: "🌈\nКакой знак дал Бог Ноаху после потопа?", correctAnswer: "Радугу в облаках", distractors: ["Звезду", "Лестницу", "Шофар"], grades: 2...4),
        BankQuestion(prompt: "🪜\nКому приснилась лестница с ангелами?", correctAnswer: "Яакову", distractors: ["Йосефу", "Моше", "Шмуэлю"], grades: 2...4),
        BankQuestion(prompt: "🎨\nУ кого была разноцветная рубашка (ктонет пасим)?", correctAnswer: "У Йосефа", distractors: ["У Давида", "У Аарона", "У Ицхака"], grades: 2...4),
        BankQuestion(prompt: "👶\nГде нашли младенца Моше в корзинке?", correctAnswer: "В реке Нил", distractors: ["В пустыне", "В шалаше", "На горе"], grades: 2...4),
        BankQuestion(prompt: "🗿\nНа чём Бог написал десять заповедей?", correctAnswer: "На каменных скрижалях", distractors: ["На бумаге", "На дереве", "На песке"], grades: 2...4),
        BankQuestion(prompt: "🏔️\nНа какой горе Моше получил Тору?", correctAnswer: "Гора Синай", distractors: ["Гора Хермон", "Гора Кармель", "Гора Тавор"], grades: 2...4),
        BankQuestion(prompt: "🐑\nКем был Давид до того, как стал царём?", correctAnswer: "Пастухом", distractors: ["Плотником", "Рыбаком", "Священником"], grades: 2...4),
        BankQuestion(prompt: "🪨\nЧем Давид победил Голиафа?", correctAnswer: "Пращой и камнем", distractors: ["Мечом", "Луком", "Палкой"], grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nСколько цветов на флаге Израиля?", correctAnswer: "Два", distractors: ["Три", "Четыре", "Один"], grades: 2...4),
        BankQuestion(prompt: "🎵\nКак называется гимн Государства Израиль?", correctAnswer: "«Ха-Тиква»", distractors: ["«Золотой Иерусалим»", "«Эвейну шалом алейхем»", "«Добрая земля»"], grades: 2...4),
        BankQuestion(prompt: "💰\nКак называются деньги, которыми пользуются в Израиле?", correctAnswer: "Шекель", distractors: ["Доллар", "Евро", "Фунт"], grades: 2...4),
        BankQuestion(prompt: "🌴\nНа каком дереве растут финики?", correctAnswer: "Пальма", distractors: ["Дуб", "Кипарис", "Сосна"], grades: 2...4),
        BankQuestion(prompt: "🐪\nКакое животное называют «кораблём пустыни»?", correctAnswer: "Верблюд", distractors: ["Лошадь", "Осёл", "Корова"], grades: 2...4),
        BankQuestion(prompt: "💡\nЧто изобрёл Томас Эдисон, чтобы в доме было светло?", correctAnswer: "Электрическую лампочку", distractors: ["Телефон", "Самолёт", "Поезд"], grades: 3...5),
        BankQuestion(prompt: "✈️\nЧто изобрели братья Райт — то, что летает в небе?", correctAnswer: "Самолёт", distractors: ["Корабль", "Мотоцикл", "Подводную лодку"], grades: 3...5),
        BankQuestion(prompt: "☎️\nКакой прибор изобрёл Грэм Белл, чтобы говорить издалека?", correctAnswer: "Телефон", distractors: ["Фотоаппарат", "Часы", "Компьютер"], grades: 3...5),
        BankQuestion(prompt: "🕯️\nСколько свечей зажигают в последний вечер Хануки?", correctAnswer: "Восемь", distractors: ["Одну", "Две", "Четыре"], grades: 2...4),
        BankQuestion(prompt: "📜\nКакой свиток читают в праздник Пурим?", correctAnswer: "Свиток Эстер", distractors: ["Свиток Рут", "Агаду", "Тору"], grades: 2...4),
        BankQuestion(prompt: "🍞\nКакую еду не едят в праздник Песах?", correctAnswer: "Хлеб", distractors: ["Мацу", "Яблоки", "Орехи"], grades: 2...4),
        BankQuestion(prompt: "🌳\nКакой праздник называют «днём рождения деревьев»?", correctAnswer: "Ту би-Шват", distractors: ["Пурим", "Шавуот", "Суккот"], grades: 2...4),
        BankQuestion(prompt: "🎭\nЧто принято надевать в праздник Пурим?", correctAnswer: "Карнавальный костюм", distractors: ["Плащ от дождя", "Купальник", "Пижаму"], grades: 2...4),
        BankQuestion(prompt: "🐸\nКакое животное было одной из десяти казней египетских?", correctAnswer: "Лягушка", distractors: ["Слон", "Медведь", "Жираф"], grades: 2...4),
        BankQuestion(prompt: "👑\nКто был мудрым царём, построившим Храм?", correctAnswer: "Шломо", distractors: ["Шауль", "Йосеф", "Аарон"], grades: 2...4),
        BankQuestion(prompt: "🐋\nКто проглотил пророка Йону в море?", correctAnswer: "Большая рыба", distractors: ["Крокодил", "Осьминог", "Акула"], grades: 2...4),
        BankQuestion(prompt: "⭐\nКак называется шестиконечный знак на флаге Израиля?", correctAnswer: "Маген Давид", distractors: ["Менора", "Шофар", "Корона"], grades: 2...4),
        BankQuestion(prompt: "🕎\nКакой символ с семью ветвями является гербом Израиля?", correctAnswer: "Менора", distractors: ["Севивон", "Трещотка", "Труба"], grades: 2...4),
        BankQuestion(prompt: "🏛️\nКакой город — столица Государства Израиль?", correctAnswer: "Иерусалим", distractors: ["Тель-Авив", "Хайфа", "Эйлат"], grades: 2...4),
        BankQuestion(prompt: "🌸\nВ какое время года празднуют Песах?", correctAnswer: "Весной", distractors: ["Зимой", "Летом", "Осенью"], grades: 2...4),
        BankQuestion(prompt: "🍯\nКакого года желают друг другу в Рош ха-Шана?", correctAnswer: "Сладкого", distractors: ["Холодного", "Длинного", "Дождливого"], grades: 2...4),
        BankQuestion(prompt: "📯\nНа каком инструменте трубят в Рош ха-Шана?", correctAnswer: "Шофар", distractors: ["Флейта", "Барабан", "Пианино"], grades: 2...4),
        BankQuestion(prompt: "🌿\nЧто держат вместе с лулавом в Суккот?", correctAnswer: "Этрог", distractors: ["Яблоко", "Помидор", "Цветок"], grades: 2...4),
        BankQuestion(prompt: "👫\nКто были первыми мужчиной и женщиной в Торе?", correctAnswer: "Адам и Хава (Ева)", distractors: ["Ноах и Сара", "Моше и Рут", "Давид и Эстер"], grades: 2...4),
        BankQuestion(prompt: "🌟\nСколько звёзд показал Бог Аврааму, когда обещал ему большое потомство?", correctAnswer: "Очень много", distractors: ["Три", "Одну", "Ни одной"], grades: 2...4),
        BankQuestion(prompt: "🐑\nКакое животное Авраам принёс в жертву вместо Ицхака?", correctAnswer: "Барана", distractors: ["Корову", "Голубя", "Рыбу"], grades: 2...4),
        BankQuestion(prompt: "💍\nКак звали жену Ицхака, которую он встретил у колодца?", correctAnswer: "Ривка (Ревекка)", distractors: ["Сара", "Лея", "Двора"], grades: 2...4),
        BankQuestion(prompt: "🦁\nКакое животное изображено на гербе Иерусалима?", correctAnswer: "Лев", distractors: ["Верблюд", "Рыба", "Голубь"], grades: 2...4),
        BankQuestion(prompt: "🥖\nКакой особый хлеб едят в шаббат?", correctAnswer: "Хала", distractors: ["Маца", "Пита", "Багет"], grades: 2...4),
        BankQuestion(prompt: "🕯️🕯️\nКогда зажигают свечи в честь шаббата?", correctAnswer: "В пятницу вечером", distractors: ["В воскресенье", "В полдень", "В ханукальный вечер"], grades: 2...4),
        BankQuestion(prompt: "🏜️\nСколько лет сыны Израиля шли по пустыне?", correctAnswer: "Сорок", distractors: ["Один год", "Десять", "Сто"], grades: 2...4),
        BankQuestion(prompt: "🌊\nКакое озеро в Израиле даёт пресную воду для питья?", correctAnswer: "Кинерет", distractors: ["Мёртвое море", "Средиземное море", "Красное море"], grades: 2...4),
        BankQuestion(prompt: "🚲\nНа чём принято кататься по пустым улицам в Йом Кипур в Израиле?", correctAnswer: "На велосипеде", distractors: ["На лошади", "На поезде", "На корабле"], grades: 2...4),
        BankQuestion(prompt: "В какой древней стране построили пирамиды?", correctAnswer: "Египет", distractors: ["Греция", "Китай", "Италия"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "В какой праздник каждый вечер зажигают ещё одну свечу?", correctAnswer: "Ханука", distractors: ["Пурим", "Песах", "Суккот"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "В какой праздник наряжаются и едят «уши Амана»?", correctAnswer: "Пурим", distractors: ["Ханука", "Песах", "Шавуот"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "В какой праздник едят мацу?", correctAnswer: "Песах", distractors: ["Пурим", "Ханука", "Суккот"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "В какой праздник строят шалаш из веток и едят в нём?", correctAnswer: "Суккот", distractors: ["Пурим", "Песах", "Ханука"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какое изобретение даёт нам свет в комнате ночью?", correctAnswer: "Электрическая лампочка", distractors: ["Телефон", "Автомобиль", "Часы"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "С помощью какого изобретения можно поговорить с тем, кто далеко?", correctAnswer: "Телефон", distractors: ["Лампочка", "Велосипед", "Ножницы"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой транспорт летает по воздуху?", correctAnswer: "Самолёт", distractors: ["Корабль", "Поезд", "Автомобиль"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой транспорт плывёт по воде?", correctAnswer: "Корабль", distractors: ["Самолёт", "Автомобиль", "Велосипед"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Сколько колёс у обычного велосипеда?", correctAnswer: "Два", distractors: ["Одно", "Три", "Четыре"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "На ком ездили люди до того, как появились автомобили?", correctAnswer: "На лошади", distractors: ["На самолёте", "На поезде", "На автобусе"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "В какой праздник трубят в шофар?", correctAnswer: "Рош ха-Шана", distractors: ["Пурим", "Ханука", "Песах"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Во что сладкое макают яблоко в Рош ха-Шана?", correctAnswer: "В мёд", distractors: ["В соль", "В сливочное масло", "В растительное масло"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что зажигают в Хануку?", correctAnswer: "Свечи", distractors: ["Воздушные шарики", "Цветы", "Камни"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какую игрушку крутят в Хануку?", correctAnswer: "Севивон (волчок)", distractors: ["Мяч", "Куклу", "Самолётик"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какой транспорт едет по рельсам?", correctAnswer: "Поезд", distractors: ["Самолёт", "Корабль", "Велосипед"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что люди рисовали в пещерах много тысяч лет назад?", correctAnswer: "Рисунки животных", distractors: ["Числа", "Компьютерные карты", "Фотографии с телефона"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой прибор помогает нам узнать, который час?", correctAnswer: "Часы", distractors: ["Фотоаппарат", "Насос", "Метла"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется шалаш с крышей из веток, в котором живут семь дней осенью?", correctAnswer: "Сукка", distractors: ["Палатка", "Башня", "Пещера"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "В какой праздник устраивают седер и читают Агаду?", correctAnswer: "Песах", distractors: ["Пурим", "Ханука", "Суккот"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Чем писали люди до того, как появился компьютер?", correctAnswer: "Ручка и бумага", distractors: ["Самолёт", "Автомобиль", "Телевизор"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какое животное много лет назад носило грузы по пустыне?", correctAnswer: "Верблюд", distractors: ["Рыба", "Птица", "Заяц"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какое изобретение помогает нам смотреть дома фильмы и передачи?", correctAnswer: "Телевизор", distractors: ["Автомобиль", "Велосипед", "Стол"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется большой свет, который светит нам днём?", correctAnswer: "Солнце", distractors: ["Лампочка", "Костёр", "Фонарик"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой большой транспорт возит много людей по городу?", correctAnswer: "Автобус", distractors: ["Велосипед", "Лошадь", "Самокат"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой праздник отмечают весной, а перед ним делают дома большую уборку?", correctAnswer: "Песах", distractors: ["Ханука", "Пурим", "Рош ха-Шана"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какая страна — государство еврейского народа?", correctAnswer: "Израиль", distractors: ["Египет", "Греция", "Италия"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что зажигали люди, чтобы было светло, пока не было электричества?", correctAnswer: "Свеча", distractors: ["Телефон", "Компьютер", "Телевизор"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какую особую еду едят в праздник Шавуот?", correctAnswer: "Молочные блюда", distractors: ["Маца", "Уши Амана", "Пончики"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какое сладкое жареное лакомство едят на Хануку?", correctAnswer: "Пончик", distractors: ["Маца", "Уши Амана", "Яблоко в мёду"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Как называют человека, который летит в космос на космическом корабле?", correctAnswer: "Космонавт", distractors: ["Водитель", "Повар", "Врач"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой прибор помогает нам слушать музыку?", correctAnswer: "Радио", distractors: ["Стул", "Бинокль", "Зонт"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что надевают на ноги — и раньше, и сегодня?", correctAnswer: "Обувь", distractors: ["Перчатки", "Шапка", "Очки"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой транспорт ездит по дороге на четырёх колёсах?", correctAnswer: "Автомобиль", distractors: ["Самолёт", "Корабль", "Поезд"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что пьют люди, чтобы не мучила жажда, — и раньше, и сегодня?", correctAnswer: "Вода", distractors: ["Топливо", "Краска", "Песок"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой праздник наступает после Рош ха-Шана, и взрослые в него постятся?", correctAnswer: "Йом Кипур", distractors: ["Пурим", "Ханука", "Песах"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какой прибор помогает нам фотографировать?", correctAnswer: "Фотоаппарат", distractors: ["Часы", "Ложка", "Расчёска"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что строили люди, чтобы перебраться с одного берега реки на другой?", correctAnswer: "Мост", distractors: ["Башня", "Лестница", "Шкаф"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какое особое угощение едят в Ту би-Шват?", correctAnswer: "Сухофрукты", distractors: ["Маца", "Пончики", "Уши Амана"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Как называется книга, которую читают вечером в пасхальный седер?", correctAnswer: "Агада", distractors: ["Словарь", "Атлас", "Тетрадь"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какой транспорт ныряет под воду?", correctAnswer: "Подводная лодка", distractors: ["Самолёт", "Поезд", "Автобус"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой прибор помещается в руке, и на нём пишут сообщения и играют в игры?", correctAnswer: "Мобильный телефон", distractors: ["Метла", "Мяч", "Сковорода"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой город — столица Государства Израиль?", correctAnswer: "Иерусалим", distractors: ["Париж", "Лондон", "Рим"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какой флаг белый, с синими полосами и звездой Давида?", correctAnswer: "Флаг Израиля", distractors: ["Флаг Франции", "Флаг Италии", "Флаг Японии"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какой прибор помогает разглядеть очень далёкие предметы, например звёзды?", correctAnswer: "Телескоп", distractors: ["Солнечные очки", "Расчёска", "Чайная ложка"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой древний народ построил огромный Колизей в городе Рим?", correctAnswer: "Римляне", distractors: ["Египтяне", "Китайцы", "Японцы"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Как Христофор Колумб добрался до Америки?", correctAnswer: "Приплыл по морю", distractors: ["Прилетел на самолёте", "Приехал на поезде", "Поднялся на гору"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какое изобретение позволило быстро печатать много книг вместо того, чтобы переписывать их от руки?", correctAnswer: "Печатный станок", distractors: ["Компьютер", "Телефон", "Радио"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "В какой древней стране прошли первые Олимпийские игры?", correctAnswer: "Греция", distractors: ["Египет", "Китай", "Англия"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какая большая река текла в Древнем Египте и помогала людям выращивать еду?", correctAnswer: "Нил", distractors: ["Иордан", "Амазонка", "Темза"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "На каком материале из растения писали древние египтяне?", correctAnswer: "Папирус", distractors: ["Пластик", "Стекло", "Железо"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Как называли царя, который правил в Древнем Египте?", correctAnswer: "Фараон", distractors: ["Цезарь", "Сёгун", "Махараджа"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какое очень древнее круглое изобретение помогло людям перевозить тяжести?", correctAnswer: "Колесо", distractors: ["Компьютер", "Телефон", "Фотоаппарат"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой изобретатель известен тем, что сделал удачную электрическую лампочку для дома?", correctAnswer: "Томас Эдисон", distractors: ["Альберт Эйнштейн", "Христофор Колумб", "Леонардо да Винчи"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какие два брата построили первый самолёт, который поднялся в воздух?", correctAnswer: "Братья Райт", distractors: ["Братья Гримм", "Братья Люмьер", "Братья Маркс"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое изобретение помогает хранить еду холодной и свежей на кухне?", correctAnswer: "Холодильник", distractors: ["Духовка", "Компьютер", "Вентилятор"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой праздник напоминает об исходе народа Израиля из Египта к свободе?", correctAnswer: "Песах", distractors: ["Ханука", "Пурим", "Шавуот"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какой праздник отмечает получение Торы народом Израиля?", correctAnswer: "Шавуот", distractors: ["Пурим", "Ханука", "Суккот"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какой древний прибор помогал морякам находить направление с помощью стрелки, что смотрит на север?", correctAnswer: "Компас", distractors: ["Часы", "Бинокль", "Телефон"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое знаменитое сооружение египтяне строили как гробницу для своих царей?", correctAnswer: "Пирамида", distractors: ["Колокольня", "Замок", "Мост"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой транспорт много лет назад ездил по рельсам благодаря углю и большому котлу с водой?", correctAnswer: "Паровоз", distractors: ["Реактивный самолёт", "Космический корабль", "Мотоцикл"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какая высокая железная башня стоит в Париже и знаменита на весь мир?", correctAnswer: "Эйфелева башня", distractors: ["Пирамида", "Пизанская башня", "Великая Китайская стена"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какое огромное сооружение длиной в тысячи километров построили в Китае много лет назад?", correctAnswer: "Великая Китайская стена", distractors: ["Берлинская стена", "Эйфелева башня", "Колизей"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой транспорт поднимается и опускается, а над крышей у него большой винт?", correctAnswer: "Вертолёт", distractors: ["Корабль", "Поезд", "Велосипед"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой новый и лёгкий материал изобрели, и сегодня из него делают много бутылок и игрушек?", correctAnswer: "Пластик", distractors: ["Бумага", "Золото", "Камень"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как ещё называют праздник Ту би-Шват, когда сажают деревья?", correctAnswer: "Новый год деревьев", distractors: ["Праздник первых плодов", "Праздник мацы", "Праздник огней"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Как называется главная книга еврейского народа, которую читают в синагоге?", correctAnswer: "Тора", distractors: ["Атлас", "Словарь", "Газета"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какой знаменитый учёный открыл многое о силе тяжести?", correctAnswer: "Исаак Ньютон", distractors: ["Христофор Колумб", "Томас Эдисон", "Генри Форд"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой старинный прибор отмерял время струйкой песка, перетекающей из одной колбы в другую?", correctAnswer: "Песочные часы", distractors: ["Компьютер", "Телефон", "Фотоаппарат"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "В какой древний музыкальный инструмент трубят в Рош ха-Шана?", correctAnswer: "Шофар", distractors: ["Флейта", "Барабан", "Скрипка"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое изобретение позволяет разогреть еду за считаные секунды?", correctAnswer: "Микроволновка", distractors: ["Холодильник", "Фотоаппарат", "Радио"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой старинный прибор помогал считать с помощью бусин, скользящих по прутикам?", correctAnswer: "Счёты", distractors: ["Калькулятор", "Телефон", "Часы"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой израильский праздник отмечает день, когда родилось Государство Израиль?", correctAnswer: "День независимости", distractors: ["Пурим", "Ханука", "Ту би-Шват"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое важное растение выращивали много лет назад, чтобы делать из него муку и хлеб?", correctAnswer: "Пшеница", distractors: ["Роза", "Кактус", "Водоросль"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой большой и тяжёлый транспорт возит много грузов по дороге?", correctAnswer: "Грузовик", distractors: ["Велосипед", "Самокат", "Самолёт"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "В какой праздник посылают друзьям угощения, а нуждающимся — подарки?", correctAnswer: "Пурим", distractors: ["Ханука", "Песах", "Суккот"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какой знаменитый учёный исследовал время и пространство?", correctAnswer: "Альберт Эйнштейн", distractors: ["Томас Эдисон", "Христофор Колумб", "Юлий Цезарь"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой дорогой цвет в древности носили только цари?", correctAnswer: "Пурпурный", distractors: ["Серый", "Коричневый", "Бежевый"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой быстрый транспорт летит высоко в небе и перевозит людей между странами?", correctAnswer: "Пассажирский самолёт", distractors: ["Парусная лодка", "Карета", "Самокат"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое старинное орудие помогало земледельцам вскапывать и переворачивать землю перед посевом?", correctAnswer: "Плуг", distractors: ["Фотоаппарат", "Телескоп", "Часы"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой древний знаменитый город в Греции был центром учёности и мудрости?", correctAnswer: "Афины", distractors: ["Каир", "Токио", "Москва"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "Какой знаменитый вождь вывел народ Израиля из Египта, как рассказывает история Песаха?", correctAnswer: "Моше Рабейну", distractors: ["Царь Давид", "Царь Шломо", "Авраам Авину"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какое древнее письмо из рисунков и знаков использовали египтяне?", correctAnswer: "Иероглифы", distractors: ["Компьютерный код", "Нотная запись", "Только цифры"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какой художник и изобретатель из Италии написал «Мону Лизу» и придумал много изобретений?", correctAnswer: "Леонардо да Винчи", distractors: ["Томас Эдисон", "Исаак Ньютон", "Христофор Колумб"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какой изобретатель известен тем, что создал первый телефон?", correctAnswer: "Александр Грэхем Белл", distractors: ["Томас Эдисон", "Генри Форд", "Исаак Ньютон"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какой древний народ придумал демократию — порядок, при котором люди голосуют и решают вместе?", correctAnswer: "Греки", distractors: ["Египтяне", "Китайцы", "Викинги"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какой знаменитый морской народ из Северной Европы плавал на длинных лодках и открывал далёкие земли?", correctAnswer: "Викинги", distractors: ["Египтяне", "Японцы", "Римляне"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какая знаменитая учёная исследовала излучение и дважды получила Нобелевскую премию?", correctAnswer: "Мария Кюри", distractors: ["Мария-Антуанетта", "Флоренс Найтингейл", "Анна Франк"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какая древняя страна изобрела бумагу и шёлк?", correctAnswer: "Китай", distractors: ["Египет", "Греция", "Франция"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какой праздник напоминает о чуде маленького кувшинчика масла, что горел восемь дней в Храме?", correctAnswer: "Ханука", distractors: ["Пурим", "Песах", "Шавуот"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какая смелая царица из истории Пурима помогла спасти еврейский народ?", correctAnswer: "Царица Эстер", distractors: ["Пророчица Мирьям", "Судья Двора", "Рут Моавитянка"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какой знаменитый царь народа Израиля построил Первый Храм в Иерусалиме?", correctAnswer: "Царь Шломо", distractors: ["Моше Рабейну", "Авраам Авину", "Яаков Авину"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какой научный прибор помогает увидеть совсем крошечное — клетки и бактерии?", correctAnswer: "Микроскоп", distractors: ["Телескоп", "Компас", "Песочные часы"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой мореплаватель возглавил первое плавание вокруг света на корабле?", correctAnswer: "Фернан Магеллан", distractors: ["Томас Эдисон", "Исаак Ньютон", "Генри Форд"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какая древняя находка с надписями помогла учёным разгадать египетские иероглифы?", correctAnswer: "Розеттский камень", distractors: ["Скрижали Завета", "Философский камень", "Таблица умножения"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какой знаменитый учёный смотрел в телескоп, изучая звёзды и Луну?", correctAnswer: "Галилео Галилей", distractors: ["Христофор Колумб", "Томас Эдисон", "Генри Форд"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какой быстрый аппарат с мощным двигателем улетает с Земли в космос?", correctAnswer: "Ракета", distractors: ["Корабль", "Велосипед", "Карета"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой древний народ строил длинные дороги и водопроводы, чтобы вода текла в его города?", correctAnswer: "Римляне", distractors: ["Викинги", "Японцы", "Эскимосы"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какое изобретение братьев Люмьер позволило показывать движущиеся картины на большом экране?", correctAnswer: "Кинематограф", distractors: ["Радио", "Телефон", "Холодильник"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой праздник отмечает дарование Торы на горе Синай, и в него украшают дом зеленью и цветами?", correctAnswer: "Шавуот", distractors: ["Суккот", "Пурим", "Ханука"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какой знаменитый английский мореплаватель исследовал много земель в Тихом океане?", correctAnswer: "Джеймс Кук", distractors: ["Томас Эдисон", "Генри Форд", "Альберт Эйнштейн"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какой древний прибор показывал время по тени от палочки?", correctAnswer: "Солнечные часы", distractors: ["Наручные часы", "Компьютер", "Фотоаппарат"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "На каком древнем языке говорили в Древнем Риме, и от него произошли многие языки Европы?", correctAnswer: "Латынь", distractors: ["Китайский", "Японский", "Арабский"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какое изобретение позволило посылать сообщения далеко-далеко с помощью кода из точек и тире?", correctAnswer: "Телеграф", distractors: ["Холодильник", "Фотоаппарат", "Плуг"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой знаменитый человек вернул иврит в живую, разговорную речь?", correctAnswer: "Элиэзер Бен-Йехуда", distractors: ["Теодор Герцль", "Альберт Эйнштейн", "Томас Эдисон"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какой прочный материал люди научились плавить и ковать для орудий, и он дал имя целой эпохе?", correctAnswer: "Железо", distractors: ["Пластик", "Стекло", "Резина"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какого знаменитого мечтателя называют провидцем еврейского государства?", correctAnswer: "Теодор Герцль", distractors: ["Элиэзер Бен-Йехуда", "Альберт Эйнштейн", "Христофор Колумб"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какая звезда помогала морякам находить дорогу ночью, потому что указывает на север?", correctAnswer: "Полярная звезда", distractors: ["Полная луна", "Солнце", "Облако"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какая древняя страна делилась на города-государства, такие как Афины и Спарта?", correctAnswer: "Греция", distractors: ["Египет", "Китай", "Англия"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какое святое древнее место в Иерусалиме осталось от Храма, и люди приходят туда молиться?", correctAnswer: "Стена Плача", distractors: ["Эйфелева башня", "Колизей", "Великая Китайская стена"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какой старинный транспорт ездил по земле, когда лошади тянули повозку на колёсах?", correctAnswer: "Карета", distractors: ["Подводная лодка", "Самолёт", "Космический корабль"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое изобретение Иоганна Гутенберга позволило быстро печатать книги?", correctAnswer: "Печатный станок", distractors: ["Фотоаппарат", "Телефон", "Автомобиль"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "В какой израильский праздник ночью жгут костры?", correctAnswer: "Лаг ба-Омер", distractors: ["Пурим", "Песах", "Шавуот"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "Какой древний народ в Южной Америке строил города высоко в горах?", correctAnswer: "Инки", distractors: ["Римляне", "Викинги", "Японцы"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какой прозрачный материал изобрели много лет назад, и из него делают окна и стаканы?", correctAnswer: "Стекло", distractors: ["Железо", "Дерево", "Камень"], tier: .hard, grades: 4...6),
    ]
}
