import Foundation

/// 💰 Деньги — русский. Переведено с ивритского банка (246 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let money: [BankQuestion] = [
        BankQuestion(prompt: "💰\nСколько агорот в одном шекеле?", correctAnswer: "100", distractors: ["10", "50", "1000"], grades: 2...3),
        BankQuestion(prompt: "🪙🪙🪙🪙🪙\n5 монет по 1 ₪ — сколько это вместе?", correctAnswer: "5 ₪", distractors: ["3 ₪", "4 ₪", "6 ₪"], grades: 1...3),
        BankQuestion(prompt: "🍦\nУ тебя 10 ₪, а мороженое стоит 6 ₪. Сколько сдачи ты получишь?", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "5 ₪"], grades: 3...4),
        BankQuestion(prompt: "💵\nКакая банкнота стоит больше всех?", correctAnswer: "200 ₪", distractors: ["20 ₪", "50 ₪", "100 ₪"], grades: 1...2),
        BankQuestion(prompt: "🐷\nЧто делают с копилкой?", correctAnswer: "Кладут в неё деньги на будущее", distractors: ["Хранят в ней конфеты", "Наливают в неё воду", "Ставят её на полку для красоты"], grades: 1...3),
        BankQuestion(prompt: "🛒\nХочешь купить дорогую игрушку. Что лучше сделать?", correctAnswer: "Копить понемногу каждую неделю", distractors: ["Потратить всё сразу", "Просить ещё и ещё", "Совсем не думать об этом"], grades: 2...5),
        BankQuestion(prompt: "🥤\nЧто из этого — важная «необходимость»?", correctAnswer: "Еда и вода", distractors: ["Новая игрушка", "Наклейки", "Игра в телефоне"], grades: 2...5),
        BankQuestion(prompt: "🪙🪙\n2 монеты по 5 ₪ — сколько это?", correctAnswer: "10 ₪", distractors: ["7 ₪", "12 ₪", "15 ₪"], grades: 2...3),
        BankQuestion(prompt: "🛍️\nТы купил на 12 ₪ и заплатил банкнотой 20 ₪. Сколько сдачи?", correctAnswer: "8 ₪", distractors: ["6 ₪", "7 ₪", "10 ₪"], grades: 3...4),
        BankQuestion(prompt: "💳\nЧто такое кредитная карта?", correctAnswer: "Способ платить без наличных", distractors: ["Игрушка", "Карточка для игры", "Фотография"], grades: 3...5),
        BankQuestion(prompt: "🏷️\nКакой товар дешевле: один стоит 8 ₪, другой — 12 ₪?", correctAnswer: "Тот, что за 8 ₪", distractors: ["Тот, что за 12 ₪", "Оба стоят одинаково", "Нельзя узнать"], grades: 2...3),
        BankQuestion(prompt: "💝\nДруг забыл взять деньги на еду. Как хорошо поступить?", correctAnswer: "Поделиться с ним своей едой", distractors: ["Не обращать внимания", "Молча есть одному", "Съесть всё побыстрее"], grades: 0...2),
        BankQuestion(prompt: "🪙\nСколько агорот стоит монета в полшекеля?", correctAnswer: "50", distractors: ["5", "10", "100"], grades: 3...4),
        BankQuestion(prompt: "📋\nЧто такое «бюджет»?", correctAnswer: "План, сколько денег можно потратить", distractors: ["Вид конфет", "Настольная игра", "Вид монеты"], grades: 4...6),
        BankQuestion(prompt: "💰\nУ тебя 3 ₪, и ты получил ещё 5 ₪. Сколько у тебя теперь?", correctAnswer: "8 ₪", distractors: ["2 ₪", "7 ₪", "9 ₪"], grades: 1...3),
        BankQuestion(prompt: "🤔\nКогда стоит что-то покупать?", correctAnswer: "Когда это правда нужно", distractors: ["Всегда и сразу", "Когда купил друг", "Никогда"], grades: 2...5),
        BankQuestion(prompt: "🏦\nГде взрослые надёжно хранят деньги?", correctAnswer: "В банке", distractors: ["На улице", "В мусорном ведре", "На дереве"], grades: 1...3),
        BankQuestion(prompt: "🎁\nТы накопил 50 ₪, а подарок стоит 80 ₪. Сколько ещё нужно?", correctAnswer: "30 ₪", distractors: ["20 ₪", "40 ₪", "60 ₪"], grades: 3...4),
        BankQuestion(prompt: "♻️\nКак можно экономить деньги дома?", correctAnswer: "Выключать свет, который не нужен", distractors: ["Оставлять всё включённым", "Выбрасывать еду", "Покупать всё по два раза"], grades: 2...5),
        BankQuestion(prompt: "🪙🪙🪙\n3 монеты по 2 ₪ — сколько это?", correctAnswer: "6 ₪", distractors: ["5 ₪", "8 ₪", "9 ₪"], grades: 2...3),
        BankQuestion(prompt: "Игрушка стоит 45 шекелей. Заплатили банкнотой в 50. Сколько сдачи получите?", correctAnswer: "Сдача — 5 шекелей", distractors: ["Сдача — 10 шекелей", "Сдача — 15 шекелей", "Сдача — 45 шекелей"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Мороженое стоит 12 шекелей. Сколько будут стоить 3 мороженых?", correctAnswer: "36 шекелей", distractors: ["24 шекеля", "30 шекелей", "42 шекеля"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "У вас 100 шекелей. Вы купили книгу за 35 и игру за 40. Сколько осталось?", correctAnswer: "25 шекелей", distractors: ["35 шекелей", "15 шекелей", "30 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Что такое «накопления»?", correctAnswer: "Деньги, которые хранят на будущее, а не тратят", distractors: ["Деньги, которые тратят сразу", "Подарок от друзей", "Вид монеты"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "Если копить 10 шекелей каждую неделю, сколько будет через месяц (4 недели)?", correctAnswer: "40 шекелей", distractors: ["10 шекелей", "30 шекелей", "50 шекелей"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Что такое «цена по акции»?", correctAnswer: "Цена дешевле обычной и только на время", distractors: ["Самая дорогая цена в магазине", "Цена, которую платят только летом", "Цена, которую придумал сам покупатель"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Рубашка стоила 60 шекелей, а сейчас продаётся за полцены. Сколько она стоит?", correctAnswer: "30 шекелей", distractors: ["20 шекелей", "40 шекелей", "55 шекелей"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Зачем сравнивать цены перед покупкой?", correctAnswer: "Чтобы найти тот же товар дешевле", distractors: ["Чтобы потратить больше времени", "Потому что так требует закон", "Чтобы купить как можно больше"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Что банк делает с деньгами, которые у него хранят?", correctAnswer: "Хранит их и добавляет проценты", distractors: ["Тратит их", "Выбрасывает их", "Меняет их на конфеты"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Обед: пицца за 28 шекелей и напиток за 7. Сколько вместе?", correctAnswer: "35 шекелей", distractors: ["33 шекеля", "37 шекелей", "38 шекелей"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🪙\nКак называется валюта Государства Израиль?", correctAnswer: "Шекель", distractors: ["Доллар", "Евро", "Лира"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙\nСколько будет шекель плюс ещё один шекель?", correctAnswer: "2 шекеля", distractors: ["1 шекель", "3 шекеля", "10 шекелей"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙\nСколько будет две монеты по 5 шекелей?", correctAnswer: "10 шекелей", distractors: ["5 шекелей", "7 шекелей", "20 шекелей"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🛒\nГде в магазине платят за покупки?", correctAnswer: "На кассе", distractors: ["На входе", "На складе", "На парковке"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏷️\nЧто говорит нам цена товара?", correctAnswer: "Сколько денег нужно за него заплатить", distractors: ["Сколько он весит", "Какого он цвета", "Когда закрывается магазин"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙\nСколько агорот в одном шекеле?", correctAnswer: "100", distractors: ["10", "50", "1000"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧸\nИгрушка стоит 7 шекелей, а у вас 10 шекелей. Можно её купить?", correctAnswer: "Да, и ещё останется сдача", distractors: ["Нет, денег не хватит", "Только если будет скидка", "Нельзя узнать"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙\nСколько будет монета в 2 шекеля и ещё монета в шекель?", correctAnswer: "3 шекеля", distractors: ["2 шекеля", "4 шекеля", "5 шекелей"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "💵\nВы заплатили 20 шекелей за игру, которая стоит 12 шекелей. Сколько сдачи получите?", correctAnswer: "8 шекелей", distractors: ["6 шекелей", "10 шекелей", "12 шекелей"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "💵\nВы заплатили 50 шекелей за книгу, которая стоит 35 шекелей. Сколько сдачи получите?", correctAnswer: "15 шекелей", distractors: ["25 шекелей", "10 шекелей", "20 шекелей"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧃\nОдин сок стоит 6 шекелей, а другой — 9 шекелей. Какой из них дешевле?", correctAnswer: "Тот, что за 6 шекелей", distractors: ["Тот, что за 9 шекелей", "Оба стоят одинаково", "Нельзя узнать"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐷\nЧто значит копить деньги?", correctAnswer: "Откладывать деньги для важной цели", distractors: ["Сразу всё потратить", "Спрятать деньги и забыть где", "Отдать всё в подарок"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍞\nЧто из этого — необходимость, а не желание?", correctAnswer: "Хлеб к обеду", distractors: ["Ещё одна конфета", "Новая игрушка", "Блестящие наклейки"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🎮\nЧто из этого — желание, а не необходимость?", correctAnswer: "Новая компьютерная игра", distractors: ["Вода для питья", "Пальто на зиму", "Лекарство, когда болеешь"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🪙\nВы копите 5 шекелей каждую неделю. Сколько накопите за 4 недели?", correctAnswer: "20 шекелей", distractors: ["9 шекелей", "15 шекелей", "25 шекелей"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🛒\nВы купили тетрадь за 7 шекелей и карандаш за 8 шекелей. Сколько заплатили всего?", correctAnswer: "15 шекелей", distractors: ["14 шекелей", "16 шекелей", "13 шекелей"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐷\nГде дома лучше хранить деньги, которые копишь?", correctAnswer: "В копилке", distractors: ["На полу в гостиной", "В ящике с игрушками", "В кармане старого пальто"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍫\nОдин и тот же батончик стоит 4 шекеля в одном магазине и 5 шекелей в другом. Где выгоднее купить?", correctAnswer: "В магазине, где он за 4 шекеля", distractors: ["В магазине, где он за 5 шекелей", "Разницы между магазинами нет", "В том магазине, который дальше"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🏷️\nРубашка стоит 30 шекелей, и на неё скидка — полцены. Сколько вы заплатите?", correctAnswer: "15 шекелей", distractors: ["10 шекелей", "20 шекелей", "25 шекелей"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏷️\nИгра стоит 40 шекелей, и на неё скидка 25%. Сколько вы заплатите?", correctAnswer: "30 шекелей", distractors: ["25 шекелей", "35 шекелей", "10 шекелей"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏷️\nКнига стоит 50 шекелей, и на неё скидка 10%. Сколько вы заплатите?", correctAnswer: "45 шекелей", distractors: ["40 шекелей", "48 шекелей", "5 шекелей"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏦\nЧто такое банк?", correctAnswer: "Место, где хранят деньги и дают их в долг", distractors: ["Магазин сладостей", "Место, где раздают деньги бесплатно", "Игра в карты"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "📈\nКак называется добавка, которую банк добавляет к деньгам за время хранения?", correctAnswer: "Проценты", distractors: ["Скидка", "Сдача", "Штраф"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🐷\nКарманные деньги — двадцать шекелей в неделю, а тратишь ты пятнадцать. Сколько накопишь за 4 недели?", correctAnswer: "20 шекелей", distractors: ["5 шекелей", "15 шекелей", "60 шекелей"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "📋\nЧто такое бюджет?", correctAnswer: "План, сколько денег тратить и на что", distractors: ["Список игр", "Вид монеты", "Название банка"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🧠\nЧто делает умный покупатель перед большой покупкой?", correctAnswer: "Сравнивает цены в разных магазинах", distractors: ["Покупает в первом же магазине", "Выбирает самый дорогой товар", "Покупает, не глядя на цену"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🎁\nПо акции 1+1 два товара стоят 10 шекелей. Сколько на самом деле стоит один товар?", correctAnswer: "5 шекелей", distractors: ["10 шекелей", "20 шекелей", "2 шекеля"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🎯\nИгра стоит 60 шекелей, а вы копите 10 шекелей в неделю. За сколько недель сможете её купить?", correctAnswer: "6 недель", distractors: ["4 недели", "5 недель", "10 недель"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🪙🪙🪙🪙\nЧетыре монеты по 1 ₪ — сколько это вместе?", correctAnswer: "4 ₪", distractors: ["3 ₪", "5 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "🪙🪙\nМонета 2 ₪ и ещё монета 2 ₪ — сколько это?", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "🍬\nУ тебя 5 ₪, а леденец стоит 2 ₪. Сколько сдачи ты получишь?", correctAnswer: "3 ₪", distractors: ["1 ₪", "2 ₪", "4 ₪"], grades: 3...4),
        BankQuestion(prompt: "🥨\nТы купил бублик за 4 ₪ и заплатил 10 ₪. Сколько сдачи?", correctAnswer: "6 ₪", distractors: ["4 ₪", "5 ₪", "7 ₪"], grades: 3...4),
        BankQuestion(prompt: "🍌\nБанан стоит 3 ₪. Ты заплатил 5 ₪. Сколько сдачи?", correctAnswer: "2 ₪", distractors: ["1 ₪", "3 ₪", "4 ₪"], grades: 3...4),
        BankQuestion(prompt: "💰\nУ тебя 2 ₪, и ты получил ещё 6 ₪. Сколько у тебя теперь?", correctAnswer: "8 ₪", distractors: ["4 ₪", "7 ₪", "9 ₪"], grades: 2...3),
        BankQuestion(prompt: "🪙🪙🪙\nТри монеты по 1 ₪ и ещё одна монета 1 ₪ — сколько это?", correctAnswer: "4 ₪", distractors: ["3 ₪", "5 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "🥕\nМорковка стоит 2 ₪. Сколько будут стоить три морковки?", correctAnswer: "6 ₪", distractors: ["4 ₪", "5 ₪", "8 ₪"], grades: 2...3),
        BankQuestion(prompt: "🪙\nКакая монета стоит больше всех?", correctAnswer: "10 ₪", distractors: ["1 ₪", "2 ₪", "5 ₪"], grades: 1...2),
        BankQuestion(prompt: "💵\nКакая банкнота стоит меньше всех?", correctAnswer: "20 ₪", distractors: ["50 ₪", "100 ₪", "200 ₪"], grades: 1...2),
        BankQuestion(prompt: "🪙\nСколько монет по 1 ₪ нужно, чтобы получилось 5 ₪?", correctAnswer: "5 монет", distractors: ["2 монеты", "3 монеты", "10 монет"], grades: 2...3),
        BankQuestion(prompt: "🧃\nЧто из этого — «желание», а не «необходимость»?", correctAnswer: "Новая игрушка", distractors: ["Вода, чтобы пить", "Здоровая еда", "Тёплая одежда"], grades: 3...4),
        BankQuestion(prompt: "🛏️\nЧто из этого — важная «необходимость»?", correctAnswer: "Место, где спать", distractors: ["Цветной шарик", "Наклейки", "Новая игра"], grades: 3...4),
        BankQuestion(prompt: "🐷\nКак наполняется копилка?", correctAnswer: "В неё каждый раз кладут немного денег", distractors: ["Из неё каждый день достают", "Её оставляют пустой", "Её выбрасывают"], grades: 3...4),
        BankQuestion(prompt: "💡\nЗачем копить деньги?", correctAnswer: "Чтобы потом хватило на что-то большое", distractors: ["Чтобы потратить быстрее", "Чтобы их потерять", "Чтобы их спрятать"], grades: 3...4),
        BankQuestion(prompt: "🛒\nУ тебя 10 ₪, а игрушка стоит 15 ₪. Сколько ещё нужно накопить?", correctAnswer: "Ещё 5 ₪", distractors: ["Ещё 10 ₪", "Ещё 15 ₪", "Ещё 25 ₪"], grades: 3...4),
        BankQuestion(prompt: "🍕\nОдна пицца на четверых друзей. Как будет справедливее всего?", correctAnswer: "Разделить поровну", distractors: ["Каждому кусок разного размера", "Дать только двоим", "Оставить всё на завтра"], grades: 3...4),
        BankQuestion(prompt: "💝\nУ брата нет денег на наклейку, а у тебя их две. Как поступить по-доброму?", correctAnswer: "Дать ему одну наклейку", distractors: ["Оставить обе себе", "Дать как-нибудь завтра", "Купить ещё наклеек"], grades: 3...4),
        BankQuestion(prompt: "🏷️\nОдна и та же игрушка в одном магазине стоит 9 ₪, а в другом — 7 ₪. Где дешевле?", correctAnswer: "Там, где 7 ₪", distractors: ["Там, где 9 ₪", "Цена одинаковая", "Нельзя узнать"], grades: 3...4),
        BankQuestion(prompt: "📋\nЧто стоит сделать перед тем, как покупать много вещей?", correctAnswer: "Написать список и посчитать деньги", distractors: ["Купить всё без раздумий", "Не считать свои деньги", "Купить только самое дорогое"], grades: 4...6),
        BankQuestion(prompt: "💰\nТы накопил 4 ₪ и получил ещё 4 ₪ от бабушки. Сколько у тебя?", correctAnswer: "8 ₪", distractors: ["4 ₪", "6 ₪", "10 ₪"], grades: 2...3),
        BankQuestion(prompt: "🪙\nКакая монета дороже — 2 ₪ или 5 ₪?", correctAnswer: "Монета 5 ₪", distractors: ["Монета 2 ₪", "Обе одинаковые", "Нельзя узнать"], grades: 1...2),
        BankQuestion(prompt: "🛍️\nТы заплатил за покупку 7 ₪ банкнотой 10 ₪. Сколько сдачи?", correctAnswer: "3 ₪", distractors: ["2 ₪", "4 ₪", "5 ₪"], grades: 3...4),
        BankQuestion(prompt: "🍫\nШоколадка стоит 6 ₪, и ты заплатил 6 ₪. Сколько сдачи?", correctAnswer: "0 ₪", distractors: ["1 ₪", "2 ₪", "6 ₪"], grades: 3...4),
        BankQuestion(prompt: "🤝\nВы с другом хотите вместе купить мяч за 10 ₪. Сколько даст каждый, если поровну?", correctAnswer: "5 ₪", distractors: ["2 ₪", "10 ₪", "20 ₪"], grades: 3...4),
        BankQuestion(prompt: "🐖\nВ копилке 5 ₪, и ты положил ещё 3 ₪. Сколько теперь?", correctAnswer: "8 ₪", distractors: ["2 ₪", "7 ₪", "9 ₪"], grades: 2...3),
        BankQuestion(prompt: "🧾\nЧто дают в магазине после того, как заплатишь?", correctAnswer: "Чек", distractors: ["Игрушку в подарок", "Ещё денег", "Ключ от магазина"], grades: 4...6),
        BankQuestion(prompt: "💸\nЧто будет, если сразу потратить все деньги?", correctAnswer: "Не останется денег на другое", distractors: ["Деньги вернутся сами", "Дадут ещё денег", "Ничего не случится"], grades: 3...4),
        BankQuestion(prompt: "🎈\nШарик стоит 2 ₪. Сколько будут стоить два шарика?", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "🪙🪙🪙🪙🪙\nПять монет по 1 ₪ — сколько это вместе?", correctAnswer: "5 ₪", distractors: ["4 ₪", "6 ₪", "10 ₪"], grades: 1...2),
        BankQuestion(prompt: "🪙🪙🪙\nТри монеты по 2 ₪ — сколько это вместе?", correctAnswer: "6 ₪", distractors: ["3 ₪", "5 ₪", "8 ₪"], grades: 2...3),
        BankQuestion(prompt: "🍎\nЯблоко стоит 3 ₪, и ты заплатил 10 ₪. Сколько сдачи?", correctAnswer: "7 ₪", distractors: ["5 ₪", "6 ₪", "8 ₪"], grades: 3...4),
        BankQuestion(prompt: "🥛\nТы выпил молоко за 4 ₪ и заплатил 5 ₪. Сколько сдачи?", correctAnswer: "1 ₪", distractors: ["2 ₪", "3 ₪", "4 ₪"], grades: 3...4),
        BankQuestion(prompt: "🍦\nМороженое стоит 8 ₪, и ты заплатил 10 ₪. Сколько сдачи?", correctAnswer: "2 ₪", distractors: ["1 ₪", "3 ₪", "4 ₪"], grades: 3...4),
        BankQuestion(prompt: "🪙\nСколько монет по 2 ₪ нужно, чтобы получилось 10 ₪?", correctAnswer: "5 монет", distractors: ["2 монеты", "3 монеты", "10 монет"], grades: 2...3),
        BankQuestion(prompt: "💧\nЧто из этого — важная «необходимость» для тела?", correctAnswer: "Вода, чтобы пить", distractors: ["Игровой компьютер", "Большой леденец", "Смешная шапка"], grades: 3...4),
        BankQuestion(prompt: "🎮\nЧто из этого — «желание», а не «необходимость»?", correctAnswer: "Новая компьютерная игра", distractors: ["Обувь, чтобы ходить", "Здоровая еда", "Тёплое место для сна"], grades: 3...4),
        BankQuestion(prompt: "🐷\nЧто лучше сделать с деньгами, которые сейчас не нужны?", correctAnswer: "Положить в копилку", distractors: ["Сразу всё потратить", "Потерять их", "Выбросить в мусор"], grades: 4...6),
        BankQuestion(prompt: "🏷️\nОдна и та же книга стоит 8 ₪ в одном магазине и 6 ₪ в другом. Где дешевле?", correctAnswer: "Там, где 6 ₪", distractors: ["Там, где 8 ₪", "Цена одинаковая", "Нельзя узнать"], grades: 3...4),
        BankQuestion(prompt: "🍪\nПеченье стоит 2 ₪. Сколько будут стоить три печенья?", correctAnswer: "6 ₪", distractors: ["4 ₪", "5 ₪", "8 ₪"], grades: 2...3),
        BankQuestion(prompt: "💰\nТы накопил 3 ₪ и получил ещё 2 ₪. Сколько у тебя теперь?", correctAnswer: "5 ₪", distractors: ["1 ₪", "4 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "🤝\nТри пирожных на троих детей. Сколько получит каждый при честном делении?", correctAnswer: "Одно пирожное", distractors: ["Два пирожных", "Три пирожных", "Ни одного"], grades: 2...3),
        BankQuestion(prompt: "🪙\nКакая монета стоит меньше — 1 ₪ или 5 ₪?", correctAnswer: "Монета 1 ₪", distractors: ["Монета 5 ₪", "Обе одинаковые", "Нельзя узнать"], grades: 1...2),
        BankQuestion(prompt: "📋\nТы хотел купить 3 вещи, но денег хватает только на две. Что лучше?", correctAnswer: "Выбрать две самые нужные вещи", distractors: ["Купить только самую дорогую", "Отказаться от всего и уйти", "Купить только самую дешёвую"], grades: 3...4),
        BankQuestion(prompt: "🍇\nГроздь винограда стоит 5 ₪, и ты заплатил 5 ₪. Сколько сдачи?", correctAnswer: "0 ₪", distractors: ["1 ₪", "2 ₪", "5 ₪"], grades: 3...4),
        BankQuestion(prompt: "🐖\nВ копилке было 6 ₪, и ты достал 2 ₪. Сколько осталось?", correctAnswer: "4 ₪", distractors: ["2 ₪", "6 ₪", "8 ₪"], grades: 2...3),
        BankQuestion(prompt: "🎁\nТы хотел подарок за 12 ₪, но у тебя только 9 ₪. Что лучше сделать?", correctAnswer: "Накопить ещё немного, пока не хватит", distractors: ["Купить всё равно и остаться должным", "Совсем отказаться от подарка", "Попросить подарок ещё дороже"], grades: 4...6),
        BankQuestion(prompt: "🪙🪙\nМонета 5 ₪ и ещё монета 2 ₪ — сколько это вместе?", correctAnswer: "7 ₪", distractors: ["3 ₪", "6 ₪", "10 ₪"], grades: 2...3),
        BankQuestion(prompt: "🧺\nМама дала тебе 10 ₪ только на фрукты. Как правильно поступить?", correctAnswer: "Купить на эти деньги фрукты", distractors: ["Купить на них игрушку", "Купить на них конфеты", "Спрятать деньги"], grades: 3...4),
        BankQuestion(prompt: "🍭\nЛеденец стоит 1 ₪. Сколько будут стоить четыре леденца?", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "5 ₪"], grades: 2...3),
        BankQuestion(prompt: "💝\nУ подруги нет денег на сок, а у тебя их чуть больше. Как хорошо поступить?", correctAnswer: "Поделиться и купить сок вам обеим", distractors: ["Купить сок только себе", "Оставить деньги на завтра", "Купить себе сок побольше"], grades: 3...4),
        BankQuestion(prompt: "🪙\nСколько монет по 1 ₪ равны одной монете 2 ₪?", correctAnswer: "2 монеты", distractors: ["1 монета", "3 монеты", "5 монет"], grades: 1...2),
        BankQuestion(prompt: "🛒\nУ тебя 8 ₪, и ты купил вещь за 3 ₪. Сколько денег осталось?", correctAnswer: "5 ₪", distractors: ["3 ₪", "4 ₪", "6 ₪"], grades: 2...3),
        BankQuestion(prompt: "💡\nЧто значит копить деньги?", correctAnswer: "Оставлять немного денег, а не тратить всё", distractors: ["Быстро потратить всё", "Отдать все свои деньги", "Потерять деньги"], grades: 4...6),
        BankQuestion(prompt: "🎪\nБилет на спектакль стоит 9 ₪, и ты заплатил 10 ₪. Сколько сдачи?", correctAnswer: "1 ₪", distractors: ["2 ₪", "3 ₪", "0 ₪"], grades: 3...4),
        BankQuestion(prompt: "⚖️\nЧто лучше купить сначала, когда денег мало?", correctAnswer: "То, что нам правда нужно", distractors: ["То, что хочется на минутку", "Самое дорогое в магазине", "Вообще ничего и никогда"], grades: 4...6),
        BankQuestion(prompt: "Сколько агорот в одном шекеле?", correctAnswer: "100", distractors: ["10", "50", "1000"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называются деньги, которыми пользуются в Израиле?", correctAnswer: "Шекель", distractors: ["Доллар", "Евро", "Иена"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что стоит больше?", correctAnswer: "10 шекелей", distractors: ["5 шекелей", "2 шекеля", "1 шекель"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что стоит больше?", correctAnswer: "5 шекелей", distractors: ["2 шекеля", "1 шекель", "Полшекеля"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какая монета меньше по стоимости?", correctAnswer: "1 шекель", distractors: ["10 шекелей", "5 шекелей", "2 шекеля"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Как называется коробочка, в которой хранят деньги?", correctAnswer: "Копилка", distractors: ["Холодильник", "Ящик с инструментами", "Кастрюля"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Монета в два шекеля — сколько это шекелей?", correctAnswer: "2", distractors: ["1", "5", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что можно купить за деньги?", correctAnswer: "Хлеб", distractors: ["Солнце", "Воздух", "Дождь"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какие деньги — банкнота, а не монета?", correctAnswer: "20 шекелей", distractors: ["1 шекель", "5 шекелей", "10 шекелей"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какие деньги — монета?", correctAnswer: "5 шекелей", distractors: ["50 шекелей", "100 шекелей", "200 шекелей"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Банкнота в пятьдесят шекелей — сколько это шекелей?", correctAnswer: "50", distractors: ["5", "15", "500"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что стоит больше?", correctAnswer: "100 шекелей", distractors: ["50 шекелей", "20 шекелей", "10 шекелей"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Если одна вещь стоит 2 шекеля, а другая — 5 шекелей, что дешевле?", correctAnswer: "Та, что за 2 шекеля", distractors: ["Та, что за 5 шекелей", "Обе стоят одинаково", "Нельзя узнать"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что значит «копить»?", correctAnswer: "Хранить деньги на будущее", distractors: ["Сразу всё потратить", "Потерять деньги", "Выбросить деньги"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Банкнота в сто шекелей — сколько это шекелей?", correctAnswer: "100", distractors: ["10", "1000", "50"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что нам правда нужно (необходимость)?", correctAnswer: "Еда", distractors: ["Ещё одна игрушка", "Наклейки", "Конфета"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что из этого — только желание, а не обязательное?", correctAnswer: "Новая игрушка", distractors: ["Еда", "Вода", "Одежда"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Где деньги хранят в безопасности надолго?", correctAnswer: "В банке", distractors: ["На улице", "В мусорном ведре", "В холодильнике"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что стоит больше?", correctAnswer: "2 шекеля", distractors: ["1 шекель", "Полшекеля", "10 агорот"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Банкнота в двадцать шекелей — сколько это шекелей?", correctAnswer: "20", distractors: ["2", "200", "12"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что нужно сделать в магазине, чтобы получить товар?", correctAnswer: "Заплатить деньги", distractors: ["Взять и не платить", "Всегда просить в подарок", "Бросить деньги на пол"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какая банкнота в Израиле самая большая по стоимости?", correctAnswer: "200 шекелей", distractors: ["100 шекелей", "50 шекелей", "20 шекелей"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Если у тебя один шекель, сколько это агорот?", correctAnswer: "100", distractors: ["1", "10", "50"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что дешевле?", correctAnswer: "То, что стоит 3 шекеля", distractors: ["То, что стоит 8 шекелей", "То, что стоит 10 шекелей", "То, что стоит 6 шекелей"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какая монета стоит больше всех?", correctAnswer: "10 шекелей", distractors: ["5 шекелей", "2 шекеля", "1 шекель"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что такое цена?", correctAnswer: "Сколько денег стоит вещь", distractors: ["Цвет вещи", "Размер вещи", "Вес вещи"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Ты заплатил 10 шекелей за вещь, которая стоит 9 шекелей. Сколько сдачи получишь?", correctAnswer: "1 шекель", distractors: ["2 шекеля", "5 шекелей", "9 шекелей"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называются деньги, которые возвращают после оплаты?", correctAnswer: "Сдача", distractors: ["Штраф", "Подарок", "Долг"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что важнее купить сначала?", correctAnswer: "Еду", distractors: ["Наклейки", "Шарик", "Игрушку"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Сколько монет по 1 шекелю нужно, чтобы получилось 2 шекеля?", correctAnswer: "2 монеты", distractors: ["1 монета", "3 монеты", "5 монет"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что стоит больше?", correctAnswer: "Банкнота 20 шекелей", distractors: ["Монета 10 шекелей", "Монета 5 шекелей", "Монета 2 шекеля"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Какие деньги сделаны из бумаги?", correctAnswer: "Банкнота 50 шекелей", distractors: ["Монета 1 шекель", "Монета 2 шекеля", "Монета 10 шекелей"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Ты купил конфету за один шекель, а было у тебя два шекеля. Сколько осталось?", correctAnswer: "1 шекель", distractors: ["2 шекеля", "3 шекеля", "0 шекелей"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что лучше сделать с деньгами, которые подарили?", correctAnswer: "Отложить часть в копилку", distractors: ["Потерять их", "Выбросить их", "Сразу потратить всё до конца"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что мы делаем в копилке?", correctAnswer: "Собираем деньги", distractors: ["Готовим еду", "Прячем обувь", "Храним игрушки"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какая монета меньше по стоимости?", correctAnswer: "Полшекеля", distractors: ["1 шекель", "2 шекеля", "5 шекелей"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Монета в пять шекелей — сколько это шекелей?", correctAnswer: "5", distractors: ["1", "2", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что делать, если сейчас не хватает денег на игрушку?", correctAnswer: "Копить, пока не хватит", distractors: ["Взять её, не заплатив", "Сердиться и плакать", "Отказаться от еды"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что нам обязательно нужно (необходимость)?", correctAnswer: "Вода для питья", distractors: ["Новая игра", "Видео в телефоне", "Наклейки"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Как называется место, где покупают товары?", correctAnswer: "Магазин", distractors: ["Зоопарк", "Школа", "Детская площадка"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Сколько агорот в половине шекеля?", correctAnswer: "50", distractors: ["10", "100", "5"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что стоит сделать перед покупкой?", correctAnswer: "Посмотреть, сколько это стоит", distractors: ["Купить, не глядя", "Не знать цену", "Заплатить дважды"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "У тебя банкнота 100 шекелей. Это большая сумма или маленькая?", correctAnswer: "Много денег", distractors: ["Совсем мало", "Вообще ничего", "Меньше шекеля"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Что стоит больше?", correctAnswer: "1 шекель", distractors: ["50 агорот", "10 агорот", "20 агорот"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "У каких денег самая большая ценность?", correctAnswer: "Банкнота 50 шекелей", distractors: ["Банкнота 20 шекелей", "Монета 10 шекелей", "Монета 5 шекелей"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Ты заплатил 5 шекелей за вещь, которая стоит 4 шекеля. Сколько сдачи?", correctAnswer: "1 шекель", distractors: ["2 шекеля", "4 шекеля", "5 шекелей"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что значит «дорого»?", correctAnswer: "Стоит много денег", distractors: ["Стоит мало денег", "Ничего не стоит", "Очень лёгкое"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Что значит «дёшево»?", correctAnswer: "Стоит мало денег", distractors: ["Стоит много денег", "Сломано", "Очень большое"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какая монета стоит меньше всех?", correctAnswer: "10 агорот", distractors: ["1 шекель", "2 шекеля", "5 шекелей"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "Сколько монет по 1 шекелю нужно, чтобы получилось 5 шекелей?", correctAnswer: "5 монет", distractors: ["2 монеты", "3 монеты", "10 монет"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Ты заплатил 10 шекелей за вещь, которая стоит 7 шекелей — сколько сдачи получишь?", correctAnswer: "3 шекеля", distractors: ["2 шекеля", "4 шекеля", "7 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят монета 5 шекелей и монета 2 шекеля?", correctAnswer: "7 шекелей", distractors: ["3 шекеля", "10 шекелей", "52 шекеля"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Сколько монет по 2 шекеля нужно, чтобы получилось 10 шекелей?", correctAnswer: "5 монет", distractors: ["2 монеты", "4 монеты", "10 монет"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Сколько монет по 5 шекелей вместе дают 10 шекелей?", correctAnswer: "2 монеты", distractors: ["1 монета", "3 монеты", "5 монет"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Ты заплатил 20 шекелей за вещь, которая стоит 15 шекелей — сколько сдачи?", correctAnswer: "Сдача — 5 шекелей", distractors: ["Сдача — 3 шекеля", "Сдача — 10 шекелей", "Сдача — 15 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "У тебя 8 шекелей, а ты хочешь купить вещь за 10 шекелей. Сколько не хватает?", correctAnswer: "2 шекеля", distractors: ["1 шекель", "3 шекеля", "8 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят две монеты по 10 шекелей?", correctAnswer: "20 шекелей", distractors: ["10 шекелей", "15 шекелей", "100 шекелей"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Сколько монет по 1 шекелю вместе равны монете 10 шекелей?", correctAnswer: "10 монет", distractors: ["5 монет", "2 монеты", "20 монет"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Ты купил две вещи: одну за 3 шекеля и одну за 4 шекеля. Сколько заплатил всего?", correctAnswer: "7 шекелей", distractors: ["1 шекель", "6 шекелей", "12 шекелей"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что делать, если хочешь купить дорогую вещь в будущем?", correctAnswer: "Копить понемногу каждый раз", distractors: ["Потратить всё сразу", "Совсем не копить", "Покупать другие вещи"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что из этого — «необходимость», а не просто «желание»?", correctAnswer: "Лекарство, когда болеешь", distractors: ["Новая компьютерная игра", "Ещё одна раскраска", "Ещё одна шапка другого цвета"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят монета 10 шекелей и монета 5 шекелей?", correctAnswer: "15 шекелей", distractors: ["5 шекелей", "20 шекелей", "50 шекелей"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Вещь стоит 12 шекелей, а ты заплатил банкнотой в 20. Сколько сдачи?", correctAnswer: "8 шекелей", distractors: ["2 шекеля", "12 шекелей", "20 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое сочетание монет даёт 7 шекелей?", correctAnswer: "5 шекелей и 2 шекеля", distractors: ["5 шекелей и 5 шекелей", "10 шекелей и 2 шекеля", "2 шекеля и 2 шекеля"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "У тебя 6 шекелей, и ты получил ещё 4 шекеля. Сколько у тебя теперь?", correctAnswer: "10 шекелей", distractors: ["2 шекеля", "8 шекелей", "14 шекелей"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что дешевле: вещь за 15 шекелей или вещь за 12 шекелей?", correctAnswer: "Та, что за 12 шекелей", distractors: ["Та, что за 15 шекелей", "Обе стоят одинаково", "Нельзя узнать"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Сколько монет по 2 шекеля вместе дают 6 шекелей?", correctAnswer: "3 монеты", distractors: ["2 монеты", "4 монеты", "6 монет"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Ты заплатил 50 шекелей за вещь, которая стоит 45 шекелей. Сколько тебе вернут?", correctAnswer: "5 шекелей сдачи", distractors: ["3 шекеля сдачи", "10 шекелей сдачи", "45 шекелей сдачи"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят купюра в 20 шекелей и монета в 10 шекелей?", correctAnswer: "30 шекелей", distractors: ["20 шекелей", "25 шекелей", "210 шекелей"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Если ты копишь по 2 шекеля каждый день, сколько накопишь за 3 дня?", correctAnswer: "6 шекелей", distractors: ["2 шекеля", "5 шекелей", "23 шекеля"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой совет самый лучший, когда получаешь карманные деньги?", correctAnswer: "Немного потратить и немного отложить", distractors: ["Сразу потратить всё", "Никогда ими не пользоваться", "Потерять их"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят купюра в 20 шекелей и монета в 5 шекелей?", correctAnswer: "25 шекелей", distractors: ["15 шекелей", "20 шекелей", "30 шекелей"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "У тебя 10 шекелей. Ты купил что-то за 6 шекелей. Сколько осталось?", correctAnswer: "4 шекеля", distractors: ["3 шекеля", "6 шекелей", "16 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что стоит сравнить, прежде чем покупать один и тот же товар в двух магазинах?", correctAnswer: "Цену", distractors: ["Цвет магазина", "Время суток", "Погоду"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Сколько монет по полшекеля нужно, чтобы получился 1 шекель?", correctAnswer: "2 монеты", distractors: ["1 монета", "5 монет", "10 монет"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Ты купил три вещи по 2 шекеля каждая. Сколько ты заплатил?", correctAnswer: "6 шекелей", distractors: ["2 шекеля", "5 шекелей", "8 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что стоит дороже: две вещи, каждая по 5 шекелей, или одна вещь за 8 шекелей?", correctAnswer: "Две вещи по 5 шекелей", distractors: ["Вещь за 8 шекелей", "Стоят одинаково", "Узнать невозможно"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Ты заплатил 100 шекелей за вещь, которая стоит 90 шекелей. Сколько сдачи?", correctAnswer: "10 шекелей", distractors: ["5 шекелей", "20 шекелей", "90 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое сочетание монет вместе даёт 12 шекелей?", correctAnswer: "10 шекелей и 2 шекеля", distractors: ["5 шекелей и 5 шекелей", "10 шекелей и 10 шекелей", "2 шекеля и 2 шекеля"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Сколько купюр по 20 шекелей вместе дают 100 шекелей?", correctAnswer: "5 купюр", distractors: ["2 купюры", "4 купюры", "10 купюр"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "У тебя было 14 шекелей, и ты потратил 4 шекеля. Сколько осталось?", correctAnswer: "10 шекелей", distractors: ["8 шекелей", "12 шекелей", "18 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что такое «бюджет»?", correctAnswer: "План, который говорит, сколько денег можно потратить", distractors: ["Вид монеты", "Большой магазин", "Игрушка"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Если твой бюджет — 10 шекелей, сколько ты можешь потратить?", correctAnswer: "Не больше 10 шекелей", distractors: ["20 шекелей", "50 шекелей", "100 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят три монеты по 2 шекеля?", correctAnswer: "6 шекелей", distractors: ["2 шекеля", "5 шекелей", "8 шекелей"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что лучше делать тому, кто хочет накопить?", correctAnswer: "Покупать только то, что действительно нужно", distractors: ["Покупать всё, что видишь", "Тратить на всё подряд", "Совсем не хранить деньги"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Сколько сдачи ты получишь с 5 шекелей, если купил что-то за 2 шекеля?", correctAnswer: "3 шекеля", distractors: ["1 шекель", "2 шекеля", "5 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят монета в 2 шекеля и монета в 1 шекель?", correctAnswer: "3 шекеля", distractors: ["1 шекель", "2 шекеля", "21 шекель"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Ты накопил 5 шекелей на первой неделе и 5 шекелей на второй. Сколько всего ты накопил?", correctAnswer: "10 шекелей", distractors: ["5 шекелей", "15 шекелей", "55 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Вещь стоит 18 шекелей. Ты заплатил купюрой в 20 шекелей. Сколько сдачи?", correctAnswer: "2 шекеля", distractors: ["1 шекель", "3 шекеля", "18 шекелей"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое сочетание вместе даёт 15 шекелей?", correctAnswer: "10 шекелей и 5 шекелей", distractors: ["10 шекелей и 10 шекелей", "5 шекелей и 5 шекелей", "2 шекеля и 5 шекелей"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Сколько вместе стоят две купюры по 50 шекелей?", correctAnswer: "100 шекелей", distractors: ["50 шекелей", "150 шекелей", "500 шекелей"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "У тебя 20 шекелей, и ты купил книгу за 13 шекелей. Сколько осталось?", correctAnswer: "7 шекелей", distractors: ["3 шекеля", "13 шекелей", "33 шекеля"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что стоит сделать перед тем, как купить дорогую игрушку?", correctAnswer: "Спросить себя, правда ли она нужна", distractors: ["Купить не думая", "Купить сразу две", "Забыть про цену"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Сколько монет по 1 шекелю вместе равны монете в 5 шекелей?", correctAnswer: "5 монет", distractors: ["2 монеты", "3 монеты", "10 монет"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Сколько агорот нужно добавить к 50 агоротам, чтобы получился целый шекель?", correctAnswer: "Ещё 50 агорот", distractors: ["Ещё 10 агорот", "Ещё 100 агорот", "Ещё 5 агорот"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Вещь стоит 23 шекеля, и ты заплатил купюрой в 50 шекелей. Сколько сдачи?", correctAnswer: "27 шекелей", distractors: ["17 шекелей", "23 шекеля", "37 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят купюра в 50 шекелей, монета в 10 шекелей и монета в 5 шекелей?", correctAnswer: "65 шекелей", distractors: ["55 шекелей", "60 шекелей", "70 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Ты копишь по 5 шекелей каждую неделю. Сколько накопишь за 4 недели?", correctAnswer: "20 шекелей", distractors: ["10 шекелей", "15 шекелей", "25 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Ты купил две вещи: одну за 12 шекелей и одну за 13 шекелей. Сколько ты заплатил?", correctAnswer: "25 шекелей", distractors: ["15 шекелей", "23 шекеля", "35 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Вещь стоит 35 шекелей, и ты заплатил купюрой в 50 шекелей. Сколько сдачи?", correctAnswer: "15 шекелей", distractors: ["5 шекелей", "10 шекелей", "25 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "У тебя 30 шекелей, а игрушка стоит 45 шекелей. Сколько тебе не хватает?", correctAnswer: "15 шекелей", distractors: ["10 шекелей", "20 шекелей", "45 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Сколько купюр по 50 шекелей вместе дают 200 шекелей?", correctAnswer: "4 купюры", distractors: ["2 купюры", "3 купюры", "5 купюр"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Ты купил 4 тетради по 5 шекелей каждая. Сколько ты заплатил?", correctAnswer: "20 шекелей", distractors: ["9 шекелей", "15 шекелей", "25 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Вещь стоит 64 шекеля, и ты заплатил купюрой в 100 шекелей. Сколько сдачи?", correctAnswer: "36 шекелей", distractors: ["26 шекелей", "46 шекелей", "64 шекеля"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Ты хочешь купить что-то за 60 шекелей. У тебя есть 25 шекелей. Сколько ещё нужно накопить?", correctAnswer: "35 шекелей", distractors: ["25 шекелей", "30 шекелей", "45 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят две купюры по 20 шекелей и монета в 10 шекелей?", correctAnswer: "50 шекелей", distractors: ["40 шекелей", "45 шекелей", "60 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Что лучше для того, кто копит на будущее?", correctAnswer: "Каждый раз откладывать часть денег", distractors: ["Потратить всё за один день", "Никогда не копить", "Покупать только ненужные вещи"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "У тебя было 40 шекелей. Ты потратил 18 шекелей. Сколько осталось?", correctAnswer: "22 шекеля", distractors: ["12 шекелей", "28 шекелей", "32 шекеля"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Сколько агорот в двух шекелях?", correctAnswer: "200 агорот", distractors: ["20 агорот", "100 агорот", "2 агоры"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какое сочетание купюр вместе даёт 70 шекелей?", correctAnswer: "50 шекелей и 20 шекелей", distractors: ["50 шекелей и 10 шекелей", "20 шекелей и 20 шекелей", "100 шекелей и 20 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Ты купил 3 бутылки воды по 4 шекеля каждая. Сколько ты заплатил?", correctAnswer: "12 шекелей", distractors: ["7 шекелей", "9 шекелей", "16 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Ты копишь по 10 шекелей в месяц. Сколько накопишь за 3 месяца?", correctAnswer: "30 шекелей", distractors: ["13 шекелей", "20 шекелей", "300 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Вещь стоит 48 шекелей. Ты заплатил купюрой в 50 шекелей. Сколько сдачи?", correctAnswer: "2 шекеля", distractors: ["1 шекель", "5 шекелей", "48 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят купюра в 100 шекелей и купюра в 50 шекелей?", correctAnswer: "150 шекелей", distractors: ["105 шекелей", "140 шекелей", "200 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "У тебя 100 шекелей. Ты купил обувь за 75 шекелей. Сколько осталось?", correctAnswer: "25 шекелей", distractors: ["15 шекелей", "20 шекелей", "35 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Как умнее всего разделить карманные деньги — 10 шекелей?", correctAnswer: "Часть потратить, часть отложить", distractors: ["Всё сразу на сладости", "Никогда их не трогать", "Потерять их"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Ты купил 5 наклеек по 2 шекеля каждая. Сколько ты заплатил?", correctAnswer: "10 шекелей", distractors: ["7 шекелей", "12 шекелей", "15 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Вещь стоит 88 шекелей, и ты заплатил купюрой в 100 шекелей. Сколько сдачи?", correctAnswer: "12 шекелей", distractors: ["8 шекелей", "18 шекелей", "22 шекеля"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Ты хочешь велосипед за 150 шекелей. Ты уже накопил 100 шекелей. Сколько нужно добавить?", correctAnswer: "Ещё 50 шекелей", distractors: ["Ещё 40 шекелей", "Ещё 60 шекелей", "Ещё 100 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят три монеты по 10 шекелей?", correctAnswer: "30 шекелей", distractors: ["13 шекелей", "20 шекелей", "40 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "У тебя 50 шекелей. Ты купил подарок за 32 шекеля. Сколько осталось?", correctAnswer: "18 шекелей", distractors: ["12 шекелей", "22 шекеля", "28 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Что лучше сделать, если хочется что-то купить, но денег не хватает?", correctAnswer: "Подождать и накопить ещё", distractors: ["Взять из магазина, не заплатив", "Рассердиться на продавца", "Забыть, как копят деньги"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое сочетание купюр вместе даёт 120 шекелей?", correctAnswer: "100 шекелей и 20 шекелей", distractors: ["100 шекелей и 10 шекелей", "50 шекелей и 50 шекелей", "200 шекелей и 20 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Вещь стоит 19 шекелей. Ты купил две такие. Сколько ты заплатил?", correctAnswer: "38 шекелей", distractors: ["21 шекель", "29 шекелей", "40 шекелей"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Ты копишь по 3 шекеля каждый день целую неделю (7 дней). Сколько ты накопил?", correctAnswer: "21 шекель", distractors: ["10 шекелей", "18 шекелей", "24 шекеля"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Сколько вместе стоят купюра в 200 шекелей и купюра в 50 шекелей?", correctAnswer: "250 шекелей", distractors: ["205 шекелей", "240 шекелей", "300 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "У тебя было 25 шекелей, и ты получил ещё 15 шекелей. Сколько у тебя теперь?", correctAnswer: "40 шекелей", distractors: ["10 шекелей", "30 шекелей", "45 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Вещь стоит 55 шекелей, и ты заплатил купюрой в 100 шекелей. Сколько сдачи?", correctAnswer: "45 шекелей", distractors: ["35 шекелей", "40 шекелей", "55 шекелей"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какой совет самый лучший перед большой покупкой?", correctAnswer: "Сравнить цены в нескольких магазинах", distractors: ["Купить, не сравнивая", "Заплатить как можно больше", "Не спрашивать цену"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Сколько монет по 10 шекелей вместе равны купюре в 50 шекелей?", correctAnswer: "5 монет", distractors: ["2 монеты", "4 монеты", "10 монет"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Ты хочешь разделить 30 шекелей поровну на траты, накопления и помощь другим. Сколько выйдет на каждую часть?", correctAnswer: "10 шекелей", distractors: ["5 шекелей", "15 шекелей", "30 шекелей"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Вещь стоит 14 шекелей. Ты купил три такие. Сколько ты заплатил?", correctAnswer: "42 шекеля", distractors: ["17 шекелей", "28 шекелей", "44 шекеля"], tier: .hard, grades: 4...6),
    ]
}
