import Foundation

/// 🎵 Музыка — русский. Переведено с ивритского банка (70 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let music: [BankQuestion] = [
        BankQuestion(prompt: "🎸\nСколько струн у обычной гитары?", correctAnswer: "6", distractors: ["4", "5", "8"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🎻\nСколько струн у скрипки?", correctAnswer: "4", distractors: ["3", "5", "6"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🎹\nВ какие два цвета покрашены клавиши пианино?", correctAnswer: "Чёрный и белый", distractors: ["Красный и синий", "Зелёный и жёлтый", "Оранжевый и фиолетовый"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥁\nКак играют на барабанах?", correctAnswer: "Ударяют по ним", distractors: ["Дуют в них", "Перебирают на них струны", "Крутят их"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎸\nКак играют на гитаре?", correctAnswer: "Перебирают струны", distractors: ["Дуют в неё", "Бьют по ней палочками", "Нажимают на клавиши"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎻\nЧем водят по струнам скрипки, чтобы играть?", correctAnswer: "Смычком", distractors: ["Молотком", "Барабанной палочкой", "Ложкой"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎹\nНа каком инструменте нажимают на клавиши?", correctAnswer: "Пианино", distractors: ["Барабан", "Скрипка", "Труба"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪈\nВ какой инструмент дуют?", correctAnswer: "Флейта", distractors: ["Барабан", "Гитара", "Пианино"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥁\nКакой инструмент относится к ударным?", correctAnswer: "Барабан", distractors: ["Скрипка", "Флейта", "Гитара"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🎻\nКакой инструмент относится к струнным?", correctAnswer: "Скрипка", distractors: ["Барабан", "Труба", "Тарелки"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪘\nКак играют на дарбуке?", correctAnswer: "Бьют по ней руками", distractors: ["Дуют в неё", "Водят по ней смычком", "Нажимают на клавиши"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪈\nНа каком маленьком духовом инструменте многие дети учатся играть в школе?", correctAnswer: "Блокфлейта", distractors: ["Труба", "Пианино", "Контрабас"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🎤\nЧто помогает певцу звучать громче?", correctAnswer: "Микрофон", distractors: ["Очки", "Шляпа", "Дирижёрская палочка"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎧\nКак называют того, кто играет на музыкальном инструменте?", correctAnswer: "Музыкант", distractors: ["Певец", "Художник", "Парикмахер"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎵\nСколько нот в гамме: до, ре, ми, фа, соль, ля, си?", correctAnswer: "7", distractors: ["5", "8", "10"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🎵\nКакая нота в гамме самая первая?", correctAnswer: "До", distractors: ["Ре", "Соль", "Си"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎵\nКакая нота идёт сразу после «до»?", correctAnswer: "Ре", distractors: ["Ми", "Фа", "Ля"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎼\nКак называются знаки, которыми записывают музыку?", correctAnswer: "Ноты", distractors: ["Буквы", "Цифры", "Точки"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔉\nЧто противоположно громкой музыке?", correctAnswer: "Тихая музыка", distractors: ["Быстрая музыка", "Длинная музыка", "Весёлая музыка"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐇\nЧто противоположно медленной музыке?", correctAnswer: "Быстрая музыка", distractors: ["Громкая музыка", "Тихая музыка", "Грустная музыка"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎵\nЧто противоположно высокому звуку?", correctAnswer: "Низкий звук", distractors: ["Громкий звук", "Быстрый звук", "Долгий звук"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐦\nКакой звук самый высокий?", correctAnswer: "Щебет птицы", distractors: ["Мычание коровы", "Рык льва", "Звук тубы"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "👏\nКогда хлопают в ладоши вместе с музыкой, под что хлопают?", correctAnswer: "Под ритм", distractors: ["Под цвет", "Под высоту", "Под вкус"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "👏\nМы хлопнули 2 раза, а потом ещё 2 раза. Сколько хлопков всего?", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🎤\nКак называется группа людей, которые поют вместе?", correctAnswer: "Хор", distractors: ["Оркестр", "Танцевальная студия", "Футбольная команда"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎼\nКак называется большая группа музыкантов, которые играют вместе?", correctAnswer: "Оркестр", distractors: ["Хор", "Класс", "Семья"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪄\nКто стоит перед оркестром и показывает музыкантам, когда и как играть?", correctAnswer: "Дирижёр", distractors: ["Судья", "Водитель", "Художник"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌙\nКак называется песня, которую поют малышу, чтобы он уснул?", correctAnswer: "Колыбельная", distractors: ["Гимн", "Марш", "Песенка на день рождения"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌳\nО чём поётся в песне «Йонатан а-Катан»?", correctAnswer: "О мальчике, который залез на дерево", distractors: ["О коте, который пил молоко", "О корабле в море", "О мишке, который пошёл спать"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎠\nО чём поётся в песне «Над-нед»?", correctAnswer: "О качелях", distractors: ["О горке", "О велосипеде", "О воздушном шарике"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎂\nКакую песню поют, когда зажигают свечи на праздничном торте?", correctAnswer: "«Йом хуледет самеах»", distractors: ["«Йонатан а-Катан»", "«Над-нед»", "«Атиква»"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🕎\nВ какой праздник поют «Маоз цур»?", correctAnswer: "Ханука", distractors: ["Песах", "Пурим", "Суккот"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎸\nК какой семье инструментов относится гитара?", correctAnswer: "Струнные", distractors: ["Духовые", "Ударные", "Клавишные"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎺\nК какой семье инструментов относится труба?", correctAnswer: "Духовые", distractors: ["Струнные", "Ударные", "Клавишные"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🥁\nК какой семье инструментов относятся барабаны?", correctAnswer: "Ударные", distractors: ["Струнные", "Духовые", "Клавишные"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎷\nК какой семье инструментов относится саксофон?", correctAnswer: "Духовые", distractors: ["Струнные", "Ударные", "Клавишные"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎹\nОрган и синтезатор — к какой семье инструментов они относятся?", correctAnswer: "Клавишные", distractors: ["Струнные", "Духовые", "Ударные"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔔\nТарелки — это два круглых металлических диска. Как на них играют?", correctAnswer: "Ударяют их друг о друга", distractors: ["Дуют в них", "Перебирают на них струны", "Нажимают на клавиши"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎻\nКакой инструмент похож на скрипку, но больше, и играют на нём сидя?", correctAnswer: "Виолончель", distractors: ["Флейта", "Туба", "Арфа"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎻\nКакой из этих инструментов звучит ниже всех?", correctAnswer: "Контрабас", distractors: ["Скрипка", "Блокфлейта", "Флейта-пикколо"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎺\nТуба — очень большой духовой инструмент. Какие звуки она издаёт?", correctAnswer: "Низкие", distractors: ["Очень высокие", "Резкие, как свист", "Тонкие, как колокольчик"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪕\nКакой большой струнный инструмент похож на треугольник, и струны на нём перебирают пальцами?", correctAnswer: "Арфа", distractors: ["Скрипка", "Туба", "Аккордеон"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪗\nКакой инструмент растягивают и сжимают руками, и у него ещё есть клавиши?", correctAnswer: "Аккордеон", distractors: ["Пианино", "Флейта", "Барабан"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎸\nСколько струн обычно у бас-гитары?", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎹\nЧёрные клавиши на пианино собраны в группы по…", correctAnswer: "2 и 3", distractors: ["1 и 4", "4 и 5", "3 и 6"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥁\nКакой инструмент обычно держит ритм в группе?", correctAnswer: "Барабаны", distractors: ["Флейта", "Скрипка", "Микрофон"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎵\nКакая нота идёт сразу после «ми»?", correctAnswer: "Фа", distractors: ["Ре", "Соль", "Си"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎵\nКакая нота идёт прямо перед «соль»?", correctAnswer: "Фа", distractors: ["Ми", "Ля", "До"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎵\nКакая нота идёт сразу после «ля»?", correctAnswer: "Си", distractors: ["Соль", "Фа", "Ре"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎼\nНа скольких линейках нотного стана пишут ноты?", correctAnswer: "5", distractors: ["3", "4", "7"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "⏩\nКак называется скорость музыки?", correctAnswer: "Темп", distractors: ["Мелодия", "Гармония", "Гамма"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎶\nКак называется главный напев песни — тот, что мы запоминаем и мурлычем себе под нос?", correctAnswer: "Мелодия", distractors: ["Темп", "Ритм", "Соло"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nСколько долей в такте, если музыканты считают «раз-два-три-четыре»?", correctAnswer: "4", distractors: ["2", "3", "8"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎶\nКак называется часть песни, которая повторяется несколько раз?", correctAnswer: "Припев", distractors: ["Куплет", "Нота", "Дирижёрская палочка"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✍️\nЧем занимается композитор?", correctAnswer: "Сочиняет новую музыку", distractors: ["Чинит музыкальные инструменты", "Продаёт билеты", "Фотографирует концерты"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎼\nБах, Моцарт и Бетховен были…", correctAnswer: "Композиторами", distractors: ["Художниками", "Футболистами", "Поварами"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "👂\nКакой знаменитый композитор продолжал сочинять прекрасную музыку, даже когда почти перестал слышать?", correctAnswer: "Бетховен", distractors: ["Моцарт", "Бах", "Вивальди"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🇮🇱\nКак называется гимн Государства Израиль?", correctAnswer: "«Атиква»", distractors: ["«Йерушалаим шель захав»", "«Йонатан а-Катан»", "«Хава нагила»"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "💃\nКакой израильский танец танцуют в кругу, взявшись за руки?", correctAnswer: "Хора", distractors: ["Балет", "Танго", "Хип-хоп"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐐\nВ какой праздник поют «Хад гадья»?", correctAnswer: "Песах", distractors: ["Ханука", "Пурим", "Рош ха-Шана"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🎹\nСколько клавиш у обычного пианино?", correctAnswer: "88", distractors: ["50", "100", "120"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🔊\nЧто в музыке означает слово «форте»?", correctAnswer: "Играть громко", distractors: ["Играть тихо", "Играть быстро", "Играть медленно"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "📈\nЧто означает «крещендо»?", correctAnswer: "Музыка становится всё громче", distractors: ["Музыка становится всё тише", "Музыка останавливается", "Музыка повторяется с начала"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "💃\nВ вальсе в каждом такте считают до…", correctAnswer: "3", distractors: ["2", "4", "5"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🎼\nКак называется завиток, который стоит в самом начале нотного стана?", correctAnswer: "Скрипичный ключ", distractors: ["Восклицательный знак", "Гамма", "Доля"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🔁\nЧто такое песня «каноном»?", correctAnswer: "Каждая группа начинает ту же мелодию чуть позже предыдущей", distractors: ["Песня без слов", "Очень длинная песня", "Песня, которую поют шёпотом"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🇦🇹\nВ какой стране родился композитор Моцарт?", correctAnswer: "Австрия", distractors: ["Израиль", "Япония", "Бразилия"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "👶\nМоцарт был вундеркиндом. Примерно в каком возрасте он начал сочинять музыку?", correctAnswer: "5", distractors: ["15", "20", "30"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🍂\nКто сочинил «Времена года»?", correctAnswer: "Вивальди", distractors: ["Моцарт", "Бетховен", "Бах"], tier: .hard, grades: 3...4),
        BankQuestion(prompt: "🇩🇪\nИз какой страны был композитор Бах?", correctAnswer: "Германия", distractors: ["Италия", "Испания", "Россия"], tier: .hard, grades: 3...4),
    ]
}
