import Foundation

/// 🔬 Наука — русский. Переведено с ивритского банка (311 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let science: [BankQuestion] = [
        BankQuestion(prompt: "🕷️\nСколько ног у паука?", correctAnswer: "8", distractors: ["6", "10", "4"], grades: 0...2),
        BankQuestion(prompt: "🌱\nОткуда растения получают энергию?", correctAnswer: "От солнца", distractors: ["Из земли", "Из воздуха", "От луны"], grades: 2...4),
        BankQuestion(prompt: "🌍\nСколько дней в неделе?", correctAnswer: "7", distractors: ["5", "6", "8"], grades: 0...2),
        BankQuestion(prompt: "🌈\nСколько цветов у радуги?", correctAnswer: "7", distractors: ["5", "6", "10"], grades: 0...2),
        BankQuestion(prompt: "👂\nКаким органом мы слышим?", correctAnswer: "Ушами", distractors: ["Глазами", "Носом", "Ртом"], grades: 0...2),
        BankQuestion(prompt: "🐝\nКакое животное делает мёд?", correctAnswer: "Пчела", distractors: ["Муравей", "Муха", "Бабочка"], grades: 0...2),
        BankQuestion(prompt: "❄️\nЧто происходит с водой на морозе?", correctAnswer: "Она замерзает", distractors: ["Она испаряется", "Она исчезает", "Она нагревается"], grades: 2...4),
        BankQuestion(prompt: "🌡️\nЧем измеряют температуру?", correctAnswer: "Термометром", distractors: ["Весами", "Линейкой", "Часами"], grades: 2...4),
        BankQuestion(prompt: "🦷\nСколько зубов у взрослого человека?", correctAnswer: "32", distractors: ["20", "28", "40"], grades: 2...4),
        BankQuestion(prompt: "🦴\nСколько дней в году?", correctAnswer: "365", distractors: ["360", "350", "400"], grades: 2...4),
        BankQuestion(prompt: "🌙\nСколько времени Луна тратит на один оборот вокруг Земли?", correctAnswer: "Примерно месяц", distractors: ["Один день", "Один год", "Одну неделю"], grades: 4...6),
        BankQuestion(prompt: "☀️\nКакая звезда (та, что светит сама) ближе всего к Земле?", correctAnswer: "Солнце", distractors: ["Луна", "Марс", "Юпитер"], grades: 4...6),
        BankQuestion(prompt: "🐠\nГде дышат рыбы?", correctAnswer: "В воде", distractors: ["В воздухе", "В земле", "На дереве"], grades: 0...2),
        BankQuestion(prompt: "🦋\nВ кого превращается гусеница?", correctAnswer: "В бабочку", distractors: ["В пчелу", "В птицу", "В паука"], grades: 0...2),
        BankQuestion(prompt: "🌋\nЧто выходит из вулкана?", correctAnswer: "Лава", distractors: ["Снег", "Лёд", "Молоко"], grades: 2...4),
        BankQuestion(prompt: "💨\nИз чего состоит воздух?", correctAnswer: "Из газов", distractors: ["Из камней", "Из железа", "Из дерева"], grades: 2...4),
        BankQuestion(prompt: "🌊\nЧто создаёт волны в море?", correctAnswer: "Ветер", distractors: ["Рыбы", "Камни", "Деревья"], grades: 2...4),
        BankQuestion(prompt: "🦷\nКак называется твёрдое вещество, которое покрывает зуб снаружи?", correctAnswer: "Эмаль", distractors: ["Сахар", "Известь", "Железо"], grades: 4...6),
        BankQuestion(prompt: "🚀\nКак называют красную планету?", correctAnswer: "Марс", distractors: ["Юпитер", "Сатурн", "Венера"], grades: 4...6),
        BankQuestion(prompt: "🧠\nКакой орган помогает нам думать?", correctAnswer: "Мозг", distractors: ["Сердце", "Желудок", "Лёгкие"], grades: 0...2),
        BankQuestion(prompt: "При какой температуре кипит вода?", correctAnswer: "100 градусов", distractors: ["50 градусов", "80 градусов", "200 градусов"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какая планета самая большая в Солнечной системе?", correctAnswer: "Юпитер", distractors: ["Марс", "Сатурн", "Венера"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Что делает сердце?", correctAnswer: "Гонит кровь по всему телу", distractors: ["Переваривает еду", "Посылает мысли", "Очищает воздух"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Как растения делают себе еду?", correctAnswer: "Фотосинтез — с помощью солнечного света", distractors: ["Высасывают еду из насекомых", "Едят землю", "Покупают в магазине"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Сколько примерно костей у взрослого человека?", correctAnswer: "206", distractors: ["100", "500", "50"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что тянет нас вниз, к Земле?", correctAnswer: "Сила притяжения", distractors: ["Ветер", "Электричество", "Магнит в небе"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Без какого газа из воздуха человек не может жить?", correctAnswer: "Кислород", distractors: ["Углекислый газ", "Водород", "Гелий"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Кто из них млекопитающее?", correctAnswer: "Дельфин", distractors: ["Акула", "Крокодил", "Лягушка"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Сколько времени Земля тратит на один круг вокруг Солнца?", correctAnswer: "Один год", distractors: ["Один день", "Один месяц", "Одну неделю"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "В каком состоянии вещества находится лёд?", correctAnswer: "Твёрдом", distractors: ["Жидком", "Газообразном", "Плазменном"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "Каким органом мы видим?", correctAnswer: "Глазами", distractors: ["Ушами", "Носом", "Руками"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Какое чувство у нас в ушах?", correctAnswer: "Слух", distractors: ["Зрение", "Вкус", "Обоняние"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Что нужно растению, чтобы расти?", correctAnswer: "Вода, свет и воздух", distractors: ["Только темнота", "Только песок", "Сахар и соль"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Как называется детёныш собаки?", correctAnswer: "Щенок", distractors: ["Котёнок", "Цыплёнок", "Телёнок"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Как называется детёныш курицы?", correctAnswer: "Цыплёнок", distractors: ["Телёнок", "Козлёнок", "Щенок"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Где живут пчёлы?", correctAnswer: "В улье", distractors: ["В норе", "В курятнике", "В конюшне"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Что ест корова?", correctAnswer: "Траву", distractors: ["Мясо", "Рыбу", "Насекомых"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "В какое время года в Израиле выпадает больше всего дождя?", correctAnswer: "Зимой", distractors: ["Летом", "Весной", "Осенью"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Когда видно звёзды на небе?", correctAnswer: "Ночью", distractors: ["В полдень", "Утром", "После обеда"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Откуда вылупляется цыплёнок?", correctAnswer: "Из яйца", distractors: ["Из семечка", "Из цветка", "Из листика"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Какая часть растения находится под землёй?", correctAnswer: "Корень", distractors: ["Лист", "Цветок", "Стебель"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Что светит и греет Землю днём?", correctAnswer: "Солнце", distractors: ["Луна", "Звёзды", "Облака"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "Лёд — это вода в состоянии:", correctAnswer: "Твёрдом", distractors: ["Жидком", "Газообразном", "Плазменном"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Молоко — это вещество в состоянии:", correctAnswer: "Жидком", distractors: ["Твёрдом", "Газообразном", "Плазменном"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Когда вода кипит, она превращается:", correctAnswer: "В пар (газ)", distractors: ["В лёд", "В снег", "В песок"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Что происходит с морской водой, когда солнце её нагревает?", correctAnswer: "Она испаряется", distractors: ["Она замерзает", "Она исчезает навсегда", "Она превращается в соль"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Откуда берётся дождь?", correctAnswer: "Из облаков", distractors: ["Из солнца", "Из звёзд", "Из гор"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Какой орган гонит кровь по телу?", correctAnswer: "Сердце", distractors: ["Лёгкие", "Желудок", "Мозг"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Каким органом мы дышим?", correctAnswer: "Лёгкими", distractors: ["Сердцем", "Печенью", "Желудком"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Для чего нужен скелет?", correctAnswer: "Держать тело и защищать органы", distractors: ["Переваривать еду", "Гонять кровь", "Видеть в темноте"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Какой материал прозрачный?", correctAnswer: "Стекло", distractors: ["Дерево", "Железо", "Камень"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Какой материал притягивается магнитом?", correctAnswer: "Железо", distractors: ["Дерево", "Пластик", "Стекло"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Что ест заяц в пищевой цепи?", correctAnswer: "Растения", distractors: ["Насекомых", "Рыбу", "Мясо"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Кто стоит в начале пищевой цепи?", correctAnswer: "Растения", distractors: ["Львы", "Орлы", "Люди"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "Какую энергию Земля получает от Солнца?", correctAnswer: "Энергию света и тепла", distractors: ["Энергию звука", "Энергию ветра", "Энергию из батареек"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Какой материал проводит электричество?", correctAnswer: "Медь", distractors: ["Резина", "Пластик", "Дерево"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Какой материал не проводит электричество?", correctAnswer: "Резина", distractors: ["Железо", "Медь", "Алюминий"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Сколько планет вращается вокруг Солнца?", correctAnswer: "Восемь", distractors: ["Семь", "Девять", "Десять"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Какая планета ближе всего к Солнцу?", correctAnswer: "Меркурий", distractors: ["Венера", "Марс", "Юпитер"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Какую планету называют красной?", correctAnswer: "Марс", distractors: ["Юпитер", "Сатурн", "Венера"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Какой газ нужен нашему телу из воздуха, чтобы жить?", correctAnswer: "Кислород", distractors: ["Углекислый газ", "Водород", "Азот"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Какой газ добавляется в воздух, когда мы выдыхаем?", correctAnswer: "Углекислый газ", distractors: ["Кислород", "Водород", "Гелий"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Для чего нужна кровь?", correctAnswer: "Разносить кислород и питание по всему телу", distractors: ["Переваривать еду", "Создавать свет", "Очищать воздух"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Что такое экосистема?", correctAnswer: "Животные и растения, которые живут вместе в одной среде", distractors: ["Куча камней в пустыне", "Машина, которая делает электричество", "Вид погоды"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Для чего служат ветряные турбины?", correctAnswer: "Для выработки электричества", distractors: ["Чтобы греть солнце", "Чтобы создавать дождь", "Чтобы замораживать воду"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Почему луна светит ночью?", correctAnswer: "Она отражает солнечный свет", distractors: ["Она горит, как солнце", "Она сама создаёт свет", "Её освещают звёзды"], tier: .hard, grades: 5...5),
        BankQuestion(prompt: "Что растение производит во время фотосинтеза?", correctAnswer: "Сахар и кислород", distractors: ["Соль и воду", "Только углекислый газ", "Новую землю"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Что нужно растению для фотосинтеза?", correctAnswer: "Свет, вода и углекислый газ", distractors: ["Полная темнота", "Только кислород", "Соль и сахар"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "В какой части растения в основном происходит фотосинтез?", correctAnswer: "В листьях", distractors: ["В корнях", "В цветках", "В семенах"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "В чём помогает рычаг?", correctAnswer: "Легко поднять тяжёлый груз", distractors: ["Греть воду", "Видеть далеко", "Лучше слышать"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Для чего нужен подъёмный блок?", correctAnswer: "Поднимать грузы с помощью верёвки", distractors: ["Измерять температуру", "Создавать свет", "Охлаждать еду"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Что распространяется быстрее всего?", correctAnswer: "Свет", distractors: ["Звук", "Ветер", "Запах"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Почему молнию видно раньше, чем слышно гром?", correctAnswer: "Потому что свет быстрее звука", distractors: ["Потому что гром появляется позже", "Потому что звук быстрее света", "Потому что молния ближе"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Через что звук проходит быстрее всего?", correctAnswer: "Через твёрдые тела", distractors: ["Через воздух", "Через воду", "Через пустоту в космосе"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Почему важно сдавать вещи на переработку?", correctAnswer: "Чтобы было меньше мусора и загрязнения", distractors: ["Чтобы мусора стало больше", "Чтобы пачкать море", "Нет причины, это просто привычка"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Какого цвета бак для переработки бумаги в Израиле?", correctAnswer: "Синий", distractors: ["Зелёный", "Оранжевый", "Красный"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Каким прибором пользуются, чтобы увидеть бактерии?", correctAnswer: "Микроскоп", distractors: ["Бинокль", "Телескоп", "Лупа"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Из-за чего тесто для хлеба поднимается?", correctAnswer: "Из-за дрожжей", distractors: ["Из-за соли", "Из-за холодной воды", "Из-за лишней муки"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🌱\nЧто нужно растениям, чтобы расти?", correctAnswer: "Солнце, вода и земля", distractors: ["Воздух и торт", "Только песок", "Только снег"], grades: 0...2),
        BankQuestion(prompt: "💧\nСколько процентов Земли покрыто водой?", correctAnswer: "Около 71%", distractors: ["20%", "50%", "100%"], grades: 4...6),
        BankQuestion(prompt: "🧊\nЧто происходит с водой при 0 градусов?", correctAnswer: "Она замерзает", distractors: ["Она исчезает", "Она кипит", "Она меняет цвет"], grades: 2...4),
        BankQuestion(prompt: "🌡️\nПри какой температуре кипит вода?", correctAnswer: "100°C", distractors: ["50°C", "200°C", "30°C"], grades: 4...6),
        BankQuestion(prompt: "🌍\nСколько на Земле больших тектонических плит?", correctAnswer: "Около семи", distractors: ["Одна", "Две", "Сто"], grades: 4...6),
        BankQuestion(prompt: "🦴\nСколько костей в теле взрослого человека?", correctAnswer: "206", distractors: ["150", "100", "300"], grades: 2...4),
        BankQuestion(prompt: "👀\nСколько цветов в радуге?", correctAnswer: "7", distractors: ["5", "6", "10"], grades: 0...2),
        BankQuestion(prompt: "🐅\nКакой орган качает кровь?", correctAnswer: "Сердце", distractors: ["Лёгкие", "Печень", "Мозг"], grades: 2...4),
        BankQuestion(prompt: "🌬️\nКакой газ мы забираем из воздуха, когда дышим?", correctAnswer: "Кислород", distractors: ["Водород", "Углерод", "Озон"], grades: 2...4),
        BankQuestion(prompt: "🌙\nСколько времени Луне нужно, чтобы облететь Землю?", correctAnswer: "Около 27 дней", distractors: ["Один день", "Один год", "100 дней"], grades: 4...6),
        BankQuestion(prompt: "☀️\nСколько времени солнечный свет летит до нас?", correctAnswer: "8 минут", distractors: ["Секунду", "Час", "Сутки"], grades: 4...6),
        BankQuestion(prompt: "🪐\nКакая планета самая большая?", correctAnswer: "Юпитер", distractors: ["Венера", "Марс", "Земля"], grades: 4...6),
        BankQuestion(prompt: "🌎\nСколько планет в Солнечной системе?", correctAnswer: "8", distractors: ["7", "9", "10"], grades: 4...6),
        BankQuestion(prompt: "🔴\nКакая планета красная?", correctAnswer: "Марс", distractors: ["Венера", "Юпитер", "Сатурн"], grades: 4...6),
        BankQuestion(prompt: "🌟\nКакое небесное тело ближе всего к Земле?", correctAnswer: "Луна", distractors: ["Марс", "Венера", "Солнце"], grades: 4...6),
        BankQuestion(prompt: "🌳\nКакой газ растения поглощают, чтобы делать себе еду?", correctAnswer: "Углекислый газ", distractors: ["Кислород", "Гелий", "Азот"], grades: 4...6),
        BankQuestion(prompt: "🌳\nКакой газ растения выделяют на свету?", correctAnswer: "Кислород", distractors: ["Азот", "Водород", "Гелий"], grades: 4...6),
        BankQuestion(prompt: "🐝\nКак цветы получают пыльцу?", correctAnswer: "С помощью пчёл", distractors: ["С помощью дождя", "С помощью земли", "С помощью солнца"], grades: 0...2),
        BankQuestion(prompt: "❄️\nКакие свойства у льда?", correctAnswer: "Холодный и твёрдый", distractors: ["Горячий и мягкий", "Прозрачный и жидкий", "Жёлтый и душистый"], grades: 0...2),
        BankQuestion(prompt: "🔥\nЧто нужно огню, чтобы гореть?", correctAnswer: "Кислород и топливо", distractors: ["Только вода", "Песок", "Холод"], grades: 2...4),
        BankQuestion(prompt: "🌊\nИз-за чего в море появляются волны?", correctAnswer: "Из-за ветра", distractors: ["Из-за рыб", "Из-за песка", "Из-за облаков"], grades: 2...4),
        BankQuestion(prompt: "🌜\nЧто сильнее всего влияет на приливы и отливы?", correctAnswer: "Луна", distractors: ["Ветер", "Солнце", "Рыбы"], grades: 4...6),
        BankQuestion(prompt: "🦟\nСколько ног у насекомого?", correctAnswer: "6", distractors: ["4", "8", "10"], grades: 0...2),
        BankQuestion(prompt: "🐍\nЗмеи — это...?", correctAnswer: "Пресмыкающиеся", distractors: ["Млекопитающие", "Птицы", "Рыбы"], grades: 2...4),
        BankQuestion(prompt: "🐬\nДельфины — это...?", correctAnswer: "Млекопитающие", distractors: ["Рыбы", "Пресмыкающиеся", "Птицы"], grades: 2...4),
        BankQuestion(prompt: "🦇\nЛетучие мыши — это...?", correctAnswer: "Млекопитающие", distractors: ["Птицы", "Насекомые", "Пресмыкающиеся"], grades: 2...4),
        BankQuestion(prompt: "🐢\nЧерепахи — это...?", correctAnswer: "Пресмыкающиеся", distractors: ["Млекопитающие", "Рыбы", "Птицы"], grades: 2...4),
        BankQuestion(prompt: "🌱\nКакая часть растения всасывает воду?", correctAnswer: "Корень", distractors: ["Лист", "Цветок", "Ствол"], grades: 0...2),
        BankQuestion(prompt: "☀️\nКакая часть растения делает энергию из солнечного света?", correctAnswer: "Лист", distractors: ["Корень", "Цветок", "Земля"], grades: 2...4),
        BankQuestion(prompt: "💪\nКакая часть тела самая сильная и двигает нас?", correctAnswer: "Мышцы", distractors: ["Кожа", "Волосы", "Ногти"], grades: 2...4),
        BankQuestion(prompt: "🦷\nСколько зубов у взрослого?", correctAnswer: "32", distractors: ["20", "28", "40"], grades: 2...4),
        BankQuestion(prompt: "🧠\nКакой орган думает?", correctAnswer: "Мозг", distractors: ["Сердце", "Печень", "Лёгкие"], grades: 0...2),
        BankQuestion(prompt: "👀\nСколько глаз у пчелы?", correctAnswer: "5", distractors: ["2", "3", "8"], grades: 2...4),
        BankQuestion(prompt: "🐌\nСколько сердец у осьминога?", correctAnswer: "3", distractors: ["1", "2", "5"], grades: 2...4),
        BankQuestion(prompt: "🦒\nКакое животное самое высокое на суше?", correctAnswer: "Жираф", distractors: ["Слон", "Лошадь", "Человек"], grades: 0...2),
        BankQuestion(prompt: "🐋\nКакое животное самое большое в мире?", correctAnswer: "Синий кит", distractors: ["Слон", "Акула", "Жираф"], grades: 0...2),
        BankQuestion(prompt: "🐆\nКакое животное быстрее всех бегает по земле?", correctAnswer: "Гепард", distractors: ["Лошадь", "Тигр", "Лев"], grades: 0...2),
        BankQuestion(prompt: "⚡\nКак называются гром и молния вместе?", correctAnswer: "Гроза", distractors: ["Песчаная буря", "Торнадо", "Зелёная буря"], grades: 2...4),
        BankQuestion(prompt: "🌫\nЧто такое туман?", correctAnswer: "Облако у самой земли", distractors: ["Мелкий дождь", "Пыль", "Дым"], grades: 2...4),
        BankQuestion(prompt: "🌋\nЧто вытекает из вулкана во время извержения?", correctAnswer: "Лава", distractors: ["Снег", "Лёд", "Мороженое"], grades: 2...4),
        BankQuestion(prompt: "🌊\nКак называется огромная волна в море?", correctAnswer: "Цунами", distractors: ["Торнадо", "Буря", "Туман"], grades: 2...4),
        BankQuestion(prompt: "💎\nКакое вещество самое твёрдое в природе?", correctAnswer: "Алмаз", distractors: ["Железо", "Камень", "Стекло"], grades: 2...4),
        BankQuestion(prompt: "🧲\nЧто притягивает железные предметы?", correctAnswer: "Магнит", distractors: ["Вода", "Камень", "Пластик"], grades: 2...4),
        BankQuestion(prompt: "🔦\nКак движется свет?", correctAnswer: "По прямой линии", distractors: ["По кругу", "Зигзагами", "Совсем не движется"], grades: 4...6),
        BankQuestion(prompt: "👂\nКак мы слышим?", correctAnswer: "С помощью звуковых волн", distractors: ["С помощью световых волн", "С помощью прикосновения", "С помощью запаха"], grades: 4...6),
        BankQuestion(prompt: "🌈\nСколько цветов в радуге?", correctAnswer: "7", distractors: ["5", "8", "10"], grades: 0...2),
        BankQuestion(prompt: "🌳\nКакое дерево самое высокое в мире?", correctAnswer: "Секвойя", distractors: ["Дуб", "Эвкалипт", "Финиковая пальма"], grades: 2...4),
        BankQuestion(prompt: "💨\nКакие вещества быстрее всего расходятся во все стороны?", correctAnswer: "Газы", distractors: ["Жидкости", "Твёрдые тела", "Ничего из этого"], grades: 2...4),
        BankQuestion(prompt: "🌧\nКакие есть три состояния вещества?", correctAnswer: "Твёрдое, жидкое, газообразное", distractors: ["Горячее, холодное, тёплое", "Тёплое, мокрое, сухое", "Первое, второе, третье"], grades: 2...4),
        BankQuestion(prompt: "🐦\nЧто позволяет птице летать?", correctAnswer: "Крылья", distractors: ["Зубы", "Хвост", "Шерсть"], grades: 0...2),
        BankQuestion(prompt: "🌳\nКакой газ деревья выделяют на свету?", correctAnswer: "Кислород", distractors: ["Водород", "Гелий", "Азот"], grades: 2...4),
        BankQuestion(prompt: "🦠\nЧто такое бактерия?", correctAnswer: "Крошечное живое существо", distractors: ["Вид овоща", "Вид металла", "Вид камня"], grades: 4...6),
        BankQuestion(prompt: "🌍\nКакая сила тянет нас к земле?", correctAnswer: "Сила тяжести", distractors: ["Магнит", "Ветер", "Свет"], grades: 4...6),
        BankQuestion(prompt: "🐸\nКак называется детёныш лягушки?", correctAnswer: "Головастик", distractors: ["Щенок", "Цыплёнок", "Жеребёнок"], grades: 0...2),
        BankQuestion(prompt: "🐔\nОткуда вылупляются цыплята?", correctAnswer: "Из яйца", distractors: ["Из земли", "Из облака", "Из воды"], grades: 0...2),
        BankQuestion(prompt: "🐪\nЧто верблюд хранит в горбу?", correctAnswer: "Жир", distractors: ["Воду", "Песок", "Воздух"], grades: 2...4),
        BankQuestion(prompt: "🦉\nКогда сова чаще всего бодрствует?", correctAnswer: "Ночью", distractors: ["В полдень", "Утром", "Никогда"], grades: 0...2),
        BankQuestion(prompt: "🐻\nЧто делают медведи холодной зимой?", correctAnswer: "Спят зимним сном", distractors: ["Плавают в море", "Летят на юг", "Загорают"], grades: 0...2),
        BankQuestion(prompt: "🦷\nКакой орган помогает нам жевать еду?", correctAnswer: "Зубы", distractors: ["Уши", "Колени", "Ногти"], grades: 0...2),
        BankQuestion(prompt: "🩸\nКакого цвета наша кровь?", correctAnswer: "Красного", distractors: ["Синего", "Зелёного", "Жёлтого"], grades: 0...2),
        BankQuestion(prompt: "👃\nКаким органом мы нюхаем?", correctAnswer: "Носом", distractors: ["Глазами", "Ушами", "Руками"], grades: 0...2),
        BankQuestion(prompt: "👅\nКаким органом мы чувствуем вкус?", correctAnswer: "Языком", distractors: ["Носом", "Глазами", "Ушами"], grades: 0...2),
        BankQuestion(prompt: "💤\nКогда наше тело отдыхает и набирается сил?", correctAnswer: "Когда мы спим", distractors: ["Когда мы бегаем", "Когда мы едим", "Когда мы смеёмся"], grades: 0...2),
        BankQuestion(prompt: "🌙\nЧто светит в небе ночью?", correctAnswer: "Луна", distractors: ["Солнце", "Цветы", "Дождевые тучи"], grades: 0...2),
        BankQuestion(prompt: "🌍\nКакая форма у Земли?", correctAnswer: "Круглая, как мяч", distractors: ["Плоская", "Квадратная", "Треугольная"], grades: 2...4),
        BankQuestion(prompt: "☀️\nКогда светит солнце?", correctAnswer: "Днём", distractors: ["Ночью", "Только зимой", "Никогда"], grades: 0...2),
        BankQuestion(prompt: "⭐\nКогда видно звёзды?", correctAnswer: "Ночью", distractors: ["В полдень", "Утром", "Когда светит солнце"], grades: 0...2),
        BankQuestion(prompt: "🚀\nКак называют человека, который летает в космос?", correctAnswer: "Астронавт", distractors: ["Лётчик", "Водолаз", "Водитель"], grades: 2...4),
        BankQuestion(prompt: "⛈️\nЧто видно в небе за мгновение до грома?", correctAnswer: "Молния", distractors: ["Радуга", "Снег", "Луна"], grades: 2...4),
        BankQuestion(prompt: "🌧️\nЧто падает из тучи, когда идёт дождь?", correctAnswer: "Капли воды", distractors: ["Песок", "Листья", "Камни"], grades: 0...2),
        BankQuestion(prompt: "⛄\nЧто должно быть на улице, чтобы слепить снеговика?", correctAnswer: "Мороз и снег", distractors: ["Сильная жара", "Тёплый дождь", "Тёплый ветер"], grades: 0...2),
        BankQuestion(prompt: "🌬️\nЧто вращает крылья мельницы, у которой нет мотора?", correctAnswer: "Ветер", distractors: ["Дождь", "Снег", "Солнце"], grades: 2...4),
        BankQuestion(prompt: "🌡️\nВ какое время года в Израиле жарче всего?", correctAnswer: "Летом", distractors: ["Зимой", "Осенью", "Весной"], grades: 0...2),
        BankQuestion(prompt: "🌼\nКакая часть растения самая яркая и красивая?", correctAnswer: "Цветок", distractors: ["Корень", "Ствол", "Земля"], grades: 0...2),
        BankQuestion(prompt: "🍎\nС какой части дерева срывают яблоко?", correctAnswer: "С ветки", distractors: ["С корня", "С земли", "Со ствола"], grades: 0...2),
        BankQuestion(prompt: "🌻\nКуда поворачивается молодой подсолнух?", correctAnswer: "К солнцу", distractors: ["К земле", "К луне", "К воде"], grades: 2...4),
        BankQuestion(prompt: "🌳\nЧто вырастает из маленького семечка, которое посадили?", correctAnswer: "Растение", distractors: ["Камень", "Облако", "Рыба"], grades: 0...2),
        BankQuestion(prompt: "💧\nЧто мы делаем в воде, чтобы стать чистыми?", correctAnswer: "Моемся", distractors: ["Спим", "Красим", "Едим"], grades: 0...2),
        BankQuestion(prompt: "🚰\nОткуда дома течёт питьевая вода?", correctAnswer: "Из крана", distractors: ["Из окна", "Из лампы", "Из телевизора"], grades: 0...2),
        BankQuestion(prompt: "🐟\nКакой орган помогает рыбе дышать в воде?", correctAnswer: "Жабры", distractors: ["Лёгкие", "Нос", "Уши"], grades: 2...4),
        BankQuestion(prompt: "🦆\nЧто утка умеет лучше всего?", correctAnswer: "Плавать в воде", distractors: ["Лазать по деревьям", "Копать норы", "Плести паутину"], grades: 0...2),
        BankQuestion(prompt: "🌊\nКакая на вкус морская вода?", correctAnswer: "Солёная", distractors: ["Сладкая", "Кислая", "Острая"], grades: 0...2),
        BankQuestion(prompt: "☁️\nИз чего состоят облака?", correctAnswer: "Из крошечных капелек воды", distractors: ["Из мягкой шерсти", "Из дыма", "Из песка"], grades: 2...4),
        BankQuestion(prompt: "🐜\nКак живут муравьи?", correctAnswer: "Большой семьёй", distractors: ["Всегда поодиночке", "В море", "На облаке"], grades: 0...2),
        BankQuestion(prompt: "🦋\nСколько крыльев у бабочки?", correctAnswer: "4", distractors: ["2", "6", "8"], grades: 2...4),
        BankQuestion(prompt: "🐢\nЧто черепаха всегда носит на спине?", correctAnswer: "Панцирь", distractors: ["Крылья", "Колючки", "Шерсть"], grades: 0...2),
        BankQuestion(prompt: "🌈\nКогда чаще всего появляется радуга?", correctAnswer: "После дождя", distractors: ["Вечером", "В снегопад", "Тёмной ночью"], grades: 0...2),
        BankQuestion(prompt: "🌙\nЧто видно в небе ясной ночью?", correctAnswer: "Луна и звёзды", distractors: ["Солнце и радуга", "Дождевые тучи", "Цветы"], grades: 0...2),
        BankQuestion(prompt: "🫀\nКакой орган бьётся у нас в груди?", correctAnswer: "Сердце", distractors: ["Печень", "Желудок", "Селезёнка"], grades: 2...4),
        BankQuestion(prompt: "💪\nЧто помогает нам двигать руками и ногами?", correctAnswer: "Мышцы", distractors: ["Волосы", "Ногти", "Слёзы"], grades: 2...4),
        BankQuestion(prompt: "🦵\nЧто находится внутри тела и придаёт ему форму?", correctAnswer: "Кости", distractors: ["Облака", "Снег", "Песок"], grades: 2...4),
        BankQuestion(prompt: "🫁\nКакой орган наполняется воздухом, когда мы дышим?", correctAnswer: "Лёгкие", distractors: ["Сердце", "Желудок", "Мозг"], grades: 2...4),
        BankQuestion(prompt: "💇\nЧто растёт у нас на голове?", correctAnswer: "Волосы", distractors: ["Перья", "Чешуя", "Иголки"], grades: 0...2),
        BankQuestion(prompt: "🦘\nКакое животное носит детёныша в сумке?", correctAnswer: "Кенгуру", distractors: ["Лев", "Слон", "Зебра"], grades: 0...2),
        BankQuestion(prompt: "🐧\nКакая птица не умеет летать, зато отлично плавает?", correctAnswer: "Пингвин", distractors: ["Голубь", "Орёл", "Воробей"], grades: 0...2),
        BankQuestion(prompt: "🕸️\nЧто плетёт паук, чтобы ловить добычу?", correctAnswer: "Паутину", distractors: ["Мёд", "Молоко", "Гнездо из соломы"], grades: 0...2),
        BankQuestion(prompt: "🐘\nЧем слон пьёт и поднимает вещи?", correctAnswer: "Хоботом", distractors: ["Хвостом", "Ушами", "Ногами"], grades: 0...2),
        BankQuestion(prompt: "🐄\nКакой напиток мы получаем от коровы?", correctAnswer: "Молоко", distractors: ["Сок", "Мёд", "Масло"], grades: 0...2),
        BankQuestion(prompt: "🪐\nКакая планета знаменита кольцами вокруг неё?", correctAnswer: "Сатурн", distractors: ["Марс", "Венера", "Земля"], grades: 4...6),
        BankQuestion(prompt: "🌕\nКак называют луну, когда виден весь её круглый диск?", correctAnswer: "Полнолуние", distractors: ["Новолуние", "Красная луна", "Маленькая луна"], grades: 2...4),
        BankQuestion(prompt: "🌌\nКак называется огромное скопление звёзд?", correctAnswer: "Галактика", distractors: ["Тучка", "Радуга", "Буря"], grades: 4...6),
        BankQuestion(prompt: "🌑\nСколько солнц в нашей Солнечной системе?", correctAnswer: "Одно", distractors: ["Два", "Три", "Ни одного"], grades: 2...4),
        BankQuestion(prompt: "⚡\nКакой яркий свет вспыхивает в небе во время грозы?", correctAnswer: "Молния", distractors: ["Радуга", "Снег", "Туман"], grades: 0...2),
        BankQuestion(prompt: "🌪️\nКак называют сильный ветер, который крутится столбом?", correctAnswer: "Торнадо", distractors: ["Радуга", "Капля", "Обычное облако"], grades: 2...4),
        BankQuestion(prompt: "☀️\nКак называется день без облаков, когда ярко светит солнце?", correctAnswer: "Ясный день", distractors: ["Дождливый день", "Снежный день", "Бурный день"], grades: 0...2),
        BankQuestion(prompt: "🌡️\nВ какое время года в Израиле холоднее всего?", correctAnswer: "Зимой", distractors: ["Летом", "Весной", "Осенью"], grades: 0...2),
        BankQuestion(prompt: "🍂\nВ какое время года листья опадают с деревьев?", correctAnswer: "Осенью", distractors: ["Летом", "Весной", "Круглый год"], grades: 0...2),
        BankQuestion(prompt: "🌷\nВ какое время года распускается больше всего цветов?", correctAnswer: "Весной", distractors: ["Зимой", "Осенью", "Ночью"], grades: 0...2),
        BankQuestion(prompt: "🌰\nЧто появляется первым, когда семечко начинает расти в земле?", correctAnswer: "Корень", distractors: ["Цветок", "Плод", "Большой лист"], grades: 2...4),
        BankQuestion(prompt: "🌿\nКакого цвета листья у большинства растений?", correctAnswer: "Зелёные", distractors: ["Синие", "Фиолетовые", "Чёрные"], grades: 0...2),
        BankQuestion(prompt: "🍋\nКакой вкус у лимона?", correctAnswer: "Кислый", distractors: ["Сладкий", "Солёный", "Острый"], grades: 0...2),
        BankQuestion(prompt: "🍯\nКакой вкус у мёда?", correctAnswer: "Сладкий", distractors: ["Кислый", "Солёный", "Горький"], grades: 0...2),
        BankQuestion(prompt: "🥶\nКаким кажется лёд, когда его трогаешь?", correctAnswer: "Холодным", distractors: ["Горячим", "Мокрым и тёплым", "Мягким"], grades: 0...2),
        BankQuestion(prompt: "🔥\nКакая на ощупь еда, которую только что достали из духовки?", correctAnswer: "Горячая", distractors: ["Холодная", "Замороженная", "Твёрдая как камень"], grades: 0...2),
        BankQuestion(prompt: "💧\nЧто происходит со снегом, когда его нагревают?", correctAnswer: "Он превращается в воду", distractors: ["Он превращается в камень", "Он превращается в песок", "Он остаётся таким же"], grades: 2...4),
        BankQuestion(prompt: "🪵\nИз чего сделана доска, которую выпилили из ствола?", correctAnswer: "Дерево", distractors: ["Стекло", "Железо", "Пластик"], grades: 0...2),
        BankQuestion(prompt: "👅\nС помощью какого чувства мы узнаём, сладкая еда или солёная?", correctAnswer: "Вкус", distractors: ["Зрение", "Слух", "Обоняние"], grades: 2...4),
        BankQuestion(prompt: "Какой орган помогает нам дышать?", correctAnswer: "Лёгкие", distractors: ["Сердце", "Печень", "Желудок"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "Какое животное говорит «му»?", correctAnswer: "Корова", distractors: ["Собака", "Кошка", "Петух"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное любит грызть морковку?", correctAnswer: "Кролик", distractors: ["Рыба", "Птица", "Змея"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Каким органом мы видим?", correctAnswer: "Глаза", distractors: ["Уши", "Нос", "Рот"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Каким органом мы слышим?", correctAnswer: "Уши", distractors: ["Глаза", "Руки", "Ноги"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Где живут рыбы?", correctAnswer: "В воде", distractors: ["На дереве", "В воздухе", "В песке"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Что нужно растению, чтобы расти?", correctAnswer: "Вода", distractors: ["Сахар", "Камень", "Пластик"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какая звезда светит нам днём?", correctAnswer: "Солнце", distractors: ["Луна", "Падающая звезда", "Марс"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Когда мы видим луну?", correctAnswer: "Ночью", distractors: ["Утром", "В полдень", "Никогда"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Что падает с неба, когда идёт дождь?", correctAnswer: "Вода", distractors: ["Песок", "Камни", "Листья"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное умеет летать?", correctAnswer: "Птица", distractors: ["Рыба", "Слон", "Черепаха"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное говорит «гав-гав»?", correctAnswer: "Собака", distractors: ["Кошка", "Корова", "Лошадь"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Каким органом мы нюхаем?", correctAnswer: "Нос", distractors: ["Глаза", "Уши", "Рука"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какая часть растения находится в земле?", correctAnswer: "Корень", distractors: ["Цветок", "Лист", "Плод"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Сколько лап у собаки?", correctAnswer: "Четыре", distractors: ["Две", "Шесть", "Восемь"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "В какое время года в холодных странах идёт снег?", correctAnswer: "Зимой", distractors: ["Летом", "Весной", "Осенью"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Как называется твёрдая замёрзшая вода?", correctAnswer: "Лёд", distractors: ["Пар", "Капля", "Облако"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное даёт нам молоко?", correctAnswer: "Корова", distractors: ["Петух", "Рыба", "Кошка"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какого цвета большинство листьев?", correctAnswer: "Зелёного", distractors: ["Синего", "Красного", "Фиолетового"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Каким органом мы чувствуем вкус?", correctAnswer: "Язык", distractors: ["Ухо", "Глаз", "Нос"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное живёт дома и говорит «мяу»?", correctAnswer: "Кошка", distractors: ["Лев", "Волк", "Лиса"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какой газ из воздуха нужен нам, чтобы дышать?", correctAnswer: "Кислород", distractors: ["Вода", "Песок", "Сахар"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "У какого животного длинный хобот?", correctAnswer: "Слон", distractors: ["Жираф", "Зебра", "Обезьяна"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Что помогает птице летать?", correctAnswer: "Крылья", distractors: ["Плавники", "Длинный хвост", "Рога"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какой из этих плодов растёт на дереве?", correctAnswer: "Яблоки", distractors: ["Виноград", "Клубника", "Арбуз"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное прыгает и носит детёныша в сумке?", correctAnswer: "Кенгуру", distractors: ["Кролик", "Белка", "Лягушка"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Когда солнце светит на небе?", correctAnswer: "Днём", distractors: ["Ночью", "Только зимой", "Никогда"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какого цвета небо в ясный день?", correctAnswer: "Синего", distractors: ["Зелёного", "Красного", "Коричневого"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Из какого материала столяр делает стол и стул?", correctAnswer: "Дерево", distractors: ["Стекло", "Металл", "Пластик"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное лает?", correctAnswer: "Собака", distractors: ["Кошка", "Корова", "Овца"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Что ест лягушка?", correctAnswer: "Насекомых", distractors: ["Траву", "Камни", "Цветы"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какой частью тела мы думаем?", correctAnswer: "Мозг", distractors: ["Сердце", "Рука", "Нога"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое время года самое жаркое?", correctAnswer: "Лето", distractors: ["Зима", "Осень", "Весна"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное живёт в воде и у него есть плавники?", correctAnswer: "Рыба", distractors: ["Кошка", "Птица", "Лошадь"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Что вырастает из семечка, которое посадили в землю?", correctAnswer: "Растение", distractors: ["Камень", "Металл", "Вода"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "У какого животного очень длинная шея?", correctAnswer: "Жираф", distractors: ["Кролик", "Собака", "Мышь"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Из какого материала делают окно, через которое всё видно?", correctAnswer: "Стекло", distractors: ["Дерево", "Камень", "Ткань"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Сколько пальцев на одной руке?", correctAnswer: "Пять", distractors: ["Три", "Семь", "Десять"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какой предмет помогает нам видеть в темноте?", correctAnswer: "Фонарик", distractors: ["Ложка", "Стул", "Книга"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное лазает по деревьям и любит бананы?", correctAnswer: "Обезьяна", distractors: ["Рыба", "Корова", "Черепаха"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Что нам даёт курица?", correctAnswer: "Яйца", distractors: ["Молоко", "Шерсть", "Мёд"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное носит свой домик на спине?", correctAnswer: "Улитка", distractors: ["Кролик", "Птица", "Кошка"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Что мы делаем ногами?", correctAnswer: "Ходим", distractors: ["Слышим", "Видим", "Нюхаем"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное даёт нам шерсть?", correctAnswer: "Овца", distractors: ["Рыба", "Курица", "Черепаха"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Что мы пьём, когда хочется пить?", correctAnswer: "Воду", distractors: ["Песок", "Воздух", "Камень"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какое животное ходит очень медленно и носит панцирь?", correctAnswer: "Черепаха", distractors: ["Леопард", "Кролик", "Газель"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Из какого материала делают кастрюли, в которых варят еду?", correctAnswer: "Металл", distractors: ["Бумага", "Ткань", "Вата"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "Какой орган переваривает еду в животе?", correctAnswer: "Желудок", distractors: ["Мозг", "Лёгкие", "Ухо"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Сколько планет вращается вокруг Солнца в Солнечной системе?", correctAnswer: "Восемь", distractors: ["Шесть", "Десять", "Четыре"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как называется процесс, когда вода от тепла превращается в пар?", correctAnswer: "Испарение", distractors: ["Замерзание", "Таяние", "Конденсация"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой орган качает кровь по телу?", correctAnswer: "Сердце", distractors: ["Мозг", "Лёгкие", "Желудок"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какая часть растения превращается в плод?", correctAnswer: "Цветок", distractors: ["Корень", "Лист", "Ствол"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какой газ растения выделяют днём, и он помогает нам дышать?", correctAnswer: "Кислород", distractors: ["Углекислый газ", "Водяной пар", "Дым"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какую планету называют «красной планетой»?", correctAnswer: "Марс", distractors: ["Венера", "Юпитер", "Сатурн"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какой материал притягивается к магниту?", correctAnswer: "Железо", distractors: ["Дерево", "Стекло", "Пластик"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что происходит с водой, если поставить её в морозилку?", correctAnswer: "Она замерзает и превращается в лёд", distractors: ["Она испаряется", "Она исчезает", "Она становится горячей"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Из-за чего на нашей планете бывают день и ночь?", correctAnswer: "Земля вращается вокруг своей оси", distractors: ["Луна закрывает Солнце", "Облака заслоняют свет", "Солнце гаснет"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое морское животное — млекопитающее и дышит воздухом?", correctAnswer: "Дельфин", distractors: ["Акула", "Осьминог", "Медуза"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое чувство позволяет нам понять, горячее что-то или холодное?", correctAnswer: "Осязание", distractors: ["Обоняние", "Слух", "Зрение"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что растение получает от солнца, чтобы приготовить себе пищу?", correctAnswer: "Свет", distractors: ["Лёд", "Камни", "Металл"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое животное откладывает яйца и покрыто перьями?", correctAnswer: "Птица", distractors: ["Собака", "Корова", "Лошадь"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Кто сначала бывает головастиком, а потом отращивает лапы и выходит на берег?", correctAnswer: "Лягушка", distractors: ["Черепаха", "Змея", "Рыба"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Почему осенью у некоторых деревьев опадают листья?", correctAnswer: "Меняется время года и становится холодно", distractors: ["Летом не хватило воды", "Слишком много солнца", "Ветер их красит"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое небесное тело вращается вокруг Земли?", correctAnswer: "Луна", distractors: ["Солнце", "Марс", "Венера"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Что происходит со льдом, если оставить его в тепле?", correctAnswer: "Он тает и превращается в воду", distractors: ["Он превращается в камень", "Он исчезает", "Он превращается в дерево"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое насекомое делает мёд?", correctAnswer: "Пчела", distractors: ["Муравей", "Бабочка", "Муха"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Как называется вода, которая поднимается в воздух и собирается в облака?", correctAnswer: "Водяной пар", distractors: ["Лёд", "Снег", "Песок"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое чувство помогает нам наслаждаться запахом цветов?", correctAnswer: "Обоняние", distractors: ["Зрение", "Слух", "Вкус"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какая часть растения впитывает воду из земли?", correctAnswer: "Корень", distractors: ["Лист", "Цветок", "Плод"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое животное меняет кожу и ползёт без ног?", correctAnswer: "Змея", distractors: ["Ящерица", "Черепаха", "Лягушка"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какой орган разносит кровь и кислород по всему телу?", correctAnswer: "Сердце", distractors: ["Мозг", "Печень", "Глаз"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Как называется разноцветная дуга, которая появляется в небе после дождя и солнца?", correctAnswer: "Радуга", distractors: ["Молния", "Снег", "Туман"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какой материал хорошо проводит электричество?", correctAnswer: "Металл", distractors: ["Дерево", "Пластик", "Резина"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое животное спит всю зиму в спячке?", correctAnswer: "Медведь", distractors: ["Собака", "Лошадь", "Корова"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Как называется время года, когда распускается много цветов?", correctAnswer: "Весна", distractors: ["Зима", "Лето", "Осень"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какая часть глаза пропускает свет внутрь?", correctAnswer: "Зрачок", distractors: ["Бровь", "Ресница", "Ухо"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое животное дышит жабрами?", correctAnswer: "Рыба", distractors: ["Собака", "Птица", "Кошка"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Как называется детёныш кошки?", correctAnswer: "Котёнок", distractors: ["Козлёнок", "Телёнок", "Жеребёнок"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое небесное тело даёт нам свет и тепло и на самом деле является звездой?", correctAnswer: "Солнце", distractors: ["Луна", "Облако", "Падающая звезда"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Как называется процесс, когда пар остывает и снова превращается в капли?", correctAnswer: "Конденсация", distractors: ["Замерзание", "Испарение", "Таяние"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Какое животное плетёт сети, чтобы ловить добычу?", correctAnswer: "Паук", distractors: ["Муравей", "Бабочка", "Жук"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Как называют животное, которое ест только растения?", correctAnswer: "Травоядное", distractors: ["Хищник", "Летающее", "Водное"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какая часть тела защищает мозг?", correctAnswer: "Череп", distractors: ["Рёбра", "Ладонь", "Колено"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какое животное меняет цвет, чтобы слиться с окружением?", correctAnswer: "Хамелеон", distractors: ["Кролик", "Корова", "Лошадь"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какая сила тянет предметы вниз, к земле?", correctAnswer: "Сила тяжести", distractors: ["Сила ветра", "Сила магнита", "Сила солнца"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как называется очень сухая местность, где мало дождей и много песка?", correctAnswer: "Пустыня", distractors: ["Лес", "Озеро", "Болото"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "Какой орган очищает кровь и помогает переваривать пищу?", correctAnswer: "Печень", distractors: ["Сердце", "Мозг", "Ухо"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как называется процесс, в котором растения делают себе пищу из солнечного света?", correctAnswer: "Фотосинтез", distractors: ["Испарение", "Дыхание", "Пищеварение"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой газ растения поглощают из воздуха, когда делают себе пищу?", correctAnswer: "Углекислый газ", distractors: ["Кислород", "Азот", "Водяной пар"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Вода испаряется, собирается в облака и снова выпадает дождём. Как называется этот бесконечный путь?", correctAnswer: "Круговорот воды", distractors: ["Смена времён года", "Фазы Луны", "Вращение Земли"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой орган управляет нашими мыслями и движениями?", correctAnswer: "Мозг", distractors: ["Сердце", "Печень", "Лёгкие"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что заставляет два разных полюса магнита притягиваться друг к другу?", correctAnswer: "Магнетизм", distractors: ["Сила тяжести", "Сила трения", "Сила ветра"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой орган фильтрует кровь и выводит мочу?", correctAnswer: "Почка", distractors: ["Сердце", "Лёгкое", "Мозг"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое условие нужно, чтобы предмет утонул, а не плавал на поверхности?", correctAnswer: "Плотность больше, чем у воды", distractors: ["Тёмный цвет", "Круглая форма", "Очень маленький вес"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой газ составляет большую часть воздуха, которым мы дышим?", correctAnswer: "Азот", distractors: ["Кислород", "Углекислый газ", "Водяной пар"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как называется слой газов, который окружает Землю?", correctAnswer: "Атмосфера", distractors: ["Слой льда", "Слой песка", "Слой воды"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая часть уха помогает нам держать равновесие?", correctAnswer: "Внутреннее ухо", distractors: ["Мочка уха", "Кожа лица", "Скула"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое состояние воды является газообразным?", correctAnswer: "Пар", distractors: ["Лёд", "Снег", "Иней"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая сила заставляет Луну двигаться вокруг Земли?", correctAnswer: "Сила тяжести", distractors: ["Сила ветра", "Свет солнца", "Магнетизм"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как называется огромное скопление звёзд в космосе?", correctAnswer: "Галактика", distractors: ["Планета", "Спутник", "Астероид"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое вещество в листе даёт ему зелёный цвет и поглощает свет?", correctAnswer: "Хлорофилл", distractors: ["Вода", "Песок", "Сахар"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой орган переносит еду изо рта в желудок?", correctAnswer: "Пищевод", distractors: ["Трахея", "Артерия", "Вена"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая планета знаменита яркими кольцами вокруг неё?", correctAnswer: "Сатурн", distractors: ["Марс", "Венера", "Меркурий"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как называется процесс, когда жидкая вода превращается в твёрдый лёд?", correctAnswer: "Замерзание", distractors: ["Испарение", "Таяние", "Конденсация"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое чувство работает благодаря клеткам, которые улавливают свет внутри глаза?", correctAnswer: "Зрение", distractors: ["Слух", "Вкус", "Осязание"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая сила замедляет предметы, которые скользят друг по другу?", correctAnswer: "Сила трения", distractors: ["Сила магнита", "Сила света", "Сила звука"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое животное — млекопитающее, но откладывает яйца?", correctAnswer: "Утконос", distractors: ["Медведь", "Дельфин", "Кролик"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что в крови переносит кислород ко всем органам тела?", correctAnswer: "Красные кровяные клетки", distractors: ["Белые кровяные клетки", "Только вода", "Сахар"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как называется тело в космосе, которое вращается вокруг планеты?", correctAnswer: "Спутник", distractors: ["Солнце", "Галактика", "Падающая звезда"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какая порода образуется, когда лава остывает и застывает?", correctAnswer: "Вулканическая порода", distractors: ["Песчаник", "Известняк", "Мрамор"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой орган хранит жёлчь, которая помогает переваривать жир?", correctAnswer: "Жёлчный пузырь", distractors: ["Сердце", "Лёгкое", "Мозг"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое погодное явление возникает от сильного электрического разряда между облаками?", correctAnswer: "Молния", distractors: ["Снег", "Туман", "Роса"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что в крови помогает бороться с микробами и сохранять здоровье?", correctAnswer: "Белые кровяные клетки", distractors: ["Красные кровяные клетки", "Водяной пар", "Сахар"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как называется процесс, когда семя начинает расти и выпускает корешок и росток?", correctAnswer: "Прорастание", distractors: ["Замерзание", "Испарение", "Конденсация"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какой орган дыхательной системы проводит воздух из горла в лёгкие?", correctAnswer: "Трахея", distractors: ["Пищевод", "Артерия", "Кишечник"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как называется явление, когда Луна проходит между Солнцем и Землёй и закрывает его от нас?", correctAnswer: "Солнечное затмение", distractors: ["Лунное затмение", "Радуга", "Восход"], tier: .hard, grades: 4...6),
    ]
}
