import Foundation

/// 🇬🇧 Английский язык — русский. Переведено с ивритского банка (362 вопросов),
/// израильские реалии и шекели сохранены.
extension RussianContent {
    static let english: [BankQuestion] = [
        BankQuestion(prompt: "🐈\nКак это сказать по-английски?", correctAnswer: "cat", distractors: ["dog", "fish", "bird"], grades: 3...4),
        BankQuestion(prompt: "🐕\nКак это сказать по-английски?", correctAnswer: "dog", distractors: ["cat", "horse", "cow"], grades: 3...4),
        BankQuestion(prompt: "🌞\nКак это сказать по-английски?", correctAnswer: "sun", distractors: ["moon", "star", "sky"], grades: 3...4),
        BankQuestion(prompt: "🍎\nКак это сказать по-английски?", correctAnswer: "apple", distractors: ["banana", "orange", "pear"], grades: 3...4),
        BankQuestion(prompt: "🏠\nКак это сказать по-английски?", correctAnswer: "house", distractors: ["car", "tree", "school"], grades: 3...5),
        BankQuestion(prompt: "📚\nКак это сказать по-английски?", correctAnswer: "book", distractors: ["pen", "table", "chair"], grades: 3...5),
        BankQuestion(prompt: "🚗\nКак это сказать по-английски?", correctAnswer: "car", distractors: ["bus", "bike", "boat"], grades: 3...5),
        BankQuestion(prompt: "🌳\nКак это сказать по-английски?", correctAnswer: "tree", distractors: ["flower", "grass", "leaf"], grades: 3...4),
        BankQuestion(prompt: "💧\nКак это сказать по-английски?", correctAnswer: "water", distractors: ["fire", "ice", "milk"], grades: 3...4),
        BankQuestion(prompt: "⭐\nКак это сказать по-английски?", correctAnswer: "star", distractors: ["sun", "moon", "cloud"], grades: 3...4),
        BankQuestion(prompt: "🌙\nКак это сказать по-английски?", correctAnswer: "moon", distractors: ["star", "sun", "night"], grades: 3...4),
        BankQuestion(prompt: "🥛\nКак это сказать по-английски?", correctAnswer: "milk", distractors: ["water", "juice", "tea"], grades: 3...5),
        BankQuestion(prompt: "🍞\nКак это сказать по-английски?", correctAnswer: "bread", distractors: ["cake", "rice", "egg"], grades: 3...5),
        BankQuestion(prompt: "🐟\nКак это сказать по-английски?", correctAnswer: "fish", distractors: ["cat", "dog", "bird"], grades: 3...4),
        BankQuestion(prompt: "🐦\nКак это сказать по-английски?", correctAnswer: "bird", distractors: ["fish", "frog", "duck"], grades: 3...4),
        BankQuestion(prompt: "🌸\nКак это сказать по-английски?", correctAnswer: "flower", distractors: ["tree", "leaf", "grass"], grades: 3...4),
        BankQuestion(prompt: "🐘\nКак это сказать по-английски?", correctAnswer: "elephant", distractors: ["lion", "bear", "tiger"], grades: 3...4),
        BankQuestion(prompt: "🦁\nКак это сказать по-английски?", correctAnswer: "lion", distractors: ["tiger", "bear", "elephant"], grades: 3...4),
        BankQuestion(prompt: "🚲\nКак это сказать по-английски?", correctAnswer: "bike", distractors: ["car", "bus", "train"], grades: 3...5),
        BankQuestion(prompt: "🎂\nКак это сказать по-английски?", correctAnswer: "cake", distractors: ["bread", "milk", "fruit"], grades: 3...5),
        BankQuestion(prompt: "✋\nКак сказать «рука» по-английски?", correctAnswer: "hand", distractors: ["foot", "head", "eye"], grades: 3...5),
        BankQuestion(prompt: "👁️\nКак сказать «глаз» по-английски?", correctAnswer: "eye", distractors: ["ear", "nose", "mouth"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «apple»?", correctAnswer: "яблоко", distractors: ["банан", "апельсин", "груша"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «book»?", correctAnswer: "книга", distractors: ["тетрадь", "ручка", "письмо"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «tree»?", correctAnswer: "дерево", distractors: ["цветок", "лист", "ветка"], grades: 3...5),
        BankQuestion(prompt: "🦋\nКак это сказать по-английски?", correctAnswer: "butterfly", distractors: ["dragonfly", "ladybug", "caterpillar"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "☂️\nКак это сказать по-английски?", correctAnswer: "umbrella", distractors: ["raincoat", "shadow", "shelter"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Как сказать «очки» по-английски?", correctAnswer: "glasses", distractors: ["windows", "mirrors", "bottles"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Как сказать «скоро» по-английски?", correctAnswer: "soon", distractors: ["late", "never", "always"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какое слово противоположно слову «empty»?", correctAnswer: "full", distractors: ["open", "heavy", "clean"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какое слово противоположно слову «expensive»?", correctAnswer: "cheap", distractors: ["rich", "small", "easy"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "«I am thirsty» — что это значит?", correctAnswer: "Я хочу пить", distractors: ["Я хочу есть", "Я устал", "Я рад"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "«See you tomorrow» — что это значит?", correctAnswer: "Увидимся завтра", distractors: ["До встречи вчера", "Доброе утро", "Я вижу тебя сейчас"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "Какое из этих слов — животное?", correctAnswer: "squirrel", distractors: ["mountain", "kitchen", "winter"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как сказать «библиотека» по-английски?", correctAnswer: "library", distractors: ["laboratory", "bakery", "pharmacy"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔴\nКак называется этот цвет по-английски?", correctAnswer: "red", distractors: ["blue", "green", "yellow"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "🔵\nКак называется этот цвет по-английски?", correctAnswer: "blue", distractors: ["red", "green", "black"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "🟢\nКак называется этот цвет по-английски?", correctAnswer: "green", distractors: ["yellow", "blue", "orange"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "С какой буквы начинается слово dog?", correctAnswer: "D", distractors: ["B", "G", "O"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "С какой буквы начинается слово sun?", correctAnswer: "S", distractors: ["C", "N", "U"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "5️⃣\nКак назвать это число по-английски?", correctAnswer: "five", distractors: ["four", "six", "nine"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "3️⃣\nКак назвать это число по-английски?", correctAnswer: "three", distractors: ["two", "five", "eight"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "Как сказать «папа» по-английски?", correctAnswer: "father", distractors: ["mother", "brother", "sister"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "Как сказать «мама» по-английски?", correctAnswer: "mother", distractors: ["father", "sister", "teacher"], tier: .easy, grades: 3...3),
        BankQuestion(prompt: "Что значит Good morning?", correctAnswer: "Доброе утро", distractors: ["Спокойной ночи", "До свидания", "Большое спасибо"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "Что значит Thank you?", correctAnswer: "Спасибо", distractors: ["Пожалуйста", "Извините", "Привет"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "Какая форма множественного числа у слова cat?", correctAnswer: "cats", distractors: ["cates", "caty", "catten"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "Какая форма множественного числа у слова book?", correctAnswer: "books", distractors: ["bookes", "booky", "booken"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "Как сказать «учительница» по-английски?", correctAnswer: "teacher", distractors: ["student", "doctor", "driver"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "Как сказать «школа» по-английски?", correctAnswer: "school", distractors: ["park", "store", "house"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "Как сказать «дождь» по-английски?", correctAnswer: "rain", distractors: ["snow", "wind", "cloud"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "Как сказать «снег» по-английски?", correctAnswer: "snow", distractors: ["rain", "wind", "storm"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "Как сказать «нос» по-английски?", correctAnswer: "nose", distractors: ["mouth", "hand", "eye"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "Как сказать «рука» по-английски?", correctAnswer: "hand", distractors: ["foot", "head", "leg"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "✏️\nКак это сказать по-английски?", correctAnswer: "pencil", distractors: ["pen", "paper", "eraser"], tier: .medium, grades: 4...4),
        BankQuestion(prompt: "The boy is eating an apple.\nЧто делает мальчик?", correctAnswer: "ест яблоко", distractors: ["пьёт сок", "играет в мяч", "читает книгу"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "The girl is reading a book.\nЧто делает девочка?", correctAnswer: "читает книгу", distractors: ["пишет письмо", "ест мороженое", "рисует картинку"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "The dog is sleeping.\nЧто делает собака?", correctAnswer: "спит", distractors: ["ест", "бегает", "лает"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "Каким английским словом спрашивают «где»?", correctAnswer: "Where", distractors: ["What", "Who", "When"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "Как переводится слово What?", correctAnswer: "что", distractors: ["кто", "где", "когда"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "Как переводится слово Who?", correctAnswer: "кто", distractors: ["что", "как", "почему"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "Какое слово противоположно слову big?", correctAnswer: "small", distractors: ["tall", "long", "wide"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "Какое слово противоположно слову hot?", correctAnswer: "cold", distractors: ["warm", "wet", "dry"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "Какое слово противоположно слову day?", correctAnswer: "night", distractors: ["morning", "noon", "evening"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "Какое местоимение используют, когда говорят о мальчике (Дани)?", correctAnswer: "he", distractors: ["she", "it", "we"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "Какое местоимение используют, когда говорят о девочке (Рут)?", correctAnswer: "she", distractors: ["he", "it", "they"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "Какое местоимение используют, когда говорят о столе?", correctAnswer: "it", distractors: ["he", "she", "you"], tier: .medium, grades: 5...5),
        BankQuestion(prompt: "Выберите правильную форму:\nEvery day Dan ___ to school.", correctAnswer: "walks", distractors: ["walking", "is walk", "walk"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Выберите правильную форму:\nLook! The baby ___ now.", correctAnswer: "is crying", distractors: ["cries", "cry", "crying"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Выберите правильную форму:\nShe ___ TV every evening.", correctAnswer: "watches", distractors: ["watching", "is watch", "watch"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Выберите правильную форму:\nRight now the children ___ in the park.", correctAnswer: "are playing", distractors: ["plays", "is playing", "played"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Книга лежит на столе.\nThe book is ___ the table.", correctAnswer: "on", distractors: ["in", "under", "at"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Кошка под кроватью.\nThe cat is ___ the bed.", correctAnswer: "under", distractors: ["on", "in", "next"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Мяч внутри коробки.\nThe ball is ___ the box.", correctAnswer: "in", distractors: ["on", "under", "at"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Какая форма множественного числа у слова child?", correctAnswer: "children", distractors: ["childs", "childes", "childrens"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Какая форма множественного числа у слова foot?", correctAnswer: "feet", distractors: ["foots", "feets", "footes"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Какая форма множественного числа у слова mouse?", correctAnswer: "mice", distractors: ["mouses", "mices", "meese"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Tom has a red bike. He rides it to school every day.\nКакого цвета велосипед Тома?", correctAnswer: "красный", distractors: ["синий", "зелёный", "жёлтый"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "Anna lives in Haifa. She has two cats.\nСколько кошек у Анны?", correctAnswer: "две", distractors: ["одна", "три", "четыре"], tier: .hard, grades: 6...6),
        BankQuestion(prompt: "🦓\nКак это сказать по-английски?", correctAnswer: "zebra", distractors: ["horse", "cow", "donkey"], grades: 3...4),
        BankQuestion(prompt: "🦒\nКак это сказать по-английски?", correctAnswer: "giraffe", distractors: ["elephant", "horse", "camel"], grades: 3...4),
        BankQuestion(prompt: "🐒\nКак это сказать по-английски?", correctAnswer: "monkey", distractors: ["bear", "tiger", "lion"], grades: 3...4),
        BankQuestion(prompt: "🐻\nКак это сказать по-английски?", correctAnswer: "bear", distractors: ["wolf", "fox", "dog"], grades: 3...4),
        BankQuestion(prompt: "🐺\nКак это сказать по-английски?", correctAnswer: "wolf", distractors: ["dog", "fox", "bear"], grades: 3...4),
        BankQuestion(prompt: "🐰\nКак это сказать по-английски?", correctAnswer: "rabbit", distractors: ["mouse", "hamster", "fox"], grades: 3...4),
        BankQuestion(prompt: "🐭\nКак это сказать по-английски?", correctAnswer: "mouse", distractors: ["rabbit", "rat", "cat"], grades: 3...4),
        BankQuestion(prompt: "🐢\nКак это сказать по-английски?", correctAnswer: "turtle", distractors: ["snake", "frog", "fish"], grades: 3...4),
        BankQuestion(prompt: "🐸\nКак это сказать по-английски?", correctAnswer: "frog", distractors: ["fish", "turtle", "lizard"], grades: 3...4),
        BankQuestion(prompt: "🐝\nКак это сказать по-английски?", correctAnswer: "bee", distractors: ["fly", "ant", "butterfly"], grades: 3...4),
        BankQuestion(prompt: "🦊\nКак это сказать по-английски?", correctAnswer: "fox", distractors: ["wolf", "dog", "cat"], grades: 3...4),
        BankQuestion(prompt: "🦄\nКак это сказать по-английски?", correctAnswer: "unicorn", distractors: ["horse", "dragon", "pony"], grades: 3...4),
        BankQuestion(prompt: "🐬\nКак это сказать по-английски?", correctAnswer: "dolphin", distractors: ["whale", "fish", "shark"], grades: 3...4),
        BankQuestion(prompt: "🦈\nКак это сказать по-английски?", correctAnswer: "shark", distractors: ["whale", "fish", "dolphin"], grades: 3...4),
        BankQuestion(prompt: "🐢\nКак сказать «медленный» по-английски?", correctAnswer: "slow", distractors: ["fast", "small", "old"], grades: 3...4),
        BankQuestion(prompt: "🔴\nКакой это цвет по-английски?", correctAnswer: "red", distractors: ["blue", "yellow", "pink"], grades: 3...4),
        BankQuestion(prompt: "🔵\nКакой это цвет по-английски?", correctAnswer: "blue", distractors: ["red", "green", "purple"], grades: 3...4),
        BankQuestion(prompt: "🟢\nКакой это цвет по-английски?", correctAnswer: "green", distractors: ["yellow", "blue", "brown"], grades: 3...4),
        BankQuestion(prompt: "🟡\nКакой это цвет по-английски?", correctAnswer: "yellow", distractors: ["orange", "gold", "white"], grades: 3...4),
        BankQuestion(prompt: "🟠\nКакой это цвет по-английски?", correctAnswer: "orange", distractors: ["yellow", "red", "brown"], grades: 3...4),
        BankQuestion(prompt: "🟣\nКакой это цвет по-английски?", correctAnswer: "purple", distractors: ["pink", "blue", "green"], grades: 3...4),
        BankQuestion(prompt: "⚫\nКакой это цвет по-английски?", correctAnswer: "black", distractors: ["gray", "brown", "dark"], grades: 3...4),
        BankQuestion(prompt: "⚪\nКакой это цвет по-английски?", correctAnswer: "white", distractors: ["gray", "silver", "light"], grades: 3...4),
        BankQuestion(prompt: "1\nКак сказать это число по-английски?", correctAnswer: "one", distractors: ["two", "three", "four"], grades: 3...4),
        BankQuestion(prompt: "2\nКак сказать это число по-английски?", correctAnswer: "two", distractors: ["three", "one", "five"], grades: 3...4),
        BankQuestion(prompt: "3\nКак сказать это число по-английски?", correctAnswer: "three", distractors: ["thirteen", "two", "four"], grades: 3...4),
        BankQuestion(prompt: "4\nКак сказать это число по-английски?", correctAnswer: "four", distractors: ["five", "fourteen", "forty"], grades: 3...4),
        BankQuestion(prompt: "5\nКак сказать это число по-английски?", correctAnswer: "five", distractors: ["four", "fifteen", "six"], grades: 3...4),
        BankQuestion(prompt: "10\nКак сказать это число по-английски?", correctAnswer: "ten", distractors: ["twenty", "tin", "eleven"], grades: 3...4),
        BankQuestion(prompt: "«Папа» — как это по-английски?", correctAnswer: "father", distractors: ["mother", "brother", "sister"], grades: 3...4),
        BankQuestion(prompt: "«Мама» — как это по-английски?", correctAnswer: "mother", distractors: ["father", "sister", "aunt"], grades: 3...4),
        BankQuestion(prompt: "«Брат» — как это по-английски?", correctAnswer: "brother", distractors: ["sister", "father", "uncle"], grades: 3...4),
        BankQuestion(prompt: "«Сестра» — как это по-английски?", correctAnswer: "sister", distractors: ["brother", "mother", "aunt"], grades: 3...4),
        BankQuestion(prompt: "«Дедушка» — как это по-английски?", correctAnswer: "grandfather", distractors: ["father", "uncle", "grandson"], grades: 3...4),
        BankQuestion(prompt: "«Бабушка» — как это по-английски?", correctAnswer: "grandmother", distractors: ["mother", "aunt", "granddaughter"], grades: 3...4),
        BankQuestion(prompt: "«Бегать» — как это по-английски?", correctAnswer: "run", distractors: ["jump", "walk", "swim"], grades: 3...5),
        BankQuestion(prompt: "«Прыгать» — как это по-английски?", correctAnswer: "jump", distractors: ["run", "fly", "climb"], grades: 3...5),
        BankQuestion(prompt: "«Кушать» — как это по-английски?", correctAnswer: "eat", distractors: ["drink", "sleep", "cook"], grades: 3...5),
        BankQuestion(prompt: "«Спать» — как это по-английски?", correctAnswer: "sleep", distractors: ["eat", "play", "rest"], grades: 3...5),
        BankQuestion(prompt: "«Читать» — как это по-английски?", correctAnswer: "read", distractors: ["write", "look", "listen"], grades: 3...5),
        BankQuestion(prompt: "«Писать» — как это по-английски?", correctAnswer: "write", distractors: ["read", "draw", "speak"], grades: 3...5),
        BankQuestion(prompt: "«Играть» — как это по-английски?", correctAnswer: "play", distractors: ["work", "study", "sleep"], grades: 3...5),
        BankQuestion(prompt: "«Видеть» — как это по-английски?", correctAnswer: "see", distractors: ["hear", "look", "watch"], grades: 3...5),
        BankQuestion(prompt: "«Слышать» — как это по-английски?", correctAnswer: "hear", distractors: ["see", "say", "listen"], grades: 3...5),
        BankQuestion(prompt: "«Говорить» — как это по-английски?", correctAnswer: "speak", distractors: ["write", "listen", "sing"], grades: 3...5),
        BankQuestion(prompt: "«Воскресенье» — как это по-английски?", correctAnswer: "Sunday", distractors: ["Monday", "Saturday", "Friday"], grades: 3...5),
        BankQuestion(prompt: "«Понедельник» — как это по-английски?", correctAnswer: "Monday", distractors: ["Sunday", "Tuesday", "Friday"], grades: 3...5),
        BankQuestion(prompt: "«Вторник» — как это по-английски?", correctAnswer: "Tuesday", distractors: ["Wednesday", "Monday", "Thursday"], grades: 3...5),
        BankQuestion(prompt: "«Среда» — как это по-английски?", correctAnswer: "Wednesday", distractors: ["Tuesday", "Thursday", "Sunday"], grades: 3...5),
        BankQuestion(prompt: "«Четверг» — как это по-английски?", correctAnswer: "Thursday", distractors: ["Friday", "Wednesday", "Sunday"], grades: 3...5),
        BankQuestion(prompt: "«Пятница» — как это по-английски?", correctAnswer: "Friday", distractors: ["Saturday", "Thursday", "Sunday"], grades: 3...5),
        BankQuestion(prompt: "«Суббота» — как это по-английски?", correctAnswer: "Saturday", distractors: ["Sunday", "Friday", "Monday"], grades: 3...5),
        BankQuestion(prompt: "🌧\n«Дождь» — как это по-английски?", correctAnswer: "rain", distractors: ["snow", "wind", "cloud"], grades: 3...5),
        BankQuestion(prompt: "❄️\n«Снег» — как это по-английски?", correctAnswer: "snow", distractors: ["ice", "rain", "cold"], grades: 3...5),
        BankQuestion(prompt: "🌬\n«Ветер» — как это по-английски?", correctAnswer: "wind", distractors: ["rain", "storm", "weather"], grades: 3...5),
        BankQuestion(prompt: "☁️\n«Облако» — как это по-английски?", correctAnswer: "cloud", distractors: ["sky", "fog", "smoke"], grades: 3...5),
        BankQuestion(prompt: "⛈\n«Буря» — как это по-английски?", correctAnswer: "storm", distractors: ["rain", "thunder", "wind"], grades: 3...5),
        BankQuestion(prompt: "«Голова» — как это по-английски?", correctAnswer: "head", distractors: ["hand", "neck", "hair"], grades: 3...4),
        BankQuestion(prompt: "«Нос» — как это по-английски?", correctAnswer: "nose", distractors: ["mouth", "ear", "eye"], grades: 3...4),
        BankQuestion(prompt: "«Рот» — как это по-английски?", correctAnswer: "mouth", distractors: ["nose", "lip", "tongue"], grades: 3...4),
        BankQuestion(prompt: "«Ухо» — как это по-английски?", correctAnswer: "ear", distractors: ["eye", "nose", "head"], grades: 3...4),
        BankQuestion(prompt: "«Нога» — как это по-английски?", correctAnswer: "leg", distractors: ["hand", "arm", "knee"], grades: 3...4),
        BankQuestion(prompt: "«Кисть руки» — как это по-английски?", correctAnswer: "hand", distractors: ["foot", "shoulder", "finger"], grades: 3...4),
        BankQuestion(prompt: "🧀\n«Сыр» — как это по-английски?", correctAnswer: "cheese", distractors: ["butter", "milk", "yogurt"], grades: 3...4),
        BankQuestion(prompt: "🍕\n«Пицца» — как это по-английски?", correctAnswer: "pizza", distractors: ["pasta", "bread", "burger"], grades: 3...4),
        BankQuestion(prompt: "🍔\n«Гамбургер» — как это по-английски?", correctAnswer: "burger", distractors: ["pizza", "hotdog", "fries"], grades: 3...4),
        BankQuestion(prompt: "🍌\n«Банан» — как это по-английски?", correctAnswer: "banana", distractors: ["apple", "lemon", "mango"], grades: 3...4),
        BankQuestion(prompt: "🍊\n«Апельсин» — как это по-английски?", correctAnswer: "orange", distractors: ["lemon", "apple", "fruit"], grades: 3...4),
        BankQuestion(prompt: "🍓\n«Клубника» — как это по-английски?", correctAnswer: "strawberry", distractors: ["raspberry", "cherry", "apple"], grades: 3...4),
        BankQuestion(prompt: "🍉\n«Арбуз» — как это по-английски?", correctAnswer: "watermelon", distractors: ["melon", "pumpkin", "apple"], grades: 3...4),
        BankQuestion(prompt: "🍇\n«Виноград» — как это по-английски?", correctAnswer: "grapes", distractors: ["berries", "cherry", "plum"], grades: 3...4),
        BankQuestion(prompt: "«Учитель» — как это по-английски?", correctAnswer: "teacher", distractors: ["student", "doctor", "parent"], grades: 3...5),
        BankQuestion(prompt: "«Ученик» — как это по-английски?", correctAnswer: "student", distractors: ["teacher", "kid", "child"], grades: 3...5),
        BankQuestion(prompt: "«Школа» — как это по-английски?", correctAnswer: "school", distractors: ["college", "class", "home"], grades: 3...5),
        BankQuestion(prompt: "«Класс» — как это по-английски?", correctAnswer: "class", distractors: ["school", "room", "lesson"], grades: 3...5),
        BankQuestion(prompt: "«Карандаш» — как это по-английски?", correctAnswer: "pencil", distractors: ["pen", "paper", "eraser"], grades: 3...5),
        BankQuestion(prompt: "«Ручка» — как это по-английски?", correctAnswer: "pen", distractors: ["pencil", "marker", "ink"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «dog»?", correctAnswer: "собака", distractors: ["кошка", "кролик", "лошадь"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «cat»?", correctAnswer: "кошка", distractors: ["собака", "лев", "тигр"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «house»?", correctAnswer: "дом", distractors: ["квартира", "вилла", "комната"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «star»?", correctAnswer: "звезда", distractors: ["солнце", "луна", "облако"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «water»?", correctAnswer: "вода", distractors: ["молоко", "сок", "чай"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «sun»?", correctAnswer: "солнце", distractors: ["луна", "звезда", "свет"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «red»?", correctAnswer: "красный", distractors: ["синий", "зелёный", "розовый"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «happy»?", correctAnswer: "радостный", distractors: ["грустный", "сердитый", "усталый"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «big»?", correctAnswer: "большой", distractors: ["маленький", "длинный", "широкий"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «small»?", correctAnswer: "маленький", distractors: ["большой", "узкий", "короткий"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «fast»?", correctAnswer: "быстрый", distractors: ["медленный", "сильный", "длинный"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «cold»?", correctAnswer: "холодный", distractors: ["горячий", "приятный", "мокрый"], grades: 3...5),
        BankQuestion(prompt: "Что означает слово «hot»?", correctAnswer: "горячий", distractors: ["холодный", "приятный", "ветреный"], grades: 3...5),
        BankQuestion(prompt: "🐮\nКак это сказать по-английски?", correctAnswer: "cow", distractors: ["goat", "sheep", "pig"], grades: 3...4),
        BankQuestion(prompt: "🐷\nКак это сказать по-английски?", correctAnswer: "pig", distractors: ["cow", "dog", "sheep"], grades: 3...4),
        BankQuestion(prompt: "🐴\nКак это сказать по-английски?", correctAnswer: "horse", distractors: ["donkey", "cow", "goat"], grades: 3...4),
        BankQuestion(prompt: "🐑\nКак это сказать по-английски?", correctAnswer: "sheep", distractors: ["goat", "cow", "pig"], grades: 3...4),
        BankQuestion(prompt: "🐔\nКак это сказать по-английски?", correctAnswer: "chicken", distractors: ["duck", "bird", "cow"], grades: 3...4),
        BankQuestion(prompt: "🦆\nКак это сказать по-английски?", correctAnswer: "duck", distractors: ["chicken", "bird", "fish"], grades: 3...4),
        BankQuestion(prompt: "🍌\nКак по-английски «банан»?", correctAnswer: "banana", distractors: ["apple", "lemon", "orange"], grades: 3...5),
        BankQuestion(prompt: "🥚\nКак по-английски «яйцо»?", correctAnswer: "egg", distractors: ["milk", "bread", "cheese"], grades: 3...5),
        BankQuestion(prompt: "🍪\nКак по-английски «печенье»?", correctAnswer: "cookie", distractors: ["cake", "candy", "bread"], grades: 3...5),
        BankQuestion(prompt: "🍦\nКак по-английски «мороженое»?", correctAnswer: "ice cream", distractors: ["cake", "candy", "milk"], grades: 3...5),
        BankQuestion(prompt: "🟤\nКак называется этот цвет по-английски?", correctAnswer: "brown", distractors: ["black", "gray", "orange"], grades: 3...4),
        BankQuestion(prompt: "🩷\nКак называется этот цвет по-английски?", correctAnswer: "pink", distractors: ["red", "purple", "orange"], grades: 3...4),
        BankQuestion(prompt: "🦶\nКак по-английски «ступня»?", correctAnswer: "foot", distractors: ["leg", "hand", "arm"], grades: 3...5),
        BankQuestion(prompt: "💪\nКак по-английски «рука»?", correctAnswer: "arm", distractors: ["leg", "foot", "head"], grades: 3...5),
        BankQuestion(prompt: "🦷\nКак по-английски «зуб»?", correctAnswer: "tooth", distractors: ["nose", "mouth", "ear"], grades: 3...5),
        BankQuestion(prompt: "👶\nКак по-английски «малыш»?", correctAnswer: "baby", distractors: ["boy", "girl", "man"], grades: 3...5),
        BankQuestion(prompt: "6\nКак сказать это число по-английски?", correctAnswer: "six", distractors: ["seven", "sixteen", "sixty"], grades: 3...4),
        BankQuestion(prompt: "7\nКак сказать это число по-английски?", correctAnswer: "seven", distractors: ["six", "seventy", "eleven"], grades: 3...4),
        BankQuestion(prompt: "8\nКак сказать это число по-английски?", correctAnswer: "eight", distractors: ["nine", "eighteen", "eighty"], grades: 3...4),
        BankQuestion(prompt: "9\nКак сказать это число по-английски?", correctAnswer: "nine", distractors: ["eight", "ten", "ninety"], grades: 3...4),
        BankQuestion(prompt: "🎒\nКак по-английски «сумка»?", correctAnswer: "bag", distractors: ["book", "box", "desk"], grades: 3...5),
        BankQuestion(prompt: "✂️\nКак по-английски «ножницы»?", correctAnswer: "scissors", distractors: ["pencil", "ruler", "glue"], grades: 3...5),
        BankQuestion(prompt: "🏔️\nКак по-английски «гора»?", correctAnswer: "mountain", distractors: ["river", "sea", "hill"], grades: 3...5),
        BankQuestion(prompt: "🌊\nКак по-английски «море»?", correctAnswer: "sea", distractors: ["lake", "river", "rain"], grades: 3...5),
        BankQuestion(prompt: "🍃\nКак по-английски «лист дерева»?", correctAnswer: "leaf", distractors: ["tree", "grass", "flower"], grades: 3...5),
        BankQuestion(prompt: "🚶\nКак по-английски «идти пешком»?", correctAnswer: "walk", distractors: ["run", "jump", "sit"], grades: 3...5),
        BankQuestion(prompt: "🥤\nКак по-английски «пить»?", correctAnswer: "drink", distractors: ["eat", "cook", "wash"], grades: 3...5),
        BankQuestion(prompt: "👟\nКак по-английски «ботинок»?", correctAnswer: "shoe", distractors: ["hat", "shirt", "sock"], grades: 3...5),
        BankQuestion(prompt: "🧢\nКак по-английски «шапка»?", correctAnswer: "hat", distractors: ["shoe", "shirt", "coat"], grades: 3...5),
        BankQuestion(prompt: "👩\nКак по-английски «мама»?", correctAnswer: "mother", distractors: ["father", "sister", "grandma"], grades: 3...4),
        BankQuestion(prompt: "👨\nКак по-английски «папа»?", correctAnswer: "father", distractors: ["mother", "brother", "uncle"], grades: 3...4),
        BankQuestion(prompt: "👵\nКак по-английски «бабушка»?", correctAnswer: "grandma", distractors: ["mother", "aunt", "sister"], grades: 3...4),
        BankQuestion(prompt: "👦\nКак по-английски «брат»?", correctAnswer: "brother", distractors: ["sister", "father", "friend"], grades: 3...4),
        BankQuestion(prompt: "😀\nКак по-английски «весёлый»?", correctAnswer: "happy", distractors: ["sad", "angry", "tired"], grades: 3...4),
        BankQuestion(prompt: "😢\nКак по-английски «грустный»?", correctAnswer: "sad", distractors: ["happy", "scared", "hungry"], grades: 3...4),
        BankQuestion(prompt: "😠\nКак по-английски «сердитый»?", correctAnswer: "angry", distractors: ["happy", "sleepy", "sad"], grades: 3...4),
        BankQuestion(prompt: "😴\nКак по-английски «усталый»?", correctAnswer: "tired", distractors: ["happy", "hungry", "angry"], grades: 3...4),
        BankQuestion(prompt: "☀️\nКак по-английски «солнце»?", correctAnswer: "sun", distractors: ["rain", "cloud", "wind"], grades: 3...4),
        BankQuestion(prompt: "🌧️\nКак по-английски «дождь»?", correctAnswer: "rain", distractors: ["sun", "snow", "cloud"], grades: 3...4),
        BankQuestion(prompt: "❄️\nКак по-английски «снег»?", correctAnswer: "snow", distractors: ["rain", "sun", "wind"], grades: 3...4),
        BankQuestion(prompt: "☁️\nКак по-английски «облако»?", correctAnswer: "cloud", distractors: ["sun", "rain", "snow"], grades: 3...4),
        BankQuestion(prompt: "🛏️\nКак по-английски «спальня»?", correctAnswer: "bedroom", distractors: ["kitchen", "bathroom", "garden"], grades: 3...5),
        BankQuestion(prompt: "🍳\nКак по-английски «кухня»?", correctAnswer: "kitchen", distractors: ["bedroom", "bathroom", "garden"], grades: 3...5),
        BankQuestion(prompt: "🛁\nКак по-английски «ванная комната»?", correctAnswer: "bathroom", distractors: ["kitchen", "bedroom", "garden"], grades: 3...5),
        BankQuestion(prompt: "🚪\nКак по-английски «дверь»?", correctAnswer: "door", distractors: ["window", "wall", "floor"], grades: 3...5),
        BankQuestion(prompt: "👮\nКак по-английски «полиция»?", correctAnswer: "police", distractors: ["doctor", "teacher", "farmer"], grades: 3...5),
        BankQuestion(prompt: "👨‍🍳\nКак по-английски «повар»?", correctAnswer: "cook", distractors: ["doctor", "teacher", "pilot"], grades: 3...5),
        BankQuestion(prompt: "👩‍⚕️\nКак по-английски «врач»?", correctAnswer: "doctor", distractors: ["teacher", "police", "cook"], grades: 3...5),
        BankQuestion(prompt: "🧑‍🚒\nКак по-английски «пожарный»?", correctAnswer: "firefighter", distractors: ["doctor", "teacher", "pilot"], grades: 3...5),
        BankQuestion(prompt: "👕\nКак по-английски «рубашка»?", correctAnswer: "shirt", distractors: ["pants", "socks", "dress"], grades: 3...5),
        BankQuestion(prompt: "👖\nКак по-английски «штаны»?", correctAnswer: "pants", distractors: ["shirt", "socks", "coat"], grades: 3...5),
        BankQuestion(prompt: "🧦\nКак по-английски «носки»?", correctAnswer: "socks", distractors: ["shoes", "pants", "gloves"], grades: 3...5),
        BankQuestion(prompt: "🧥\nКак по-английски «пальто»?", correctAnswer: "coat", distractors: ["shirt", "hat", "socks"], grades: 3...5),
        BankQuestion(prompt: "🥕\nКак по-английски «морковь»?", correctAnswer: "carrot", distractors: ["tomato", "potato", "onion"], grades: 3...5),
        BankQuestion(prompt: "🍅\nКак по-английски «помидор»?", correctAnswer: "tomato", distractors: ["carrot", "potato", "pepper"], grades: 3...5),
        BankQuestion(prompt: "🥔\nКак по-английски «картошка»?", correctAnswer: "potato", distractors: ["tomato", "carrot", "onion"], grades: 3...5),
        BankQuestion(prompt: "🌽\nКак по-английски «кукуруза»?", correctAnswer: "corn", distractors: ["carrot", "tomato", "potato"], grades: 3...5),
        BankQuestion(prompt: "🐶\nКак по-английски «собака»?", correctAnswer: "dog", distractors: ["cat", "cow", "pig"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐱\nКак по-английски «кошка»?", correctAnswer: "cat", distractors: ["dog", "fish", "bird"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐟\nКак по-английски «рыба»?", correctAnswer: "fish", distractors: ["frog", "duck", "bird"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐦\nКак по-английски «птица»?", correctAnswer: "bird", distractors: ["fish", "bee", "cat"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐄\nКак по-английски «корова»?", correctAnswer: "cow", distractors: ["pig", "dog", "goat"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐷\nКак по-английски «свинья»?", correctAnswer: "pig", distractors: ["cow", "dog", "cat"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐭\nКак по-английски «мышь»?", correctAnswer: "mouse", distractors: ["cat", "frog", "bird"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐰\nКак по-английски «кролик»?", correctAnswer: "rabbit", distractors: ["mouse", "cat", "dog"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍎\nКак по-английски «яблоко»?", correctAnswer: "apple", distractors: ["banana", "orange", "lemon"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍊\nКак по-английски «апельсин»?", correctAnswer: "orange", distractors: ["apple", "lemon", "banana"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍋\nКак по-английски «лимон»?", correctAnswer: "lemon", distractors: ["orange", "apple", "grape"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍇\nКак по-английски «виноград»?", correctAnswer: "grapes", distractors: ["apple", "banana", "cherry"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍓\nКак по-английски «клубника»?", correctAnswer: "strawberry", distractors: ["cherry", "apple", "grape"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🥛\nКак по-английски «молоко»?", correctAnswer: "milk", distractors: ["water", "juice", "tea"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🍞\nКак по-английски «хлеб»?", correctAnswer: "bread", distractors: ["cake", "rice", "egg"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🧀\nКак по-английски «сыр»?", correctAnswer: "cheese", distractors: ["egg", "milk", "bread"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "💧\nКак по-английски «вода»?", correctAnswer: "water", distractors: ["milk", "juice", "fire"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🟡\nКак называется этот цвет по-английски?", correctAnswer: "yellow", distractors: ["green", "red", "orange"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "⚫\nКак называется этот цвет по-английски?", correctAnswer: "black", distractors: ["white", "blue", "brown"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "⚪\nКак называется этот цвет по-английски?", correctAnswer: "white", distractors: ["black", "yellow", "red"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🖐️\nКак по-английски «кисть руки»?", correctAnswer: "hand", distractors: ["foot", "head", "leg"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "👁️\nКак по-английски «глаз»?", correctAnswer: "eye", distractors: ["ear", "nose", "mouth"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "👂\nКак по-английски «ухо»?", correctAnswer: "ear", distractors: ["eye", "nose", "hand"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "👃\nКак по-английски «нос»?", correctAnswer: "nose", distractors: ["ear", "eye", "mouth"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "👄\nКак по-английски «рот»?", correctAnswer: "mouth", distractors: ["nose", "ear", "eye"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌙\nКак по-английски «луна»?", correctAnswer: "moon", distractors: ["sun", "star", "sky"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "⭐\nКак по-английски «звезда»?", correctAnswer: "star", distractors: ["moon", "sun", "cloud"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌳\nКак по-английски «дерево»?", correctAnswer: "tree", distractors: ["flower", "grass", "leaf"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🌸\nКак по-английски «цветок»?", correctAnswer: "flower", distractors: ["tree", "grass", "leaf"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🏠\nКак по-английски «дом»?", correctAnswer: "house", distractors: ["door", "window", "room"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🚗\nКак по-английски «машина»?", correctAnswer: "car", distractors: ["bus", "train", "bike"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🚌\nКак по-английски «автобус»?", correctAnswer: "bus", distractors: ["car", "train", "boat"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "✈️\nКак по-английски «самолёт»?", correctAnswer: "airplane", distractors: ["car", "boat", "train"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "📖\nКак по-английски «книга»?", correctAnswer: "book", distractors: ["pen", "bag", "desk"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "✏️\nКак по-английски «карандаш»?", correctAnswer: "pencil", distractors: ["book", "bag", "ruler"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "Как сказать число 1 по-английски?", correctAnswer: "one", distractors: ["two", "three", "four"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "Как сказать число 2 по-английски?", correctAnswer: "two", distractors: ["one", "three", "five"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "Как сказать число 3 по-английски?", correctAnswer: "three", distractors: ["two", "four", "six"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "Как сказать число 4 по-английски?", correctAnswer: "four", distractors: ["three", "five", "two"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "Как сказать число 5 по-английски?", correctAnswer: "five", distractors: ["four", "six", "three"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "Как по-английски «привет»?", correctAnswer: "hello", distractors: ["goodbye", "thanks", "please"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🐴\nКак по-английски «лошадь»?", correctAnswer: "horse", distractors: ["cow", "goat", "sheep"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐑\nКак по-английски «овца»?", correctAnswer: "sheep", distractors: ["goat", "cow", "horse"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦁\nКак по-английски «лев»?", correctAnswer: "lion", distractors: ["tiger", "bear", "wolf"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐯\nКак по-английски «тигр»?", correctAnswer: "tiger", distractors: ["lion", "bear", "fox"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐻\nКак по-английски «медведь»?", correctAnswer: "bear", distractors: ["lion", "wolf", "fox"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐘\nКак по-английски «слон»?", correctAnswer: "elephant", distractors: ["giraffe", "lion", "zebra"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦒\nКак по-английски «жираф»?", correctAnswer: "giraffe", distractors: ["elephant", "zebra", "horse"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐒\nКак по-английски «мартышка»?", correctAnswer: "monkey", distractors: ["bear", "lion", "fox"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐸\nКак по-английски «лягушка»?", correctAnswer: "frog", distractors: ["fish", "snake", "turtle"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐝\nКак по-английски «пчела»?", correctAnswer: "bee", distractors: ["ant", "fly", "bird"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👟\nКак по-английски «ботинки»?", correctAnswer: "shoes", distractors: ["socks", "hat", "shirt"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как по-английски «брат»?", correctAnswer: "brother", distractors: ["sister", "father", "mother"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как по-английски «сестра»?", correctAnswer: "sister", distractors: ["brother", "mother", "father"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что противоположно слову big по-английски?", correctAnswer: "small", distractors: ["tall", "long", "wide"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что противоположно слову hot по-английски?", correctAnswer: "cold", distractors: ["warm", "wet", "dry"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что противоположно слову up по-английски?", correctAnswer: "down", distractors: ["left", "right", "top"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что противоположно слову day по-английски?", correctAnswer: "night", distractors: ["noon", "week", "hour"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что противоположно слову open по-английски?", correctAnswer: "close", distractors: ["push", "pull", "lock"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что противоположно слову happy по-английски?", correctAnswer: "sad", distractors: ["mad", "tired", "shy"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что противоположно слову fast по-английски?", correctAnswer: "slow", distractors: ["quick", "soft", "loud"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что противоположно слову new по-английски?", correctAnswer: "old", distractors: ["young", "fresh", "clean"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как сказать число 6 по-английски?", correctAnswer: "six", distractors: ["seven", "five", "eight"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как сказать число 7 по-английски?", correctAnswer: "seven", distractors: ["six", "eight", "nine"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как сказать число 8 по-английски?", correctAnswer: "eight", distractors: ["seven", "nine", "six"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как сказать число 9 по-английски?", correctAnswer: "nine", distractors: ["eight", "ten", "seven"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как сказать число 10 по-английски?", correctAnswer: "ten", distractors: ["nine", "eight", "seven"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🪑\nКак по-английски «стул»?", correctAnswer: "chair", distractors: ["table", "bed", "door"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛏️\nКак по-английски «кровать»?", correctAnswer: "bed", distractors: ["chair", "table", "sofa"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🪟\nКак по-английски «окно»?", correctAnswer: "window", distractors: ["door", "wall", "floor"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚲\nКак по-английски «велосипед»?", correctAnswer: "bicycle", distractors: ["car", "bus", "train"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚂\nКак по-английски «поезд»?", correctAnswer: "train", distractors: ["bus", "car", "boat"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⛵\nКак по-английски «лодка»?", correctAnswer: "boat", distractors: ["car", "train", "plane"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как по-английски «спасибо»?", correctAnswer: "thank you", distractors: ["please", "hello", "sorry"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как по-английски «пожалуйста», когда о чём-то просишь?", correctAnswer: "please", distractors: ["thanks", "sorry", "hello"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как по-английски «да»?", correctAnswer: "yes", distractors: ["no", "maybe", "now"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Как по-английски «нет»?", correctAnswer: "no", distractors: ["yes", "maybe", "never"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌈\nКак по-английски «радуга»?", correctAnswer: "rainbow", distractors: ["cloud", "rain", "sky"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐔\nКак по-английски «курица»?", correctAnswer: "chicken", distractors: ["duck", "bird", "goose"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦆\nКак по-английски «утка»?", correctAnswer: "duck", distractors: ["chicken", "bird", "goose"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍰\nКак по-английски «торт»?", correctAnswer: "cake", distractors: ["bread", "cookie", "pie"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что противоположно слову good по-английски?", correctAnswer: "bad", distractors: ["nice", "kind", "fine"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "Что противоположно слову clean по-английски?", correctAnswer: "dirty", distractors: ["wet", "old", "dark"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что противоположно слову full по-английски?", correctAnswer: "empty", distractors: ["heavy", "light", "open"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что противоположно слову heavy по-английски?", correctAnswer: "light", distractors: ["full", "soft", "thin"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что противоположно слову strong по-английски?", correctAnswer: "weak", distractors: ["soft", "small", "thin"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что противоположно слову easy по-английски?", correctAnswer: "hard", distractors: ["soft", "slow", "weak"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что противоположно слову first по-английски?", correctAnswer: "last", distractors: ["next", "best", "near"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что противоположно слову near по-английски?", correctAnswer: "far", distractors: ["close", "next", "here"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Что противоположно слову loud по-английски?", correctAnswer: "quiet", distractors: ["proud", "slow", "happy"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как по-английски «бегать»?", correctAnswer: "run", distractors: ["walk", "jump", "swim"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как по-английски «прыгать»?", correctAnswer: "jump", distractors: ["run", "walk", "climb"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как по-английски «плавать»?", correctAnswer: "swim", distractors: ["run", "jump", "fly"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как по-английски «кушать»?", correctAnswer: "eat", distractors: ["drink", "cook", "sleep"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как по-английски «пить»?", correctAnswer: "drink", distractors: ["eat", "cook", "wash"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как по-английски «спать»?", correctAnswer: "sleep", distractors: ["eat", "wake", "rest"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как по-английски «читать»?", correctAnswer: "read", distractors: ["write", "draw", "speak"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как по-английски «писать»?", correctAnswer: "write", distractors: ["read", "draw", "talk"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как по-английски «идти пешком»?", correctAnswer: "walk", distractors: ["run", "jump", "stand"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как будет множественное число слова cat по-английски?", correctAnswer: "cats", distractors: ["cates", "caties", "cat"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Как будет множественное число слова dog по-английски?", correctAnswer: "dogs", distractors: ["doges", "dogies", "dog"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Как будет множественное число слова box по-английски?", correctAnswer: "boxes", distractors: ["boxs", "boxies", "box"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Как будет множественное число слова baby по-английски?", correctAnswer: "babies", distractors: ["babys", "babyes", "baby"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Как будет множественное число слова child по-английски?", correctAnswer: "children", distractors: ["childs", "childes", "childrens"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Как будет множественное число слова mouse по-английски?", correctAnswer: "mice", distractors: ["mouses", "mouse", "mices"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Как будет множественное число слова foot по-английски?", correctAnswer: "feet", distractors: ["foots", "feets", "foot"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Как сказать число 11 по-английски?", correctAnswer: "eleven", distractors: ["twelve", "ten", "seven"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как сказать число 12 по-английски?", correctAnswer: "twelve", distractors: ["eleven", "twenty", "ten"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как сказать число 20 по-английски?", correctAnswer: "twenty", distractors: ["twelve", "thirty", "two"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как по-английски число 100?", correctAnswer: "hundred", distractors: ["thousand", "twenty", "ten"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦋\nКак это будет по-английски?", correctAnswer: "butterfly", distractors: ["bee", "bird", "fly"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐢\nКак это будет по-английски?", correctAnswer: "turtle", distractors: ["frog", "snake", "fish"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐍\nКак это будет по-английски?", correctAnswer: "snake", distractors: ["turtle", "frog", "worm"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦊\nКак это будет по-английски?", correctAnswer: "fox", distractors: ["wolf", "dog", "bear"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐺\nКак это будет по-английски?", correctAnswer: "wolf", distractors: ["fox", "dog", "bear"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦉\nКак это будет по-английски?", correctAnswer: "owl", distractors: ["duck", "bat", "eagle"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐙\nКак это будет по-английски?", correctAnswer: "octopus", distractors: ["fish", "crab", "squid"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦀\nКак это будет по-английски?", correctAnswer: "crab", distractors: ["fish", "octopus", "shrimp"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌽\nКак это будет по-английски?", correctAnswer: "corn", distractors: ["carrot", "potato", "pea"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍉\nКак это будет по-английски?", correctAnswer: "watermelon", distractors: ["grapes", "apple", "orange"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍍\nКак это будет по-английски?", correctAnswer: "pineapple", distractors: ["apple", "mango", "lemon"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧤\nКак это будет по-английски?", correctAnswer: "gloves", distractors: ["socks", "hat", "scarf"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧥\nКак это будет по-английски?", correctAnswer: "coat", distractors: ["shirt", "hat", "dress"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "👗\nКак это будет по-английски?", correctAnswer: "dress", distractors: ["shirt", "coat", "skirt"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как будет «дедушка» по-английски?", correctAnswer: "grandfather", distractors: ["grandmother", "father", "uncle"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как будет «бабушка» по-английски?", correctAnswer: "grandmother", distractors: ["grandfather", "mother", "aunt"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как будет «учитель» по-английски?", correctAnswer: "teacher", distractors: ["student", "doctor", "driver"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как будет «ученик» по-английски?", correctAnswer: "student", distractors: ["teacher", "doctor", "friend"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как будет «врач» по-английски?", correctAnswer: "doctor", distractors: ["teacher", "nurse", "driver"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое множественное число у английского слова tooth?", correctAnswer: "teeth", distractors: ["tooths", "teeths", "tooth"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "Какое английское слово противоположно слову wet (мокрый)?", correctAnswer: "dry", distractors: ["hot", "cold", "clean"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Какое английское слово противоположно слову light (светлый)?", correctAnswer: "dark", distractors: ["white", "bright", "gray"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как будет «зима» по-английски?", correctAnswer: "winter", distractors: ["summer", "spring", "autumn"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как будет «лето» по-английски?", correctAnswer: "summer", distractors: ["winter", "spring", "autumn"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как будет «воскресенье» по-английски?", correctAnswer: "Sunday", distractors: ["Monday", "Friday", "Saturday"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "Как будет «утро» по-английски?", correctAnswer: "morning", distractors: ["evening", "night", "noon"], tier: .hard, grades: 4...6),
    ]
}
