import Foundation

/// 🔬 Science — English (US). Adapted from the `science` lists in QuestionBanks,
/// QuestionBanksExpanded, QuestionBanksWorkflow(2/3) and
/// QuestionBanksCurriculumEnglishScience (Hebrew), aligned to NGSS-style US
/// science (life, earth & space, physical science, engineering) for K–8th grade.
extension EnglishContent {
    static let science: [BankQuestion] = [
        // MARK: From QuestionBanks + QuestionBanksExpanded
        BankQuestion(prompt: "🕷️\nHow many legs does a spider have?", correctAnswer: "8", distractors: ["6", "10", "4"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🌱\nWhere do plants get their energy from?", correctAnswer: "Sunlight", distractors: ["Soil", "Moonlight", "Rainwater"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "📅\nHow many days are in a week?", correctAnswer: "7", distractors: ["5", "6", "8"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌈\nWe remember the rainbow's colors as ROY G BIV. How many colors is that?", correctAnswer: "7", distractors: ["5", "6", "10"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🌈\nIn ROY G BIV, what color does the G stand for?", correctAnswer: "Green", distractors: ["Gray", "Gold", "Grape"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🌈\nWhich color is on the outside edge of a rainbow's arch?", correctAnswer: "Red", distractors: ["Violet", "Green", "Blue"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🎵\nWhich body part do we hear with?", correctAnswer: "Ears", distractors: ["Eyes", "Nose", "Mouth"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍯\nWhich animal makes honey?", correctAnswer: "Bee", distractors: ["Ant", "Fly", "Butterfly"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥤\nWhat does an ice cube do when you drop it into a glass of water?", correctAnswer: "It floats", distractors: ["It sinks to the bottom", "It turns into sand", "It turns into steam"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🤒\nWhat do we use to measure temperature?", correctAnswer: "A thermometer", distractors: ["A scale", "A ruler", "A clock"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦷\nHow many teeth are in a full set of adult teeth?", correctAnswer: "32", distractors: ["20", "24", "40"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🦷\nHow many baby teeth do children usually have?", correctAnswer: "20", distractors: ["10", "32", "50"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "📅\nHow many days are in a year that is not a leap year?", correctAnswer: "365", distractors: ["360", "350", "400"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌙\nAbout how long does it take the Moon to travel once around Earth?", correctAnswer: "About a month", distractors: ["About a day", "About a week", "About a year"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌓\nWhat do we call the Moon's changing shapes that we see during a month?", correctAnswer: "Phases", distractors: ["Seasons", "Eclipses", "Orbits"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⭐\nWhich star is closest to Earth?", correctAnswer: "The Sun", distractors: ["The North Star", "Sirius", "Betelgeuse"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🐠\nWhere do fish live and breathe?", correctAnswer: "In water", distractors: ["In the air", "In the ground", "In trees"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐛\nWhat can a caterpillar turn into?", correctAnswer: "A butterfly", distractors: ["A bee", "A bird", "A spider"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🌋\nWhat hot, melted rock flows out of a volcano?", correctAnswer: "Lava", distractors: ["Water", "Snow", "Sand"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌋\nWhat do we call melted rock while it is still deep under the ground?", correctAnswer: "Magma", distractors: ["Granite", "Sand", "Clay"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "💨\nWhat is air made of?", correctAnswer: "A mix of gases", distractors: ["Liquid water", "Only dust", "Nothing at all"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🌊\nWhat makes most ocean waves?", correctAnswer: "Wind", distractors: ["Fish", "Rocks", "Seaweed"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🏖️\nWhat is beach sand mostly made of?", correctAnswer: "Tiny bits of rock and shell", distractors: ["Salt crystals", "Sugar", "Snow"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪨\nWhat do we call it when wind and water slowly break rocks into smaller pieces?", correctAnswer: "Weathering", distractors: ["Evaporation", "Pollination", "Hibernation"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦷\nWhat is the hard outer layer that covers your teeth called?", correctAnswer: "Enamel", distractors: ["Sugar", "Chalk", "Iron"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔴\nWhich planet is called the Red Planet?", correctAnswer: "Mars", distractors: ["Jupiter", "Saturn", "Venus"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏠\nWhich planet do we live on?", correctAnswer: "Earth", distractors: ["Mars", "Venus", "Jupiter"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪐\nWhich planet is the farthest from the Sun?", correctAnswer: "Neptune", distractors: ["Mercury", "Mars", "Earth"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔥\nWhich planet is the hottest?", correctAnswer: "Venus", distractors: ["Earth", "Mars", "Neptune"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🪐\nWhich planet is the smallest?", correctAnswer: "Mercury", distractors: ["Jupiter", "Saturn", "Earth"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🤔\nWhich organ helps us think?", correctAnswer: "The brain", distractors: ["The heart", "The stomach", "The lungs"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌱\nWhat does a plant need to grow?", correctAnswer: "Water and sunlight", distractors: ["Candy and soda", "Only sand", "Only darkness"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "💧\nAbout how much of Earth's surface is covered by water?", correctAnswer: "About 70%", distractors: ["About 10%", "About 30%", "About 95%"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧊\nAt what temperature does water start to freeze?", correctAnswer: "32°F (0°C)", distractors: ["50°F (10°C)", "72°F (22°C)", "212°F (100°C)"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌡️\nAt what temperature does water boil at sea level?", correctAnswer: "212°F (100°C)", distractors: ["32°F (0°C)", "98°F (37°C)", "122°F (50°C)"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌍\nWhat are the giant, slowly moving pieces of Earth's outer layer called?", correctAnswer: "Tectonic plates", distractors: ["Ocean currents", "Magnets", "Craters"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🦴\nHow many bones are in an adult human body?", correctAnswer: "206", distractors: ["150", "100", "300"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🩸\nWhich organ pumps blood around your body?", correctAnswer: "The heart", distractors: ["The lungs", "The liver", "The brain"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌬️\nWhich gas do we need to breathe in to live?", correctAnswer: "Oxygen", distractors: ["Hydrogen", "Helium", "Carbon dioxide"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "☀️\nAbout how long does sunlight take to reach Earth?", correctAnswer: "About 8 minutes", distractors: ["About 1 second", "About 1 hour", "About 1 day"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🪐\nWhich planet is the biggest in our solar system?", correctAnswer: "Jupiter", distractors: ["Venus", "Mars", "Earth"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌎\nHow many planets are in our solar system?", correctAnswer: "8", distractors: ["7", "9", "10"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📏\nWhich of these is closest to Earth?", correctAnswer: "The Moon", distractors: ["Mars", "Venus", "The Sun"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌳\nWhich gas do plants take in from the air to make their food?", correctAnswer: "Carbon dioxide", distractors: ["Oxygen", "Nitrogen", "Helium"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌳\nWhich gas do plants give off that we need to breathe?", correctAnswer: "Oxygen", distractors: ["Carbon dioxide", "Helium", "Smoke"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐝\nWhen bees carry pollen from flower to flower, what is it called?", correctAnswer: "Pollination", distractors: ["Evaporation", "Hibernation", "Migration"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧊\nWhat is ice like?", correctAnswer: "Cold and hard", distractors: ["Hot and soft", "Warm and runny", "Yellow and smelly"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔥\nWhat three things does a fire need to burn?", correctAnswer: "Fuel, heat, and oxygen", distractors: ["Water, ice, and sand", "Rain, wind, and snow", "Only cold air"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🌊\nWhat mainly causes the ocean tides?", correctAnswer: "The Moon's gravity", distractors: ["The wind", "Fish swimming", "Rain"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐞\nHow many legs does an insect have?", correctAnswer: "6", distractors: ["4", "8", "10"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🕷️\nA spider has 8 legs. Which animal group does it belong to?", correctAnswer: "Arachnids", distractors: ["Insects", "Reptiles", "Mammals"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐍\nWhat kind of animal is a snake?", correctAnswer: "A reptile", distractors: ["A mammal", "A bird", "A fish"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐬\nWhat kind of animal is a dolphin?", correctAnswer: "A mammal", distractors: ["A fish", "A reptile", "A bird"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🦇\nWhat kind of animal is a bat?", correctAnswer: "A mammal", distractors: ["A bird", "An insect", "A reptile"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🐢\nWhat kind of animal is a turtle?", correctAnswer: "A reptile", distractors: ["A mammal", "A fish", "A bird"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌱\nWhich part of a plant soaks up water from the soil?", correctAnswer: "The roots", distractors: ["The flower", "The fruit", "The bark"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "☀️\nWhich part of a plant uses sunlight to make food?", correctAnswer: "The leaves", distractors: ["The roots", "The flower", "The soil"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🐝\nHow many eyes does a honeybee have?", correctAnswer: "5", distractors: ["2", "3", "8"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🐙\nHow many hearts does an octopus have?", correctAnswer: "3", distractors: ["1", "2", "5"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🌍\nWhat is the tallest animal on land?", correctAnswer: "Giraffe", distractors: ["Elephant", "Horse", "Human"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌊\nWhat is the biggest animal in the world?", correctAnswer: "Blue whale", distractors: ["Elephant", "Shark", "Giraffe"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🏁\nWhat is the fastest animal on land?", correctAnswer: "Cheetah", distractors: ["Horse", "Tiger", "Lion"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "⚡\nWhat do we call a storm with thunder and lightning?", correctAnswer: "A thunderstorm", distractors: ["A sandstorm", "A heat wave", "A drizzle"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌫️\nWhat is fog?", correctAnswer: "A cloud close to the ground", distractors: ["Light rain", "Dust", "Smoke"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌊\nWhat is a giant ocean wave, often caused by an earthquake, called?", correctAnswer: "A tsunami", distractors: ["A tornado", "A blizzard", "Fog"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "⛏️\nWhat is the hardest natural material?", correctAnswer: "Diamond", distractors: ["Iron", "Granite", "Glass"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🧲\nWhat can a magnet pick up?", correctAnswer: "A steel paper clip", distractors: ["A wooden block", "A plastic cup", "A rubber band"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔦\nHow does light travel?", correctAnswer: "In straight lines", distractors: ["In circles", "In spirals", "It doesn't move"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "👂\nHow does sound reach our ears?", correctAnswer: "As sound waves", distractors: ["As light waves", "Through smell", "Through taste"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌲\nWhat kind of tree is the tallest in the world?", correctAnswer: "Coast redwood", distractors: ["Oak", "Palm tree", "Apple tree"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🫙\nWhich state of matter spreads out to fill its whole container?", correctAnswer: "Gas", distractors: ["Solid", "Liquid", "Powder"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🧪\nWhat are the three common states of matter?", correctAnswer: "Solid, liquid, gas", distractors: ["Hot, cold, warm", "Rock, water, air", "One, two, three"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🐦\nWhat helps a bird fly?", correctAnswer: "Wings", distractors: ["Teeth", "Fur", "Horns"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦠\nWhat are bacteria?", correctAnswer: "Tiny living things", distractors: ["A kind of vegetable", "A kind of metal", "A kind of rock"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌍\nWhat force pulls us down toward the ground?", correctAnswer: "Gravity", distractors: ["Magnetism", "Wind", "Light"], tier: .medium, grades: 3...5),

        // MARK: From QuestionBanksWorkflow + QuestionBanksWorkflow2
        BankQuestion(prompt: "🐸\nWhat is a baby frog called?", correctAnswer: "A tadpole", distractors: ["A cub", "A chick", "A foal"], tier: .hard, grades: 0...2),
        BankQuestion(prompt: "🐔\nWhat do baby chicks hatch from?", correctAnswer: "An egg", distractors: ["A seed", "A flower", "A leaf"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐪\nWhat does a camel store in its hump?", correctAnswer: "Fat", distractors: ["Water", "Sand", "Air"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🦉\nWhen are most owls awake?", correctAnswer: "At night", distractors: ["At noon", "In the morning", "Never"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🐻\nWhat do many bears do during the cold winter?", correctAnswer: "Sleep for a long time in a den", distractors: ["Swim in the ocean", "Fly south", "Lie in the sun"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🥪\nWhich body part helps us chew food?", correctAnswer: "Teeth", distractors: ["Ears", "Knees", "Fingernails"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🩹\nWhat color is our blood?", correctAnswer: "Red", distractors: ["Blue", "Green", "Yellow"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌸\nWhich body part do we smell with?", correctAnswer: "Nose", distractors: ["Eyes", "Ears", "Hands"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍭\nWhich body part do we taste with?", correctAnswer: "Tongue", distractors: ["Ears", "Eyes", "Knees"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🔋\nWhen does our body rest and get its energy back?", correctAnswer: "When we sleep", distractors: ["When we run", "When we jump", "When we shout"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🚀\nWhat shape is Earth?", correctAnswer: "Round like a ball", distractors: ["Flat like a pancake", "Square like a box", "Shaped like a triangle"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "☀️\nWhen does the Sun shine in the sky?", correctAnswer: "During the day", distractors: ["At night", "Only in winter", "Never"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "⭐\nWhen can we see the stars?", correctAnswer: "At night", distractors: ["At noon", "In the morning", "Only when it rains"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🚀\nWhat do we call a person who travels into space?", correctAnswer: "An astronaut", distractors: ["A firefighter", "A diver", "A farmer"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌧️\nWhat falls from the clouds when it rains?", correctAnswer: "Drops of water", distractors: ["Sand", "Leaves", "Rocks"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "⛄\nWhat kind of weather do you need to build a snowman?", correctAnswer: "Cold and snowy", distractors: ["Very hot", "Rainy and warm", "Hot and windy"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌾\nWhat makes the blades of a windmill turn?", correctAnswer: "Wind", distractors: ["Rain", "Snow", "Sunshine"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌡️\nIn most of the United States, which season is usually the hottest?", correctAnswer: "Summer", distractors: ["Winter", "Fall", "Spring"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐝\nWhich part of a plant often has bright colors that attract bees?", correctAnswer: "The flower", distractors: ["The root", "The stem", "The seed"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🍎\nWhere do apples grow on an apple tree?", correctAnswer: "On the branches", distractors: ["On the roots", "In the soil", "Inside the trunk"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🌻\nYoung sunflowers turn during the day to follow what?", correctAnswer: "The Sun", distractors: ["The Moon", "The wind", "The rain"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🫘\nWhat grows from a small seed that you plant?", correctAnswer: "A plant", distractors: ["A rock", "A cloud", "A fish"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🛁\nWhat do we do with soap and water to get clean?", correctAnswer: "Wash", distractors: ["Sleep", "Paint", "Eat"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🏠\nWhere does drinking water come out in a house?", correctAnswer: "The faucet", distractors: ["The window", "The lamp", "The TV"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐟\nWhich body part helps a fish breathe underwater?", correctAnswer: "Gills", distractors: ["Lungs", "Nose", "Ears"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🦆\nWhat is a duck very good at?", correctAnswer: "Swimming", distractors: ["Climbing trees", "Digging tunnels", "Spinning webs"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌊\nHow does ocean water taste?", correctAnswer: "Salty", distractors: ["Sweet", "Sour", "Spicy"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "☁️\nWhat are clouds made of?", correctAnswer: "Tiny drops of water or ice", distractors: ["Soft cotton", "Smoke", "Sand"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🐜\nHow do ants live?", correctAnswer: "In big groups", distractors: ["Always alone", "In the ocean", "On the clouds"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🦋\nHow many wings does a butterfly have?", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🐢\nWhat does a turtle always carry on its back?", correctAnswer: "A shell", distractors: ["Wings", "Spikes", "Fur"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🌈\nWhen do we often see a rainbow?", correctAnswer: "When the Sun comes out after rain", distractors: ["In the middle of a dark night", "Inside a closed box", "Deep under the ground"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "👀\nWhat can cover the Sun and make the day look gray?", correctAnswer: "Clouds", distractors: ["Stars", "Rainbows", "Butterflies"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🫀\nWhat is your heart mostly made of?", correctAnswer: "Muscle", distractors: ["Bone", "Skin", "Hair"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🏃\nWhat helps us move our arms and legs?", correctAnswer: "Muscles", distractors: ["Hair", "Nails", "Tears"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧍\nWhat inside your body holds it up and gives it its shape?", correctAnswer: "Bones", distractors: ["Hair", "Tears", "Nails"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎈\nWhich organs fill up with air when we breathe in?", correctAnswer: "The lungs", distractors: ["The heart", "The stomach", "The brain"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🧢\nWhat grows on top of our heads?", correctAnswer: "Hair", distractors: ["Feathers", "Scales", "Leaves"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "👝\nWhich animal carries its baby in a pouch?", correctAnswer: "Kangaroo", distractors: ["Lion", "Elephant", "Zebra"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🦘\nWhat is a baby kangaroo called?", correctAnswer: "A joey", distractors: ["A cub", "A calf", "A kid"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🌊\nWhich bird cannot fly but is a great swimmer?", correctAnswer: "Penguin", distractors: ["Pigeon", "Eagle", "Sparrow"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🕷️\nWhat does a spider spin to catch its food?", correctAnswer: "A web", distractors: ["Honey", "Milk", "A straw nest"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐘\nWhat does an elephant use to drink and pick things up?", correctAnswer: "Its trunk", distractors: ["Its tail", "Its ears", "Its feet"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🐘\nWhat are an elephant's long, curved teeth called?", correctAnswer: "Tusks", distractors: ["Horns", "Antlers", "Claws"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐄\nWhat drink do we get from cows?", correctAnswer: "Milk", distractors: ["Juice", "Honey", "Oil"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔭\nWhich planet is famous for its bright rings?", correctAnswer: "Saturn", distractors: ["Mars", "Venus", "Mercury"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌀\nWhich planet has a giant storm called the Great Red Spot?", correctAnswer: "Jupiter", distractors: ["Mars", "Venus", "Earth"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🌃\nWhat do we call the Moon when it looks like a complete circle?", correctAnswer: "A full moon", distractors: ["A crescent moon", "A half moon", "A new moon"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✨\nWhat do we call a huge group of billions of stars?", correctAnswer: "A galaxy", distractors: ["A planet", "A moon", "An asteroid"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔭\nWhat is the name of our galaxy?", correctAnswer: "The Milky Way", distractors: ["Andromeda", "The Big Dipper", "Orion"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "☀️\nHow many suns are in our solar system?", correctAnswer: "One", distractors: ["Two", "Three", "None"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "👀\nWhat bright flash do you see in the sky during a thunderstorm?", correctAnswer: "Lightning", distractors: ["A rainbow", "Snow", "Fog"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "💨\nWhat is a strong, spinning column of wind called?", correctAnswer: "A tornado", distractors: ["A rainbow", "A raindrop", "A breeze"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🗓️\nWhat do we call a day with no clouds and lots of sunshine?", correctAnswer: "Sunny", distractors: ["Rainy", "Snowy", "Stormy"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🥶\nIn most of the United States, which season is usually the coldest?", correctAnswer: "Winter", distractors: ["Summer", "Spring", "Fall"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍂\nWhich season is known for colorful leaves falling from the trees?", correctAnswer: "Fall", distractors: ["Summer", "Spring", "Winter"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🌷\nWhich season comes right after winter and brings lots of new flowers?", correctAnswer: "Spring", distractors: ["Summer", "Fall", "Winter"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🌰\nWhen a seed starts to grow in the soil, what grows out first?", correctAnswer: "The root", distractors: ["The flower", "The fruit", "A big leaf"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🎨\nWhat color are most plant leaves?", correctAnswer: "Green", distractors: ["Blue", "Purple", "Black"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍋\nHow does a lemon taste?", correctAnswer: "Sour", distractors: ["Sweet", "Salty", "Spicy"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍯\nHow does honey taste?", correctAnswer: "Sweet", distractors: ["Sour", "Salty", "Bitter"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥧\nHow does food feel when it just came out of the oven?", correctAnswer: "Hot", distractors: ["Cold", "Frozen", "Hard as a rock"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🧈\nWhat do we call it when a solid turns into a liquid, like ice turning into water?", correctAnswer: "Melting", distractors: ["Freezing", "Boiling", "Growing"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪑\nWhich material comes from trees and is used to make many tables?", correctAnswer: "Wood", distractors: ["Glass", "Iron", "Plastic"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🧂\nWhich sense tells us if food is sweet or salty?", correctAnswer: "Taste", distractors: ["Sight", "Hearing", "Touch"], tier: .medium, grades: 2...4),

        // MARK: From QuestionBanksWorkflow3
        BankQuestion(prompt: "🫁\nWhat is the dome-shaped muscle under your lungs that helps you breathe?", correctAnswer: "The diaphragm", distractors: ["The biceps", "The heart", "The tongue"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🔊\nWhich animal says \"moo\"?", correctAnswer: "Cow", distractors: ["Dog", "Cat", "Rooster"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥕\nWhich animal loves to munch on carrots?", correctAnswer: "Rabbit", distractors: ["Fish", "Bird", "Snake"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📖\nWhich body part do we see with?", correctAnswer: "Eyes", distractors: ["Ears", "Nose", "Mouth"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪴\nWhat does a plant need to drink?", correctAnswer: "Water", distractors: ["Sand", "Sugar", "Plastic"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "💡\nWhich star gives us light during the day?", correctAnswer: "The Sun", distractors: ["The Moon", "A shooting star", "Mars"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "☁️\nWhich animal can fly?", correctAnswer: "Bird", distractors: ["Cow", "Elephant", "Turtle"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔊\nWhich animal says \"woof\"?", correctAnswer: "Dog", distractors: ["Cat", "Cow", "Horse"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌱\nWhich part of a plant usually grows under the ground?", correctAnswer: "The root", distractors: ["The leaf", "The flower", "The branch"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐕\nHow many legs does a dog have?", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐄\nWhat does a cow eat?", correctAnswer: "Grass", distractors: ["Meat", "Fish", "Rocks"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "❄️\nIn cold places, which season has the most snow?", correctAnswer: "Winter", distractors: ["Summer", "Spring", "Fall"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "❄️\nWhat do we call water that is frozen hard?", correctAnswer: "Ice", distractors: ["Steam", "A raindrop", "A cloud"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔊\nWhich animal lives in many homes and says \"meow\"?", correctAnswer: "Cat", distractors: ["Lion", "Wolf", "Fox"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌳\nWhat grows on an apple tree?", correctAnswer: "Apples", distractors: ["Bananas", "Grapes", "Strawberries"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌤️\nWhat color is the sky on a clear, sunny day?", correctAnswer: "Blue", distractors: ["Green", "Red", "Brown"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐸\nWhat do frogs eat?", correctAnswer: "Insects", distractors: ["Grass", "Rocks", "Flowers"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐟\nWhat do fish use to swim?", correctAnswer: "Fins", distractors: ["Wings", "Legs", "Hands"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📏\nWhich animal has a very long neck?", correctAnswer: "Giraffe", distractors: ["Rabbit", "Dog", "Mouse"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪟\nWhat are windows made of so we can see through them?", correctAnswer: "Glass", distractors: ["Wood", "Stone", "Cloth"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "✋\nHow many fingers are on one hand?", correctAnswer: "5", distractors: ["3", "7", "10"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌙\nWhich tool helps us see in the dark?", correctAnswer: "A flashlight", distractors: ["A spoon", "A chair", "A book"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍌\nWhich animal climbs trees and loves bananas?", correctAnswer: "Monkey", distractors: ["Fish", "Cow", "Turtle"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐔\nWhat do hens give us?", correctAnswer: "Eggs", distractors: ["Milk", "Wool", "Honey"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🏠\nWhich animal carries its home on its back?", correctAnswer: "Snail", distractors: ["Rabbit", "Bird", "Cat"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🦵\nWhat do we do with our legs?", correctAnswer: "Walk", distractors: ["Hear", "See", "Smell"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🧶\nWhich animal gives us wool?", correctAnswer: "Sheep", distractors: ["Fish", "Chicken", "Turtle"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥤\nWhat is the best drink when we are thirsty?", correctAnswer: "Water", distractors: ["Sand", "Air", "Mud"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🥚\nWhich of these animals lays eggs?", correctAnswer: "Turtle", distractors: ["Cat", "Dog", "Cow"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍳\nWhat are cooking pots usually made of?", correctAnswer: "Metal", distractors: ["Paper", "Cloth", "Wax"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍽️\nWhich organ helps digest the food we eat?", correctAnswer: "The stomach", distractors: ["The brain", "The lungs", "The heart"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "☀️\nWhich planet is closest to the Sun?", correctAnswer: "Mercury", distractors: ["Mars", "Jupiter", "Earth"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "♨️\nWhat is it called when heat turns liquid water into a gas?", correctAnswer: "Evaporation", distractors: ["Freezing", "Melting", "Condensation"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🫀\nWhich blood vessels carry blood away from the heart?", correctAnswer: "Arteries", distractors: ["Veins", "Nerves", "Tendons"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🍓\nWhich part of a plant turns into fruit?", correctAnswer: "The flower", distractors: ["The root", "The leaf", "The stem"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧲\nWhat are the two ends of a magnet called?", correctAnswer: "Poles", distractors: ["Corners", "Handles", "Wheels"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧊\nWhat happens to water when you put it in the freezer?", correctAnswer: "It turns into ice", distractors: ["It turns into steam", "It disappears", "It gets hot"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌍\nWhat causes day and night?", correctAnswer: "Earth spinning on its axis", distractors: ["The Moon covering the Sun", "Clouds blocking the light", "The Sun turning off"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐳\nHow does a whale breathe?", correctAnswer: "Through a blowhole", distractors: ["Through gills", "Through its fins", "Through its tail"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "☕\nWhich sense lets us feel if something is hot or cold?", correctAnswer: "Touch", distractors: ["Smell", "Hearing", "Sight"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐻\nWhat do we call an animal that eats both plants and meat?", correctAnswer: "Omnivore", distractors: ["Herbivore", "Carnivore", "Decomposer"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🪶\nWhich animal lays eggs and has feathers?", correctAnswer: "A bird", distractors: ["A dog", "A cow", "A horse"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐸\nWhat kind of animal is a frog?", correctAnswer: "An amphibian", distractors: ["A reptile", "A mammal", "A fish"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍂\nWhy do many trees lose their leaves in the fall?", correctAnswer: "The days get shorter and colder", distractors: ["Too much sunshine", "Hungry birds eat them", "The wind paints them"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔄\nWhich object in the sky travels around Earth?", correctAnswer: "The Moon", distractors: ["The Sun", "Mars", "Venus"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧊\nWhich ice cube will melt the fastest?", correctAnswer: "One in the sunshine", distractors: ["One in the freezer", "One in a cooler", "One in the snow"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "☁️\nWhat do we call water that rises into the air as a gas and helps form clouds?", correctAnswer: "Water vapor", distractors: ["Ice", "Snow", "Sand"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌸\nWhich sense do you use when you sniff a flower?", correctAnswer: "Smell", distractors: ["Sight", "Hearing", "Taste"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌿\nWhich animal sheds its skin and moves without legs?", correctAnswer: "Snake", distractors: ["Turtle", "Frog", "Mouse"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🫀\nHow many chambers does the human heart have?", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌈\nA rainbow forms when sunlight shines through what?", correctAnswer: "Raindrops", distractors: ["Rocks", "Leaves", "Smoke"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⚡\nWhich kind of material lets electricity flow through it easily?", correctAnswer: "Metal", distractors: ["Wood", "Plastic", "Rubber"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐻\nWhat do we call the long, deep winter sleep some animals take?", correctAnswer: "Hibernation", distractors: ["Migration", "Pollination", "Evaporation"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦅\nWhat do we call it when birds fly to a warmer place for the winter?", correctAnswer: "Migration", distractors: ["Hibernation", "Pollination", "Condensation"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👁️\nWhich part of the eye lets light in?", correctAnswer: "The pupil", distractors: ["The eyebrow", "The eyelash", "The earlobe"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🐟\nWhat covers the body of most fish?", correctAnswer: "Scales", distractors: ["Feathers", "Fur", "Shells"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐱\nWhat is a baby cat called?", correctAnswer: "A kitten", distractors: ["A kid", "A calf", "A foal"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📏\nWhich of these is the biggest?", correctAnswer: "The Sun", distractors: ["Earth", "The Moon", "Mars"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "💧\nWhat is it called when water vapor cools and turns back into drops?", correctAnswer: "Condensation", distractors: ["Freezing", "Evaporation", "Melting"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🕷️\nWhat is a spider's web made of?", correctAnswer: "Silk", distractors: ["Hair", "Grass", "Mud"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🥬\nWhat do we call an animal that eats only plants?", correctAnswer: "Herbivore", distractors: ["Carnivore", "Omnivore", "Predator"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧠\nWhich part of the body protects the brain?", correctAnswer: "The skull", distractors: ["The ribs", "The kneecap", "The palm"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎨\nWhich animal can change the color of its skin?", correctAnswer: "Chameleon", distractors: ["Pig", "Cow", "Horse"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🗺️\nWhat do we call a very dry place that gets little rain?", correctAnswer: "A desert", distractors: ["A forest", "A lake", "A swamp"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧽\nWhich large organ cleans the blood and helps with digestion?", correctAnswer: "The liver", distractors: ["The heart", "The brain", "The ear"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌿\nWhat is the process plants use to make food from sunlight?", correctAnswer: "Photosynthesis", distractors: ["Evaporation", "Respiration", "Digestion"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔄\nWhat is the cycle where water evaporates, forms clouds, and falls as rain?", correctAnswer: "The water cycle", distractors: ["The life cycle", "The rock cycle", "The Moon cycle"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧠\nWhat carries messages between the brain and the rest of the body?", correctAnswer: "Nerves", distractors: ["Bones", "Muscles", "Hair"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🧲\nWhat force pulls the opposite poles of two magnets together?", correctAnswer: "Magnetic force", distractors: ["Gravity", "Friction", "Wind"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💧\nWhich organs filter the blood and make urine?", correctAnswer: "The kidneys", distractors: ["The lungs", "The heart", "The brain"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⚓\nWhen does an object sink in water instead of floating?", correctAnswer: "When it is denser than water", distractors: ["When it is a dark color", "When it is round", "When it is very light"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌬️\nWhich gas makes up most of the air we breathe?", correctAnswer: "Nitrogen", distractors: ["Oxygen", "Carbon dioxide", "Water vapor"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌍\nWhat is the layer of gases around Earth called?", correctAnswer: "The atmosphere", distractors: ["The crust", "The mantle", "The core"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "👂\nWhich part of the ear helps us keep our balance?", correctAnswer: "The inner ear", distractors: ["The earlobe", "The eardrum", "The outer ear"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌙\nWhich force keeps the Moon traveling around Earth?", correctAnswer: "Gravity", distractors: ["Wind", "Sunlight", "Magnetism"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍃\nWhat green substance in leaves captures sunlight?", correctAnswer: "Chlorophyll", distractors: ["Water", "Sand", "Sugar"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍎\nWhich tube carries food from your mouth to your stomach?", correctAnswer: "The esophagus", distractors: ["The windpipe", "An artery", "A vein"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧊\nWhat is it called when liquid water turns into solid ice?", correctAnswer: "Freezing", distractors: ["Evaporation", "Melting", "Condensation"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "👁️\nWhich sense uses light-sensing cells inside the eye?", correctAnswer: "Sight", distractors: ["Hearing", "Taste", "Touch"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🛷\nWhich force slows down things that rub or slide against each other?", correctAnswer: "Friction", distractors: ["Magnetism", "Light", "Sound"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥚\nWhich mammal lays eggs?", correctAnswer: "Platypus", distractors: ["Bear", "Dolphin", "Rabbit"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🩸\nWhich blood cells carry oxygen and make blood red?", correctAnswer: "Red blood cells", distractors: ["White blood cells", "Platelets", "Nerve cells"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🛰️\nWhat do we call a natural object that travels around a planet?", correctAnswer: "A moon", distractors: ["A star", "A galaxy", "A comet"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌋\nWhat kind of rock forms when lava cools and hardens?", correctAnswer: "Igneous rock", distractors: ["Sedimentary rock", "Metamorphic rock", "Limestone"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🫙\nWhich organ stores bile, which helps digest fat?", correctAnswer: "The gallbladder", distractors: ["The heart", "The lungs", "The brain"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🔊\nWhat causes thunder?", correctAnswer: "Lightning heating the air very fast", distractors: ["Clouds bumping into each other", "Rain hitting the ground", "Wind blowing through trees"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🛡️\nWhich blood cells help the body fight germs?", correctAnswer: "White blood cells", distractors: ["Red blood cells", "Skin cells", "Hair cells"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌱\nWhat is it called when a seed begins to sprout a root and a shoot?", correctAnswer: "Germination", distractors: ["Freezing", "Evaporation", "Condensation"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🫁\nWhich tube carries air from your throat to your lungs?", correctAnswer: "The trachea (windpipe)", distractors: ["The esophagus", "An artery", "The intestine"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌑\nWhat happens when the Moon passes between the Sun and Earth and blocks the Sun?", correctAnswer: "A solar eclipse", distractors: ["A lunar eclipse", "A rainbow", "A sunrise"], tier: .hard, grades: 4...6),

        // MARK: From QuestionBanksCurriculumEnglishScience
        BankQuestion(prompt: "🔦\nWhich sense needs light to work?", correctAnswer: "Sight", distractors: ["Hearing", "Taste", "Smell"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌻\nWhich part of a plant holds it up and carries water to the leaves?", correctAnswer: "The stem", distractors: ["The flower", "The seed", "The petal"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐶\nWhat is a baby dog called?", correctAnswer: "A puppy", distractors: ["A kitten", "A chick", "A calf"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐔\nWhat is a baby chicken called?", correctAnswer: "A chick", distractors: ["A calf", "A kid", "A puppy"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐝\nWhere do honeybees live?", correctAnswer: "In a hive", distractors: ["In a den", "In a coop", "In a stable"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌨️\nWhat do we call a big snowstorm with strong winds?", correctAnswer: "A blizzard", distractors: ["A drought", "A heat wave", "A rainbow"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌅\nIn which direction does the Sun rise?", correctAnswer: "East", distractors: ["West", "North", "South"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧊\nIce is water in which state of matter?", correctAnswer: "Solid", distractors: ["Liquid", "Gas", "Plasma"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥛\nMilk is in which state of matter?", correctAnswer: "Liquid", distractors: ["Solid", "Gas", "Plasma"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🫖\nWhen water boils, what does it turn into?", correctAnswer: "Steam", distractors: ["Ice", "Snow", "Frost"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🌨️\nWhat do we call water that falls from clouds as rain, snow, sleet, or hail?", correctAnswer: "Precipitation", distractors: ["Evaporation", "Condensation", "Erosion"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "☔\nWhere does rain come from?", correctAnswer: "Clouds", distractors: ["The Sun", "The stars", "Mountains"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🦴\nWhat do we call the place where two bones meet, like your elbow or knee?", correctAnswer: "A joint", distractors: ["A muscle", "A tendon", "A vein"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔍\nWhat do we call a material that light cannot pass through, like wood?", correctAnswer: "Opaque", distractors: ["Transparent", "Translucent", "Shiny"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🐰\nIn a food chain, what does a rabbit eat?", correctAnswer: "Plants", distractors: ["Insects", "Fish", "Meat"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🔗\nWhat is at the start of most food chains?", correctAnswer: "Plants", distractors: ["Lions", "Eagles", "People"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "☀️\nWhat kinds of energy does Earth get from the Sun?", correctAnswer: "Light and heat", distractors: ["Sound and music", "Battery power", "Gasoline"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🔌\nWhat do we call the complete path electricity flows around, from a battery to a bulb and back?", correctAnswer: "A circuit", distractors: ["A magnet", "A switch", "An orbit"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🧤\nWhich material is an electrical insulator?", correctAnswer: "Rubber", distractors: ["Iron", "Copper", "Aluminum"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "😮‍💨\nWhich waste gas does your body get rid of when you breathe out?", correctAnswer: "Carbon dioxide", distractors: ["Oxygen", "Hydrogen", "Helium"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🩸\nWhat is the main job of blood?", correctAnswer: "To carry oxygen and nutrients around the body", distractors: ["To digest food", "To make light", "To clean the air"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🌳\nWhat is an ecosystem?", correctAnswer: "Living things and their surroundings working together", distractors: ["A pile of rocks in a desert", "A machine that makes electricity", "A kind of weather"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🌬️\nWhat do wind turbines make?", correctAnswer: "Electricity", distractors: ["Rain", "Snow", "Clouds"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🌕\nWhy does the Moon shine at night?", correctAnswer: "It reflects sunlight", distractors: ["It burns like the Sun", "It makes its own light", "The stars light it up"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌿\nWhat does a plant make during photosynthesis?", correctAnswer: "Sugar and oxygen", distractors: ["Salt and water", "Only carbon dioxide", "New soil"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🌿\nWhat does a plant need for photosynthesis?", correctAnswer: "Light, water, and carbon dioxide", distractors: ["Total darkness", "Only oxygen", "Salt and sugar"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🔬\nWhich tiny parts of a plant cell carry out photosynthesis?", correctAnswer: "Chloroplasts", distractors: ["Mitochondria", "The nucleus", "The cell wall"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏗️\nWhat does a lever help us do?", correctAnswer: "Lift heavy things more easily", distractors: ["Heat water", "See far away", "Hear better"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⚙️\nWhat is a pulley used for?", correctAnswer: "Lifting things with a rope", distractors: ["Measuring temperature", "Making light", "Cooling food"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥁\nAll sounds are made by something doing what?", correctAnswer: "Vibrating", distractors: ["Glowing", "Melting", "Freezing"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌩️\nWhy do we see lightning before we hear thunder?", correctAnswer: "Light travels faster than sound", distractors: ["Thunder is made later", "Sound travels faster than light", "Lightning is closer to us"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🔊\nSound usually travels fastest through which?", correctAnswer: "Solids", distractors: ["Liquids", "Air", "Empty space"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "♻️\nWhy is it important to recycle?", correctAnswer: "To cut down on pollution and trash", distractors: ["To make more trash", "To make the ocean dirty", "There is no reason"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "♻️\nWhat does it mean to reuse something?", correctAnswer: "Use it again", distractors: ["Throw it away", "Break it", "Bury it"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🦠\nWhich tool do scientists use to see bacteria?", correctAnswer: "A microscope", distractors: ["Binoculars", "A telescope", "A magnifying glass"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍞\nWhat makes bread dough rise?", correctAnswer: "Yeast", distractors: ["Salt", "Cold water", "Extra flour"], tier: .hard, grades: 5...7),

        // MARK: New US items (NGSS life, earth & space, physical science, engineering)
        BankQuestion(prompt: "🏡\nWhat do we call the natural home of an animal?", correctAnswer: "A habitat", distractors: ["A fossil", "A skeleton", "An orbit"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🪐\nWhich tool helps us see faraway planets and stars?", correctAnswer: "A telescope", distractors: ["A microscope", "A stethoscope", "A thermometer"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌊\nWhat do we call a huge storm that forms over warm ocean water with very strong winds?", correctAnswer: "A hurricane", distractors: ["A blizzard", "A drought", "A sandstorm"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🦕\nWhat do we call the remains or traces of ancient living things preserved in rock?", correctAnswer: "Fossils", distractors: ["Crystals", "Minerals", "Magma"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧬\nWhat do we call a trait that is passed from parents to their young?", correctAnswer: "An inherited trait", distractors: ["A learned skill", "A habit", "A hobby"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦊\nWhat do we call a body part or behavior that helps an animal survive where it lives?", correctAnswer: "An adaptation", distractors: ["A habitat", "A food chain", "A fossil"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧲\nWhat happens when you push the north poles of two magnets toward each other?", correctAnswer: "They push apart", distractors: ["They stick together", "They melt", "They glow"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌊\nWhich is the largest ocean on Earth?", correctAnswer: "The Pacific Ocean", distractors: ["The Atlantic Ocean", "The Indian Ocean", "The Arctic Ocean"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📏\nWhat is the largest organ of the human body?", correctAnswer: "The skin", distractors: ["The heart", "The brain", "The stomach"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🌡️\nWhat is normal human body temperature?", correctAnswer: "About 98.6°F (37°C)", distractors: ["About 50°F (10°C)", "About 75°F (24°C)", "About 120°F (49°C)"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌍\nAbout how long does it take Earth to travel once around the Sun?", correctAnswer: "About 365 days", distractors: ["About 24 hours", "About 30 days", "About 100 years"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌗\nAbout how long does it take Earth to spin around once?", correctAnswer: "About 24 hours", distractors: ["About 1 week", "About 1 month", "About 1 year"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏔️\nWhat is a huge, slow-moving river of ice called?", correctAnswer: "A glacier", distractors: ["A geyser", "A canyon", "A volcano"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⛲\nWhat is a hot spring that shoots water and steam into the air, like Old Faithful?", correctAnswer: "A geyser", distractors: ["A glacier", "A canyon", "A delta"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏞️\nWhat do we call it when moving water or wind carries away bits of rock and soil?", correctAnswer: "Erosion", distractors: ["Evaporation", "Pollination", "Condensation"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛠️\nWhat do engineers call an early model they build to test an idea?", correctAnswer: "A prototype", distractors: ["A fossil", "An orbit", "A habitat"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏜️\nThe Grand Canyon was carved mostly by what?", correctAnswer: "The Colorado River", distractors: ["An earthquake", "A volcano", "A meteor"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌱\nIn a food web, what are plants called because they make their own food?", correctAnswer: "Producers", distractors: ["Consumers", "Decomposers", "Predators"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🍄\nWhat do we call living things that break down dead plants and animals?", correctAnswer: "Decomposers", distractors: ["Producers", "Predators", "Herbivores"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "⚡\nWhich of these is a renewable energy source?", correctAnswer: "Solar power", distractors: ["Coal", "Oil", "Natural gas"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "💨\nWhich tool measures wind speed?", correctAnswer: "An anemometer", distractors: ["A thermometer", "A barometer", "A rain gauge"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⚖️\nWhat do we call the amount of matter in an object?", correctAnswer: "Mass", distractors: ["Speed", "Temperature", "Color"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "📈\nWhat is a scientist's testable prediction called?", correctAnswer: "A hypothesis", distractors: ["A conclusion", "A graph", "A fossil"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🌎\nWhat is the center of Earth called?", correctAnswer: "The core", distractors: ["The crust", "The mantle", "The atmosphere"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🪨\nWhat kind of rock forms from layers of sand and mud pressed together?", correctAnswer: "Sedimentary rock", distractors: ["Igneous rock", "Metamorphic rock", "Volcanic glass"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌡️\nWhat does a barometer measure?", correctAnswer: "Air pressure", distractors: ["Temperature", "Wind speed", "Rainfall"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🍳\nWhich of these is a physical change?", correctAnswer: "Ice melting", distractors: ["Wood burning", "A nail rusting", "Bread baking"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🧪\nWhat always happens in a chemical change?", correctAnswer: "A new substance forms", distractors: ["Only the shape changes", "It gets cut into smaller pieces", "It melts"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🧫\nWhat is the basic unit of all living things?", correctAnswer: "The cell", distractors: ["The organ", "The tissue", "The organ system"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🧬\nWhich part of a cell holds most of its DNA and controls the cell?", correctAnswer: "The nucleus", distractors: ["The cell wall", "The cell membrane", "The vacuole"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🔋\nWhich cell parts release energy from food?", correctAnswer: "Mitochondria", distractors: ["Chloroplasts", "Ribosomes", "Vacuoles"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌿\nWhich structure do plant cells have that animal cells do not?", correctAnswer: "A cell wall", distractors: ["A nucleus", "A cell membrane", "Mitochondria"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🫁\nWhat are the tiny air sacs in the lungs called?", correctAnswer: "Alveoli", distractors: ["Villi", "Neurons", "Tendons"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "💪\nWhat connects muscles to bones?", correctAnswer: "Tendons", distractors: ["Nerves", "Veins", "Hair"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🍃\nWhat are the tiny openings on leaves that let gases in and out?", correctAnswer: "Stomata", distractors: ["Xylem", "Petals", "Pollen"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "⚛️\nWhat is the smallest unit of a chemical element?", correctAnswer: "An atom", distractors: ["A cell", "A crystal", "A grain of sand"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "💧\nWhat is the chemical formula for water?", correctAnswer: "H₂O", distractors: ["CO₂", "O₂", "NaCl"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏎️\nHow do you find an object's average speed?", correctAnswer: "Distance divided by time", distractors: ["Time divided by distance", "Distance times time", "Mass times time"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌡️\nWhen the temperature of a material goes up, what happens to its particles?", correctAnswer: "They move faster", distractors: ["They stop moving", "They move more slowly", "They disappear"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🎢\nA roller coaster car sitting at the top of a hill has the most of which energy?", correctAnswer: "Potential energy", distractors: ["Kinetic energy", "Sound energy", "Light energy"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🔋\nWhat kind of energy is stored in a battery?", correctAnswer: "Chemical energy", distractors: ["Sound energy", "Light energy", "Kinetic energy"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌎\nWhy does Earth have seasons?", correctAnswer: "Earth's axis is tilted", distractors: ["The Moon blocks the Sun", "The Sun gets hotter and cooler", "Clouds cover Earth in winter"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌋\nWhere do most earthquakes and volcanoes happen?", correctAnswer: "Along the edges of tectonic plates", distractors: ["Only at the North Pole", "Only in deserts", "Only where it rains a lot"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌞\nThe Sun is made mostly of which two gases?", correctAnswer: "Hydrogen and helium", distractors: ["Oxygen and nitrogen", "Carbon dioxide and steam", "Neon and argon"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌌\nWhat does a light-year measure?", correctAnswer: "Distance", distractors: ["Time", "Brightness", "Weight"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "⚛️\nWhich particle in an atom has a negative charge?", correctAnswer: "Electron", distractors: ["Proton", "Neutron", "Nucleus"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🧂\nWhat is the chemical name for table salt?", correctAnswer: "Sodium chloride", distractors: ["Calcium carbonate", "Carbon dioxide", "Sodium bicarbonate"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🚀\nNewton's third law says every action has an equal and opposite what?", correctAnswer: "Reaction", distractors: ["Motion", "Gravity", "Speed"], tier: .hard, grades: 7...8),
    ]
}
