import Foundation

/// 🗺️ Geography — English (US). Adapted from the Hebrew geography banks (QuestionBanks, Expanded,
/// Workflow, Workflow2, Workflow3, CurriculumHumanities) as a map of learning goals per grade:
/// map skills, landforms and water, continents and oceans, US regions, states and capitals,
/// US rivers and mountains, stable world capitals and landmarks, climate zones and
/// latitude/longitude. Every Israel item became a US equivalent; only timeless facts
/// (no population rankings, no disputed borders or renamed features).
extension EnglishContent {
    static let geography: [BankQuestion] = [
        // ── Kindergarten–1st · Our world ──
        BankQuestion(prompt: "🌍\nWhat is the name of the planet we live on?", correctAnswer: "Earth", distractors: ["Mars", "The Moon", "The Sun"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌐\nWhat shape is the Earth?", correctAnswer: "Round like a ball", distractors: ["Flat like a plate", "Square like a box", "Long like a stick"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌊\nIs there more water or more land on Earth?", correctAnswer: "More water", distractors: ["More land", "The same amount", "No water at all"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐪\nWhat do we call a dry place with lots of sand and very little rain?", correctAnswer: "Desert", distractors: ["Forest", "Ocean", "Swamp"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌲\nWhat do we call a place with lots and lots of trees?", correctAnswer: "Forest", distractors: ["Desert", "Beach", "Ocean"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐚\nWhat do we call the sandy place next to the ocean?", correctAnswer: "Beach", distractors: ["Mountain", "Forest", "Desert"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🧗\nWhat do we call very tall land that goes up to a high top?", correctAnswer: "Mountain", distractors: ["Valley", "Beach", "Road"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🛶\nWhat do we call water that flows along from one place to another?", correctAnswer: "River", distractors: ["Mountain", "Desert", "Island"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌊\nWhat do we call land with water all around it?", correctAnswer: "Island", distractors: ["Mountain", "Desert", "Valley"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐧\nWhich place is covered in ice and snow and is very cold?", correctAnswer: "The South Pole", distractors: ["The desert", "The beach", "A rain forest"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐟\nWhat is the biggest kind of water on Earth?", correctAnswer: "Ocean", distractors: ["Pond", "Puddle", "Swimming pool"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🏖️\nAt the beach, what rolls in from the ocean and splashes on the sand?", correctAnswer: "Waves", distractors: ["Rocks", "Clouds", "Trees"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚕\nWhat do we call a place with many buildings, streets and people?", correctAnswer: "City", distractors: ["Desert", "Ocean", "Forest"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐄\nWhere do farmers grow crops and raise cows?", correctAnswer: "On a farm", distractors: ["In the ocean", "On a glacier", "In a cave"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "📍\nWhat is a drawing of a place that shows where things are?", correctAnswer: "A map", distractors: ["A calendar", "A clock", "A menu"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🔵\nWhat do we call a round model of the Earth?", correctAnswer: "A globe", distractors: ["A compass", "A telescope", "A clock"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🖍️\nOn a globe, what color usually shows water?", correctAnswer: "Blue", distractors: ["Green", "Brown", "Red"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🏠\nWhat tells people exactly where your home is so mail can get there?", correctAnswer: "Your address", distractors: ["Your birthday", "Your favorite color", "Your shoe size"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "☀️\nIn which direction does the sun rise in the morning?", correctAnswer: "East", distractors: ["West", "North", "South"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌇\nIn which direction does the sun set in the evening?", correctAnswer: "West", distractors: ["East", "North", "South"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "❄️\nIn which season is it usually coldest in most of the United States?", correctAnswer: "Winter", distractors: ["Summer", "Spring", "Fall"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "☀️\nIn which season is it usually hottest in most of the United States?", correctAnswer: "Summer", distractors: ["Winter", "Spring", "Fall"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐻\nWhere do bears, deer and owls often live?", correctAnswer: "In the forest", distractors: ["In the ocean", "In the desert sand", "On an iceberg"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌵\nWhere would you most likely see a cactus growing?", correctAnswer: "In the desert", distractors: ["On an iceberg", "In a lake", "At the North Pole"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "💧\nWhat do we call a body of water with land all around it?", correctAnswer: "Lake", distractors: ["Island", "Peninsula", "Mountain"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏘️\nWhat do we call a small place with a few houses and stores?", correctAnswer: "Town", distractors: ["Ocean", "Continent", "Planet"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🗺️\nWhat is the name of our country?", correctAnswer: "The United States of America", distractors: ["Canada", "Mexico", "Brazil"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🎨\nWhat colors are on the flag of the United States?", correctAnswer: "Red, white and blue", distractors: ["Green and yellow", "Black and orange", "Purple and pink"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "⭐\nHow many stars are on the flag of the United States?", correctAnswer: "50", distractors: ["13", "25", "100"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "〰️\nHow many stripes are on the flag of the United States?", correctAnswer: "13", distractors: ["10", "50", "7"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐦\nWhich bird is the national bird of the United States?", correctAnswer: "Bald eagle", distractors: ["Robin", "Parrot", "Penguin"], tier: .easy, grades: 1...3),
        // ── Grades 1–4 · Map skills ──
        BankQuestion(prompt: "🧭\nOn most maps, which direction is at the top?", correctAnswer: "North", distractors: ["South", "East", "West"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🧭\nWhat is the opposite of north?", correctAnswer: "South", distractors: ["East", "West", "Up"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧭\nWhat is the opposite of east?", correctAnswer: "West", distractors: ["North", "South", "Down"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧭\nNorth, south, east and west are called the... ?", correctAnswer: "Cardinal directions", distractors: ["Map symbols", "Seasons", "Continents"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🗺️\nWhat do we call the symbol on a map that shows north, south, east and west?", correctAnswer: "Compass rose", distractors: ["Map key", "Scale", "Title"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🔣\nWhat part of a map explains what its symbols mean?", correctAnswer: "Map key", distractors: ["Compass rose", "Scale", "Grid"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "📏\nWhat part of a map helps you figure out real distances?", correctAnswer: "Map scale", distractors: ["Map key", "Compass rose", "Title"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧲\nWhich tool has a needle that points north?", correctAnswer: "A compass", distractors: ["A ruler", "A thermometer", "A clock"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🧭\nYou face north. Which direction is on your right?", correctAnswer: "East", distractors: ["West", "South", "North"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧭\nYou face north. Which direction is behind you?", correctAnswer: "South", distractors: ["East", "West", "North"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧭\nWhich direction is halfway between north and east?", correctAnswer: "Northeast", distractors: ["Northwest", "Southeast", "Southwest"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧭\nWhich direction is halfway between south and west?", correctAnswer: "Southwest", distractors: ["Southeast", "Northwest", "Northeast"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "↖️\nWhat is the opposite direction of northwest?", correctAnswer: "Southeast", distractors: ["Southwest", "Northeast", "North"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🗺️\nOn a map, a small airplane symbol most likely shows... ?", correctAnswer: "An airport", distractors: ["A school", "A lake", "A mountain"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🗺️\nOn many maps, what does a thin blue line usually show?", correctAnswer: "A river", distractors: ["A road", "A state border", "A mountain"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "📚\nWhat do we call a book full of maps?", correctAnswer: "An atlas", distractors: ["A dictionary", "A diary", "A cookbook"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🗺️\nWhat kind of map shows the borders of states and countries?", correctAnswer: "Political map", distractors: ["Physical map", "Weather map", "Star map"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⛰️\nWhat kind of map shows mountains, rivers and other landforms?", correctAnswer: "Physical map", distractors: ["Political map", "Road map", "Seating chart"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📏\nOn a map, 1 inch stands for 10 miles. How far is 3 inches?", correctAnswer: "30 miles", distractors: ["3 miles", "13 miles", "300 miles"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📏\nOn a map, 1 inch stands for 50 miles. Two towns are 4 inches apart. How far apart are they?", correctAnswer: "200 miles", distractors: ["54 miles", "150 miles", "250 miles"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🔢\nOn a grid map, what helps you find a place, like \"B3\"?", correctAnswer: "A letter and a number", distractors: ["Two colors", "A picture of the place", "The map title"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧭\nOn a map with north at the top, a town is at the top and a lake is at the bottom. Which direction is the lake from the town?", correctAnswer: "South", distractors: ["North", "East", "West"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🗺️\nWhat is the name for the words at the top of a map telling what it shows?", correctAnswer: "The title", distractors: ["The key", "The scale", "The compass rose"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏔️\nOn a topographic map, what do lines packed close together show?", correctAnswer: "A steep slope", distractors: ["Flat land", "A lake", "A highway"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "📐\nWhich is more accurate for showing the true shapes and sizes of all the continents?", correctAnswer: "A globe", distractors: ["A flat world map", "A road map", "A city map"], tier: .hard, grades: 5...7),
        // ── Grades 1–3 · Communities ──
        BankQuestion(prompt: "🏙️\nA busy city with many people and tall buildings is called... ?", correctAnswer: "Urban", distractors: ["Rural", "Suburban", "Polar"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🚜\nAn area in the countryside with farms and lots of open land is called... ?", correctAnswer: "Rural", distractors: ["Urban", "Suburban", "Tropical"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🏡\nA neighborhood of homes near the edge of a big city is called... ?", correctAnswer: "Suburban", distractors: ["Urban", "Rural", "Arctic"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🚗\nWhat do we call the path that cars drive on?", correctAnswer: "A road", distractors: ["A river", "A valley", "A cliff"], tier: .easy, grades: 0...1),
        // ── Kindergarten–2nd · More about places ──
        BankQuestion(prompt: "☁️\nWhat falls from clouds and fills rivers and lakes?", correctAnswer: "Rain", distractors: ["Sand", "Leaves", "Rocks"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🏜️\nWhich animal is built for living in the hot, dry desert?", correctAnswer: "Camel", distractors: ["Penguin", "Polar bear", "Seal"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🧊\nWhich animal lives where it is icy and cold?", correctAnswer: "Penguin", distractors: ["Camel", "Lion", "Parrot"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐋\nWhere do whales live?", correctAnswer: "In the ocean", distractors: ["In the desert", "In a forest", "On a mountain"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚲\nWhat do we call the streets and homes right around where you live?", correctAnswer: "Your neighborhood", distractors: ["Your planet", "Your ocean", "Your continent"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🦆\nWhat do we call a small body of still water, smaller than a lake?", correctAnswer: "Pond", distractors: ["Ocean", "River", "Sea"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🏞️\nWhat do we call a small, narrow river?", correctAnswer: "Stream", distractors: ["Ocean", "Glacier", "Continent"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌊\nWhat do we call a big body of salt water that is smaller than an ocean?", correctAnswer: "Sea", distractors: ["Pond", "Stream", "Puddle"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🌎\nWhat do we call one of the huge areas of land on Earth, like North America?", correctAnswer: "Continent", distractors: ["Pond", "Street", "Island"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "❄️\nWhere would you most likely find snow in the summer?", correctAnswer: "On top of a very tall mountain", distractors: ["On a sunny beach", "In a hot desert", "In a warm lake"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "📏\nWhich of these places is the smallest?", correctAnswer: "A house", distractors: ["A city", "A state", "A country"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🌎\nWhich of these places is the biggest?", correctAnswer: "A country", distractors: ["A town", "A street", "A house"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🗺️\nHouse, street, city... what comes next, from smaller to bigger?", correctAnswer: "State", distractors: ["Street", "House", "Neighborhood"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🏫\nOn a map of your classroom, a little square stands for each desk. What is that square called?", correctAnswer: "A symbol", distractors: ["A compass", "A globe", "A continent"], tier: .medium, grades: 1...2),
        // ── Grades 2–5 · Landforms and bodies of water ──
        BankQuestion(prompt: "🏞️\nWhat do we call low land between hills or mountains?", correctAnswer: "Valley", distractors: ["Peak", "Island", "Plateau"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🌾\nWhat do we call a large area of flat land?", correctAnswer: "Plain", distractors: ["Mountain", "Canyon", "Volcano"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🏜️\nWhat do we call high, flat land that rises steeply above the land around it?", correctAnswer: "Plateau", distractors: ["Valley", "Plain", "Bay"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏜️\nWhat do we call a deep, narrow valley with steep sides, often carved by a river?", correctAnswer: "Canyon", distractors: ["Plain", "Peninsula", "Hill"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🗺️\nWhat do we call land with water on three sides?", correctAnswer: "Peninsula", distractors: ["Island", "Lake", "Plain"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌉\nWhat do we call a narrow strip of land that connects two larger pieces of land?", correctAnswer: "Isthmus", distractors: ["Strait", "Bay", "Delta"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏝️\nWhat do we call a group of islands close together?", correctAnswer: "Archipelago", distractors: ["Continent", "Peninsula", "Canyon"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⛵\nWhat do we call part of an ocean or lake that curves into the land?", correctAnswer: "Bay", distractors: ["Island", "Peninsula", "Mesa"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌊\nWhat do we call a narrow waterway that connects two larger bodies of water?", correctAnswer: "Strait", distractors: ["Isthmus", "Plateau", "Glacier"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🚢\nWhat do we call a waterway that people dig so ships can pass through?", correctAnswer: "Canal", distractors: ["Canyon", "Glacier", "Delta"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🔥\nWhat do we call a mountain that can erupt with hot lava?", correctAnswer: "Volcano", distractors: ["Glacier", "Mesa", "Valley"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🧊\nWhat do we call a huge, slow-moving river of ice?", correctAnswer: "Glacier", distractors: ["Volcano", "Delta", "Canyon"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "💦\nWhat do we call a river pouring over the edge of a cliff?", correctAnswer: "Waterfall", distractors: ["Glacier", "Canal", "Pond"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🐊\nWhat do we call soggy ground covered with shallow water and plants, like a swamp or marsh?", correctAnswer: "Wetland", distractors: ["Desert", "Plateau", "Mountain"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔺\nWhat do we call the land formed where a river drops mud and sand as it enters the sea?", correctAnswer: "Delta", distractors: ["Source", "Canyon", "Peak"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏔️\nWhere a river begins is called its... ?", correctAnswer: "Source", distractors: ["Mouth", "Delta", "Bank"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌊\nWhere a river ends and flows into a bigger body of water is called its... ?", correctAnswer: "Mouth", distractors: ["Source", "Peak", "Valley"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏞️\nA smaller river that flows into a bigger river is called a... ?", correctAnswer: "Tributary", distractors: ["Delta", "Canal", "Glacier"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🪨\nWhat do we call a flat-topped hill with steep sides, common in the Southwest?", correctAnswer: "Mesa", distractors: ["Delta", "Bay", "Glacier"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⛰️\nWhat do we call a long row of connected peaks?", correctAnswer: "Mountain range", distractors: ["Plain", "Canyon", "Island chain"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⛰️\nWhat do we call the very top of a mountain?", correctAnswer: "Peak", distractors: ["Valley", "Mouth", "Base"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⛰️\nWhich is taller, a hill or a mountain?", correctAnswer: "A mountain", distractors: ["A hill", "They are the same height", "A valley"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧂\nWhich kind of water is salty?", correctAnswer: "Ocean water", distractors: ["Rain water", "River water", "Lake Superior water"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🚰\nWater in most rivers and lakes that is not salty is called... ?", correctAnswer: "Fresh water", distractors: ["Salt water", "Sea water", "Ocean water"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🏖️\nWhat do we call the land along the edge of an ocean?", correctAnswer: "Coast", distractors: ["Plateau", "Valley", "Canyon"], tier: .easy, grades: 2...3),
        // ── Grades 2–6 · Continents and oceans ──
        BankQuestion(prompt: "🌍\nHow many continents are there?", correctAnswer: "7", distractors: ["5", "6", "8"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🌊\nHow many oceans do most world maps show today?", correctAnswer: "5", distractors: ["3", "7", "10"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🗺️\nOn which continent is the United States?", correctAnswer: "North America", distractors: ["South America", "Europe", "Asia"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🗺️\nWhich continent is the largest?", correctAnswer: "Asia", distractors: ["Africa", "Europe", "North America"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📏\nWhich continent is the smallest?", correctAnswer: "Australia", distractors: ["Europe", "Antarctica", "South America"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🥶\nWhich continent is the coldest?", correctAnswer: "Antarctica", distractors: ["Asia", "Europe", "North America"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧊\nWhich continent is covered almost completely by ice?", correctAnswer: "Antarctica", distractors: ["Africa", "Australia", "South America"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🗺️\nWhich continent is also a single country?", correctAnswer: "Australia", distractors: ["Asia", "Europe", "Africa"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌊\nWhich ocean is the largest?", correctAnswer: "Pacific Ocean", distractors: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌊\nWhich ocean is the smallest?", correctAnswer: "Arctic Ocean", distractors: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌊\nWhich ocean is on the east coast of the United States?", correctAnswer: "Atlantic Ocean", distractors: ["Pacific Ocean", "Indian Ocean", "Arctic Ocean"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🌊\nWhich ocean is on the west coast of the United States?", correctAnswer: "Pacific Ocean", distractors: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🌊\nWhich ocean lies between Africa and Australia?", correctAnswer: "Indian Ocean", distractors: ["Atlantic Ocean", "Arctic Ocean", "Southern Ocean"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🧊\nWhich ocean surrounds the North Pole?", correctAnswer: "Arctic Ocean", distractors: ["Indian Ocean", "Southern Ocean", "Pacific Ocean"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🐧\nWhich ocean surrounds Antarctica?", correctAnswer: "Southern Ocean", distractors: ["Arctic Ocean", "Indian Ocean", "Atlantic Ocean"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌊\nWhich ocean lies between North America and Europe?", correctAnswer: "Atlantic Ocean", distractors: ["Pacific Ocean", "Indian Ocean", "Southern Ocean"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📍\nOn which continent is Egypt?", correctAnswer: "Africa", distractors: ["Asia", "Europe", "South America"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📍\nOn which continent is Brazil?", correctAnswer: "South America", distractors: ["North America", "Africa", "Asia"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📍\nOn which continent is India?", correctAnswer: "Asia", distractors: ["Africa", "Europe", "Australia"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📍\nOn which continent is France?", correctAnswer: "Europe", distractors: ["Asia", "Africa", "South America"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📍\nOn which continent is Mexico?", correctAnswer: "North America", distractors: ["South America", "Europe", "Africa"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📍\nOn which continent is Japan?", correctAnswer: "Asia", distractors: ["Europe", "Australia", "North America"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📍\nOn which continent is Kenya?", correctAnswer: "Africa", distractors: ["Asia", "South America", "Europe"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "📍\nOn which continent is Argentina?", correctAnswer: "South America", distractors: ["Africa", "Europe", "Australia"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌐\nWhich continent is crossed by both the equator and the Prime Meridian?", correctAnswer: "Africa", distractors: ["Europe", "Australia", "North America"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🗺️\nWhich continent has the most countries?", correctAnswer: "Africa", distractors: ["Asia", "Europe", "South America"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌊\nWhich sea lies between Europe and Africa?", correctAnswer: "Mediterranean Sea", distractors: ["Caribbean Sea", "Red Sea", "Bering Sea"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🗺️\nWhich two continents are joined by the narrow land of Panama?", correctAnswer: "North America and South America", distractors: ["Europe and Asia", "Africa and Asia", "Australia and Asia"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🗻\nWhich mountains are often used as a border between Europe and Asia?", correctAnswer: "Ural Mountains", distractors: ["Andes Mountains", "Rocky Mountains", "Appalachian Mountains"], tier: .hard, grades: 6...8),
        // ── Grades 2–5 · Animals around the world ──
        BankQuestion(prompt: "🦘\nIn which country do kangaroos live in the wild?", correctAnswer: "Australia", distractors: ["Canada", "Brazil", "Egypt"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🐨\nIn which country do koalas live in the wild?", correctAnswer: "Australia", distractors: ["China", "India", "Mexico"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🐼\nIn which country do giant pandas live in the wild?", correctAnswer: "China", distractors: ["Australia", "Brazil", "France"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🐻‍❄️\nWhere do polar bears live?", correctAnswer: "Near the North Pole, in the Arctic", distractors: ["In Antarctica", "In the Sahara", "In the Amazon rain forest"], tier: .medium, grades: 2...5),
        BankQuestion(prompt: "🐧\nWhere do emperor penguins live?", correctAnswer: "Antarctica", distractors: ["The Arctic", "Africa's deserts", "The Amazon rain forest"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🦁\nOn which continent do most wild lions live?", correctAnswer: "Africa", distractors: ["Antarctica", "Europe", "North America"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🦓\nOn which continent do zebras live in the wild?", correctAnswer: "Africa", distractors: ["Europe", "Australia", "Antarctica"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🐅\nOn which continent do tigers live in the wild?", correctAnswer: "Asia", distractors: ["Africa", "Australia", "South America"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦙\nIn which mountains of South America do llamas live?", correctAnswer: "Andes Mountains", distractors: ["Alps", "Himalayas", "Rocky Mountains"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🦬\nOn which continent do American bison roam the grassy plains?", correctAnswer: "North America", distractors: ["South America", "Africa", "Australia"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🐊\nIn which US state's Everglades do alligators live?", correctAnswer: "Florida", distractors: ["Alaska", "Maine", "Montana"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦜\nWhere do many colorful parrots and monkeys live?", correctAnswer: "In a tropical rain forest", distractors: ["At the North Pole", "On a glacier", "In a polar desert"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🫎\nWhich cold US state is home to many wild moose, bears and caribou?", correctAnswer: "Alaska", distractors: ["Florida", "Hawaii", "Arizona"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🐘\nWhere do the biggest elephants in the world live?", correctAnswer: "Africa", distractors: ["Europe", "Australia", "Antarctica"], tier: .medium, grades: 3...5),
        // ── Grades 2–5 · The United States ──
        BankQuestion(prompt: "🏛️\nWhat is the capital of the United States?", correctAnswer: "Washington, D.C.", distractors: ["New York City", "Los Angeles", "Chicago"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🇺🇸\nHow many states are in the United States?", correctAnswer: "50", distractors: ["13", "48", "52"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🌎\nWhich country is the northern neighbor of the United States?", correctAnswer: "Canada", distractors: ["Mexico", "Brazil", "Cuba"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧭\nWhich country borders the United States to the south?", correctAnswer: "Mexico", distractors: ["Canada", "Brazil", "Argentina"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "📏\nWhich is the largest US state by area?", correctAnswer: "Alaska", distractors: ["Texas", "California", "Montana"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔹\nWhich is the smallest US state by area?", correctAnswer: "Rhode Island", distractors: ["Delaware", "Connecticut", "New Jersey"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌺\nWhich US state is made up of islands in the Pacific Ocean?", correctAnswer: "Hawaii", distractors: ["Alaska", "Florida", "Maine"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🗺️\nWhich US state is a peninsula in the Southeast?", correctAnswer: "Florida", distractors: ["Colorado", "Ohio", "Kansas"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📏\nWhich is the second-largest US state by area?", correctAnswer: "Texas", distractors: ["Florida", "Ohio", "New York"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🗽\nIn which city is the Statue of Liberty?", correctAnswer: "New York City", distractors: ["Washington, D.C.", "Chicago", "Miami"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🍎\nWhich US city is nicknamed \"the Big Apple\"?", correctAnswer: "New York City", distractors: ["Boston", "Seattle", "Denver"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌉\nIn which city is the Golden Gate Bridge?", correctAnswer: "San Francisco", distractors: ["Chicago", "Boston", "Houston"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔔\nIn which city can you see the Liberty Bell?", correctAnswer: "Philadelphia", distractors: ["Denver", "Seattle", "Phoenix"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌈\nIn which city is the Gateway Arch?", correctAnswer: "St. Louis", distractors: ["Atlanta", "Portland", "San Diego"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🗿\nIn which state is Mount Rushmore?", correctAnswer: "South Dakota", distractors: ["Colorado", "Texas", "Florida"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏞️\nIn which state is the Grand Canyon?", correctAnswer: "Arizona", distractors: ["Florida", "Ohio", "Maine"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏞️\nWhich river carved the Grand Canyon?", correctAnswer: "Colorado River", distractors: ["Mississippi River", "Hudson River", "Ohio River"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌋\nYellowstone, the first national park in the world, is mostly in which state?", correctAnswer: "Wyoming", distractors: ["Florida", "Georgia", "Iowa"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💦\nWhich famous waterfalls are on the border of New York and Canada?", correctAnswer: "Niagara Falls", distractors: ["Victoria Falls", "Angel Falls", "Yosemite Falls"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚀\nIn which state is the Kennedy Space Center, where many rockets launch?", correctAnswer: "Florida", distractors: ["Alaska", "Montana", "Vermont"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏛️\nIn which state is the Alamo, a famous old mission?", correctAnswer: "Texas", distractors: ["California", "Georgia", "Maine"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌊\nHow many Great Lakes are there?", correctAnswer: "5", distractors: ["3", "4", "7"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌊\nWhich is the largest of the Great Lakes?", correctAnswer: "Lake Superior", distractors: ["Lake Erie", "Lake Ontario", "Lake Michigan"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌊\nWhich Great Lake is the only one entirely inside the United States?", correctAnswer: "Lake Michigan", distractors: ["Lake Superior", "Lake Erie", "Lake Ontario"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏞️\nWhich great river flows south through the middle of the US, past St. Louis and New Orleans?", correctAnswer: "Mississippi River", distractors: ["Colorado River", "Columbia River", "Hudson River"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏞️\nWhich river forms part of the border between Texas and Mexico?", correctAnswer: "Rio Grande", distractors: ["Mississippi River", "Missouri River", "Ohio River"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏞️\nWhich river forms much of the border between Oregon and Washington?", correctAnswer: "Columbia River", distractors: ["Rio Grande", "Hudson River", "Potomac River"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏞️\nWhich river flows past Washington, D.C.?", correctAnswer: "Potomac River", distractors: ["Colorado River", "Rio Grande", "Columbia River"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏞️\nWhich river flows along the west side of Manhattan in New York City?", correctAnswer: "Hudson River", distractors: ["Missouri River", "Colorado River", "Snake River"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏞️\nWhich river joins the Mississippi River near St. Louis?", correctAnswer: "Missouri River", distractors: ["Hudson River", "Columbia River", "Potomac River"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌊\nHoover Dam holds back water on which river?", correctAnswer: "Colorado River", distractors: ["Hudson River", "Ohio River", "Delaware River"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "⛰️\nWhich tall mountain range runs through the western United States?", correctAnswer: "Rocky Mountains", distractors: ["Appalachian Mountains", "Alps", "Himalayas"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⛰️\nWhich older, lower mountain range runs through the eastern United States?", correctAnswer: "Appalachian Mountains", distractors: ["Rocky Mountains", "Andes Mountains", "Sierra Nevada"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🥾\nThe Appalachian Trail runs from Georgia all the way to which state?", correctAnswer: "Maine", distractors: ["Florida", "Texas", "California"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏔️\nIn which mountain range is Yosemite National Park?", correctAnswer: "Sierra Nevada", distractors: ["Appalachian Mountains", "Ozark Mountains", "Alps"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌋\nIn which state did Mount St. Helens erupt in 1980?", correctAnswer: "Washington", distractors: ["Hawaii", "Colorado", "Nevada"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏔️\nWhat is the name for the ridge in the Rockies that decides whether rivers flow toward the Pacific or the Atlantic side?", correctAnswer: "Continental Divide", distractors: ["Equator", "Prime Meridian", "Tropic of Cancer"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🔥\nWhich desert valley in California is the lowest and hottest place in North America?", correctAnswer: "Death Valley", distractors: ["Grand Canyon", "Napa Valley", "Yosemite Valley"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🦐\nWhich huge lake in Utah is home to tiny brine shrimp but almost no fish?", correctAnswer: "Great Salt Lake", distractors: ["Lake Tahoe", "Lake Erie", "Crater Lake"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "💙\nWhich lake in Oregon, formed in an old volcano, is the deepest lake in the United States?", correctAnswer: "Crater Lake", distractors: ["Lake Tahoe", "Great Salt Lake", "Lake Erie"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌋\nWhich US state has active volcanoes that make new land from lava?", correctAnswer: "Hawaii", distractors: ["Kansas", "Ohio", "Vermont"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌵\nIn which desert is the city of Las Vegas?", correctAnswer: "Mojave Desert", distractors: ["Sahara Desert", "Gobi Desert", "Atacama Desert"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌾\nWhat is the name of the flat, grassy land in the middle of the United States?", correctAnswer: "Great Plains", distractors: ["Great Basin", "Rocky Mountains", "Everglades"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "✳️\nAt the Four Corners, four states meet. Which state is NOT one of them?", correctAnswer: "Nevada", distractors: ["Arizona", "Utah", "New Mexico"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🦀\nWhich large bay lies in Maryland and Virginia?", correctAnswer: "Chesapeake Bay", distractors: ["San Francisco Bay", "Hudson Bay", "Monterey Bay"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🧭\nWhich ocean does Alaska's northern coast touch?", correctAnswer: "Arctic Ocean", distractors: ["Indian Ocean", "Atlantic Ocean", "Southern Ocean"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🧊\nWhich narrow strait separates Alaska from Russia?", correctAnswer: "Bering Strait", distractors: ["Strait of Gibraltar", "Panama Canal", "Suez Canal"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "⏰\nHow many main time zones cover the 48 connected states?", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🗺️\nWhich region are Maine, Vermont and Massachusetts in?", correctAnswer: "Northeast", distractors: ["Southwest", "West", "Midwest"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🗺️\nWhich region are Arizona and New Mexico in?", correctAnswer: "Southwest", distractors: ["Northeast", "Midwest", "Southeast"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🗺️\nWhich region are Ohio, Iowa and Illinois in?", correctAnswer: "Midwest", distractors: ["Southwest", "Northeast", "West"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🗺️\nWhich region are Georgia and Florida in?", correctAnswer: "Southeast", distractors: ["Northeast", "Midwest", "West"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🗺️\nWhich region are Oregon, Washington and California in?", correctAnswer: "West", distractors: ["Northeast", "Midwest", "Southeast"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌽\nWhich US region is famous for huge farms of corn and wheat, sometimes called America's Breadbasket?", correctAnswer: "Midwest", distractors: ["Northeast", "Southwest", "Southeast"], tier: .medium, grades: 4...6),
        // ── Grades 3–8 · State capitals ──
        BankQuestion(prompt: "🐻\nWhat is the capital of California?", correctAnswer: "Sacramento", distractors: ["Los Angeles", "San Francisco", "San Diego"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🤠\nWhat is the capital of Texas?", correctAnswer: "Austin", distractors: ["Houston", "Dallas", "San Antonio"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🍎\nWhat is the capital of New York State?", correctAnswer: "Albany", distractors: ["New York City", "Buffalo", "Rochester"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🍊\nWhat is the capital of Florida?", correctAnswer: "Tallahassee", distractors: ["Miami", "Orlando", "Tampa"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌽\nWhat is the capital of Illinois?", correctAnswer: "Springfield", distractors: ["Chicago", "Peoria", "Rockford"], tier: .medium, grades: 4...7),
        BankQuestion(prompt: "🔔\nWhat is the capital of Pennsylvania?", correctAnswer: "Harrisburg", distractors: ["Philadelphia", "Pittsburgh", "Erie"], tier: .medium, grades: 4...7),
        BankQuestion(prompt: "🦞\nWhat is the capital of Massachusetts?", correctAnswer: "Boston", distractors: ["Worcester", "Springfield", "Salem"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🍑\nWhat is the capital of Georgia?", correctAnswer: "Atlanta", distractors: ["Savannah", "Augusta", "Macon"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏔️\nWhat is the capital of Colorado?", correctAnswer: "Denver", distractors: ["Boulder", "Aspen", "Colorado Springs"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌵\nWhat is the capital of Arizona?", correctAnswer: "Phoenix", distractors: ["Tucson", "Flagstaff", "Yuma"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌲\nWhat is the capital of Washington State?", correctAnswer: "Olympia", distractors: ["Seattle", "Spokane", "Tacoma"], tier: .hard, grades: 4...7),
        BankQuestion(prompt: "🦫\nWhat is the capital of Oregon?", correctAnswer: "Salem", distractors: ["Portland", "Eugene", "Bend"], tier: .hard, grades: 4...7),
        BankQuestion(prompt: "🎰\nWhat is the capital of Nevada?", correctAnswer: "Carson City", distractors: ["Las Vegas", "Reno", "Henderson"], tier: .hard, grades: 4...7),
        BankQuestion(prompt: "🌺\nWhat is the capital of Hawaii?", correctAnswer: "Honolulu", distractors: ["Hilo", "Kahului", "Pearl City"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "❄️\nWhat is the capital of Alaska?", correctAnswer: "Juneau", distractors: ["Anchorage", "Fairbanks", "Nome"], tier: .hard, grades: 4...7),
        BankQuestion(prompt: "🌰\nWhat is the capital of Ohio?", correctAnswer: "Columbus", distractors: ["Cleveland", "Cincinnati", "Toledo"], tier: .medium, grades: 4...7),
        BankQuestion(prompt: "🚗\nWhat is the capital of Michigan?", correctAnswer: "Lansing", distractors: ["Detroit", "Grand Rapids", "Ann Arbor"], tier: .hard, grades: 4...7),
        BankQuestion(prompt: "🌄\nWhat is the capital of Tennessee?", correctAnswer: "Nashville", distractors: ["Memphis", "Knoxville", "Chattanooga"], tier: .medium, grades: 4...7),
        BankQuestion(prompt: "🎺\nWhat is the capital of Louisiana?", correctAnswer: "Baton Rouge", distractors: ["New Orleans", "Shreveport", "Lafayette"], tier: .hard, grades: 4...7),
        BankQuestion(prompt: "🏛️\nWhat is the capital of Virginia?", correctAnswer: "Richmond", distractors: ["Norfolk", "Virginia Beach", "Arlington"], tier: .hard, grades: 4...7),
        BankQuestion(prompt: "✈️\nWhat is the capital of North Carolina?", correctAnswer: "Raleigh", distractors: ["Charlotte", "Durham", "Asheville"], tier: .hard, grades: 4...7),
        BankQuestion(prompt: "🐝\nWhat is the capital of Utah?", correctAnswer: "Salt Lake City", distractors: ["Provo", "Ogden", "St. George"], tier: .medium, grades: 4...7),
        BankQuestion(prompt: "🛶\nWhat is the capital of Minnesota?", correctAnswer: "Saint Paul", distractors: ["Minneapolis", "Duluth", "Rochester"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🧀\nWhat is the capital of Wisconsin?", correctAnswer: "Madison", distractors: ["Milwaukee", "Green Bay", "Kenosha"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌉\nWhat is the capital of Missouri?", correctAnswer: "Jefferson City", distractors: ["St. Louis", "Kansas City", "Springfield"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🐴\nWhat is the capital of Kentucky?", correctAnswer: "Frankfort", distractors: ["Louisville", "Lexington", "Bowling Green"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏖️\nWhat is the capital of New Jersey?", correctAnswer: "Trenton", distractors: ["Newark", "Jersey City", "Atlantic City"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "⛵\nWhat is the capital of Maryland?", correctAnswer: "Annapolis", distractors: ["Baltimore", "Rockville", "Frederick"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "⚓\nWhat is the capital of Rhode Island?", correctAnswer: "Providence", distractors: ["Warwick", "Cranston", "Pawtucket"], tier: .medium, grades: 4...7),
        BankQuestion(prompt: "🍂\nWhat is the capital of New Hampshire?", correctAnswer: "Concord", distractors: ["Manchester", "Nashua", "Keene"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🥔\nWhat is the capital of Idaho?", correctAnswer: "Boise", distractors: ["Idaho Falls", "Pocatello", "Twin Falls"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🦌\nWhat is the capital of Montana?", correctAnswer: "Helena", distractors: ["Billings", "Missoula", "Bozeman"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌶️\nWhat is the capital of New Mexico?", correctAnswer: "Santa Fe", distractors: ["Albuquerque", "Las Cruces", "Roswell"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌴\nWhat is the capital of South Carolina?", correctAnswer: "Columbia", distractors: ["Charleston", "Greenville", "Myrtle Beach"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌾\nWhat is the capital of Iowa?", correctAnswer: "Des Moines", distractors: ["Cedar Rapids", "Davenport", "Sioux City"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌻\nWhat is the capital of Kansas?", correctAnswer: "Topeka", distractors: ["Wichita", "Kansas City", "Dodge City"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🍁\nWhat is the capital of Vermont?", correctAnswer: "Montpelier", distractors: ["Burlington", "Rutland", "Stowe"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🦞\nWhat is the capital of Maine?", correctAnswer: "Augusta", distractors: ["Portland", "Bangor", "Bar Harbor"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌳\nWhat is the capital of Connecticut?", correctAnswer: "Hartford", distractors: ["Waterbury", "Stamford", "Bridgeport"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🐓\nWhat is the capital of Delaware?", correctAnswer: "Dover", distractors: ["Wilmington", "Newark", "Lewes"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "💎\nWhat is the capital of Arkansas?", correctAnswer: "Little Rock", distractors: ["Fayetteville", "Fort Smith", "Hot Springs"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏈\nWhat is the capital of Alabama?", correctAnswer: "Montgomery", distractors: ["Birmingham", "Mobile", "Huntsville"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🎷\nWhat is the capital of Mississippi?", correctAnswer: "Jackson", distractors: ["Biloxi", "Gulfport", "Tupelo"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🦬\nWhat is the capital of Wyoming?", correctAnswer: "Cheyenne", distractors: ["Casper", "Laramie", "Rock Springs"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌾\nWhat is the capital of Nebraska?", correctAnswer: "Lincoln", distractors: ["Omaha", "Grand Island", "Kearney"], tier: .hard, grades: 5...8),
        // ── Grades 3–8 · World capitals ──
        BankQuestion(prompt: "🏙️\nWhat is the capital of France?", correctAnswer: "Paris", distractors: ["Marseille", "Lyon", "Nice"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "🏙️\nWhat is the capital of the United Kingdom?", correctAnswer: "London", distractors: ["Manchester", "Liverpool", "Birmingham"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Italy?", correctAnswer: "Rome", distractors: ["Milan", "Venice", "Florence"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Spain?", correctAnswer: "Madrid", distractors: ["Barcelona", "Seville", "Valencia"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Germany?", correctAnswer: "Berlin", distractors: ["Munich", "Hamburg", "Frankfurt"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Japan?", correctAnswer: "Tokyo", distractors: ["Seoul", "Beijing", "Bangkok"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "🏙️\nWhat is the capital of China?", correctAnswer: "Beijing", distractors: ["Shanghai", "Hong Kong", "Tokyo"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Canada?", correctAnswer: "Ottawa", distractors: ["Toronto", "Vancouver", "Montreal"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Egypt?", correctAnswer: "Cairo", distractors: ["Alexandria", "Giza", "Aswan"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Brazil?", correctAnswer: "Brasília", distractors: ["Rio de Janeiro", "São Paulo", "Salvador"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Australia?", correctAnswer: "Canberra", distractors: ["Sydney", "Melbourne", "Perth"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Russia?", correctAnswer: "Moscow", distractors: ["St. Petersburg", "Kyiv", "Minsk"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏙️\nWhat is the capital of India?", correctAnswer: "New Delhi", distractors: ["Mumbai", "Bengaluru", "Kolkata"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Argentina?", correctAnswer: "Buenos Aires", distractors: ["Santiago", "Montevideo", "Lima"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏙️\nWhat is the capital of New Zealand?", correctAnswer: "Wellington", distractors: ["Auckland", "Christchurch", "Queenstown"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of South Korea?", correctAnswer: "Seoul", distractors: ["Busan", "Tokyo", "Bangkok"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Greece?", correctAnswer: "Athens", distractors: ["Rome", "Istanbul", "Sparta"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Portugal?", correctAnswer: "Lisbon", distractors: ["Madrid", "Porto", "Barcelona"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🏙️\nWhat is the capital of the Netherlands?", correctAnswer: "Amsterdam", distractors: ["Brussels", "Berlin", "Copenhagen"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🏛️\nWhich city is the seat of Switzerland's government?", correctAnswer: "Bern", distractors: ["Zurich", "Geneva", "Vienna"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Austria?", correctAnswer: "Vienna", distractors: ["Bern", "Munich", "Prague"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Sweden?", correctAnswer: "Stockholm", distractors: ["Oslo", "Copenhagen", "Helsinki"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Norway?", correctAnswer: "Oslo", distractors: ["Stockholm", "Copenhagen", "Reykjavík"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Denmark?", correctAnswer: "Copenhagen", distractors: ["Oslo", "Stockholm", "Amsterdam"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Finland?", correctAnswer: "Helsinki", distractors: ["Oslo", "Stockholm", "Tallinn"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Ireland?", correctAnswer: "Dublin", distractors: ["London", "Edinburgh", "Cork"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Iceland?", correctAnswer: "Reykjavík", distractors: ["Oslo", "Dublin", "Helsinki"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Poland?", correctAnswer: "Warsaw", distractors: ["Prague", "Budapest", "Kraków"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Hungary?", correctAnswer: "Budapest", distractors: ["Warsaw", "Prague", "Vienna"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of the Czech Republic?", correctAnswer: "Prague", distractors: ["Vienna", "Warsaw", "Budapest"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Belgium?", correctAnswer: "Brussels", distractors: ["Amsterdam", "Paris", "Luxembourg"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Thailand?", correctAnswer: "Bangkok", distractors: ["Seoul", "Hanoi", "Manila"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Vietnam?", correctAnswer: "Hanoi", distractors: ["Bangkok", "Ho Chi Minh City", "Manila"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of the Philippines?", correctAnswer: "Manila", distractors: ["Hanoi", "Bangkok", "Jakarta"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Peru?", correctAnswer: "Lima", distractors: ["Bogotá", "Santiago", "Quito"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Chile?", correctAnswer: "Santiago", distractors: ["Lima", "Buenos Aires", "Caracas"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Colombia?", correctAnswer: "Bogotá", distractors: ["Lima", "Caracas", "Medellín"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Cuba?", correctAnswer: "Havana", distractors: ["San Juan", "Santo Domingo", "Kingston"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Kenya?", correctAnswer: "Nairobi", distractors: ["Mombasa", "Addis Ababa", "Kampala"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Nigeria?", correctAnswer: "Abuja", distractors: ["Lagos", "Accra", "Nairobi"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of Saudi Arabia?", correctAnswer: "Riyadh", distractors: ["Mecca", "Jeddah", "Medina"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🏙️\nWhat is the capital of the United Arab Emirates?", correctAnswer: "Abu Dhabi", distractors: ["Dubai", "Sharjah", "Doha"], tier: .hard, grades: 7...8),
        // ── Grades 3–7 · Famous places ──
        BankQuestion(prompt: "🗼\nIn which city is the Eiffel Tower?", correctAnswer: "Paris", distractors: ["London", "Rome", "Berlin"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧱\nIn which country is the Great Wall?", correctAnswer: "China", distractors: ["Japan", "India", "Egypt"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔺\nIn which country are the Great Pyramids of Giza?", correctAnswer: "Egypt", distractors: ["Mexico", "Greece", "India"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "🕌\nIn which country is the Taj Mahal?", correctAnswer: "India", distractors: ["China", "Egypt", "Thailand"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏟️\nIn which city is the ancient Colosseum?", correctAnswer: "Rome", distractors: ["Athens", "Paris", "Madrid"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🕰️\nIn which city is the famous clock tower called Big Ben?", correctAnswer: "London", distractors: ["Paris", "New York City", "Sydney"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🎭\nIn which country is the Sydney Opera House?", correctAnswer: "Australia", distractors: ["New Zealand", "England", "Canada"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "🏔️\nIn which country are the ancient Inca ruins of Machu Picchu?", correctAnswer: "Peru", distractors: ["Mexico", "Egypt", "China"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🗼\nIn which country is the Leaning Tower of Pisa?", correctAnswer: "Italy", distractors: ["France", "Spain", "Greece"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🙏\nIn which Brazilian city is the giant Christ the Redeemer statue?", correctAnswer: "Rio de Janeiro", distractors: ["São Paulo", "Brasília", "Buenos Aires"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🪨\nIn which country is Stonehenge?", correctAnswer: "England", distractors: ["France", "Egypt", "Greece"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🗿\nThe giant moai statues are on which island?", correctAnswer: "Easter Island", distractors: ["Hawaii", "Iceland", "Madagascar"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "⛪\nWhich tiny country inside the city of Rome is the smallest country in the world?", correctAnswer: "Vatican City", distractors: ["Monaco", "San Marino", "Luxembourg"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🛶\nWhich Italian city is famous for canals instead of streets?", correctAnswer: "Venice", distractors: ["Rome", "Milan", "Naples"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌷\nWhich European country is famous for windmills and tulips?", correctAnswer: "The Netherlands", distractors: ["Belgium", "Denmark", "Switzerland"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌉\nWhich city sits on two continents, Europe and Asia?", correctAnswer: "Istanbul", distractors: ["Ankara", "Athens", "Moscow"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "👢\nWhich European country is shaped like a boot?", correctAnswer: "Italy", distractors: ["Spain", "France", "Greece"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏛️\nIn which city is the ancient Parthenon temple?", correctAnswer: "Athens", distractors: ["Rome", "Cairo", "Paris"], tier: .medium, grades: 4...6),
        // ── Grades 4–8 · Rivers, mountains, deserts and lakes of the world ──
        BankQuestion(prompt: "🏞️\nWhich river is usually named the longest in the world?", correctAnswer: "Nile River", distractors: ["Mississippi River", "Thames River", "Danube River"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🐊\nWhich long river flows north through Egypt?", correctAnswer: "Nile River", distractors: ["Amazon River", "Danube River", "Yangtze River"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌧️\nWhich South American river carries more water than any other river on Earth?", correctAnswer: "Amazon River", distractors: ["Nile River", "Mississippi River", "Danube River"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌳\nThe largest tropical rain forest in the world is on which continent?", correctAnswer: "South America", distractors: ["Europe", "Australia", "North America"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏞️\nWhich river flows through London?", correctAnswer: "Thames River", distractors: ["Seine River", "Danube River", "Rhine River"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏞️\nWhich river flows through Paris?", correctAnswer: "Seine River", distractors: ["Thames River", "Rhine River", "Danube River"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏞️\nWhich long river flows through Vienna and Budapest?", correctAnswer: "Danube River", distractors: ["Seine River", "Thames River", "Nile River"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏞️\nWhich is the longest river in Asia?", correctAnswer: "Yangtze River", distractors: ["Ganges River", "Danube River", "Nile River"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏞️\nWhich is the longest river in Europe?", correctAnswer: "Volga River", distractors: ["Thames River", "Seine River", "Rhine River"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🙏\nWhich river in India is holy to many Hindus?", correctAnswer: "Ganges River", distractors: ["Amazon River", "Volga River", "Thames River"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏔️\nWhat is the tallest mountain on Earth above sea level?", correctAnswer: "Mount Everest", distractors: ["Mount Kilimanjaro", "Mount Fuji", "Mont Blanc"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏔️\nIn which mountain range is Mount Everest?", correctAnswer: "Himalayas", distractors: ["Alps", "Andes", "Rocky Mountains"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏔️\nWhich is the tallest mountain in Africa?", correctAnswer: "Mount Kilimanjaro", distractors: ["Mount Everest", "Mount Fuji", "Mont Blanc"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🗻\nWhich famous cone-shaped mountain is in Japan?", correctAnswer: "Mount Fuji", distractors: ["Mount Everest", "Mount Kilimanjaro", "Mont Blanc"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏔️\nWhich mountain range stretches along the western side of South America?", correctAnswer: "Andes Mountains", distractors: ["Alps", "Himalayas", "Rocky Mountains"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏔️\nWhich famous mountain range crosses France, Switzerland, Italy and Austria?", correctAnswer: "Alps", distractors: ["Himalayas", "Andes", "Ural Mountains"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🐫\nWhich huge hot desert covers much of northern Africa?", correctAnswer: "Sahara Desert", distractors: ["Gobi Desert", "Mojave Desert", "Atacama Desert"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏜️\nWhat is the largest hot desert in the world?", correctAnswer: "Sahara Desert", distractors: ["Gobi Desert", "Mojave Desert", "Sonoran Desert"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🥶\nWhich cold desert lies in China and Mongolia?", correctAnswer: "Gobi Desert", distractors: ["Sahara Desert", "Mojave Desert", "Kalahari Desert"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌵\nWhich desert in Chile is one of the driest places on Earth?", correctAnswer: "Atacama Desert", distractors: ["Sahara Desert", "Gobi Desert", "Mojave Desert"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌊\nWhich is the largest lake in the world by area?", correctAnswer: "Caspian Sea", distractors: ["Lake Titicaca", "Lake Victoria", "Lake Baikal"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "💎\nWhich lake in Russia is the deepest lake in the world?", correctAnswer: "Lake Baikal", distractors: ["Lake Victoria", "Caspian Sea", "Lake Superior"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🦛\nWhich is the largest lake in Africa?", correctAnswer: "Lake Victoria", distractors: ["Lake Baikal", "Caspian Sea", "Lake Titicaca"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🚢\nWhich canal connects the Atlantic and Pacific Oceans?", correctAnswer: "Panama Canal", distractors: ["Suez Canal", "Erie Canal", "Strait of Gibraltar"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🚢\nWhich canal connects the Mediterranean Sea and the Red Sea?", correctAnswer: "Suez Canal", distractors: ["Panama Canal", "Erie Canal", "Bering Strait"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "⛵\nWhich strait separates Spain from Africa?", correctAnswer: "Strait of Gibraltar", distractors: ["Bering Strait", "Panama Canal", "Suez Canal"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌍\nWhich is the largest country in the world by area?", correctAnswer: "Russia", distractors: ["China", "Canada", "Brazil"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "📏\nWhich country is the second-largest in the world by area?", correctAnswer: "Canada", distractors: ["Mexico", "Brazil", "India"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌎\nWhich is the largest country in South America?", correctAnswer: "Brazil", distractors: ["Argentina", "Chile", "Peru"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🗺️\nWhich long, narrow country stretches along the west coast of South America?", correctAnswer: "Chile", distractors: ["Brazil", "Argentina", "Paraguay"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌋\nWhich island country in the North Atlantic is known for glaciers and volcanoes?", correctAnswer: "Iceland", distractors: ["Ireland", "Portugal", "Cuba"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏝️\nWhat is the largest island in the world?", correctAnswer: "Greenland", distractors: ["New Guinea", "Madagascar", "Iceland"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🧭\nWhich island country lies just west of Great Britain?", correctAnswer: "Ireland", distractors: ["Iceland", "Norway", "Portugal"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏛️\nWhich ancient civilization built great cities in what is now Mexico and Central America?", correctAnswer: "The Maya", distractors: ["The Vikings", "The Romans", "The Greeks"], tier: .hard, grades: 5...7),
        // ── Grades 3–8 · Globe lines, hemispheres and climate ──
        BankQuestion(prompt: "🌐\nWhat is the imaginary line around the middle of the Earth, halfway between the North and South Poles?", correctAnswer: "Equator", distractors: ["Prime Meridian", "Tropic of Cancer", "Arctic Circle"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧭\nOn which continent is the South Pole?", correctAnswer: "Antarctica", distractors: ["Australia", "South America", "Africa"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "🌐\nThe equator divides the Earth into which two halves?", correctAnswer: "Northern and Southern Hemispheres", distractors: ["Eastern and Western Hemispheres", "Day and night sides", "Land and water halves"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌐\nThe Prime Meridian and the 180° line divide the Earth into which two halves?", correctAnswer: "Eastern and Western Hemispheres", distractors: ["Northern and Southern Hemispheres", "Arctic and Antarctic halves", "Land and water halves"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🇺🇸\nMost of the United States is in which two hemispheres?", correctAnswer: "Northern and Western", distractors: ["Southern and Western", "Northern and Eastern", "Southern and Eastern"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🦘\nAustralia is in which two hemispheres?", correctAnswer: "Southern and Eastern", distractors: ["Northern and Eastern", "Southern and Western", "Northern and Western"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "📏\nLines that run east and west around the globe and measure distance north or south of the equator are called... ?", correctAnswer: "Lines of latitude", distractors: ["Lines of longitude", "Contour lines", "Time zones"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "📏\nLines that run from the North Pole to the South Pole and measure distance east or west are called... ?", correctAnswer: "Lines of longitude", distractors: ["Lines of latitude", "Parallels", "Contour lines"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌐\nWhat is the latitude of the equator?", correctAnswer: "0°", distractors: ["45°", "90°", "180°"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🧊\nWhat is the latitude of the North Pole?", correctAnswer: "90° N", distractors: ["0°", "45° N", "180° N"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🧭\nWhat is the name of the 0° line of longitude that passes through Greenwich, England?", correctAnswer: "Prime Meridian", distractors: ["Equator", "International Date Line", "Tropic of Capricorn"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "📅\nWhich imaginary line near 180° longitude is where the calendar day changes?", correctAnswer: "International Date Line", distractors: ["Prime Meridian", "Equator", "Arctic Circle"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌞\nWhat is the name of the line of latitude at about 23.5° north of the equator?", correctAnswer: "Tropic of Cancer", distractors: ["Tropic of Capricorn", "Arctic Circle", "Prime Meridian"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🌞\nWhat is the name of the line of latitude at about 23.5° south of the equator?", correctAnswer: "Tropic of Capricorn", distractors: ["Tropic of Cancer", "Antarctic Circle", "Equator"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "📍\nWhich of these is written as latitude and longitude?", correctAnswer: "40° N, 74° W", distractors: ["40 miles north", "Grid square B4", "Zone 5"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "📍\nHow many degrees is one full trip around the Earth along the equator?", correctAnswer: "360°", distractors: ["90°", "100°", "180°"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "📍\nA city is at 35° S latitude. Which hemisphere is it in?", correctAnswer: "Southern Hemisphere", distractors: ["Northern Hemisphere", "Eastern Hemisphere", "Western Hemisphere"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "📍\nWhich latitude is closest to the equator?", correctAnswer: "10° N", distractors: ["30° N", "60° N", "80° N"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌐\nWhat kind of climate is found near the equator?", correctAnswer: "Tropical, hot and often rainy", distractors: ["Polar, very cold", "Cold and snowy all year", "Cool and foggy all year"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🗺️\nWhat kind of climate is found in the Arctic and in Antarctica?", correctAnswer: "Polar, very cold", distractors: ["Tropical, hot and rainy", "Desert, hot and dry", "Mild and warm all year"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🍂\nMost of the United States has warm summers and cold winters. What is this climate zone called?", correctAnswer: "Temperate", distractors: ["Polar", "Tropical", "Equatorial"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌡️\nIn general, what happens to temperatures as you move away from the equator toward the poles?", correctAnswer: "They get colder", distractors: ["They get hotter", "They stay the same", "They change every hour"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏔️\nWhy is it colder at the top of a tall mountain than at the bottom?", correctAnswer: "The air is thinner up high and holds less heat", distractors: ["The top is closer to the ocean", "The sun is farther from the top", "Mountains make their own ice"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🎄\nWhen it is winter in the United States, what season is it in Australia?", correctAnswer: "Summer", distractors: ["Winter", "Spring", "Fall"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌍\nWhy do we have seasons on Earth?", correctAnswer: "Earth is tilted as it travels around the sun", distractors: ["The sun turns on and off", "The Moon blocks the sun", "Earth gets closer to the stars"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌅\nWhy does the sun seem to rise in the east?", correctAnswer: "Earth spins from west to east", distractors: ["The sun circles the Earth", "Earth spins from east to west", "The Moon pushes the sun"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌧️\nWhat is the name for the strong seasonal winds that bring heavy summer rain to India?", correctAnswer: "Monsoon", distractors: ["Tornado", "Blizzard", "Drought"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "☔\nWhat is weather?", correctAnswer: "The conditions outside on a certain day", distractors: ["The average weather over many years", "A kind of map", "A mountain range"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📆\nWhat is climate?", correctAnswer: "The usual weather of a place over many years", distractors: ["The weather today", "One rainstorm", "The time on a clock"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏜️\nWhat do we call a long period with very little rain?", correctAnswer: "Drought", distractors: ["Flood", "Monsoon", "Blizzard"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "💨\nWhat do we call a huge storm that forms over warm ocean water, with very strong winds?", correctAnswer: "Hurricane", distractors: ["Blizzard", "Drought", "Earthquake"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⛈️\nWhat do we call a spinning column of wind that reaches down from a thunderstorm to the ground?", correctAnswer: "Tornado", distractors: ["Hurricane", "Monsoon", "Tsunami"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🌋\nWhat do we call the huge moving pieces of Earth's outer shell?", correctAnswer: "Tectonic plates", distractors: ["Latitude lines", "Continents of ice", "Time zones"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "⚠️\nWhat do we call a series of giant ocean waves often caused by an undersea earthquake?", correctAnswer: "Tsunami", distractors: ["Tornado", "Hurricane", "Monsoon"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌋\nThe zone of many volcanoes and earthquakes around the Pacific Ocean is called the... ?", correctAnswer: "Ring of Fire", distractors: ["Great Divide", "Tropic Zone", "Bermuda Belt"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🌎\nLong ago all the continents were joined in one supercontinent. What is it called?", correctAnswer: "Pangaea", distractors: ["Atlantis", "Eurasia", "Arabia"], tier: .hard, grades: 6...8),
        // ── Grades 5–8 · People and places ──
        BankQuestion(prompt: "🌱\nWhy have many big cities grown up next to rivers and coasts?", correctAnswer: "For water, trade and transportation", distractors: ["Because it never rains there", "Because rivers keep cities cold", "Because mountains are nearby"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌾\nWhy do many farms lie on river plains and deltas?", correctAnswer: "The soil is rich and water is nearby", distractors: ["The land is too steep to build on", "It never floods there", "Crops grow best on rocks"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏙️\nWhen many people move from the countryside to cities, it is called... ?", correctAnswer: "Urbanization", distractors: ["Erosion", "Irrigation", "Deforestation"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🪓\nWhat do we call clearing away huge areas of trees for farms, roads or lumber?", correctAnswer: "Deforestation", distractors: ["Irrigation", "Urbanization", "Migration"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "💧\nWhat do we call bringing water to farm fields through pipes or ditches?", correctAnswer: "Irrigation", distractors: ["Erosion", "Pollution", "Migration"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏞️\nWhat do we call the slow wearing away of rock and soil by wind and water?", correctAnswer: "Erosion", distractors: ["Irrigation", "Eruption", "Migration"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🚶\nWhat do we call people moving from one place or country to live in another?", correctAnswer: "Migration", distractors: ["Erosion", "Irrigation", "Latitude"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🧭\nWhich country lies directly between the United States and Guatemala?", correctAnswer: "Mexico", distractors: ["Canada", "Cuba", "Brazil"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🏝️\nWhich island country lies about 90 miles south of Florida?", correctAnswer: "Cuba", distractors: ["Iceland", "Ireland", "Japan"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌎\nWhich US territory in the Caribbean has San Juan as its capital?", correctAnswer: "Puerto Rico", distractors: ["Guam", "Hawaii", "Cuba"], tier: .hard, grades: 5...8),
    ]
}
