import Foundation

/// ⚽ Soccer world — English (US). Adapted from QuestionBanksSoccer (Hebrew).
/// Timeless facts only: rules, positions, the field, settled World Cup history,
/// US national team history, MLS basics and soccer math. Israeli clubs, stadiums
/// and leagues were replaced with US/MLS equivalents; open-ended records are dated.
extension EnglishContent {
    static let soccer: [BankQuestion] = [
        // ── Rules and words ──
        BankQuestion(prompt: "⚽\nIn a professional game, how many players from each team are on the field at the same time?", correctAnswer: "11", distractors: ["9", "10", "12"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "✋\nWhich player is allowed to catch the ball with their hands?", correctAnswer: "Goalkeeper", distractors: ["Forward", "Midfielder", "Defender"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⚽\nWhat is it called when the ball goes into the net?", correctAnswer: "A goal", distractors: ["A corner kick", "A penalty kick", "A time-out"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🚫\nField players are not allowed to touch the ball with which body part?", correctAnswer: "Their hands", distractors: ["Their feet", "Their head", "Their chest"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🃏\nWhich color card sends a player out of the game?", correctAnswer: "Red", distractors: ["Yellow", "Green", "Blue"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🃏\nWhat does a player get as a warning for a foul that is not too serious?", correctAnswer: "A yellow card", distractors: ["A red card", "A penalty kick", "A corner kick"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "📣\nWho blows the whistle and makes the calls in a game?", correctAnswer: "The referee", distractors: ["The coach", "The goalkeeper", "The captain"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⏱️\nHow many halves are there in a soccer game?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⏱️\nIn a professional adult game, how many minutes long is one half?", correctAnswer: "45", distractors: ["30", "60", "90"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "⏱️\nHow many minutes long is a regular professional game, not counting added time?", correctAnswer: "90", distractors: ["60", "100", "120"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎯\nWhat is the kick taken from the penalty spot, with only the goalkeeper to beat?", correctAnswer: "A penalty kick", distractors: ["A corner kick", "A free kick", "A throw-in"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "⚽\nThe ball goes out over the sideline. How is it put back into play?", correctAnswer: "A throw-in", distractors: ["A penalty kick", "A goal kick", "A drop ball"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "⚽\nThe ball goes out over the goal line, not into the goal, and a defender touched it last. What does the attacking team get?", correctAnswer: "A corner kick", distractors: ["A penalty kick", "A throw-in", "A goal kick"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⚡\nWhat do you call the player whose main job is to score goals?", correctAnswer: "Forward", distractors: ["Goalkeeper", "Defender", "Referee"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "⚽\nWhat do you call a field player whose main job is to stop the other team from scoring?", correctAnswer: "Defender", distractors: ["Forward", "Referee", "Coach"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎟️\nWhat do you call a big soccer field with seats for lots of fans?", correctAnswer: "A stadium", distractors: ["A gym", "A pool", "A garden"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🥅\nHow many goals are there on a soccer field?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🤝\nWhat is a \"pass\"?", correctAnswer: "A player sends the ball to a teammate", distractors: ["A player shoots at the goal", "The referee blows the whistle", "The fans clap"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🤝\nThe final score is 2 to 2. How did the game end?", correctAnswer: "In a tie", distractors: ["In a win", "In a loss", "In a penalty kick"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧢\nWhat do you call the player who leads the team and wears a band on their arm?", correctAnswer: "Captain", distractors: ["Goalkeeper", "Referee", "Coach"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔁\nWhat is it called when one player leaves the field and another player comes in for them?", correctAnswer: "A substitution", distractors: ["A penalty", "Offside", "A corner kick"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎯\nWhat is it called when one player scores 3 goals in the same game?", correctAnswer: "A hat trick", distractors: ["A derby", "Offside", "A penalty"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "😬\nA player accidentally scores into their own team's goal. What is that called?", correctAnswer: "An own goal", distractors: ["A hat trick", "A penalty kick", "Offside"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🟨🟨\nA player gets a second yellow card in the same game. What happens?", correctAnswer: "They get a red card and must leave", distractors: ["They keep playing", "The other team gets a penalty kick", "The game is over"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "📏\nAbout how long is a full-size soccer field?", correctAnswer: "About 100 yards", distractors: ["About 10 yards", "About 30 yards", "About 1,000 yards"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "📺\nWhat is VAR?", correctAnswer: "A video referee who helps the referee on the field", distractors: ["A kind of soccer cleat", "The name of a stadium", "A special kind of kick"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⏱️\nA World Cup knockout game is tied after 90 minutes. How long is extra time?", correctAnswer: "30 minutes", distractors: ["10 minutes", "45 minutes", "90 minutes"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🎯\nA World Cup knockout game is still tied after extra time. What decides the winner?", correctAnswer: "A penalty shootout", distractors: ["A coin toss", "Another game tomorrow", "The team with more corner kicks"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🚫\nWhat is \"offside\"?", correctAnswer: "An attacker is closer to the goal than the last defender when a teammate passes to them", distractors: ["The ball went out of the field", "A player touched the ball with a hand", "A kick that was too hard"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌍\nIn many countries, people call a soccer field a…", correctAnswer: "Pitch", distractors: ["Court", "Rink", "Diamond"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🙆\nWhat is a \"header\"?", correctAnswer: "Hitting the ball with your head", distractors: ["Kicking the ball very high", "The goalkeeper catching the ball", "The first goal of the game"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧤\nA goalkeeper keeps a \"clean sheet.\" What does that mean?", correctAnswer: "Their team let in no goals", distractors: ["Their uniform stayed clean", "They scored a goal", "They got a yellow card"], tier: .hard, grades: 4...6),

        // ── Teams and places ──
        BankQuestion(prompt: "🇺🇸\nThe Sounders are an MLS team. In which city do they play?", correctAnswer: "Seattle", distractors: ["Portland", "Denver", "Miami"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🇺🇸\nIn which state does the LA Galaxy play?", correctAnswer: "California", distractors: ["Texas", "Florida", "New York"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "⚽\nMLS has teams from the United States and one other country. In which country does Toronto FC play?", correctAnswer: "Canada", distractors: ["Mexico", "England", "Brazil"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nWhat is the top professional soccer league in the United States called?", correctAnswer: "Major League Soccer", distractors: ["The Premier League", "La Liga", "The Bundesliga"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nWhat is the championship game of Major League Soccer (MLS) called?", correctAnswer: "MLS Cup", distractors: ["The Super Bowl", "The World Series", "The Stanley Cup Final"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏙️\nWhat is a game between two teams from the same city often called?", correctAnswer: "A derby", distractors: ["A penalty", "A World Cup", "A hat trick"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏟️\nThe Rose Bowl, where the 1994 World Cup final was played, is in which state?", correctAnswer: "California", distractors: ["Florida", "New York", "Texas"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⚽\nIn which country does FC Barcelona play?", correctAnswer: "Spain", distractors: ["Italy", "France", "Portugal"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "⚽\nIn which city does Real Madrid play?", correctAnswer: "Madrid", distractors: ["Barcelona", "London", "Paris"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "⚽\nIn which country does Manchester United play?", correctAnswer: "England", distractors: ["Germany", "Spain", "Netherlands"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⚽\nIn which country does Bayern Munich play?", correctAnswer: "Germany", distractors: ["Austria", "Italy", "Belgium"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⚽\nIn which country does Juventus play?", correctAnswer: "Italy", distractors: ["Spain", "France", "Greece"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⚽\nIn which city does Paris Saint-Germain play?", correctAnswer: "Paris", distractors: ["Marseille", "London", "Rome"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏆\nWhat is the top league in England called?", correctAnswer: "The Premier League", distractors: ["La Liga", "Serie A", "The Bundesliga"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nWhat is the top league in Spain called?", correctAnswer: "La Liga", distractors: ["The Premier League", "Serie A", "Ligue 1"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⭐\nThe UEFA Champions League is a competition for…", correctAnswer: "Top club teams from Europe", distractors: ["National teams from different countries", "Kids' teams", "Teams from the United States only"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⭐\nWhich club won the first five European Cups in a row, from 1956 to 1960?", correctAnswer: "Real Madrid", distractors: ["Barcelona", "Liverpool", "AC Milan"], tier: .hard, grades: 4...6),

        // ── National teams, the World Cup and famous players ──
        BankQuestion(prompt: "👕\nWhat color is Brazil's famous national team jersey?", correctAnswer: "Yellow", distractors: ["Red", "Blue", "Black"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "👕\nWhat colors is Argentina's national team jersey?", correctAnswer: "Light blue and white", distractors: ["Red and black", "Green and yellow", "Blue and red"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nIn which country was Lionel Messi born?", correctAnswer: "Argentina", distractors: ["Brazil", "Spain", "Portugal"], tier: .easy, grades: 2...6),
        BankQuestion(prompt: "🌍\nIn which country was Cristiano Ronaldo born?", correctAnswer: "Portugal", distractors: ["Spain", "Brazil", "Italy"], tier: .easy, grades: 2...6),
        BankQuestion(prompt: "👑\nWhich country was Pelé, \"the King of Soccer,\" from?", correctAnswer: "Brazil", distractors: ["Argentina", "Portugal", "Mexico"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "👕\nWhich famous shirt number did Pelé wear for Brazil?", correctAnswer: "10", distractors: ["1", "5", "99"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nHow often is the men's World Cup held?", correctAnswer: "Every 4 years", distractors: ["Every 2 years", "Every 3 years", "Every 5 years"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nWhat is the World Cup?", correctAnswer: "A world championship for national teams", distractors: ["A league for teams from Spain", "A game between two cities", "A contest just for kids"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏆\nUp to 2022, which country had won the men's World Cup the most times?", correctAnswer: "Brazil", distractors: ["Germany", "Argentina", "Italy"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nWhich country won the 2022 World Cup?", correctAnswer: "Argentina", distractors: ["France", "Brazil", "Germany"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nWhich country won the 2018 World Cup?", correctAnswer: "France", distractors: ["Croatia", "Brazil", "Spain"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nWhich country won the 2014 World Cup, which was held in Brazil?", correctAnswer: "Germany", distractors: ["Brazil", "Argentina", "Netherlands"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nWhich country won the 2010 World Cup?", correctAnswer: "Spain", distractors: ["Netherlands", "Germany", "Italy"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥇\nWhich country won the very first World Cup, in 1930?", correctAnswer: "Uruguay", distractors: ["Brazil", "Italy", "England"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🌍\nIn which country was the 2022 World Cup held?", correctAnswer: "Qatar", distractors: ["Russia", "Brazil", "Japan"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇺🇸\nIn which year did the United States host the men's World Cup for the first time?", correctAnswer: "1994", distractors: ["1986", "2002", "2010"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nWhich country won the 1994 World Cup, held in the United States?", correctAnswer: "Brazil", distractors: ["United States", "Germany", "France"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌎\nWhich three countries hosted the 2026 World Cup together?", correctAnswer: "United States, Canada and Mexico", distractors: ["United States, Brazil and Argentina", "Canada, England and France", "Mexico, Spain and Italy"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔢\nThe 2026 World Cup was the first one with how many teams?", correctAnswer: "48", distractors: ["16", "24", "32"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇺🇸\nIn which year did the US women's team win the very first Women's World Cup?", correctAnswer: "1991", distractors: ["1975", "2003", "2011"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇺🇸\nThe US women's team won the 1999 Women's World Cup final at home. Which country did they beat?", correctAnswer: "China", distractors: ["Brazil", "Japan", "England"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇺🇸\nHow many Women's World Cups did the US women's team win from 1991 to 2019?", correctAnswer: "4", distractors: ["1", "2", "7"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⭐\nMia Hamm is a famous soccer star. Which national team did she play for?", correctAnswer: "United States", distractors: ["Canada", "Germany", "Brazil"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🥇\nBy the end of the 2022 World Cup, who had scored the most goals in World Cup history?", correctAnswer: "Miroslav Klose", distractors: ["Pelé", "Lionel Messi", "Cristiano Ronaldo"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "📜\nIn which country were the rules of modern soccer first written down?", correctAnswer: "England", distractors: ["Brazil", "Italy", "Greece"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌎\nOn which continent is Brazil?", correctAnswer: "South America", distractors: ["Europe", "Africa", "Asia"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nOn which continent is Germany?", correctAnswer: "Europe", distractors: ["Asia", "South America", "Australia"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nThe 2010 World Cup was held in South Africa. On which continent is that?", correctAnswer: "Africa", distractors: ["Europe", "Asia", "South America"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇪🇺\nHow often is the European Championship (the Euro) for national teams held?", correctAnswer: "Every 4 years", distractors: ["Every year", "Every 2 years", "Every 6 years"], tier: .hard, grades: 4...6),

        // ── Soccer math ──
        BankQuestion(prompt: "🔢\nThe Lions scored 3 goals and the Hawks scored 1. By how many goals did the Lions win?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔢\nA game ended 4 to 2. How many goals were scored in all?", correctAnswer: "6", distractors: ["2", "4", "8"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔢\nAt halftime the score was 1 to 0. The final score was 3 to 1. How many goals were scored in the second half?", correctAnswer: "3", distractors: ["2", "4", "1"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔢\nA win is worth 3 points and a tie is worth 1 point. A team won twice and tied once. How many points does it have?", correctAnswer: "7", distractors: ["6", "5", "9"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔢\nA win is worth 3 points and a loss is worth 0. A team won 5 games and lost 2. How many points does it have?", correctAnswer: "15", distractors: ["7", "10", "21"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔢\nAt the 2014 World Cup, Germany beat Brazil 7 to 1. By how many goals did Germany win?", correctAnswer: "6", distractors: ["7", "8", "5"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⏱️\nA game starts at 8:00 PM. It has 90 minutes of play and a 15-minute halftime. At about what time does it end?", correctAnswer: "9:45 PM", distractors: ["9:30 PM", "10:00 PM", "9:00 PM"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nA player scored 12 goals in 8 games. How many goals is that per game, on average?", correctAnswer: "1.5", distractors: ["1", "2", "4"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🔢\nA league has 4 teams, and every team plays each of the others once. How many games are there in all?", correctAnswer: "6", distractors: ["4", "8", "12"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🔢\nA team scored 2 goals in each of 6 games. How many goals is that in all?", correctAnswer: "12", distractors: ["8", "10", "14"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⏱️\nThe referee added 4 minutes to a 45-minute second half. How many minutes long was that half?", correctAnswer: "49", distractors: ["45", "50", "94"], tier: .medium, grades: 3...5),

        // ── 1st grade · basics, shapes, colors and math to 10 ──
        BankQuestion(prompt: "⚽\nWhat shape is a soccer ball?", correctAnswer: "Round", distractors: ["Square", "Triangle", "Heart"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nWhere do you have to kick the ball to score?", correctAnswer: "Into the goal", distractors: ["Into the basket", "Into the pool", "Into the mailbox"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nWhich body part do you use to kick the ball?", correctAnswer: "Your foot", distractors: ["Your ear", "Your nose", "Your belly"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🥅\nWho guards the goal?", correctAnswer: "The goalkeeper", distractors: ["The forward", "The coach", "The fans"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "👕\nHow many teams play in one game?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nWhat hangs behind the goal and catches the ball?", correctAnswer: "A net", distractors: ["A blanket", "A curtain", "A rug"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nHow many balls do you play with in one game?", correctAnswer: "One", distractors: ["Two", "Three", "Ten"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nWhat color is the grass on the field?", correctAnswer: "Green", distractors: ["Red", "Blue", "Purple"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "📣\nWho blows the whistle in the game?", correctAnswer: "The referee", distractors: ["The goalkeeper", "The fans", "The coach"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🃏\nWhich color card is a warning?", correctAnswer: "Yellow", distractors: ["Blue", "Green", "White"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏟️\nWhat do you call the place where you play soccer?", correctAnswer: "A field", distractors: ["A pool", "A classroom", "A kitchen"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "👟\nWhat special shoes do soccer players wear?", correctAnswer: "Cleats", distractors: ["Flippers", "Mittens", "Slippers"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⏱️\nA soccer game is split into how many parts?", correctAnswer: "Two", distractors: ["One", "Three", "Ten"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧤\nWhich player wears special gloves to catch the ball?", correctAnswer: "The goalkeeper", distractors: ["The forward", "The referee", "The coach"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🎉\nWhat does the team that wins the tournament get?", correctAnswer: "A trophy", distractors: ["A ball", "A card", "A whistle"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🦵\nHow many legs does one player have?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "↩️\nThe ball rolls out over the sideline. What happens next?", correctAnswer: "A player throws it back in", distractors: ["The game ends", "Everyone gets a new ball", "Everyone goes home"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🤝\nWhat is a kind thing to say to the team that lost?", correctAnswer: "Good game!", distractors: ["You lost!", "Ha ha!", "Go home!"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\nA team scores 1 goal and then 1 more goal. How many goals is that?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\n2 goals and 1 more goal. How many goals in all?", correctAnswer: "3", distractors: ["2", "4", "5"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\n3 goals and 2 more goals. How many goals?", correctAnswer: "5", distractors: ["4", "6", "7"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "⚽\n4 goals and 3 more goals. How many goals?", correctAnswer: "7", distractors: ["6", "8", "9"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "⚽\n5 goals and 5 more goals. How many goals?", correctAnswer: "10", distractors: ["9", "11", "15"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nIn the first half there were 6 goals, but the referee said 2 of them did not count. How many goals counted?", correctAnswer: "4", distractors: ["3", "5", "8"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nThere were 5 balls on the field, and 3 rolled away. How many are left?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔢\n7 players were on the field, and 4 went to rest. How many are still on the field?", correctAnswer: "3", distractors: ["2", "4", "5"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🧮\n10 players are on the field, plus the goalkeeper. How many players does the team have on the field?", correctAnswer: "11", distractors: ["10", "12", "9"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🥇\nThe blue team scored 3 goals and the red team scored 1. Who won?", correctAnswer: "The blue team", distractors: ["The red team", "Neither team", "Both teams"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🤷\nEach team scored 2 goals. What do you call that score?", correctAnswer: "A tie", distractors: ["A win", "A loss", "A penalty"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "👋\nWhat do the players do at the end of the game?", correctAnswer: "Shake hands", distractors: ["Argue", "Run away", "Fall asleep"], tier: .easy, grades: 1...2),
    ]
}
