import Foundation

/// 🧩 Logic — English (US). Adapted from the `logic` lists in QuestionBanks,
/// QuestionBanksExpanded, QuestionBanksWorkflow, QuestionBanksWorkflow2 and
/// QuestionBanksWorkflow3 (Hebrew). Tiers for the older untiered items come from
/// QuestionDifficultyTags. Hebrew-alphabet series were rebuilt on A–Z; items that
/// repeated an earlier prompt were replaced with a fresh item of the same kind.
extension EnglishContent {
    static let logic: [BankQuestion] = [
        // ── From QuestionBanks ──
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 2, 3, ?", correctAnswer: "4", distractors: ["5", "6", "2"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n2, 4, 6, ?", correctAnswer: "8", distractors: ["7", "10", "9"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n5, 10, 15, ?", correctAnswer: "20", distractors: ["25", "16", "18"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n10, 9, 8, ?", correctAnswer: "7", distractors: ["6", "11", "5"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🧩\nWhat comes next?\n🔴🟢🔴🟢🔴 ?", correctAnswer: "🟢", distractors: ["🔴", "🔵", "🟡"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🧩\nWhat comes next?\n🐶🐱🐶🐱🐶 ?", correctAnswer: "🐱", distractors: ["🐶", "🐭", "🐰"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong?\n🐶 🚗 🐱 🐰", correctAnswer: "🚗", distractors: ["🐶", "🐱", "🐰"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong?\n🚗 🚌 🍎 🚲", correctAnswer: "🍎", distractors: ["🚗", "🚌", "🚲"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong?\n📖 ⚽ 🏀 🎾", correctAnswer: "📖", distractors: ["⚽", "🏀", "🎾"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong?\n☀️ 🌙 ⭐ 🌳", correctAnswer: "🌳", distractors: ["☀️", "🌙", "⭐"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🍎\nIf 🍎 = 2, then 🍎 + 🍎 = ?", correctAnswer: "4", distractors: ["3", "5", "2"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "⚖️\nIf 🐱 > 🐭, which one is bigger?", correctAnswer: "The cat", distractors: ["The mouse", "They are the same size", "You can't tell"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🔺\nWhat shape comes next?\n🔺🔻🔺🔻🔺 ?", correctAnswer: "🔻", distractors: ["🔺", "⬛", "⚫"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐕\nHow many legs do 3 dogs have?", correctAnswer: "12", distractors: ["6", "8", "10"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "👧\nMia is older than Lily, and Lily is older than Tom. Who is the oldest?", correctAnswer: "Mia", distractors: ["Lily", "Tom", "They are all the same age"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🔍\nWhich one is different?\n🍎 🍌 🐶 🍇", correctAnswer: "🐶", distractors: ["🍎", "🍌", "🍇"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "📅\nIf today is Tuesday, what day was yesterday?", correctAnswer: "Monday", distractors: ["Wednesday", "Sunday", "Thursday"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐦\n5 birds are sitting in a tree. 2 fly away. How many birds are left?", correctAnswer: "3", distractors: ["7", "2", "4"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🔤\nWhat letter comes next?\nA, B, C, ?", correctAnswer: "D", distractors: ["E", "A", "C"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "📐\nWhich shape has no corners?", correctAnswer: "⚪", distractors: ["🔺", "⬛", "⬢"], tier: .medium, grades: 0...2),

        // ── From QuestionBanksExpanded · sequences ──
        BankQuestion(prompt: "🔢\nWhat number comes next?\n2, 4, 6, 8, ?", correctAnswer: "10", distractors: ["9", "11", "12"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n5, 10, 15, 20, ?", correctAnswer: "25", distractors: ["22", "30", "24"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 4, 9, 16, ?", correctAnswer: "25", distractors: ["20", "24", "30"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐚\nWhat number comes next?\n1, 1, 2, 3, 5, ?", correctAnswer: "8", distractors: ["6", "7", "10"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n100, 90, 80, ?", correctAnswer: "70", distractors: ["75", "60", "85"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 3, 5, 7, ?", correctAnswer: "9", distractors: ["8", "10", "11"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n10, 20, 40, 80, ?", correctAnswer: "160", distractors: ["100", "120", "200"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔤\nWhat letter comes next?\nA, C, E, G, ?", correctAnswer: "I", distractors: ["H", "J", "K"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🔤\nWhat letter comes next?\nB, D, F, ?", correctAnswer: "H", distractors: ["G", "I", "J"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "🧩\nWhat comes next?\n🔴🔵🔴🔵🔴 ?", correctAnswer: "🔵", distractors: ["🔴", "🟢", "🟡"], tier: .easy, grades: 0...2),

        // ── From QuestionBanksExpanded · odd one out ──
        BankQuestion(prompt: "🤔\nWhich one does not belong: apple, basketball, banana, pear?", correctAnswer: "Basketball", distractors: ["Apple", "Banana", "Pear"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong: table, dog, cat, lion?", correctAnswer: "Table", distractors: ["Dog", "Cat", "Lion"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong: car, bicycle, bus, truck?", correctAnswer: "Bicycle", distractors: ["Car", "Bus", "Truck"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong: fish, shark, lion, dolphin?", correctAnswer: "Lion", distractors: ["Fish", "Shark", "Dolphin"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong: three, red, five, seven?", correctAnswer: "Red", distractors: ["Three", "Five", "Seven"], tier: .medium, grades: 0...2),

        // ── From QuestionBanksExpanded · comparisons ──
        BankQuestion(prompt: "📏\nWhich animal is the biggest?", correctAnswer: "Elephant", distractors: ["Mouse", "Ant", "Butterfly"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔍\nWhich animal is the smallest?", correctAnswer: "Ant", distractors: ["Horse", "Dog", "Cat"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🏁\nWhich one is the fastest?", correctAnswer: "Airplane", distractors: ["Bicycle", "Boat", "Train"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "⚖️\nWhich one is the heaviest?", correctAnswer: "Elephant", distractors: ["Feather", "Apple", "Book"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📐\nWhich animal is the tallest?", correctAnswer: "Giraffe", distractors: ["Dog", "Cat", "Rooster"], tier: .easy, grades: 0...2),

        // ── From QuestionBanksExpanded · riddles ──
        BankQuestion(prompt: "❓\nI drink water, but not from a cup. What am I?", correctAnswer: "A plant", distractors: ["A table", "A window", "A book"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "❓\nI have four legs, but I can't walk. What am I?", correctAnswer: "A table", distractors: ["A horse", "A dog", "A turtle"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "❓\nI shine in the night sky. I am not the sun, and sometimes I look like a thin slice. What am I?", correctAnswer: "The moon", distractors: ["A star", "A flashlight", "A lamp"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "❓\nI am orange, I grow under the ground, and I have green leaves on top. What am I?", correctAnswer: "A carrot", distractors: ["An apple", "A cucumber", "An orange"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "❓\nI have a spine but no bones. What am I?", correctAnswer: "A book", distractors: ["A fish", "A dog", "A snake"], tier: .hard, grades: 2...4),

        // ── From QuestionBanksExpanded · categories ──
        BankQuestion(prompt: "🎨\nWhich one is not a color?", correctAnswer: "Table", distractors: ["Red", "Blue", "Green"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐴\nWhich one is not an animal?", correctAnswer: "Car", distractors: ["Horse", "Dog", "Bird"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍌\nWhich one is not a fruit?", correctAnswer: "Potato", distractors: ["Apple", "Banana", "Orange"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🥦\nWhich one is not a vegetable?", correctAnswer: "Orange", distractors: ["Broccoli", "Carrot", "Lettuce"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "📅\nWhich one is not a day of the week?", correctAnswer: "January", distractors: ["Monday", "Tuesday", "Wednesday"], tier: .hard, grades: 0...2),

        // ── From QuestionBanksExpanded · if–then ──
        BankQuestion(prompt: "🐕\nAll dogs bark. Rex is a dog. What does Rex do?", correctAnswer: "He barks", distractors: ["He meows", "He moos", "He quacks"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "➕\nIf 2 + 2 = 4, then 3 + 3 = ?", correctAnswer: "6", distractors: ["5", "7", "8"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes after 7?", correctAnswer: "8", distractors: ["6", "9", "10"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes before 5?", correctAnswer: "4", distractors: ["6", "3", "7"], tier: .easy, grades: 0...2),

        // ── From QuestionBanksExpanded · time ──
        BankQuestion(prompt: "📅\nHow many days are in a week?", correctAnswer: "7", distractors: ["5", "6", "8"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🗓️\nHow many months are in a year?", correctAnswer: "12", distractors: ["10", "11", "13"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🕛\nHow many hours are in one whole day?", correctAnswer: "24", distractors: ["12", "18", "30"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "⏰\nHow many minutes are in an hour?", correctAnswer: "60", distractors: ["50", "100", "30"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "⏱️\nHow many seconds are in a minute?", correctAnswer: "60", distractors: ["100", "30", "12"], tier: .hard, grades: 2...4),

        // ── From QuestionBanksExpanded · opposites ──
        BankQuestion(prompt: "🐘\nWhat is the opposite of \"big\"?", correctAnswer: "Small", distractors: ["Long", "Wide", "Tall"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔥\nWhat is the opposite of \"hot\"?", correctAnswer: "Cold", distractors: ["Tasty", "Sweet", "Dry"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐇\nWhat is the opposite of \"fast\"?", correctAnswer: "Slow", distractors: ["Strong", "Long", "Heavy"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "☀️\nWhat is the opposite of \"day\"?", correctAnswer: "Night", distractors: ["Morning", "Noon", "Afternoon"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "😊\nWhat is the opposite of \"happy\"?", correctAnswer: "Sad", distractors: ["Funny", "Calm", "Silly"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "👉\nWhat is the opposite of \"right\"?", correctAnswer: "Left", distractors: ["Above", "Below", "In front"], tier: .medium, grades: 0...2),

        // ── From QuestionBanksWorkflow ──
        BankQuestion(prompt: "🔢\nWhat number comes next?\n3, 6, 9, ?", correctAnswer: "12", distractors: ["10", "11", "15"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n20, 18, 16, ?", correctAnswer: "14", distractors: ["15", "12", "17"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧩\nWhat comes next?\n🌟⬛🌟⬛🌟 ?", correctAnswer: "⬛", distractors: ["🌟", "🔵", "🔺"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🧩\nWhat comes next?\n🍓🍋🍓🍋🍓 ?", correctAnswer: "🍋", distractors: ["🍓", "🍇", "🍊"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🧩\nWhat comes next?\n☀️🌙☀️🌙☀️ ?", correctAnswer: "🌙", distractors: ["☀️", "⭐", "☁️"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🧩\nWhat comes next?\n🐘🦒🐘🦒🐘 ?", correctAnswer: "🦒", distractors: ["🐘", "🦓", "🐅"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n4, 8, 12, ?", correctAnswer: "16", distractors: ["14", "18", "20"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "⬛\nWhat shape comes next?\n⬛⬜⬛⬜⬛ ?", correctAnswer: "⬜", distractors: ["⬛", "🔺", "🔵"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong?\n🐦 🐟 🦅 🦜", correctAnswer: "🐟", distractors: ["🐦", "🦅", "🦜"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🛋️\nWhich one is not furniture?", correctAnswer: "Rake", distractors: ["Chair", "Dresser", "Bed"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🎵\nWhich one is not a musical instrument?", correctAnswer: "Frying pan", distractors: ["Flute", "Drum", "Piano"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "👂\nHow many ears do two children have?", correctAnswer: "4", distractors: ["2", "3", "6"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🖐️\nHow many fingers are on two hands?", correctAnswer: "10", distractors: ["5", "8", "12"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐞\nIf 🐞 = 3, then 🐞 + 🐞 = ?", correctAnswer: "6", distractors: ["5", "4", "9"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📦\nA box has 2 balls. We add 2 more. How many balls are in the box now?", correctAnswer: "4", distractors: ["3", "2", "5"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📅\nIf today is Wednesday, what day will tomorrow be?", correctAnswer: "Thursday", distractors: ["Tuesday", "Friday", "Monday"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "📅\nWhat day comes right before Sunday?", correctAnswer: "Saturday", distractors: ["Monday", "Friday", "Tuesday"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🔤\nWhat letter comes next?\nD, E, F, ?", correctAnswer: "G", distractors: ["H", "E", "C"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🔤\nWhat letter comes right before K?", correctAnswer: "J", distractors: ["L", "M", "I"], tier: .hard, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes after 14?", correctAnswer: "15", distractors: ["13", "16", "20"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes before 10?", correctAnswer: "9", distractors: ["11", "8", "12"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📏\nWhich one is the longest?", correctAnswer: "Snake", distractors: ["Ant", "Fly", "Bee"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "↔️\nWhich one is the widest?", correctAnswer: "Bus", distractors: ["Pencil", "Straw", "String"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "⚖️\nWhich one weighs the most?", correctAnswer: "Rock", distractors: ["Feather", "Leaf", "Balloon"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍪\nThere are 6 cookies on a plate. I eat 2. How many are left?", correctAnswer: "4", distractors: ["8", "5", "3"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🧩\nWhat comes next?\n🟦🟥🟨🟦🟥 ?", correctAnswer: "🟨", distractors: ["🟦", "🟥", "🟩"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🔷\nWhich one is not a shape?", correctAnswer: "Sun", distractors: ["Circle", "Square", "Triangle"], tier: .medium, grades: 0...2),

        // ── From QuestionBanksWorkflow2 ──
        BankQuestion(prompt: "🔢\nWhat number comes next?\n7, 14, 21, ?", correctAnswer: "28", distractors: ["27", "30", "35"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n3, 6, 12, 24, ?", correctAnswer: "48", distractors: ["36", "30", "40"], tier: .hard, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n50, 40, 30, ?", correctAnswer: "20", distractors: ["25", "10", "35"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧩\nWhat comes next?\n🟢🟢🔴🟢🟢🔴🟢🟢 ?", correctAnswer: "🔴", distractors: ["🟢", "🔵", "🟡"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🧩\nWhat comes next?\n🐢🐰🐢🐰🐢 ?", correctAnswer: "🐰", distractors: ["🐢", "🐭", "🦊"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🧩\nWhat comes next?\n⭐🌙⭐⭐🌙⭐⭐⭐🌙 ?", correctAnswer: "⭐", distractors: ["🌙", "☀️", "☁️"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "🧩\nWhat comes next?\n🔴🟡🔵🔴🟡 ?", correctAnswer: "🔵", distractors: ["🔴", "🟡", "🟢"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n9, 8, 7, 6, ?", correctAnswer: "5", distractors: ["4", "7", "10"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔤\nWhat letter comes next?\nA, C, E, ?", correctAnswer: "G", distractors: ["F", "H", "B"], tier: .hard, grades: 1...3),
        BankQuestion(prompt: "🤔\nWhich one does not belong?\n🐝 🌻 🦋 🐞", correctAnswer: "🌻", distractors: ["🐝", "🦋", "🐞"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong?\n👕 👖 🧦 🍕", correctAnswer: "🍕", distractors: ["👕", "👖", "🧦"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong?\n🦈 🐦 🦅 🦉", correctAnswer: "🦈", distractors: ["🐦", "🦅", "🦉"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong?\n✏️ ☂️ 📕 ✂️", correctAnswer: "☂️", distractors: ["✏️", "📕", "✂️"], tier: .hard, grades: 0...2),
        BankQuestion(prompt: "🦶\nWhich one is not a leg, a foot or a paw?", correctAnswer: "🪶", distractors: ["🐾", "🦵", "🦶"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🚲\nHow many wheels does one bicycle have?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "✋\nHow many fingers are on one hand?", correctAnswer: "5", distractors: ["4", "10", "6"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐈\nHow many tails do 4 cats have?", correctAnswer: "4", distractors: ["8", "2", "16"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🐦\nHow many wings do two birds have?", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🔢\nWhat number comes before 8?", correctAnswer: "7", distractors: ["9", "6", "10"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes after 19?", correctAnswer: "20", distractors: ["18", "21", "29"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🔤\nWhat letter comes right after M?", correctAnswer: "N", distractors: ["L", "P", "K"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "📅\nIf today is Friday, what day was yesterday?", correctAnswer: "Thursday", distractors: ["Wednesday", "Saturday", "Tuesday"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍌\nIf 🍌 = 5, then 🍌 + 🍌 = ?", correctAnswer: "10", distractors: ["7", "15", "25"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🐟\nAll fish swim. What does a fish do?", correctAnswer: "It swims", distractors: ["It barks", "It meows", "It moos"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "🌷\nThere are 4 flowers in the garden. We pick 1. How many are left?", correctAnswer: "3", distractors: ["5", "2", "4"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐘\nThe elephant 🐘 is heavier than the mouse 🐭. Which one is lighter?", correctAnswer: "The mouse", distractors: ["The elephant", "They weigh the same", "You can't tell"], tier: .medium, grades: 0...2),
        BankQuestion(prompt: "☀️\n🏠\nWhere is the sun compared to the house?", correctAnswer: "Above it", distractors: ["Below it", "Next to it", "Behind it"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📐\nWhich shape has 3 corners?", correctAnswer: "🔺", distractors: ["⚪", "⬛", "⬢"], tier: .medium, grades: 0...2),

        // ── From QuestionBanksWorkflow3 · easy ──
        BankQuestion(prompt: "🤔\nWhich one does not belong: dog, chair, cat, horse?", correctAnswer: "Chair", distractors: ["Dog", "Cat", "Horse"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n2, 3, 4, ?", correctAnswer: "5", distractors: ["6", "3", "7"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n6, 8, 10, ?", correctAnswer: "12", distractors: ["11", "13", "14"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nWhat number comes after 5?", correctAnswer: "6", distractors: ["4", "7", "8"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes before 4?", correctAnswer: "3", distractors: ["5", "2", "6"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "☀️\nDay is to sun as night is to ___?", correctAnswer: "Moon", distractors: ["Cloud", "Rain", "Tree"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🤔\nWhich one does not belong: orange, banana, car, apple?", correctAnswer: "Car", distractors: ["Orange", "Banana", "Apple"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n5, 6, 7, ?", correctAnswer: "8", distractors: ["9", "10", "6"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📅\nWhat day comes right after Sunday?", correctAnswer: "Monday", distractors: ["Tuesday", "Saturday", "Wednesday"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong: bird, butterfly, fish, bee?", correctAnswer: "Fish", distractors: ["Bird", "Butterfly", "Bee"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n5, 4, 3, ?", correctAnswer: "2", distractors: ["1", "6", "4"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐘\nBig is to ___ as hot is to cold?", correctAnswer: "Small", distractors: ["Wide", "Long", "Heavy"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🤔\nWhich one does not belong: shoe, eye, ear, nose?", correctAnswer: "Shoe", distractors: ["Eye", "Ear", "Nose"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔤\nWhat letter comes right after A?", correctAnswer: "B", distractors: ["C", "D", "E"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 3, 5, ?", correctAnswer: "7", distractors: ["6", "8", "9"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🤔\nWhich one does not belong: rose, lily, table, tulip?", correctAnswer: "Table", distractors: ["Rose", "Lily", "Tulip"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🌡️\nSummer is to hot as winter is to ___?", correctAnswer: "Cold", distractors: ["Dry", "Bright", "Sunny"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "📅\nWhat day comes right before Friday?", correctAnswer: "Thursday", distractors: ["Saturday", "Sunday", "Wednesday"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n0, 2, 4, ?", correctAnswer: "6", distractors: ["5", "7", "8"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🤔\nWhich one does not belong: banana, grapes, pear, book?", correctAnswer: "Book", distractors: ["Banana", "Grapes", "Pear"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🐦\nA bird flies in the ___ as a fish swims in the water.", correctAnswer: "Sky", distractors: ["Sand", "Mud", "Pond"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nWhat number comes after 9?", correctAnswer: "10", distractors: ["8", "11", "7"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong: red, finger, yellow, orange?", correctAnswer: "Finger", distractors: ["Red", "Yellow", "Orange"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n10, 15, 20, ?", correctAnswer: "25", distractors: ["21", "30", "24"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🧤\nHand is to glove as foot is to ___?", correctAnswer: "Sock", distractors: ["Hat", "Scarf", "Shirt"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nWhat number comes before 6?", correctAnswer: "5", distractors: ["7", "4", "8"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong: bicycle, car, dog, bus?", correctAnswer: "Dog", distractors: ["Bicycle", "Car", "Bus"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n2, 4, 8, ?", correctAnswer: "16", distractors: ["10", "12", "18"], tier: .easy, grades: 4...6),
        BankQuestion(prompt: "🌸\nWhich season comes right after spring?", correctAnswer: "Summer", distractors: ["Winter", "Fall", "Spring"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong: table, elephant, chair, dresser?", correctAnswer: "Elephant", distractors: ["Table", "Chair", "Dresser"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "👵\nMom is to Dad as Grandma is to ___?", correctAnswer: "Grandpa", distractors: ["Uncle", "Brother", "Baby"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n20, 30, 40, ?", correctAnswer: "50", distractors: ["41", "60", "45"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔤\nWhat letter comes right before D?", correctAnswer: "C", distractors: ["E", "B", "F"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong: red, yellow, pizza, blue?", correctAnswer: "Pizza", distractors: ["Red", "Yellow", "Blue"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n10, 20, 30, ?", correctAnswer: "40", distractors: ["35", "50", "31"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nWhat number comes after 29?", correctAnswer: "30", distractors: ["28", "31", "39"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🤔\nWhich one does not belong: dog, cat, apple, rabbit?", correctAnswer: "Apple", distractors: ["Dog", "Cat", "Rabbit"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n6, 9, 12, ?", correctAnswer: "15", distractors: ["13", "14", "18"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🌗\nDay is to light as night is to ___?", correctAnswer: "Dark", distractors: ["Sun", "Morning", "Light"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "📅\nWhat day comes right before Tuesday?", correctAnswer: "Monday", distractors: ["Wednesday", "Sunday", "Saturday"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤔\nWhich one does not belong: carrot, apple, pear, orange?", correctAnswer: "Carrot", distractors: ["Apple", "Pear", "Orange"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 4, 7, ?", correctAnswer: "10", distractors: ["8", "9", "11"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🐟\nA fish lives in ___ as a bird lives in a tree.", correctAnswer: "Water", distractors: ["Sand", "Air", "Fire"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "💯\nWhat number comes after 99?", correctAnswer: "100", distractors: ["98", "101", "90"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🤔\nWhich one does not belong: one, two, cup, three?", correctAnswer: "Cup", distractors: ["One", "Two", "Three"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n2, 5, 8, ?", correctAnswer: "11", distractors: ["9", "10", "12"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "📏\nBig is to small as long is to ___?", correctAnswer: "Short", distractors: ["Wide", "Heavy", "Tall"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nWhat number comes before 1?", correctAnswer: "0", distractors: ["2", "3", "10"], tier: .easy, grades: 1...3),

        // ── From QuestionBanksWorkflow3 · medium ──
        BankQuestion(prompt: "🤔\nWhich one does not belong: circle, square, cube, triangle?", correctAnswer: "Cube", distractors: ["Circle", "Square", "Triangle"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 3, 9, 27, ?", correctAnswer: "81", distractors: ["36", "54", "30"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "✋\nFinger is to hand as toe is to ___?", correctAnswer: "Foot", distractors: ["Head", "Back", "Neck"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n100, 81, 64, 49, ?", correctAnswer: "36", distractors: ["40", "30", "25"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🤔\nWhich one does not belong: eagle, dove, dog, parrot?", correctAnswer: "Dog", distractors: ["Eagle", "Dove", "Parrot"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✏️\nWriter is to pen as painter is to ___?", correctAnswer: "Paintbrush", distractors: ["Book", "Spoon", "Hammer"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n200, 180, 160, ?", correctAnswer: "140", distractors: ["150", "120", "170"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🤔\nWhich one does not belong: Sunday, four, Monday, Tuesday?", correctAnswer: "Four", distractors: ["Sunday", "Monday", "Tuesday"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍎\nDoctor is to patient as teacher is to ___?", correctAnswer: "Student", distractors: ["Book", "Board", "Classroom"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n2, 6, 18, ?", correctAnswer: "54", distractors: ["36", "24", "48"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🤔\nWhich one does not belong: triangle, red, blue, green?", correctAnswer: "Triangle", distractors: ["Red", "Blue", "Green"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐝\nBee is to honey as cow is to ___?", correctAnswer: "Milk", distractors: ["Wool", "Egg", "Water"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n5, 10, 20, 40, ?", correctAnswer: "80", distractors: ["60", "50", "70"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🤔\nWhich one does not belong: fork, ball, spoon, knife?", correctAnswer: "Ball", distractors: ["Fork", "Spoon", "Knife"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐍\nLion is to roar as snake is to ___?", correctAnswer: "Hiss", distractors: ["Bark", "Chirp", "Baa"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 2, 4, 7, 11, ?", correctAnswer: "16", distractors: ["14", "15", "17"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🤔\nWhich one does not belong: cat, bike, person, fish?", correctAnswer: "Bike", distractors: ["Cat", "Person", "Fish"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✈️\nShip is to sea as airplane is to ___?", correctAnswer: "Sky", distractors: ["Road", "Train track", "Sand"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n81, 27, 9, ?", correctAnswer: "3", distractors: ["6", "1", "4"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🤔\nWhich one does not belong: horse, elephant, motorcycle, camel?", correctAnswer: "Motorcycle", distractors: ["Horse", "Elephant", "Camel"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "👑\nKing is to crown as firefighter is to ___?", correctAnswer: "Helmet", distractors: ["Apron", "Swimsuit", "Slippers"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n12, 10, 8, 6, ?", correctAnswer: "4", distractors: ["5", "3", "2"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🤔\nWhich one does not belong: rose, rock, daisy, daffodil?", correctAnswer: "Rock", distractors: ["Rose", "Daisy", "Daffodil"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌳\nTree is to leaf as book is to ___?", correctAnswer: "Page", distractors: ["Shelf", "Pencil", "Bag"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n7, 14, 21, 28, ?", correctAnswer: "35", distractors: ["30", "32", "42"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🤔\nWhich one does not belong: two, four, winter, six?", correctAnswer: "Winter", distractors: ["Two", "Four", "Six"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍞\nBaker is to bread as farmer is to ___?", correctAnswer: "Crops", distractors: ["Oven", "Hammer", "Books"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n3, 3, 6, 9, 15, ?", correctAnswer: "24", distractors: ["18", "21", "30"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🐇\nRabbit is to hopping as fish is to ___?", correctAnswer: "Swimming", distractors: ["Running", "Flying", "Crawling"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n50, 45, 40, 35, ?", correctAnswer: "30", distractors: ["25", "32", "28"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🤔\nWhich one does not belong: finger, palm, notebook, elbow?", correctAnswer: "Notebook", distractors: ["Finger", "Palm", "Elbow"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🐢\nTurtle is to slow as cheetah is to ___?", correctAnswer: "Fast", distractors: ["Heavy", "Big", "Strong"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n2, 3, 5, 8, 13, ?", correctAnswer: "21", distractors: ["18", "20", "26"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🤔\nWhich one does not belong: shark, tuna, goldfish, tiger?", correctAnswer: "Tiger", distractors: ["Shark", "Dolphin", "Whale"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "❄️\nWinter is to snow as summer is to ___?", correctAnswer: "Sunshine", distractors: ["Sleet", "Frost", "Blizzards"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n6, 12, 24, 48, ?", correctAnswer: "96", distractors: ["72", "60", "84"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🤔\nWhich one does not belong: bee, horse, ant, butterfly?", correctAnswer: "Horse", distractors: ["Bee", "Ant", "Butterfly"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍳\nCook is to pot as carpenter is to ___?", correctAnswer: "Hammer", distractors: ["Plate", "Pillow", "Spoon"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n11, 22, 33, 44, ?", correctAnswer: "55", distractors: ["50", "54", "66"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🤔\nWhich one does not belong: January, March, classroom, August?", correctAnswer: "Classroom", distractors: ["January", "March", "August"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧤\nHand is to glove as head is to ___?", correctAnswer: "Hat", distractors: ["Sock", "Shoe", "Belt"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🤔\nWhich one does not belong: saw, sofa, screwdriver, hammer?", correctAnswer: "Sofa", distractors: ["Saw", "Screwdriver", "Hammer"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "⭐\nStar is to night as sun is to ___?", correctAnswer: "Day", distractors: ["Moon", "Cloud", "Sky"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 3, 6, 10, 15, ?", correctAnswer: "21", distractors: ["18", "20", "24"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🤔\nWhich one does not belong: juice, milk, orange, water?", correctAnswer: "Orange", distractors: ["Juice", "Milk", "Water"], tier: .medium, grades: 2...4),

        // ── From QuestionBanksWorkflow3 · hard ──
        BankQuestion(prompt: "🐈\nAll cats have tails. Mitzi has a tail. Does Mitzi have to be a cat?", correctAnswer: "Not necessarily", distractors: ["Yes, for sure", "No, Mitzi can't be a cat", "Yes, every animal with a tail is a cat"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n2, 4, 8, 16, 32, ?", correctAnswer: "64", distractors: ["48", "40", "56"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📏\nDanny is taller than Sam, and Sam is taller than Leo. Who is the shortest?", correctAnswer: "Leo", distractors: ["Danny", "Sam", "They are all the same height"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 4, 9, 16, 25, ?", correctAnswer: "36", distractors: ["30", "35", "49"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📅\nIf today is Wednesday, what day will it be in three days?", correctAnswer: "Saturday", distractors: ["Friday", "Sunday", "Thursday"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n3, 7, 15, 31, ?", correctAnswer: "63", distractors: ["47", "55", "62"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🪶\nAll birds have wings. Max has no wings. What is true?", correctAnswer: "Max is not a bird", distractors: ["Max is a bird", "Max can fly", "You can't tell"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 2, 6, 24, ?", correctAnswer: "120", distractors: ["48", "72", "96"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📅\nIf yesterday was Monday, what day will tomorrow be?", correctAnswer: "Wednesday", distractors: ["Tuesday", "Thursday", "Sunday"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n2, 5, 11, 23, ?", correctAnswer: "47", distractors: ["35", "44", "46"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🍪\nAva has more cookies than Zoe, but fewer cookies than Mia. Who has the most cookies?", correctAnswer: "Mia", distractors: ["Ava", "Zoe", "They all have the same"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n5, 11, 17, 23, ?", correctAnswer: "29", distractors: ["27", "28", "30"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔀\nWhat number comes next?\n100, 1, 99, 2, 98, ?", correctAnswer: "3", distractors: ["97", "4", "96"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🤔\nWhich one does not belong: strawberry, cucumber, raspberry, cherry?", correctAnswer: "Cucumber", distractors: ["Strawberry", "Raspberry", "Cherry"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🔴\nAll the balls in a box are red. I take out one ball. What color is it?", correctAnswer: "Red", distractors: ["Blue", "Green", "You can't tell"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n4, 9, 16, 25, 36, ?", correctAnswer: "49", distractors: ["42", "45", "48"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🐭\n2 cats catch 2 mice in 2 minutes. At the same speed, how many mice will 2 cats catch in 4 minutes?", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 8, 27, 64, ?", correctAnswer: "125", distractors: ["100", "81", "120"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🤔\nWhich number does not belong: 5, 15, 12, 25?", correctAnswer: "12", distractors: ["5", "15", "25"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "👧\nMaya has two sisters and one brother. How many of the kids in her family are girls?", correctAnswer: "3", distractors: ["2", "4", "1"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n90, 81, 72, 63, ?", correctAnswer: "54", distractors: ["50", "55", "52"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "👴\nGrandpa is to Dad as Dad is to ___?", correctAnswer: "Me", distractors: ["Uncle", "Grandma", "Grandpa"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔥\nPretend that all red things are hot, and all hot things are dangerous. What is true about a red ball?", correctAnswer: "It is dangerous", distractors: ["It is cold", "It is safe", "You can't tell"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📆\nWhat number comes next?\n31, 28, 31, 30, 31, ?", correctAnswer: "30", distractors: ["31", "28", "29"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🤔\nWhich word does not belong: first, second, middle, third?", correctAnswer: "Middle", distractors: ["First", "Second", "Third"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🥚\nA carton has 12 eggs. I take out half of them, and then 2 more. How many eggs are left in the carton?", correctAnswer: "4", distractors: ["6", "5", "8"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n1, 3, 7, 13, 21, ?", correctAnswer: "31", distractors: ["28", "29", "30"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🕯️\nIn a dark room, I light 1 candle and then 4 more. Then 2 candles go out. How many candles are still lit?", correctAnswer: "3", distractors: ["5", "2", "4"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n64, 32, 16, 8, ?", correctAnswer: "4", distractors: ["6", "2", "5"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🤔\nWhich one does not belong: 1, square, 5, 9?", correctAnswer: "Square", distractors: ["1", "5", "9"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📅\nThe day after tomorrow will be Friday. What day was yesterday?", correctAnswer: "Tuesday", distractors: ["Monday", "Wednesday", "Thursday"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n3, 5, 9, 17, ?", correctAnswer: "33", distractors: ["25", "29", "31"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "✋\nEvery hand has 5 fingers. How many fingers do 3 children have altogether?", correctAnswer: "30", distractors: ["15", "25", "20"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🤔\nWhich number does not belong: 10, 23, 20, 30?", correctAnswer: "23", distractors: ["10", "20", "30"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🪑\nRose sits to the right of Dana, and Dana sits to the right of Maya. Who sits in the middle?", correctAnswer: "Dana", distractors: ["Rose", "Maya", "You can't tell"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n2, 6, 12, 20, 30, ?", correctAnswer: "42", distractors: ["38", "40", "36"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "📅\nIf tomorrow is Sunday, what day was it two days ago?", correctAnswer: "Thursday", distractors: ["Friday", "Wednesday", "Saturday"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🧩\nWhich shape has no flat faces at all?", correctAnswer: "Sphere", distractors: ["Cube", "Pyramid", "Rectangular prism"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🍎\nJake has twice as many apples as Owen. Owen has 4 apples. How many apples do they have together?", correctAnswer: "12", distractors: ["8", "10", "16"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🎂\nElla is older than Grace, and Grace is older than Ruby. Who is the youngest?", correctAnswer: "Ruby", distractors: ["Ella", "Grace", "They are all the same age"], tier: .hard, grades: 3...6),
        BankQuestion(prompt: "🔢\nWhat number comes next?\n7, 10, 16, 28, ?", correctAnswer: "52", distractors: ["40", "44", "48"], tier: .hard, grades: 4...6),
    ]
}
