import Foundation

/// 💰 Money — English (US). Adapted from the Hebrew money banks (QuestionBanks, Workflow, Workflow2,
/// Workflow3, CurriculumHumanities) as a map of learning goals, rewritten for US kids:
/// US coins and bills, counting change, needs vs wants, saving, budgeting, unit price,
/// earning, banks, debit vs credit, and percent/interest in the upper grades. No shekels.
extension EnglishContent {
    static let money: [BankQuestion] = [
        // ── Kindergarten · What money is ──
        BankQuestion(prompt: "🪙\nWhat do we use to buy things at a store?", correctAnswer: "Money", distractors: ["Rocks", "Leaves", "Crayons"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🏪\nWhat do we call a place where we buy things?", correctAnswer: "A store", distractors: ["A park", "A school", "A playground"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🧺\nWhere can your family buy food?", correctAnswer: "A grocery store", distractors: ["A fire station", "A playground", "A library"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🛍️\nWhen you buy a toy at a store, who do you pay?", correctAnswer: "The cashier", distractors: ["The toy", "The door", "The shopping cart"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🍎\nAn apple costs 10¢. Which ONE coin pays for it exactly?", correctAnswer: "A dime", distractors: ["A penny", "A nickel", "A quarter"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐷\nWhat is a piggy bank for?", correctAnswer: "Saving money", distractors: ["Keeping snacks", "Holding water", "Growing plants"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🪙\nWhich is more money: 2 pennies or 5 pennies?", correctAnswer: "5 pennies", distractors: ["2 pennies", "They are worth the same", "You can't tell"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "💝\nWhat can you do with money besides spending it?", correctAnswer: "Save it", distractors: ["Eat it", "Plant it", "Paint it"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "💵\nWhich of these is a job people get paid for?", correctAnswer: "Firefighter", distractors: ["Napping", "Playing tag", "Blowing bubbles"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🪙\nWhich of these is a coin?", correctAnswer: "Penny", distractors: ["Button", "Marble", "Sticker"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "⚪\nWhat do we call round, metal money?", correctAnswer: "A coin", distractors: ["A bill", "A stamp", "A ticket"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📄\nWhat do we call money made of paper?", correctAnswer: "A bill", distractors: ["A coin", "A stamp", "A ticket"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🟤\nWhich coin is copper-colored, not silver?", correctAnswer: "Penny", distractors: ["Nickel", "Dime", "Quarter"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪙\nHow many cents is a penny worth?", correctAnswer: "1¢", distractors: ["5¢", "10¢", "25¢"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🪙\nHow many cents is a nickel worth?", correctAnswer: "5¢", distractors: ["1¢", "10¢", "25¢"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪙\nHow many cents is a dime worth?", correctAnswer: "10¢", distractors: ["1¢", "5¢", "25¢"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪙\nHow many cents is a quarter worth?", correctAnswer: "25¢", distractors: ["5¢", "10¢", "50¢"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪙\nWhich coin is worth the most?", correctAnswer: "Quarter", distractors: ["Penny", "Nickel", "Dime"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪙\nWhich coin is worth the least?", correctAnswer: "Penny", distractors: ["Nickel", "Dime", "Quarter"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🪙\nA nickel is worth 5¢ and a penny is worth 1¢. Which is worth more?", correctAnswer: "The nickel", distractors: ["The penny", "They are worth the same", "Neither one"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🪙🪙\n1 penny and 1 more penny. How many cents is that?", correctAnswer: "2¢", distractors: ["1¢", "3¢", "11¢"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🪙🪙🪙🪙🪙\nEach penny is 1 cent. How many cents are 5 pennies?", correctAnswer: "5¢", distractors: ["4¢", "6¢", "10¢"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🍭\nA lollipop costs 3 pennies. How many pennies do 2 lollipops cost?", correctAnswer: "6", distractors: ["3", "5", "9"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "💰\nYou have 4¢ and find 3¢ more. How much do you have now?", correctAnswer: "7¢", distractors: ["1¢", "6¢", "8¢"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🥤\nYou have 10¢ and spend 4¢. How much is left?", correctAnswer: "6¢", distractors: ["4¢", "5¢", "14¢"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🏷️\nOne toy costs $5. Another toy costs $2. Which one costs more?", correctAnswer: "The $5 toy", distractors: ["The $2 toy", "They cost the same", "Neither one costs money"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "💭\nWhich one is a WANT, not a need?", correctAnswer: "A new toy", distractors: ["Food", "Water", "A warm coat"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "✅\nWhich one is a NEED?", correctAnswer: "Food to eat", distractors: ["A new video game", "Stickers", "A balloon"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🤝\nYour friend forgot a snack at school. What is a kind thing to do?", correctAnswer: "Share some of your snack", distractors: ["Laugh at them", "Walk away", "Eat fast so they can't see"], tier: .easy, grades: 0...2),
        // ── Grades 1–2 · Coins and bills ──
        BankQuestion(prompt: "🪙\nWhich coin is the smallest in size?", correctAnswer: "Dime", distractors: ["Penny", "Nickel", "Quarter"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔢\nHow many pennies make a nickel?", correctAnswer: "5", distractors: ["2", "10", "25"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔢\nHow many pennies make a dime?", correctAnswer: "10", distractors: ["5", "25", "100"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔢\nHow many nickels make a dime?", correctAnswer: "2", distractors: ["3", "5", "10"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔢\nHow many pennies make a quarter?", correctAnswer: "25", distractors: ["10", "50", "100"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔢\nHow many nickels make a quarter?", correctAnswer: "5", distractors: ["2", "4", "25"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "💵\nHow many cents are in one dollar?", correctAnswer: "100", distractors: ["10", "50", "1,000"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nHow many quarters make one dollar?", correctAnswer: "4", distractors: ["2", "5", "10"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔢\nHow many dimes make one dollar?", correctAnswer: "10", distractors: ["4", "5", "100"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🔢\nHow many nickels make one dollar?", correctAnswer: "20", distractors: ["5", "10", "25"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪙🪙\n2 dimes. How much money is that?", correctAnswer: "20¢", distractors: ["2¢", "10¢", "12¢"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙🪙🪙\n3 dimes. How much money is that?", correctAnswer: "30¢", distractors: ["3¢", "13¢", "25¢"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙🪙\n1 dime and 1 nickel. How much money is that?", correctAnswer: "15¢", distractors: ["6¢", "11¢", "20¢"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙🪙\n2 quarters. How much money is that?", correctAnswer: "50¢", distractors: ["25¢", "40¢", "52¢"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙🪙🪙🪙\n1 dime and 3 pennies. How much money is that?", correctAnswer: "13¢", distractors: ["4¢", "10¢", "31¢"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙🪙🪙🪙🪙\n1 nickel and 4 pennies. How much money is that?", correctAnswer: "9¢", distractors: ["5¢", "8¢", "54¢"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🪙🪙🪙\n2 dimes and 1 nickel. How much money is that?", correctAnswer: "25¢", distractors: ["20¢", "21¢", "30¢"], tier: .medium, grades: 1...2),
        BankQuestion(prompt: "🪙🪙\n1 quarter and 1 dime. How much money is that?", correctAnswer: "35¢", distractors: ["26¢", "30¢", "45¢"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🪙🪙🪙\n3 quarters. How much money is that?", correctAnswer: "75¢", distractors: ["30¢", "50¢", "60¢"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🪙🪙🪙🪙\n1 quarter, 2 dimes and 1 nickel. How much money is that?", correctAnswer: "50¢", distractors: ["40¢", "45¢", "55¢"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🪙\nWhich coins make exactly 12¢?", correctAnswer: "1 dime and 2 pennies", distractors: ["1 nickel and 2 pennies", "1 dime and 1 penny", "2 dimes"], tier: .medium, grades: 1...2),
        BankQuestion(prompt: "🪙\nWhich coins make exactly 25¢?", correctAnswer: "1 dime and 3 nickels", distractors: ["2 dimes", "3 nickels", "1 dime and 2 nickels"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🪙\nWhich coins make exactly 30¢?", correctAnswer: "1 quarter and 1 nickel", distractors: ["1 quarter and 1 penny", "2 dimes", "3 nickels"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "⚖️\nWhich is worth more: 3 dimes or 1 quarter?", correctAnswer: "3 dimes", distractors: ["1 quarter", "They are worth the same", "You can't tell"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "⚖️\nWhich is worth more: 4 nickels or 1 quarter?", correctAnswer: "1 quarter", distractors: ["4 nickels", "They are worth the same", "You can't tell"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "⚖️\nCompare 4 dimes with 1 quarter and 3 nickels. What is true?", correctAnswer: "They are worth the same", distractors: ["The dimes are worth more", "The quarter and nickels are worth more", "You can't tell"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🇺🇸\nWhat is the name of the money used in the United States?", correctAnswer: "Dollar", distractors: ["Euro", "Peso", "Yen"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "💵\nWhich bill is worth the most?", correctAnswer: "$20 bill", distractors: ["$1 bill", "$5 bill", "$10 bill"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "💵\nWhich bill is worth the least?", correctAnswer: "$1 bill", distractors: ["$5 bill", "$10 bill", "$20 bill"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔍\nWhich of these amounts comes as a paper bill, not a coin?", correctAnswer: "$5", distractors: ["5¢", "10¢", "25¢"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "💵\nHow many $1 bills equal one $10 bill?", correctAnswer: "10", distractors: ["2", "5", "100"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "💵\nHow many $5 bills make $20?", correctAnswer: "4", distractors: ["2", "5", "10"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "💵\nHow many $10 bills make $100?", correctAnswer: "10", distractors: ["5", "20", "50"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "💵\nHow many $20 bills make $100?", correctAnswer: "5", distractors: ["2", "4", "10"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "💵\nTwo $5 bills and three $1 bills. How much money is that?", correctAnswer: "$13", distractors: ["$8", "$10", "$15"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "💵\nOne $10 bill, one $5 bill and two $1 bills. How much money is that?", correctAnswer: "$17", distractors: ["$13", "$16", "$18"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "💵\nOne $1 bill and 2 quarters. How much money is that?", correctAnswer: "$1.50", distractors: ["$1.02", "$1.25", "$3.00"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "💵\nWhich way shows one dollar and twenty-five cents?", correctAnswer: "$1.25", distractors: ["$125", "$12.50", "$0.125"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "💵\nHow do you write 50 cents using a dollar sign?", correctAnswer: "$0.50", distractors: ["$50", "$5.00", "$0.05"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🪙\nWhose face is on the penny?", correctAnswer: "Abraham Lincoln", distractors: ["George Washington", "Thomas Jefferson", "Benjamin Franklin"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪙\nWhose face is on the nickel?", correctAnswer: "Thomas Jefferson", distractors: ["Abraham Lincoln", "George Washington", "Benjamin Franklin"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🪙\nWhose face is on the quarter?", correctAnswer: "George Washington", distractors: ["Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "💵\nWhose face is on the one-dollar bill?", correctAnswer: "George Washington", distractors: ["Abraham Lincoln", "Benjamin Franklin", "Thomas Jefferson"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "💵\nWhose face is on the five-dollar bill?", correctAnswer: "Abraham Lincoln", distractors: ["George Washington", "Alexander Hamilton", "Benjamin Franklin"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "💵\nWhose face is on the $100 bill?", correctAnswer: "Benjamin Franklin", distractors: ["George Washington", "Abraham Lincoln", "Ulysses S. Grant"], tier: .medium, grades: 3...5),
        // ── Grades 1–3 · Needs, wants, saving, shopping ──
        BankQuestion(prompt: "💡\nWhat does it mean to SAVE money?", correctAnswer: "Keep some money to use later", distractors: ["Spend it all right away", "Throw it away", "Lose it"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🎯\nYou want a toy that costs more than you have. What is a smart plan?", correctAnswer: "Save a little each week until you have enough", distractors: ["Take it without paying", "Give up on saving forever", "Spend your money on candy first"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🎁\nGrandma gives you $10. What is a smart choice?", correctAnswer: "Save some and spend some", distractors: ["Lose it on the way home", "Throw it in the trash", "Hide it and forget where"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "👨‍👩‍👧\nWhich is a NEED for every family?", correctAnswer: "A safe place to live", distractors: ["A bigger TV", "A new game", "Fancy sneakers"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🎮\nYou need new shoes. You want a video game. You can buy only one. Which should you buy?", correctAnswer: "The shoes", distractors: ["The video game", "Two video games", "Candy instead"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "❄️\nIt's a cold winter. Which of these is a need?", correctAnswer: "A warm coat", distractors: ["A toy robot", "A second bike", "Glitter stickers"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏷️\nWhat does a price tag tell you?", correctAnswer: "How much something costs", distractors: ["How heavy it is", "What color it is", "When the store closes"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🛒\nWhere in a store do you pay for things?", correctAnswer: "At the checkout", distractors: ["In the parking lot", "At the front door", "In the stockroom"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🤔\nWhich costs less: a $3 book or an $8 book?", correctAnswer: "The $3 book", distractors: ["The $8 book", "They cost the same", "You can't tell"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🔒\nWhere do grown-ups keep money safe?", correctAnswer: "In a bank", distractors: ["Under a rock outside", "In the trash can", "In a mailbox"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "💼\nWhat is one way grown-ups earn money?", correctAnswer: "Working at a job", distractors: ["Sleeping late", "Watching TV", "Taking a bath"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🧹\nHow can a kid earn a little money at home?", correctAnswer: "Doing extra chores", distractors: ["Hiding the remote", "Skipping homework", "Staying up late"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🫙\nMany kids use three money jars: Save, Spend and…", correctAnswer: "Share", distractors: ["Lose", "Hide", "Waste"], tier: .easy, grades: 1...3),
        // ── Grades 2–4 · Adding, change and word problems ──
        BankQuestion(prompt: "🍬\nA candy costs 5¢. You have 8¢. How much is left after you buy it?", correctAnswer: "3¢", distractors: ["2¢", "4¢", "13¢"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🐷\nYou put 2 dimes in your piggy bank each day for 3 days. How much did you save?", correctAnswer: "60¢", distractors: ["20¢", "23¢", "50¢"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🎈\nA balloon costs 10¢. How much do 3 balloons cost?", correctAnswer: "30¢", distractors: ["13¢", "20¢", "40¢"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🧃\nJuice costs 45¢. You pay with 2 quarters. How much change do you get?", correctAnswer: "5¢", distractors: ["10¢", "15¢", "25¢"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🍦\nIce cream costs 60¢. You pay with $1. How much change do you get?", correctAnswer: "40¢", distractors: ["30¢", "50¢", "60¢"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🥨\nA pretzel costs 75¢. You pay with $1. How much change do you get?", correctAnswer: "25¢", distractors: ["15¢", "35¢", "75¢"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🍌\nA banana costs 35¢. You pay with 2 quarters. How much change do you get?", correctAnswer: "15¢", distractors: ["5¢", "10¢", "25¢"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🍪\nA cookie costs 90¢. You pay with $1. How much change do you get?", correctAnswer: "10¢", distractors: ["1¢", "5¢", "20¢"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "✏️\nA pencil costs 45¢ and an eraser costs 30¢. How much for both?", correctAnswer: "75¢", distractors: ["65¢", "70¢", "85¢"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🧸\nA toy costs $7. You pay with a $10 bill. How much change do you get?", correctAnswer: "$3", distractors: ["$2", "$4", "$17"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "📚\nA book costs $15. You pay with a $20 bill. How much change do you get?", correctAnswer: "$5", distractors: ["$3", "$10", "$15"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎟️\nA ticket costs $12. You pay with a $20 bill. How much change do you get?", correctAnswer: "$8", distractors: ["$7", "$9", "$12"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📒\nA notebook costs $2 and a pen costs $1. You pay with a $5 bill. How much change do you get?", correctAnswer: "$2", distractors: ["$1", "$3", "$4"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🛒\nMilk costs $3, bread costs $2 and eggs cost $4. What is the total?", correctAnswer: "$9", distractors: ["$7", "$8", "$10"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🧁\nCupcakes cost $2 each. How much do 6 cupcakes cost?", correctAnswer: "$12", distractors: ["$8", "$10", "$14"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🍉\nA watermelon costs $5. How much do 4 watermelons cost?", correctAnswer: "$20", distractors: ["$9", "$15", "$25"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "💵\nYou earn $4 a week for chores. How much do you earn in 5 weeks?", correctAnswer: "$20", distractors: ["$9", "$16", "$25"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🐷\nYou have $8 and a kite costs $15. How much more do you need?", correctAnswer: "$7", distractors: ["$5", "$8", "$23"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🫙\nYou get $12 and put half in your Save jar. How much did you save?", correctAnswer: "$6", distractors: ["$3", "$4", "$8"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏷️\nThe same cereal costs $4 at Store A and $3 at Store B. Where do you pay less?", correctAnswer: "Store B", distractors: ["Store A", "Both cost the same", "Neither store sells it"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🎯\nYou have $10. Which two things can you buy together?", correctAnswer: "A $4 book and a $5 ball", distractors: ["A $6 book and a $5 ball", "A $7 kite and a $4 yo-yo", "An $8 puzzle and a $3 top"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎨\nPaints cost $23. You pay with a $50 bill. How much change do you get?", correctAnswer: "$27", distractors: ["$17", "$33", "$37"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "👟\nSneakers cost $64. You pay with a $100 bill. How much change do you get?", correctAnswer: "$36", distractors: ["$26", "$44", "$46"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🎒\nA backpack costs $38. You pay with two $20 bills. How much change do you get?", correctAnswer: "$2", distractors: ["$8", "$12", "$18"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧃\nA drink costs $1.25. You pay with $2.00. How much change do you get?", correctAnswer: "$0.75", distractors: ["$0.25", "$0.85", "$1.75"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🥪\nA sandwich costs $3.60. You pay with a $5 bill. How much change do you get?", correctAnswer: "$1.40", distractors: ["$1.30", "$1.60", "$2.40"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍿\nPopcorn costs $4.35. You pay with a $10 bill. How much change do you get?", correctAnswer: "$5.65", distractors: ["$4.65", "$5.75", "$6.65"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🚲\nA bike costs $120. You have saved $85. How much more do you need?", correctAnswer: "$35", distractors: ["$25", "$45", "$205"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🎧\nHeadphones cost $45. You save $5 each week. How many weeks until you can buy them?", correctAnswer: "9", distractors: ["5", "8", "10"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🎮\nA game costs $60. You save $10 each week. How many weeks until you can buy it?", correctAnswer: "6", distractors: ["4", "5", "10"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🪙\nYou save 25¢ every day for 8 days. How much did you save?", correctAnswer: "$2.00", distractors: ["$0.33", "$1.50", "$2.50"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍎\nApples cost 40¢ each. How much do 3 apples cost?", correctAnswer: "$1.20", distractors: ["$0.43", "$1.00", "$1.40"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🎈\n5 friends share the cost of $20 worth of balloons equally. How much does each friend pay?", correctAnswer: "$4", distractors: ["$5", "$15", "$100"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🍕\nA pizza costs $18. Three friends split the cost equally. How much does each one pay?", correctAnswer: "$6", distractors: ["$3", "$9", "$15"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🫙\nYou split $30 equally into Save, Spend and Share jars. How much goes in each jar?", correctAnswer: "$10", distractors: ["$5", "$15", "$30"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧮\nHow much money are 7 quarters?", correctAnswer: "$1.75", distractors: ["$0.70", "$1.50", "$2.00"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧮\nHow many dimes are in $3.50?", correctAnswer: "35", distractors: ["14", "30", "350"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧮\nHow many pennies are in $5?", correctAnswer: "500", distractors: ["50", "100", "5,000"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "⚖️\nWhich costs more: 2 pens at $3 each, or 1 marker set for $5?", correctAnswer: "The 2 pens", distractors: ["The marker set", "They cost the same", "You can't tell"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "⚖️\nWhich costs less: 3 stickers at 20¢ each, or 1 sticker sheet for 50¢?", correctAnswer: "The sticker sheet", distractors: ["The 3 stickers", "They cost the same", "You can't tell"], tier: .medium, grades: 3...4),
        // ── Grades 2–5 · Smart choices, stores and banks ──
        BankQuestion(prompt: "💡\nBefore buying something big, what is a smart question to ask?", correctAnswer: "Do I really need it?", distractors: ["What color is the store?", "Is it the most expensive one?", "Can I buy two right now?"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧺\nMom gives you $5 only for fruit. What should you do?", correctAnswer: "Buy fruit with it", distractors: ["Buy candy with it", "Buy a toy with it", "Hide the money"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "💸\nWhat happens if you spend all your money right away?", correctAnswer: "Nothing is left for later", distractors: ["The money comes back by itself", "You get more money", "The store gives you a prize"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "💸\nWhen you shop, what is \"change\"?", correctAnswer: "Money you get back when you pay more than the price", distractors: ["Money you owe the store", "A free toy", "The price tag"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "💰\nWhat is an allowance?", correctAnswer: "Money a kid gets regularly from family", distractors: ["Money a store gives away", "A kind of bank", "A coin collection"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📄\nWhat paper shows what you bought and how much you paid?", correctAnswer: "A receipt", distractors: ["A coupon", "A map", "A menu"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧾\nWhy is it smart to keep a receipt?", correctAnswer: "So you can return or exchange something", distractors: ["To use it as money", "To pay next time", "To get free money"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏷️\nWhat is a \"sale\" at a store?", correctAnswer: "When prices are lowered for a while", distractors: ["When prices go up", "When the store is closed", "When everything is free"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎟️\nWhat is a coupon?", correctAnswer: "A paper or code that lowers the price", distractors: ["A bill worth $100", "A bank statement", "A tag that raises the price"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏦\nWho works at a bank and helps you put money in or take it out?", correctAnswer: "A teller", distractors: ["A lifeguard", "A mail carrier", "A chef"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏦\nWhat is it called when you put money INTO your bank account?", correctAnswer: "A deposit", distractors: ["A withdrawal", "A loan", "A receipt"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏧\nWhat is it called when you take money OUT of your bank account?", correctAnswer: "A withdrawal", distractors: ["A deposit", "A coupon", "A tax"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏧\nWhat is an ATM?", correctAnswer: "A machine where you can get cash from your bank account", distractors: ["A machine that prints free money", "A store that sells coins", "A kind of piggy bank"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔁\nWhat is it called when people trade things without using money?", correctAnswer: "Bartering", distractors: ["Budgeting", "Saving", "Borrowing"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏭\nPeople who make goods or offer services are called…", correctAnswer: "Producers", distractors: ["Consumers", "Customers", "Shoppers"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛍️\nPeople who buy and use goods and services are called…", correctAnswer: "Consumers", distractors: ["Producers", "Factories", "Farms"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "✂️\nA haircut is an example of a…", correctAnswer: "Service", distractors: ["Good", "Coin", "Bill"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🍏\nAn apple you buy at the store is an example of a…", correctAnswer: "Good", distractors: ["Service", "Bank", "Budget"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🩺\nWhich one is a service?", correctAnswer: "A doctor checking your health", distractors: ["A box of crayons", "A bike", "A loaf of bread"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "💸\nWhat is a donation?", correctAnswer: "Money or things given to help others", distractors: ["Money you borrow", "A bank fee", "A store price"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🤲\nWhat is a charity?", correctAnswer: "A group that helps people or animals in need", distractors: ["A kind of store", "A bank account", "A price tag"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "📋\nWhat is a budget?", correctAnswer: "A plan for how to spend and save money", distractors: ["A kind of coin", "A big store", "A shopping cart"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📋\nYour party budget is $20. Which set of things fits the budget?", correctAnswer: "Plates for $5 and snacks for $12", distractors: ["Balloons for $10 and a cake for $15", "Games for $18 and hats for $6", "Pizza for $25"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "📺\nWhy do ads try to make you want things?", correctAnswer: "To get you to buy them", distractors: ["To help you save", "To teach you math", "To lower prices"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🧑‍💼\nAn entrepreneur is someone who…", correctAnswer: "Starts a business", distractors: ["Only buys things", "Collects coins", "Counts money at a bank"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🍋\nYou sell lemonade for 50¢ a cup and sell 12 cups. How much money do you take in?", correctAnswer: "$6.00", distractors: ["$5.00", "$6.50", "$12.50"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍋\nYour lemonade supplies cost $4 and you sold $10 of lemonade. What is your profit?", correctAnswer: "$6", distractors: ["$4", "$10", "$14"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "📈\nWhat is profit?", correctAnswer: "Money left after paying your costs", distractors: ["All the money you spend", "The price of supplies", "Money you borrow"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🍰\nBake-sale supplies cost $15. You sell 30 cookies for $1 each. What is your profit?", correctAnswer: "$15", distractors: ["$1", "$30", "$45"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🧮\nYou earn $50 and spend $35. How much can you save?", correctAnswer: "$15", distractors: ["$5", "$25", "$85"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🧮\nYour income is $40 a week and your expenses are $28. How much is left?", correctAnswer: "$12", distractors: ["$8", "$18", "$68"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🐷\nYour allowance is $20 a week and you spend $15. How much do you save in 4 weeks?", correctAnswer: "$20", distractors: ["$5", "$15", "$60"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "💼\nWhat is income?", correctAnswer: "Money you earn or receive", distractors: ["Money you spend", "Money you owe", "A price tag"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🧾\nWhat is an expense?", correctAnswer: "Money you spend", distractors: ["Money you earn", "Money in a piggy bank", "A paycheck"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌧️\nWhy is it good to have an emergency fund?", correctAnswer: "To pay for surprises, like a broken bike", distractors: ["To buy candy every day", "To lend to strangers", "To never use a bank"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🤔\nYou can buy a movie ticket or a book, but not both. You pick the ticket. What is the book called?", correctAnswer: "Your opportunity cost", distractors: ["Your discount", "Your interest", "Your change"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🧸\nMany people want a toy, but the store has only a few. What usually happens to the price?", correctAnswer: "It goes up", distractors: ["It goes down", "It becomes free", "It drops to zero"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🛒\nWhat is an impulse buy?", correctAnswer: "Buying something on the spot without planning", distractors: ["Buying something from your list", "Saving for months", "Comparing prices first"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🔐\nWhat should you never share with other people?", correctAnswer: "Your bank PIN", distractors: ["Your favorite song", "A thank-you note", "A book report"], tier: .medium, grades: 4...7),
        BankQuestion(prompt: "🎣\nAn email asks for your bank password so you can \"win a prize.\" What is it most likely?", correctAnswer: "A scam", distractors: ["A real prize", "A gift from the bank", "A school project"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "💳\nWhat does a debit card do?", correctAnswer: "Pays with money from your bank account", distractors: ["Borrows money you pay back later", "Gives you free money", "Opens the bank door"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "💳\nWhat does it mean to pay with a credit card?", correctAnswer: "You borrow money that you must pay back", distractors: ["You use free money", "You pay with coins", "You spend money from a piggy bank"], tier: .medium, grades: 4...6),
        // ── Grades 4–6 · Discounts, unit price, earning ──
        BankQuestion(prompt: "🏷️\nA $30 shirt is on sale for half price. How much do you pay?", correctAnswer: "$15", distractors: ["$10", "$20", "$25"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🎁\nBuy one, get one free: 2 cans cost $3 together. What does each can really cost?", correctAnswer: "$1.50", distractors: ["$1.00", "$3.00", "$6.00"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🍫\nChocolate bars are 3 for $2.40. How much is one bar?", correctAnswer: "80¢", distractors: ["60¢", "$1.20", "$7.20"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🍿\nA movie ticket costs $11.50 and snacks cost $6.25. What is the total?", correctAnswer: "$17.75", distractors: ["$16.75", "$17.25", "$18.75"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🧮\nYou buy 3 items for $4.99 each. About how much is that?", correctAnswer: "About $15", distractors: ["About $5", "About $12", "About $20"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🏷️\nA $40 game is 25% off. How much do you pay?", correctAnswer: "$30", distractors: ["$10", "$25", "$35"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏷️\nA $50 book is 10% off. How much do you pay?", correctAnswer: "$45", distractors: ["$5", "$40", "$48"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏷️\nShoes cost $45 and are 1/3 off. What is the sale price?", correctAnswer: "$30", distractors: ["$15", "$35", "$42"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "✏️\nWhich pencil deal is the best buy?", correctAnswer: "10 pencils for $3", distractors: ["2 pencils for $1", "4 pencils for $2", "5 pencils for $2"], tier: .medium, grades: 5...6),
        BankQuestion(prompt: "🧃\nA 12-pack of juice boxes costs $6.00. What does one juice box cost?", correctAnswer: "50¢", distractors: ["60¢", "72¢", "$2.00"], tier: .medium, grades: 5...6),
        BankQuestion(prompt: "🍎\n4 pounds of apples cost $6. How much does 1 pound cost?", correctAnswer: "$1.50", distractors: ["$1.00", "$2.00", "$24.00"], tier: .medium, grades: 5...6),
        BankQuestion(prompt: "💵\nYou have a $20 bill and pens cost $1.75 each. What is the most pens you can buy?", correctAnswer: "11", distractors: ["9", "10", "12"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🎡\nYou have $25 and rides cost $3.50 each. After 6 rides, how much is left?", correctAnswer: "$4.00", distractors: ["$3.50", "$4.50", "$21.00"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "💼\nYou work 10 hours and earn $12 an hour. How much do you earn?", correctAnswer: "$120", distractors: ["$22", "$102", "$1,200"], tier: .medium, grades: 5...6),
        BankQuestion(prompt: "🧑‍🌾\nYou mow 3 lawns a week for $20 each. How many weeks to earn $300?", correctAnswer: "5", distractors: ["3", "10", "15"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🎯\nA bike costs $240 and you save $30 a month. How many months until you can buy it?", correctAnswer: "8", distractors: ["6", "7", "9"], tier: .medium, grades: 5...6),
        BankQuestion(prompt: "📋\nYou save 20% of $50. How much do you save?", correctAnswer: "$10", distractors: ["$5", "$20", "$25"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🎟️\nA streaming plan costs $12 a month. How much is that for a whole year?", correctAnswer: "$144", distractors: ["$120", "$132", "$156"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🏦\nWhat is interest on a savings account?", correctAnswer: "Money the bank pays you for keeping your money there", distractors: ["A fee for walking into the bank", "A discount on toys", "Money you pay to use an ATM"], tier: .medium, grades: 5...6),
        BankQuestion(prompt: "🏦\nWhich kind of bank account usually pays more interest and is not for everyday spending?", correctAnswer: "Savings account", distractors: ["Checking account", "Gift card", "Library card"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🧾\nWhat does a bank statement show?", correctAnswer: "The money that went into and out of your account", distractors: ["The bank's opening hours", "Your grades at school", "Prices at the grocery store"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🧾\nWhat is sales tax?", correctAnswer: "Extra money added to a price that goes to the government", distractors: ["A discount from the store", "Money the store pays you", "A tip for the cashier"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "💼\nWhat is the money taken from paychecks to pay for roads, schools and more called?", correctAnswer: "Taxes", distractors: ["Tips", "Coupons", "Allowance"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "📉\nWhat is debt?", correctAnswer: "Money that you owe", distractors: ["Money that you earned", "Money in a piggy bank", "A gift"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🌱\nWhich usually helps savings grow the most over many years?", correctAnswer: "Starting to save early", distractors: ["Starting to save later", "Keeping cash under the bed", "Never saving"], tier: .medium, grades: 5...8),
        // ── Grades 6–8 · Percent, tax, tips, interest, credit ──
        BankQuestion(prompt: "🏷️\nAn $80 jacket is 20% off. How much money do you save?", correctAnswer: "$16", distractors: ["$20", "$60", "$64"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🛹\nA $60 skateboard is 30% off. What is the sale price?", correctAnswer: "$42", distractors: ["$18", "$30", "$48"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🥣\nA 10-ounce box of cereal costs $3.00. What is the unit price?", correctAnswer: "30¢ per ounce", distractors: ["3¢ per ounce", "33¢ per ounce", "$3 per ounce"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🧃\nWhich bottle of juice is the best buy?", correctAnswer: "64 ounces for $4.00", distractors: ["16 ounces for $1.20", "32 ounces for $2.50", "48 ounces for $3.60"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🍏\n4 pounds of apples cost $6. At that price, how much would 10 pounds cost?", correctAnswer: "$15", distractors: ["$12", "$16", "$60"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🧾\nA $20 toy has a 5% sales tax. How much is the tax?", correctAnswer: "$1.00", distractors: ["$0.50", "$2.00", "$5.00"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🧾\nA $250 bike has a 6% sales tax. How much is the tax?", correctAnswer: "$15", distractors: ["$1.50", "$6", "$25"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🧾\nA $40 item has an 8% sales tax. What is the total cost?", correctAnswer: "$43.20", distractors: ["$32.00", "$40.80", "$48.00"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🍽️\nA meal costs $30 and you leave a 20% tip. How much is the tip?", correctAnswer: "$6", distractors: ["$3", "$10", "$20"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🍽️\nA meal costs $25 and you leave a 15% tip. How much is the tip?", correctAnswer: "$3.75", distractors: ["$1.50", "$2.50", "$4.25"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "💼\nYou earn $15 an hour and work 6 hours a week. How much do you earn in 4 weeks?", correctAnswer: "$360", distractors: ["$90", "$240", "$600"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🥧\nFood is 30% of a $500 monthly budget. How much money is for food?", correctAnswer: "$150", distractors: ["$30", "$130", "$170"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "📋\nA family's budget is $4,000 a month and rent is $1,000. What percent goes to rent?", correctAnswer: "25%", distractors: ["4%", "10%", "40%"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "📱\nPhone A costs $600 up front. Phone B costs $30 a month for 24 months. How much more does Phone B cost in total?", correctAnswer: "$120", distractors: ["$30", "$60", "$720"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏷️\nOn a $100 coat, which is the better deal: 30% off or $25 off?", correctAnswer: "30% off", distractors: ["$25 off", "They are the same", "You can't tell"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🎯\nWhy is \"Save $50 by June\" a better goal than \"save some money\"?", correctAnswer: "It is specific and has a deadline", distractors: ["It is harder to measure", "It has no end date", "It needs no plan"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🧾\nWhat is a warranty?", correctAnswer: "A promise to fix or replace a product if it breaks", distractors: ["A coupon for next time", "A type of tax", "A bank loan"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🧾\nWhat is a checking account mostly used for?", correctAnswer: "Paying for everyday things", distractors: ["Earning the most interest", "Storing gold bars", "Collecting coins"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "📈\nYou put $100 in savings that earns 5% simple interest per year. How much interest do you earn in 1 year?", correctAnswer: "$5", distractors: ["$0.50", "$50", "$105"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "💳\nWhen you borrow money, what is the interest?", correctAnswer: "Extra money you pay back on top of what you borrowed", distractors: ["A gift from the lender", "The amount you borrowed", "A coupon"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "🏦\nWhy do banks lend money?", correctAnswer: "To earn interest from the borrowers", distractors: ["Because they want to lose money", "Because loans are always free", "To close the bank"], tier: .hard, grades: 6...8),
        BankQuestion(prompt: "📈\n$200 earns 3% simple interest per year. How much interest is that after 2 years?", correctAnswer: "$12", distractors: ["$6", "$60", "$206"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "📈\n$500 earns 4% simple interest per year. What is the balance after 3 years?", correctAnswer: "$560", distractors: ["$512", "$520", "$620"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "📈\nWhat is compound interest?", correctAnswer: "Interest earned on your money and on the interest it already earned", distractors: ["Interest only on your first deposit", "A fee for closing an account", "A discount on a loan"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "📈\n$100 earns 10% interest, compounded once a year. What is the balance after 2 years?", correctAnswer: "$121", distractors: ["$110", "$120", "$200"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "💳\nYou borrow $1,000 at 6% simple interest for 1 year. How much do you pay back in all?", correctAnswer: "$1,060", distractors: ["$940", "$1,006", "$1,600"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "💳\nWhat usually happens if you pay only part of your credit card bill?", correctAnswer: "You are charged interest on the rest", distractors: ["The rest is forgiven", "The bank pays it for you", "Your prices go down"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "📊\nWhat is a credit score?", correctAnswer: "A number that shows how well someone pays back money they borrow", distractors: ["The cash in your wallet", "Your grade in math class", "The price of a credit card"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "📝\nWhat is a mortgage?", correctAnswer: "A loan to buy a home", distractors: ["A savings account", "A tax refund", "A store coupon"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🚗\nA car loan payment is $300 a month for 5 years. How much is paid in all?", correctAnswer: "$18,000", distractors: ["$1,500", "$3,600", "$15,000"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🛡️\nIn the US, what insures money in a bank account, up to a limit, if the bank fails?", correctAnswer: "The FDIC", distractors: ["The stock market", "A credit card company", "The school board"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "📈\nWhat is a share of stock?", correctAnswer: "A small piece of ownership in a company", distractors: ["A loan to a friend", "A kind of coin", "A bank receipt"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "📉\nWhy is it risky to put all your savings into one company's stock?", correctAnswer: "Its value can drop", distractors: ["Stocks never change in value", "Banks forbid it", "It always doubles"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🧺\nWhat does it mean to diversify your investments?", correctAnswer: "Spread your money across different investments", distractors: ["Put all your money in one place", "Keep all your money under a mattress", "Spend all your money"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🎈\nWhat is inflation?", correctAnswer: "When prices rise over time", distractors: ["When prices fall every day", "When banks close", "When coins get bigger"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "💰\nIf prices rise 3% in a year, something that cost $100 now costs about…", correctAnswer: "$103", distractors: ["$97", "$130", "$300"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "💼\nWhat is gross pay?", correctAnswer: "Pay before taxes and deductions are taken out", distractors: ["Pay after taxes are taken out", "Money spent on groceries", "Only a bonus"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "💼\nWhat is net pay?", correctAnswer: "Pay after taxes and deductions are taken out", distractors: ["Pay before taxes", "The total at a store", "Money in a piggy bank"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🧾\nWhich of these is a fixed expense?", correctAnswer: "Rent that is the same every month", distractors: ["Movie tickets", "Snacks at the mall", "A surprise gift"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🛒\nWhich of these is a variable expense that changes month to month?", correctAnswer: "Money spent on eating out", distractors: ["Rent that never changes", "A set monthly phone plan", "A fixed car payment"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🧮\nA price rises from $20 to $25. What is the percent increase?", correctAnswer: "25%", distractors: ["5%", "20%", "80%"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🧮\nA price drops from $50 to $40. What is the percent decrease?", correctAnswer: "20%", distractors: ["10%", "25%", "80%"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🏷️\nA store buys an item for $20 and marks it up 50%. What is the new price?", correctAnswer: "$30", distractors: ["$25", "$40", "$70"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "📊\nAn investment grows from $200 to $260. What is the percent gain?", correctAnswer: "30%", distractors: ["6%", "23%", "60%"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "⚖️\nWhich is more: 30% of $50 or 50% of $30?", correctAnswer: "They are the same", distractors: ["30% of $50", "50% of $30", "You can't tell"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🏷️\nA $100 item is 20% off, then another 10% off the sale price. What is the final price?", correctAnswer: "$72", distractors: ["$70", "$80", "$90"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "📈\nBy the Rule of 72, money growing 8% a year doubles in about how many years?", correctAnswer: "9", distractors: ["6", "8", "12"], tier: .hard, grades: 8...8),
    ]
}
