import Foundation

/// 🏛️ History & social studies — English (US). Adapted from the Hebrew `history` lists
/// (QuestionBanks, Expanded, Workflow 1–3, CurriculumHumanities) as a map of learning goals.
/// Universal items (inventions, ancient civilizations, explorers, scientists) are kept;
/// Israeli/Jewish history and holidays are replaced by what US social studies teaches:
/// K–1 symbols, holidays and community helpers · 2 historical figures and then-and-now ·
/// 3 communities and early settlements · 4 Native nations and national/regional history ·
/// 5 colonies, Revolution, Declaration, Constitution · 6 ancient civilizations ·
/// 7 Middle Ages and world history · 8 US history through Reconstruction + civics basics.
/// Settled facts only — no current officeholders, no contested interpretations.
extension EnglishContent {
    static let history: [BankQuestion] = [
        // ── K–1 · American symbols ──
        BankQuestion(prompt: "🎨\nWhat colors are on the American flag?", correctAnswer: "Red, white and blue", distractors: ["Red, yellow and green", "Black, white and gold", "Blue, green and orange"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔍\nThe American flag has stripes and lots of…", correctAnswer: "Stars", distractors: ["Hearts", "Circles", "Moons"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🇺🇸\nWhich bird is a symbol of the United States?", correctAnswer: "Bald eagle", distractors: ["Robin", "Parrot", "Penguin"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🔦\nWhich famous statue stands in New York Harbor holding a torch?", correctAnswer: "Statue of Liberty", distractors: ["Lincoln Memorial", "Mount Rushmore", "Liberty Bell"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🏔️\nWhich monument has the faces of four presidents carved into a mountain?", correctAnswer: "Mount Rushmore", distractors: ["Statue of Liberty", "Washington Monument", "Golden Gate Bridge"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔔\nWhich famous bell with a big crack is in Philadelphia?", correctAnswer: "Liberty Bell", distractors: ["Big Ben", "Wedding bell", "Jingle bell"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🏷️\nWhat is a popular nickname for the American flag?", correctAnswer: "Stars and Stripes", distractors: ["Union Jack", "Maple Leaf", "Rising Sun"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "⭐\nHow many stars are on the American flag?", correctAnswer: "50", distractors: ["13", "48", "25"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "⭐\nWhat does each star on the American flag stand for?", correctAnswer: "One state", distractors: ["One president", "One big city", "One river"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎤\nWhat is the name of the national anthem of the United States?", correctAnswer: "The Star-Spangled Banner", distractors: ["America the Beautiful", "Yankee Doodle", "Twinkle, Twinkle, Little Star"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "✋\nWhat do many students say while facing the flag at the start of the school day?", correctAnswer: "The Pledge of Allegiance", distractors: ["The Gettysburg Address", "The alphabet song", "A tongue twister"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "🗽\nThe Statue of Liberty was a gift from which country?", correctAnswer: "France", distractors: ["England", "Spain", "Mexico"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌎\nHow many states are in the United States?", correctAnswer: "50", distractors: ["48", "52", "13"], tier: .easy, grades: 2...4),

        // ── K–1 · Presidents we meet early ──
        BankQuestion(prompt: "🎩\nWho was the first president of the United States?", correctAnswer: "George Washington", distractors: ["Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🏠\nWhat is the name of the house where the president lives and works?", correctAnswer: "The White House", distractors: ["Mount Rushmore", "The Statue of Liberty", "The Liberty Bell"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🎩\nWhich president was nicknamed \"Honest Abe\"?", correctAnswer: "Abraham Lincoln", distractors: ["George Washington", "Thomas Jefferson", "John Adams"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🪙\nWhich president is on the penny?", correctAnswer: "Abraham Lincoln", distractors: ["George Washington", "Thomas Jefferson", "Benjamin Franklin"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "💵\nWhich president is on the one-dollar bill?", correctAnswer: "George Washington", distractors: ["Abraham Lincoln", "Thomas Jefferson", "John Adams"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "👑\nWhich president is often called the \"Father of His Country\"?", correctAnswer: "George Washington", distractors: ["Abraham Lincoln", "Thomas Jefferson", "Theodore Roosevelt"], tier: .medium, grades: 2...4),

        // ── K–3 · Holidays ──
        BankQuestion(prompt: "🎆\nWhich summer holiday do Americans celebrate with fireworks, parades and picnics?", correctAnswer: "Independence Day", distractors: ["Thanksgiving", "Valentine's Day", "Earth Day"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🎂\nOn Independence Day, we celebrate the birthday of…", correctAnswer: "The United States", distractors: ["George Washington", "The first Thanksgiving", "The Statue of Liberty"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "📅\nOn what date do Americans celebrate Independence Day?", correctAnswer: "July 4", distractors: ["December 25", "January 1", "October 31"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🍽️\nOn which holiday do families share a big meal and give thanks?", correctAnswer: "Thanksgiving", distractors: ["Halloween", "Independence Day", "Labor Day"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍗\nWhich bird is often the main dish at Thanksgiving dinner?", correctAnswer: "Turkey", distractors: ["Penguin", "Parrot", "Owl"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "📅\nIn which month do Americans celebrate Thanksgiving?", correctAnswer: "November", distractors: ["July", "February", "May"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "⛵\nWhich ship carried the Pilgrims to America in 1620?", correctAnswer: "Mayflower", distractors: ["Titanic", "Santa María", "Half Moon"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌽\nThe Pilgrims shared a harvest feast in 1621 with which Native American people?", correctAnswer: "Wampanoag", distractors: ["Cherokee", "Navajo", "Inuit"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌱\nWhich crop did Squanto help the Pilgrims learn to grow?", correctAnswer: "Corn", distractors: ["Rice", "Bananas", "Coffee"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✊\nMartin Luther King Jr. Day honors a leader who worked for…", correctAnswer: "Fair and equal rights for all people", distractors: ["Faster cars", "Bigger cities", "New planets"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🚶\nMartin Luther King Jr. believed in changing unfair laws through…", correctAnswer: "Peaceful protest", distractors: ["Fighting", "Secret codes", "Magic spells"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "📅\nIn which month do we celebrate Martin Luther King Jr. Day?", correctAnswer: "January", distractors: ["July", "November", "May"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎩\nWhich February holiday honors George Washington, Abraham Lincoln and other leaders of our nation?", correctAnswer: "Presidents' Day", distractors: ["Labor Day", "Memorial Day", "Thanksgiving"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🛠️\nOn Labor Day, Americans honor…", correctAnswer: "Workers", distractors: ["Pets", "Astronauts", "Kings"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎖️\nOn Veterans Day, Americans thank people who…", correctAnswer: "Served in the military", distractors: ["Invented machines", "Won sports games", "Wrote books"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌳\nWhich holiday is all about planting trees?", correctAnswer: "Arbor Day", distractors: ["Labor Day", "Flag Day", "Memorial Day"], tier: .medium, grades: 1...3),
        BankQuestion(prompt: "♻️\nWhich day in April is about taking care of our planet?", correctAnswer: "Earth Day", distractors: ["Flag Day", "Labor Day", "Veterans Day"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🎉\nWhich holiday celebrates the end of slavery in the United States?", correctAnswer: "Juneteenth", distractors: ["Labor Day", "Flag Day", "Arbor Day"], tier: .medium, grades: 2...5),

        // ── K–1 · Community helpers ──
        BankQuestion(prompt: "🚒\nWhich community helper puts out fires?", correctAnswer: "Firefighter", distractors: ["Mail carrier", "Baker", "Dentist"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "✉️\nWhich community helper brings letters and packages to our homes?", correctAnswer: "Mail carrier", distractors: ["Firefighter", "Farmer", "Pilot"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🤒\nWhich community helper takes care of us when we are sick?", correctAnswer: "Doctor", distractors: ["Mail carrier", "Firefighter", "Bus driver"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚦\nWhich community helper directs traffic and helps keep our neighborhood safe?", correctAnswer: "Police officer", distractors: ["Librarian", "Baker", "Farmer"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "📚\nWhich community helper helps us find books to borrow?", correctAnswer: "Librarian", distractors: ["Firefighter", "Dentist", "Pilot"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌽\nWhich community helper grows the food we eat?", correctAnswer: "Farmer", distractors: ["Librarian", "Mail carrier", "Pilot"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🦷\nWhich community helper takes care of our teeth?", correctAnswer: "Dentist", distractors: ["Baker", "Mail carrier", "Farmer"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🏫\nWho helps children learn at school?", correctAnswer: "Teacher", distractors: ["Firefighter", "Pilot", "Farmer"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🚌\nWho drives children to school in a big yellow bus?", correctAnswer: "Bus driver", distractors: ["Pilot", "Baker", "Dentist"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🐶\nWhich community helper takes care of sick pets?", correctAnswer: "Veterinarian", distractors: ["Mail carrier", "Librarian", "Pilot"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍞\nWhich community helper bakes bread and cakes?", correctAnswer: "Baker", distractors: ["Dentist", "Firefighter", "Mail carrier"], tier: .easy, grades: 0...1),

        // ── K–2 · Past and present ──
        BankQuestion(prompt: "🕰️\nWhich word means a time that already happened?", correctAnswer: "Past", distractors: ["Future", "Present", "Tomorrow"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🔮\nWhich word means a time that has not happened yet?", correctAnswer: "Future", distractors: ["Past", "Yesterday", "Long ago"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🌙\nLong ago, before electric lights, what did people light to see at night?", correctAnswer: "Candles", distractors: ["Phones", "Computers", "TVs"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🛣️\nLong ago, before cars, which animal did many people ride to get around?", correctAnswer: "Horse", distractors: ["Dolphin", "Penguin", "Rabbit"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📬\nBefore computers, what did people use to write letters?", correctAnswer: "Pen and paper", distractors: ["Laptop", "Tablet", "Smartphone"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "👵\nBefore telephones, how did people usually send news to family far away?", correctAnswer: "They wrote letters", distractors: ["They sent emails", "They made video calls", "They sent text messages"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🥛\nBefore refrigerators, what did people use to keep food cold?", correctAnswer: "Ice", distractors: ["Fire", "Sand", "Sunlight"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🧺\nLong ago, before washing machines, how did people clean their clothes?", correctAnswer: "By hand", distractors: ["With robots", "With computers", "At a car wash"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏫\nLong ago, many American children learned together in a school with just one room. What was it called?", correctAnswer: "One-room schoolhouse", distractors: ["Skyscraper", "Castle", "Lighthouse"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🗺️\nLong ago, which vehicle carried people across the country on railroad tracks?", correctAnswer: "Steam train", distractors: ["Airplane", "Rocket", "Submarine"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🏡\nMany American pioneers built their homes out of…", correctAnswer: "Logs", distractors: ["Glass", "Steel", "Plastic"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🐂\nMany pioneer families traveled west in…", correctAnswer: "Covered wagons", distractors: ["Airplanes", "Buses", "Rockets"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🗿\nWhere can we go to see old objects that teach us about the past?", correctAnswer: "Museum", distractors: ["Gas station", "Car wash", "Bakery"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "📏\nWhat do we call a line that shows events in the order they happened?", correctAnswer: "Timeline", distractors: ["Map", "Recipe", "Poem"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🔍\nWhat do we call a person who studies the past?", correctAnswer: "Historian", distractors: ["Weather reporter", "Mechanic", "Pilot"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🏺\nWhat do we call old objects, like pots and tools, that people made long ago?", correctAnswer: "Artifacts", distractors: ["Planets", "Recipes", "Receipts"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🎨\nLong ago, what did early people paint on cave walls?", correctAnswer: "Animals", distractors: ["Cars", "Computers", "Airplanes"], tier: .easy, grades: 1...3),

        // ── K–4 · Inventions that changed life ──
        BankQuestion(prompt: "🌙\nWhich invention gives us light in a room at night?", correctAnswer: "Light bulb", distractors: ["Telephone", "Clock", "Bicycle"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🗣️\nWhich invention lets us talk to someone who is far away?", correctAnswer: "Telephone", distractors: ["Light bulb", "Bicycle", "Scissors"], tier: .easy, grades: 0...2),
        BankQuestion(prompt: "🍿\nWhich invention lets us watch shows and movies at home?", correctAnswer: "Television", distractors: ["Refrigerator", "Bicycle", "Toaster"], tier: .easy, grades: 0...1),
        BankQuestion(prompt: "🧊\nWhich kitchen invention keeps food cold and fresh?", correctAnswer: "Refrigerator", distractors: ["Oven", "Toaster", "Fan"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "📦\nWhich very old invention rolls and helped people move heavy loads?", correctAnswer: "The wheel", distractors: ["The computer", "The telephone", "The camera"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "⏲️\nWhich old timer measures time with sand trickling from a top bulb to a bottom bulb?", correctAnswer: "Hourglass", distractors: ["Sundial", "Wristwatch", "Calendar"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🕰️\nWhich ancient clock told the time using a moving shadow?", correctAnswer: "Sundial", distractors: ["Hourglass", "Wristwatch", "Alarm clock"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔢\nWhich old counting tool uses beads that slide on rods?", correctAnswer: "Abacus", distractors: ["Calculator", "Compass", "Sundial"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🗺️\nWhich tool with a magnetic needle helps travelers find north?", correctAnswer: "Compass", distractors: ["Hourglass", "Telescope", "Abacus"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🌾\nWhich old farm tool was pulled through the soil to get it ready for planting?", correctAnswer: "Plow", distractors: ["Telescope", "Compass", "Hourglass"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📚\nWhich invention made it much faster to make many copies of books?", correctAnswer: "Printing press", distractors: ["Telephone", "Radio", "Camera"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🦠\nWhich tool lets scientists see tiny things like cells?", correctAnswer: "Microscope", distractors: ["Telescope", "Compass", "Hourglass"], tier: .medium, grades: 4...6),

        // ── 2–5 · Famous Americans ──
        BankQuestion(prompt: "💡\nWhich inventor is famous for making a light bulb that worked well in homes?", correctAnswer: "Thomas Edison", distractors: ["Albert Einstein", "Christopher Columbus", "George Washington"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🧑‍🔬\nWhich invention is Alexander Graham Bell famous for?", correctAnswer: "Telephone", distractors: ["Light bulb", "Airplane", "Television"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "✈️\nWhich brothers flew the first successful airplane in 1903?", correctAnswer: "The Wright brothers", distractors: ["The Grimm brothers", "The Lumière brothers", "The Marx Brothers"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "⚡\nWhich Founding Father experimented with electricity and invented the lightning rod?", correctAnswer: "Benjamin Franklin", distractors: ["George Washington", "John Adams", "Paul Revere"], tier: .medium, grades: 2...5),
        BankQuestion(prompt: "💺\nRosa Parks bravely refused to give up her seat on a…", correctAnswer: "Bus", distractors: ["Train", "Airplane", "Boat"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🌟\nWhich brave woman escaped slavery and then helped many others reach freedom?", correctAnswer: "Harriet Tubman", distractors: ["Rosa Parks", "Clara Barton", "Susan B. Anthony"], tier: .medium, grades: 2...5),
        BankQuestion(prompt: "🥜\nWhich scientist found many new uses for peanuts?", correctAnswer: "George Washington Carver", distractors: ["Thomas Edison", "Benjamin Franklin", "Henry Ford"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "📣\nSusan B. Anthony worked hard so that women could…", correctAnswer: "Vote in elections", distractors: ["Fly airplanes", "Build bridges", "Play soccer"], tier: .medium, grades: 2...4),
        BankQuestion(prompt: "🚶\nWhich fruit trees did Johnny Appleseed plant?", correctAnswer: "Apple trees", distractors: ["Orange trees", "Banana trees", "Coconut trees"], tier: .easy, grades: 1...2),
        BankQuestion(prompt: "🏟️\nIn 1947, Jackie Robinson bravely broke the color barrier in which major sport?", correctAnswer: "Baseball", distractors: ["Soccer", "Hockey", "Tennis"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🩹\nWhich nurse started the American Red Cross?", correctAnswer: "Clara Barton", distractors: ["Harriet Tubman", "Amelia Earhart", "Susan B. Anthony"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "✈️\nWho was the first woman to fly an airplane alone across the Atlantic Ocean?", correctAnswer: "Amelia Earhart", distractors: ["Clara Barton", "Rosa Parks", "Harriet Tubman"], tier: .hard, grades: 3...5),
        BankQuestion(prompt: "🚗\nWhich carmaker built the Model T, a car many families could afford?", correctAnswer: "Henry Ford", distractors: ["Thomas Edison", "Benjamin Franklin", "Alexander Graham Bell"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🎤\nWhat is the name of Martin Luther King Jr.'s famous 1963 speech?", correctAnswer: "I Have a Dream", distractors: ["Gettysburg Address", "Farewell Address", "Four Freedoms"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "📖\nWhich system of raised dots helped Helen Keller read?", correctAnswer: "Braille", distractors: ["Morse code", "Hieroglyphs", "Cuneiform"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🍇\nCesar Chavez worked to improve the lives of…", correctAnswer: "Farm workers", distractors: ["Astronauts", "Kings", "Pilots"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚌\nIn which city did Rosa Parks refuse to give up her bus seat in 1955?", correctAnswer: "Montgomery, Alabama", distractors: ["Chicago, Illinois", "Boston, Massachusetts", "Seattle, Washington"], tier: .hard, grades: 5...8),

        // ── 2–4 · Communities and government ──
        BankQuestion(prompt: "🏘️\nWhat do we call a place where people live, work and play together?", correctAnswer: "Community", distractors: ["Ocean", "Planet", "Desert"], tier: .easy, grades: 1...3),
        BankQuestion(prompt: "🏙️\nWhat kind of community is a big city with tall buildings and many people?", correctAnswer: "Urban", distractors: ["Rural", "Suburban", "Wilderness"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🚜\nWhat kind of community has farms and lots of open land?", correctAnswer: "Rural", distractors: ["Urban", "Suburban", "Downtown"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🏡\nWhat kind of community is near a big city and has many houses with yards?", correctAnswer: "Suburban", distractors: ["Urban", "Rural", "Downtown"], tier: .medium, grades: 2...3),
        BankQuestion(prompt: "🏛️\nWho is the leader of a city or town?", correctAnswer: "Mayor", distractors: ["Governor", "President", "Principal"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🗺️\nWho is the leader of a state?", correctAnswer: "Governor", distractors: ["Mayor", "President", "Sheriff"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🦅\nWho is the leader of the whole United States?", correctAnswer: "President", distractors: ["Mayor", "Governor", "Principal"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "📜\nWhat do we call the rules that a government makes?", correctAnswer: "Laws", distractors: ["Games", "Recipes", "Stories"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🙋\nHow do citizens choose their leaders?", correctAnswer: "By voting", distractors: ["By flipping a coin", "By running a race", "By drawing pictures"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🚧\nWhich of these do taxes help pay for?", correctAnswer: "Public schools and roads", distractors: ["Birthday presents", "Movie tickets", "Video games"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧳\nWhat is an immigrant?", correctAnswer: "A person who moves to a new country to live", distractors: ["A person who visits for one day", "A person who fixes cars", "A person who studies stars"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "⛴️\nLong ago, millions of immigrants arriving in New York first stopped at which island?", correctAnswer: "Ellis Island", distractors: ["Rhode Island", "Easter Island", "Treasure Island"], tier: .medium, grades: 3...5),

        // ── 3 · Early settlements ──
        BankQuestion(prompt: "🌎\nWho were the first people to live in North America?", correctAnswer: "Native Americans", distractors: ["Pilgrims", "Vikings", "Spanish explorers"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧑‍🌾\nWhat do we call people who move to a new land to build homes and farms?", correctAnswer: "Settlers", distractors: ["Tourists", "Astronauts", "Pirates"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🏞️\nWhy did many early settlers build their towns near rivers?", correctAnswer: "For water and travel", distractors: ["To hide from the sun", "To avoid farming", "To stay away from boats"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🏰\nWhat was the first permanent English settlement in North America, started in 1607?", correctAnswer: "Jamestown", distractors: ["Plymouth", "Boston", "Philadelphia"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🪨\nIn 1620, the Pilgrims started a colony called…", correctAnswer: "Plymouth", distractors: ["Jamestown", "St. Augustine", "Philadelphia"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⛪\nSt. Augustine, Florida, founded in 1565 and still a city today, was started by settlers from…", correctAnswer: "Spain", distractors: ["England", "France", "Netherlands"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🌷\nNew York City began as a Dutch settlement called…", correctAnswer: "New Amsterdam", distractors: ["New Holland", "New Paris", "New London"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🏞️\nPocahontas was the daughter of a Powhatan leader who lived near which English settlement?", correctAnswer: "Jamestown", distractors: ["Plymouth", "Boston", "Philadelphia"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🤝\nWhich Patuxet man, who spoke English, helped the Pilgrims at Plymouth?", correctAnswer: "Squanto", distractors: ["Sequoyah", "Sitting Bull", "Geronimo"], tier: .hard, grades: 4...5),

        // ── 3–4 · Native American nations ──
        BankQuestion(prompt: "🌾\nWhich cone-shaped home made of poles and animal skins was used by peoples of the Great Plains?", correctAnswer: "Tipi", distractors: ["Igloo", "Longhouse", "Pueblo"], tier: .medium, grades: 3...4),
        BankQuestion(prompt: "🧥\nWhich animal gave Plains peoples food, clothing and material for shelter?", correctAnswer: "Bison", distractors: ["Camel", "Llama", "Kangaroo"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🧊\nWhat are the dome-shaped snow shelters that some Inuit people built called?", correctAnswer: "Igloos", distractors: ["Tipis", "Longhouses", "Wigwams"], tier: .easy, grades: 3...4),
        BankQuestion(prompt: "🪵\nThe Haudenosaunee (Iroquois) lived in large bark-covered homes shared by many families, called…", correctAnswer: "Longhouses", distractors: ["Tipis", "Igloos", "Pyramids"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🧱\nPueblo peoples of the Southwest built homes from sun-dried clay bricks called…", correctAnswer: "Adobe", distractors: ["Marble", "Steel", "Glass"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🌲\nNative peoples of the Pacific Northwest are famous for carving tall wooden…", correctAnswer: "Totem poles", distractors: ["Pyramids", "Castles", "Windmills"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🐟\nWhich fish was an important food for Native peoples of the Pacific Northwest?", correctAnswer: "Salmon", distractors: ["Clownfish", "Goldfish", "Piranha"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🌽\nCorn, beans and squash, which many Native American farmers grew together, are called the…", correctAnswer: "Three Sisters", distractors: ["Three Kings", "Big Three", "Three Friends"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "✍️\nWho created a writing system for the Cherokee language?", correctAnswer: "Sequoyah", distractors: ["Sacagawea", "Squanto", "Sitting Bull"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏞️\nCahokia, a large ancient Native American city with huge earth mounds, was near which river?", correctAnswer: "Mississippi River", distractors: ["Colorado River", "Hudson River", "Rio Grande"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🗺️\nThe forced removal of the Cherokee Nation from their homelands in the 1830s is known as the…", correctAnswer: "Trail of Tears", distractors: ["Oregon Trail", "Underground Railroad", "Pony Express"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "⚖️\nWhich president signed the Indian Removal Act of 1830?", correctAnswer: "Andrew Jackson", distractors: ["Thomas Jefferson", "Abraham Lincoln", "George Washington"], tier: .hard, grades: 8...8),

        // ── 4 · Growing nation, national and regional history ──
        BankQuestion(prompt: "🧭\nWhich Shoshone woman helped guide Lewis and Clark on their journey west?", correctAnswer: "Sacagawea", distractors: ["Pocahontas", "Harriet Tubman", "Clara Barton"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🗺️\nWhich president sent Lewis and Clark to explore the West?", correctAnswer: "Thomas Jefferson", distractors: ["George Washington", "Abraham Lincoln", "John Adams"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "💰\nFrom which country did the United States buy the Louisiana Territory in 1803?", correctAnswer: "France", distractors: ["Spain", "England", "Mexico"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🐻‍❄️\nFrom which country did the United States buy Alaska in 1867?", correctAnswer: "Russia", distractors: ["Canada", "England", "France"], tier: .hard, grades: 4...8),
        BankQuestion(prompt: "🗓️\nWhich two states were the last to join the United States, in 1959?", correctAnswer: "Alaska and Hawaii", distractors: ["Texas and California", "Arizona and New Mexico", "Utah and Nevada"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "👑\nWho was the last queen of the Kingdom of Hawaii?", correctAnswer: "Liliuokalani", distractors: ["Pocahontas", "Sacagawea", "Cleopatra"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⛪\nThe Alamo, a famous mission and battle site from 1836, is in which state?", correctAnswer: "Texas", distractors: ["California", "Arizona", "Florida"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "⛏️\nIn 1849, thousands of people rushed to California hoping to find…", correctAnswer: "Gold", distractors: ["Oil", "Diamonds", "Coal"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🛤️\nWhich famous trail did many pioneers follow west in covered wagons in the 1840s?", correctAnswer: "Oregon Trail", distractors: ["Appalachian Trail", "Silk Road", "Route 66"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🐎\nWhat did Pony Express riders carry across the West on horseback?", correctAnswer: "Mail", distractors: ["Gold", "Cows", "Water"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🛶\nThe Erie Canal, finished in 1825, connected the Great Lakes to which river?", correctAnswer: "Hudson River", distractors: ["Mississippi River", "Colorado River", "Missouri River"], tier: .hard, grades: 4...8),
        BankQuestion(prompt: "🗿\nWhich of these presidents is carved on Mount Rushmore?", correctAnswer: "Abraham Lincoln", distractors: ["John Adams", "Ulysses S. Grant", "John F. Kennedy"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🏔️\nIn which state is Mount Rushmore?", correctAnswer: "South Dakota", distractors: ["North Dakota", "Montana", "Wyoming"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🏕️\nWhich was the first national park in the United States, created in 1872?", correctAnswer: "Yellowstone", distractors: ["Grand Canyon", "Yosemite", "Everglades"], tier: .hard, grades: 4...5),
        BankQuestion(prompt: "🌱\nBefore the Civil War, large cotton farms were found mostly in which region?", correctAnswer: "The South", distractors: ["New England", "The Pacific Northwest", "Alaska"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "📡\nThe telegraph sent messages using a code of dots and dashes named after…", correctAnswer: "Samuel Morse", distractors: ["Eli Whitney", "Thomas Edison", "Henry Ford"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🛤️\nWhat was the Underground Railroad?", correctAnswer: "A secret network that helped enslaved people escape to freedom", distractors: ["A train that ran under a city", "A subway line in New York", "A tunnel to a gold mine"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🧭\nWhat did many people escaping slavery follow in the night sky to find their way to freedom?", correctAnswer: "The North Star", distractors: ["The Moon", "A comet", "Mars"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🎙️\nWhich man escaped slavery and became a famous speaker and writer against it?", correctAnswer: "Frederick Douglass", distractors: ["Paul Revere", "Benjamin Franklin", "Andrew Jackson"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "🚂\nIn which year was the first transcontinental railroad across the United States completed?", correctAnswer: "1869", distractors: ["1776", "1812", "1920"], tier: .hard, grades: 7...8),

        // ── 3–7 · Explorers ──
        BankQuestion(prompt: "🌊\nHow did Christopher Columbus travel to the Americas?", correctAnswer: "By sailing ship", distractors: ["By airplane", "By train", "By car"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⛵\nIn which year did Christopher Columbus first sail across the Atlantic to the Americas?", correctAnswer: "1492", distractors: ["1620", "1776", "1066"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🚢\nWhich of these was one of Columbus's ships in 1492?", correctAnswer: "Santa María", distractors: ["Mayflower", "Titanic", "Endeavour"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "👑\nChristopher Columbus sailed for the king and queen of which country?", correctAnswer: "Spain", distractors: ["England", "France", "Portugal"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🛡️\nWhich Norse explorer reached North America about 500 years before Columbus?", correctAnswer: "Leif Erikson", distractors: ["Ferdinand Magellan", "Marco Polo", "Hernán Cortés"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🌐\nWhose expedition was the first to sail all the way around the world?", correctAnswer: "Ferdinand Magellan", distractors: ["Christopher Columbus", "Marco Polo", "Leif Erikson"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🗺️\nWhich British captain explored the Pacific and mapped the coasts of New Zealand and eastern Australia?", correctAnswer: "James Cook", distractors: ["Christopher Columbus", "Leif Erikson", "Marco Polo"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🐉\nWhich Italian traveler journeyed to China and told stories about the court of Kublai Khan?", correctAnswer: "Marco Polo", distractors: ["Christopher Columbus", "Leif Erikson", "Vasco da Gama"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "🌍\nWhich Portuguese explorer was the first to sail from Europe around Africa to India?", correctAnswer: "Vasco da Gama", distractors: ["Ferdinand Magellan", "Christopher Columbus", "Marco Polo"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "⚓\nWhich Spanish conquistador led the conquest of the Aztec Empire?", correctAnswer: "Hernán Cortés", distractors: ["Francisco Pizarro", "Christopher Columbus", "Ferdinand Magellan"], tier: .hard, grades: 7...8),

        // ── 3–5 · The 13 colonies ──
        BankQuestion(prompt: "🔢\nHow many British colonies joined together to form the United States?", correctAnswer: "13", distractors: ["50", "10", "7"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "👑\nBefore the American Revolution, the 13 colonies were ruled by…", correctAnswer: "Great Britain", distractors: ["France", "Spain", "Netherlands"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🔨\nWhich colonial worker made horseshoes and tools out of iron?", correctAnswer: "Blacksmith", distractors: ["Cooper", "Cobbler", "Weaver"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🪵\nIn colonial times, what did a cooper make?", correctAnswer: "Barrels", distractors: ["Horseshoes", "Shoes", "Candles"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🗺️\nWhich colonial region included Massachusetts, Connecticut and Rhode Island?", correctAnswer: "New England", distractors: ["Middle Colonies", "Southern Colonies", "Western Colonies"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🌲\nWilliam Penn founded Pennsylvania as a safe home for which religious group?", correctAnswer: "Quakers", distractors: ["Puritans", "Catholics", "Anglicans"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🗓️\nWhich was the last of the 13 colonies to be founded, in 1732?", correctAnswer: "Georgia", distractors: ["Virginia", "Massachusetts", "New York"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "⛵\nWhat did the Pilgrims sign aboard their ship in 1620 to agree on rules for their colony?", correctAnswer: "Mayflower Compact", distractors: ["Declaration of Independence", "Bill of Rights", "Magna Carta"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏡\nWhat is the name of George Washington's home in Virginia?", correctAnswer: "Mount Vernon", distractors: ["Monticello", "The Hermitage", "Graceland"], tier: .hard, grades: 5...8),

        // ── 4–5 · The American Revolution ──
        BankQuestion(prompt: "🌊\nTo protest a British tax, colonists dumped hundreds of chests of what into Boston Harbor?", correctAnswer: "Tea", distractors: ["Coffee", "Sugar", "Gold"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🫖\nIn which year did the Boston Tea Party happen?", correctAnswer: "1773", distractors: ["1620", "1812", "1865"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "💰\nThe Stamp Act of 1765 made colonists pay a tax on…", correctAnswer: "Printed papers", distractors: ["Tea", "Horses", "Houses"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏇\nWhich silversmith rode at night in 1775 to warn that British soldiers were coming?", correctAnswer: "Paul Revere", distractors: ["Benjamin Franklin", "Thomas Jefferson", "John Hancock"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🥁\nWhat nickname did colonists give British soldiers because of their uniforms?", correctAnswer: "Redcoats", distractors: ["Minutemen", "Patriots", "Pilgrims"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "🪖\nColonial militia members who could be ready to fight at a moment's notice were called…", correctAnswer: "Minutemen", distractors: ["Redcoats", "Pilgrims", "Loyalists"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "🫡\nColonists who sided with the British king during the Revolution were called…", correctAnswer: "Loyalists", distractors: ["Patriots", "Minutemen", "Pilgrims"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "👑\nWho was king of Great Britain during the American Revolution?", correctAnswer: "George III", distractors: ["Henry VIII", "Louis XVI", "William the Conqueror"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "💥\nThe first battles of the American Revolution were fought at Lexington and…", correctAnswer: "Concord", distractors: ["Yorktown", "Gettysburg", "Saratoga"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "📖\nWhich writer's pamphlet \"Common Sense\" urged colonists to break away from Britain?", correctAnswer: "Thomas Paine", distractors: ["Paul Revere", "John Hancock", "Francis Scott Key"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "⚔️\nWho led the Continental Army during the American Revolution?", correctAnswer: "George Washington", distractors: ["Thomas Jefferson", "Benjamin Franklin", "John Adams"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "❄️\nWhere did George Washington's army spend a hard winter in 1777–1778?", correctAnswer: "Valley Forge", distractors: ["Yorktown", "Plymouth", "Gettysburg"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🛶\nWhich river did George Washington's army cross on Christmas night in 1776?", correctAnswer: "Delaware River", distractors: ["Mississippi River", "Rio Grande", "Colorado River"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🏳️\nAt which battle in 1781 did a large British army surrender to forces led by George Washington?", correctAnswer: "Yorktown", distractors: ["Lexington", "Bunker Hill", "Gettysburg"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🤝\nWhich country became an important ally of the Americans during the Revolution?", correctAnswer: "France", distractors: ["Russia", "China", "Japan"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🕊️\nWhich treaty officially ended the American Revolutionary War in 1783?", correctAnswer: "Treaty of Paris", distractors: ["Treaty of Versailles", "Treaty of Ghent", "Treaty of Tordesillas"], tier: .hard, grades: 8...8),

        // ── 4–5 · The Declaration of Independence ──
        BankQuestion(prompt: "📜\nWhich document did the colonies write to explain why they wanted to be free from Britain?", correctAnswer: "Declaration of Independence", distractors: ["Constitution", "Bill of Rights", "Gettysburg Address"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "📜\nIn which year was the Declaration of Independence approved?", correctAnswer: "1776", distractors: ["1492", "1787", "1812"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏛️\nWhich group of colonial leaders approved the Declaration of Independence?", correctAnswer: "Continental Congress", distractors: ["British Parliament", "Supreme Court", "U.S. Senate"], tier: .medium, grades: 4...5),
        BankQuestion(prompt: "✒️\nWho was the main writer of the Declaration of Independence?", correctAnswer: "Thomas Jefferson", distractors: ["George Washington", "Abraham Lincoln", "Paul Revere"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "🖋️\nWhose large signature is the most famous on the Declaration of Independence?", correctAnswer: "John Hancock", distractors: ["George Washington", "Abraham Lincoln", "Paul Revere"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "🏙️\nIn which city was the Declaration of Independence signed?", correctAnswer: "Philadelphia", distractors: ["Boston", "New York City", "Washington, D.C."], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "💬\nThe Declaration of Independence says people have the right to life, liberty and the pursuit of…", correctAnswer: "Happiness", distractors: ["Wealth", "Power", "Fame"], tier: .hard, grades: 5...8),

        // ── 5 & 8 · The Constitution and civics ──
        BankQuestion(prompt: "📜\nIn which year was the U.S. Constitution written?", correctAnswer: "1787", distractors: ["1776", "1492", "1865"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🧾\nWhich document begins with the words \"We the People\"?", correctAnswer: "The U.S. Constitution", distractors: ["The Declaration of Independence", "The Gettysburg Address", "The Emancipation Proclamation"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "🏛️\nIn which building were both the Declaration of Independence and the Constitution signed?", correctAnswer: "Independence Hall", distractors: ["The White House", "The U.S. Capitol", "Faneuil Hall"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "📚\nWho is known as the \"Father of the Constitution\"?", correctAnswer: "James Madison", distractors: ["Thomas Jefferson", "John Adams", "Alexander Hamilton"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "📃\nWhat was the first plan of government for the United States, before the Constitution?", correctAnswer: "Articles of Confederation", distractors: ["Bill of Rights", "Mayflower Compact", "Emancipation Proclamation"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🤝\nUnder the Great Compromise, a state's number of seats in the House of Representatives is based on its…", correctAnswer: "Population", distractors: ["Land area", "Number of cities", "Number of farms"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🌳\nHow many branches does the U.S. government have?", correctAnswer: "3", distractors: ["2", "4", "5"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🏛️\nWhich branch of government makes the laws?", correctAnswer: "Legislative", distractors: ["Executive", "Judicial", "Military"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "🖊️\nWhich branch of government, led by the president, carries out the laws?", correctAnswer: "Executive", distractors: ["Legislative", "Judicial", "Local"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "⚖️\nWhich branch of government, which includes the Supreme Court, decides what laws mean?", correctAnswer: "Judicial", distractors: ["Legislative", "Executive", "Military"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "🏛️\nCongress is made up of the Senate and the…", correctAnswer: "House of Representatives", distractors: ["Supreme Court", "Cabinet", "White House"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "📍\nIn which building does Congress meet?", correctAnswer: "The U.S. Capitol", distractors: ["The White House", "Mount Vernon", "The Pentagon"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "🗺️\nHow many senators does each state have?", correctAnswer: "2", distractors: ["1", "4", "10"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🗓️\nHow many years is one term for a U.S. president?", correctAnswer: "4", distractors: ["2", "6", "8"], tier: .medium, grades: 4...8),
        BankQuestion(prompt: "🗓️\nHow many years is one term for a U.S. senator?", correctAnswer: "6", distractors: ["2", "4", "8"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🗓️\nHow many years is one term for a member of the House of Representatives?", correctAnswer: "2", distractors: ["4", "6", "8"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🔄\nWhat do we call the system that lets each branch of government limit the power of the others?", correctAnswer: "Checks and balances", distractors: ["Supply and demand", "Trial and error", "Rise and fall"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "✋\nWhen the president rejects a bill passed by Congress, it is called a…", correctAnswer: "Veto", distractors: ["Verdict", "Treaty", "Tax"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "✏️\nWhat is a change or addition to the Constitution called?", correctAnswer: "Amendment", distractors: ["Election", "Veto", "Anthem"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "📜\nWhat are the first ten amendments to the Constitution called?", correctAnswer: "Bill of Rights", distractors: ["Declaration of Independence", "Articles of Confederation", "Gettysburg Address"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "📜\nWhich freedom is protected by the First Amendment?", correctAnswer: "Freedom of speech", distractors: ["Right to a jury trial", "Right to a speedy trial", "Protection from unfair searches"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🗳️\nHow old must a U.S. citizen be to vote in national elections?", correctAnswer: "18", distractors: ["16", "21", "25"], tier: .medium, grades: 4...8),
        BankQuestion(prompt: "🏛️\nWhat does the \"D.C.\" in Washington, D.C. stand for?", correctAnswer: "District of Columbia", distractors: ["Department of Congress", "Downtown Capital", "Delaware County"], tier: .medium, grades: 4...6),

        // ── 8 · The young nation ──
        BankQuestion(prompt: "🎖️\nWho was the second president of the United States?", correctAnswer: "John Adams", distractors: ["Thomas Jefferson", "Abraham Lincoln", "James Madison"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🎶\nWho wrote the words of \"The Star-Spangled Banner\"?", correctAnswer: "Francis Scott Key", distractors: ["George Washington", "Paul Revere", "Benjamin Franklin"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "🎆\nDuring which war was \"The Star-Spangled Banner\" written?", correctAnswer: "War of 1812", distractors: ["Civil War", "American Revolution", "World War I"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🌎\nWhich 1823 policy warned European countries not to start new colonies in the Americas?", correctAnswer: "Monroe Doctrine", distractors: ["Emancipation Proclamation", "Missouri Compromise", "Bill of Rights"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🌵\nAfter the Mexican-American War (1846–1848), the United States gained land that included…", correctAnswer: "California", distractors: ["Florida", "Alaska", "Louisiana"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🧵\nWho invented the cotton gin in 1793?", correctAnswer: "Eli Whitney", distractors: ["Samuel Morse", "Robert Fulton", "Cyrus McCormick"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🛠️\nRobert Fulton is famous for building a successful…", correctAnswer: "Steamboat", distractors: ["Airplane", "Telephone", "Cotton gin"], tier: .medium, grades: 7...8),
        BankQuestion(prompt: "👩\nThe Seneca Falls Convention of 1848 was the first big meeting in the US about…", correctAnswer: "Women's rights", distractors: ["Building railroads", "Ending the War of 1812", "Choosing a capital city"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🗳️\nWhich amendment gave women the right to vote in 1920?", correctAnswer: "19th Amendment", distractors: ["1st Amendment", "13th Amendment", "5th Amendment"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🗺️\nThe Missouri Compromise of 1820 let Missouri join as a slave state and which state join as a free state?", correctAnswer: "Maine", distractors: ["Ohio", "Texas", "California"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "📕\nWhich author wrote \"Uncle Tom's Cabin,\" a novel against slavery?", correctAnswer: "Harriet Beecher Stowe", distractors: ["Harriet Tubman", "Louisa May Alcott", "Emily Dickinson"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🏠\nThe Homestead Act of 1862 offered settlers…", correctAnswer: "Free land in the West", distractors: ["Free train tickets", "Gold coins", "Houses in big cities"], tier: .hard, grades: 8...8),

        // ── 5 & 8 · The Civil War and Reconstruction ──
        BankQuestion(prompt: "🇺🇸\nWho was president during the Civil War?", correctAnswer: "Abraham Lincoln", distractors: ["George Washington", "Thomas Jefferson", "Andrew Jackson"], tier: .medium, grades: 5...8),
        BankQuestion(prompt: "🔢\nAbraham Lincoln was which number president?", correctAnswer: "16th", distractors: ["1st", "3rd", "10th"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "⚖️\nWhich issue divided the North and the South most in the years before the Civil War?", correctAnswer: "Slavery", distractors: ["Railroads", "Tea taxes", "Gold mining"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "📅\nIn which year did the American Civil War begin?", correctAnswer: "1861", distractors: ["1776", "1812", "1914"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🕊️\nIn which year did the American Civil War end?", correctAnswer: "1865", distractors: ["1783", "1812", "1918"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🏰\nThe Civil War began when Confederate forces fired on which fort in 1861?", correctAnswer: "Fort Sumter", distractors: ["Fort McHenry", "Fort Knox", "The Alamo"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🧭\nDuring the Civil War, what was the group of Southern states that left the Union called?", correctAnswer: "The Confederacy", distractors: ["The Commonwealth", "The Colonies", "The Continental Army"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "📜\nIn 1863, which order by President Lincoln declared enslaved people in the Confederate states free?", correctAnswer: "Emancipation Proclamation", distractors: ["Gettysburg Address", "Bill of Rights", "Monroe Doctrine"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🎙️\nWhich short, famous speech did Lincoln give at a Pennsylvania battlefield in 1863?", correctAnswer: "Gettysburg Address", distractors: ["I Have a Dream", "Emancipation Proclamation", "Farewell Address"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🏳️\nWhich Confederate general surrendered his army at Appomattox Court House, Virginia, in 1865?", correctAnswer: "Robert E. Lee", distractors: ["Stonewall Jackson", "William T. Sherman", "Jefferson Davis"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "⭐\nWho was the top general of the Union army at the end of the Civil War?", correctAnswer: "Ulysses S. Grant", distractors: ["Robert E. Lee", "Stonewall Jackson", "George Washington"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "📜\nWhich amendment to the Constitution ended slavery in the United States?", correctAnswer: "13th Amendment", distractors: ["1st Amendment", "19th Amendment", "5th Amendment"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🔨\nWhat is the period after the Civil War, when the nation worked to rebuild the South and reunite the country, called?", correctAnswer: "Reconstruction", distractors: ["The Renaissance", "The Gold Rush", "The Revolution"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🏫\nWhich government agency, created in 1865, helped formerly enslaved people with food, schools and jobs?", correctAnswer: "Freedmen's Bureau", distractors: ["Red Cross", "Pony Express", "Peace Corps"], tier: .hard, grades: 8...8),
        BankQuestion(prompt: "🌟\nJuneteenth marks the day in 1865 when enslaved people in which state learned they were free?", correctAnswer: "Texas", distractors: ["Virginia", "New York", "California"], tier: .hard, grades: 5...8),
        BankQuestion(prompt: "⚖️\nIn Brown v. Board of Education (1954), the Supreme Court ruled that separating public school students by race was…", correctAnswer: "Unconstitutional", distractors: ["Required", "Encouraged", "Constitutional"], tier: .hard, grades: 7...8),

        // ── 6 · Early humans ──
        BankQuestion(prompt: "👣\nEarly people who moved from place to place, living on wild animals and plants instead of farming, are called…", correctAnswer: "Hunter-gatherers", distractors: ["Farmers", "Merchants", "Knights"], tier: .medium, grades: 5...6),
        BankQuestion(prompt: "🌾\nOnce early people learned to farm, many of them…", correctAnswer: "Settled down in villages", distractors: ["Stopped eating food", "Built the first airplanes", "Moved into space"], tier: .medium, grades: 5...6),
        BankQuestion(prompt: "🔥\nWhich period of history is named after a metal made by mixing copper and tin?", correctAnswer: "Bronze Age", distractors: ["Stone Age", "Iron Age", "Ice Age"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🪨\nStonehenge, a prehistoric circle of huge stones, is in which country?", correctAnswer: "England", distractors: ["Egypt", "Mexico", "China"], tier: .medium, grades: 6...7),

        // ── 3–7 · Ancient Egypt ──
        BankQuestion(prompt: "🔺\nWhich ancient people built the Great Pyramids of Giza?", correctAnswer: "Ancient Egyptians", distractors: ["Ancient Romans", "Ancient Greeks", "Vikings"], tier: .easy, grades: 3...6),
        BankQuestion(prompt: "🏞️\nWhich great river helped ancient Egyptians grow their food?", correctAnswer: "Nile", distractors: ["Amazon", "Mississippi", "Thames"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌿\nWhat did ancient Egyptians make from a river plant and use for writing?", correctAnswer: "Papyrus", distractors: ["Plastic", "Glass", "Iron"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "👑\nWhat was a king of ancient Egypt called?", correctAnswer: "Pharaoh", distractors: ["Emperor", "Shogun", "Czar"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🗿\nThe Great Sphinx of Giza has the body of which animal?", correctAnswer: "Lion", distractors: ["Horse", "Eagle", "Bull"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "✍️\nWhat was the ancient Egyptian writing made of pictures and symbols called?", correctAnswer: "Hieroglyphs", distractors: ["Cuneiform", "Braille", "Morse code"], tier: .medium, grades: 5...6),
        BankQuestion(prompt: "⚱️\nAncient Egyptians carefully wrapped and preserved the bodies of their pharaohs. What are these called?", correctAnswer: "Mummies", distractors: ["Statues", "Fossils", "Paintings"], tier: .medium, grades: 5...6),
        BankQuestion(prompt: "🪨\nWhich ancient stone helped scholars learn to read Egyptian hieroglyphs?", correctAnswer: "Rosetta Stone", distractors: ["Plymouth Rock", "Stonehenge", "Blarney Stone"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🏺\nWhich young pharaoh's tomb, full of treasure, was discovered in 1922?", correctAnswer: "Tutankhamun", distractors: ["Cleopatra", "Julius Caesar", "Alexander the Great"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "👸\nCleopatra was a famous queen of…", correctAnswer: "Egypt", distractors: ["England", "China", "Spain"], tier: .medium, grades: 6...7),

        // ── 6 · Mesopotamia, India and China ──
        BankQuestion(prompt: "🌊\nAncient Mesopotamia was located between which two rivers?", correctAnswer: "Tigris and Euphrates", distractors: ["Nile and Congo", "Amazon and Orinoco", "Yangtze and Yellow"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🔱\nWhich wedge-shaped writing was invented in ancient Mesopotamia?", correctAnswer: "Cuneiform", distractors: ["Hieroglyphs", "Braille", "Latin alphabet"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "⚖️\nWhich king of Babylon created one of the oldest written sets of laws?", correctAnswer: "Hammurabi", distractors: ["Julius Caesar", "Tutankhamun", "Alexander the Great"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "📜\nWhich ancient poem about a king of Uruk comes from Mesopotamia?", correctAnswer: "The Epic of Gilgamesh", distractors: ["The Odyssey", "The Iliad", "Beowulf"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🛕\nWhat was the stepped temple tower of ancient Mesopotamia called?", correctAnswer: "Ziggurat", distractors: ["Obelisk", "Pagoda", "Colosseum"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🏙️\nHarappa and Mohenjo-daro were cities of which ancient civilization?", correctAnswer: "Indus Valley", distractors: ["Maya", "Aztec", "Roman"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🧱\nIn which country is the Great Wall?", correctAnswer: "China", distractors: ["Japan", "India", "Egypt"], tier: .easy, grades: 3...5),
        BankQuestion(prompt: "📄\nWhich ancient civilization invented paper and silk?", correctAnswer: "China", distractors: ["Egypt", "Greece", "Rome"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🐫\nWhat were the ancient trade routes that linked China with the Mediterranean called?", correctAnswer: "Silk Road", distractors: ["Oregon Trail", "Route 66", "Appian Way"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "🏮\nWhich ancient Chinese teacher's ideas about respect and family are still studied today?", correctAnswer: "Confucius", distractors: ["Socrates", "Aristotle", "Julius Caesar"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🏺\nIn which country is the Terracotta Army of life-size clay soldiers?", correctAnswer: "China", distractors: ["Egypt", "Greece", "Mexico"], tier: .medium, grades: 6...7),

        // ── 6 · Ancient Greece ──
        BankQuestion(prompt: "🏅\nWhere did the Olympic Games begin long ago?", correctAnswer: "Ancient Greece", distractors: ["Ancient Egypt", "Ancient China", "Ancient Rome"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🗳️\nWhich ancient Greek city-state is known as the birthplace of democracy?", correctAnswer: "Athens", distractors: ["Sparta", "Rome", "Babylon"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "🛡️\nWhich Greek city-state was famous for training tough soldiers?", correctAnswer: "Sparta", distractors: ["Athens", "Rome", "Babylon"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "👑\nIn Greek mythology, who was the king of the gods?", correctAnswer: "Zeus", distractors: ["Poseidon", "Apollo", "Hermes"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "🏛️\nThe Parthenon was built to honor which Greek goddess?", correctAnswer: "Athena", distractors: ["Aphrodite", "Hera", "Artemis"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🎓\nWhich Greek philosopher was a teacher of Alexander the Great?", correctAnswer: "Aristotle", distractors: ["Socrates", "Homer", "Pythagoras"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "📖\nWhich ancient Greek poet is traditionally credited with the Iliad and the Odyssey?", correctAnswer: "Homer", distractors: ["Plato", "Aristotle", "Socrates"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🤫\nIn the Greek legend of Troy, how did Greek soldiers sneak into the city?", correctAnswer: "Inside a giant wooden horse", distractors: ["Through a secret tunnel", "Riding on elephants", "Flying on eagles"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🗡️\nAlexander the Great came from which kingdom north of Greece?", correctAnswer: "Macedonia", distractors: ["Egypt", "Persia", "Carthage"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🔤\nWhich ancient seafaring traders created the alphabet that the Greek alphabet was based on?", correctAnswer: "Phoenicians", distractors: ["Egyptians", "Vikings", "Aztecs"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🐚\nIn ancient times, which dye color was so costly that it became a symbol of royalty?", correctAnswer: "Purple", distractors: ["Gray", "Brown", "Beige"], tier: .medium, grades: 6...7),

        // ── 6 · Ancient Rome ──
        BankQuestion(prompt: "🏟️\nWhich ancient people built the Colosseum?", correctAnswer: "Romans", distractors: ["Egyptians", "Chinese", "Aztecs"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "💧\nWhich ancient empire was famous for building long roads and stone aqueducts to carry water to its cities?", correctAnswer: "Roman Empire", distractors: ["Mongol Empire", "Mali Empire", "Viking kingdoms"], tier: .hard, grades: 5...7),
        BankQuestion(prompt: "🗣️\nWhich language did people speak in ancient Rome?", correctAnswer: "Latin", distractors: ["Chinese", "Japanese", "Arabic"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "🏛️\nWho was the first emperor of Rome?", correctAnswer: "Augustus", distractors: ["Julius Caesar", "Nero", "Constantine"], tier: .hard, grades: 6...7),
        BankQuestion(prompt: "🍼\nAccording to legend, the founders of Rome were twins raised by a…", correctAnswer: "Wolf", distractors: ["Bear", "Lion", "Eagle"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "🌋\nWhich ancient Roman city was buried by the eruption of Mount Vesuvius?", correctAnswer: "Pompeii", distractors: ["Athens", "Alexandria", "Carthage"], tier: .medium, grades: 6...7),

        // ── 6–7 · The Americas before Columbus ──
        BankQuestion(prompt: "🌽\nWhich ancient civilization of Central America built stepped pyramids and made an advanced calendar?", correctAnswer: "Maya", distractors: ["Inca", "Vikings", "Romans"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "⛰️\nWhich civilization built Machu Picchu high in the Andes Mountains?", correctAnswer: "Inca", distractors: ["Maya", "Aztec", "Egyptians"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "🦅\nThe Aztec capital Tenochtitlan stood where which modern city is today?", correctAnswer: "Mexico City", distractors: ["Lima", "Havana", "Buenos Aires"], tier: .hard, grades: 7...7),

        // ── 7 · The Middle Ages ──
        BankQuestion(prompt: "🐴\nIn medieval Europe, soldiers in armor who fought on horseback were called…", correctAnswer: "Knights", distractors: ["Gladiators", "Pharaohs", "Senators"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🏰\nWhat was the water-filled ditch around a castle called?", correctAnswer: "Moat", distractors: ["Tower", "Dungeon", "Courtyard"], tier: .medium, grades: 4...7),
        BankQuestion(prompt: "🗝️\nThe medieval system where lords gave land to knights in exchange for loyalty and service is called…", correctAnswer: "Feudalism", distractors: ["Democracy", "Communism", "Capitalism"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🌾\nIn medieval Europe, poor farmers who were bound to work a lord's land were called…", correctAnswer: "Serfs", distractors: ["Knights", "Nobles", "Monks"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "📜\nWhat was the Black Death that swept through Europe in the 1300s?", correctAnswer: "A terrible plague", distractors: ["A long war", "A volcano eruption", "A great flood"], tier: .medium, grades: 7...8),
        BankQuestion(prompt: "✒️\nWhich English document from 1215 limited the power of the king?", correctAnswer: "Magna Carta", distractors: ["Bill of Rights", "Declaration of Independence", "Mayflower Compact"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "👑\nWhich king of the Franks was crowned emperor in the year 800?", correctAnswer: "Charlemagne", distractors: ["William the Conqueror", "King Arthur", "Richard the Lionheart"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "🏹\nIn 1066, William the Conqueror won the Battle of Hastings and became king of…", correctAnswer: "England", distractors: ["France", "Spain", "Scotland"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "🌬️\nWhich seafaring people from northern Europe sailed in longships?", correctAnswer: "Vikings", distractors: ["Egyptians", "Aztecs", "Romans"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "🐎\nWhich leader founded the Mongol Empire?", correctAnswer: "Genghis Khan", distractors: ["Kublai Khan", "Charlemagne", "Attila the Hun"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "🌉\nConstantinople, the capital of the Byzantine Empire, is known today as…", correctAnswer: "Istanbul", distractors: ["Athens", "Rome", "Cairo"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "📚\nThe House of Wisdom, a great center of learning during the Islamic Golden Age, was in which city?", correctAnswer: "Baghdad", distractors: ["Paris", "London", "Beijing"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "💰\nMansa Musa, one of the richest rulers in history, led which West African empire?", correctAnswer: "Mali", distractors: ["Egypt", "Rome", "Persia"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "⚜️\nWhich young French heroine led French troops during the Hundred Years' War?", correctAnswer: "Joan of Arc", distractors: ["Marie Curie", "Cleopatra", "Queen Elizabeth I"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "⚔️\nWhat were the trained warriors of old Japan called?", correctAnswer: "Samurai", distractors: ["Knights", "Vikings", "Gladiators"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "🎌\nIn old Japan, what was the title of the top military leader who ruled in the emperor's name?", correctAnswer: "Shogun", distractors: ["Pharaoh", "Czar", "Sultan"], tier: .hard, grades: 7...7),

        // ── 5–8 · Renaissance, science and the modern world ──
        BankQuestion(prompt: "🖨️\nWho built a printing press with movable type in Europe around 1440?", correctAnswer: "Johannes Gutenberg", distractors: ["Leonardo da Vinci", "Galileo Galilei", "William Shakespeare"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "🌻\nThe Renaissance, a time of new art and learning, began in what is now…", correctAnswer: "Italy", distractors: ["Japan", "Egypt", "Brazil"], tier: .medium, grades: 7...7),
        BankQuestion(prompt: "🎨\nWhich Renaissance artist painted the Mona Lisa?", correctAnswer: "Leonardo da Vinci", distractors: ["Michelangelo", "Vincent van Gogh", "Pablo Picasso"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🖌️\nWhich Renaissance artist painted the ceiling of the Sistine Chapel?", correctAnswer: "Michelangelo", distractors: ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "🎭\nWhich English writer wrote the play \"Romeo and Juliet\"?", correctAnswer: "William Shakespeare", distractors: ["Charles Dickens", "Mark Twain", "Homer"], tier: .medium, grades: 6...8),
        BankQuestion(prompt: "👑\nElizabeth I was a famous queen of…", correctAnswer: "England", distractors: ["France", "Spain", "Russia"], tier: .medium, grades: 6...7),
        BankQuestion(prompt: "☀️\nWhich astronomer's 1543 book argued that Earth moves around the Sun?", correctAnswer: "Nicolaus Copernicus", distractors: ["Ptolemy", "Aristotle", "Julius Caesar"], tier: .hard, grades: 7...7),
        BankQuestion(prompt: "🔭\nWhich Italian scientist used a telescope to study the Moon and planets in the early 1600s?", correctAnswer: "Galileo Galilei", distractors: ["Isaac Newton", "Christopher Columbus", "Thomas Edison"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🪐\nWhich scientist described the law of gravity in the 1680s?", correctAnswer: "Isaac Newton", distractors: ["Galileo Galilei", "Albert Einstein", "Thomas Edison"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🧪\nWho was the first woman to win a Nobel Prize?", correctAnswer: "Marie Curie", distractors: ["Florence Nightingale", "Amelia Earhart", "Clara Barton"], tier: .medium, grades: 6...8),
        BankQuestion(prompt: "💊\nWhich scientist discovered penicillin in 1928?", correctAnswer: "Alexander Fleming", distractors: ["Louis Pasteur", "Marie Curie", "Isaac Newton"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🔬\nWhich French scientist showed that heating drinks can kill the germs that spoil them?", correctAnswer: "Louis Pasteur", distractors: ["Isaac Newton", "Alexander Fleming", "Galileo Galilei"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🧠\nWhich scientist is famous for the theory of relativity?", correctAnswer: "Albert Einstein", distractors: ["Isaac Newton", "Thomas Edison", "Charles Darwin"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🏭\nIn which country did the Industrial Revolution begin?", correctAnswer: "Great Britain", distractors: ["Japan", "Brazil", "Egypt"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "⚙️\nWhich Scottish inventor greatly improved the steam engine?", correctAnswer: "James Watt", distractors: ["Henry Ford", "Thomas Edison", "Samuel Morse"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🔧\nKarl Benz of Germany built one of the first gasoline-powered…", correctAnswer: "Cars", distractors: ["Airplanes", "Rockets", "Ships"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "✨\nThe Lumière brothers of France were pioneers of…", correctAnswer: "Movies", distractors: ["Airplanes", "Telephones", "Light bulbs"], tier: .medium, grades: 5...7),
        BankQuestion(prompt: "🏗️\nWhich famous iron tower was built in Paris in 1889?", correctAnswer: "Eiffel Tower", distractors: ["Leaning Tower of Pisa", "Big Ben", "CN Tower"], tier: .medium, grades: 4...6),
        BankQuestion(prompt: "🌐\nIn which year did World War I begin?", correctAnswer: "1914", distractors: ["1900", "1939", "1861"], tier: .hard, grades: 7...8),
        BankQuestion(prompt: "🕊️\nIn which year did World War II end?", correctAnswer: "1945", distractors: ["1918", "1939", "1965"], tier: .hard, grades: 7...8),
    ]
}
