import Foundation

/// ⚽ עולם הכדורגל — the first PAID question pack (see QuestionPack). Ships with
/// the build; the cloud switch only turns it on. Facts are deliberately timeless
/// (rules, geography, history, arithmetic of results) — no current rosters that
/// go stale in a season. Grade-tagged like every bank (compiler-enforced).
enum QuestionBanksSoccer {
    static let soccer: [BankQuestion] = [
        // ── קַל · חֻקִּים וּמֻשָּׂגִים ──
        BankQuestion(prompt: "⚽\nכַּמָּה שַׂחְקָנִים שֶׁל כָּל קְבוּצָה נִמְצָאִים עַל הַמִּגְרָשׁ בְּבַת אַחַת?", correctAnswer: "11", distractors: ["9", "10", "12"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧤\nאֵיךְ קוֹרְאִים לַשַּׂחְקָן שֶׁמֻּתָּר לוֹ לִתְפֹּס אֶת הַכַּדּוּר בַּיָּדַיִם?", correctAnswer: "שׁוֹעֵר", distractors: ["חָלוּץ", "קַשָּׁר", "מָגֵן"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🥅\nאֵיךְ קוֹרְאִים לָזֶה כְּשֶׁהַכַּדּוּר נִכְנָס לַשַּׁעַר?", correctAnswer: "גּוֹל", distractors: ["קֶרֶן", "פֶּנְדֶּל", "פֶּסֶק זְמַן"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🙌\nבְּאֵיזֶה חֵלֶק גּוּף אָסוּר לְשַׂחְקָן שָׂדֶה לָגַעַת בַּכַּדּוּר?", correctAnswer: "בַּיָּדַיִם", distractors: ["בָּרַגְלַיִם", "בָּרֹאשׁ", "בֶּחָזֶה"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🟥\nאֵיזֶה צֶבַע כַּרְטִיס מוֹצִיא שַׂחְקָן מֵהַמִּשְׂחָק?", correctAnswer: "אָדֹם", distractors: ["צָהֹב", "יָרֹק", "כָּחֹל"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🟨\nמַה מְקַבֵּל שַׂחְקָן עַל עֲבֵרָה לֹא חֲמוּרָה — אַזְהָרָה?", correctAnswer: "כַּרְטִיס צָהֹב", distractors: ["כַּרְטִיס אָדֹם", "פֶּנְדֶּל", "שַׁעַר"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "📣\nמִי שׁוֹרֵק וּמַחְלִיט בַּמִּשְׂחָק?", correctAnswer: "הַשּׁוֹפֵט", distractors: ["הַמְּאַמֵּן", "הַשּׁוֹעֵר", "הַקַּפְּטֶן"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⏱️\nכַּמָּה מַחֲצִיּוֹת יֵשׁ בְּמִשְׂחַק כַּדּוּרֶגֶל?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "⏱️\nכַּמָּה דַּקּוֹת נִמְשֶׁכֶת מַחֲצִית אַחַת?", correctAnswer: "45", distractors: ["30", "60", "90"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "⏱️\nכַּמָּה דַּקּוֹת נִמְשָׁךְ מִשְׂחָק רָגִיל (בְּלִי תּוֹסֶפֶת זְמַן)?", correctAnswer: "90", distractors: ["60", "100", "120"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎯\nאֵיךְ קוֹרְאִים לִבְעִיטָה מִ־11 מֶטֶר, לְבַד מוּל הַשּׁוֹעֵר?", correctAnswer: "פֶּנְדֶּל", distractors: ["קֶרֶן", "בְּעִיטָה חָפְשִׁית", "זְרִיקַת חוּץ"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🤾\nהַכַּדּוּר יָצָא מֵהַקַּו הַצְּדָדִי. אֵיךְ מַחֲזִירִים אוֹתוֹ לַמִּשְׂחָק?", correctAnswer: "זְרִיקַת חוּץ", distractors: ["פֶּנְדֶּל", "בְּעִיטַת שַׁעַר", "כַּדּוּר שׁוֹפֵט"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🚩\nהַכַּדּוּר יָצָא מֵהַקַּו שֶׁל הַשַּׁעַר, אַחֲרֵי שֶׁנָּגַע בְּמָגֵן. מַה מְקַבֶּלֶת הַקְּבוּצָה הַתּוֹקֶפֶת?", correctAnswer: "קֶרֶן", distractors: ["פֶּנְדֶּל", "זְרִיקַת חוּץ", "שַׁעַר"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⚡\nאֵיךְ קוֹרְאִים לַשַּׂחְקָן שֶׁהַתַּפְקִיד שֶׁלּוֹ הוּא לְהַבְקִיעַ שְׁעָרִים?", correctAnswer: "חָלוּץ", distractors: ["שׁוֹעֵר", "מָגֵן", "שׁוֹפֵט"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🛡️\nאֵיךְ קוֹרְאִים לַשַּׂחְקָן שֶׁמֵּגֵן עַל הַשַּׁעַר שֶׁל הַקְּבוּצָה שֶׁלּוֹ?", correctAnswer: "מָגֵן", distractors: ["חָלוּץ", "שׁוֹפֵט", "מְאַמֵּן"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🏟️\nאֵיךְ קוֹרְאִים לְמִגְרָשׁ כַּדּוּרֶגֶל גָּדוֹל עִם קָהָל?", correctAnswer: "אִצְטַדְיוֹן", distractors: ["אוּלָם", "בְּרֵכָה", "גַּן"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🥅\nכַּמָּה שְׁעָרִים יֵשׁ עַל מִגְרַשׁ כַּדּוּרֶגֶל?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...3),
        BankQuestion(prompt: "🤝\nמַהִי \"מְסִירָה\"?", correctAnswer: "שַׂחְקָן מַעֲבִיר אֶת הַכַּדּוּר לְחָבֵר לַקְּבוּצָה", distractors: ["שַׂחְקָן בּוֹעֵט לַשַּׁעַר", "הַשּׁוֹפֵט שׁוֹרֵק", "הַקָּהָל מוֹחֵא כַּפַּיִם"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🤝\nהַתּוֹצָאָה בְּסוֹף הַמִּשְׂחָק הִיא 2:2. אֵיךְ נִגְמַר הַמִּשְׂחָק?", correctAnswer: "בְּתֵיקוּ", distractors: ["בְּנִצָּחוֹן", "בְּהֶפְסֵד", "בְּפֶנְדֶּל"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🧢\nאֵיךְ קוֹרְאִים לַשַּׂחְקָן שֶׁמַּנְהִיג אֶת הַקְּבוּצָה וְעוֹנֵד סֶרֶט עַל הַזְּרוֹעַ?", correctAnswer: "קַפְּטֶן", distractors: ["שׁוֹעֵר", "שׁוֹפֵט", "מְאַמֵּן"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔁\nאֵיךְ קוֹרְאִים לָזֶה כְּשֶׁשַּׂחְקָן יוֹצֵא וְשַׂחְקָן אַחֵר נִכְנָס בִּמְקוֹמוֹ?", correctAnswer: "חִלּוּף", distractors: ["פֶּנְדֶּל", "נִבְדָּל", "קֶרֶן"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🎯\nאֵיךְ קוֹרְאִים לִשְׁלוֹשָׁה שְׁעָרִים שֶׁל אוֹתוֹ שַׂחְקָן בְּמִשְׂחָק אֶחָד?", correctAnswer: "הַאט־טְרִיק", distractors: ["דֶּרְבִּי", "אוֹפְסַיְד", "פֶּנְדֶּל"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "😬\nשַׂחְקָן הִבְקִיעַ בְּטָעוּת לַשַּׁעַר שֶׁל הַקְּבוּצָה שֶׁלּוֹ. אֵיךְ קוֹרְאִים לָזֶה?", correctAnswer: "שַׁעַר עַצְמִי", distractors: ["הַאט־טְרִיק", "פֶּנְדֶּל", "נִבְדָּל"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🟨🟨\nשַׂחְקָן קִבֵּל כַּרְטִיס צָהֹב שֵׁנִי בְּאוֹתוֹ מִשְׂחָק. מַה קוֹרֶה?", correctAnswer: "הוּא מְקַבֵּל אָדֹם וְיוֹצֵא", distractors: ["הוּא מַמְשִׁיךְ לְשַׂחֵק", "הַקְּבוּצָה מְקַבֶּלֶת פֶּנְדֶּל", "הַמִּשְׂחָק נִפְסָק"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "📏\nמַה בְּעֵרֶךְ הָאֹרֶךְ שֶׁל מִגְרַשׁ כַּדּוּרֶגֶל?", correctAnswer: "כְּ־100 מֶטֶר", distractors: ["כְּ־30 מֶטֶר", "כְּ־10 מֶטֶר", "כְּ־1,000 מֶטֶר"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "📺\nמַה זֶה VAR?", correctAnswer: "שׁוֹפֵט וִידֵאוֹ שֶׁעוֹזֵר לַשּׁוֹפֵט בַּמִּגְרָשׁ", distractors: ["סוּג שֶׁל נַעֲלֵי כַּדּוּרֶגֶל", "שֵׁם שֶׁל אִצְטַדְיוֹן", "בְּעִיטָה מְיֻחֶדֶת"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⏱️\nמִשְׂחַק גָּבִיעַ נִגְמַר בְּתֵיקוּ. כַּמָּה זְמַן נִמְשֶׁכֶת הַהַאֲרָכָה?", correctAnswer: "30 דַּקּוֹת", distractors: ["10 דַּקּוֹת", "45 דַּקּוֹת", "90 דַּקּוֹת"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🎯\nגַּם אַחֲרֵי הַהַאֲרָכָה הַתּוֹצָאָה תֵּיקוּ. מָה מַכְרִיעַ אֶת הַמִּשְׂחָק?", correctAnswer: "בְּעִיטוֹת פֶּנְדֶּלִים", distractors: ["הַטָּלַת מַטְבֵּעַ", "עוֹד מִשְׂחָק מָחָר", "הַקְּבוּצָה עִם יוֹתֵר קְרָנוֹת"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🚫\nמַהוּ \"נִבְדָּל\" (אוֹפְסַיְד)?", correctAnswer: "תּוֹקֵף שֶׁעוֹמֵד קָרוֹב מִדַּי לַשַּׁעַר, מֵאֲחוֹרֵי הַמָּגֵן הָאַחֲרוֹן, כְּשֶׁמּוֹסְרִים לוֹ", distractors: ["כַּדּוּר שֶׁיָּצָא מֵהַמִּגְרָשׁ", "עֲבֵרָה בַּיָּדַיִם", "בְּעִיטָה חֲזָקָה מִדַּי"], tier: .hard, grades: 4...6),

        // ── קְבוּצוֹת וּמְקוֹמוֹת ──
        BankQuestion(prompt: "🇮🇱\nבְּאֵיזוֹ עִיר מְשַׂחֶקֶת מַכַּבִּי חֵיפָה?", correctAnswer: "חֵיפָה", distractors: ["תֵּל אָבִיב", "יְרוּשָׁלַיִם", "בְּאֵר שֶׁבַע"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🇮🇱\nבְּאֵיזוֹ עִיר מְשַׂחֶקֶת הַפּוֹעֵל בְּאֵר שֶׁבַע?", correctAnswer: "בְּאֵר שֶׁבַע", distractors: ["אֵילַת", "חֵיפָה", "נְתַנְיָה"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🏟️\nבְּאֵיזוֹ עִיר נִמְצָא אִצְטַדְיוֹן \"טֶדִּי\"?", correctAnswer: "יְרוּשָׁלַיִם", distractors: ["חֵיפָה", "תֵּל אָבִיב", "נְתַנְיָה"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏟️\nבְּאֵיזוֹ עִיר נִמְצָא אִצְטַדְיוֹן \"סַמִּי עוֹפֶר\"?", correctAnswer: "חֵיפָה", distractors: ["יְרוּשָׁלַיִם", "בְּאֵר שֶׁבַע", "פֶּתַח תִּקְוָה"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏟️\nבְּאֵיזוֹ עִיר נִמְצָא אִצְטַדְיוֹן \"בְּלוּמְפִילְד\"?", correctAnswer: "תֵּל אָבִיב", distractors: ["חֵיפָה", "יְרוּשָׁלַיִם", "רִאשׁוֹן לְצִיּוֹן"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇮🇱\nמַכַּבִּי תֵּל אָבִיב נֶגֶד הַפּוֹעֵל תֵּל אָבִיב — אֵיךְ קוֹרְאִים לְמִשְׂחָק בֵּין שְׁתֵּי קְבוּצוֹת מֵאוֹתָהּ עִיר?", correctAnswer: "דֶּרְבִּי", distractors: ["פֶּנְדֶּל", "מוֹנְדְּיָאל", "הַאט־טְרִיק"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nאֵיךְ קוֹרְאִים לַלִּיגָה הַבְּכִירָה בְּיִשְׂרָאֵל?", correctAnswer: "לִיגַת הָעָל", distractors: ["לִיגָה א׳", "פְּרֶמְיֶר לִיג", "לָה לִיגָה"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nאֵיךְ קוֹרְאִים לַגָּבִיעַ הַחָשׁוּב בְּיִשְׂרָאֵל, שֶׁבּוֹ מְשַׂחֲקוֹת קְבוּצוֹת מִכָּל הַלִּיגוֹת?", correctAnswer: "גְּבִיעַ הַמְּדִינָה", distractors: ["גְּבִיעַ הָעוֹלָם", "לִיגַת הָאַלּוּפוֹת", "גְּבִיעַ הַשָּׁלוֹם"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nלְאֵיזוֹ קְבוּצָה יֵשׁ הֲכִי הַרְבֵּה אַלִּיפֻיּוֹת בְּיִשְׂרָאֵל?", correctAnswer: "מַכַּבִּי תֵּל אָבִיב", distractors: ["הַפּוֹעֵל בְּאֵר שֶׁבַע", "בֵּיתָ\"ר יְרוּשָׁלַיִם", "בְּנֵי יְהוּדָה"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nכַּמָּה קְבוּצוֹת מְשַׂחֲקוֹת בְּלִיגַת הָעָל?", correctAnswer: "14", distractors: ["10", "16", "20"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇪🇸\nבְּאֵיזוֹ מְדִינָה מְשַׂחֶקֶת בַּרְצֶלוֹנָה?", correctAnswer: "סְפָרַד", distractors: ["אִיטַלְיָה", "צָרְפַת", "פּוֹרְטוּגָל"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🇪🇸\nבְּאֵיזוֹ עִיר מְשַׂחֶקֶת רֵיאָל מַדְרִיד?", correctAnswer: "מַדְרִיד", distractors: ["בַּרְצֶלוֹנָה", "לוֹנְדוֹן", "פָּרִיז"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏴󠁧󠁢󠁥󠁮󠁧󠁿\nבְּאֵיזוֹ מְדִינָה מְשַׂחֶקֶת מַנְצֶ'סְטֶר יוּנַיְטֶד?", correctAnswer: "אַנְגְּלִיָּה", distractors: ["גֶּרְמַנְיָה", "סְפָרַד", "הוֹלַנְד"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇩🇪\nבְּאֵיזוֹ מְדִינָה מְשַׂחֶקֶת בָּאיֶרְן מִינְכֶן?", correctAnswer: "גֶּרְמַנְיָה", distractors: ["אוֹסְטְרִיָּה", "אִיטַלְיָה", "בֶּלְגְּיָה"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇮🇹\nבְּאֵיזוֹ מְדִינָה מְשַׂחֶקֶת יוּבֶנְטוּס?", correctAnswer: "אִיטַלְיָה", distractors: ["סְפָרַד", "צָרְפַת", "יָוָן"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇫🇷\nבְּאֵיזוֹ עִיר מְשַׂחֶקֶת פָּרִיז סֶן זֶ'רְמֶן?", correctAnswer: "פָּרִיז", distractors: ["מַרְסֵי", "לוֹנְדוֹן", "רוֹמָא"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏆\nאֵיךְ קוֹרְאִים לַלִּיגָה הַבְּכִירָה בְּאַנְגְּלִיָּה?", correctAnswer: "פְּרֶמְיֶר לִיג", distractors: ["לָה לִיגָה", "סֶרְיֶה A", "בּוּנְדֶּסְלִיגָה"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nאֵיךְ קוֹרְאִים לַלִּיגָה הַבְּכִירָה בִּסְפָרַד?", correctAnswer: "לָה לִיגָה", distractors: ["פְּרֶמְיֶר לִיג", "סֶרְיֶה A", "לִיג 1"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "⭐\nלִיגַת הָאַלּוּפוֹת הִיא תַּחֲרוּת שֶׁל…", correctAnswer: "הַקְּבוּצוֹת הַטּוֹבוֹת בְּאֵירוֹפָּה", distractors: ["נִבְחָרוֹת שֶׁל מְדִינוֹת", "קְבוּצוֹת יְלָדִים", "קְבוּצוֹת מִיִּשְׂרָאֵל בִּלְבַד"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⭐\nאֵיזוֹ קְבוּצָה זָכְתָה בְּלִיגַת הָאַלּוּפוֹת הֲכִי הַרְבֵּה פְּעָמִים?", correctAnswer: "רֵיאָל מַדְרִיד", distractors: ["בַּרְצֶלוֹנָה", "לִיבֶרְפּוּל", "מִילָאן"], tier: .hard, grades: 4...6),

        // ── נִבְחָרוֹת, מוֹנְדְּיָאל וְשַׂחְקָנִים ──
        BankQuestion(prompt: "🇧🇷\nמַה צֶבַע הַחֻלְצָה הַמְּפֻרְסֶמֶת שֶׁל נִבְחֶרֶת בְּרָזִיל?", correctAnswer: "צָהֹב", distractors: ["אָדֹם", "כָּחֹל", "שָׁחֹר"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🇦🇷\nמַה צִבְעֵי הַחֻלְצָה שֶׁל נִבְחֶרֶת אַרְגֶּנְטִינָה?", correctAnswer: "תְּכֵלֶת וְלָבָן", distractors: ["אָדֹם וְשָׁחֹר", "יָרֹק וְצָהֹב", "כָּחֹל וְאָדֹם"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇦🇷\nבְּאֵיזוֹ מְדִינָה נוֹלַד לִיאוֹנֵל מֶסִי?", correctAnswer: "אַרְגֶּנְטִינָה", distractors: ["בְּרָזִיל", "סְפָרַד", "פּוֹרְטוּגָל"], tier: .easy, grades: 2...6),
        BankQuestion(prompt: "🇵🇹\nבְּאֵיזוֹ מְדִינָה נוֹלַד כְּרִיסְטְיָאנוֹ רוֹנַאלְדוֹ?", correctAnswer: "פּוֹרְטוּגָל", distractors: ["סְפָרַד", "בְּרָזִיל", "אִיטַלְיָה"], tier: .easy, grades: 2...6),
        BankQuestion(prompt: "👑\nמֵאֵיזוֹ מְדִינָה הָיָה פֶּלֶה, \"מֶלֶךְ הַכַּדּוּרֶגֶל\"?", correctAnswer: "בְּרָזִיל", distractors: ["אַרְגֶּנְטִינָה", "פּוֹרְטוּגָל", "מֶקְסִיקוֹ"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔟\nאֵיזֶה מִסְפָּר חֻלְצָה מְפֻרְסָם לוֹבְשִׁים בְּדֶרֶךְ כְּלָל הַשַּׂחְקָנִים הַיְּצִירָתִיִּים, כְּמוֹ מֶסִי וּפֶלֶה?", correctAnswer: "10", distractors: ["1", "5", "99"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nכָּל כַּמָּה שָׁנִים מִתְקַיֵּם הַמּוֹנְדְּיָאל?", correctAnswer: "4", distractors: ["2", "3", "5"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nמַהוּ הַמּוֹנְדְּיָאל?", correctAnswer: "אַלִּיפוּת הָעוֹלָם שֶׁל הַנִּבְחָרוֹת", distractors: ["לִיגָה שֶׁל קְבוּצוֹת מִסְּפָרַד", "מִשְׂחָק בֵּין שְׁתֵּי עָרִים", "תַּחֲרוּת לִילָדִים"], tier: .easy, grades: 2...5),
        BankQuestion(prompt: "🏆\nאֵיזוֹ מְדִינָה זָכְתָה בַּמּוֹנְדְּיָאל הֲכִי הַרְבֵּה פְּעָמִים?", correctAnswer: "בְּרָזִיל", distractors: ["גֶּרְמַנְיָה", "אַרְגֶּנְטִינָה", "אִיטַלְיָה"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nאֵיזוֹ מְדִינָה זָכְתָה בַּמּוֹנְדְּיָאל 2022?", correctAnswer: "אַרְגֶּנְטִינָה", distractors: ["צָרְפַת", "בְּרָזִיל", "גֶּרְמַנְיָה"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🏆\nאֵיזוֹ מְדִינָה זָכְתָה בַּמּוֹנְדְּיָאל 2018?", correctAnswer: "צָרְפַת", distractors: ["קְרוֹאַטְיָה", "בְּרָזִיל", "סְפָרַד"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nאֵיזוֹ מְדִינָה זָכְתָה בַּמּוֹנְדְּיָאל 2014, שֶׁנֶּעֱרַךְ בִּבְרָזִיל?", correctAnswer: "גֶּרְמַנְיָה", distractors: ["בְּרָזִיל", "אַרְגֶּנְטִינָה", "הוֹלַנְד"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🏆\nאֵיזוֹ מְדִינָה זָכְתָה בַּמּוֹנְדְּיָאל 2010?", correctAnswer: "סְפָרַד", distractors: ["הוֹלַנְד", "גֶּרְמַנְיָה", "אִיטַלְיָה"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥇\nאֵיזוֹ מְדִינָה זָכְתָה בַּמּוֹנְדְּיָאל הָרִאשׁוֹן, בִּשְׁנַת 1930?", correctAnswer: "אוּרוּגְוַאי", distractors: ["בְּרָזִיל", "אִיטַלְיָה", "אַנְגְּלִיָּה"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🇶🇦\nבְּאֵיזוֹ מְדִינָה נֶעֱרַךְ הַמּוֹנְדְּיָאל 2022?", correctAnswer: "קָטַאר", distractors: ["רוּסְיָה", "בְּרָזִיל", "יַפָּן"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🇮🇱\nבְּאֵיזוֹ שָׁנָה הִשְׁתַּתְּפָה נִבְחֶרֶת יִשְׂרָאֵל בַּמּוֹנְדְּיָאל — הַפַּעַם הַיְּחִידָה עַד הַיּוֹם?", correctAnswer: "1970", distractors: ["1950", "1990", "2010"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🥇\nמִי הִבְקִיעַ הֲכִי הַרְבֵּה שְׁעָרִים בְּכָל הַמּוֹנְדְּיָאלִים?", correctAnswer: "מִירוֹסְלַב קְלוֹזֶה", distractors: ["פֶּלֶה", "מֶסִי", "רוֹנַאלְדוֹ"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🏴󠁧󠁢󠁥󠁮󠁧󠁿\nבְּאֵיזוֹ מְדִינָה נִכְתְּבוּ לָרִאשׁוֹנָה חֻקֵּי הַכַּדּוּרֶגֶל הַמּוֹדֶרְנִי?", correctAnswer: "אַנְגְּלִיָּה", distractors: ["בְּרָזִיל", "אִיטַלְיָה", "יָוָן"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🌎\nבְּאֵיזוֹ יַבֶּשֶׁת נִמְצֵאת בְּרָזִיל?", correctAnswer: "דְּרוֹם אָמֶרִיקָה", distractors: ["אֵירוֹפָּה", "אַפְרִיקָה", "אַסְיָה"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nבְּאֵיזוֹ יַבֶּשֶׁת נִמְצֵאת גֶּרְמַנְיָה?", correctAnswer: "אֵירוֹפָּה", distractors: ["אַסְיָה", "דְּרוֹם אָמֶרִיקָה", "אוֹסְטְרַלְיָה"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🌍\nהַמּוֹנְדְּיָאל 2010 נֶעֱרַךְ בִּדְרוֹם אַפְרִיקָה. בְּאֵיזוֹ יַבֶּשֶׁת זֶה?", correctAnswer: "אַפְרִיקָה", distractors: ["אֵירוֹפָּה", "אַסְיָה", "אָמֶרִיקָה"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🇪🇺\nכָּל כַּמָּה שָׁנִים מִתְקַיֶּמֶת אַלִּיפוּת אֵירוֹפָּה (הַיּוּרוֹ)?", correctAnswer: "4", distractors: ["1", "2", "6"], tier: .hard, grades: 4...6),

        // ── חֶשְׁבּוֹן שֶׁל תּוֹצָאוֹת ──
        BankQuestion(prompt: "🔢\nמַכַּבִּי הִבְקִיעָה 3 שְׁעָרִים וְהַפּוֹעֵל 1. בְּכַמָּה שְׁעָרִים נִצְּחָה מַכַּבִּי?", correctAnswer: "2", distractors: ["1", "3", "4"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔢\nמִשְׂחָק נִגְמַר 4:2. כַּמָּה שְׁעָרִים הֻבְקְעוּ בְּסַךְ הַכֹּל?", correctAnswer: "6", distractors: ["2", "4", "8"], tier: .easy, grades: 2...4),
        BankQuestion(prompt: "🔢\nבַּמַּחֲצִית הַתּוֹצָאָה הָיְתָה 1:0, וּבַסִּיּוּם 3:1. כַּמָּה שְׁעָרִים הֻבְקְעוּ בַּמַּחֲצִית הַשְּׁנִיָּה?", correctAnswer: "3", distractors: ["2", "4", "1"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "🔢\nעַל נִצָּחוֹן מְקַבְּלִים 3 נְקֻדּוֹת וְעַל תֵּיקוּ נְקֻדָּה אַחַת. קְבוּצָה נִצְּחָה פַּעֲמַיִם וְסִיְּמָה פַּעַם אַחַת בְּתֵיקוּ. כַּמָּה נְקֻדּוֹת יֵשׁ לָהּ?", correctAnswer: "7", distractors: ["6", "5", "9"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔢\nעַל נִצָּחוֹן מְקַבְּלִים 3 נְקֻדּוֹת. קְבוּצָה נִצְּחָה 5 מִשְׂחָקִים וְהִפְסִידָה 2. כַּמָּה נְקֻדּוֹת יֵשׁ לָהּ?", correctAnswer: "15", distractors: ["7", "10", "21"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "🔢\nבְּמוֹנְדְּיָאל 2014 גֶּרְמַנְיָה נִצְּחָה אֶת בְּרָזִיל 7:1. בְּכַמָּה שְׁעָרִים?", correctAnswer: "6", distractors: ["7", "8", "5"], tier: .medium, grades: 3...6),
        BankQuestion(prompt: "⏱️\nהַמִּשְׂחָק הִתְחִיל בְּ־20:00. בְּאֵיזוֹ שָׁעָה בְּעֵרֶךְ הוּא נִגְמָר, אַחֲרֵי 90 דַּקּוֹת וְהַפְסָקָה שֶׁל 15 דַּקּוֹת?", correctAnswer: "21:45", distractors: ["21:30", "22:00", "21:00"], tier: .hard, grades: 4...6),
        BankQuestion(prompt: "🔢\nשַׂחְקָן הִבְקִיעַ 12 שְׁעָרִים בְּ־8 מִשְׂחָקִים. כַּמָּה שְׁעָרִים בְּמִשְׂחָק בְּמְמֻצָּע?", correctAnswer: "1.5", distractors: ["1", "2", "4"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🔢\nבְּלִיגָה 4 קְבוּצוֹת, וְכָל קְבוּצָה מְשַׂחֶקֶת נֶגֶד כָּל אַחַת מֵהָאֲחֵרוֹת פַּעַם אַחַת. כַּמָּה מִשְׂחָקִים יֵשׁ בְּסַךְ הַכֹּל?", correctAnswer: "6", distractors: ["4", "8", "12"], tier: .hard, grades: 5...6),
        BankQuestion(prompt: "🔢\nקְבוּצָה הִבְקִיעָה 2 שְׁעָרִים בְּכָל אֶחָד מִ־6 מִשְׂחָקִים. כַּמָּה שְׁעָרִים בְּסַךְ הַכֹּל?", correctAnswer: "12", distractors: ["8", "10", "14"], tier: .medium, grades: 3...5),
        BankQuestion(prompt: "⏱️\nהַשּׁוֹפֵט הוֹסִיף 4 דַּקּוֹת לַמַּחֲצִית הַשְּׁנִיָּה. כַּמָּה דַּקּוֹת נִמְשְׁכָה הַמַּחֲצִית?", correctAnswer: "49", distractors: ["45", "50", "94"], tier: .medium, grades: 3...5),
    ]
}
