import Foundation

/// Extra questions authored + adversarially verified via the expand-question-banks
/// workflow (nikud + correctness reviewed). Appended to the live pools in
/// `QuestionBanks.bank(for:)`.
enum QuestionBanksWorkflow {
    static let english: [BankQuestion] = [
        BankQuestion(prompt: "🐮\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "cow", distractors: ["goat", "sheep", "pig"]),
        BankQuestion(prompt: "🐷\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "pig", distractors: ["cow", "dog", "sheep"]),
        BankQuestion(prompt: "🐴\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "horse", distractors: ["donkey", "cow", "goat"]),
        BankQuestion(prompt: "🐑\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "sheep", distractors: ["goat", "cow", "pig"]),
        BankQuestion(prompt: "🐔\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "chicken", distractors: ["duck", "bird", "cow"]),
        BankQuestion(prompt: "🦆\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "duck", distractors: ["chicken", "bird", "fish"]),
        BankQuestion(prompt: "🍌\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "banana", distractors: ["apple", "lemon", "orange"]),
        BankQuestion(prompt: "🥚\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "egg", distractors: ["milk", "bread", "cheese"]),
        BankQuestion(prompt: "🍪\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "cookie", distractors: ["cake", "candy", "bread"]),
        BankQuestion(prompt: "🍦\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "ice cream", distractors: ["cake", "candy", "milk"]),
        BankQuestion(prompt: "🟤\nמַה הַצֶּבַע בְּאַנְגְּלִית?", correctAnswer: "brown", distractors: ["black", "gray", "orange"]),
        BankQuestion(prompt: "🩷\nמַה הַצֶּבַע בְּאַנְגְּלִית?", correctAnswer: "pink", distractors: ["red", "purple", "orange"]),
        BankQuestion(prompt: "🦶\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "foot", distractors: ["leg", "hand", "arm"]),
        BankQuestion(prompt: "💪\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "arm", distractors: ["leg", "hand", "foot"]),
        BankQuestion(prompt: "🦷\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "tooth", distractors: ["nose", "mouth", "ear"]),
        BankQuestion(prompt: "👶\nאֵיךְ אוֹמְרִים 'תִּינוֹק' בְּאַנְגְּלִית?", correctAnswer: "baby", distractors: ["boy", "girl", "man"]),
        BankQuestion(prompt: "6\nאֵיךְ אוֹמְרִים אֶת הַמִּסְפָּר בְּאַנְגְּלִית?", correctAnswer: "six", distractors: ["seven", "sixteen", "sixty"]),
        BankQuestion(prompt: "7\nאֵיךְ אוֹמְרִים אֶת הַמִּסְפָּר בְּאַנְגְּלִית?", correctAnswer: "seven", distractors: ["six", "seventy", "eleven"]),
        BankQuestion(prompt: "8\nאֵיךְ אוֹמְרִים אֶת הַמִּסְפָּר בְּאַנְגְּלִית?", correctAnswer: "eight", distractors: ["nine", "eighteen", "eighty"]),
        BankQuestion(prompt: "9\nאֵיךְ אוֹמְרִים אֶת הַמִּסְפָּר בְּאַנְגְּלִית?", correctAnswer: "nine", distractors: ["eight", "ten", "ninety"]),
        BankQuestion(prompt: "🎒\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "bag", distractors: ["book", "box", "desk"]),
        BankQuestion(prompt: "✂️\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "scissors", distractors: ["pencil", "ruler", "glue"]),
        BankQuestion(prompt: "🏔️\nאֵיךְ אוֹמְרִים 'הַר' בְּאַנְגְּלִית?", correctAnswer: "mountain", distractors: ["river", "sea", "hill"]),
        BankQuestion(prompt: "🌊\nאֵיךְ אוֹמְרִים 'יָם' בְּאַנְגְּלִית?", correctAnswer: "sea", distractors: ["lake", "river", "rain"]),
        BankQuestion(prompt: "🍃\nאֵיךְ אוֹמְרִים 'עָלֶה' בְּאַנְגְּלִית?", correctAnswer: "leaf", distractors: ["tree", "grass", "flower"]),
        BankQuestion(prompt: "🚶\nאֵיךְ אוֹמְרִים 'לָלֶכֶת' בְּאַנְגְּלִית?", correctAnswer: "walk", distractors: ["run", "jump", "sit"]),
        BankQuestion(prompt: "🥤\nאֵיךְ אוֹמְרִים 'לִשְׁתּוֹת' בְּאַנְגְּלִית?", correctAnswer: "drink", distractors: ["eat", "cook", "wash"]),
        BankQuestion(prompt: "👟\nאֵיךְ אוֹמְרִים 'נַעַל' בְּאַנְגְּלִית?", correctAnswer: "shoe", distractors: ["hat", "shirt", "sock"]),
        BankQuestion(prompt: "🧢\nאֵיךְ אוֹמְרִים 'כּוֹבַע' בְּאַנְגְּלִית?", correctAnswer: "hat", distractors: ["shoe", "shirt", "coat"]),
    ]

    static let hebrew: [BankQuestion] = [
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'אָרֹךְ'?", correctAnswer: "קָצָר", distractors: ["צָר", "כָּבֵד", "גָּבוֹהַּ"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'נָקִי'?", correctAnswer: "מְלֻכְלָךְ", distractors: ["יָבֵשׁ", "רָטֹב", "חָדָשׁ"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'לְמַעְלָה'?", correctAnswer: "לְמַטָּה", distractors: ["הַצִּדָּה", "קָדִימָה", "אָחוֹרָה"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'מָתוֹק'?", correctAnswer: "מַר", distractors: ["חַם", "טָעִים", "קַר"]),
        BankQuestion(prompt: "מָה הָרַבִּים שֶׁל 'כֶּלֶב'?", correctAnswer: "כְּלָבִים", distractors: ["כְּלָבוֹת", "כֶּלֶבִים", "כְּלָבַיִם"]),
        BankQuestion(prompt: "מָה הָרַבִּים שֶׁל 'פֶּרַח'?", correctAnswer: "פְּרָחִים", distractors: ["פְּרָחוֹת", "פֶּרַחִים", "פְּרָחַיִם"]),
        BankQuestion(prompt: "מָה הָרַבִּים שֶׁל 'יַלְדָּה'?", correctAnswer: "יְלָדוֹת", distractors: ["יְלָדִים", "יַלְדּוֹת", "יַלְדָּיִם"]),
        BankQuestion(prompt: "מָה הָרַבִּים שֶׁל 'עֵץ'?", correctAnswer: "עֵצִים", distractors: ["עֵצוֹת", "עֲצָיִם", "עֵצַיִם"]),
        BankQuestion(prompt: "אֵיזוֹ מִלָּה הִיא יֶרֶק?", correctAnswer: "מְלָפְפוֹן", distractors: ["תַּפּוּחַ", "כִּסֵּא", "אַרְנָב"]),
        BankQuestion(prompt: "אֵיזוֹ מִלָּה הִיא רָהִיט?", correctAnswer: "אֲרוֹן", distractors: ["בָּנָנָה", "חָתוּל", "כָּחֹל"]),
        BankQuestion(prompt: "אֵיזוֹ מִלָּה הִיא צֶבַע?", correctAnswer: "יָרֹק", distractors: ["שֻׁלְחָן", "תַּפּוּז", "סוּס"]),
        BankQuestion(prompt: "אֵיזוֹ מִלָּה הִיא בַּעַל חַיִּים?", correctAnswer: "צִפּוֹר", distractors: ["מִטָּה", "אֲגָס", "וָרֹד"]),
        BankQuestion(prompt: "אֵיזֶה קוֹל מַשְׁמִיעַ הַתַּרְנְגוֹל? 🐓", correctAnswer: "קוּקוּרִיקוּ", distractors: ["מוּ", "הַב הַב", "מְיָאוּ"]),
        BankQuestion(prompt: "אֵיזֶה קוֹל מַשְׁמִיעָה הַכִּבְשָׂה? 🐑", correctAnswer: "מֶה", distractors: ["מוּ", "מְיָאוּ", "קְוָואק"]),
        BankQuestion(prompt: "אֵיזֶה קוֹל מַשְׁמִיעַ הַחֲמוֹר? 🫏", correctAnswer: "אִי-הָא", distractors: ["הַב הַב", "צִיּוּץ", "מוּ"]),
        BankQuestion(prompt: "אֵיזֶה קוֹל מַשְׁמִיעַ הַבַּרְוָז? 🦆", correctAnswer: "קְוָואק", distractors: ["מֶה", "קוּקוּרִיקוּ", "הַב הַב"]),
        BankQuestion(prompt: "מָה מִתְחָרֵז עִם 'דָּג'?", correctAnswer: "חַג", distractors: ["סוּס", "כַּדּוּר", "פֶּרַח"]),
        BankQuestion(prompt: "מָה מִתְחָרֵז עִם 'גָּמָל'?", correctAnswer: "נָמָל", distractors: ["סוּס", "פִּיל", "צָב"]),
        BankQuestion(prompt: "בְּאֵיזוֹ אוֹת מַתְחִילָה הַמִּלָּה 'שֻׁלְחָן'? 🪑", correctAnswer: "שׁ", distractors: ["ס", "צ", "ל"]),
        BankQuestion(prompt: "בְּאֵיזוֹ אוֹת מַתְחִילָה הַמִּלָּה 'גֶּזֶר'? 🥕", correctAnswer: "ג", distractors: ["ז", "ר", "ק"]),
        BankQuestion(prompt: "בְּאֵיזוֹ אוֹת מַתְחִילָה הַמִּלָּה 'עֲנָנִים'? ☁️", correctAnswer: "ע", distractors: ["א", "ה", "נ"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'בַּחֹרֶף יוֹרֵד...'", correctAnswer: "גֶּשֶׁם", distractors: ["חוֹל", "שֶׁמֶשׁ", "אָבָק"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'הַצִּפּוֹר עָפָה בַּ...'", correctAnswer: "שָׁמַיִם", distractors: ["מַיִם", "אֲדָמָה", "אָרוֹן"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'אֲנִי יָשֵׁן בַּלַּיְלָה עַל הַ...'", correctAnswer: "מִטָּה", distractors: ["עֵץ", "כְּבִישׁ", "גַּג"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'הַשֶּׁמֶשׁ זוֹרַחַת בַּ...'", correctAnswer: "בֹּקֶר", distractors: ["לַיְלָה", "אָרוֹן", "כּוֹס"]),
    ]

    static let logic: [BankQuestion] = [
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n3, 6, 9, ?", correctAnswer: "12", distractors: ["10", "11", "15"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n20, 18, 16, ?", correctAnswer: "14", distractors: ["15", "12", "17"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n🌟⬛🌟⬛🌟?", correctAnswer: "⬛", distractors: ["🌟", "🔵", "🔺"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n🍓🍋🍓🍋🍓?", correctAnswer: "🍋", distractors: ["🍓", "🍇", "🍊"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n☀️🌙☀️🌙☀️?", correctAnswer: "🌙", distractors: ["☀️", "⭐", "☁️"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n🐘🦒🐘🦒🐘?", correctAnswer: "🦒", distractors: ["🐘", "🦓", "🐅"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n4, 8, 12, ?", correctAnswer: "16", distractors: ["14", "18", "20"]),
        BankQuestion(prompt: "מָה הַצּוּרָה הַבָּאָה?\n⬛⬜⬛⬜⬛?", correctAnswer: "⬜", distractors: ["⬛", "🔺", "🔵"]),
        BankQuestion(prompt: "מִי לֹא שַׁיָּךְ?", correctAnswer: "🐟", distractors: ["🐦", "🦅", "🦜"]),
        BankQuestion(prompt: "מַה זֶה לֹא רָהִיט?", correctAnswer: "מַסּוֹק", distractors: ["כִּסֵּא", "אֲרוֹן", "מִטָּה"]),
        BankQuestion(prompt: "מַה זֶה לֹא כְּלִי נְגִינָה?", correctAnswer: "מַחְבֵּת", distractors: ["חָלִיל", "תֹּף", "פְּסַנְתֵּר"]),
        BankQuestion(prompt: "כַּמָּה אָזְנַיִם יֵשׁ לִשְׁנֵי יְלָדִים?", correctAnswer: "4", distractors: ["2", "3", "6"]),
        BankQuestion(prompt: "כַּמָּה אֶצְבָּעוֹת יֵשׁ בִּשְׁתֵּי יָדַיִם?", correctAnswer: "10", distractors: ["5", "8", "12"]),
        BankQuestion(prompt: "אִם 🐞=3, אָז 🐞+🐞=?", correctAnswer: "6", distractors: ["5", "4", "9"]),
        BankQuestion(prompt: "אִם בַּקֻּפְסָה 2 כַּדּוּרִים וְהוֹסַפְנוּ עוֹד 2, כַּמָּה יֵשׁ?", correctAnswer: "4", distractors: ["3", "2", "5"]),
        BankQuestion(prompt: "אִם הַיּוֹם רְבִיעִי, מָה יִהְיֶה מָחָר?", correctAnswer: "חֲמִישִׁי", distractors: ["שְׁלִישִׁי", "שִׁשִּׁי", "שֵׁנִי"]),
        BankQuestion(prompt: "אֵיזֶה יוֹם בָּא לִפְנֵי יוֹם רִאשׁוֹן?", correctAnswer: "שַׁבָּת", distractors: ["שֵׁנִי", "שִׁשִּׁי", "שְׁלִישִׁי"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\nד, ה, ו, ?", correctAnswer: "ז", distractors: ["ח", "ה", "ג"]),
        BankQuestion(prompt: "אֵיזוֹ אוֹת בָּאָה לִפְנֵי כ?", correctAnswer: "י", distractors: ["ל", "מ", "ט"]),
        BankQuestion(prompt: "מַה בָּא אַחֲרֵי הַמִּסְפָּר 14?", correctAnswer: "15", distractors: ["13", "16", "20"]),
        BankQuestion(prompt: "מַה בָּא לִפְנֵי הַמִּסְפָּר 10?", correctAnswer: "9", distractors: ["11", "8", "12"]),
        BankQuestion(prompt: "מַה אָרֹךְ יוֹתֵר?", correctAnswer: "נָחָשׁ", distractors: ["נְמָלָה", "זְבוּב", "דְּבוֹרָה"]),
        BankQuestion(prompt: "מַה רָחָב יוֹתֵר?", correctAnswer: "אוֹטוֹבּוּס", distractors: ["עִפָּרוֹן", "קַשׁ", "חוּט"]),
        BankQuestion(prompt: "מָה כָּבֵד יוֹתֵר?", correctAnswer: "אֶבֶן", distractors: ["נוֹצָה", "עָלֶה", "בָּלוֹן"]),
        BankQuestion(prompt: "אִם בַּצַּלַּחַת 6 עוּגִיּוֹת וְאָכַלְתִּי 2, כַּמָּה נִשְׁאֲרוּ?", correctAnswer: "4", distractors: ["8", "5", "3"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n🟦🟥🟨🟦🟥?", correctAnswer: "🟨", distractors: ["🟦", "🟥", "🟩"]),
        BankQuestion(prompt: "מַה זֶה לֹא צוּרָה?", correctAnswer: "שֶׁמֶשׁ", distractors: ["עִגּוּל", "רִבּוּעַ", "מְשֻׁלָּשׁ"]),
    ]

    static let science: [BankQuestion] = [
        BankQuestion(prompt: "🐸\nאֵיךְ נִקְרָא הַתִּינוֹק שֶׁל הַצְּפַרְדֵּעַ?", correctAnswer: "רֹאשָׁן", distractors: ["גּוּר", "אֶפְרוֹחַ", "סְיָח"]),
        BankQuestion(prompt: "🐔\nמֵאַיִן בּוֹקְעִים הָאֶפְרוֹחִים?", correctAnswer: "מֵהַבֵּיצָה", distractors: ["מֵהָאֲדָמָה", "מֵהֶעָנָן", "מֵהַמַּיִם"]),
        BankQuestion(prompt: "🐪\nמָה הַגַּמָּל אוֹגֵר בַּדַּבֶּשֶׁת?", correctAnswer: "שֻׁמָּן", distractors: ["מַיִם", "חוֹל", "אֲוִיר"]),
        BankQuestion(prompt: "🦉\nמָתַי הַיַּנְשׁוּף עֵר בְּעִקָּר?", correctAnswer: "בַּלַּיְלָה", distractors: ["בַּצָּהֳרַיִם", "בַּבֹּקֶר", "אַף פַּעַם"]),
        BankQuestion(prompt: "🐻\nמָה דֻּבִּים עוֹשִׂים בַּחֹרֶף הַקַּר?", correctAnswer: "יְשֵׁנִים שֵׁנַת חֹרֶף", distractors: ["שׂוֹחִים בַּיָּם", "טָסִים דָּרוֹמָה", "מִשְׁתַּזְּפִים"]),
        BankQuestion(prompt: "🦷\nאֵיזֶה אֵיבָר עוֹזֵר לָנוּ לִלְעֹס אֹכֶל?", correctAnswer: "הַשִּׁנַּיִם", distractors: ["הָאָזְנַיִם", "הַבִּרְכַּיִם", "הַצִּפָּרְנַיִם"]),
        BankQuestion(prompt: "🩸\nאֵיזֶה צֶבַע הַדָּם שֶׁלָּנוּ?", correctAnswer: "אָדֹם", distractors: ["כָּחֹל", "יָרֹק", "צָהֹב"]),
        BankQuestion(prompt: "👃\nבְּאֵיזֶה אֵיבָר אֲנַחְנוּ מְרִיחִים?", correctAnswer: "בָּאַף", distractors: ["בָּעֵינַיִם", "בָּאָזְנַיִם", "בַּיָּדַיִם"]),
        BankQuestion(prompt: "👅\nבְּאֵיזֶה אֵיבָר אֲנַחְנוּ טוֹעֲמִים?", correctAnswer: "בַּלָּשׁוֹן", distractors: ["בָּאַף", "בָּעֵינַיִם", "בָּאָזְנַיִם"]),
        BankQuestion(prompt: "💤\nמָתַי הַגּוּף שֶׁלָּנוּ נָח וְצוֹבֵר כֹּחַ?", correctAnswer: "כְּשֶׁאֲנַחְנוּ יְשֵׁנִים", distractors: ["כְּשֶׁאֲנַחְנוּ רָצִים", "כְּשֶׁאֲנַחְנוּ אוֹכְלִים", "כְּשֶׁאֲנַחְנוּ צוֹחֲקִים"]),
        BankQuestion(prompt: "🌙\nמָה מֵאִיר אֶת הַשָּׁמַיִם בַּלַּיְלָה?", correctAnswer: "הַיָּרֵחַ", distractors: ["הַשֶּׁמֶשׁ", "פְּרָחִים", "עֲנָנֵי גֶּשֶׁם"]),
        BankQuestion(prompt: "🌍\nמָה צוּרַת כַּדּוּר הָאָרֶץ?", correctAnswer: "עָגֹל כְּמוֹ כַּדּוּר", distractors: ["שָׁטוּחַ", "מְרֻבָּע", "מְשֻׁלָּשׁ"]),
        BankQuestion(prompt: "☀️\nמָתַי הַשֶּׁמֶשׁ זוֹרַחַת?", correctAnswer: "בַּיּוֹם", distractors: ["בַּלַּיְלָה", "רַק בַּחֹרֶף", "אַף פַּעַם"]),
        BankQuestion(prompt: "⭐\nמָתַי רוֹאִים אֶת הַכּוֹכָבִים?", correctAnswer: "בַּלַּיְלָה", distractors: ["בַּצָּהֳרַיִם", "בַּבֹּקֶר", "כְּשֶׁיֵּשׁ שֶׁמֶשׁ"]),
        BankQuestion(prompt: "🚀\nאֵיךְ קוֹרְאִים לְמִי שֶׁטָּס לֶחָלָל?", correctAnswer: "אַסְטְרוֹנָאוּט", distractors: ["טַיָּס", "צוֹלֵל", "נֶהָג"]),
        BankQuestion(prompt: "⛈️\nמָה מוֹפִיעַ בַּשָּׁמַיִם רֶגַע לִפְנֵי הָרַעַם?", correctAnswer: "בָּרָק", distractors: ["קֶשֶׁת", "שֶׁלֶג", "יָרֵחַ"]),
        BankQuestion(prompt: "🌧️\nמָה נוֹפֵל מֵהֶעָנָן כְּשֶׁיּוֹרֵד גֶּשֶׁם?", correctAnswer: "טִיפּוֹת מַיִם", distractors: ["חוֹל", "עָלִים", "אֲבָנִים"]),
        BankQuestion(prompt: "⛄\nמָה צָרִיךְ לִהְיוֹת בַּחוּץ כְּדֵי לִבְנוֹת אִישׁ שֶׁלֶג?", correctAnswer: "קַר וְיֵשׁ שֶׁלֶג", distractors: ["חַם מְאוֹד", "יוֹרֵד גֶּשֶׁם", "נוֹשֶׁבֶת רוּחַ חַמָּה"]),
        BankQuestion(prompt: "🌬️\nמָה מֵנִיעַ אֶת כַּנְפֵי טַחֲנַת הָרוּחַ?", correctAnswer: "הָרוּחַ", distractors: ["הַגֶּשֶׁם", "הַשֶּׁלֶג", "הַשֶּׁמֶשׁ"]),
        BankQuestion(prompt: "🌡️\nבְּאֵיזוֹ עוֹנָה הֲכִי חַם בְּיִשְׂרָאֵל?", correctAnswer: "בַּקַּיִץ", distractors: ["בַּחֹרֶף", "בַּסְּתָו", "בָּאָבִיב"]),
        BankQuestion(prompt: "🌼\nאֵיזֶה חֵלֶק בַּצֶּמַח הֲכִי צִבְעוֹנִי וְיָפֶה?", correctAnswer: "הַפֶּרַח", distractors: ["הַשֹּׁרֶשׁ", "הַגֶּזַע", "הָאֲדָמָה"]),
        BankQuestion(prompt: "🍎\nמֵאֵיזֶה חֵלֶק שֶׁל הָעֵץ קוֹטְפִים תַּפּוּחַ?", correctAnswer: "מֵהֶעָנָף", distractors: ["מֵהַשֹּׁרֶשׁ", "מֵהָאֲדָמָה", "מֵהַגֶּזַע"]),
        BankQuestion(prompt: "🌻\nלְאֵיזֶה כִּוּוּן פּוֹנֶה פֶּרַח הַחַמָּנִית?", correctAnswer: "לַשֶּׁמֶשׁ", distractors: ["לָאֲדָמָה", "לַיָּרֵחַ", "לַמַּיִם"]),
        BankQuestion(prompt: "🌳\nמָה גָּדֵל מִתּוֹךְ זֶרַע קָטָן שֶׁשּׁוֹתְלִים?", correctAnswer: "צֶמַח", distractors: ["אֶבֶן", "עָנָן", "דָּג"]),
        BankQuestion(prompt: "💧\nמָה אֲנַחְנוּ עוֹשִׂים בַּמַּיִם כְּדֵי לְהִתְנַקּוֹת?", correctAnswer: "מִתְרַחֲצִים", distractors: ["יְשֵׁנִים", "צוֹבְעִים", "אוֹכְלִים"]),
        BankQuestion(prompt: "🚰\nמֵאַיִן יוֹצְאִים מַיִם לִשְׁתִיָּה בַּבַּיִת?", correctAnswer: "מֵהַבֶּרֶז", distractors: ["מֵהַחַלּוֹן", "מֵהַמְּנוֹרָה", "מֵהַטֶּלֶוִיזְיָה"]),
        BankQuestion(prompt: "🐟\nאֵיזֶה אֵיבָר עוֹזֵר לַדָּג לִנְשֹׁם בַּמַּיִם?", correctAnswer: "הַזִּימִים", distractors: ["הָרֵאוֹת", "הָאַף", "הָאָזְנַיִם"]),
        BankQuestion(prompt: "🦆\nמָה הַבַּרְוָוז עוֹשֶׂה הֲכִי טוֹב?", correctAnswer: "שׂוֹחֶה בַּמַּיִם", distractors: ["מְטַפֵּס עַל עֵצִים", "חוֹפֵר מִנְהָרוֹת", "טוֹוֶה קוּרִים"]),
        BankQuestion(prompt: "🌊\nאֵיךְ הַיָּם טוֹעֵם?", correctAnswer: "מָלוּחַ", distractors: ["מָתוֹק", "חָמוּץ", "חָרִיף"]),
        BankQuestion(prompt: "☁️\nמִמָּה עֲשׂוּיִים הָעֲנָנִים?", correctAnswer: "מִטִּיפּוֹת מַיִם זְעִירוֹת", distractors: ["מִצֶּמֶר רַךְ", "מֵעָשָׁן", "מֵחוֹל"]),
        BankQuestion(prompt: "🐜\nאֵיךְ נְמָלִים חַיּוֹת?", correctAnswer: "בְּקָבוּצָה גְּדוֹלָה", distractors: ["לְבַד תָּמִיד", "בְּתוֹךְ הַיָּם", "עַל הֶעָנָן"]),
        BankQuestion(prompt: "🦋\nכַּמָּה כְּנָפַיִם יֵשׁ לְפַרְפָּר?", correctAnswer: "4", distractors: ["2", "6", "8"]),
        BankQuestion(prompt: "🐢\nמָה הַצָּב נוֹשֵׂא תָּמִיד עַל גַּבּוֹ?", correctAnswer: "שִׁרְיוֹן", distractors: ["כְּנָפַיִם", "קוֹצִים", "פַּרְוָה"]),
        BankQuestion(prompt: "🌈\nמָתַי לְרֹב מוֹפִיעָה קֶשֶׁת בַּשָּׁמַיִם?", correctAnswer: "אַחֲרֵי הַגֶּשֶׁם", distractors: ["בָּעֶרֶב", "בַּשֶּׁלֶג", "בְּלֵילוֹת חֲשׁוּכִים"]),
        BankQuestion(prompt: "🌙\nמָה רוֹאִים בַּשָּׁמַיִם בְּלֵילוֹת בְּהִירִים?", correctAnswer: "יָרֵחַ וְכוֹכָבִים", distractors: ["שֶׁמֶשׁ וְקֶשֶׁת", "עֲנָנֵי גֶּשֶׁם", "פְּרָחִים"]),
    ]

    static let history: [BankQuestion] = [
        BankQuestion(prompt: "🍯🍎\nבְּאֵיזֶה חַג טוֹבְלִים תַּפּוּחַ בִּדְבַשׁ?", correctAnswer: "רֹאשׁ הַשָּׁנָה", distractors: ["חֲנֻכָּה", "פּוּרִים", "שָׁבוּעוֹת"]),
        BankQuestion(prompt: "🛖\nבְּאֵיזֶה חַג יוֹשְׁבִים בְּסֻכָּה?", correctAnswer: "סֻכּוֹת", distractors: ["פֶּסַח", "חֲנֻכָּה", "פּוּרִים"]),
        BankQuestion(prompt: "🥛🧀\nבְּאֵיזֶה חַג נָהוּג לֶאֱכֹל מַאַכְלֵי חָלָב?", correctAnswer: "שָׁבוּעוֹת", distractors: ["פֶּסַח", "סֻכּוֹת", "פּוּרִים"]),
        BankQuestion(prompt: "🎁\nאֵיךְ קוֹרְאִים לַמִּשְׁלוֹחַ שֶׁל מַתָּנוֹת אֹכֶל בְּפוּרִים?", correctAnswer: "מִשְׁלוֹחַ מָנוֹת", distractors: ["אֲפִיקוֹמָן", "סְבִיבוֹן", "מַצָּה"]),
        BankQuestion(prompt: "🥔\nאֵיזֶה מַאֲכָל מְטֻגָּן נָהוּג לֶאֱכֹל בַּחֲנֻכָּה?", correctAnswer: "לְבִיבוֹת", distractors: ["מַצָּה", "חַלָּה", "תַּפּוּחַ בִּדְבַשׁ"]),
        BankQuestion(prompt: "🍩\nאֵיזֶה מַאֲכָל מָתוֹק נָהוּג לֶאֱכֹל בַּחֲנֻכָּה?", correctAnswer: "סֻפְגָּנִיָּה", distractors: ["עוּגַת גֶּזֶר", "מַצָּה", "חַלָּה"]),
        BankQuestion(prompt: "🔄\nאֵיךְ קוֹרְאִים לַצַּעֲצוּעַ הַמִּסְתּוֹבֵב שֶׁל חֲנֻכָּה?", correctAnswer: "סְבִיבוֹן", distractors: ["שׁוֹפָר", "רַעֲשָׁן", "חֲלִילִית"]),
        BankQuestion(prompt: "📣\nבְּאֵיזֶה חַג מְרַעֲשִׁים בְּרַעֲשָׁן?", correctAnswer: "פּוּרִים", distractors: ["פֶּסַח", "סֻכּוֹת", "ט״וּ בִּשְׁבָט"]),
        BankQuestion(prompt: "🍇\nבְּאֵיזֶה חַג נָהוּג לֶאֱכֹל פֵּרוֹת יְבֵשִׁים?", correctAnswer: "ט״וּ בִּשְׁבָט", distractors: ["חֲנֻכָּה", "פּוּרִים", "יוֹם כִּפּוּר"]),
        BankQuestion(prompt: "📖\nאֵיךְ קוֹרְאִים לַסֵּפֶר שֶׁקּוֹרְאִים בּוֹ בְּלֵיל פֶּסַח?", correctAnswer: "הַגָּדָה", distractors: ["מְגִלָּה", "סִדּוּר", "חֻמָּשׁ"]),
        BankQuestion(prompt: "🐍\nאֶת מָה הָפַךְ מַטֵּה מֹשֶׁה לִפְנֵי פַּרְעֹה?", correctAnswer: "נָחָשׁ", distractors: ["צְפַרְדֵּעַ", "אַרְיֵה", "יוֹנָה"]),
        BankQuestion(prompt: "🌊\nאֵיזֶה יָם נִבְקַע לִפְנֵי בְּנֵי יִשְׂרָאֵל?", correctAnswer: "יַם סוּף", distractors: ["הַכִּנֶּרֶת", "יַם הַמֶּלַח", "הַיַּרְדֵּן"]),
        BankQuestion(prompt: "🛶\nמִי בָּנָה תֵּבָה גְּדוֹלָה וְהִכְנִיס אֵלֶיהָ חַיּוֹת?", correctAnswer: "נֹחַ", distractors: ["מֹשֶׁה", "אַבְרָהָם", "דָּוִד"]),
        BankQuestion(prompt: "🌈\nאֵיזֶה סִימָן נָתַן אֱלֹהִים לְנֹחַ אַחֲרֵי הַמַּבּוּל?", correctAnswer: "קֶשֶׁת בֶּעָנָן", distractors: ["כּוֹכָב", "סֻלָּם", "שׁוֹפָר"]),
        BankQuestion(prompt: "🪜\nמִי חָלַם עַל סֻלָּם עִם מַלְאָכִים?", correctAnswer: "יַעֲקֹב", distractors: ["יוֹסֵף", "מֹשֶׁה", "שְׁמוּאֵל"]),
        BankQuestion(prompt: "🎨\nלְמִי הָיְתָה כְּתֹנֶת פַּסִּים צִבְעוֹנִית?", correctAnswer: "יוֹסֵף", distractors: ["דָּוִד", "אַהֲרֹן", "יִצְחָק"]),
        BankQuestion(prompt: "👶\nאֵיפֹה נִמְצָא הַתִּינוֹק מֹשֶׁה בְּתֵבָה?", correctAnswer: "בַּיְאוֹר", distractors: ["בַּמִּדְבָּר", "בַּסֻּכָּה", "עַל הָהָר"]),
        BankQuestion(prompt: "🗿\nעַל מָה כָּתַב אֱלֹהִים אֶת עֲשֶׂרֶת הַדִּבְּרוֹת?", correctAnswer: "לוּחוֹת אֶבֶן", distractors: ["נְיָר", "עֵץ", "חוֹל"]),
        BankQuestion(prompt: "🏔️\nעַל אֵיזֶה הַר קִבֵּל מֹשֶׁה אֶת הַתּוֹרָה?", correctAnswer: "הַר סִינַי", distractors: ["הַר הַחֶרְמוֹן", "הַר הַכַּרְמֶל", "הַר תָּבוֹר"]),
        BankQuestion(prompt: "🐑\nמָה הָיָה הַתַּפְקִיד שֶׁל דָּוִד לִפְנֵי שֶׁהָיָה מֶלֶךְ?", correctAnswer: "רוֹעֶה צֹאן", distractors: ["נַגָּר", "דַּיָּג", "כֹּהֵן"]),
        BankQuestion(prompt: "🪨\nבְּמָה הִשְׁתַּמֵּשׁ דָּוִד כְּדֵי לְהַבִּיס אֶת גָּלְיָת?", correctAnswer: "קֶלַע וְאֶבֶן", distractors: ["חֶרֶב", "קֶשֶׁת", "מַקֵּל"]),
        BankQuestion(prompt: "🇮🇱\nכַּמָּה צְבָעִים יֵשׁ בְּדֶגֶל יִשְׂרָאֵל?", correctAnswer: "שְׁנַיִם", distractors: ["שְׁלֹשָׁה", "אַרְבָּעָה", "אֶחָד"]),
        BankQuestion(prompt: "🎵\nאֵיךְ קוֹרְאִים לַהִמְנוֹן שֶׁל מְדִינַת יִשְׂרָאֵל?", correctAnswer: "הַתִּקְוָה", distractors: ["יְרוּשָׁלַיִם שֶׁל זָהָב", "הֵבֵאנוּ שָׁלוֹם", "הָאָרֶץ הַטּוֹבָה"]),
        BankQuestion(prompt: "💰\nאֵיךְ קוֹרְאִים לַכֶּסֶף שֶׁמִּשְׁתַּמְּשִׁים בּוֹ בְּיִשְׂרָאֵל?", correctAnswer: "שֶׁקֶל", distractors: ["דּוֹלָר", "אֵירוֹ", "לִירָה"]),
        BankQuestion(prompt: "🌴\nעַל אֵיזֶה עֵץ גְּדֵלִים תְּמָרִים?", correctAnswer: "דֶּקֶל", distractors: ["אַלּוֹן", "בְּרוֹשׁ", "אֹרֶן"]),
        BankQuestion(prompt: "🐪\nאֵיזוֹ חַיָּה נִקְרֵאת 'סְפִינַת הַמִּדְבָּר'?", correctAnswer: "גָּמָל", distractors: ["סוּס", "חֲמוֹר", "פָּרָה"]),
        BankQuestion(prompt: "💡\nמָה הִמְצִיא תּוֹמַס אֵדִיסוֹן שֶׁמֵּאִיר אֶת הַבַּיִת?", correctAnswer: "נוּרַת חַשְׁמַל", distractors: ["טֵלֵפוֹן", "מָטוֹס", "רַכֶּבֶת"]),
        BankQuestion(prompt: "✈️\nמָה הִמְצִיאוּ הָאַחִים רַייט שֶׁעָף בַּשָּׁמַיִם?", correctAnswer: "מָטוֹס", distractors: ["אֳנִיָּה", "אוֹפַנּוֹעַ", "צוֹלֶלֶת"]),
        BankQuestion(prompt: "☎️\nמַהוּ הַמַּכְשִׁיר שֶׁהִמְצִיא גְּרַהַם בֵּל שֶׁעוֹזֵר לְדַבֵּר מֵרָחוֹק?", correctAnswer: "טֵלֵפוֹן", distractors: ["מַצְלֵמָה", "שָׁעוֹן", "מַחְשֵׁב"]),
    ]

    static let geography: [BankQuestion] = [
        BankQuestion(prompt: "🦁\nאֵיפֹה חַיִּים אֲרָיוֹת בַּטֶּבַע?", correctAnswer: "בְּאַפְרִיקָה", distractors: ["בְּאַנְטַרְקְטִיקָה", "בְּיִשְׂרָאֵל", "בְּקָנָדָה"]),
        BankQuestion(prompt: "🐪\nאֵיפֹה רוֹאִים גְּמַלִּים בְּיִשְׂרָאֵל?", correctAnswer: "בַּמִּדְבָּר", distractors: ["בַּיָּם", "בַּשֶּׁלֶג", "בַּיַּעַר הַגָּשׁוּם"]),
        BankQuestion(prompt: "🐨\nבְּאֵיזוֹ אֶרֶץ חַי הַקּוֹאָלָה?", correctAnswer: "אוֹסְטְרַלְיָה", distractors: ["סִין", "הוֹדוּ", "בְּרָזִיל"]),
        BankQuestion(prompt: "🐻‍❄️\nאֵיפֹה חַי הַדֹּב הַלָּבָן?", correctAnswer: "בַּקֹּטֶב הַצְּפוֹנִי", distractors: ["בַּמִּדְבָּר", "בַּיַּעַר הַגָּשׁוּם", "בְּאַפְרִיקָה"]),
        BankQuestion(prompt: "🦓\nבְּאֵיזוֹ יַבֶּשֶׁת חַיָּה הַזֶּבְּרָה?", correctAnswer: "אַפְרִיקָה", distractors: ["אֵירוֹפָּה", "אוֹסְטְרַלְיָה", "אַנְטַרְקְטִיקָה"]),
        BankQuestion(prompt: "🦜\nאֵיפֹה חַיִּים תֻּכִּים צִבְעוֹנִיִּים רַבִּים?", correctAnswer: "בַּיַּעַר הַגָּשׁוּם", distractors: ["בַּקֹּטֶב", "בַּמִּדְבָּר", "עַל הַשֶּׁלֶג"]),
        BankQuestion(prompt: "🏖️\nאֵיזוֹ עִיר גְּדוֹלָה יוֹשֶׁבֶת עַל חוֹף הַיָּם הַתִּיכוֹן?", correctAnswer: "תֵּל אָבִיב", distractors: ["יְרוּשָׁלַיִם", "בְּאֵר שֶׁבַע", "דִּימוֹנָה"]),
        BankQuestion(prompt: "⚓\nאֵיזוֹ עִיר נָמֵל גְּדוֹלָה נִמְצֵאת בִּצְפוֹן יִשְׂרָאֵל?", correctAnswer: "חֵיפָה", distractors: ["אֵילַת", "טְבֶרְיָה", "צְפַת"]),
        BankQuestion(prompt: "🌊\nעַל שְׂפַת אֵיזֶה יָם יוֹשֶׁבֶת הָעִיר אֵילַת?", correctAnswer: "יָם סוּף", distractors: ["יָם הַמֶּלַח", "הַיָּם הַתִּיכוֹן", "הַכִּנֶּרֶת"]),
        BankQuestion(prompt: "🐟\nעַל שְׂפַת אֵיזֶה אֲגַם יוֹשֶׁבֶת הָעִיר טְבֶרְיָה?", correctAnswer: "הַכִּנֶּרֶת", distractors: ["יָם הַמֶּלַח", "הַיָּם הַתִּיכוֹן", "יָם סוּף"]),
        BankQuestion(prompt: "🏛️\nאֵיזוֹ עִיר עַתִּיקָה מְפֻרְסֶמֶת בַּצָּפוֹן עַל הַר?", correctAnswer: "צְפַת", distractors: ["אֵילַת", "אַשְׁדּוֹד", "הֶרְצְלִיָּה"]),
        BankQuestion(prompt: "🧭\nבַּמַּפָּה, אֵיזֶה כִּוּוּן נִמְצָא לְמַעְלָה?", correctAnswer: "צָפוֹן", distractors: ["דָּרוֹם", "מִזְרָח", "מַעֲרָב"]),
        BankQuestion(prompt: "☀️\nבְּאֵיזֶה כִּוּוּן זוֹרַחַת הַשֶּׁמֶשׁ בַּבֹּקֶר?", correctAnswer: "מִזְרָח", distractors: ["מַעֲרָב", "צָפוֹן", "דָּרוֹם"]),
        BankQuestion(prompt: "🇬🇷\nמַה בִּירַת יָוָון?", correctAnswer: "אָתוּנָה", distractors: ["רוֹמָא", "אִיסְטַנְבּוּל", "קָהִיר"]),
        BankQuestion(prompt: "🇵🇹\nמַה בִּירַת פּוֹרְטוּגָל?", correctAnswer: "לִיסְבּוֹן", distractors: ["מַדְרִיד", "בַּרְצֵלוֹנָה", "פָּרִיז"]),
        BankQuestion(prompt: "🇳🇱\nמַה בִּירַת הוֹלַנְד?", correctAnswer: "אַמְסְטֶרְדָּם", distractors: ["בְּרִיסֶל", "בֶּרְלִין", "פָּרִיז"]),
        BankQuestion(prompt: "🇨🇭\nמַה בִּירַת שְׁוֵיץ?", correctAnswer: "בֶּרְן", distractors: ["צִיריךְ", "גֶּ'נֵבָה", "וִינָה"]),
        BankQuestion(prompt: "🇸🇪\nמַה בִּירַת שְׁוֵדְיָה?", correctAnswer: "סְטוֹקְהוֹלְם", distractors: ["אוֹסְלוֹ", "קוֹפֶּנְהָאגֶן", "הֶלְסִינְקִי"]),
        BankQuestion(prompt: "🌋\nבְּאֵיזֶה כִּוּוּן בְּיִשְׂרָאֵל נִמְצֵאת הָעִיר אֵילַת?", correctAnswer: "בַּדָּרוֹם", distractors: ["בַּצָּפוֹן", "בַּמִּזְרָח", "בַּמַּעֲרָב"]),
        BankQuestion(prompt: "🏔️\nבְּאֵיזֶה אֵזוֹר בְּיִשְׂרָאֵל נוֹפֵל שֶׁלֶג בַּחֹרֶף?", correctAnswer: "הַחֶרְמוֹן", distractors: ["אֵילַת", "הַנֶּגֶב", "תֵּל אָבִיב"]),
        BankQuestion(prompt: "🐊\nבְּאֵיזֶה נָהָר בְּאַפְרִיקָה חַיִּים תַּנִּינִים?", correctAnswer: "הַנִּילוּס", distractors: ["הָאַמָזוֹנַס", "הַיַּרְדֵּן", "הַיַּרְקוֹן"]),
        BankQuestion(prompt: "🦅\nבְּאֵיזוֹ יַבֶּשֶׁת נִמְצָא הַיַּעַר הַגָּשׁוּם הַגָּדוֹל בְּיוֹתֵר?", correctAnswer: "דְּרוֹם אֲמֵרִיקָה", distractors: ["אֵירוֹפָּה", "אוֹסְטְרַלְיָה", "אַנְטַרְקְטִיקָה"]),
        BankQuestion(prompt: "🐅\nבְּאֵיזוֹ יַבֶּשֶׁת חַי הַנָּמֵר בַּטֶּבַע?", correctAnswer: "אַסְיָה", distractors: ["אַנְטַרְקְטִיקָה", "אוֹסְטְרַלְיָה", "אֵירוֹפָּה"]),
        BankQuestion(prompt: "🏝️\nאוֹסְטְרַלְיָה הִיא גַּם יַבֶּשֶׁת וְגַם...?", correctAnswer: "מְדִינָה", distractors: ["נָהָר", "הַר", "אוֹקְיָנוֹס"]),
        BankQuestion(prompt: "🌍\nבְּאֵיזוֹ יַבֶּשֶׁת נִמְצֵאת מִצְרַיִם?", correctAnswer: "אַפְרִיקָה", distractors: ["אַסְיָה", "אֵירוֹפָּה", "דְּרוֹם אֲמֵרִיקָה"]),
        BankQuestion(prompt: "🌎\nבְּאֵיזוֹ יַבֶּשֶׁת נִמְצֵאת בְּרָזִיל?", correctAnswer: "דְּרוֹם אֲמֵרִיקָה", distractors: ["אַפְרִיקָה", "אֵירוֹפָּה", "אַסְיָה"]),
        BankQuestion(prompt: "🐫\nאֵיזֶה מִדְבָּר עָנָק נִמְצָא בִּצְפוֹן אַפְרִיקָה?", correctAnswer: "סַהַרָה", distractors: ["הַנֶּגֶב", "סִינַי", "גּוֹבִּי"]),
        BankQuestion(prompt: "🏞️\nאֵיזֶה נָהָר זוֹרֵם בְּיִשְׂרָאֵל וְנִשְׁפָּךְ לְיָם הַמֶּלַח?", correctAnswer: "הַיַּרְדֵּן", distractors: ["הַנִּילוּס", "הָאַמָזוֹנַס", "הַיַּרְקוֹן"]),
        BankQuestion(prompt: "🌊\nאֵיזֶה אֲגַם מָלוּחַ נִמְצָא בִּדְרוֹם־מִזְרַח יִשְׂרָאֵל?", correctAnswer: "יָם הַמֶּלַח", distractors: ["הַכִּנֶּרֶת", "הַיָּם הַתִּיכוֹן", "יָם סוּף"]),
        BankQuestion(prompt: "🦬\nבְּאֵיזוֹ יַבֶּשֶׁת חַיִּים הַבּוּפָלוֹ הַגְּדוֹלִים בַּמִּישׁוֹרִים?", correctAnswer: "צְפוֹן אֲמֵרִיקָה", distractors: ["אַנְטַרְקְטִיקָה", "אֵירוֹפָּה", "אוֹסְטְרַלְיָה"]),
        BankQuestion(prompt: "🌐\nאֵיךְ קוֹרְאִים לַכַּדּוּר שֶׁמַּרְאֶה אֶת כָּל הָעוֹלָם?", correctAnswer: "גְּלוֹבּוּס", distractors: ["מַצְפֵּן", "טֶלֶסְקוֹפּ", "שָׁעוֹן"]),
        BankQuestion(prompt: "🗺️\nעַל מָה מְצַיְּרִים אֶת הַיַּבָּשׁוֹת וְהַיַּמִּים?", correctAnswer: "מַפָּה", distractors: ["לוּחַ שָׁנָה", "סֵפֶר בִּשּׁוּל", "תְּעוּדָה"]),
        BankQuestion(prompt: "🐘\nבְּאֵיזוֹ יַבֶּשֶׁת חַיִּים הַפִּילִים הֲכִי גְּדוֹלִים?", correctAnswer: "אַפְרִיקָה", distractors: ["אֵירוֹפָּה", "אוֹסְטְרַלְיָה", "אַנְטַרְקְטִיקָה"]),
        BankQuestion(prompt: "🇮🇪\nמַה בִּירַת אִירְלַנְד?", correctAnswer: "דַּבְּלִין", distractors: ["לוֹנְדּוֹן", "אֶדִינְבּוֹרוֹ", "אַמְסְטֶרְדָּם"]),
        BankQuestion(prompt: "🏜️\nאֵיזֶה אֵזוֹר תּוֹפֵס אֶת רֹב הַדָּרוֹם שֶׁל יִשְׂרָאֵל?", correctAnswer: "הַנֶּגֶב", distractors: ["הַגָּלִיל", "הַשָּׁרוֹן", "הַכַּרְמֶל"]),
    ]

    static let money: [BankQuestion] = [
        BankQuestion(prompt: "🪙🪙🪙🪙\nאַרְבַּע מַטְבְּעוֹת שֶׁל 1 ₪ — כַּמָּה זֶה בְּיַחַד?", correctAnswer: "4 ₪", distractors: ["3 ₪", "5 ₪", "6 ₪"]),
        BankQuestion(prompt: "🪙🪙\nמַטְבֵּעַ שֶׁל 2 ₪ וְעוֹד מַטְבֵּעַ שֶׁל 2 ₪ — כַּמָּה זֶה?", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "6 ₪"]),
        BankQuestion(prompt: "🍬\nיֵשׁ לְךָ 5 ₪ וְסֻכָּרִיָּה עוֹלָה 2 ₪. כַּמָּה עֹדֶף תְּקַבֵּל?", correctAnswer: "3 ₪", distractors: ["1 ₪", "2 ₪", "4 ₪"]),
        BankQuestion(prompt: "🥨\nקָנִיתָ בַּגֶּל בְּ-4 ₪ וְשִׁלַּמְתָּ עִם 10 ₪. כַּמָּה עֹדֶף?", correctAnswer: "6 ₪", distractors: ["4 ₪", "5 ₪", "7 ₪"]),
        BankQuestion(prompt: "🍌\nבַּנָנָה עוֹלָה 3 ₪. שִׁלַּמְתָּ עִם 5 ₪. כַּמָּה עֹדֶף?", correctAnswer: "2 ₪", distractors: ["1 ₪", "3 ₪", "4 ₪"]),
        BankQuestion(prompt: "💰\nיֵשׁ לְךָ 2 ₪ וְקִבַּלְתָּ עוֹד 6 ₪. כַּמָּה יֵשׁ לְךָ עַכְשָׁו?", correctAnswer: "8 ₪", distractors: ["4 ₪", "7 ₪", "9 ₪"]),
        BankQuestion(prompt: "🪙🪙🪙\nשָׁלוֹשׁ מַטְבְּעוֹת שֶׁל 1 ₪ וְעוֹד מַטְבֵּעַ שֶׁל 1 ₪ — כַּמָּה זֶה?", correctAnswer: "4 ₪", distractors: ["3 ₪", "5 ₪", "6 ₪"]),
        BankQuestion(prompt: "🥕\nגֶּזֶר עוֹלֶה 2 ₪. כַּמָּה יַעֲלוּ שְׁלוֹשָׁה גְּזָרִים?", correctAnswer: "6 ₪", distractors: ["4 ₪", "5 ₪", "8 ₪"]),
        BankQuestion(prompt: "🪙\nאֵיזֶה מַטְבֵּעַ שָׁוֶה הֲכִי הַרְבֵּה?", correctAnswer: "10 ₪", distractors: ["1 ₪", "2 ₪", "5 ₪"]),
        BankQuestion(prompt: "💵\nאֵיזֶה שְׁטָר שָׁוֶה הֲכִי מְעַט?", correctAnswer: "20 ₪", distractors: ["50 ₪", "100 ₪", "200 ₪"]),
        BankQuestion(prompt: "🪙\nכַּמָּה מַטְבְּעוֹת שֶׁל 1 ₪ צָרִיךְ כְּדֵי לְהַגִּיעַ לְ-5 ₪?", correctAnswer: "5", distractors: ["2", "3", "10"]),
        BankQuestion(prompt: "🧃\nמַה מֵאֵלֶּה הוּא 'רָצוֹן' וְלֹא 'צֹרֶךְ'?", correctAnswer: "צַעֲצוּעַ חָדָשׁ", distractors: ["מַיִם לִשְׁתּוֹת", "אֹכֶל בָּרִיא", "בְּגָדִים חַמִּים"]),
        BankQuestion(prompt: "🛏️\nמַה מֵאֵלֶּה הוּא 'צֹרֶךְ' חָשׁוּב?", correctAnswer: "מָקוֹם לִישֹׁן", distractors: ["בָּלוֹן צִבְעוֹנִי", "מַדְבֵּקוֹת", "מִשְׂחָק חָדָשׁ"]),
        BankQuestion(prompt: "🐷\nאֵיךְ קֻפַּת הַחִסָּכוֹן מִתְמַלֵּאת?", correctAnswer: "מוֹסִיפִים אֵלֶיהָ קְצָת כֶּסֶף כָּל פַּעַם", distractors: ["מוֹצִיאִים מִמֶּנָּה כָּל יוֹם", "מַשְׁאִירִים אוֹתָהּ רֵיקָה", "זוֹרְקִים אוֹתָהּ"]),
        BankQuestion(prompt: "💡\nלָמָּה כְּדַאי לַחְסֹךְ כֶּסֶף?", correctAnswer: "כְּדֵי שֶׁיִּהְיֶה לְמַשֶּׁהוּ גָּדוֹל בֶּעָתִיד", distractors: ["כְּדֵי לְבַזְבֵּז מַהֵר יוֹתֵר", "כְּדֵי לְאַבֵּד אוֹתוֹ", "כְּדֵי לְהַסְתִּיר אוֹתוֹ"]),
        BankQuestion(prompt: "🛒\nיֵשׁ לְךָ 10 ₪ וְהַצַּעֲצוּעַ עוֹלֶה 15 ₪. מָה אֶפְשָׁר לַעֲשׂוֹת?", correctAnswer: "לַחְסֹךְ עוֹד קְצָת וְאָז לִקְנוֹת", distractors: ["לָקַחַת בְּלִי לְשַׁלֵּם", "לִבְכּוֹת עַד שֶׁיִּתְּנוּ", "לִשְׁבֹּר אֶת הַצַּעֲצוּעַ"]),
        BankQuestion(prompt: "🍕\nיֵשׁ לָכֶם פִּיצָה אַחַת לְ-4 חֲבֵרִים. מָה הֲכִי הוֹגֵן?", correctAnswer: "לְחַלֵּק שָׁוֶה בְּשָׁוֶה", distractors: ["אֶחָד לוֹקֵחַ הַכֹּל", "זוֹרְקִים אֶת הַפִּיצָה", "רָבִים עָלֶיהָ"]),
        BankQuestion(prompt: "💝\nלְאָחִיךָ אֵין כֶּסֶף לְמַדְבֵּקָה וּלְךָ יֵשׁ שְׁתַּיִם. מָה נֶחְמָד?", correctAnswer: "לָתֵת לוֹ מַדְבֵּקָה אַחַת", distractors: ["לְהַחְבִּיא אֶת שְׁתֵּיהֶן", "לְהַרְאוֹת לוֹ וְלֹא לָתֵת", "לִזְרֹק אֶת שֶׁלּוֹ"]),
        BankQuestion(prompt: "🏷️\nאוֹתוֹ צַעֲצוּעַ בַּחֲנוּת אַחַת עוֹלֶה 9 ₪ וּבַחֲנוּת אַחֶרֶת 7 ₪. אֵיפֹה זוֹל יוֹתֵר?", correctAnswer: "בְּ-7 ₪", distractors: ["בְּ-9 ₪", "אוֹתוֹ מְחִיר", "אִי אֶפְשָׁר לָדַעַת"]),
        BankQuestion(prompt: "📋\nמָה כְּדַאי לַעֲשׂוֹת לִפְנֵי שֶׁקּוֹנִים הַרְבֵּה דְּבָרִים?", correctAnswer: "לִכְתֹּב רְשִׁימָה וְלִבְדֹּק כַּמָּה כֶּסֶף יֵשׁ", distractors: ["לִקְנוֹת הַכֹּל בְּלִי לַחְשֹׁב", "לִשְׁכֹּחַ אֶת הַכֶּסֶף בַּבַּיִת", "לָקַחַת אֶת הַכֹּל מֵהַמַּדָּף"]),
        BankQuestion(prompt: "💰\nחָסַכְתָּ 4 ₪ וְקִבַּלְתָּ עוֹד 4 ₪ מִסַּבְתָּא. כַּמָּה יֵשׁ לְךָ?", correctAnswer: "8 ₪", distractors: ["4 ₪", "6 ₪", "10 ₪"]),
        BankQuestion(prompt: "🪙\nאֵיזֶה מַטְבֵּעַ גָּדוֹל יוֹתֵר בְּעֵרֶךְ — 2 ₪ אוֹ 5 ₪?", correctAnswer: "5 ₪", distractors: ["2 ₪", "שְׁנֵיהֶם שָׁוִים", "אִי אֶפְשָׁר לָדַעַת"]),
        BankQuestion(prompt: "🛍️\nשִׁלַּמְתָּ 7 ₪ עִם שְׁטָר שֶׁל 10 ₪. כַּמָּה עֹדֶף?", correctAnswer: "3 ₪", distractors: ["2 ₪", "4 ₪", "5 ₪"]),
        BankQuestion(prompt: "🍫\nשׁוֹקוֹלָד עוֹלֶה 6 ₪ וְשִׁלַּמְתָּ עִם 6 ₪. כַּמָּה עֹדֶף?", correctAnswer: "0 ₪", distractors: ["1 ₪", "2 ₪", "6 ₪"]),
        BankQuestion(prompt: "🤝\nאַתָּה וְחָבֵר רוֹצִים לִקְנוֹת כַּדּוּר בְּ-10 ₪ בְּיַחַד. כַּמָּה יִתֵּן כָּל אֶחָד שָׁוֶה בְּשָׁוֶה?", correctAnswer: "5 ₪", distractors: ["2 ₪", "10 ₪", "20 ₪"]),
        BankQuestion(prompt: "🐖\nבְּקֻפַּת הַחִסָּכוֹן יֵשׁ 5 ₪ וְשַׂמְתָּ עוֹד 3 ₪. כַּמָּה יֵשׁ עַכְשָׁו?", correctAnswer: "8 ₪", distractors: ["2 ₪", "7 ₪", "9 ₪"]),
        BankQuestion(prompt: "🧾\nמָה מְקַבְּלִים בַּחֲנוּת אַחֲרֵי שֶׁמְּשַׁלְּמִים?", correctAnswer: "קַבָּלָה", distractors: ["צַעֲצוּעַ בְּמַתָּנָה", "כֶּסֶף נוֹסָף", "מַפְתֵּחַ לַחֲנוּת"]),
        BankQuestion(prompt: "💸\nמָה קוֹרֶה אִם מְבַזְבְּזִים אֶת כָּל הַכֶּסֶף מִיָּד?", correctAnswer: "לֹא נִשְׁאָר כֶּסֶף לִדְבָרִים אֲחֵרִים", distractors: ["הַכֶּסֶף חוֹזֵר לְבַד", "מְקַבְּלִים עוֹד כֶּסֶף", "שׁוּם דָּבָר לֹא קוֹרֶה"]),
        BankQuestion(prompt: "🎈\nבָּלוֹן עוֹלֶה 2 ₪. כַּמָּה יַעֲלוּ שְׁנֵי בָּלוֹנִים?", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "6 ₪"]),
    ]

}
