import Foundation

/// Second wave of authored + adversarially-verified questions (expand-banks-v2:
/// rethought Hebrew with no spelling type — comprehension, riddles, meanings, etc.).
enum QuestionBanksWorkflow2 {
    static let english: [BankQuestion] = [
        BankQuestion(prompt: "👩\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "mother", distractors: ["father", "sister", "grandma"]),
        BankQuestion(prompt: "👨\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "father", distractors: ["mother", "brother", "uncle"]),
        BankQuestion(prompt: "👵\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "grandma", distractors: ["mother", "aunt", "sister"]),
        BankQuestion(prompt: "👦\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "brother", distractors: ["sister", "father", "friend"]),
        BankQuestion(prompt: "😀\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "happy", distractors: ["sad", "angry", "tired"]),
        BankQuestion(prompt: "😢\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "sad", distractors: ["happy", "scared", "hungry"]),
        BankQuestion(prompt: "😠\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "angry", distractors: ["happy", "sleepy", "sad"]),
        BankQuestion(prompt: "😴\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "tired", distractors: ["happy", "hungry", "angry"]),
        BankQuestion(prompt: "☀️\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "sun", distractors: ["rain", "cloud", "wind"]),
        BankQuestion(prompt: "🌧️\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "rain", distractors: ["sun", "snow", "cloud"]),
        BankQuestion(prompt: "❄️\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "snow", distractors: ["rain", "sun", "wind"]),
        BankQuestion(prompt: "☁️\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "cloud", distractors: ["sun", "rain", "snow"]),
        BankQuestion(prompt: "🛏️\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "bedroom", distractors: ["kitchen", "bathroom", "garden"]),
        BankQuestion(prompt: "🍳\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "kitchen", distractors: ["bedroom", "bathroom", "garden"]),
        BankQuestion(prompt: "🛁\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "bathroom", distractors: ["kitchen", "bedroom", "garden"]),
        BankQuestion(prompt: "🚪\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "door", distractors: ["window", "wall", "floor"]),
        BankQuestion(prompt: "👮\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "police", distractors: ["doctor", "teacher", "farmer"]),
        BankQuestion(prompt: "👨‍🍳\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "cook", distractors: ["doctor", "teacher", "pilot"]),
        BankQuestion(prompt: "👩‍⚕️\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "doctor", distractors: ["teacher", "police", "cook"]),
        BankQuestion(prompt: "🧑‍🚒\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "firefighter", distractors: ["doctor", "teacher", "pilot"]),
        BankQuestion(prompt: "👕\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "shirt", distractors: ["pants", "socks", "dress"]),
        BankQuestion(prompt: "👖\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "pants", distractors: ["shirt", "socks", "coat"]),
        BankQuestion(prompt: "🧦\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "socks", distractors: ["shoes", "pants", "gloves"]),
        BankQuestion(prompt: "🧥\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "coat", distractors: ["shirt", "hat", "socks"]),
        BankQuestion(prompt: "🥕\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "carrot", distractors: ["tomato", "potato", "onion"]),
        BankQuestion(prompt: "🍅\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "tomato", distractors: ["carrot", "potato", "pepper"]),
        BankQuestion(prompt: "🥔\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "potato", distractors: ["tomato", "carrot", "onion"]),
        BankQuestion(prompt: "🌽\nאֵיךְ אוֹמְרִים אֶת זֶה בְּאַנְגְּלִית?", correctAnswer: "corn", distractors: ["carrot", "tomato", "potato"]),
    ]

    static let hebrew: [BankQuestion] = [
        BankQuestion(prompt: "דָּנִי קָנָה בַּלּוֹן צָהֹב בַּיָּרִיד. אֵיזֶה צֶבַע הַבַּלּוֹן?", correctAnswer: "צָהֹב", distractors: ["אָדֹם", "כָּחֹל", "יָרֹק"]),
        BankQuestion(prompt: "נֹעָה הָלְכָה עִם אִמָּא לְגַן הַחַיּוֹת וְרָאֲתָה פִּיל. מָה נֹעָה רָאֲתָה?", correctAnswer: "פִּיל", distractors: ["דֻּבִּי", "סוּס", "אֲרִי"]),
        BankQuestion(prompt: "יוֹתָם שָׁתָה כּוֹס מַיִם קְרִירִים כִּי הָיָה צָמֵא. לָמָּה יוֹתָם שָׁתָה?", correctAnswer: "כִּי הָיָה צָמֵא", distractors: ["כִּי הָיָה רָעֵב", "כִּי הָיָה עָיֵף", "כִּי הָיָה קַר לוֹ"]),
        BankQuestion(prompt: "שִׁירָה שִׂחֲקָה בַּחוֹל וּבָנְתָה אַרְמוֹן גָּדוֹל. מָה שִׁירָה בָּנְתָה?", correctAnswer: "אַרְמוֹן", distractors: ["מִגְדָּל", "גֶּשֶׁר", "סִירָה"]),
        BankQuestion(prompt: "סָבָּא נָסַע בָּרַכֶּבֶת לְחֵיפָה לְבַקֵּר אֶת הַדּוֹדָה. לְאָן נָסַע סָבָּא?", correctAnswer: "לְחֵיפָה", distractors: ["לְאֵילַת", "לִירוּשָׁלַיִם", "לְתֵל אָבִיב"]),
        BankQuestion(prompt: "מַאיָה אִחֲרָה לַגַּן כִּי הִיא קָמָה מְאֻחָר בַּבֹּקֶר. לָמָּה מַאיָה אִחֲרָה?", correctAnswer: "כִּי קָמָה מְאֻחָר", distractors: ["כִּי לֹא רָצְתָה לָלֶכֶת", "כִּי הָיְתָה חוֹלָה", "כִּי יָרַד גֶּשֶׁם"]),
        BankQuestion(prompt: "אוֹרִי מָצָא חָתוּל קָטָן בֶּחָצֵר וְהֶאֱכִיל אוֹתוֹ. אֵיזוֹ חַיָּה אוֹרִי מָצָא?", correctAnswer: "חָתוּל", distractors: ["כֶּלֶב", "צִפּוֹר", "אַרְנָב"]),
        BankQuestion(prompt: "תָּמָר לָבְשָׁה מְעִיל חַם כִּי בַּחוּץ יָרַד גֶּשֶׁם וְהָיָה קַר. מָתַי לָבְשָׁה תָּמָר מְעִיל?", correctAnswer: "כְּשֶׁהָיָה קַר", distractors: ["כְּשֶׁהָיָה חַם", "כְּשֶׁזָּרְחָה הַשֶּׁמֶשׁ", "כְּשֶׁהָלְכָה לִישׁוֹן"]),
        BankQuestion(prompt: "גִּיל אָסַף שָׁלוֹשׁ אֲבָנִים יָפוֹת בְּחוֹף הַיָּם. כַּמָּה אֲבָנִים אָסַף גִּיל?", correctAnswer: "שָׁלוֹשׁ", distractors: ["שְׁתַּיִם", "אַרְבַּע", "חָמֵשׁ"]),
        BankQuestion(prompt: "רוֹנִי אָפְתָה עוּגַת שׁוֹקוֹלָד לְיוֹם הַהֻלֶּדֶת שֶׁל אַבָּא. לְמִי אָפְתָה רוֹנִי עוּגָה?", correctAnswer: "לְאַבָּא", distractors: ["לְאִמָּא", "לְסָבְתָא", "לְאָחִיהָ"]),
        BankQuestion(prompt: "אֵיתָן רָץ מַהֵר בַּמִּגְרָשׁ וְהִבְקִיעַ שַׁעַר בְּמִשְׂחַק הַכַּדּוּרֶגֶל. מָה אֵיתָן הִבְקִיעַ?", correctAnswer: "שַׁעַר", distractors: ["סַל", "נְקֻדָּה", "פֶּנְדֵּל"]),
        BankQuestion(prompt: "הַיַּלְדָּה לִיאַת קָטְפָה תַּפּוּז מֵהָעֵץ בַּגִּנָּה וְאָכְלָה אוֹתוֹ. מֵאֵיזֶה עֵץ קָטְפָה לִיאַת?", correctAnswer: "עֵץ תַּפּוּז", distractors: ["עֵץ תַּפּוּחַ", "עֵץ זַיִת", "עֵץ דֶּקֶל"]),
        BankQuestion(prompt: "עֹמֶר שָׁכַח אֶת הַמִּטְרִיָּה בַּבַּיִת, וְלָכֵן הוּא הִתְרַטֵּב בַּגֶּשֶׁם. מָה עֹמֶר שָׁכַח?", correctAnswer: "מִטְרִיָּה", distractors: ["כּוֹבַע", "מְעִיל", "תִּיק"]),
        BankQuestion(prompt: "סָבְתָא נָתְנָה לְיָעֵל מַתָּנָה: בֻּבָּה חֲדָשָׁה. מָה קִבְּלָה יָעֵל מִסָּבְתָא?", correctAnswer: "בֻּבָּה", distractors: ["סֵפֶר", "כַּדּוּר", "אוֹפַנַּיִם"]),
        BankQuestion(prompt: "אֲנִי לָבָן, בָּא מֵהַפָּרָה, וְשׁוֹתִים אוֹתִי בַּבֹּקֶר. מָה אֲנִי?", correctAnswer: "חָלָב", distractors: ["מַיִם", "דְּבַשׁ", "תַּפּוּז"]),
        BankQuestion(prompt: "יֵשׁ לִי כְּנָפַיִם, אֲנִי מְזַמְזֵם וְעוֹשֶׂה דְּבַשׁ. מִי אֲנִי?", correctAnswer: "דְּבוֹרָה", distractors: ["פַּרְפַּר", "צִפּוֹר", "יַתּוּשׁ"]),
        BankQuestion(prompt: "אֲנִי קוֹפֵץ, יֵשׁ לִי כִּיס עַל הַבֶּטֶן וְגָר בְּאוֹסְטְרַלְיָה. מִי אֲנִי?", correctAnswer: "קֶנְגּוּרוּ", distractors: ["אַרְנָב", "צְפַרְדֵּעַ", "סְנָאִי"]),
        BankQuestion(prompt: "אֲנִי צָהֹב, נִמְצָא בַּשָּׁמַיִם בַּיּוֹם וּמְחַמֵּם אֶת כֻּלָּם. מָה אֲנִי?", correctAnswer: "שֶׁמֶשׁ", distractors: ["יָרֵחַ", "עָנָן", "כּוֹכָב"]),
        BankQuestion(prompt: "אֲנִי בָּא מֵהָעֲנָנִים, נוֹפֵל מִלְמַעְלָה וּמַרְטִיב אֶת הַכֹּל. מָה אֲנִי?", correctAnswer: "גֶּשֶׁם", distractors: ["שֶׁלֶג", "רוּחַ", "אֵשׁ"]),
        BankQuestion(prompt: "יֵשׁ לִי גַּלְגַּלִּים, צִלְצוּל וַאֲנִי נוֹסֵעַ עַל הַמְּסִלָּה. מָה אֲנִי?", correctAnswer: "רַכֶּבֶת", distractors: ["אֳנִיָּה", "מָטוֹס", "אוֹפַנַּיִם"]),
        BankQuestion(prompt: "אֲנִי מְלַקֵּק אֶת הֶחָלָב, מְיַלֵּל 'מְיָאוּ' וְאוֹהֵב לִישֹׁן. מִי אֲנִי?", correctAnswer: "חָתוּל", distractors: ["כֶּלֶב", "עֵז", "סוּס"]),
        BankQuestion(prompt: "אֲנִי קַר מְאֹד, לָבָן וְנוֹפֵל בַּחֹרֶף בְּמָקוֹם קַר. מָה אֲנִי?", correctAnswer: "שֶׁלֶג", distractors: ["חוֹל", "סֻכָּר", "קֶמַח"]),
        BankQuestion(prompt: "יֵשׁ לִי צַוָּאר אָרֹךְ מְאֹד וַאֲנִי אוֹכֵל עָלִים מֵרֹאשׁ הָעֵץ. מִי אֲנִי?", correctAnswer: "גִּ'ירָפָה", distractors: ["פִּיל", "זֶבְּרָה", "אַרְיֵה"]),
        BankQuestion(prompt: "אֲנִי גָּדוֹל וָאֲפֹר, יֵשׁ לִי חֵדֶק אָרֹךְ וְאָזְנַיִם עֲנָקִיּוֹת. מִי אֲנִי?", correctAnswer: "פִּיל", distractors: ["הִיפּוֹפּוֹטָם", "קַרְנַף", "דֹּב"]),
        BankQuestion(prompt: "אֲנִי שׁוֹחֶה בַּמַּיִם, יֵשׁ לִי סְנַפִּירִים וְאֵין לִי רַגְלַיִם. מִי אֲנִי?", correctAnswer: "דָּג", distractors: ["צָב", "בַּרְוָז", "צְפַרְדֵּעַ"]),
        BankQuestion(prompt: "אֲנִי גָּדֵל בַּגִּנָּה, אֲנִי אָדֹם וְרֵיחָנִי, וְיֵשׁ לִי קוֹצִים. מָה אֲנִי?", correctAnswer: "וֶרֶד", distractors: ["עֵץ", "דֶּשֶׁא", "פֶּטֶל"]),
        BankQuestion(prompt: "אֲנִי בָּא אַחֲרֵי הַגֶּשֶׁם, יֵשׁ לִי הַרְבֵּה צְבָעִים וַאֲנִי בַּשָּׁמַיִם. מָה אֲנִי?", correctAnswer: "קֶשֶׁת", distractors: ["עָנָן", "בָּרָק", "כּוֹכָב"]),
        BankQuestion(prompt: "אֲנִי עָגֹל, מְתַקְתַּק, אָדֹם, וְגָדֵל עַל עֵץ. מָה אֲנִי?", correctAnswer: "תַּפּוּחַ", distractors: ["בָּנָנָה", "אֲבַטִּיחַ", "עֲנָבִים"]),
        BankQuestion(prompt: "מָה הַמַּשְׁמָעוּת שֶׁל 'זָעִיר'?", correctAnswer: "קָטָן מְאֹד", distractors: ["גָּבוֹהַּ מְאֹד", "כָּבֵד מְאֹד", "רוֹעֵשׁ מְאֹד"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה דּוֹמָה בְּמַשְׁמָעוּת לְ'מָהִיר'?", correctAnswer: "זָרִיז", distractors: ["חָזָק", "רָעֵב", "צָהֹב"]),
        BankQuestion(prompt: "מָה הַמַּשְׁמָעוּת שֶׁל 'נֶהְדָּר'?", correctAnswer: "יָפֶה וְטוֹב מְאֹד", distractors: ["יָשָׁן וְשָׁבוּר", "קַר וְרָטֹב", "רֵיק לְגַמְרֵי"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה דּוֹמָה בְּמַשְׁמָעוּת לְ'עָצוּב'?", correctAnswer: "עָגוּם", distractors: ["מְצֻחְצָח", "מָתוֹק", "רָחָב"]),
        BankQuestion(prompt: "מָה הַמַּשְׁמָעוּת שֶׁל 'אַמִּיץ'?", correctAnswer: "לֹא מְפַחֵד", distractors: ["מְאֹד עָיֵף", "מְאֹד רָעֵב", "מְאֹד נָקִי"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה דּוֹמָה בְּמַשְׁמָעוּת לְ'חָכָם'?", correctAnswer: "פִּקֵּחַ", distractors: ["שָׂמֵחַ", "גָּבוֹהַּ", "מָהִיר"]),
        BankQuestion(prompt: "מָה הַמַּשְׁמָעוּת שֶׁל 'בּוֹהֵק'?", correctAnswer: "מַבְרִיק וּמֵאִיר", distractors: ["כֵּהֶה וְחָשׁוּךְ", "רַךְ וְנָעִים", "חַם וְלַח"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה דּוֹמָה בְּמַשְׁמָעוּת לְ'בַּיִת'?", correctAnswer: "מִשְׁכָּן", distractors: ["מִשְׂחָק", "מַתָּנָה", "מַסָּע"]),
        BankQuestion(prompt: "מָה הַמַּשְׁמָעוּת שֶׁל 'רָעֵב'?", correctAnswer: "רוֹצֶה לֶאֱכֹל", distractors: ["רוֹצֶה לִישֹׁן", "רוֹצֶה לָשִׁיר", "רוֹצֶה לִרְחֹץ"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה דּוֹמָה בְּמַשְׁמָעוּת לְ'דֶּרֶךְ'?", correctAnswer: "שְׁבִיל", distractors: ["עָנָן", "כִּסֵּא", "כּוֹכָב"]),
        BankQuestion(prompt: "מָה הַמַּשְׁמָעוּת שֶׁל 'צוֹהֵל'?", correctAnswer: "שָׂמֵחַ מְאֹד", distractors: ["עָיֵף מְאֹד", "כּוֹעֵס מְאֹד", "רָטֹב מְאֹד"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה דּוֹמָה בְּמַשְׁמָעוּת לְ'חָבֵר'?", correctAnswer: "יָדִיד", distractors: ["שָׁכֵן", "מוֹרֶה", "אוֹרֵחַ"]),
        BankQuestion(prompt: "מָה הַמַּשְׁמָעוּת שֶׁל 'מֻפְתָּע'?", correctAnswer: "לֹא צִפָּה שֶׁזֶּה יִקְרֶה", distractors: ["יוֹדֵעַ הַכֹּל מֵרֹאשׁ", "מְאֹד רָגוּעַ", "מְאֹד עָיֵף"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה דּוֹמָה בְּמַשְׁמָעוּת לְ'יָפֶה'?", correctAnswer: "נָאֶה", distractors: ["גָּדוֹל", "קַר", "רָחוֹק"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'כָּבֵד'?", correctAnswer: "קַל", distractors: ["גָּדוֹל", "חָזָק", "עָבֶה"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'גָּבוֹהַּ'?", correctAnswer: "נָמוּךְ", distractors: ["קָצָר", "קָטָן", "רָחוֹק"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'רָטוֹב'?", correctAnswer: "יָבֵשׁ", distractors: ["קַר", "נָקִי", "חָלָק"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'חָדָשׁ'?", correctAnswer: "יָשָׁן", distractors: ["קָרוּעַ", "שָׁבוּר", "מְלֻכְלָךְ"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'רָחוֹק'?", correctAnswer: "קָרוֹב", distractors: ["מָהִיר", "קָטָן", "נָמוּךְ"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'חָזָק'?", correctAnswer: "חַלָּשׁ", distractors: ["קָטָן", "עָיֵף", "אִיטִּי"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'רוֹעֵשׁ'?", correctAnswer: "שָׁקֵט", distractors: ["רוֹקֵד", "אִיטִּי", "רָחוֹק"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'עָשִׁיר'?", correctAnswer: "עָנִי", distractors: ["קַמְצָן", "עָצוּב", "רָעֵב"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'רִאשׁוֹן'?", correctAnswer: "אַחֲרוֹן", distractors: ["שֵׁנִי", "אֶמְצָעִי", "הַבָּא"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'לְהַדְלִיק'?", correctAnswer: "לְכַבּוֹת", distractors: ["לִשְׂרֹף", "לְהָאִיר", "לְחַמֵּם"]),
        BankQuestion(prompt: "מָה הַהֵפֶךְ מִ'לֶאֱהֹב'?", correctAnswer: "לִשְׂנֹא", distractors: ["לִכְעֹס", "לִבְכּוֹת", "לְפַחֵד"]),
        BankQuestion(prompt: "מָה הָרַבִּים שֶׁל 'חַלּוֹן'?", correctAnswer: "חַלּוֹנוֹת", distractors: ["חַלּוֹנִים", "חַלּוֹנַיִם", "חֲלוֹנֵי"]),
        BankQuestion(prompt: "מָה הָרַבִּים שֶׁל 'אִישׁ'?", correctAnswer: "אֲנָשִׁים", distractors: ["אִישִׁים", "אִישׁוֹת", "אֲנָשׁוֹת"]),
        BankQuestion(prompt: "מָה הָרַבִּים שֶׁל 'שֻׁלְחָן'?", correctAnswer: "שֻׁלְחָנוֹת", distractors: ["שֻׁלְחָנִים", "שֻׁלְחָנַיִם", "שֻׁלְחֵי"]),
        BankQuestion(prompt: "אֵיךְ אוֹמְרִים 'גָּדוֹל' כְּשֶׁמְּדַבְּרִים עַל יַלְדָּה?", correctAnswer: "גְּדוֹלָה", distractors: ["גְּדוֹלִים", "גָּדוֹל", "גְּדוֹלוֹת"]),
        BankQuestion(prompt: "אֵיךְ אוֹמְרִים 'קָטָן' כְּשֶׁמְּדַבְּרִים עַל חֲתוּלָה?", correctAnswer: "קְטַנָּה", distractors: ["קָטָן", "קְטַנִּים", "קְטַנּוֹת"]),
        BankQuestion(prompt: "אֵיךְ אוֹמְרִים 'הַתִּיק שֶׁל בֵּית הַסֵּפֶר' בְּמִלָּה אַחַת?", correctAnswer: "יַלְקוּט", distractors: ["מִזְוָדָה", "אַרְנָק", "קֻפְסָה"]),
        BankQuestion(prompt: "אֵיךְ קוֹרְאִים לַבֶּגֶד שֶׁל הַיָּד בַּחֹרֶף?", correctAnswer: "כְּפָפָה", distractors: ["גֶּרֶב", "כּוֹבַע", "צָעִיף"]),
        BankQuestion(prompt: "אֵיךְ אוֹמְרִים 'הַזָּנָב שֶׁל הַכֶּלֶב' בִּסְמִיכוּת?", correctAnswer: "זְנַב הַכֶּלֶב", distractors: ["זָנָב הַכֶּלֶב", "הַזָּנָב כֶּלֶב", "כֶּלֶב הַזָּנָב"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מִתְחָרֶזֶת עִם 'כַּדּוּר'?", correctAnswer: "צִפּוֹר", distractors: ["סֵפֶר", "כִּסֵּא", "תַּפּוּחַ"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מִתְחָרֶזֶת עִם 'דָּג'?", correctAnswer: "חָג", distractors: ["יָם", "אֲגַם", "סִירָה"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מִתְחָרֶזֶת עִם 'פִּיל'?", correctAnswer: "גִּיל", distractors: ["דֹּב", "זְאֵב", "אַרְיֵה"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מִתְחָרֶזֶת עִם 'יָד'?", correctAnswer: "כַּד", distractors: ["רֶגֶל", "אֹזֶן", "עַיִן"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מִתְחָרֶזֶת עִם 'בַּיִת'?", correctAnswer: "זַיִת", distractors: ["חַלּוֹן", "דֶּלֶת", "גַּג"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מִתְחָרֶזֶת עִם 'עִיר'?", correctAnswer: "שִׁיר", distractors: ["כְּפָר", "רְחוֹב", "בִּנְיָן"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מִתְחָרֶזֶת עִם 'מַיִם'?", correctAnswer: "שָׁמַיִם", distractors: ["נָהָר", "גֶּשֶׁם", "טִפָּה"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מִתְחָרֶזֶת עִם 'כּוֹבַע'?", correctAnswer: "אֶצְבַּע", distractors: ["נַעַל", "מְעִיל", "צָעִיף"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מִתְחָרֶזֶת עִם 'סוּס'?", correctAnswer: "אוֹטוֹבּוּס", distractors: ["חֲמוֹר", "פָּרָה", "עֵז"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מַתְחִילָה בְּאוֹתוֹ צְלִיל כְּמוֹ 'שֶׁמֶשׁ'?", correctAnswer: "שׁוּלְחָן", distractors: ["מִטָּה", "כִּסֵּא", "אָרוֹן"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה מַתְחִילָה בְּאוֹתוֹ צְלִיל כְּמוֹ 'בָּנָנָה'?", correctAnswer: "בַּקְבּוּק", distractors: ["תַּפּוּחַ", "אֲנָנָס", "עֲנָבִים"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה נִגְמֶרֶת בְּאוֹתוֹ צְלִיל כְּמוֹ 'פַּרְפַּר'?", correctAnswer: "כְּפָר", distractors: ["דְּבוֹרָה", "נְמָלָה", "זְבוּב"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה הִיא כְּלִי תַּחְבּוּרָה?", correctAnswer: "אוֹטוֹבּוּס", distractors: ["כִּסֵּא", "תַּפּוּחַ", "מַחְבֶּרֶת"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה הִיא חַיַּת יָם?", correctAnswer: "דּוֹלְפִין", distractors: ["גָּמָל", "אַרְיֵה", "תֻּכִּי"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה הִיא פְּרִי?", correctAnswer: "אֲבַטִּיחַ", distractors: ["מַזְלֵג", "כּוֹבַע", "סֻלָּם"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה הִיא כְּלִי עֲבוֹדָה?", correctAnswer: "פַּטִּישׁ", distractors: ["עֻגָּה", "פַּרְפַּר", "כָּרִית"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה הִיא יֶרֶק?", correctAnswer: "מְלָפְפוֹן", distractors: ["שָׁעוֹן", "נַעַל", "מָטוֹס"]),
        BankQuestion(prompt: "מַה זֶה לֹא בֶּגֶד?", correctAnswer: "מַזְלֵג", distractors: ["חֻלְצָה", "מִכְנָסַיִם", "גַּרְבַּיִם"]),
        BankQuestion(prompt: "מַה זֶה לֹא חַיַּת מֶשֶׁק?", correctAnswer: "זֶבְּרָה", distractors: ["פָּרָה", "תַּרְנְגֹלֶת", "כֶּבֶשׂ"]),
        BankQuestion(prompt: "מַה זֶה לֹא מַאֲכָל?", correctAnswer: "כַּפְכַּף", distractors: ["לֶחֶם", "גְּבִינָה", "אֹרֶז"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה הִיא צֶבַע?", correctAnswer: "סָגֹל", distractors: ["כֶּלֶב", "שֻׁלְחָן", "עָנָן"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה הִיא מָקוֹם שֶׁלּוֹמְדִים בּוֹ?", correctAnswer: "בֵּית סֵפֶר", distractors: ["מִקְלַחַת", "מִטְבָּח", "חֲנוּת"]),
        BankQuestion(prompt: "מַה זֶה לֹא דָּבָר מָתוֹק?", correctAnswer: "לִימוֹן", distractors: ["דְּבַשׁ", "שׁוֹקוֹלָד", "סֻכָּרִיָּה"]),
        BankQuestion(prompt: "אֵיזוֹ מִילָּה שַׁיֶּכֶת לַגּוּף שֶׁלָּנוּ?", correctAnswer: "בֶּרֶךְ", distractors: ["מַחְבַּת", "אוֹפַנַּיִם", "מַחְשֵׁב"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'בַּקַּיִץ הַיָּם...'", correctAnswer: "חַם", distractors: ["קָפוּא", "מוּשְׁלָג", "יָבֵשׁ"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'הַדָּג שׂוֹחֶה בְּתוֹךְ הַ...'", correctAnswer: "מַיִם", distractors: ["עֵץ", "אֲוִיר", "חוֹל"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'כְּשֶׁאֲנִי עָיֵף אֲנִי הוֹלֵךְ...'", correctAnswer: "לִישֹׁן", distractors: ["לִרְקֹד", "לִקְפֹּץ", "לָרוּץ"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'הַכֶּלֶב נוֹבֵחַ, וְהַחָתוּל...'", correctAnswer: "מְיַלֵּל", distractors: ["מְצַיֵּץ", "גּוֹעֶה", "צוֹהֵל"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'אֲנִי רוֹאֶה עִם הָ...'", correctAnswer: "עֵינַיִם", distractors: ["אָזְנַיִם", "אַף", "רַגְלַיִם"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'הַגְּלִידָה קָרָה וְהַמָּרָק...'", correctAnswer: "חַם", distractors: ["קָפוּא", "צָהֹב", "רָטֹב"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'בַּלַּיְלָה רוֹאִים בַּשָּׁמַיִם אֶת הַ...'", correctAnswer: "יָרֵחַ", distractors: ["שֶׁמֶשׁ", "עָנָן", "קֶשֶׁת"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'אֲנִי שׁוֹמֵעַ מוּזִיקָה עִם הָ...'", correctAnswer: "אָזְנַיִם", distractors: ["יָדַיִם", "עֵינַיִם", "בִּרְכַּיִם"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'אַחֲרֵי שֶׁאוֹכְלִים, מְצַחְצְחִים אֶת הַ...'", correctAnswer: "שִׁנַּיִם", distractors: ["נַעֲלַיִם", "חַלּוֹנוֹת", "צַעֲצוּעִים"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'הַפְּרָחִים צוֹמְחִים בָּ...'", correctAnswer: "גִּנָּה", distractors: ["מְקָרֵר", "אַמְבַּטְיָה", "אֲרוֹן"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'כְּשֶׁחַם לִי אֲנִי לוֹבֵשׁ חֻלְצָה, וּכְשֶׁקַּר אֲנִי לוֹבֵשׁ...'", correctAnswer: "מְעִיל", distractors: ["כּוֹבַע יָם", "סַנְדָּלִים", "בֶּגֶד יָם"]),
        BankQuestion(prompt: "הַשְׁלִימוּ: 'הַדְּבוֹרָה אוֹסֶפֶת מֵהַפֶּרַח וְעוֹשָׂה...'", correctAnswer: "דְּבַשׁ", distractors: ["חָלָב", "מִיץ", "קֶמַח"]),
    ]

    static let logic: [BankQuestion] = [
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n7, 14, 21, ?", correctAnswer: "28", distractors: ["27", "30", "35"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n3, 6, 12, 24, ?", correctAnswer: "48", distractors: ["36", "30", "40"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n50, 40, 30, ?", correctAnswer: "20", distractors: ["25", "10", "35"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n🟢🟢🔴🟢🟢🔴🟢🟢?", correctAnswer: "🔴", distractors: ["🟢", "🔵", "🟡"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n🐢🐰🐢🐰🐢?", correctAnswer: "🐰", distractors: ["🐢", "🐭", "🦊"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n⭐🌙⭐⭐🌙⭐⭐⭐🌙?", correctAnswer: "⭐", distractors: ["🌙", "☀️", "🌟"]),
        BankQuestion(prompt: "מָה הַצּוּרָה הַבָּאָה?\n🔵🔺🟦🔵🔺?", correctAnswer: "🟦", distractors: ["🔵", "🔺", "⚫"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\n9, 8, 7, 6, ?", correctAnswer: "5", distractors: ["4", "7", "10"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי?\nא, ג, ה, ?", correctAnswer: "ז", distractors: ["ו", "ח", "ב"]),
        BankQuestion(prompt: "מִי לֹא שַׁיָּךְ?", correctAnswer: "🌻", distractors: ["🐝", "🦋", "🐞"]),
        BankQuestion(prompt: "מִי לֹא שַׁיָּךְ?", correctAnswer: "🍕", distractors: ["👕", "👖", "🧦"]),
        BankQuestion(prompt: "מִי לֹא שַׁיָּךְ?", correctAnswer: "🦈", distractors: ["🐦", "🦅", "🦉"]),
        BankQuestion(prompt: "מִי לֹא שַׁיָּךְ?", correctAnswer: "☂️", distractors: ["✏️", "📕", "✂️"]),
        BankQuestion(prompt: "מַה זֶה לֹא רֶגֶל שֶׁל חַיָּה?", correctAnswer: "🪶", distractors: ["🐾", "🦵", "🦶"]),
        BankQuestion(prompt: "כַּמָּה גַּלְגַּלִּים יֵשׁ לִשְׁנֵי אוֹפַנַּיִם?", correctAnswer: "4", distractors: ["2", "3", "6"]),
        BankQuestion(prompt: "כַּמָּה אֶצְבָּעוֹת יֵשׁ בְּיָד אַחַת?", correctAnswer: "5", distractors: ["4", "10", "6"]),
        BankQuestion(prompt: "כַּמָּה זְנָבוֹת יֵשׁ לְ-4 חֲתוּלִים?", correctAnswer: "4", distractors: ["8", "2", "16"]),
        BankQuestion(prompt: "כַּמָּה כְּנָפַיִם יֵשׁ לִשְׁתֵּי צִיפּוֹרִים?", correctAnswer: "4", distractors: ["2", "6", "8"]),
        BankQuestion(prompt: "מָה בָּא לִפְנֵי הַמִּסְפָּר 8?", correctAnswer: "7", distractors: ["9", "6", "10"]),
        BankQuestion(prompt: "מָה בָּא אַחֲרֵי הַמִּסְפָּר 19?", correctAnswer: "20", distractors: ["18", "21", "29"]),
        BankQuestion(prompt: "אֵיזוֹ אוֹת בָּאָה אַחֲרֵי הָאוֹת מ?", correctAnswer: "נ", distractors: ["ל", "ס", "כ"]),
        BankQuestion(prompt: "אִם הַיּוֹם יוֹם שִׁשִּׁי, אֵיזֶה יוֹם הָיָה אֶתְמוֹל?", correctAnswer: "חֲמִישִׁי", distractors: ["רְבִיעִי", "שַׁבָּת", "שְׁלִישִׁי"]),
        BankQuestion(prompt: "אִם 🍌=5, אָז 🍌+🍌=?", correctAnswer: "10", distractors: ["7", "15", "25"]),
        BankQuestion(prompt: "אִם כָּל הַדָּגִים שׂוֹחִים, מָה עוֹשֶׂה הַדָּג?", correctAnswer: "שׂוֹחֶה", distractors: ["עָף", "קוֹפֵץ", "רָץ"]),
        BankQuestion(prompt: "אִם בַּגִּנָּה 4 פְּרָחִים וְקָטַפְנוּ 1, כַּמָּה נִשְׁאֲרוּ?", correctAnswer: "3", distractors: ["5", "2", "4"]),
        BankQuestion(prompt: "אִם 🐘 כָּבֵד מֵ-🐭, מִי קַל יוֹתֵר?", correctAnswer: "🐭", distractors: ["🐘", "אוֹתוֹ דָּבָר", "לֹא יוֹדֵעַ"]),
        BankQuestion(prompt: "אֵיפֹה נִמְצֵאת הַשֶּׁמֶשׁ?\n☀️\n🏠", correctAnswer: "לְמַעְלָה", distractors: ["לְמַטָּה", "בַּצַּד", "מֵאָחוֹר"]),
        BankQuestion(prompt: "בְּאֵיזוֹ צוּרָה יֵשׁ 3 פִּינּוֹת?", correctAnswer: "🔺", distractors: ["⚪", "⬛", "⬢"]),
    ]

    static let science: [BankQuestion] = [
        BankQuestion(prompt: "🫀\nאֵיזֶה אֵיבָר פּוֹעֵם בְּתוֹךְ הֶחָזֶה שֶׁלָּנוּ?", correctAnswer: "הַלֵּב", distractors: ["הַכָּבֵד", "הַקֵּבָה", "הַטְּחוֹל"]),
        BankQuestion(prompt: "💪\nמָה עוֹזֵר לָנוּ לְהָזִיז אֶת הַיָּדַיִם וְהָרַגְלַיִם?", correctAnswer: "הַשְּׁרִירִים", distractors: ["הַשֵּׂעָר", "הַצִּפָּרְנַיִם", "הַדְּמָעוֹת"]),
        BankQuestion(prompt: "🦵\nמָה נִמְצָא בְּתוֹךְ הַגּוּף וְנוֹתֵן לוֹ צוּרָה?", correctAnswer: "הָעֲצָמוֹת", distractors: ["הָעֲנָנִים", "הַשֶּׁלֶג", "הַחוֹל"]),
        BankQuestion(prompt: "🫁\nאֵיזֶה אֵיבָר מִתְמַלֵּא בַּאֲוִיר כְּשֶׁאֲנַחְנוּ נוֹשְׁמִים?", correctAnswer: "הָרֵאוֹת", distractors: ["הַלֵּב", "הַקֵּבָה", "הַמֹּחַ"]),
        BankQuestion(prompt: "💇\nמָה צוֹמֵחַ עַל הָרֹאשׁ שֶׁלָּנוּ?", correctAnswer: "שֵׂעָר", distractors: ["נוֹצוֹת", "קַשְׂקַשִּׂים", "פַּרְוָה"]),
        BankQuestion(prompt: "🦘\nאֵיזוֹ חַיָּה נוֹשֵׂאת אֶת הַגּוּר שֶׁלָּהּ בְּכִיס?", correctAnswer: "קֶנְגּוּרוּ", distractors: ["אַרְיֵה", "פִּיל", "זֶבְּרָה"]),
        BankQuestion(prompt: "🐧\nאֵיזוֹ צִיפּוֹר לֹא יְכוֹלָה לָעוּף אֲבָל שׂוֹחָה נֶהְדָּר?", correctAnswer: "פִּינְגְּוִוין", distractors: ["יוֹנָה", "נֶשֶׁר", "דְּרוֹר"]),
        BankQuestion(prompt: "🕸️\nמָה הָעַכָּבִישׁ טוֹוֶה כְּדֵי לָצוּד?", correctAnswer: "קוּרִים", distractors: ["דְּבַשׁ", "חֲלָב", "קֵן מִקַּשׁ"]),
        BankQuestion(prompt: "🐘\nבְּמָה הַפִּיל מִשְׁתַּמֵּשׁ כְּדֵי לִשְׁתּוֹת וּלְהָרִים דְּבָרִים?", correctAnswer: "בַּחֵדֶק", distractors: ["בַּזָּנָב", "בָּאָזְנַיִם", "בָּרַגְלַיִם"]),
        BankQuestion(prompt: "🐄\nאֵיזֶה מַשְׁקֶה אֲנַחְנוּ מְקַבְּלִים מֵהַפָּרָה?", correctAnswer: "חָלָב", distractors: ["מִיץ", "דְּבַשׁ", "שֶׁמֶן"]),
        BankQuestion(prompt: "🪐\nאֵיזֶה כּוֹכַב לֶכֶת מְפֻרְסָם בַּטַּבָּעוֹת שֶׁמְּסַבְּבוֹת אוֹתוֹ?", correctAnswer: "שַׁבְּתַאי", distractors: ["מַאְדִּים", "נוֹגַהּ", "כַּדּוּר הָאָרֶץ"]),
        BankQuestion(prompt: "🌕\nכְּשֶׁהַיָּרֵחַ עָגֹל וּמָלֵא לְגַמְרֵי אֵיךְ קוֹרְאִים לוֹ?", correctAnswer: "יָרֵחַ מָלֵא", distractors: ["יָרֵחַ אָדֹם", "יָרֵחַ קַר", "יָרֵחַ קָטָן"]),
        BankQuestion(prompt: "🌌\nאֵיךְ קוֹרְאִים לָאוֹסֶף הָעֲנָק שֶׁל כּוֹכָבִים בַּשָּׁמַיִם?", correctAnswer: "גָּלַקְסְיָה", distractors: ["עֲנָנָה", "קֶשֶׁת", "סוּפָה"]),
        BankQuestion(prompt: "🌑\nכַּמָּה שְׁמָשׁוֹת יֵשׁ בְּמַעֲרֶכֶת הַשֶּׁמֶשׁ שֶׁלָּנוּ?", correctAnswer: "אַחַת", distractors: ["שְׁתַּיִם", "שָׁלוֹשׁ", "אֵין"]),
        BankQuestion(prompt: "⚡\nאֵיזֶה אוֹר מַבְהִיק מוֹפִיעַ בַּשָּׁמַיִם בִּזְמַן סוּפָה?", correctAnswer: "בָּרָק", distractors: ["קֶשֶׁת", "שֶׁלֶג", "עֲרָפֶל"]),
        BankQuestion(prompt: "🌪️\nאֵיךְ קוֹרְאִים לְרוּחַ חֲזָקָה שֶׁמִּסְתּוֹבֶבֶת כְּמוֹ עַמּוּד?", correctAnswer: "טוֹרְנָדוֹ", distractors: ["קֶשֶׁת", "טִיפָּה", "עָנָן רָגִיל"]),
        BankQuestion(prompt: "☀️\nאֵיךְ קוֹרְאִים לְיוֹם בְּלִי עֲנָנִים שֶׁבּוֹ הַשֶּׁמֶשׁ זוֹרַחַת?", correctAnswer: "יוֹם בָּהִיר", distractors: ["יוֹם גָּשׁוּם", "יוֹם מֻשְׁלָג", "יוֹם סוֹעֵר"]),
        BankQuestion(prompt: "🌡️\nבְּאֵיזוֹ עוֹנָה הֲכִי קַר בְּיִשְׂרָאֵל?", correctAnswer: "בַּחֹרֶף", distractors: ["בַּקַּיִץ", "בָּאָבִיב", "בַּסְּתָו"]),
        BankQuestion(prompt: "🍂\nבְּאֵיזוֹ עוֹנָה הֶעָלִים נוֹשְׁרִים מֵהָעֵצִים?", correctAnswer: "בַּסְּתָו", distractors: ["בַּקַּיִץ", "בָּאָבִיב", "בְּכָל הַשָּׁנָה"]),
        BankQuestion(prompt: "🌷\nבְּאֵיזוֹ עוֹנָה פּוֹרְחִים הֲכִי הַרְבֵּה פְּרָחִים?", correctAnswer: "בָּאָבִיב", distractors: ["בַּחֹרֶף", "בַּסְּתָו", "בַּלַּיְלָה"]),
        BankQuestion(prompt: "🌰\nמָה צוֹמֵחַ קֹדֶם כְּשֶׁזֶּרַע מַתְחִיל לִגְדֹּל בָּאֲדָמָה?", correctAnswer: "הַשֹּׁרֶשׁ", distractors: ["הַפֶּרַח", "הַפְּרִי", "הֶעָלֶה הַגָּדוֹל"]),
        BankQuestion(prompt: "🌿\nמָה הַצֶּבַע שֶׁל רֹב הֶעָלִים שֶׁל הַצְּמָחִים?", correctAnswer: "יָרֹק", distractors: ["כָּחֹל", "סָגֹל", "שָׁחֹר"]),
        BankQuestion(prompt: "🍋\nאֵיךְ טוֹעֵם לִימוֹן?", correctAnswer: "חָמוּץ", distractors: ["מָתוֹק", "מָלוּחַ", "חָרִיף"]),
        BankQuestion(prompt: "🍯\nאֵיךְ טוֹעֵם דְּבַשׁ?", correctAnswer: "מָתוֹק", distractors: ["חָמוּץ", "מָלוּחַ", "מַר"]),
        BankQuestion(prompt: "🥶\nאֵיךְ מַרְגִּישׁ קֶרַח כְּשֶׁנּוֹגְעִים בּוֹ?", correctAnswer: "קַר", distractors: ["חַם", "רָטֹב וְחַם", "רַךְ"]),
        BankQuestion(prompt: "🔥\nאֵיךְ מַרְגִּישׁ אֹכֶל שֶׁיָּצָא מֵהַתַּנּוּר?", correctAnswer: "חַם", distractors: ["קַר", "קָפוּא", "קָשֶׁה כְּמוֹ אֶבֶן"]),
        BankQuestion(prompt: "💧\nמָה קוֹרֶה לְשֶׁלֶג כְּשֶׁמְּחַמְּמִים אוֹתוֹ?", correctAnswer: "הוּא הוֹפֵךְ לְמַיִם", distractors: ["הוּא הוֹפֵךְ לְאֶבֶן", "הוּא הוֹפֵךְ לַחוֹל", "הוּא נִשְׁאָר אוֹתוֹ דָּבָר"]),
        BankQuestion(prompt: "🪵\nמֵאֵיזֶה חֹמֶר עָשׂוּי שֻׁלְחָן עֵץ?", correctAnswer: "עֵץ", distractors: ["זְכוּכִית", "בַּרְזֶל", "פְּלַסְטִיק"]),
        BankQuestion(prompt: "👅\nבְּעֶזְרַת אֵיזֶה חוּשׁ אֲנַחְנוּ יוֹדְעִים אִם אֹכֶל מָתוֹק אוֹ מָלוּחַ?", correctAnswer: "חוּשׁ הַטַּעַם", distractors: ["חוּשׁ הָרְאִיָּה", "חוּשׁ הַשְּׁמִיעָה", "חוּשׁ הָרֵיחַ"]),
    ]

    static let history: [BankQuestion] = [
        BankQuestion(prompt: "🕯️\nכַּמָּה נֵרוֹת מַדְלִיקִים בַּלַּיְלָה הָאַחֲרוֹן שֶׁל חֲנֻכָּה?", correctAnswer: "שְׁמוֹנָה", distractors: ["אֶחָד", "שְׁנַיִם", "אַרְבָּעָה"]),
        BankQuestion(prompt: "📜\nאֵיזוֹ מְגִלָּה קוֹרְאִים בְּחַג פּוּרִים?", correctAnswer: "מְגִלַּת אֶסְתֵּר", distractors: ["מְגִלַּת רוּת", "הַהַגָּדָה", "הַתּוֹרָה"]),
        BankQuestion(prompt: "🍞\nאֵיזֶה אֹכֶל אֲנַחְנוּ לֹא אוֹכְלִים בְּחַג הַפֶּסַח?", correctAnswer: "לֶחֶם", distractors: ["מַצָּה", "תַּפּוּחַ", "אֱגוֹזִים"]),
        BankQuestion(prompt: "🌳\nאֵיזֶה חַג נִקְרָא 'יוֹם הֻלֶּדֶת לָאִילָנוֹת'?", correctAnswer: "ט״וּ בִּשְׁבָט", distractors: ["פּוּרִים", "שָׁבוּעוֹת", "סֻכּוֹת"]),
        BankQuestion(prompt: "🎭\nמָה נָהוּג לִלְבֹּשׁ בְּחַג פּוּרִים?", correctAnswer: "תַּחְפֹּשֶׂת", distractors: ["מְעִיל גֶּשֶׁם", "בֶּגֶד יָם", "פִּיגָ'מָה"]),
        BankQuestion(prompt: "🐸\nאֵיזוֹ חַיָּה הָיְתָה אַחַת מֵעֶשֶׂר הַמַּכּוֹת בְּמִצְרַיִם?", correctAnswer: "צְפַרְדֵּעַ", distractors: ["פִּיל", "דֻּבִּי", "ג'ִירָפָה"]),
        BankQuestion(prompt: "👑\nמִי הָיָה הַמֶּלֶךְ הֶחָכָם שֶׁבָּנָה אֶת בֵּית הַמִּקְדָּשׁ?", correctAnswer: "שְׁלֹמֹה", distractors: ["שָׁאוּל", "יוֹסֵף", "אַהֲרֹן"]),
        BankQuestion(prompt: "🐋\nמִי בָּלַע אֶת יוֹנָה הַנָּבִיא בַּיָּם?", correctAnswer: "דָּג גָּדוֹל", distractors: ["תַּנִּין", "תְּמַנּוּן", "כְּרִישׁ"]),
        BankQuestion(prompt: "⭐\nאֵיךְ קוֹרְאִים לַסֵּמֶל בַּעַל שֵׁשׁ הַקְּצָווֹת שֶׁעַל דֶּגֶל יִשְׂרָאֵל?", correctAnswer: "מָגֵן דָּוִד", distractors: ["מְנוֹרָה", "שׁוֹפָר", "כֶּתֶר"]),
        BankQuestion(prompt: "🕎\nאֵיזֶה סֵמֶל עִם שִׁבְעָה קָנִים הוּא סֵמֶל הַמְּדִינָה?", correctAnswer: "מְנוֹרָה", distractors: ["סְבִיבוֹן", "רַעֲשָׁן", "חֲצוֹצְרָה"]),
        BankQuestion(prompt: "🏛️\nמַה בִּירַת מְדִינַת יִשְׂרָאֵל?", correctAnswer: "יְרוּשָׁלַיִם", distractors: ["תֵּל אָבִיב", "חֵיפָה", "אֵילַת"]),
        BankQuestion(prompt: "🌸\nבְּאֵיזוֹ עוֹנָה חוֹגְגִים אֶת חַג הַפֶּסַח?", correctAnswer: "בָּאָבִיב", distractors: ["בַּחֹרֶף", "בַּקַּיִץ", "בַּסְּתָו"]),
        BankQuestion(prompt: "🍯\nמָה מְבָרְכִים בְּרֹאשׁ הַשָּׁנָה שֶׁתִּהְיֶה שָׁנָה?", correctAnswer: "מְתוּקָה", distractors: ["קָרָה", "אֲרֻכָּה", "רְטֻבָּה"]),
        BankQuestion(prompt: "📯\nאֵיזֶה כְּלִי תּוֹקְעִים בּוֹ בְּרֹאשׁ הַשָּׁנָה?", correctAnswer: "שׁוֹפָר", distractors: ["חָלִיל", "תֹּף", "פְּסַנְתֵּר"]),
        BankQuestion(prompt: "🌿\nמָה מְנַעְנְעִים יַחַד עִם הַלּוּלָב בְּסֻכּוֹת?", correctAnswer: "אֶתְרוֹג", distractors: ["תַּפּוּחַ", "עַגְבָנִיָּה", "פֶּרַח"]),
        BankQuestion(prompt: "👫\nמִי הָיוּ הָאִישׁ וְהָאִשָּׁה הָרִאשׁוֹנִים בַּתּוֹרָה?", correctAnswer: "אָדָם וְחַוָּה", distractors: ["נֹחַ וְשָׂרָה", "מֹשֶׁה וְרוּת", "דָּוִד וְאֶסְתֵּר"]),
        BankQuestion(prompt: "🌟\nכַּמָּה כּוֹכָבִים הֶרְאָה אֱלֹהִים לְאַבְרָהָם וְהִבְטִיחַ זֶרַע רַב?", correctAnswer: "רַבִּים מְאוֹד", distractors: ["שְׁלֹשָׁה", "אֶחָד", "אֶפֶס"]),
        BankQuestion(prompt: "🐑\nאֵיזוֹ חַיָּה הִקְרִיב אַבְרָהָם בִּמְקוֹם יִצְחָק?", correctAnswer: "אַיִל", distractors: ["פָּרָה", "יוֹנָה", "דָּג"]),
        BankQuestion(prompt: "💍\nמִי הָיְתָה אִשְׁתּוֹ שֶׁל יִצְחָק שֶׁפָּגַשׁ לְיַד הַבְּאֵר?", correctAnswer: "רִבְקָה", distractors: ["שָׂרָה", "לֵאָה", "דְּבוֹרָה"]),
        BankQuestion(prompt: "🦁\nאֵיזוֹ חַיָּה מוֹפִיעָה בְּסֵמֶל הָעִיר יְרוּשָׁלַיִם?", correctAnswer: "אַרְיֵה", distractors: ["גָּמָל", "דָּג", "יוֹנָה"]),
        BankQuestion(prompt: "🥖\nאֵיזֶה לֶחֶם מְיֻחָד אוֹכְלִים בְּשַׁבָּת?", correctAnswer: "חַלָּה", distractors: ["מַצָּה", "פִּיתָה", "בָּגֵט"]),
        BankQuestion(prompt: "🕯️🕯️\nמָתַי מַדְלִיקִים נֵרוֹת לִכְבוֹד שַׁבָּת?", correctAnswer: "בְּעֶרֶב שַׁבָּת", distractors: ["בְּיוֹם רִאשׁוֹן", "בַּצָּהֳרַיִם", "בְּלֵיל חֲנֻכָּה"]),
        BankQuestion(prompt: "🏜️\nכַּמָּה שָׁנִים הָלְכוּ בְּנֵי יִשְׂרָאֵל בַּמִּדְבָּר?", correctAnswer: "אַרְבָּעִים", distractors: ["שָׁנָה אַחַת", "עֶשֶׂר", "מֵאָה"]),
        BankQuestion(prompt: "🌊\nאֵיזֶה אֲגַם בְּיִשְׂרָאֵל מַסְפִּיק מַיִם מְתוּקִים לִשְׁתִיָּה?", correctAnswer: "הַכִּנֶּרֶת", distractors: ["יָם הַמֶּלַח", "הַיָּם הַתִּיכוֹן", "יָם סוּף"]),
        BankQuestion(prompt: "🚲\nמָה נָהוּג לִרְכֹּב עָלָיו בָּרְחוֹבוֹת הָרֵיקִים בְּיוֹם כִּפּוּר בְּיִשְׂרָאֵל?", correctAnswer: "אוֹפַנַּיִם", distractors: ["סוּס", "רַכֶּבֶת", "אֳנִיָּה"]),
    ]

    static let geography: [BankQuestion] = [
        BankQuestion(prompt: "🇮🇱\nמַהִי בִּירַת יִשְׂרָאֵל?", correctAnswer: "יְרוּשָׁלַיִם", distractors: ["תֵּל אָבִיב", "חֵיפָה", "אֵילַת"]),
        BankQuestion(prompt: "🗼\nבְּאֵיזוֹ עִיר נִמְצָא מִגְדַּל אֵיפֶל?", correctAnswer: "פָּרִיז", distractors: ["לוֹנְדּוֹן", "רוֹמָא", "מַדְרִיד"]),
        BankQuestion(prompt: "🌊\nאֵיךְ קוֹרְאִים לַיָּם הַמָּלוּחַ בְּיוֹתֵר בְּיִשְׂרָאֵל?", correctAnswer: "יָם הַמֶּלַח", distractors: ["הַיָּם הַתִּיכוֹן", "הַכִּנֶּרֶת", "הַיָּם הָאָדֹם"]),
        BankQuestion(prompt: "🐘\nבְּאֵיזוֹ יַבֶּשֶׁת חַיִּים פִּילִים וַאֲרָיוֹת בַּטֶּבַע?", correctAnswer: "אַפְרִיקָה", distractors: ["אֵירוֹפָּה", "אַנְטַארְקְטִיקָה", "אוֹסְטְרַלְיָה"]),
        BankQuestion(prompt: "🐧\nהֵיכָן חַיִּים הַפִּינְגְּוִינִים בַּקֹּר הַגָּדוֹל?", correctAnswer: "אַנְטַארְקְטִיקָה", distractors: ["אַפְרִיקָה", "יִשְׂרָאֵל", "הַמִּדְבָּר"]),
        BankQuestion(prompt: "🦘\nבְּאֵיזוֹ אֶרֶץ חַיִּים הַקֶּנְגּוּרוּ?", correctAnswer: "אוֹסְטְרַלְיָה", distractors: ["יִשְׂרָאֵל", "מִצְרַיִם", "קָנָדָה"]),
        BankQuestion(prompt: "🐼\nבְּאֵיזוֹ אֶרֶץ חַי הַדֹּב פַּנְדָּה?", correctAnswer: "סִין", distractors: ["צָרְפַת", "בְּרָזִיל", "יָוָן"]),
        BankQuestion(prompt: "🏰\nמַהִי בִּירַת צָרְפַת?", correctAnswer: "פָּרִיז", distractors: ["בֵּרְלִין", "אַתּוּנָה", "קָהִיר"]),
        BankQuestion(prompt: "🎡\nמַהִי בִּירַת אַנְגְּלִיָּה?", correctAnswer: "לוֹנְדּוֹן", distractors: ["פָּרִיז", "רוֹמָא", "לִיסְבּוֹן"]),
        BankQuestion(prompt: "🍕\nמַהִי בִּירַת אִיטַלְיָה?", correctAnswer: "רוֹמָא", distractors: ["מִילָאנוֹ", "פָּרִיז", "וִינָה"]),
        BankQuestion(prompt: "🐪\nבְּאֵיזֶה מָקוֹם נִמְצָא הַרְבֵּה חוֹל וְכִמְעַט אֵין מַיִם?", correctAnswer: "הַמִּדְבָּר", distractors: ["הַיַּעַר", "הָאֹקְיָנוֹס", "הַקֹּטֶב"]),
        BankQuestion(prompt: "⛰️\nאֵיךְ קוֹרְאִים לָהָר הַגָּבוֹהַּ בַּצָּפוֹן שֶׁל יִשְׂרָאֵל שֶׁיּוֹרֵד עָלָיו שֶׁלֶג?", correctAnswer: "הַחֶרְמוֹן", distractors: ["הַר תָּבוֹר", "הַר הַכַּרְמֶל", "מָצָדָה"]),
        BankQuestion(prompt: "💧\nאֵיךְ קוֹרְאִים לָאֲגַם הַגָּדוֹל שֶׁל יִשְׂרָאֵל שֶׁשּׁוֹתִים מִמֶּנּוּ מַיִם?", correctAnswer: "הַכִּנֶּרֶת", distractors: ["יָם הַמֶּלַח", "הַיַּרְקוֹן", "הַיָּם הַתִּיכוֹן"]),
        BankQuestion(prompt: "🏖️\nאֵיךְ קוֹרְאִים לָעִיר שֶׁבְּדָרוֹם יִשְׂרָאֵל עִם יָם וְשׁוֹנִית?", correctAnswer: "אֵילַת", distractors: ["חֵיפָה", "צְפַת", "טְבֶרְיָה"]),
        BankQuestion(prompt: "🚢\nבְּאֵיזוֹ עִיר בְּיִשְׂרָאֵל יֵשׁ נְמַל יָם גָּדוֹל וְהַר כַּרְמֶל?", correctAnswer: "חֵיפָה", distractors: ["יְרוּשָׁלַיִם", "בְּאֵר שֶׁבַע", "אֵילַת"]),
        BankQuestion(prompt: "🇺🇸\nמַהִי בִּירַת אַרְצוֹת הַבְּרִית?", correctAnswer: "וָשִׁינְגְּטוֹן", distractors: ["נְיוּ יוֹרְק", "לוֹס אַנְגֶ'לֶס", "שִׁיקָגוֹ"]),
        BankQuestion(prompt: "🇪🇬\nמַהִי בִּירַת מִצְרַיִם?", correctAnswer: "קָהִיר", distractors: ["יְרוּשָׁלַיִם", "עַמָּאן", "דַּמֶּשֶׂק"]),
        BankQuestion(prompt: "🐠\nאֵיךְ קוֹרְאִים לַיָּם שֶׁל אֵילַת עִם הַדָּגִים הַצִּבְעוֹנִיִּים?", correctAnswer: "הַיָּם הָאָדֹם", distractors: ["יָם הַמֶּלַח", "הַכִּנֶּרֶת", "הַיָּם הַתִּיכוֹן"]),
        BankQuestion(prompt: "🌍\nמַהִי הַיַּבֶּשֶׁת שֶׁבָּהּ נִמְצֵאת יִשְׂרָאֵל?", correctAnswer: "אַסְיָה", distractors: ["אַפְרִיקָה", "אֵירוֹפָּה", "אוֹסְטְרַלְיָה"]),
        BankQuestion(prompt: "🦁\nאֵיךְ קוֹרְאִים לַמָּקוֹם שֶׁבּוֹ רוֹאִים חַיּוֹת מֵאֲחוֹרֵי גָּדֵר?", correctAnswer: "גַּן חַיּוֹת", distractors: ["הַיַּעַר", "הַמִּדְבָּר", "הַיָּם"]),
        BankQuestion(prompt: "🦅\nאֵיךְ קוֹרְאִים לַנָּהָר שֶׁעוֹבֵר בְּתֵל אָבִיב?", correctAnswer: "הַיַּרְקוֹן", distractors: ["הַיַּרְדֵּן", "הַנִּילוּס", "הַכִּנֶּרֶת"]),
        BankQuestion(prompt: "🛶\nאֵיךְ קוֹרְאִים לַנָּהָר שֶׁמַּפְרִיד בֵּין יִשְׂרָאֵל לְיַרְדֵּן?", correctAnswer: "הַיַּרְדֵּן", distractors: ["הַיַּרְקוֹן", "הַנִּילוּס", "הַכִּנֶּרֶת"]),
        BankQuestion(prompt: "🐻\nבְּאֵיזֶה מָקוֹם יֵשׁ הַרְבֵּה עֵצִים גְּבוֹהִים וְחַיּוֹת בָּר?", correctAnswer: "הַיַּעַר", distractors: ["הַמִּדְבָּר", "הָעִיר", "הַחוֹף"]),
        BankQuestion(prompt: "🇯🇵\nבְּאֵיזוֹ אֶרֶץ הַשֶּׁמֶשׁ עַל הַדֶּגֶל וְאוֹכְלִים סוּשִׁי?", correctAnswer: "יָפָּן", distractors: ["יִשְׂרָאֵל", "אִיטַלְיָה", "מֶקְסִיקוֹ"]),
        BankQuestion(prompt: "🏛️\nמַהִי בִּירַת יָוָן?", correctAnswer: "אַתּוּנָה", distractors: ["רוֹמָא", "קָהִיר", "פָּרִיז"]),
        BankQuestion(prompt: "🌐\nכַּמָּה יַבָּשׁוֹת יֵשׁ בָּעוֹלָם?", correctAnswer: "שֶׁבַע", distractors: ["שָׁלוֹשׁ", "חָמֵשׁ", "עֶשֶׂר"]),
        BankQuestion(prompt: "🏜️\nאֵיךְ קוֹרְאִים לַמִּדְבָּר הַגָּדוֹל שֶׁבְּדָרוֹם יִשְׂרָאֵל?", correctAnswer: "הַנֶּגֶב", distractors: ["הַגָּלִיל", "הַשָּׁרוֹן", "הַכַּרְמֶל"]),
        BankQuestion(prompt: "🕌\nבְּאֵיזוֹ עִיר נִמְצָא הַכֹּתֶל הַמַּעֲרָבִי?", correctAnswer: "יְרוּשָׁלַיִם", distractors: ["תֵּל אָבִיב", "אֵילַת", "חֵיפָה"]),
        BankQuestion(prompt: "🐫\nבְּאֵיזוֹ יַבֶּשֶׁת נִמְצָא מִדְבַּר הַסַּהָרָה הָעֲנָק?", correctAnswer: "אַפְרִיקָה", distractors: ["אֵירוֹפָּה", "אַסְיָה", "אוֹסְטְרַלְיָה"]),
        BankQuestion(prompt: "❄️\nאֵיךְ קוֹרְאִים לַמָּקוֹם הֲכִי קַר בָּעוֹלָם עִם הַרְבֵּה קֶרַח?", correctAnswer: "הַקֹּטֶב", distractors: ["הַמִּדְבָּר", "הַיַּעַר", "הֶחָוָה"]),
    ]

    static let money: [BankQuestion] = [
        BankQuestion(prompt: "🪙🪙🪙🪙🪙\nחָמֵשׁ מַטְבְּעוֹת שֶׁל 1 ₪ — כַּמָּה זֶה בְּיַחַד?", correctAnswer: "5 ₪", distractors: ["4 ₪", "6 ₪", "10 ₪"]),
        BankQuestion(prompt: "🪙🪙🪙\nשָׁלוֹשׁ מַטְבְּעוֹת שֶׁל 2 ₪ — כַּמָּה זֶה בְּיַחַד?", correctAnswer: "6 ₪", distractors: ["3 ₪", "5 ₪", "8 ₪"]),
        BankQuestion(prompt: "🍎\nתַּפּוּחַ עוֹלֶה 3 ₪ וְשִׁלַּמְתָּ עִם 10 ₪. כַּמָּה עֹדֶף?", correctAnswer: "7 ₪", distractors: ["5 ₪", "6 ₪", "8 ₪"]),
        BankQuestion(prompt: "🥛\nשָׁתִית חָלָב בְּ-4 ₪ וְשִׁלַּמְתָּ עִם 5 ₪. כַּמָּה עֹדֶף?", correctAnswer: "1 ₪", distractors: ["2 ₪", "3 ₪", "4 ₪"]),
        BankQuestion(prompt: "🍦\nגְּלִידָה עוֹלָה 8 ₪ וְשִׁלַּמְתָּ עִם 10 ₪. כַּמָּה עֹדֶף?", correctAnswer: "2 ₪", distractors: ["1 ₪", "3 ₪", "4 ₪"]),
        BankQuestion(prompt: "🪙\nכַּמָּה מַטְבְּעוֹת שֶׁל 2 ₪ צָרִיךְ כְּדֵי לְהַגִּיעַ לְ-10 ₪?", correctAnswer: "5", distractors: ["2", "3", "10"]),
        BankQuestion(prompt: "💧\nמַה מֵאֵלֶּה הוּא 'צֹרֶךְ' חָשׁוּב לַגּוּף?", correctAnswer: "מַיִם לִשְׁתּוֹת", distractors: ["מַחְשֵׁב מִשְׂחָק", "סֻכָּרִיָּה גְּדוֹלָה", "כּוֹבַע מַצְחִיק"]),
        BankQuestion(prompt: "🎮\nמַה מֵאֵלֶּה הוּא 'רָצוֹן' וְלֹא 'צֹרֶךְ'?", correctAnswer: "מִשְׂחָק מַחְשֵׁב חָדָשׁ", distractors: ["נַעֲלַיִם לָלֶכֶת", "אֹכֶל בָּרִיא", "מָקוֹם חַם לִישֹׁן"]),
        BankQuestion(prompt: "🐷\nמָה הֲכִי טוֹב לַעֲשׂוֹת עִם כֶּסֶף שֶׁקִּבַּלְתָּ וְלֹא צָרִיךְ עַכְשָׁו?", correctAnswer: "לָשִׂים בְּקֻפַּת הַחִסָּכוֹן", distractors: ["לְבַזְבֵּז הַכֹּל מִיָּד", "לְאַבֵּד אוֹתוֹ", "לִזְרֹק לַפַּח"]),
        BankQuestion(prompt: "🏷️\nאוֹתוֹ סֵפֶר עוֹלֶה 8 ₪ בַּחֲנוּת אַחַת וְ-6 ₪ בַּחֲנוּת הַשְּׁנִיָּה. אֵיפֹה זוֹל יוֹתֵר?", correctAnswer: "בְּ-6 ₪", distractors: ["בְּ-8 ₪", "אוֹתוֹ מְחִיר", "אִי אֶפְשָׁר לָדַעַת"]),
        BankQuestion(prompt: "🍪\nעוּגִיָּה עוֹלָה 2 ₪. כַּמָּה יַעֲלוּ שָׁלוֹשׁ עוּגִיּוֹת?", correctAnswer: "6 ₪", distractors: ["4 ₪", "5 ₪", "8 ₪"]),
        BankQuestion(prompt: "💰\nחָסַכְתָּ 3 ₪ וְקִבַּלְתָּ עוֹד 2 ₪. כַּמָּה יֵשׁ לְךָ עַכְשָׁו?", correctAnswer: "5 ₪", distractors: ["1 ₪", "4 ₪", "6 ₪"]),
        BankQuestion(prompt: "🤝\nשָׁלוֹשׁ עוּגוֹת לְ-3 יְלָדִים. כַּמָּה מְקַבֵּל כָּל אֶחָד בְּחֲלוּקָה הוֹגֶנֶת?", correctAnswer: "עוּגָה אַחַת", distractors: ["שְׁתֵּי עוּגוֹת", "שָׁלוֹשׁ עוּגוֹת", "אַף עוּגָה"]),
        BankQuestion(prompt: "🪙\nאֵיזֶה מַטְבֵּעַ שָׁוֶה פָּחוֹת — 1 ₪ אוֹ 5 ₪?", correctAnswer: "1 ₪", distractors: ["5 ₪", "שְׁנֵיהֶם שָׁוִים", "אִי אֶפְשָׁר לָדַעַת"]),
        BankQuestion(prompt: "📋\nתִּכְנַנְתָּ לִקְנוֹת 3 דְּבָרִים אֲבָל הַכֶּסֶף מַסְפִּיק רַק לִשְׁנַיִם. מָה כְּדַאי?", correctAnswer: "לִבְחֹר אֶת שְׁנֵי הַדְּבָרִים הֲכִי חֲשׁוּבִים", distractors: ["לִקְנוֹת רַק אֶת הַיָּקָר בְּיוֹתֵר", "לְוַתֵּר עַל הַכֹּל וְלָלֶכֶת", "לִקְנוֹת אֶת הַזּוֹל בְּיוֹתֵר בִּלְבַד"]),
        BankQuestion(prompt: "🍇\nאֶשְׁכּוֹל עֲנָבִים עוֹלֶה 5 ₪ וְשִׁלַּמְתָּ עִם 5 ₪. כַּמָּה עֹדֶף?", correctAnswer: "0 ₪", distractors: ["1 ₪", "2 ₪", "5 ₪"]),
        BankQuestion(prompt: "🐖\nבְּקֻפַּת הַחִסָּכוֹן יֵשׁ 6 ₪ וְהוֹצֵאתָ 2 ₪. כַּמָּה נִשְׁאַר?", correctAnswer: "4 ₪", distractors: ["2 ₪", "6 ₪", "8 ₪"]),
        BankQuestion(prompt: "🎁\nרָצִיתָ מַתָּנָה בְּ-12 ₪ אֲבָל יֵשׁ לְךָ רַק 9 ₪. מָה כְּדַאי לַעֲשׂוֹת?", correctAnswer: "לַחְסֹךְ עוֹד קְצָת עַד שֶׁיַּסְפִּיק", distractors: ["לְחַפֵּשׂ מַתָּנָה זוֹלָה יוֹתֵר בְּ-9 ₪", "לְוַתֵּר וְלֹא לִקְנוֹת מַתָּנָה", "לְבַקֵּשׁ מַתָּנָה יְקָרָה עוֹד יוֹתֵר"]),
        BankQuestion(prompt: "🪙🪙\nמַטְבֵּעַ שֶׁל 5 ₪ וְעוֹד מַטְבֵּעַ שֶׁל 2 ₪ — כַּמָּה זֶה בְּיַחַד?", correctAnswer: "7 ₪", distractors: ["3 ₪", "6 ₪", "10 ₪"]),
        BankQuestion(prompt: "🧺\nאִמָּא נְתָנָה לְךָ 10 ₪ רַק לְפֵרוֹת. מָה נָכוֹן לַעֲשׂוֹת?", correctAnswer: "לִקְנוֹת פֵּרוֹת בַּכֶּסֶף הַזֶּה", distractors: ["לִקְנוֹת בּוֹ צַעֲצוּעַ", "לִקְנוֹת בּוֹ סֻכָּרִיּוֹת", "לְהַחְבִּיא אֶת הַכֶּסֶף"]),
        BankQuestion(prompt: "🍭\nסֻכָּרִיָּה עוֹלָה 1 ₪. כַּמָּה יַעֲלוּ אַרְבַּע סֻכָּרִיּוֹת?", correctAnswer: "4 ₪", distractors: ["2 ₪", "3 ₪", "5 ₪"]),
        BankQuestion(prompt: "💝\nלַחֲבֵרָה אֵין כֶּסֶף לְמִיץ וּלְךָ יֵשׁ קְצָת יוֹתֵר. מָה נֶחְמָד לַעֲשׂוֹת?", correctAnswer: "לְשַׁתֵּף אוֹתָהּ וְלִקְנוֹת מִיץ לִשְׁנֵיכֶם", distractors: ["לִקְנוֹת מִיץ רַק לְעַצְמְךָ", "לִשְׁמֹר אֶת הַכֶּסֶף לְמָחָר", "לוֹמַר שֶׁאֵין לְךָ כֶּסֶף"]),
        BankQuestion(prompt: "🪙\nכַּמָּה מַטְבְּעוֹת שֶׁל 1 ₪ שָׁווֹת לְמַטְבֵּעַ אֶחָד שֶׁל 2 ₪?", correctAnswer: "2", distractors: ["1", "3", "5"]),
        BankQuestion(prompt: "🛒\nיֵשׁ לְךָ 8 ₪ וְקָנִיתָ דָּבָר בְּ-3 ₪. כַּמָּה כֶּסֶף נִשְׁאַר לְךָ?", correctAnswer: "5 ₪", distractors: ["3 ₪", "4 ₪", "6 ₪"]),
        BankQuestion(prompt: "💡\nמָה הַמַּשְׁמָעוּת שֶׁל לַחְסֹךְ כֶּסֶף?", correctAnswer: "לִשְׁמֹר קְצָת כֶּסֶף בְּמָקוֹם לְבַזְבֵּז הַכֹּל", distractors: ["לְבַזְבֵּז אֶת הַכֹּל מַהֵר", "לָתֵת אֶת כָּל הַכֶּסֶף", "לְאַבֵּד אֶת הַכֶּסֶף"]),
        BankQuestion(prompt: "🎪\nכַּרְטִיס לְהַצָּגָה עוֹלֶה 9 ₪ וְשִׁלַּמְתָּ עִם 10 ₪. כַּמָּה עֹדֶף?", correctAnswer: "1 ₪", distractors: ["2 ₪", "3 ₪", "0 ₪"]),
        BankQuestion(prompt: "⚖️\nמָה עֹדֵף לִקְנוֹת קֹדֶם כְּשֶׁיֵּשׁ מְעַט כֶּסֶף?", correctAnswer: "דָּבָר שֶׁאֲנַחְנוּ בֶּאֱמֶת צְרִיכִים", distractors: ["דָּבָר שֶׁרַק רוֹצִים לְרֶגַע", "הַדָּבָר הֲכִי יָקָר בַּחֲנוּת", "שׁוּם דָּבָר אַף פַּעַם"]),
    ]

}
